### ISSUE TITLE
Node #06: Selecting Audio card results in a malformed activity

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder-Samples#1002]
## Sample information
1. Sample type: samples\
2. Sample language: nodejs
3. Sample name: 06.using-cards

## Describe the bug
Selecting Audio Card from the choice prompt results in an error due to a malformed activity.

## Screenshots:
Webchat in Ibiza portal:
![audio_card_results_in_error](https://user-images.githubusercontent.com/14935595/49349324-f3a78180-f65e-11e8-8aca-1ca2afb0dd4a.jpg)

The logstream in the Ibiza portal:
![logstream](https://user-images.githubusercontent.com/14935595/49349331-f6a27200-f65e-11e8-82cf-5809eae12269.jpg)

## Additional Context:
This is with the 4.1.5 release of the botbuilder-js SDKs.
[bug]

**Comment by sgellock** [comment]
can't repo
