### ISSUE TITLE
[csharp_dotnetcore][14.nlp-with-dispatch] Duplicate Readme tools install causes errors

### ISSUE THREAD

**Issue by DanDev33** [Microsoft/BotBuilder-Samples#1007]
## Describe the bug
tools install produces Failure message "luisgen is already installed".

## To Reproduce
1. #install-botbuilder-tools section has npm list of tools to install.
2. #deploy-this-bot-to-azure-and-configure-services one step below has user install same list but expanded with chatdown and luisgen - this FAILs , with message luisgen is already installed.

## Suggested behavior
Add chatdown to top list, remove bottom list and instead add a pointer back to list in #install-botbuilder-tools.

**Comment by sgellock** [comment]
PR #1200 contains the fix
