### ISSUE TITLE
Unhandled exception in 12.nlp-with-luis sample

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotBuilder-Samples#1010]
## Sample information
1. Sample language: [dotnetcore]
2. Sample name: <12.nlp-with-luis>

## Describe the bug
Unhandled exception thrown at this line `var app = new LuisApplication(luis.AppId, luis.AuthoringKey, luis.GetEndpoint());` in the `BotServices` constructor. 

## To Reproduce
1. Add service reference using the following command:
`msbot connect luis -n LuisBot --appId 354d5b24-707b-4fb9-b76d-f991177eb4ab --region westus --authoringKey xxxxx --version "v0.1"`

2. The service reference is added successfully, as shown below:
{
  "type": "luis",
  "name": "LuisBot",
  "appId": "xxxx",
  "version": "v0.1",
  "authoringKey": "xxx",
  "region": "westus",
  "id": "178"
}
3. Build and run the sample.
4. Open the .bot file in the Emulator, and you'll get the exception.

The reason for the exception is that after running the `msbot connect service` command, there are now two service references in the bot file. The original service reference in the bot file does not have values set, see below. 

{
    "type": "luis",
    "name": "",
    **"appId": "",**
    **"authoringKey": "",**
    "subscriptionKey": "",
    "version": "0.1",
    "region": "",
    "id": "34"
},

## Expected behavior
.bot files should not contain entries that causes the bot to fail. 

[bug]

**Comment by Diruuo** [comment]
Could you show your entire .bot file for reference? Also what version of the Bot Emulator are you using? 

I am unable to reproduce this.
