### ISSUE TITLE
Neither LUIS sample demonstrates use of entities

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#1020]
## Sample information
1. samples
2. JS/TS
3. 12.nlp-with-luis and 21.luis-with-appinsights

## Describe the bug
The LUIS sample should demonstrate how to give a bot NLP capabilities. LUIS effectively returns two things: intents and entities. Entities are fairly core to NLP, but these samples don't illustrate how you use them. To make matters worse, the entities property returned by LUIS is untyped, so intellisense won't help a developer understand how to use them (see https://github.com/Microsoft/botbuilder-js/issues/682)

## To Reproduce
1. Run the LUIS sample

[bug]

**Comment by sgellock** [comment]
@ryanvolum would be good to be consistent with feedback.  In some instances the feedback has been that a sample should contain 1 concept and 1 concept only.  this feedback would imply differently.

**Comment by ryanvolum** [comment]
@sgellock I think samples should contain the minimum necessary components to explain a concept. As an example, having state in the "welcoming a user" sample seems a bit superfluous, and may lead developers to believe that the botbuilder's state API is somehow necessary in welcoming a user. 

In this case, the sample is intended to demonstrate the use of NLP in a bot. I would argue (as I imagine the LUIS team would) that the minimum components necessary in demonstrating NLP are the use of intents and of entities. This is not just idiomatic - how you use an entity often depends on what intent was triggered, as with: 

setAlarm: Book me an alarm at **3:00PM** 
cancelAlarm: Cancel my alarm at **3:00PM** 

Without intent, "3:00PM" doesn't give your bot enough information to take action. 

The main issue right now is that no sample covers the use of entities, and given https://github.com/Microsoft/botbuilder-js/issues/682, intellisense isn't going to help. Either extending the current sample or creating another sample to demonstrate the use of entities would satisfy this issue. Given the above example, I'd lean towards the former.

**Comment by sgellock** [comment]
The updated CoreBot sample that will be released as part of the samples-work-in-progress branch, eta, after LA Open Hack, will address this.
