### ISSUE TITLE
Need subscription key removed from qnamaker .bot

### ISSUE THREAD

**Issue by ivorb** [Microsoft/BotBuilder-Samples#1026]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: 11. qna-maker

## Describe the bug
Need subscription key removed from .bot file. Isn't currently in docs and user has found it needs to be removed from the bot file for it to work when he ran it

https://github.com/MicrosoftDocs/bot-docs/issues/559

[bug]

**Comment by jwiley84** [comment]
That is very strange that they cannot run the bot when the key is there. While I've done some quick repro-testing, and it is true that the subscription key is non-essential, I've never had an issue when it IS there. That being said, I wonder if this is the underlying issue with [this](https://github.com/Microsoft/botbuilder-tools/issues/815). Can you get the exact error from the customer?

**Comment by jwiley84** [comment]
Closing for lack of response. If you can get the customer's exact error, please reopen this issue.
