### ISSUE TITLE
qna-with-appinsights

### ISSUE THREAD

**Issue by bindualapati** [Microsoft/BotBuilder-Samples#1041]
i have this constant in my index.js file - 
const { ApplicationInsightsTelemetryClient, ApplicationInsightsWebserverMiddleware } = require('applicationinsights');

error message when i run the bot -
const appInsightsClient = new ApplicationInsightsTelemetryClient(appInsightsConfig.instrumentationKey);
                          ^

TypeError: ApplicationInsightsTelemetryClient is not a constructor

**Comment by jwiley84** [comment]
This is occurring in javascript_node sample #20.

**Comment by jwiley84** [comment]
![errorai](https://user-images.githubusercontent.com/17333688/49611095-66fa0d80-f955-11e8-816f-10b5e2c562da.png)

**Comment by benbrown** [comment]
This is because the package is pointing at applicationinsights instead of botbuilder-applicationinsights, because botbuilder-applicationinsights is not public yet.

@sgellock what's your take on this? should we roll this all the way back and restore my branch and not re-merge until 4.2 is published?  or fix this now?

**Comment by sgellock** [comment]
Samples are like apps to customers.  They need to run 100% of the time.

So as a principle, we should back this out until 4.2 is out the door.

**Comment by daveta** [comment]
I tested (with a patched sample, that includes the new Application Insights package).  Seems to work now.  Sample will take a few tweaks.

**Comment by benbrown** [comment]
https://github.com/Microsoft/BotBuilder-Samples/pull/1054

**Comment by jwiley84** [comment]
I'll run a quick test, let you know if goes funky.

**Comment by jwiley84** [comment]
So the first (and ONLY the first, was never able to repro it) time I ran each appInsight sample, I got the following error: 
![weirderror](https://user-images.githubusercontent.com/17333688/49678082-0a6f1f00-fa37-11e8-9395-76de864a6766.png)

**Comment by jwiley84** [comment]
Sorry I didn't see this reply! I only saw it once, and had no problems with my bots. I just thought it was weird.

**Comment by benbrown** [comment]
@jwiley84 👍
