### ISSUE TITLE
Add examples of utilizing the Confidence Scores and Active Learning elements of the QnAMaker Service

### ISSUE THREAD

**Issue by Diruuo** [Microsoft/BotBuilder-Samples#1042]
**Is your feature request related to a problem? Please describe.**
The QnAMaker-related samples make no mention of how to utilize the Score, or the Active Learning or other functionality of the QnAMaker service. The samples that exist in other places are incomplete/outdated/not functional. 

**Describe the solution you'd like**
I would prefer it if either the 11.qnamaker sample or perhaps one of the more advanced bot samples included instructions on how to achieve this. 51.cafe-bot includes a variable related to this (`public const double QnaConfidenceThreshold = 0.5;`) but it is not used anywhere in the project. 

**Describe alternatives you've considered**
I've tried to follow the samples [here](https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/CSharp/Samples/QnAMaker) but those samples have no mention of the .bot files or the more modern way of defining these services. The link for QnA Maker documentation (not preview) also mentions [confidence score](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/confidence-score) but nowhere in the documentation is it explained how to adjust this. 

[enhancement]

**Comment by sgellock** [comment]
@Diruuo PR #1161 should address this request for you.

**Comment by Diruuo** [comment]
@sgellock Perfect, thank you!
