### ISSUE TITLE
Unclear how I get the secret to my .bot file when I use Azure Portal first experience

### ISSUE THREAD

**Issue by drub0y** [Microsoft/BotBuilder-Samples#1043]
If I use the Azure Portal to create a V4 bot (any language) it will create a `.bot` file and a secret key which it uses to encrypt all the related secrets in the file. Then I download the project and try to run it locally, but I don't have the secret yet so I can't and then there is no clear/easy way to go get the secret.

The answer is you have to go get it from the App Settings of the Web App that was created for your bot, but how is the developer supposed to know that? I didn't see this in the docs, but maybe I missed it? Even if it is documented, this seems like a really rough roadblock in the getting started experience. Part of me wants to recommend not applying a secret to the bot in this scenario to reduce the friction. However, this is a risky decision because then the `.bot` file is up in the cloud with secrets that aren't encrypted and if this ends up being their production instance that wouldn't be... errr... "good".  🤔

Maybe the answer is just better/more explicit documentation around how getting the bot secret value in this scenario? Maybe the `az cli` extension could have an explicit command for fetching the app setting by the well known name?

**Comment by sgellock** [comment]
Moving this to the samples repo where it will get the attention it needs.  this is a doc issue, plus there is a broader discussion around .bot file encryption, developer experience, and the fact that I don't want .bot files encrypted by default.  I want a "Things to consider when deploying to production" doc that introduces this concept as well as key vault, etc.  the friction introduced by encrypting this out of the gate is way too painful.

this will also require ABS Portal work which can't get done for the 4.2 release.

**Comment by sgellock** [comment]
@Kaiqb has this covered in the C# deployment doc.  NodeJS is coming and is planned for the 4.2 release

**Comment by sgellock** [comment]
now addressed in the nodejs deployment docs
