### ISSUE TITLE
This template depends on flat-map-stream, which is a security concern right now!

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1044]
**Is your feature request related to a problem? Please describe.**
(Copied from bot-docs: issue [596](https://github.com/MicrosoftDocs/bot-docs/issues/596). Quoted below.)

**Describe the solution you'd like**
Remove reference to flat-map-stream package.

**Describe alternatives you've considered**
Quoted issue from @kraghavk.

>The project generated by botbuilder mentioned here has a dependency on flat-map-stream package and this package cannot be trusted anymore. See npm audit output below:
```text
                   === npm audit security report ===


                             Manual Review

         Some vulnerabilities require your attention to resolve

      Visit https://go.npm.me/audit-guide for additional guidance

Critical Malicious Package

Package flatmap-stream

Patched in No patch available

Dependency of nodemon [dev]

Path nodemon > pstree.remy > ps-tree > event-stream >flatmap-stream

More info https://nodesecurity.io/advisories/737

found 1 critical severity vulnerability in 2920 scanned packages
1 vulnerability requires manual review. See the full report for details.
```
> Hope MS will fix this dependency soon.

[enhancement]

**Comment by sgellock** [comment]
a fix for this has been merged into master.  generator-botbuilder v 4.1.20 or higher will have the fix when it is published
