### ISSUE TITLE
FileNotFound running sample

### ISSUE THREAD

**Issue by dwhiteddsoft** [Microsoft/BotBuilder-Samples#1056]
## Sample information
1. Sample type: \samples\ 
2. Sample language: dotnetcore 
3. Sample name: 07.using-adaptive-cards

## Describe the bug
This occurs running Visual Studio on OSX. When running the sample it throws an error. After putting in some error handling the error is System.IO.FileNotFound. This error occurs in CreateAdaptiveCardAttachment  on tis line:
            var adaptiveCardJson = File.ReadAllText(filePath);
To make it work I changed it to this but not sure if this is how you want to fix it:
            var adaptiveCardJson = File.ReadAllText(filePath.Replace("\\","/"));

## To Reproduce
1. Download sample on OSX
2. Run
3. test in bot emulator
4. type anything
5. encounter error

## Expected behavior
The bot should not throw and error and should show a random card

[bug]

**Comment by sgellock** [comment]
@dwhiteddsoft thanks for the logging the issue.  the proper fix is to use Path.Combine when building file paths.  I just merged PR #1164 which contains the fix.
