### ISSUE TITLE
Direct line v3 - reply to bot on Attachment having buttons on it.

### ISSUE THREAD

**Issue by amitkumar3968** [Microsoft/BotBuilder-Samples#106]
Hi ALL,

I making project of hitting MS bot via Direct Line Api V3.
direct line is enabled.
token is generating.
communicationg via websocket url .
then able to post message back via Direct line v3 post method.
now , problem is , that, how to post json response  back, if bot earlier messaged me, having hero card with buttons 
on it .

I am not able to post button action via Direct line post api.

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
