### ISSUE TITLE
VSIX needs better category & naming for supported Project Types

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotBuilder-Samples#1073]
![image](https://user-images.githubusercontent.com/20270743/49752325-e2fd9980-fc64-11e8-8b09-8b03e2e5d72a.png)

These should follow convention for other Azure services (if we're calling this the Azure Bot Service):
**Category**: Cloud
**Subcategory**: Azure Bot Service
**Name**: `Echo Bot`, `Empty Bot`

**Comment by cleemullins** [comment]
@yochay to get improved / fancy / descdriptions for the templates as well.

**Comment by cleemullins** [comment]
This has been resolved, exactly as @brandonh-msft has called out. The revised VSIX was pushed to the Visual Studio Marketplace yesterday.
