### ISSUE TITLE
C# nlp-with-dispatch calls for wrong key

### ISSUE THREAD

**Issue by jwiley84** [Microsoft/BotBuilder-Samples#1076]
csharp_dotnetcore #14 nlp-with-dispatch bot throws an error if the dispatch service in the .bot file doesn't have a subscriptionKey. Except dispatch services don't have subscription keys, only authoring keys. This error needs to be changed to ask for authoringKey instead. 

![dispatch error](https://user-images.githubusercontent.com/17333688/49820424-b1500580-fd2c-11e8-9842-3b2df80497bf.png)

**Comment by stevengum** [comment]
The [DispatchService can contain a SubscriptionKey](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs#L11). When the Dispatch entry in the bot file is created, only the AuthoringKey is required, not the optional SubscriptionKey. This can lead to no "subscriptionKey" entry being added to the .bot file. 

![msbot-connect-dispatch-4 3 2-134](https://user-images.githubusercontent.com/14935595/50922266-f1270d00-13fe-11e9-89aa-a012674fe2e0.jpg)


The Node.js sample uses the authoringKey for the [DispatchService ](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/14.nlp-with-dispatch/bot.js#L44-L45)and the [LuisServices](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/14.nlp-with-dispatch/homeAutomation.js#L46-L47), so the samples need to be brought into alignment. 

@sgellock, I'm thinking that we should follow the Node.js sample's lead and have the bot use the authoring key, but add a comment indicating that's only for prototyping.
