### ISSUE TITLE
Consider using fat arrow functions instead of binding functions in waterfall dialog samples

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#1077]
Waterfall dialogs take an array of functions to step through on each step. The samples that cover this (e.g. [04.simple-prompt](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/04.simple-prompt)) use functions from the same class and bind them in order to pass them in. This practice was fairly common among the React community early on, but is fairly hard to look at/grok: 

```
        // Create a dialog that asks the user for their name.
        this.dialogs.add(new WaterfallDialog(WHO_ARE_YOU, [
            this.askForName.bind(this),
            this.collectAndDisplayName.bind(this)
        ]));
```
Most React developers now lean towards using fat arrow functions to resolve the binding confusion. In this case, if `askForName` was declared as a fat arrow function: 
```
    public askForName = async (dc) => {
        await dc.prompt(NAME_PROMPT, `What is your name, human?`);
    }
```
instead of: 
```
    async askForName(dc) {
        await dc.prompt(NAME_PROMPT, `What is your name, human?`);
    }
```

Then we could declare our waterfall dialog like: 
```
        this.dialogs.add(new WaterfallDialog(WHO_ARE_YOU, [
            this.askForName,
            this.collectAndDisplayName
        ]));
```
which is far less confusing.

See [this medium article](https://medium.com/@nikolalsvk/loosing-bind-this-in-react-8637ebf372cf) for reference.

Consider changing samples that use waterfall dialogs to using fat arrows to avoid `this` confusion. 

[enhancement]

**Comment by benbrown** [comment]
Thank you for the feedback! We'll keep this in mind as we revise the samples.
