### ISSUE TITLE
Return heroCard in blog-LUISActionBinding

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotBuilder-Samples#108]
Hello,
I'm wondering how I can return a herocard in the fulfill function in the ActionBinding framework? The examples are all strings in the callback. For example, in the WeatherInPlaceAction, I want to show a sunny picture with temperature instead of just a sentence. Really appreciate your help!

Yan

**Comment by HelloJyo** [comment]
Did you get it? Can you share some info how you make it work?

**Comment by pcostantini** [comment]
Please take a look at this comment:
https://github.com/Microsoft/BotBuilder-Samples/issues/155#issuecomment-313703804
