### ISSUE TITLE
VSIX templates still utilize obsoleted BotFrameworkOptions::State property

### ISSUE THREAD

**Issue by drub0y** [Microsoft/BotBuilder-Samples#1080]
The VSIX templates (currently 4.1.8) haven't yet been updated for 4.2 API changes which included [obseleting the `BotFrameworkOptions::State` property](https://github.com/Microsoft/botbuilder-dotnet/issues/1100). This results in build warnings right after a File->New Project experience which could obviously be a little confusing while also propagating the obsoleted pattern we want developers to move away from.

**Comment by sgellock** [comment]
A number of the csharp_dotnetcore samples are also using this deprecated method.

**Comment by paulomorgado** [comment]
In the meantime, what's the correct substitution for the deprecated property?

**Comment by Opilio22** [comment]
Not sure if this is the appropiate solution, but here is what I did:
I moved them out of the services.AddBot registration. Making them accessible for my Accessors.       

        public void ConfigureServices(IServiceCollection services)
        {
            IStorage dataStore = new MemoryStorage();

            var conversationState = new ConversationState(dataStore);
            var userState = new UserState(dataStore);

            services.AddBot<EchoBot1Bot>(options =>
            {
             ...
            }

            services.AddSingleton<EchoBot1Accessors>(sp =>
            {
             ...
            }
         }

**Comment by drub0y** [comment]
What @Opilio22 is suggesting is the correct way to go; you just need to utilize the proper language features.

In this case, you want to increase the scope of the various state variables to the `ConfigureServices` method so they are accessible to the closure for `AddBot<YourBot>` as well as any other number of `AddXXX` calls you make where they might be needed.

**Comment by cleemullins** [comment]
I've updated the VSIX, and tested. The test team is doing a regression now and I'll push to the Marketplace as soon as they're done. Version is 4.2.2.
