### ISSUE TITLE
[Question] Store user data

### ISSUE THREAD

**Issue by jerrak0s** [Microsoft/BotBuilder-Samples#109]
I am trying to store some user data for a bot but I cannot find the right way. I used a .txt file and this method works but when I upload the project all the users that will use the bot, will share the same file and I don't want to do that. I want to store some settings for every different user that will use the bot and keep these settings for ever.
I tried Stateclient and GetUserData but the stored values are disappearing. I am doing something wrong ? 
How can I implement this?

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue, and specify if you are using .NET or Node SDK, on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
