### ISSUE TITLE
Remove or fix 11.qnamaker sample.qna file

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1100]
## Sample information
1. Sample type: [samples]
2. Sample language: [dotnetcore] and [nodejs]
3. Sample name: 11.qnamaker

## Describe the bug
The CognitiveModels/sample.qna file is no longer part of the process outlined in the README. In addition, the sample.qna file for the dotnetcore and nodejs sample is poorly formed JSON (missing commas).

## To Reproduce
1. Try to figure out why these files are part of these projects.

## Expected behavior
- No extraneous files should be included in the samples.
- Any files included should be properly formed.

## Additional context
- These files are also in the dotnetwebapi and typescript samples, but those are properly formed.
- The link to the dotnetwebapi sample is broken on the repo's landing page.

[bug]

**Comment by sgellock** [comment]
Fixed with PR #1103
