### ISSUE TITLE
[webapi][13.basic bot] Unable to connect to LUIS service

### ISSUE THREAD

**Issue by jasonchuah4** [Microsoft/BotBuilder-Samples#1101]
## Describe the issues
Unable to connect to the LUIS service, would return http 500 error in Bot Emulator

## To Reproduce
1. Launch the [webapi] 13.basic bot code in Visual Studio.
2. Head to MainDialog.cs line 85 `var luisResults = await _services.LuisServices[LuisKey].RecognizeAsync(dc.Context, cancellationToken).ConfigureAwait(false);`. Put a break point on this line.
3. Press F5 to startup the IIS Server.
4. Go to Bot Emulator, open the .bot file and start a conversation. By right an interactive card (refer to screenshot below) would display too whenever a fresh conversation is started, but it doesn't show anything. Type anything in it and wait for it to hit the breakpoint.
5. Once breakpoint is hit, click Step Into (F11), you would see it is stuck at there for an infinite amount of time.

## Expected behavior
I tested on .NET Core, interactive card is displayed and it is able to process my conversation normally, but not in webapi.

## Screenshots
[https://prnt.sc/lxaygm](https://prnt.sc/lxaygm)

[issue]

**Comment by dmvtech** [comment]
I do not get the exact same error message, but I get an error on the same line. Currently investigating.

**Comment by dmvtech** [comment]
My error was related to my bot file. I am unable to reproduce the issue you are seeing.

I found some other issues that might be [related](https://github.com/Microsoft/BotFramework-Emulator/issues/301). Can you check to make sure you have the newest version of ngrok (i'm running ngrok version 2.2.8) as well as checking to see if you have any proxy servers in the mix?

**Comment by CoHealer** [comment]
@jasonchuah4, can you confirm this is still an issue for you?

**Comment by dmvtech** [comment]
Closing as we have not heard back on if this issue is still occurring or if updating ngrok has resolved the issue. Please reopen if the issue continues to block.
