### ISSUE TITLE
[Docs] v3 Add authentication to your bot via Azure Bot Service banner to doesn't point to v4 version

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#1102]
## Describe the bug
SEO on Azure Bot Service Give a clear and concise description of what the bug is.

## To Reproduce
1. Google search for "azure bot service oauth connection settings"
2. Click on top result, titled "Add authentication to your bot via Azure Bot Service - Microsoft Docs"
3. This navigates to "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0"
4. Click on the v4 link in the banner "This topic applies to SDK v3 release. You can find the documentation for the latest version of the SDK v4 here."
5.  You are navigated to the root v4 docs page

## Expected behavior
Be navigated to the v4 version of "Add authentication to your bot via Azure Bot Service"
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp

[bug]

**Comment by Kaiqb** [comment]
I have changes the SEO for the v3 doc. Once search engines crawl the site, we shouldn't see v3 version on the top.
