### ISSUE TITLE
NLP-with-Luis

### ISSUE THREAD

**Issue by btk15** [Microsoft/BotBuilder-Samples#1107]
## Describe the bug
I want to run the sample: samples/javascript_nodejs/12.nlp-with-luis
There are no clear instructions on how to do this. The current documentation is outdated.

## To Reproduce
1. Go to https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/12.nlp-with-luis/README.md
2. Click on Required Prerequisites, which takes you to https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/12.nlp-with-luis/PREREQUISITES.md
3. Follow Guide
4. Run this command: az extension add -n botservice
5. See error: No matching extensions for 'botservice'. Use --debug for more information.

## Expected behavior
The guide should be updated so that people know how to run the sample. botservice has been removed from the list of extensions but is needed by MSBot CLI tool. So what are we supposed to do?

[bug]

**Comment by a-b-r-o-w-n** [comment]
Hi @btk15, is it possible that you are not on the latest version of the azure cli? I just followed the steps in the guide and was able to install the extension without any issues.

**Comment by btk15** [comment]
Hi @a-b-r-o-w-n I am using azure-cli (2.0.54). How can you install botservice if I got a confirmation that it has been removed from the list of extensions. See here: https://github.com/Azure/azure-docs-cli-python/issues/1223

**Comment by a-b-r-o-w-n** [comment]
@btk15 It seems that I have cached extension list and was able to install `botservice`, however on a fresh VM, the extension is no longer available. I'll connect with my team and get back to you.

**Comment by sgellock** [comment]
I'll push up a PR that updates the PREREQUISITES.md.  but until I do, here is how you can fix this:
- install Azure CLI 2.0.54 (or higher)
- install msbot 4.3.2 (or higher)

**Comment by sgellock** [comment]
PR #1121 address updated pre-reqs

**Comment by nyuen** [comment]
FYI the instructions on the Readme are missing steps, you need to create to upload the Luis model and train the model.

you then need to update the bot config file and the index.js to enter the relevant information.

on my side the msbot command line from the Readme generated an invalid luis section
