### ISSUE TITLE
retryPrompt / retrySpeak no longer supported

### ISSUE THREAD

**Issue by bw-kforce-ms** [Microsoft/BotBuilder-Samples#1109]
Github issues for C#/JS

## Sample information
1. Sample type: /samples/04.simple-prompt
2. Sample language: nodejs (and C#)
3. Sample name: simple prompt

## Describe the bug
https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-cortana-skill?view=azure-bot-service-3.0

According to the old documentation, I can add retrySpeak for devices like Invoke. This behavior seems unavailable via V4 Prompts.

## To Reproduce
Build the bot. Add a retryPrompt (V4 way) AND retrySpeak (V3 way). Neither is spoken using an Invoke.
https://github.com/bw-kforce-ms/CortanaSkillsWIP/blob/master/Consumer/Node/V4Patches/04.simple-prompt.diff

## Expected behavior
Reprompts should work like they did in V3, or be documented for how its changed in V4.

## Additional context
Use the Invoke or Surface Headphones to test.

[bug]

**Comment by Zerryth** [comment]
Closing as per https://github.com/Microsoft/botbuilder-js/issues/711
