### ISSUE TITLE
[Question] How to send conversation data from bot to an email address

### ISSUE THREAD

**Issue by stelazh** [Microsoft/BotBuilder-Samples#111]
** if (message.Text.Equals("current city", StringComparison.InvariantCultureIgnoreCase))
            {
                string userCity;

                var city = context.ConversationData.Get<string>(ContextConstants.CityKey);

                if (context.PrivateConversationData.TryGetValue(ContextConstants.CityKey, out userCity))
                {
                    await context.PostAsync($"{userName}, you have overridden the city. Your searches are for things in  {userCity}. The default conversation city is {city}.");
                }
                else
                {
                    await context.PostAsync($"Hey {userName}, I'm currently configured to search for things in {city}.");

   context.ConversationData.SetValue(ContextConstants.UserNameKey, result);
                }
            } **

I want to send email from the bot  with the context of conversation data. Can you help me please ?
I want to

**Comment by Zelophobian** [comment]
I have a similar problem. I want to send the result of a waterfall conversation via email.
But I cannot get the cross-channel message to work.
Only answering on the specific channels seems to work.

Sorry for piggybacking.

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
