### ISSUE TITLE
Most C# Samples Don't Target 4.2.0

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/BotBuilder-Samples#1120]
## Sample information
Most [C# samples](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore) 

## Describe the bug
Issue https://github.com/Microsoft/botbuilder-dotnet/issues/1259 brought my attention to the SDK version that most of the C# samples are pointing to `4.1.5`.

This ofc means that sample bots will break on features that were implemented after `4.1.5`, such as in the issue linked above.

## Expected behavior
Give a clear and concise description of what you expected to happen.

Looking at the JS repo, the samples point to `4.2.0` dependencies. C# repo should do that same.

**Comment by stevengum** [comment]
@Zerryth, can you cut a PR to bump the versions and make sure the samples still build? Thanks!
