### ISSUE TITLE
[Question] CSharp/core-BasicMultiDialog: RootDialog.cs

### ISSUE THREAD

**Issue by ClownPrinceCS30** [Microsoft/BotBuilder-Samples#113]
Hey there, I've been trying to use your /CSharp/core-BasicMultiDialog/Dialogs/RootDialog.cs example and this.NameDialogResumeAfter and  this.AgeDialogResumeAfter in the SendWelcomeMessageAsync and  NameDialogResumeAfter methods are throwing errors? Do I need to pass parameters to them? line 37 and 46 btw

**Comment by ejadib** [comment]
What's the error you are getting? Code looks fine. What version of the BotBuilder SDK are u using?

**Comment by 37Stars** [comment]
The error is "Argument 2: cannot convert from 'method group' to 'ResumeAfter<string>'".

**Comment by ejadib** [comment]
I cannot reproduce the error, I just ran the sample and its working just fine. Are u updating the code somehow? Make sure to get the latest version of the code.

**Comment by JasonSowers** [comment]
Unable to reproduce as well, please reopen if you would like to continue the discussion.
