### ISSUE TITLE
Live agent hand-off sample

### ISSUE THREAD

**Issue by Avalaxy** [microsoft/BotBuilder-Samples#1133]
**Is your feature request related to a problem? Please describe.**
There are no official samples for how to implement live agent hand-off with Bot V4.

**Describe the solution you'd like**
I would like this page to be updated with a sample from Microsoft that shows the recommended way of how to do this.

**Comment by Diruuo** [comment]
I support this. 

There's this https://github.com/tompaana/intermediator-bot-sample but a more official and up-to-date example would be appreciated. 

There's some inkling of this in Microsoft's AI repo (https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/Dialogs/Shared/RouterDialog.cs) but it is not as of yet developed (that I can see).

**Comment by cleemullins** [comment]
The scenario around handoff is a frequently requested scenario. Assigning to @yochay to scope this and determine timing for the team looking into this in more detail.

**Comment by yochay** [comment]
We are actively looking to standardize this pattern.

**Comment by djpirra** [comment]
Is there any sample for this using the latest version of the framework? Where can I find it?

**Comment by mdrichardson** [comment]
@tdurnford 	has a really nice [handoff sample](https://github.com/tdurnford/botframework-human-handoff) I'd recommend taking a look at if you're looking for something a little more recent.

**Comment by Avalaxy** [comment]
Only for javascript unfortunately. I think a C# example would be more
interesting.

**Comment by tdurnford** [comment]
@diruuo mentioned @tompaana’s C# handover sample in his comment above. 
 https://github.com/tompaana/intermediator-bot-sample

**Comment by Tushar301** [comment]
I have implemented the "tompaana" solution for bot-agent-handoff (1 to 1 conversation), but how can I establish a "1 to n" scenario (i.e. one agent handling multiple users after bot escalation)?

**Comment by cleemullins** [comment]
assigning to @arturl, who is driving this work on our end.

**Comment by arturl** [comment]
Take a look at our documentation here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library.
The APIs will be in SDK 4.8, C# and JS. Note that the APIs are just the "lingua franca" for initiating and acknowledging handoff, the actual integrations must be built for specific agent hub providers. 
For an example of such integration, check out LivePerson Bot Framework connector: https://developers.liveperson.com/third-party-bots-microsoft-bot-framework.html

**Comment by FreddieK01** [comment]
Has anyone found a good sample that works? I am trying to implement this now

**Comment by AshishMoradiya** [comment]
> Take a look at our documentation here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library.
> The APIs will be in SDK 4.8, C# and JS. Note that the APIs are just the "lingua franca" for initiating and acknowledging handoff, the actual integrations must be built for specific agent hub providers.
> For an example of such integration, check out LivePerson Bot Framework connector: https://developers.liveperson.com/third-party-bots-microsoft-bot-framework.html

@arturl is there no plan for providing built in support for agent hub? samples stated here looks outdated and not using [handoff protocol](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0#handoff-protocol) described in official document. Also checked [closed issues](https://github.com/microsoft/BotBuilder-Samples/issues?q=is%3Aissue+handoff+is%3Aclosed) on this topic but none of them leads to proper direction. @FreddieK01 Let me know if you find any direction.

**Comment by FreddieK01** [comment]
thanks @AshishMoradiya I am trying to work it now. Its given me a good starting point. I guess with the handoff sample, I need to configure it to go to my own agent etc... (I'm using liveperson)

**Comment by arturl** [comment]
@AshishMoradiya, @FreddieK01,

We have LivePerson and Omnichannel samples here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library/csharp_dotnetcore/samples

All samples are up to date.

Some customer already used them to build their own integrations, for example ServiceNow.

**Comment by FreddieK01** [comment]
@arturl Thanks, I see now. I want to have a bot where it can handoff to LivePerson. To do this, using those samples, do I just use the LivePersonAgentBot, or do I need to use that in conjunction with the live person connector?

**Comment by AshishMoradiya** [comment]
> @AshishMoradiya, @FreddieK01,
> 
> We have LivePerson and Omnichannel samples here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library/csharp_dotnetcore/samples
> 
> All samples are up to date.
> 
> Some customer already used them to build their own integrations, for example ServiceNow.

@arturl Thank you for your response, Could you please throw some light on how to build own agent hub and integration? I could not find much information on it, I want to develop user waiting queue and 1 agent chat with multiple user scenario.

**Comment by arturl** [comment]
Hi @AshishMoradiya, we're focusing on providing integrations with existing party agent hubs, and this is our recommended approach. To build your own hub, you can take inspiration from the work mentioned above in this thread (https://github.com/tompaana/intermediator-bot-sample) in which both users and agents are connected to the same bot, and the bot serves as the dispatcher.
