### ISSUE TITLE
The C# Empty Bot template only supports the development environment

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1135]
## Sample information
1. Sample type: [template]
2. Sample language: [dotnetcore]
3. Sample name: Microsoft.BotFramework.CSharp.EmptyBot

## Describe the bug
Can't deploy a new "empty bot" out of the box.

## To Reproduce
1. Create a new bot using the **empty bot** template.
1. Deploy the bot.
1. Observe that you can't communicate with the deployed bot via the Emulator or Web Chat.

## Expected behavior
A bot that uses the **empty bot** template should be deployable.

## Additional context
There's at least one bug in the code. Compare this to what's in the **echo bot** template.
https://github.com/Microsoft/BotBuilder-Samples/blob/9a1346f23e7379b539e9319c6886e3013dc05145/generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Startup.cs#L59-L64

[bug]

**Comment by sgellock** [comment]
@JonathanFingold - the deployment issue is by design.  also the inability to interact with an empty bot with WebChat is also by design.  it's empty

What the 3rd issue you've raised regarding the endpoint?

**Comment by JonathanFingold** [comment]
The empty bot is a basic and functional hello world bot. It would be as good a starting point for a bot as the echo bot (which includes state wiring that not all bots will need). If I understand your question, `service` should look for the "development" **or** "production" endpoint, based on an `_isProduction` flag, like the echo bot does.
