### ISSUE TITLE
[netcore][51.cafe-bot] The GetUserNamePrompt never cancels since the If statement that checks for the user response is incorrect

### ISSUE THREAD

**Issue by Diruuo** [Microsoft/BotBuilder-Samples#1142]
## Sample information
1. Sample type: **samples**
2. Sample language: **dotnetcore**
3. Sample name: **51.cafe-bot**

## Describe the bug
When the user tries to cancel out of the GetUserNamePrompt they get asked for confirmation, but the If statement that checks that response always lands on else (```return await base.ResumeDialogAsync(dc, reason, result);```), as such the prompt never cancels. 

## To Reproduce
1. Set up Cafe bot to be functional. 
2. Land on WhoAreYou dialog
3. Type "cancel" (so that LUIS lands on the Cancel Intent and then initiates the Cancel confirmation prompt).
4. The Yes answer fails to cancel the prompt, because the code never checks whether the response returned is True or False. 

## Expected behavior
The prompt should cancel appropriately when given the confirmation to do so by the user. 

## Screenshots
The behavior when the user responds with "Yes" to the Cancel prompt. 
![image](https://user-images.githubusercontent.com/26669118/50973828-22303c00-14ea-11e9-9e14-30cacb4d5328.png)

![image](https://user-images.githubusercontent.com/26669118/50973848-2d836780-14ea-11e9-8dab-49ae1a2be6a0.png)

## Additional context
Running this check ```if (result != null && (bool)result)``` gets the appropriate response and the prompt cancels (successfully reaches ```return await dc.CancelAllDialogsAsync();```) if the user clicked Yes. 

[bug]

**Comment by v-kydela** [comment]
Hello @Diruuo 

Thanks for finding this bug! I've submitted a pull request to fix it
