### ISSUE TITLE
Update BotBuilder-Samples/SPEC.md

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#1158]
## Describe the bug
our SPEC.md is a bit out of date.  turn the crank and updating it for 4.3

**Comment by JonathanFingold** [comment]
The links to the ruleset in the [StyleCop - C#](https://github.com/Microsoft/BotBuilder-Samples/blob/master/SPEC.md#stylecop---c) section are broken.

**Comment by sgellock** [comment]
@JonathanFingold what does this have to do with SPEC.md?

**Comment by sgellock** [comment]
Fix merged into samples-work-in-progress branch.  will be updated in master when that branch is merged for the 4.4 release.
