### ISSUE TITLE
[Question] Node\intelligence-LUIS can not recognize my query

### ISSUE THREAD

**Issue by targetnull** [Microsoft/BotBuilder-Samples#117]
I'm trying the `Node\intelligence-LUIS` example locally in the bot-emulator, it replies
> Sorry, I did not understand 'Hotels'. Type 'help' if you need assistance.

no matter what I type, even 'help'. 

I have specified my LUIS endpoint, and I'm sure the LUIS service is OK because I can get normal results by typing directly in the browser url. How can I get this example work? Thanks

**Comment by ejadib** [comment]
what version of the botBuilder package are u using?

**Comment by targetnull** [comment]
The `npm view botbuilder version` gives `3.7.0`, I guess that's the latest version.
I cloned the sample repo about a week ago, so it should not be the problem of an outdated sample.

**Comment by ejadib** [comment]
Have you trained and published the LUIS model? Have you updated the Luis Model URL in the sample?

**Comment by targetnull** [comment]
1. Yes, I have trained and published the LUIS model. I just trained and published a test app [here](https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/f2059ab9-6d6b-4cf1-baae-f5a70995cbc9?subscription-key=300ccdbb2cf74771a289cad994c1b293&verbose=true&timezoneOffset=0&q=) containing two intents, `search location` and `book room`, you can try appending `where is the latest hotel` in the url and you should see it respond normally;
2. Yes I have, I update the *LUIS_MODEL_URL* in the `.env` file,
    LUIS_MODEL_URL=https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/f2059ab9-6d6b-4cf1-baae-f5a70995cbc9?subscription-key=300ccdbb2cf74771a289cad994c1b293&verbose=true&timezoneOffset=0&q=

**Comment by Aaruhi013** [comment]
Even I am facing the same issue. I have used the sample code provided.

**Comment by stevengum97** [comment]
@targetnull If you are still running into this issue, can you set your LUIS application as public (via Settings in the LUIS portal, or via the Authoring Endpoint) and provide the App ID so we can test it with the sample? From what you've reported the sample should be working...

**Comment by srichakradhar** [comment]
Even I am facing the same issue. I've set my LUIS application as public. I'm able to get this result from the browser:
`{
  "query": "Search for hotels near Seattle",
  "topScoringIntent": {
    "intent": "SearchHotels",
    "score": 1.0
  },
  "intents": [
    {
      "intent": "SearchHotels",
      "score": 1.0
    },
    {
      "intent": "None",
      "score": 0.004987137
    },
    {
      "intent": "Help",
      "score": 0.00188698818
    },
    {
      "intent": "ShowHotelsReviews",
      "score": 7.94673771E-10
    }
  ],
  "entities": [
    {
      "entity": "seattle",
      "type": "AirportCode",
      "startIndex": 23,
      "endIndex": 29,
      "score": 0.9998389
    },
    {
      "entity": "seattle",
      "type": "builtin.geography.city",
      "startIndex": 23,
      "endIndex": 29,
      "score": 0.969812334
    }
  ]
}`
but, I can't get anything except the help message on the `botframework-emulator-3.5.33-x86_64.AppImage`
`npm view botbuilder version`
`3.11.0`
check my [ LUIS_MODEL_URL ](https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/9e68536e-9a27-457f-8beb-0b3d4e780c1e?subscription-key=[hidden]&verbose=true&timezoneOffset=5.5&q=Search%20for%20hotels%20near%20Seattle)
This seems to be a node app issue. I've checked `process.env.LUIS_MODEL_URL` and it is reading it well. I think `recognizer` is not able to kick in.

**Comment by mariaaloysius1** [comment]
even I am facing the same issue, any updates on this issue
