### ISSUE TITLE
11.QnAMaker: Invalid configuration

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotBuilder-Samples#1171]
## Sample information
- Sample language: dotnetcore
- Sample name: 11.qnamaker

## Describe the bug
Exception occurs when running the sample. 

## To Reproduce
STEP 1: Create a QnA Maker service and imported the .tsv file in QnAmaker.ai
STEP 2:  Update the KBid, endpoint in .bot file. 
  - Note that instructions don't specify the host name from QnA, which also needs to be updated. However, the exception still happens even with the updated hostname. 

STEP 3: Run the project in Visual Studio.

You'll get an exception "Invalid configuration. Please check your '.bot' file for a QnA service named '{QnAMakerKey}'." This occurs because the QnAMakerKey value in QnABot.cs should be the same as the one given in .bot file.

## Expected behavior
The sample should work using the readme.

[bug]

**Comment by sgellock** [comment]
I think #1185 addresses, but can you double check @Kaiqb
