### ISSUE TITLE
During installation, unable to select typescript option

### ISSUE THREAD

**Issue by smich73** [Microsoft/BotBuilder-Samples#1172]
## Sample information
1. Sample type: yo botbuilder
2. Sample language: nodejs
3. Sample name: echobot

## Describe the bug
When building simple JS echobot using these instructions https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0 - used the Yeoman generator and walked through the options. Was unable to toggle between javascript and typescript - had to select former

## To Reproduce
1. Go to https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0
2. Follow the instructions to use Yo generator and select Echobot. Enter your bot name, description
3. I could only choose javascript and not typescript. This is despite having typescript installed on my Windows system (v 2.5.3)
4. I selected JS and it all installed ok

## Expected behavior
At the option to select 'Javascript' or 'Typescript' then I should have been able to toggle between them and select both. Instead the option is not selectable. 

## Screenshots
None

## Additional context
None

[bug]

**Comment by sgellock** [comment]
@smich73 I just installed v4.2.4 of generator-botbuilder.  I followed the instructions in the documentation link you provided above.  I was able to create an echo bot in TypeScript.  What version of the generator are you using

**Comment by smich73** [comment]
I am using botbuilder v4.2.4 via Windows command prompt. thanks all

**Comment by smich73** [comment]
Looks like the issue is with Yeoman - see the issue logged at: https://github.com/yeoman/yo/issues/360

Therefore closing this issue against botbuilder. Thank you all for your help

**Comment by sgellock** [comment]
@smich73 You can also provide all the options our template prompts for as command line parameters.  Please refer to the following for docs and examples:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder#generator-command-line-options
