### ISSUE TITLE
Botbuilder generator env file + gitignore causes cloned repos to fail. Could cause confusion for new users.

### ISSUE THREAD

**Issue by hattan** [Microsoft/BotBuilder-Samples#1174]
## Confusing behavior
Currently the yeoman template generates a .env file and includes the botFilePath in the env file. However, the .env file is in .gitignore (correctly so!) and that could cause confusion when checked into github.  A second user could clone the repo and run into an error of not being able to run the bot. 

## To Reproduce
1. Create a new bot using botbuilder-generator.
2. Push code to github
3. As a new user (or in a new folder) clone the bot.
4. Notice bot won't start due to missing botFilePath value.

## Expected behavior
The expectation is that everything needed to run the bot should be pushed to github. While not checking in the .env is correct and good practice, it does cause friction because the botFilePath is in there and results in a non functioning bot.

Perhaps including the expected local botFilePath in the Readme and making it clear that when cloning the repo, users need to add a .env file and include the default values for the botFilePath.

[bug]

**Comment by sgellock** [comment]
.bot files have been removed code generators and samples.  you can see this in the samples-work-in-progress branch, which we plan to merge into master and publish to our various registries (NuGet, npmjs.org) within the very near future, about a week.
