### ISSUE TITLE
12.nlp-with-luis Invalid Configuration

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1177]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 12.nlp-with-luis

## Describe the bug
Hits an exception "Invalid configuration. Please check your '.bot' file for a LUIS service named '{LuisKey}'."
 - Occurs because the LuisKey value in LuisBot.cs should be the same as the one given in .bot file.

## To Reproduce
1. Sign in luis.ai and import the .json file in My Apps.
2. Update the required fields in .bot file with the luis values.
3. Run the project in Visual Studio
     - Hits the exception "Invalid configuration. Please check your '.bot' file for a LUIS service named '{LuisKey}'."
 

## Expected behavior
The sample should work according to the readme

[bug]

**Comment by gopal300** [comment]
I had the same problem. I just added the Name field in the JSON file in VS project and it worked. The name in both JSON and LuisKey should be same as the app name in Luis.ai.

**Comment by mdrichardson** [comment]
To echo @gopal300, you need to make sure that `LuisKey` on line 27 of `LuisBot.cs` matches the `name` property of your LUIS endpoint in your `nlp-with-luis.bot` file.

This isn't specified in `README.md`, so I'll submit a pull request to update it.
