### ISSUE TITLE
Error 500 on Emulator

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1179]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 22.conversation-history
## Describe the bug
The emulator returns with error 500.
## To Reproduce
1. Create a BLOB storage service.
2. Update converstion-history.bot with connection string. 
3. Update the Storage ConfigurationId in Startup.cs with Blob service name.
4. On Visual studio run the project .
5. Test the bot on Emulator.
     -	The emulator returns with error 500.

## Expected behaviour
The sample should work according the readme, and could be tested on Emulator.

[bug]

**Comment by mdrichardson** [comment]
I was able to follow the readme and get mine running just fine. Are you still getting the 500 error? Can you copy/paste the error message along with the stack trace?

Screenshots of my setup and things working:

![image](https://user-images.githubusercontent.com/40401643/51934090-aeca6d80-23b7-11e9-893e-22b1fb7d0308.png)

![image](https://user-images.githubusercontent.com/40401643/51934248-fbae4400-23b7-11e9-876f-bd04fc16818d.png)

![image](https://user-images.githubusercontent.com/40401643/51934131-c43f9780-23b7-11e9-8c7c-e023118b68ae.png)

![image](https://user-images.githubusercontent.com/40401643/51934168-d6213a80-23b7-11e9-8041-4ab24e8f04a4.png)

**Comment by mdrichardson** [comment]
Gotcha. I'll add this to my README PR.
