### ISSUE TITLE
Exception while testing on Emulator

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1180]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 51.cafe-bot

## Describe the bug

1. While testing on Emulator,
It is hitting an exception in cafebot.cs to check for a Luis service name “cafeDispatchModel”.

## To Reproduce
1. Install the CLI tools.
2. Configure the required services.
3. Run the msbot clone command.It says ,
      -	Unknown arguments: --noDecorate
        So, removed it and tried running the command. It worked.
4.  Test on Emulator.
      -	It is hitting an exception in cafebot.cs to check for a Luis service name “cafeDispatchModel”.

## Expected behaviour
The sample should work according the readme and could be tested on Emulator.

[bug]

**Comment by mdrichardson** [comment]
Your error in step 4 is similar to the issue you posted here: https://github.com/Microsoft/BotBuilder-Samples/issues/1177

You need to make sure that LuisConfiguration in `CafeBot.cs` matches the name property of your LUIS endpoint in `.bot` file.

For that, as well as the `--noDecorate` error, I'll submit a pull request to correct those in the `README.md`
