### ISSUE TITLE
QnA configuration error at index.js - Not fixed even issue was raised 3 months ago

### ISSUE THREAD

**Issue by cbtham** [Microsoft/BotBuilder-Samples#1184]
## Sample information
1. Sample type: QnAmaker
2. Sample language: nodejs
3. Sample url: https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/11.qnamaker/index.js

## Describe the bug
TypeError: Cannot read property 'kbId' of null

## To Reproduce
1. npm install
2. npm start
3. See error

## Expected behavior
The sample to start running.

## The FIX
index.js configuration supposed to be qnamaker or the name that is defined in .bot file.

// QnA Maker service name as specified in .bot file.
const QNA_CONFIGURATION = 'qnamakerService';

## Additional context

[bug]

**Comment by mdrichardson** [comment]
Another good catch. I'll fold this into my other PR.
