### ISSUE TITLE
Exception while running the 'npm start' command

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1189]
## Sample information
1. Sample language: nodejs  
2. Sample name: .basic-bot

## Describe the bug

Exception that says,
‘Make sure to update the index.js file with a LUIS_CONFIGURATION name that matches your .bot file.’ 

## To Reproduce
1. Get all the prerequisites.
2. Run npm install command.
3. Run az login and az subscription commands.
4. Run msbot clone command.
5. Run npm start command. An error arises saying,
 ‘Make sure to update the index.js file with a LUIS_CONFIGURATION name that matches your .bot file.’ 
            - But in index.js file, the LUIS_CONFIGURATION value is 
            (process.env.NODE_ENV || DEV_ENVIRONMENT);

## Expected behaviour
The sample should work according the readme.

**Comment by sgellock** [comment]
This is by design.  please refer to the README.md and the PREREQUISITES.md file that will show you how to provision and configure LUIS.
