### ISSUE TITLE
Logic for checking for LuisServices in .bot files across C# samples differs

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder-Samples#1196]
## Sample information
1. Sample type: samples\
2. Sample language: dotnetcore 
3. Sample name: 12-14, 21 (nlp-with-luis, basic-bot, nlp-with-dispatch, luis-with-appinsights)

## Describe the bug
The logic to check if a valid LUIS Service entry exists in the .bot file differs across these samples. Some samples have a `BotServices.cs` file, where one does not. Other samples look to see if just a LUIS entry exists, others parse the LUIS entry to verify that all the necessary fields are available.

## Expected behavior
The code to look like it was written by one person and have the same checks across all samples that use LUIS and bot files.

[bug]

**Comment by stevengum** [comment]
Assigned to sgellock and kaiqb so we can figure out a plan to uniform this code and not create more work than necessary.

**Comment by sgellock** [comment]
won't fix, given our de-emphasis on .bot files
