### ISSUE TITLE
Why do we have 2 'Samples' repos?

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotBuilder-Samples#1199]
It's confusing to users which Samples repo they should be looking at. Additionally our docs seem to reference some samples in this repo, and some samples in the **BotFramework**-Samples repo; we should consolidate these.

I've filed a similar issue on the BotFramework repo [here](https://github.com/Microsoft/BotFramework-Samples/issues/61).

**Comment by sgellock** [comment]
@Kaiqb we should retire gh/ms/botframework-samples.

**Comment by Kaiqb** [comment]
That's is the plan. We want to merge everything into botbuilder-samples repo.

**Comment by Kaiqb** [comment]
All samples are now in the same "botbuilder-samples" repo. The change will go live in next 10 days.
