### ISSUE TITLE
[Question] Human hand off sample using .Net sdk

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/BotBuilder-Samples#120]
I came across an article for human hand off in MS bot [here](https://docs.microsoft.com/en-us/bot-framework/bot-design-pattern-handoff-human)

A sample using .nodeJS is given in this article. Do we have this sample in .Net also? If yes then please someone provide the address. Thanks

**Comment by EricDahlvang** [comment]
Near the bottom of that page you referenced, there is a link to this repo: https://github.com/palindromed/Bot-HandOff  

Scrolling down a little on that page you'll see: 

> There is also an example of handoff to human using the C# SDK https://github.com/tompaana/intermediator-bot-sample

**Comment by ejadib** [comment]
You can also take a look to https://github.com/ankitbko/human-handoff-bot
