### ISSUE TITLE
"Welcome users" sample is overly complex

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotBuilder-Samples#1201]
**Is your feature request related to a problem? Please describe.**
The JS sample `03.welcome-users` is confusing because it welcomes the user twice: once on a `ConversationUpdate` activity, and once when the user sends the first message. The code uses variables like `didBotWelcomedUser` and `welcomedUserProperty`, so it isn't clear which instance of welcoming they're tracking.

The sample also uses more concepts than necessary:
- State (only required for the confusing 2nd welcome message)
- Adaptive cards (not required, introduced in a future sample)

**Describe the solution you'd like**
This sample would be more clear and concise if it just introduced the `ConversationUpdate` activity, the only necessary concept to welcome a user.

[enhancement]

**Comment by sgellock** [comment]
We have a DCR in-flight that will simplify this.  Please refer to the following and comment there.
C# can be found here:
https://github.com/Microsoft/BotBuilder/issues/5285

JS coming within a day or so
