### ISSUE TITLE
Deployed sample doesn't work on Azure

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1203]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 03. welcome-user

## Describe the bug
The sample doesn't work on webchat in Azure after deploying it using the msbot clone command in readme.
## To Reproduce
1. Make the sample work locally.
2. Use msbot clone command (after obtaining the appId and appSecret) as given in readme to deploy the sample on Azure.
3. Test the deployed sample on Azure in webchat.
     - It doesn't work on webchat. If I try to send some message, it says 'can't send'.

## Expected behaviour
The sample should work according the readme.

**Comment by jwiley84** [comment]
I'll have to check the README, but first: after you deployed, did you go into the deployed bot's .bot file and update it with a 'production' endpoint?

**Comment by mdrichardson** [comment]
@nstejaswini 

I was able to follow the steps in the Readme and get this working, successfully.

My steps:

1. Clone the repo
2. Open the sample in Visual Studio
3. Press F5
4. Open in Emulator and tested successfully
5. Create a new app in the App Registration Portal
6. Generated a New Password and copied the AppId and Password
7. Used `msbot clone services` command from the bot's README, with the id/pass from above. This auto-generated the production endpoints in the `.bot` file.
8. Tested both production endpoints in Emulator (for some reason there's two)--success for both
9. Tested the app in Azure with "Test in Web Chat" -- success

![image](https://user-images.githubusercontent.com/40401643/52297514-c1075700-2935-11e9-8076-a5f95e84e3f5.png)


Was your deployment successful, or did it produce errors? If you can provide you `appId`, I can do additional research and look into this further.

**Comment by nstejaswini** [comment]
I tried it again today twice. It worked for the second time. Last time I tried deploying two to three samples on Azure using the msbot command given in readme file, but the same error was coming. I don't know why that happened.  
It is not given in Readme that, before using the msbot clone command, path to sample (cd botBuilder/samples/…) should be given.

**Comment by mdrichardson** [comment]
I looked into the appId you provided and I think there's something wrong with your app service or deployment. There's a couple things you can try from Azure Portal > Your App Service:

1. Try restarting the app service
2. Open the App Service Editor and verify that the `.bot` file that got deployed has a production endpoint, then check `appsettings.json` there and verify that it's using the `.bot` file that has the production endpoint. You may also want to click "Output" and then "Run" and see if it shows any errors:

![image](https://user-images.githubusercontent.com/40401643/52358752-6d584480-29ed-11e9-8036-49f38a17be23.png)


There was also a major botservice update rolled out to westus yesterday. If you had any apps on westus, that might explain some of the inconsistencies.

When you say "but the same error was coming," do you mean the "can't send" error, or were you receiving an error during deployment?

Trying this again, at the very end of `msbot clone` command's output, I got a `Zip deployment ... failed with status code '500'` error. Looks like it timed out while uploading. My Test in Web Chat then gave me the same errors you were receiving. Is it possible yours also failed to deploy? If so, when `msbot clone` errors at the end, you should be able to retry publishing by copy/pasting the `az bot publish` command that it shows in the error output. I just did this for mine and then the Test in Web Chat was successful.

**Comment by nstejaswini** [comment]
I guess the westus was the problem, because I used it as the location. By "same error" I meant "can't send". I will try using the methods you suggested and deploy it again.

**Comment by mdrichardson** [comment]
@nstejaswini 	Were you able to get this working?

**Comment by nstejaswini** [comment]
@mdrichardson 
I tried deploying it again, using westus as the location. It is not working. I checked the new .bot file for the production endpoint and also the appsettings file to check the name of the new .bot file. Everything is according to the expectation. Also I ran the 'output' and then 'run'. No errors were found.
There is no error while deployment. It says 500 directline.postActivity in Emulator.

**Comment by mdrichardson** [comment]
Interesting. That's an error that should pop up in the console when testing locally. I'll update the readme and add a step to check the LUIS name.

**Comment by mdrichardson** [comment]
I deployed again using the steps I provided above and got all three endpoints (1x development, 2x production) working in emulator, tested successfully in Test in Web Chat, and also tested successfully using the embedded Web Chat iframe.

Maybe you need to update msbot with `npm i -g msbot`?

When you run the `msbot clone services...` command, do you get *any* errors in the console window? Like this one, maybe:

![image](https://user-images.githubusercontent.com/40401643/52661640-52874380-2eb7-11e9-9e9a-e34ea24c7613.png)

There was [an update to msbot](https://github.com/Microsoft/botbuilder-tools/pull/904) recently that prevents the bot from publishing if you don't supply `--code-dir "."`. Not including this it apparently creates the default Echo Bot, but I didn't get any testing errors in either case.

**Comment by nstejaswini** [comment]
The problem with sample 3 is gone. It is working. I was talking about the 12.nlp-with-luis. I got that working too. In the readme, a note is given about updating the LuisKey value in LuisBot.cs while testing it locally. It worked locally. When I deployed it on Azure, I had to change the LuisKey value again. But without updating it I tried testing it on Emulator as there were no errors on console. That's when the 500 Error was seen. Once I updated the LuisKey value with the new Luis service name that got created because of the msbot clone command, I could run t on Emulator and Webchat successfully.

**Comment by mdrichardson** [comment]
Gotcha. I'm going to close this issue and submit a pull request to update the readme to ensure that the deployed bot has the correct LuisKey. I believe `msbot clone services...` causes a change to the `.bot` file that causes the error when deploying. We'll be getting rid of `.bot` files soon, so this shouldn't be an issue in the future.
