### ISSUE TITLE
No bot.recipe error while deploying

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1207]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 06.using-cards

## Describe the bug
 When the msbot clone command is given it showed the following error,
No bot.recipe file found under deploymentScripts/msbotClone. Please provide the folder that contains the recipe file

## To Reproduce
1.  Run the sample locally on Visual studio.
2. Obtain the appId and appSecret from registration portal.
3. Run the msbot command with required data as given in the readme.
     - An error occurs saying, No bot.recipe file is present under deploymentScripts/msbotClone. Please provide the folder that contains the recipe file.  

## Expected behaviour
The sample should work according the readme.

**Comment by mdrichardson** [comment]
I'll submit a PR to address this. The file is currently located under `deploymentScripts/` and not `deploymentScripts/msbotClone`. In the meantime, you can use this command instead:

```
msbot clone services -f deploymentScripts -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id> --appId <YOUR APP ID> --appSecret <YOUR APP SECRET PASSWORD>
```

I'm going to close this as I'm 99% sure this addresses your issue--the other samples have `bot.recipe` located under the `/msbotClone` folder, unlike this one. Feel free to reopen if you still have issues.
