### ISSUE TITLE
Url of DirectLine 3 swagger has been moved.

### ISSUE THREAD

**Issue by pernambucano** [Microsoft/BotBuilder-Samples#1208]
## Sample information
1. Sample type: \samples\
2. Sample language: [nodejs]
3. Sample name: core-DirectLine (v3)

## Describe the bug
The url of the swagger used in the example has been moved and is not useful anymore. The url written in the example is this: https://docs.botframework.com/en-us/restapi/directline3/swagger.json, however this url leads you to a v4 botframework doc.

## To Reproduce
1. Go to core-DirectLine (v3)
2. Download files
3. Run "node app.js"

## Expected behavior
We should have a directline client created. However, we can not find the swagger.json file through the url described.

## Screenshots
![image](https://user-images.githubusercontent.com/6789675/52349256-4f9ad780-2a0d-11e9-885e-b3d11cdfaf6d.png)

 
[bug]

**Comment by EricDahlvang** [comment]
The swagger file is now located here: https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-protocol/directline-3.0.json

I'll update the V3 direct line samples to use a locally hosted swagger file (it is not a good idea to take a dependency on a file located in the documentation).
