### ISSUE TITLE
[Nodjs:12.nlp-with-luis]: onTurnError

### ISSUE THREAD

**Issue by fhe-fr** [Microsoft/BotBuilder-Samples#1209]
## Sample information
1. Sample type: [\samples\ or \solutions\]
samples
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
nodejs
3. Sample name: <Name of the sample>
12.nlp-with-luis

## Describe the bug
Give a clear and concise description of what the bug is.
when runing the bot, I get the Following error:
[onTurnError]: Error: Response 400: The request's body or parameters are incorrect, meaning they are missing, malformed, or too large.
## To Reproduce
Follow the readme.MD
npm start
start the emulator and choose the bot file created during the precedent steps
[onTurnError]: Error: Response 400: The request's body or parameters are incorrect, meaning they are missing, malformed, or too large.
## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by sgellock** [comment]
Support Team, the repo steps are pretty light here.  I've run the sample many times without error.  can you see if you can get more detail from the customer on what is causing their issue.

**Comment by stevkan** [comment]
@fhe-fr, I've tried reproducing the issue using following the sample's README.md, however I have been unsuccessful in doing so. I'm wondering:

- Did you change any of the code after the msbot deployment process finished but before you ran 'npm start'?
- Did you record any other errors?
- Did this error only occur locally or did it also occur once deployed on Azure?
- Did you try recreating?
- Can you list for me which version of node, msbot, and the botbuilder libraries you have installed?

**Comment by fhe-fr** [comment]
Hi,
I resinstall everything and it works well now.
Thanks
    On Monday, February 11, 2019, 07:18:02 PM PST, Steven Kanberg <notifications@github.com> wrote:  
 
 
@fhe-fr, I've tried reproducing the issue using following the sample's README.md, however I have been unsuccessful in doing so. I'm wondering:
   
   - Did you change any of the code after the msbot deployment process finished but before you ran 'npm start'?
   - Did you record any other errors?
   - Did this error only occur locally or did it also occur once deployed on Azure?
   - Did you try recreating?
   - Can you list for me which version of node, msbot, and the botbuilder libraries you have installed?

**Comment by CoHealer** [comment]
Closing as resolved
