### ISSUE TITLE
[C#][.Net Core] [14.nlp-with-dispatch] System.InvalidOperationException: "The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file."

### ISSUE THREAD

**Issue by seank-com** [Microsoft/BotBuilder-Samples#1211]
I wrote all this up and then discovered it is Issue #[607](https://github.com/Microsoft/BotBuilder-Samples/issues/607), but it is still broken. I think the bug was closed without testing to see if the PR actually fixed the issue.

## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 14.nlp-with-dispatch

## Describe the bug

```
System.InvalidOperationException: "The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file."
  at NLP_With_Dispatch_Bot.Startup.InitBotServices(BotConfiguration config) in /usr/src/BotBuilder-Samples/samples/csharp_dotnetcore/14.nlp-with-dispatch/Startup.cs:line 223
   at NLP_With_Dispatch_Bot.Startup.ConfigureServices(IServiceCollection services) in /usr/src/BotBuilder-Samples/samples/csharp_dotnetcore/14.nlp-with-dispatch/Startup.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at NLP_With_Dispatch_Bot.Program.BuildWebHost(String[] args) in /usr/src/BotBuilder-Samples/samples/csharp_dotnetcore/14.nlp-with-dispatch/Program.cs:line 17
   at NLP_With_Dispatch_Bot.Program.Main(String[] args) in /usr/src/BotBuilder-Samples/samples/csharp_dotnetcore/14.nlp-with-dispatch/Program.cs:13
```

## To Reproduce

  1. [Install BotBuilder tools](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#install-botbuilder-tools).

    $ npm i -g msbot chatdown ludown qnamaker luis-apis botdispatch luisgen

  2. [Install BotBuilder samples](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch#to-try-this-sample)

    $ git clone https://github.com/Microsoft/botbuilder-samples.git

  3. Change to dispatch sample, remove and recreate .bot file **Note:** *Type y for `Do you have an appId for endpoint?` See Application Settings for Web App Bot in Azure Portal for MicrosoftAppId and MicrosoftAppPassword these are your appId and appPassword. When prompted `Would you like to encrypt your keys with a secret?` type n*

    $ cd botbuilder-samples/samples/csharp_dotnetcore/14.nlp-with-dispatch/
    $ rm nlp-with-dispatch.bot
    $ msbot init --name "nlp-with-dispatch" --endpoint http://localhost:3978/api/messages

  4. [Manually configure required services](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#manually-configure-required-services).

    $ ludown parse toluis --in Resources/homeautomation.lu -o CognitiveModels --out homeautomation.luis -n "Home Automation" -d "Home Automation LUIS application - Bot Builder Samples" --verbose
    $ ludown parse toluis --in Resources/weather.lu -o CognitiveModels --out weather.luis -n Weather -d "Weather LUIS application - Bot Builder Samples" --verbose
    $ luis import application --in CognitiveModels/homeautomation.luis --authoringKey <LUIS-AUTHORING-KEY> --region <LUIS-AUTHORING-REGION> --msbot | msbot connect luis --stdin
    $ luis import application --in CognitiveModels/weather.luis --authoringKey <LUIS-AUTHORING-KEY> --region <LUIS-AUTHORING-REGION> --msbot | msbot connect luis --stdin
    $ msbot get "Home Automation" | luis train version --wait --stdin
    $ msbot get "Weather" | luis train version --wait --stdin 
    $ msbot get "Home Automation" | luis publish version --stdin
    $ msbot get "Weather" | luis publish version --stdin
    $ ludown parse toqna --in resources/sample-qna.lu -o cognitiveModels --out dispatch.qna --verbose
    $ qnamaker create kb --in cognitiveModels/dispatch.qna --subscriptionKey <QNA-MAKER-SUBSCRIPTION-KEY> --msbot | msbot connect qna --stdin
    $ msbot get "sample-qna" | qnamaker publish kb --stdin
    $ dispatch create -b nlp-with-dispatch.bot | msbot connect dispatch --stdin

**Note:** *We skip the `msbot` command to secure the key because we are not publishing this file and keys are missing so we don't want to edit encrypted json.*

  5. Manually change the endpoint name in the .bot file to "development". (re: issue #606)
  6. Run the bot in [Visual Studio](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#visual-studio).

## Expected behavior

From looking at the code, the sample expects the `dispatch create` command to add a `subscriptionKey` to the section of json that begins

    {
        "type": "dispatch",

You can copy one from any of the `"type": "luis",` sections and the code will work as expected.

**Comment by mdrichardson** [comment]
I was able to replicate this issue and will be working on a fix for it tomorrow.

**Comment by mdrichardson** [comment]
Looks like [this direction is already specified in the README](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch#configure-the-dispatch-application):

> Then update the dispatch service in your bot to have a "subscriptionKey". You can use the subscription key from one of the other LUIS services in the .bot file.

Since I missed that as well, I'll submit a PR to make that step more prominent.

**Comment by seank-com** [comment]
Thanks!
