### ISSUE TITLE
Missing instructions for deploying EchoBot to Azure

### ISSUE THREAD

**Issue by denscollo** [Microsoft/BotBuilder-Samples#1214]
## Sample information
1. Sample type: Samples
2. Sample language: DotNetCore
3. Sample name: EchoBot

## Describe the bug
There is an instruction and a parameter missing for deploying the bot to Azure.

## To Reproduce
1. Follow the [Readme](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/02.a.echo-bot/README.md) "Deploy the bot to Azure" instructions

## Expected behavior
It should deploy the bot to Azure and create all the necesary resources

## Screenshots
![image](https://user-images.githubusercontent.com/42191764/52482858-2440f580-2b91-11e9-9f5c-305255965df8.png)
![image](https://user-images.githubusercontent.com/42191764/52482891-36229880-2b91-11e9-8d8f-0b682ab5f6da.png)

## Proposed Solution
For the user-secrets issue we could add a `<UserSecretsId></UserSecretsId>` placeholder in `EchoBot.csproj` and explain in the Readme that this should be modified.

Also, for the bot publish issue, we should add to the Readme deploy command the `--proj-file "EchoBot.csproj"` parameter.

**Comment by sgellock** [comment]
dotnet clone services does all of this.  additionally, changes coming in 4.3 and 4.4 will mitigate this as we will not encrypt bot files by default

**Comment by sgellock** [comment]
msbot has been deprecated in place of ARM template support.  additionally, .bot files have also been deprecated, with application configuration settings now being stored in platform specific configuration files e.g. appsettings.json for .net and .env files for Node.js
