### ISSUE TITLE
Result of Core Typescript Generation not Compiling

### ISSUE THREAD

**Issue by JCHHeilmann** [Microsoft/BotBuilder-Samples#1215]
## Sample information
1. Sample type: generator template
2. Sample language: typescript
3. Sample name: core bot template

## Describe the bug
When generating a bot setup with the core bot typescript template `npm start` and `npm run watch` result in typescript compilation errors.

## To Reproduce
1. Run `yo botbuilder`
2. What programming language do you want to use? -> Typescript
3. Which template would you like to start with? -> Core Bot 
4. Wait
5. Run `npm start` or `npm run watch``
6. Scroll up to see typescript compilation error

## Expected behavior
The bot starts running without errors.

## Workaround
Remove `"strict": true` from tsconfig.json

## Additional context
It really seams like this bug could have been easily prevented by trying it once... 😅🙈

[bug]

**Comment by sgellock** [comment]
the 4.2.5 release will have this fix
