### ISSUE TITLE
[C#][.Net Core] [24.bot-authentication-msgraph] Login button unexpectedly appears twice after successful login

### ISSUE THREAD

**Issue by ktundwal** [Microsoft/BotBuilder-Samples#1216]
## Sample information
1. Sample type: [samples/csharp_dotnetcore/24.bot-authentication-msgraph]
2. Sample language: [dotnetcore]
3. Sample name: 24.bot-authentication-msgraph

## Describe the bug
When I send 'recent' command to fetch emails using MS Graph API, bot responds with the "Login" button. Upon clicking the button, sign in windows pops up correctly. Good so far. However, when I submit my credentials, bot responds with 3 messages (2 login prompts and 1 email response). 

## To Reproduce
1. Install bot in Teams
2. Send 'recent' command
3. Wait for Login prompt. When presented click it. 
4. Provide crendetials in sign in pop up box
5. Bot sends 3 messages: first is recent messages (expected behavior). next 2 messages are "login" prompt. 

## Expected behavior
Login prompt shouldnt come in step 5.

## Screenshots
![graph-authentication-bit-bug-feb-8-2019](https://user-images.githubusercontent.com/1222093/52496171-8563cb80-2b87-11e9-8158-fd7fcd3b19e9.gif)

[bug]

**Comment by stevkan** [comment]
@ktundwal, a few questions for you, if you could answer them to help me diagnose the problem!

- Does this also occur when first attempting to login or only after having signed out and then re-logging in?
- Is this only happening when trying in Teams or is it happening in other channels, too?
- Which version of the botbuilder libraries do you have installed?
- Have you made any code changes? If so, could you post your code?

**Comment by stevkan** [comment]
Closing due to lack of response.
