### ISSUE TITLE
Proposal: MultiBot sample

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/BotBuilder-Samples#1217]
Proposal: create a sample showing multi-bot support where a single bot service endpoint hosts several bots. Many customers reach out for this functionality. 

Attached file [EchoBot_MultiCredentialProvider.zip](https://github.com/Microsoft/BotBuilder-Samples/files/2846423/EchoBot_MultiCredentialProvider.zip)
is a minimal V3 sample for C#. The work would be to port it to V4 languages. (Thanks @EricDahlvang)

Arguably, this could also be captured in a blog post if we deem it not important enough to deserve a sample.

**Comment by benbrown** [comment]
Using the MVC approach, doing a multi-bot app is much easier than it used to be.  We're not planning to create a sample dedicated specifically to this, but a blog post is a good idea!
