### ISSUE TITLE
Basic bot on mac throws error in BasicBot.cs

### ISSUE THREAD

**Issue by diberry** [Microsoft/BotBuilder-Samples#1218]
## Sample information
1. Sample type: web app bot, 4.x sdk, c#
2. Sample language: dotnetcore
3. Sample name: basic bot

## Describe the bug

Issue #1 - Emulator 4 says it is connected but doesn't get past "couldn't send" regardless if I use development or production endpoint. Verified this also happens on Win10. 

Issue #2 - Emulator 3 throws an error when running against local/development server. Verified this is a mac-only issue. 

## To Reproduce
In azure portal, created a new web app bot, SDK 4.x, c#, basic. 
Downloaded zip file to local mac environment
Unzipped files
Opened solution with mac Visual Studio
Followed readme.md instructions in base of project (adding to appsettings.json file, and using emulator)

`var adaptiveCard = File.ReadAllText(@".\Dialogs\Welcome\Resources\welcomeCard.json");`

The full exception looks like the code isn't dealing with pathing correctly. 

## Expected behavior
Expect sample to work with both emulators and have the exact same behavior as the Portal's "Test in Web Chat" -- which works and shows the cards. 

## Screenshots

![snip20190208_9](https://user-images.githubusercontent.com/41597107/52509290-70e5fa00-2bac-11e9-9618-1e1fb76ae85c.png)
![snip20190208_8](https://user-images.githubusercontent.com/41597107/52509291-717e9080-2bac-11e9-9bd0-315333bc9799.png)
![snip20190208_7](https://user-images.githubusercontent.com/41597107/52509293-717e9080-2bac-11e9-83ae-a175736e977f.png)
![snip20190208_6](https://user-images.githubusercontent.com/41597107/52509294-717e9080-2bac-11e9-9716-302c39bd44a0.png)

## Additional context

[bug]

**Comment by sgellock** [comment]
this has been fixed in the samples repo, and the code generators.  the Azure Portal needs an updated template with the fix

**Comment by diberry** [comment]
@sgellock Can you please give me ETA when it will show up in the Azure Portal ?

**Comment by sgellock** [comment]
A couple of things will drive getting this fix into the portal.  Currently we are close to releasing 4.3.  I’ll update portal templates to use the 4.3 release.  I don’t see this landing before early March.  That said, a workaround would be to download the code from the portal, apply the fix referenced in the #1223 and az bot publish the local change back up to the portal.
