### ISSUE TITLE
[Question] GZipSerialize for ConversationReference  throws SerializationException 

### ISSUE THREAD

**Issue by RomanLysogor** [Microsoft/BotBuilder-Samples#122]
GZipSerialize as an existing extension method of **ConversationReference** is throwing **SerializationException** because **ConversationReference** class is not marked as [Serializable]

**Comment by ejadib** [comment]
Please report the issue in github.com/Microsoft/BotBuilder

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
