### ISSUE TITLE
Customer feature request - make ARM template available for Bot Templates

### ISSUE THREAD

**Issue by JasonXuMSCSS** [Microsoft/BotBuilder-Samples#1220]
Customer feature request - make ARM template available for Bot Templates.

Currently this is unavailable.

This POST: https://github.com/Microsoft/BotBuilder/issues/4812 suggests to use Azure CLI instead. 

Customer had support cases opened and asked for a new feature request to be filed.

**Comment by kashifkhan** [comment]
Will these ARM templates also work for V3 bots ?

**Comment by stevengum** [comment]
The ARM templates would also work for v3 bots, they simply create the required resources necessary for deploying a bot on Azure.

**Comment by kashifkhan** [comment]
thats great news!!! will it part of the next release ?

**Comment by stevengum** [comment]
That’s correct, we will have templates in the V4 samples, and docs online on how to use the ARM templates. As per the newly updated readme, you can find the templates right now in https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress

The current templates are located in the csharp_dotnetcore/03.welcome-users sample

**Comment by stevengum** [comment]
Closing this as we have ARM templates in the above branch. Further ARM templates (e.g. AppInsights/QnAMaker) are coming soon!
