### ISSUE TITLE
Syntax error of msbot clone command

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1233]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 14.nlp-with-dispatch

## Describe the bug
	Error while running  ‘msbot clone’ command. It says “The syntax of the command is incorrect” or “was unexpected this time”.
## To Reproduce
         1.Install the required tools.
         2.Run msbot clone command.
	- When I give the command with all the required parameters it shows errors like “The syntax of the command is incorrect” or “was unexpected this time”.
	When I give the appId and appSecret values in between “ “, then it doesn’t show any error.

## Expected behaviour
The sample should work according the readme.

**Comment by mdrichardson** [comment]
This is a rare issue, but seems to pop up occasionally due in large part to whether `appSecret` contains special characters and in small part to the console the user uses.

The PR above will close that.

**Comment by sgellock** [comment]
Fixed with PR #1239
