### ISSUE TITLE
Production endpoint doesn't work

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1234]
## Sample information
1. Sample language: dotnetcore 
2. Sample name: 14.nlp-with-dispatch

## Describe the bug
The production endpoint in emulator doesn’t work.
## To Reproduce
1.	Install the required tools
2.	Run msbot clone
3.	Update NlpDispatchBot.cs.
-After updating it, the sample doesn’t work on Emulator.
It should be published on to Azure, then only the production endpoint works.
-Under the Update NlpDispatchBot.cs the ‘Update Line 35: HomeAutomationLuisKey’ is wrong. It should be Weather Luis Key.

## Expected behaviour
The sample should have some changes as above so that the bot works properly.

**Comment by mdrichardson** [comment]
I received the same error when running the sample per instructions. I think the issue is the step where you create the `.bot` file. When you run `msbot clone services...`, it creates a new `.bot` file so you again have to update your `appsettings.json`. I'll submit a PR that corrects this.

**Comment by mdrichardson** [comment]
My mistake. This should've been closed. User missed steps in README that mentions updating `appsettings.json` with the name of the new `.bot` file
