### ISSUE TITLE
[Question] core-GlobalMessageHandlers cancel with confirmation

### ISSUE THREAD

**Issue by volodyad** [Microsoft/BotBuilder-Samples#124]
I want to create Cancel scrollable like in core-GlobalMessageHandlers, but is should show confirmation dialog. My problem is that i can't receive dialog response from IDialog inside ScrollableBase.
I have this code
```cs
var cancelDialog = new CancelDialog();
var interruption = cancelDialog.Void<object, IMessageActivity>();
this.task.Call(interruption, null);
await this.task.PollAsync(token);
```
But how can I process cancelDialog  response, so I can call this.task.reset() ?

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
