### ISSUE TITLE
Deployment script for typescript bot generator doesn't work

### ISSUE THREAD

**Issue by liliankasem** [Microsoft/BotBuilder-Samples#1255]
## Sample information
1. Sample type:` \generators`
2. Sample language: node, typescript
3. Sample name: `generators/generator-botbuilder/generators/app/templates/echo/deploymentScripts`

## Describe the bug
The ` webConfigPrep.js` file provided by the yeoman generate for the typescript bot is wrong (at least it didn’t work for me using Deployment Centre -> Azure Pipelines for CI/CD). It was looking to replace `url=index.js` but the web.config file generated for me by Azure was using `server.js`. You also need to update all instances pointing at `server.js`, not just url=

So I went back and updated the script to this which worked for me:

```
if (fs.existsSync(path.resolve(WEB_CONFIG_FILE))) {
    replace({
        regex: "server.js",
        replacement: "lib/index.js",
        paths: ['./web.config'],
        recursive: false,
        silent: true,
    })
}
```

[bug]

**Comment by sgellock** [comment]
address in PR #1390
