### ISSUE TITLE
Conversation History Sample for Node

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#1258]
This sample should also exist in the Node list:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/22.conversation-history

**Comment by EricDahlvang** [comment]
https://github.com/EricDahlvang/BotBuilder-Samples/blob/eric/node_conversationHistory/samples/javascript_nodejs/22.conversation-history/README.md

I'll make updates, and a PR once the node sample structure is decided.

**Comment by cleemullins** [comment]
Consider having this be an experimental sample, or in the Botbuilder community. 

This may go *very well* with the Elastic Search Transcript host sample in the BotBuilder community already.

**Comment by sgellock** [comment]
@scheyal can you connect with @EricDahlvang and pull a plan together to do this correct.   there are a number of items that need to be cataloged and completed before we can say this scenario is fully supported correctly

**Comment by EricDahlvang** [comment]
This is done, and awaiting CR: https://github.com/microsoft/BotBuilder-Samples/pull/1706

**Comment by anil2025** [comment]
> This sample should also exist in the Node list:
> 
> https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/22.conversation-history

This link is broken, please update

**Comment by sgellock** [comment]
This is a massive PR.  I understand the need and interest, but I'm not sure we're thinking about where this should live and how it will be maintained.  I'm moving it out to R7 to give us time to reason more about it.

**Comment by sgellock** [comment]
@anil2025 the link is a recommendation as to where the sample could live.  if you are interested in the sample before we decide how and where to publish it, then look at PR #1706

**Comment by collegewap** [comment]
Updated link: https://github.com/Microsoft/BotBuilder-Samples/tree/v3/samples/csharp_dotnetcore/22.conversation-history

**Comment by EricDahlvang** [comment]
Closing this, since the Conversation History story for Direct Line needs to be prioritized and designed 'all up'.
