### ISSUE TITLE
Update this sample to the latest SDK syntax

### ISSUE THREAD

**Issue by vflorusso** [Microsoft/BotBuilder-Samples#1272]
### The c# implementation of the Bot sample source still uses deprecated way of state management

When compiling in VS 2017 with Bot Framework v4 the following code in the **startup.cs** class triggers an alert for an OBSOLETE use
```
var userState = new UserState(dataStore);
options.State.Add(userState);
```
In the VSIX for the Echo bot the same code looks like
```
var userState = new UserState(dataStore);
services.AddSingleton(userState);
```
This seems to be consistent across all samples. 
When built and run the sample works fine anyhow, but updating to the latest syntax is recommended as it would also be consistent with documentation and templates

**Comment by benbrown** [comment]
A fix for this is in progress and in the `samples-work-in-progress` branch.
