### ISSUE TITLE
 Error: Cannot find module '../SearchDialogLibrary'

### ISSUE THREAD

**Issue by aishjain** [Microsoft/BotBuilder-Samples#1277]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
I am getting this error, cant run the code. What to do?

**Comment by jwiley84** [comment]
Hi @aishjain! There is no information here for us to be able to help you. Can you clarify what sample you were running when you got this?

**Comment by EricDahlvang** [comment]
@aishjain The V3 samples have been moved to the v3-sdk-samples branch.

SearchDialogLibrary can be found here:

https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/demo-Search/SearchDialogLibrary

**Comment by sgellock** [comment]
we believe the customer has been helped.
