### ISSUE TITLE
.bot file not set to "Copy always" for copying to output directory

### ISSUE THREAD

**Issue by ivorb** [Microsoft/BotBuilder-Samples#1284]
The sample bot user tried, https://github.com/Microsoft/BotFramework-Samples/tree/master/SDKV4-Samples/dotnet_core/StateBot, doesn't have .bot file's property "Copy to Output Directory" is set to "Copy always" - which makes deploying not work. Can we update that setting in our sample? most samples have it correctly set.

**Comment by EricDahlvang** [comment]
Closing since https://github.com/Microsoft/BotFramework-Samples/pull/66 is a PR to fix the issue. (Note: the StateBot is actually in BotFramework-Samples, not BotBuilder-Samples)
