### ISSUE TITLE
download Attachment And Write failed nodejs

### ISSUE THREAD

**Issue by xiaolangxyz** [Microsoft/BotBuilder-Samples#1293]
## Sample information
1. Sample type: 15.handling-attachments
2. Sample language:  node js 
3. Sample name: 15.handling-attachments

## Describe the bug
I upload an image. The bot saved it. But the image can not open. I think it is not saved correctly
By the way, I'm just running the sample. I didn't change anything.

![1](https://user-images.githubusercontent.com/40823365/53860585-d64ece80-4024-11e9-8f15-3cc1275c32d7.png)
![2](https://user-images.githubusercontent.com/40823365/53860586-d64ece80-4024-11e9-8091-c1a49b5c9775.png)

**Comment by jwiley84** [comment]
I was able to repro this issue using a PDF, and the v4 emulator


![image](https://user-images.githubusercontent.com/17333688/54059451-155c5b80-41ae-11e9-980e-bb3c1a929e84.png)

**Comment by Zerryth** [comment]
Same. Tried saving `.jpg` and `.png` files, which attaches to message to the bot, like the OP had done. However when trying to open the newly saved `.jpg`/`.png` files, it throws an error.

Here's the one that Microsoft Paint throws:
![image](https://user-images.githubusercontent.com/35248895/54059558-72f0a800-41ae-11e9-9853-0a13d4033d24.png)


Should test bot in webchat, as it might be a webchat-related issue

**Comment by jwiley84** [comment]
Quick step repro:

- Emulator v4 (4.2.1) - Same error on `png`/`jpg`, `txt` files work as expected. Corrupts `PDF`
- Emulator v3 (3.5.3) - Same error on `png`/`jpg`, `txt` files come through with text replaced with [Object object]
- Webchat via iFrame from Azure -  Same error on `png`/`jpg`, `txt` files work as expected
- Facebook Messenger - Same error on `png`/`jpg`, `txt` files work as expected, **EXCEPT that the file name had to be hardcoded in**

**Comment by Zerryth** [comment]
`Emulator 3.5.36`
* can upload `.txt` and `.jpg`/`.png` attachments, without bot throwing error
* cannot open `.jpg`/`.png`. Gives error as shown about, about not liking the file type
* _can_ open `.txt` file, but the contents of the `.txt` file are replaced with only `[object Object]` written, nothing else

`Emulator 4.3.0`
* _cannot_ upload any attachments.
![image](https://user-images.githubusercontent.com/35248895/54061010-cdd8ce00-41b3-11e9-8d59-aaccc31673e6.png)

**Comment by Zerryth** [comment]
Emulator team is aware of the image upload issue and is filed [here](https://github.com/Microsoft/BotFramework-Emulator/issues/1362).

**Comment by Zerryth** [comment]
Update: issue inside the emulator has been fixed.

For users who had problems simply saving the attachment to disk, you should no longer encounter the issue of uploading your attachment, even if it is an image. 

C# attachments-bot runs without hiccup--saves attachment to `AppData/Temp` folder, and can open the saved attachment. However when running the node bot, attachment can upload, but when trying to open file type, the error of not being able to open a file of that type still persists.

Even when changing the save location of the node attachments to mimic the C# side and hard-coding save to `AppData/Temp` folder, attachment saves, but cannot open properly, so it doesn't appear to be a location issue, but perhaps a fs read/write issue
