### ISSUE TITLE
C# QnA sample 11 is missing endpoint=production section (=>500 Internal Server error when deployed)

### ISSUE THREAD

**Issue by seaen** [Microsoft/BotBuilder-Samples#1296]
## To Reproduce
1. Go to https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/qnamaker.bot
2. Observe it only contains endpoint=development section. 

## Issue
It is missing endpoint=production section, so it consistently gives 500 Internal Server error when this sample is published to production.

## Expected behavior
No 500 Internal Server errors.  "services" node should contain the production endpoint section.

[bug]

**Comment by jwiley84** [comment]
None of the samples have a 'production' endpoint in the .bot file. This needs to be added by the developer after deployment, along with App Id and App Password.
