### ISSUE TITLE
Graph sample breaks if user has no manager

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotBuilder-Samples#1299]
## Sample information
1. Sample type: /samples/javascript_nodejs/24.bot-authentication-msgraph
2. Sample language: nodejs
3. Sample name: 24.bot-authentication-msgraph

## Describe the bug
If the user that signs in does not have a manager (common in test tenants), then trying the "Me" action results in the bot saying "Oops. Something went wrong!" and a console output of
```
[onTurnError]: [object Object]
```
I was going to submit a PR to handle this case, but wasn't sure if it'd be better to just remove the manager call altogether since it doesn't add much to the sample.

## To Reproduce
1. Run the sample as intended.
2. Click on "Me" and log in with a user who does not have a manager.
3. Observe the error.

## Additional context
This occurs because the Graph call to `/me/manager` returns a 404, causing this code to throw an error:

https://github.com/Microsoft/BotBuilder-Samples/blob/8cb91cc83a53fd471637d4d6241baa89ffd76625/samples/javascript_nodejs/24.bot-authentication-msgraph/simple-graph-client.js#L96-L104

which is caught and re-thrown by this code:

https://github.com/Microsoft/BotBuilder-Samples/blob/8cb91cc83a53fd471637d4d6241baa89ffd76625/samples/javascript_nodejs/24.bot-authentication-msgraph/oauth-helpers.js#L56-L68

which ends up in the bot's `onTurnError()` handler:

https://github.com/Microsoft/BotBuilder-Samples/blob/8cb91cc83a53fd471637d4d6241baa89ffd76625/samples/javascript_nodejs/24.bot-authentication-msgraph/index.js#L47-L56

which tries to log the error to the console, but doesn't stringify it, so it shows up as `[object Object]`. (I think this is an issue throughout the samples.)

[bug]

**Comment by stevkan** [comment]
@navzam, The purpose of the API calls are simply to demonstrate how it can be done within a bot. Manager was chosen as it's a simple fetch and is inline with getting a user's name. I submitted PR #1276  that handles whether a user has a manager or not and provides an appropriate response, as such.

Closing the issue as resolved. Please feel free to re-open if you have more to add.
