### ISSUE TITLE
Bot samples should be consistent and build on each other in an incremental fashion

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/BotBuilder-Samples#1310]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: all of them

## Describe the bug

The current samples available introduce multiple unrelated topics, which makes it difficult for the partner to build on these samples incrementally. The samples have inconsistent styles, which also makes it difficult for the user to follow.

## To Reproduce
For example, [sample 6 - using card ](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/06.using-cards/bot.js) should build on [sample 3 - Welcome Users](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/03.welcome-users/bot.js) to better help user understand how the pieces are fit together. 

## Expected behavior
The Bot samples should build on each other incrementally, so that users can build on the samples easier.

## Additional context

[bug]

**Comment by jwiley84** [comment]
Hi @mydiemho! 
The samples are actually in the process of being restructured at the moment. I'll make sure this gets passed on to the SDE working on them. Be sure to watach this repo to see changes coming down in the near future!
