### ISSUE TITLE
Extra <div> in BasicBot/wwwroot/default.htm

### ISSUE THREAD

**Issue by scheyal** [Microsoft/BotBuilder-Samples#1313]
## Sample information
1. Sample type: Downloaded sample from ABS (BasicBot solution)
2. Sample language: [dotnetcore]
3. Sample name: ABS BasicBot code

## Describe the bug
There is an extra closing 
![screenshot1](https://user-images.githubusercontent.com/8867670/54153843-c4db3d00-43fd-11e9-8fe0-a0b684e9569b.png)
![screenshot2 png](https://user-images.githubusercontent.com/8867670/54153844-c4db3d00-43fd-11e9-9c71-4a45f6acb03c.jpg)

div in the wwwroot/default.htm page

## To Reproduce
1. Create an ABS service
2. Download code
3. Inspect wwwroot/default.htm

## Expected behavior
Proper HTML format

## Additional context

[bug]

**Comment by v-kydela** [comment]
[This does appear in this repo](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.basic-bot/wwwroot/default.htm#L420)

But you're talking about the Basic Bot template from Azure and not the Basic Bot sample from this GitHub repo, right?

**Comment by sgellock** [comment]
The next round of portal updates will contain this fix.
