### ISSUE TITLE
Is there a sample for Azure Search like we had in v3?

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder-Samples#1328]
**Describe the solution you'd like**
Samples on V4 using Azure Search like we had for v3 : https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/demo-Search

**Comment by EricDahlvang** [comment]
Hi @sowsan 

There's this PR that has not yet been merged: https://github.com/Microsoft/BotBuilder-Samples/pull/697
