### ISSUE TITLE
How do we know when the luis endpoint becomes available?  It's confusing

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/BotBuilder-Samples#1337]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]

I don't know if this is a question or an issue but how do you know when the endpoint is available remotely?

**Comment by stevkan** [comment]
Hi @xtianus79, can you please elaborate on your question? I'm not following what you mean when you say "luis endpoint becomes available". Assuming you have configured LUIS correctly, the endpoint is always available.

**Comment by xtianus79** [comment]
@stevkan when i was doing the sample tutorial nbs luisbot it said give the luis app time to setup 5 minutes should be fine.  But is there a better way to know when the luis app endpoint is available?

**Comment by stevkan** [comment]
No, to my knowledge there is no indicator that is returned stating when the LUIS app is available. It's a matter of simply testing. Out of curiosity, can you link the sample you were following?

**Comment by stevkan** [comment]
Closing due to lack of response. If you have additional questions on this issue, please feel free to re-open.

**Comment by xtianus79** [comment]
@stevkan the sample I will have to find
