### ISSUE TITLE
OAuthPrompt ending the current WaterfallDialog

### ISSUE THREAD

**Issue by sebastianzolg** [Microsoft/BotBuilder-Samples#1338]
## Sample information
1. Sample type: [18.bot-authentication
](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication)
2. Sample language: dotnetcore
3. Sample name: 18.bot-authentication

## Describe the bug
The step DisplayTokenAsync, which ist the last step in the WaterfallDialog "authDialog", is not reached after returning from prompt "Would you like to view your token?" in LoginStepAsync.

## To Reproduce
1. Clone repo
2. Configure oAuth Connection
3. Run sample
4. Say "hi"
5. Sign in
6. "Would you like to view your token?" ==> say "yes"
7. ==> Loops LoginStepAsync Step

## Expected behavior
Should reach DisplayTokenAsync and display the token

**Comment by sebastianzolg** [comment]
Solved with PR #1339 . It is confusing having this sample not working completely without state save, specially when you're working on OAuth flow which would let you think something is wrong with the flow while testing/learning.

**Comment by sgellock** [comment]
This is fixed in the samples-work-in-progress branch.  We will be merging that branch into master within a week or so, but if you need the fix now, that's where you can get it

**Comment by sebastianzolg** [comment]
Thanks! Quickly checked the samples and they seem to follow a new design. Is there any information what exactly is now advised? Webapi/controllers or more the style of e.g. the enterprise bot template (which I like very much).

So, where can we follow the thoughts on refactoring the samples?

**Comment by sgellock** [comment]
The samples-work-in-progress branch has the patterns introduced as part of the 4.3 release.  These are the patterns that we will be using in all our samples going forward and also these are the patterns we are recommending when using 4.3 or greater

**Comment by sebastianzolg** [comment]
Great. Is there a doc explaining what and why it was introduced with 4.3 and what the design considerations are? Or is this something the bot framework team came up with internally, promoting this through changing the samples?

What I found hard in learning v4 was the constant change and the various ways in doing things.

What will happen to the enterprise bot template? Is that still a recommended starting point for a good end to end architecture and concrete implementation? Will it be updated to match 4.3 patterns? 

Thanks

**Comment by sgellock** [comment]
docs to support 4.3 should be landing on or about March 25.  the design was driven by customer feedback around the desire to formalize the activity protocol more formally into the programming model.  these changes are additive, so if you look at them and you don't like them, you won't be forced to use them.  that said, it was our goal that they simply handling the core behavior of the activity protocol, surfacing the activity protocol patterns in an idiomatic way for C# and Node.js.  The enterprise bot template will evolve to pick up these patterns as they push out updated version.  if you've recently started a new project based on the enterprise template you are totally fine.  again, 4.3 was strictly additive and is not required.
