### ISSUE TITLE
[Question] DialogAction.validatedPrompt() has been deprecated as of version 3.8. Consider using custom prompts instead.

### ISSUE THREAD

**Issue by wolf0x** [Microsoft/BotBuilder-Samples#134]
Node.js 6.9.5 + NPM 4.6.1 + Bot Builder 3.8.3

DialogAction.validatedPrompt() has been deprecated as of version 3.8. Consider using custom prompts instead.

the source code is not updated yet.

**Comment by pcostantini** [comment]
Hi @wolf0x ,
There is an open PR with updates to SDK 3.8.2 (https://github.com/Microsoft/BotBuilder-Samples/pull/125), which replaces the usage of validatedPrompt with custom prompts.
Their usage is straightforward using an IntentDialog. See the following diff to understand how it applies to the Contoso Flowers sample:
https://github.com/Microsoft/BotBuilder-Samples/pull/125/files#diff-0f2118a4b1410336745f7ca0270ea338

Another e.g.:
````JavaScript
var EmailRegex = new RegExp(/[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/);

var lib = new builder.Library('validators');

lib.dialog('email',
    new builder.IntentDialog()
        .onBegin(function (session, args) {
            session.dialogData.retryPrompt = args.retryPrompt;
            session.send(args.prompt);
        }).matches(EmailRegex, function (session) {
            session.endDialogWithResult({ response: session.message.text });
        }).onDefault(function (session) {
            session.send(session.dialogData.retryPrompt);
        }));

// Export createLibrary() function
module.exports.createLibrary = function () {
    return lib.clone();
};
````

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
