### ISSUE TITLE
WaterfallStep ended by OAuthPrompt - Advise on proper dialog flow needed

### ISSUE THREAD

**Issue by sebastianzolg** [Microsoft/BotBuilder-Samples#1342]
## Sample information
1. Sample type: [18.bot-authentication
](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication)
2. Sample language: dotnetcore
3. Sample name: 18.bot-authentication

Similar Issues: #989 

## Describe the bug
The calling WaterfallStep is ended when prompting for user login several times during a conversation. Thus there is no clear approach on how to get a user token from bot cache without unexpected behaviour during the flow. 

## To Reproduce

**If you want to follow just the code**, then see my [modified forked bot sample](https://github.com/sebastianzolg/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication) here. 

Note the two extra comments [here](https://github.com/sebastianzolg/BotBuilder-Samples/blob/108e5a4b6b500b3d6bd2ce5a961f2eef2ef4b6de/samples/csharp_dotnetcore/18.bot-authentication/AuthenticationBot.cs#L240) and [here](https://github.com/sebastianzolg/BotBuilder-Samples/blob/108e5a4b6b500b3d6bd2ce5a961f2eef2ef4b6de/samples/csharp_dotnetcore/18.bot-authentication/AuthenticationBot.cs#L261) which explains the expected and actual behaviour

**If you want to run the provided sample, then:**
1. Configure OAuth for bot hosting
2. Add OAuth connection name to code `ConnectionName=""`
3. Run the sample

## Expected behavior
BeginDialog with OAuthPrompt should not end the current waterfall step. Instead it should publish its result to the calling step, at least when there is a token available. 

[bug]

**Comment by v-kydela** [comment]
@sebastianzolg - What channel are you using?

**Comment by sebastianzolg** [comment]
@v-kydela Bot Emulator 4.3.3 and Cortana. What ever I do, EndDialog called on WF context will end the currently running steps and proceed to the next. As a workaround I have now sort of an intermediate step before any step that needs a token.

This step is collection the previous steps result, storing it, handling the tokenRequest and then calling EndDialog passing a custom AuthenticationTurnResult(PreviousStepData, TokenResponse) to the next step. This way I can work around everything but I believe it should be easier or I'm missing something here.

**Comment by v-kydela** [comment]
@sebastianzolg - I believe I've figured out what's going on here. In the case of the token already being available, an `OAuthPrompt` calls `EndDialogAsync` from within its [`BeginDialogAsync`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L109):

> ```c#
> // Attempt to get the users token
> var output = await GetUserTokenAsync(dc.Context, cancellationToken).ConfigureAwait(false);
> if (output != null)
> {
>     // Return token
>     return await dc.EndDialogAsync(output, cancellationToken).ConfigureAwait(false);
> }
> ```

And a `DialogContext` calls `ResumeDialogAsync` from within its [`EndDialogAsync`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L203):

> ```c#
> // Return result to previous dialog
> return await dialog.ResumeDialogAsync(this, DialogReason.EndCalled, result, cancellationToken).ConfigureAwait(false);
> ```

The dialog being resumed in this case is the waterfall dialog, and so `ResumeDialogAsync` calls the next waterfall step. So beginning the `OAuthPrompt` doesn't end the current waterfall step as you thought. It just calls the next step before the previous step has completed. Once the next step completes, control returns to the previous step. This is still bad design, of course. For this reason, prompting or beginning a dialog should always happen at the end of a waterfall step and not in the middle. Even though the `OAuthPrompt` isn't ending the turn or even posting anything to the conversation, it's a mistake to try to use its results in the same waterfall step that calls it.

If you have a look at the [`samples-work-in-progress`](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/18.bot-authentication/Dialogs/MainDialog.cs#L67) branch, you will find the appropriate dialog design you're looking for:

> ```c#
> private async Task<DialogTurnResult> DisplayTokenPhase1Async(WaterfallStepContext stepContext, CancellationToken cancellationToken)
> {
>     await stepContext.Context.SendActivityAsync(MessageFactory.Text("Thank you."), cancellationToken);
> 
>     var result = (bool)stepContext.Result;
>     if (result)
>     {
>         // Call the prompt again because we need the token. The reasons for this are:
>         // 1. If the user is already logged in we do not need to store the token locally in the bot and worry
>         // about refreshing it. We can always just call the prompt again to get the token.
>         // 2. We never know how long it will take a user to respond. By the time the
>         // user responds the token may have expired. The user would then be prompted to login again.
>         //
>         // There is no reason to store the token locally in the bot because we can always just call
>         // the OAuth prompt to get the token or get a new token if needed.
>         return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), cancellationToken: cancellationToken);
>     }
> 
>     return await stepContext.EndDialogAsync();
> }
> 
> private async Task<DialogTurnResult> DisplayTokenPhase2Async(WaterfallStepContext stepContext, CancellationToken cancellationToken)
> {
>     var tokenResponse = (TokenResponse)stepContext.Result;
>     if (tokenResponse != null)
>     {
>         await stepContext.Context.SendActivityAsync(MessageFactory.Text($"Here is your token {tokenResponse.Token}"), cancellationToken);
>     }
> 
>     return await stepContext.EndDialogAsync();
> }
> ```

It's similar to the workaround you're already using in that it splits the token retrieval/usage into two steps. Does this resolve your issue?

**Comment by sebastianzolg** [comment]
Many thanks @v-kydela for the brief explanation. In my opinion this is something that people might struggle with. I've edited my forked sample to have a minimum version of [my workaround](https://github.com/sebastianzolg/BotBuilder-Samples/commit/61c06c1bef82b558a095b98bb6972e0847e05165) included. 

This way people can see a more complex scenario with multiple phases while maintaining the previous step results during authFlow. It is very easy to adopt while already reusable.

**Comment by v-kydela** [comment]
Thanks @sebastianzolg 

I'm closing this issue as resolved
