### ISSUE TITLE
Session context missing in Luis Intent Actions

### ISSUE THREAD

**Issue by dariuszparys** [Microsoft/BotBuilder-Samples#135]
I'm leveraging the Luis Intent Actions https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/blog-LUISActionBinding and would like to access the session to respond with attachments instead of a simple callback of text to the user. As the `session` context of the dialog is not available, how is someone supposed to do this?

@pcostantini @ejadib

**Comment by pcostantini** [comment]
Hi @dariuszparys,
There is an open PR with just that feature: https://github.com/Microsoft/BotBuilder-Samples/pull/130

It allows to specify an override for sending custom responses when actions are fulfilled:
https://github.com/Microsoft/BotBuilder-Samples/pull/130/files#diff-a9a8e724ec00a1d53b7cd3af8bf1b7ddR38

Hope it helps.
Regards,
-PabloC.

**Comment by dariuszparys** [comment]
Yes, this helps. Looking forward to see this functionality merged.
