### ISSUE TITLE
[nodejs/typescript] App Insights samples missing bot properties

### ISSUE THREAD

**Issue by daveta** [microsoft/BotBuilder-Samples#1361]
## Sample information
1. Sample type: \samples\ and \solutions\
2. Sample language: nodejs and typescript
3. Sample name: 
[21.luis-with-appinsights](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/21.luis-with-appinsights/index.js#L119)
[20.qna-with-appinsights](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/20.qna-with-appinsights/index.js#L72)
[Enterprise Template](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/src/index.ts)

## Describe the bug
Not clear if something changed in `restify`, but any sample that uses `Application Insights` requires a small fix below: 
```js
// Create HTTP server
let server = restify.createServer();

// Enable the Application Insights middleware, which helps correlate all activity
// based on the incoming request.
server.use(restify.plugins.bodyParser());  // <== NEED THIS LINE
server.use(ApplicationInsightsWebserverMiddleware);
```
This enables the telemetry generated by Application Insights to use `userId` and `sessionId` that are bot specific (instead of web identifiers which don't make sense).  It also adds some additional commonly used properties (ie, `activityId`, `channelId`, etc).

[bug]

**Comment by benbrown** [comment]
You should chat with @daveta because he also discovered this bug and may have fixed it elsewhere.

**Comment by CoHealer** [comment]
Removing Support resources post reassignment

**Comment by cleemullins** [comment]
@Kaiqb "We believe this is fixed as the samples have been re-done".

**Comment by daveta** [comment]
Samples now pass middleware to restify..
