### ISSUE TITLE
[ARM BugBash] Need instructions to populate LUIS appsettings.json values

### ISSUE THREAD

**Issue by scheyal** [Microsoft/BotBuilder-Samples#1365]
## Sample information
Any sample that's using LUIS

## Describe the bug

We need to specify instuctions on how to populate appsettings.json LUIS section (better yet, ssome automation around retrieving the values)

{
  "MicrosoftAppId": "",
  "MicrosoftAppPassword": "",
  "LuisAppId": "",
  "LuisAPIKey": "",
  "LuisAPIHostName": ""
}

## To Reproduce
Download sample or template that's using LUIS. Try to use LUIS in your bot.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by stevengum** [comment]
Closing issue as we're not using the README-LUIS.md in these samples at the moment, but instead pointing to some online Docs. The bug has been moved to stevengum/arm-templates-for-sample#1 so the bug is still fixed.
