### ISSUE TITLE
[ARM Bugbash] Faulty example command in readme

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder-Samples#1367]
https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/03.welcome-user/deploymentTemplates

This README gives this as an example command:

```bash
az deployment create --name "<name-of-deployment>" --template-file "all-up-template.json" --subscription "<subscription-guid>" --parameters appId="<msa-app-guid>" appSecret="<msa-app-password>" botId="<id-or-name-of-bot>" newServerFarmName="<name-of-server-farm>" newWebAppName="<name-of-web-app>" groupName="<new-group-name>" alwaysBuildOnDeploy=true
```

However, that command is missing the one required parameter of `az deployment create` which is `--location / -l`.

[bug]

**Comment by stevengum** [comment]
Done, thanks for the feedback!
