### ISSUE TITLE
[ARM Bugbash] all-up-template.json botId is unclear

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder-Samples#1368]
https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/03.welcome-user/deploymentTemplates

I encountered an error when using the example command in this readme because I used an existing botId. It's unclear that this parameter is meant to create a new bot with a new ID.

[bug]

**Comment by stevengum** [comment]
Done!
