### ISSUE TITLE
[ARM Bugbash] all-up-template.json appId is unclear

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder-Samples#1369]
https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/03.welcome-user/deploymentTemplates

I encountered an error when using the example command in this readme because I used an existing appId. It's unclear that this parameter is meant to create a new app with a new ID.

[bug]

**Comment by stevengum** [comment]
The first step which entails creating an app Registration indicates you're creating a new App which results in a new app ID. There are also instructions that indicate you're supposed to take the output appId for the second step. 

Closing as wontfix.

**Comment by v-kydela** [comment]
Well the example command I referenced has been removed in your latest commit, so in a way this was fixed.
