### ISSUE TITLE
[ARM Bugbash] the template file parameter is unclear

### ISSUE THREAD

**Issue by anusharavindrar** [Microsoft/BotBuilder-Samples#1370]
## Describe the bug
https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/03.welcome-user/deploymentTemplates

The README gives this as an example command:

```bash
az deployment create --name "<name-of-deployment>" --template-file "all-up-template.json" --subscription "<subscription-guid>" --parameters appId="<msa-app-guid>" appSecret="<msa-app-password>" botId="<id-or-name-of-bot>" newServerFarmName="<name-of-server-farm>" newWebAppName="<name-of-web-app>" groupName="<new-group-name>" alwaysBuildOnDeploy=true
```

If we run the above command, it throws up an error related to the 'all-up-template.json' file, stating  **No such file or directory: 'all-up-template.json'**. The documentation doesn't specify if we need to download the 'all-up-template.json' file. Its unclear what the template file is for.

[bug]

**Comment by stevengum** [comment]
Done, thanks for the feedback!
