### ISSUE TITLE
[ARM Bugbash] ARM Template Deploy instructions should indicate where application will be installed (subscription)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#1374]
## Information:
AZ CLI 61; dotnet corebot template

*Copied ("move") from https://github.com/Microsoft/botbuilder-tools/issues/1043

## Issue Description:
Trying to run through the instructions to deploy via ARM template and running into surprises:

1. We introduce a password, but don't describe what the password does/is used for in the docs
2. We don't remind people to specify subscription which could cause some enterprise devs some surprises when they deploy into their prod subscription

## Commands Example:
C:\repos\BotBuilder-Samples\samples\csharp_dotnetcore\13.core-bot\deploymentTemplates>az ad app create --display-name "NotPigLatinBot" --password "bananabanana" --available-to-other-tenants

**Comment by cleemullins** [comment]
@stevengum belives this is already done. Needs confirm, then resolve bug.

**Comment by stevengum** [comment]
Just verified today, these are both done.
