### ISSUE TITLE
[Question] Microsoft.Cognitive.LUIS.ActionBinding

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/BotBuilder-Samples#138]
Hi.

I was trying to implement Action Binding on my bot that uses Luis Dialogs but when creating an Action, Visual Studio can't find the ActionBinding namespace in `Microsoft.Cognitive.LUIS.ActionBinding`

I copied the imports from [here](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/Blog-LUISActionBinding/LuisActions.Samples.Shared/FindAirportByCodeAction.cs)

I have the latest Nuget package in my project for Microsoft.Cognitive.LUIS which is v2.0.2

Below my packages.config:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="4.6.0" targetFramework="net46" />
  <package id="Chronic.Signed" version="0.3.2" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder" version="3.8.1.0" targetFramework="net46" />
  <package id="Microsoft.Cognitive.LUIS" version="2.0.2" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net46" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.8" targetFramework="net46" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net46" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.4.403061554" targetFramework="net46" />
</packages>
```

Any tips on getting it to work?

**Comment by ejadib** [comment]
I don't think the LuisActionBinding lib is part of the Microsoft.Cognitive.LUIS Nuget package. Just get the LuisActionBinding bits from https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/Blog-LUISActionBinding/Microsoft.Cognitive.LUIS.ActionBinding

**Comment by AndreMantas** [comment]
Hmm I see. But will it ever be?

I cloned the whole BotBuilder-Samples repo, built it and copied the ActionBinding .dll to a folder in my project. Then I added a reference to that dll. It works, but I'm afraid it's not a good long term solution.

Any better ways?

**Comment by ejadib** [comment]
Right now, nope

**Comment by AndreMantas** [comment]
Ok thanks. This ActionBinding is really useful, would be cool if it had its own package...

I'm having problems with Custom Entities of type List (getting Exception Object must implement IConvertible. - 'System.InvalidCastException' in mscorlib.dll when user types a value that is on a list). I guess I should open a new issue?

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
