### ISSUE TITLE
How can we log  conversations of user and bot  in Microsoft Botframework  C# SDK V4  using Azure SQL database??

### ISSUE THREAD

**Issue by MounikaPedapati** [Microsoft/BotBuilder-Samples#1380]
Hello,

  I created a bot with Microsoft Botframework  C#  SDK   V4  and it is working well. Now I want to log the conversation messages of bot and user in Azure Sql database. 

I already tried this with SDK V3 , In SDK V3 I created a SqlActivityLogger class and called it from Global.asax file and opened a Sql Connection there.and  it is successfully logging conversation messages in Azure sql database.

SqlActivityLogger.cs

    `using Microsoft.Bot.Builder.History;
     using Microsoft.Bot.Connector;
     using System;
     using System.Data.SqlClient;
     using System.Diagnostics;
     using System.Threading.Tasks;

    namespace Robo
    {
     public class SqlActivityLogger : IActivityLogger
    {
    SqlConnection connection;

    public SqlActivityLogger(SqlConnection conn)
    {
        this.connection = conn;
    }
    public async Task LogAsync(IActivity activity)
    {
        string fromId = activity.From.Id;
        string toId = activity.Recipient.Id;
        string message = activity.AsMessageActivity().Text;
       // DateTime DateTimeNow = DateTime.Now;

        string insertQuery = "INSERT INTO RobosensusLog(fromId, toId, message) VALUES (@fromId,@toId,@message)";

        // Passing the fromId, toId, message to the the user chatlog table 
        SqlCommand command = new SqlCommand(insertQuery, connection);
        command.Parameters.AddWithValue("@fromId", fromId);
        command.Parameters.AddWithValue("@toId", toId);
        command.Parameters.AddWithValue("@message", message);
       // command.Parameters.AddWithValue("@datetime", DateTime.Now);

        // Insert to Azure sql database
        command.ExecuteNonQuery();
        Debug.WriteLine("Insertion successful of message: " + activity.AsMessageActivity().Text);
    }
    }
    }`

Global.asax

    `using Autofac;
     using Microsoft.Bot.Builder.Dialogs;
     using System;
     using System.Collections.Generic;
     using System.Data.SqlClient;
     using System.Diagnostics;
     using System.Linq;
     using System.Web;
     using System.Web.Http;
     using System.Web.Routing;

      namespace Robo
     {
      public class WebApiApplication : System.Web.HttpApplication
     {
         SqlConnection connection = null;
          protected void Application_Start()
          {
              //Setting up sql string connection
             SqlConnectionStringBuilder sqlbuilder = new SqlConnectionStringBuilder();
             sqlbuilder.DataSource = "Your data source";
             sqlbuilder.UserID = "userid";
             sqlbuilder.Password = "password";
             sqlbuilder.InitialCatalog = "your catalog";

             connection = new SqlConnection(sqlbuilder.ConnectionString);
             connection.Open();
             Debug.WriteLine("Connection Success");

             Conversation.UpdateContainer(builder =>
        {
            builder.RegisterType<SqlActivityLogger>().AsImplementedInterfaces().InstancePerDependency().WithParameter("conn", connection);
        });

        GlobalConfiguration.Configure(WebApiConfig.Register);
        }

       protected void Application_End()
        {
             connection.Close();
             Debug.WriteLine("Connection to database closed");

        }
    }
     }`

How can I do the same thing  in SDK V4.
Thanks in advance!

**Comment by EricDahlvang** [comment]
In Bot Builder V4, [ITranscriptStore](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.itranscriptstore) has replaced IActivityLogger.

You can find an Entity Framework implementation here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/78 (This was just committed, so it has not been merged yet).

You can create an **ITranscriptStore** that just System.Data.SqlClient, and persist any fields you want from the Activity in [LogActivityAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.itranscriptlogger.logactivityasync)

Once you have an ITranscriptStore implementation, it can be added to the Mideleware stack in Startup.cs with:

```cs
var myStore = new MySqlTranscriptStore(Configuration.GetSection("BotDataConnectionString").Value);
var transcriptMiddleware = new TranscriptLoggerMiddleware(myStore);
options.Middleware.Add(transcriptMiddleware);
```

**Comment by Mrinnaal** [comment]
Is it possible to get an sample code implemented in c# for v4? Thanks in advance :)

**Comment by shashank94** [comment]
Hi @EricDahlvang  I tried out your code and made the necessary changes in Startup.cs but I'm still facing issue. I'm implementing a logger for simple core bot in C# and trying to save the data locally in a database. Is it possible to get an example or a sample code for the same?
Thanks in advance.

**Comment by EricDahlvang** [comment]
Bot.Builder.Community.Storage.EntityFramework can be used in the same way as other V4 IStorage providers (nuget package https://www.nuget.org/packages/Bot.Builder.Community.Storage.EntityFramework/ )

'''cs
var storage = new EntityFrameworkStorage(Config["SqlConnectionString"]);
services.AddSingleton<IStorage>(storage);
services.AddSingleton<UserState>();
services.AddSingleton<ConversationState>();
'''

Then create property accessors from the  injected state objects where needed.

More information can be found here:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state

**Comment by fercom** [comment]
@EricDahlvang why are there two objects named logger?:
` public AdapterWithErrorHandler(ITranscriptStore **logger**, IConfiguration configuration, ILogger<BotFrameworkHttpAdapter> **logger**, ConversationState conversationState = null)`
I am trying to implement this but I am not sure how

**Comment by EricDahlvang** [comment]
@fercom oops, sorry about that.  I've updated the answer so the transcript store parameter is correctly named.  

Also, here is an example of how to use the EntityFrameworkTranscriptStore: https://github.com/EricDahlvang/EntityFrameworkTranscriptStoreExample

**Comment by fercom** [comment]
@EricDahlvang Ok, thanks, it works now ☺, now it stores the transcripts on a SQL Table, is it really better to store states and transcripts on SQL rather than azuure blobs? I read that SQL it is cheaper because of the continuous transactions [here](https://stackoverflow.com/questions/11540516/azure-mvc-web-app-architecture-how-to-split-data-between-sql-azure-and-azure/11541394#11541394), what do you think?

**Comment by ashish9607** [comment]
1
