### ISSUE TITLE
Invalid json in basic-bot.com cause emaultor to fail

### ISSUE THREAD

**Issue by jthake-msft** [Microsoft/BotBuilder-Samples#1381]
The json is invalid json in basic-bot.bot
https://github.com/Microsoft/BotBuilder-Samples/blob/805aec37d2790c4bc20c93364283078191bb1891/samples/csharp_dotnetcore/13.basic-bot/basic-bot.bot#L23

I did remove the extra comma and try and open in emulator following the steps https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.basic-bot#running-locally

But the bot did not respond when a message was posted.

**Comment by jwiley84** [comment]
Hi Jthake!

Can you post a screenshot of what the emulator shows in the log (lower right) section when you try to message your bot? For example:
![image](https://user-images.githubusercontent.com/17333688/55833542-9f108900-5acc-11e9-834b-de62856584dc.png)

**Comment by sgellock** [comment]
we've updated this sample.  until we release, the updated sample can be found in the samples-work-in-progress branch.  refer to 13.core-bot
