### ISSUE TITLE
[ARM BugBash] [TypeScript] If alwaysBuildOnDeploy = true, typescript needs to install on deployment

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/BotBuilder-Samples#1389]
## Sample information
This wasn't really part of the BugBash, but I came across this while playing with the new samples and ARM deployments.

## Describe the bug
If `alwaysBuildOnDeploy` is set to true when deploying a TypeScript bot, typescript needs to be installed before building or `tsc --build` will fail because tsc is not installed.

## To Reproduce
1. Download a sample or generate with Yeoman.
2. Set `alwaysBuildOnDeploy` to true in the `all-up-template`
3. Follow deployment instructions for deployment to new RG
4. View the Kudu logs and see that it fails with:

```json
  {
    "log_time": "2019-04-09T16:22:02.1642665Z",
    "id": "",
    "message": "'tsc' is not recognized as an internal or external command,",
    "type": 1,
    "details_url": null
  },
```

The bot will not build or start (because the "start" command requires a build first AND because if /lib isn't uploaded, there's no index.js) without manually installing typescript.

## Expected behavior
Bot to deploy and build in production environment successfully.

## Additional context / Possible Fixes
The reason this happens despite typescript being included as a dev dependency is because `deploy.cmd` calls `npm install` with the `--production` flag, which doesn't install the dev dependencies.

I don't know the "best" way to fix this (or if there's a better way that I didn't test), so I'll include my tests that did and didn't work and leave the final fix up to the dev team.

**Fixes that work**

* Move typescript from dev dependencies to regular dependencies in `package.json`
* Using a custom `deploy.cmd` that adds `call :ExecuteCmd !NPM_CMD! install --save typescript` before `call :ExecuteCmd !NPM_CMD! install --production`
    * You could also probably remove the `--production` flag, but that, of course, would install all dev dependencies
    * Let me know if you need more details on this one

**Attempts that didn't work**

* In `package.json`, adding `npm install --save typescript &&` to the front of the postinstall script. Not sure why that didn't work -- makes more sense to change to regular dependency anyway.

[bug]

**Comment by stevengum** [comment]
@mdrichardson thanks for tracking this and creating a new issue! 😎 

We decided this morning that we would remove the `alwaysBuildOnDeploy` flag. This way, the setting doesn't affect the build process for all types of deployments (for the zipdeploy API its value is effectively false, but for other deployment processes the default is true (aka _build_)). 

More importantly, this is the way zipdeploy was designed, it expects that the code is ready to go; by removing the param from the ARM template we follow Kudu's design and reduce complexity for users.

Closing this as we fixed it by removing the `alwaysBuildOnDeploy` parameter from the ARM templates. Doc updates for the READMEs should be live in the branch...

@sgellock FYI
