### ISSUE TITLE
[Question] ActionBinding - Resolution in matching entity throwing InvalidCastException when using Custom List Entities

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/BotBuilder-Samples#139]
I faced a problem yesterday when the user typed a value that is a list entity which would cause an InvalidCastException to be thrown in the ActionBinding project.

Exception message: `Object must implement IConvertible`

After some debugging (pictures attached) I found the problem and came up with a temporary fix.

In LuisActionResolver.cs (line ~445)

Before:

```
if (matchingEntity != null)
{
	var paramValue = matchingEntity.Resolution != null && matchingEntity.Resolution.Count > 0
		? matchingEntity.Resolution.First().Value
		: matchingEntity.Entity;

	result &= AssignValue(action, property, paramValue);
}
```

After:

```
if (matchingEntity != null)
{
	var paramValue = matchingEntity.Resolution != null && matchingEntity.Resolution.Count > 0
		? matchingEntity.Resolution.First().Value
		: matchingEntity.Entity;

	if (paramValue is JArray)
	{
		paramValue = (paramValue as JArray).First();
	}

	result &= AssignValue(action, property, paramValue);
}
```

(and the required imports)

It works for me since I don't have the same synonym in multiple entries.

I could create a pull request but I'm not sure if this is the best approach to solve the problem.

![1](https://cloud.githubusercontent.com/assets/7627975/26599539/cf54042a-4570-11e7-920b-f015f4076834.PNG)

![2](https://cloud.githubusercontent.com/assets/7627975/26599543/d69a8010-4570-11e7-8737-248c9ff116f1.PNG)

**Comment by nwhitmont** [comment]
@AndreMantas 
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
