### ISSUE TITLE
Bump JS samples' dependencies in samples-work-in-progress branch to 4.4.0

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder-Samples#1392]
## Describe the bug
~As part of the initial work, we bumped the version to 4.3.0, which isn't a listed version on NPM, as such we should go to 4.3.4.~

We want to go to **4.4.0**, because we'll be releasing the updated samples at  **//BUILD**.

[bug]

**Comment by sgellock** [comment]
pushed changes to samples-work-in-progress
