### ISSUE TITLE
[Discussion/DCR] Better management of duplicated files

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotBuilder-Samples#1396]
*Note: This focuses on the typescript `samples-work-in-progress` samples, but can definitely apply repo-wide.*

In reviewing PRs and making my own, I noticed that there's a decent number of exact-duplicate files in each sample. A few that come to mind:

* `/deploymentTemplates/*`
* `/deploymentScripts/webConfigPrep.js`
* `.eslint.js`
* `tsconfig.json`
* `tslint.json`

Right now, that's only a few files spread across 4 samples, but that could grow pretty quickly and easily.

Any time a change is made to one, it has to be made with all of them and that can be 1) painful and, 2) easy to miss one. The more we can avoid duplicate code, the better.

### Potential Solutions

One solution would be to move the shared files into their own repo and add them in as submodules. However, I could see this being somewhat difficult to manage and unintuitive for users browsing the samples.

I toyed with the idea of using git's `subtree` and `submodule` to try and duplicate the files within the *same* repo, but wasn't able to find a way to do so. If somebody knows how, this might be best.

Instead, I ended up settling on using a git pre-commit hook. It's not ready for production, but the basic idea is this:

`./samples/javascript_typescript/typescript-shared-files/` contains all of the shared files.

1. Dev makes a change to a file within the shared folder
2. Dev calls `git commit` and `pre-commit` hook is fired:

`pre-commit`:

```bash
#!/usr/bin/env bash

# Execute hooks from shared folders
echo -e "Executing custom pre-commit hooks..."
bash ./samples/javascript_typescript/typescript-shared-files/typescriptHook.sh
```

3. `pre-commit` fires a bash script for each language's shared samples folder, copying the changed file into each sample and adding them to the dev's commit.

`typescriptHook.sh` in `./samples/javascript_typescript/typescript-shared-files/`

```bash
#!/usr/bin/env bash

sharedDir="$(dirname "$0")"

# Set script dir to working dir
cd $sharedDir

# Stage any changes in sharedDir
git add .

echo -e "Copying shared TypeScript files into each Typescript sample, as necessary"

# Loop through typescript samples directories
for dir in ../*/; do
    # Loop through dir for each sample
    if [ $dir != "../$(basename $sharedDir)/" ]; then
        # Copy each file in shared directory into $dir
        cp -r . $dir
        rm -f $dir/typescriptHook.sh
        # Stage the files moved for commit
        for file in $dir*; do
            git add $dir/$(basename $file)
        done
    fi
done
```

This approach has a flaw, too:

* If a dev makes a change to say, `tslint.json` in an individual sample, it will get overwritten by the shared one. There's likely some way to programatically avoid this, but the real flaw is that it isn't obvious this will happen prior to commit.
  * For programatically avoiding this, I found it difficult to notify the user or require their input. If they run `git commit` from a command prompt, it works fine. If they run it from VS Code's Source Control, I couldn't find a way to force the user to either 1) see the Output window, or 2) pause the script, waiting for user input. Maybe if the pre-commit launches the script in an external shell...

The code can be enhanced as well but really, I'd just like to start a discussion on how best to avoid duplicate code between samples.

Per request of @stevengum, adding @cleemullins and @sgellock to discussion.

[enhancement]

**Comment by stevengum** [comment]
@sgellock, @cleemullins for this repo and the JS SDK, we could auto lint devs' code using the git commit hooks...

**Comment by sgellock** [comment]
I'm not a fan of git submodules.  I do see us duplicating a lot of things within the tree, so I'm open to a solution.

**Comment by sgellock** [comment]
mistakenly closed the issue.

**Comment by EricDahlvang** [comment]
If we can't roll the common code into the sdk, maybe we need another library.  I personally prefer the duplicated code to external dependencies.  Every sample stands alone.  External code file dependencies will add a layer of confusion for beginners.

**Comment by mdrichardson** [comment]
I took a quick browse of the `samples-work-in-progress` branch and there's really not that much that's being duplicated, especially with `webConfigPrep.js` not being needed. Here's all of the duplicates (some I'm not quite sure about without diff-ing):

**C#_dotnetcore**

* properties/launchsettings.json
* controllers/botcontroller.cs?
* DeploymentTemplates/?
* wwwroot/default.htm - except the bot name
* Program.cs?

**JS**

* deploymentTemplates/?
* .eslintrc.js

**TS**

* deploymentTemplates/?
* .eslintrc.js
* tsconfig.json
* tslint.json

Is it worth coding some pre-commit hooks to manage this, or is that just adding more complexity? If we're doing pre-commit linting, I could see adding this to that.

**Comment by sgellock** [comment]
I have no plans to add complexity to address this at this time. Thanks for cataloging it though.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
