### ISSUE TITLE
Bot Framework V4 human handoff sample NodeJS

### ISSUE THREAD

**Issue by EugeneFoo** [Microsoft/BotBuilder-Samples#1415]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Need a sample to demonstrate how to proper use of the human hand-off in bot V4 @ nodeJS. 
Current example in github by other seem to be outdated.
Node - https://github.com/GeekTrainer/botframework-v4-handoff

**Describe the solution you'd like**
A clear sample with updated code to show how we can use the human handoff interaction.

**Describe alternatives you've considered**
NA.

**Additional context**
NA.

[enhancement]

**Comment by sgellock** [comment]
dup of #1133

**Comment by tdurnford** [comment]
This is not an official sample, but I made a Human Handoff Bot using the most recent NodeJs SDK that you can take a look at. https://github.com/tdurnford/botframework-human-handoff

Hope this helps.

**Comment by EugeneFoo** [comment]
Thanks alot @tdurnford
