### ISSUE TITLE
Unclear whether samples should contain documentation comments or not

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder-Samples#1416]
The samples are currently inconsistent with regard to whether they contain documentation comments or just regular comments. An example of a sample with documentation comments is [EchoWithCounter](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/02.b.echo-with-counter/EchoWithCounterBot.cs):

```c#
    /// <summary>
    /// Represents a bot that processes incoming activities.
    /// For each user interaction, an instance of this class is created and the OnTurnAsync method is called.
    /// This is a Transient lifetime service. Transient lifetime services are created
    /// each time they're requested. Objects that are expensive to construct, or have a lifetime
    /// beyond a single turn, should be carefully managed.
    /// For example, the <see cref="MemoryStorage"/> object and associated
    /// <see cref="IStatePropertyAccessor{T}"/> object are created with a singleton lifetime.
    /// </summary>
    /// <seealso cref="https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1"/>
    public class EchoWithCounterBot : IBot
```

I think documentation comments are important even when there's no intention to generate documentation files because they still help with Intellisense. But in any case, a decision should be reached for the sake of consistency.

[bug]

**Comment by v-kydela** [comment]
I just had a look in the samples-work-in-progress branch and it looks like it's much harder to find an example of documentation comments than I thought. They can be seen in [MultiLingualBot](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/17.multilingual-bot/Bots/MultiLingualBot.cs), at least.

**Comment by v-kydela** [comment]
Actually, documentation comments seem to be pretty common in Node. Look at [core-bot](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/13.core-bot/dialogs/mainDialog.js):

```node
    /**
     * The run method handles the incoming activity (in the form of a TurnContext) and passes it through the dialog system.
     * If no dialog is active, it will start the default dialog.
     * @param {*} turnContext
     * @param {*} accessor
     */
    async run(turnContext, accessor) {
```

**Comment by sgellock** [comment]
We are no longer adding /// comments to C# samples

**Comment by sgellock** [comment]
I've updated any sample that used /// comments.  these changes are staged in the samples WIP branch.
