### ISSUE TITLE
Sample Address/Port Doesn't Match HTML Page's Instructions

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/BotBuilder-Samples#1417]
## Sample information
C# Samples in `samples-work-in-progress` branch

## Describe the bug
Seems like the C# samples listen for a random localhost port now, and it doesn't match what the HTML page displays:

![image](https://user-images.githubusercontent.com/35248895/56328451-e7b2ec80-6133-11e9-9845-1e7e4c7aafd9.png)

## To Reproduce
Start up multiple C# samples and wait for the HTML page to pop up

## Expected behavior
We should either 
1. ensure all of the samples start on 3978 
or 
2. dynamically pull the page address, and put it there

[bug]

**Comment by sgellock** [comment]
@Zerryth all samples should default to 3978

**Comment by sgellock** [comment]
all Properties/launchSettings.json files should be configured to use the 3978 ports.  I've update the samples that haven't done this
