### ISSUE TITLE
Bot handoff

### ISSUE THREAD

**Issue by Santoshbsk** [Microsoft/BotBuilder-Samples#1424]
Is bot to human handoff possible in V4? If yes, can I have a sample for the same?

**Comment by tdurnford** [comment]
Dup of https://github.com/Microsoft/BotBuilder-Samples/issues/1133 

These are not official handoff samples, but I would recommend taking at look: 

C#: https://github.com/tompaana/intermediator-bot-sample
Node: https://github.com/tdurnford/botframework-human-handoff
