### ISSUE TITLE
Work in progress welcomeBot sample double check members being added

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#1436]
In the [samples-work-in-progress welcomeBot](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/03.welcome-users/bots/welcomeBot.js#L32) sample, we seem to be double-checking if members have been added:

```js
        this.onMembersAdded(async (context, next) => {
            // Do we have any new members added to the conversation?
            if (context.activity.membersAdded.length !== 0) {
            ...
```
Am I wrong to believe that the callback passed in to `onMembersAdded` should only run when members have been added? If this is the case, shouldn't `context.activity.membersAdded.length` always be greater than 0? 

Please let me know if I'm misunderstanding the API. Also, I know these samples are WIP, so if there's another way you'd like feedback, let me know!

[bug]

**Comment by stevengum** [comment]
You are correct, the code in the sample is double-checking if members have been added. We will get this fixed, thanks for reporting the issue!

[activityHandler.ts code in question](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/activityHandler.ts#L210)

**Comment by stevengum** [comment]
@ryanvolum I just realized I didn't answer your last question, but leaving feedback here works great. 😄

**Comment by stevengum** [comment]
Closing as the fix went in.
