### ISSUE TITLE
JS botbuilder echobot template should use onMembersAdded

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1440]
## Sample information
1. Sample type: [\template\]
2. Sample language: [nodejs, TypeScript]
3. Sample name: generator-botbuilder/generators/app/templates/echo/
4. Branch: samples-work-in-progress

## Describe the bug
1. The bot.js file should use the `onMembersAdded` handler, instead of the `onConversationUpdate` handler, to align with the C# VSIX template. (Or the other way around, if the JavaScript is a better approach.)
1. The bot.js file should be generated in a **bots** subdirectory, to match what we see in the samples, such as the 02.echobot, for instance.

## To Reproduce
1. See the generator's [bot.js](https://github.com/Microsoft/BotBuilder-Samples/blob/ffdaf348ba16a098ddf3318ced13bfdd74e07aa9/generators/generator-botbuilder/generators/app/templates/echo/bot.js#L15) or [bot.ts](https://github.com/Microsoft/BotBuilder-Samples/blob/ffdaf348ba16a098ddf3318ced13bfdd74e07aa9/generators/generator-botbuilder/generators/app/templates/echo/bot.ts#L15) file.
1. Compare to the equivalent code in the VISX [EchoBot.cs](https://github.com/Microsoft/BotBuilder-Samples/blob/ffdaf348ba16a098ddf3318ced13bfdd74e07aa9/generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Bots/EchoBot.cs#L21) file.

## Expected behavior
The logic of the JS/TS echo bot and the C# echo bot generated from the templates should be as close to identical as possible.

[bug]

**Comment by sgellock** [comment]
fixes for this have been merged into samples-work-in-progress
