### ISSUE TITLE
Sample unit tests on bot with Dialogs and Prompts

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/BotBuilder-Samples#1443]
Please create a sample of project with all the bot stuff (Dialog, prompts, etc.) unit tested to show how to mock some object such as DialogSet, WaterfallStepContext, etc.

**Comment by gabog** [comment]
Hi @nimbusparis, thanks for the feedback, we are planning to add additional testing examples and tools support as part of 4.5. 

[This page](https://github.com/Microsoft/BotBuilder/blob/master/specs/testing/testing.md) contains some background on our general approach. 

For a complete list of the testing scenarios we are considering see [Bot Testing Issues](https://github.com/Microsoft/BotBuilder/milestone/1).

I will close this issue for now, please add your comments on the stories above if there's anything in particular you'd like to see that is not covered there.

Thanks again.

Gabo

PS: For a sneak peak of the work being doing, you can check the [CoreBotTests](https://github.com/Microsoft/botbuilder-dotnet/tree/gabog/CoreBotTests) branch (check the https://github.com/Microsoft/botbuilder-dotnet/tree/gabog/CoreBotTests/tests/Microsoft.Bot.Builder.TestBot.Tests project, it is early days and things are subject to change but it should give you an idea).
