### ISSUE TITLE
[4.5 Samples]: Remove `logger` from the Node.js samples

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#1465]
## Sample information
1. Sample type: samples
2. Sample language: JavaScript & TypeScript Node.js samples
3. Sample name: All applicable samples

## Describe the bug
The wrapper around `console` (i.e. `const logger = console;`) is superfluous. We're going to back it out and instead call `console.log()` or the applicable `console` method as needed.

`logger` as an argument will not be passed to the Bot constructors, nor will it continue to exist.

## To Reproduce
1. Go to Core bot in JavaScript or TypeScript
2. Open the `index.js/ts` for thesample
3. See the line with `const logger = console;`
4. Pause
5. Look again
6. Be baffled

[bug]

**Comment by v-kydela** [comment]
May ask for some clarification?

`console` is also assigned to `logger` in the `DialogBot` and `MainDialog` classes. Is the logger only going to be removed from `index.js/ts` or is it going to be removed from everywhere?

My understanding was that the logger argument served the purpose of parity with the C# samples, and also the purpose of allowing something other than `console` to be provided for logging, as indicated by the [comment](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/13.core-bot/index.js#L51): `// Pass in a logger to the bot. For this sample, the logger is the console, but alternatives such as Application Insights and Event Hub exist for storing the logs of the bot.`

Is this no longer needed?

**Comment by tracyboehrer** [comment]
What is the expected change for this issue?  I have the same question as Kyle.

**Comment by sgellock** [comment]
Yes.  We were being too clever.  let's just use console.log as it's the only logger we use in the js/ts samples
