### ISSUE TITLE
Typo in VSIX description

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1466]
## Sample information
1. Sample type: [\VSIX\] template
2. Sample language: [dotnetcore]
3. Sample name: <Echo Bot template>

## Describe the bug
Typo "echos" should be "echoes".

## To Reproduce
1. In https://github.com/Microsoft/BotBuilder-Samples/blob/2c2630f611e26a6061f59f727c2a9883e97d8559/generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec#L7
1. There are a few places when you look at the description for the template in Visual Studio where "echos" appears.

[bug]

**Comment by sgellock** [comment]
fix merged into samples WIP branch
