### ISSUE TITLE
Remove unused/unreferenced bot.js file from node.js #18

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#1468]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [nodejs]
3. Sample name: 18.bot-authentication (branch: samples-work-in-progress)

## Describe the bug
The **bot.js** file at the root is obsolete and unused. It's continued presence is confusing.

## To Reproduce
1. Notice the [bot.js](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/18.bot-authentication/bot.js) file at the root of the project.
2. In index.js, notice a completely different bot is created and used by the adapter:
https://github.com/Microsoft/BotBuilder-Samples/blob/561dc1d9cd9414e9f59448732ed7741ce3d3303a/samples/javascript_nodejs/18.bot-authentication/index.js#L12
https://github.com/Microsoft/BotBuilder-Samples/blob/561dc1d9cd9414e9f59448732ed7741ce3d3303a/samples/javascript_nodejs/18.bot-authentication/index.js#L52

## Expected behavior
The sample should not include any code files that are not actually part of the sample.

[bug]

**Comment by sgellock** [comment]
this has been fixed in the samples WIP branch

**Comment by sgellock** [comment]
ahh, ok.  in my hast I misred the issue.

**Comment by JonathanFingold** [comment]
No worries.

**Comment by sgellock** [comment]
OK @JonathanFingold , it's removed now, for real
