### ISSUE TITLE
[Question] Node\intelligence-LUIS doesn't respond as expected

### ISSUE THREAD

**Issue by swatikurra17** [Microsoft/BotBuilder-Samples#148]
I'm trying the Node\intelligence-LUIS example locally in the bot-emulator, it always reply back 

Sorry, I did not understand 'Hotel'. Type 'help' if you need assistance.
no matter what I type, even 'help'.

I have specified my LUIS endpoint, and I'm getting results by typing the url directly in the browser. Please help in rectifying this issue. 
Thanks
Swati

**Comment by pcostantini** [comment]
Hi @swatikurra17 , be sure to remove the 'q' parameter from the url when adding it to the .env file (or the Azure Web Site AppSettings)
Also, you can try testing the URL invoking the recognizer directly:

`builder.LuisRecognizer.recognize("This is a test", "[model_url]", console.log)`

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
