### ISSUE TITLE
Need sample to show telemetry with extensibility

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#1480]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore, nodejs or typescript]

**Comment by cleemullins** [comment]
Added this (as a PR) to an existing samples. Related to:
https://github.com/microsoft/BotBuilder-Samples/pull/1499

**Comment by cleemullins** [comment]
We are choosing to not do this at this time. Discussion w/ @munozemilio and @sgellock  (by proxy).
