### ISSUE TITLE
Documentation incorrectly makes reference to .bot file in "Interacting With Your Bot Using the Emulator"

### ISSUE THREAD

**Issue by SarahSexton** [microsoft/BotBuilder-Samples#1493]
## Sample information
1. Sample type: BotBuilder-Samples/generators/dotnet-templates/
2. Sample language: dotnetcore
3. Sample name: ".NET Core SDK Templates"

## Describe the bug
This documentation is out of date, due to the .bot file being deprecated on May 1st.

## To Reproduce
1. Go to https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/dotnet-templates#interacting-with-your-bot-using-the-emulator
2. Scroll down to "Interacting With Your Bot Using the Emulator" section
3. See incorrect documentation: "Launch the Bot Framework Emulator v4 and open the generated project's .bot file."

## Expected behavior
Creating a new bot by running the ```dotnet new corebot -n MyCoreBot``` command on Windows no longer generates a ```.bot``` file. The docs should say that in order to interact with the bot using the Emulator, the user will have to enter the URL "http://localhost:3978/api/messages" in the emulator. 

## Screenshots
![image](https://user-images.githubusercontent.com/8670346/57258490-6c957580-7011-11e9-84c2-c470f23cf9e9.png)

[bug]

**Comment by SarahSexton** [comment]
Comment: It will also be great to see this dotnet CLI approach documented on the official docs.

**Comment by stevkan** [comment]
Submitted PR #1500 that replaces reference to .bot file with steps to connect to Emulator.
