### ISSUE TITLE
Where is sample 12 for Luisai? 

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotBuilder-Samples#1498]
The personalizer asks that the sample #12 be used to complete its instructions.  12 is missing.

**Comment by jwiley84** [comment]
Hi @xtianus79!

The samples recently underwent a massive update. One update was removing that sample. I'll start looking into broken references to it this afternoon.  For now, sample [#13](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot) has LUIS for examples in showing how to connect NLP to bot framework. If you need something about the old LUIS bot specifically, I have a copy on the repo that I forked a few months ago [here](https://github.com/jwiley84/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/12.nlp-with-luis)

**Comment by xtianus79** [comment]
@jwiley84 nope thank you that clears it up. I will look into 13

Also, here is where I found a reference.  https://github.com/Azure-Samples/cognitive-services-personalizer-samples/blob/master/samples/ChatbotExample/README-LuisBot.md

to note, that example the chatbot sample. It doesn't work either.  In general.
