### ISSUE TITLE
Cannot connect to emulator

### ISSUE THREAD

**Issue by paramda** [microsoft/BotBuilder-Samples#1502]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 02.echo-bot

## Describe the bug
Samples cloned from github doesn't work with emulator even though README says "copy url http://localhost:3978/api/messages in emulator". It opens it's own cmd window where it echoes back the messages I type.

"Taking longer than usual to connect" is the message seen on emulator. 

## To Reproduce
1. Download Bot builder framework - latest 4.4.3
2. Clone GitHub Bot samples "git clone https://github.com/microsoft/botbuilder-samples.git"
3. In VS, run (F5) the EchoBot sample
4. Run Emulator and create bot with url http://localhost:3978/api/messages

## Expected behavior
Emulator should connect to localhost and display the chat window. Emulator works while creating an EchoBot using the framework in VS Studio but not with samples.

## Screenshots
![image](https://user-images.githubusercontent.com/46635755/57466303-5cb6a500-724e-11e9-83d2-28590388ffda.png)
![image](https://user-images.githubusercontent.com/46635755/57466434-a1424080-724e-11e9-9745-239d84f7c54b.png)
![image](https://user-images.githubusercontent.com/46635755/57466453-ac956c00-724e-11e9-9ff1-b3ee55d7d889.png)

## Additional context
Visual Studio: 2017 
Emulator: 4.4.1
Bot Framework: 4.4.3

[bug]

**Comment by sgellock** [comment]
@paramda, in looking at the screen attachments you've provided, it looks like you are running console-echo and not echo-bot.  console-echo's readme does not have instructions for using the emulator as it's a console application.  https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/01.console-echo

echo-bot, which can use Emulator has correct steps.  https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.echo-bot

if your goal was to run echo-bot, then make sure that VS is launching that sample for you, as it looks as if you are running the console-echo sample.
