### ISSUE TITLE
aka.ms links 'about-bot-adapter' and 'bot-services' lead to same URL

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotBuilder-Samples#1510]
## Sample information
All samples

## Describe the bug
When going through the comments of the samples, there are two urls that redirect to the same document. 
`https://aka.ms/bot-services`
`https://aka.ms/about-bot-adapter`

both lead to: `https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=csharp`

## Expected behavior
Presumably these two links should direct to different docs.

[bug]

**Comment by Kaiqb** [comment]
@corinagum - which sample file these links are in?

**Comment by corinagum** [comment]
@Kaiqb they are predominately in the generators and nodejs samples: 

![image](https://user-images.githubusercontent.com/14900841/59302988-1cca4f80-8c4a-11e9-81d3-bf05f4fdf63d.png)
![image](https://user-images.githubusercontent.com/14900841/59303015-2784e480-8c4a-11e9-8812-50cc46db8839.png)

**Comment by Kaiqb** [comment]
We used to have separate topics about bot and adapter, but those were combined into one. That is why I think there are two links. The links are going to the combined topic which is correct.
