### ISSUE TITLE
The code doesn't work with Microsoft Teams channel

### ISSUE THREAD

**Issue by kulkarninc** [microsoft/BotBuilder-Samples#1513]
Steps to reproduce
We created the bot using the template. 
Then added Microsoft Teams as one of the channel. 
Created app package inside Teams to test the bot. (Added required trusted domain so sign in button works.)
When clicked on "Sign In" button in the teams the bot is going in infinite loop.

**Comment by anshul2117** [comment]
Facing similar issues. 

 
![image](https://user-images.githubusercontent.com/6558762/57903459-01bf1800-7823-11e9-8c98-12d771a7ff53.png)

**Comment by Jeffders** [comment]
There have been some changes to Teams that require a workaround until we can update the OAuthCard:

1.	Keep using the button action of SignIn for teams (i.e. you do not need the middleware).

2.	If you are using something like the auth sample from botbuilder-samples, you can add this to the AuthBot class:
protected override async Task OnUnrecognizedActivityTypeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    if (turnContext?.Activity.Type == ActivityTypes.Invoke)
    {
        await turnContext.SendActivityAsync(
            new Activity()
            {
                Type = ActivityTypesEx.InvokeResponse,
                Value = null
            });
        await Dialog.Run(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);        
    }
}

**Comment by Anshul21** [comment]
@kulkarninc public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            DialogContext dc = null;

            switch (turnContext.Activity.Type)
            {
                case ActivityTypes.Message:
                    await ProcessInputAsync(turnContext, cancellationToken);
                    break;
                case ActivityTypes.Event:
                case ActivityTypes.Invoke:
                    // This handles the Microsoft Teams Invoke Activity sent when magic code is not used.
                    // See: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card#getting-started-with-oauthcard-in-teams
                    // Manifest Schema Here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema
                    // It also handles the Event Activity sent from The Emulator when the magic code is not used.
                    // See: https://blog.botframework.com/2018/08/28/testing-authentication-to-your-bot-using-the-bot-framework-emulator/

                    // Sanity check the activity type and channel Id.
                    if (turnContext.Activity.Type == ActivityTypes.Invoke && turnContext.Activity.ChannelId != "msteams")
                    {
                        throw new InvalidOperationException("The Invoke type is only valid onthe MSTeams channel.");
                    }
                    dc = await _dialogs.CreateContextAsync(turnContext, cancellationToken);
                    await dc.ContinueDialogAsync(cancellationToken);
                    if (!turnContext.Responded)
                    {
                        await dc.BeginDialogAsync("graphDialog", cancellationToken: cancellationToken);
                    }
                    if (turnContext?.Activity.Type == ActivityTypes.Invoke)
                    {
                        await turnContext.SendActivityAsync(
                        new Activity()
                        {
                            Type = ActivityTypesEx.InvokeResponse,
                            Value = null
                        });
                    }

                        break;
                case ActivityTypes.ConversationUpdate:
                    if (turnContext.Activity.MembersAdded != null)
                    {
                        await SendWelcomeMessageAsync(turnContext, cancellationToken);
                    }

                    break;
            }
        }
