### ISSUE TITLE
Issue publish bot on skype

### ISSUE THREAD

**Issue by praveemich** [microsoft/BotBuilder-Samples#1514]
![image_2019_05_16T07_45_50_486Z](https://user-images.githubusercontent.com/8176427/57995782-8b9c0900-7ae1-11e9-8262-82d9d33b8b64.png)
cant publish bot on skype have issue on
"Your bot did not respond to our Ping request with a success code. Please verify your bot is running and responsive before Publishing your bot.
The error received from your bot was: InternalServerError(500), Internal Server Error"

**Comment by jwiley84** [comment]
Hi @praveemich 

Despite 'Activity.Ping' being deprecated ages ago, it would seem that Skype is looking for an activity that doesn't exist anymore. Here is work around handled it in the OnTurnAsync method, specifically, in the turnContext check:

```
public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            if (turnContext == null) { BOT CODE FOR ERRORS }
            if (turnContext.Activity.Type == ActivityTypes.Message) { BOT CODE FOR TALKING }  
            else if (turnContext.Activity.Type == ActivityTypes.ConversationUpdate) { BOT CODE FOR WELCOME IN NON-SKYPE }
            else if (turnContext.Activity.Type == ActivityTypes.ContactRelationUpdate) { BOT CODE FOR WELCOME IN SKYPE}

            //HERE'S WHERE SKYPE IS LOOKING FOR A PING
            else if (turnContext.Activity.Type == ActivityTypes.Event)
            {
                if (turnContext.Activity.ChannelId == "facebook")
                {
                    //handle ALL OTHER channel specific events here
                    await turnContext.SendActivityAsync($"{turnContext.Activity.Type} event detected", cancellationToken: cancellationToken);
                }
                else
                {
                    //handle skype with empty, because skype freaks out if you detect it's channel on the ping
                }
            }
            else
            {
                await turnContext.SendActivityAsync($"{turnContext.Activity.Type} event detected", cancellationToken: cancellationToken);
            }
```

For more information, please see my post here: 
https://github.com/Microsoft/botbuilder-dotnet/issues/1074

**Comment by praveemich** [comment]
> turnContext.Activity.Type == ActivityTypes.ConversationUpdate

Thank you so much, its working
