### ISSUE TITLE
Access Denied in Ms Teams downloading inline attachment

### ISSUE THREAD

**Issue by giuleon** [microsoft/BotBuilder-Samples#1515]
Hi,

I'm trying to get the arraybuffer of an image attached via copy paste in the text box of Teams, following this example:
https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/15.handling-attachments/bots/attachmentsBot.js

at the point:
![image](https://user-images.githubusercontent.com/3914090/58007495-a7f07380-7aea-11e9-9eea-28fdbd5dea36.png)

I get an access denied error in Teams, I tried to add in the header the Bearer Token but the error doesn't change, could you tell me more about this use case?

**Comment by dmvtech** [comment]
I am taking a look at this

**Comment by dmvtech** [comment]
As you have somewhat identified, this is a permission issue. 

Teams supplies an additional property in the message content called `downloadUrl`. This ulr contains a temporary auth token to retrieve the content from the location (ODfB). 

Here would be some changes you could make to handleIncomingAttachment


```
let isteams = false;
        if(turnContext.activity.channelId === "msteams") {
            isteams = true;
        }

        // Prepare Promises to download each attachment and then execute each Promise.
        const promises = turnContext.activity.attachments.map(attachment => this.downloadAttachmentAndWrite(attachment, isteams));   
```

And downloadAttachmentAndWrite:



```
let url = "";
        //console.log(turnContext);
        if (isteams) {
            url = attachment.content.downloadUrl;
        } else {
            // Retrieve the attachment via the attachment's contentUrl.
            url = attachment.contentUrl;
        }
```

**Comment by CoHealer** [comment]
@giuleon, do you still require assistance. If not, please let us know and we'll close the issue.

**Comment by giuleon** [comment]
@dmvtech thanks for your reply I'll try this evening, I'll give you feedback @CoHealer

**Comment by giuleon** [comment]
I made some test, when I attach an image inline, it means via copy paste in the Teams text box I have this result:
![image](https://user-images.githubusercontent.com/3914090/59152560-b75a4100-8a46-11e9-9934-923b9b76c35c.png)

![image](https://user-images.githubusercontent.com/3914090/59152553-8843cf80-8a46-11e9-8cf5-735c8b49719a.png)

The problem is that, if I try to download the picture by using the contentUrl (first element in the attachments array) I get an access denied.
Differently if I parse content in the second element of the array I'm able to get a different url of the image and it works:
![image](https://user-images.githubusercontent.com/3914090/59152582-394a6a00-8a47-11e9-9928-7d6da7f4501a.png)

In fact if I put the first url in the browser where I'm already logged I receive this message:
![image](https://user-images.githubusercontent.com/3914090/59152592-7d3d6f00-8a47-11e9-90e6-d04d4fc4cad5.png)

but If I use the second url which come from the second element of the array that's the result:
![image](https://user-images.githubusercontent.com/3914090/59152614-0ce31d80-8a48-11e9-963d-d4f0b66c54ef.png)

**Comment by dmvtech** [comment]
I'm not able to get the same. Regarding:

> when I attach an image inline, it means via copy paste in the Teams text box

I am not able to paste into the text box. I can use the paperclip to attach an item or I can drag and drop an image. But I am unable to get any scenario to show 2 objects in attachments.

**Comment by giuleon** [comment]
Here how you can do this:
![Attach Inline Image](https://user-images.githubusercontent.com/3914090/59350276-ff65b600-8d1b-11e9-848d-61d363dc46ba.gif)

**Comment by dmvtech** [comment]
Thank you. I understand what I was doing wrong now.

Strange. While I can get the behavior now, with the two attachments (one is a preview it appears), I am ***not*** able to retrieve the image using the parsed url as you are.

You might be able to accomplish this by logic such as (sudo code):

```
If(msteams)
{
	If  (attachments.length > 1)
	{
		logic to grab second content and parse for url
	}
	else
	{
		logic to use attachment.content.downloadUrl
	}
}
```
but I would suggest more testing to make sure it works for everyone in your org.

I'll look into this further and see if there any other options.

**Comment by CoHealer** [comment]
@giuleon, have you tried using the suggestion @dmvtech provided? Do you still require assistance. If not, please let us know and we'll close the issue.

**Comment by CoHealer** [comment]
Closing post recommendation. If this does not resolve your issue, please re-open and we'll look into other options.
