### ISSUE TITLE
Add sample for how to use the US Government data center

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#1516]
From @Jeffders The SDK has changed the pattern for how customers designate that they are going to use the US Government data center. See below for what I told Motorola to do (I do not know their SDK version, so I gave them both).

There seem to be two work items here:
1.	Add documentation on how to configure this for both per 4.4 and post 4.4 SDKs
2.	Create accompanying samples

Is there a place I can add these work items? They apply to all the SDKs and versions.

Further details:

In your bot, you need to configure your bot to validate and create US Government data centers.

The steps are to:

1.	Add a “channel provider” setting in your appsettings.json (or the App Service Settings). Set it specifically to this name/value constant as this signals to the SDK to “use US Government values”:
ChannelService = "https://botframework.azure.us"

2.	You need to add a ConfigurationChannelProvider in your startup.cs file (if you are using .NET core). How you do this greatly depends on which version of the SDK you are using (before 4.4 or 4.4 or above). Here are some ways you can do this:
a.	4.4 or above:
In your startup .cs, in your ConfigureServices method, you need to create a ConfigurationChannelProvider instanace. If you are using the BotFrameworkHttpAdapter class, all you need to do is to inject this as singleton into the service collection like this: services.AddSingleton<IChannelProvider, ConfigurationChannelProvider>(); If you are creating your own adapter, you just need to pass this instance into the constructor of the adapter you are creating.
b.	Before 4.3:
In your startup.cs file, in your ConfigureServices method, find the AddBot method. While setting the options, you need to make sure you are adding: options.ChannelProvider = new ConfigurationChannelProvider();

**Comment by cleemullins** [comment]
Add to docs and/or FAQ.

**Comment by EricDahlvang** [comment]
This might be one good place for this information: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-services-aiandcognitiveservices#azure-bot-service

**Comment by Kaiqb** [comment]
The information on using Gov datacenter was added to the [FAQ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0).
