### ISSUE TITLE
Sample should include passing variables to the JSON instead of hard coding data which isn't a real world example

### ISSUE THREAD

**Issue by mlipinski** [microsoft/BotBuilder-Samples#1517]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by jwiley84** [comment]
Hi @mlipinski 

Which sample are you talking about? Which language? Is there a particular issue you're seeing? Please clarify your bug.

**Comment by jwiley84** [comment]
Closing for lack of clarification.
