### ISSUE TITLE
Echo and Core bot needs structural changes to work in Gov

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1519]
## Describe the bug
ABS portal templates in C# won't work in Gov env

[bug]

**Comment by cleemullins** [comment]
We believe the release of 4.4.4 SDK allows these templates to be authored now. 

This may be compelted now.

**Comment by stevengum** [comment]
I believe we need to actually get these changes into this repo, as we cut private bits/or separately updated the samples provided to the ABS team to work in Gov.

**Comment by stevengum** [comment]
### Individual work items per samples language
- [ ] #1558 (@sgellock, **C#**)
- [ ] #1556 (@stevengum, **JS**, no sample changes required other than a dependency bump)

**Comment by sgellock** [comment]
Closing this as the C# issue is resolved.  The JS issue is still open and will be resolved once 4.5.x JS modules are published.
