### ISSUE TITLE
samples/csharp_dotnetcore/17.multilingual-bot/appsettings.json

### ISSUE THREAD

**Issue by sremy91** [microsoft/BotBuilder-Samples#1522]
## Sample information
1. Sample type: samples
2. Sample language: csharp_dotnetcore
3. Sample name: 17.multilingual-bot

## Describe the bug
I guess there is a typo mistake in appsettings.json
Key name is set to 

`"TranslationKey": "<Your translation key here>"`

wherease in ce C# code another key is used:

`        public MicrosoftTranslator(IConfiguration configuration)
        {
            var key = configuration["TranslatorKey"];
            _key = key ?? throw new ArgumentNullException(nameof(key));
        }
`

## Expected behavior
One or the other typo should be fixed: **TranslationKey** vs **TranslatorKey**

[bug]

**Comment by EricDahlvang** [comment]
@sremy91 Thank you for reporting this.
