### ISSUE TITLE
[Generators][Linux] Dependencies issue when deploying with netcoreapp 2.1

### ISSUE THREAD

**Issue by ParadoxARG** [microsoft/BotBuilder-Samples#1524]
## Sample information
1. Sample type: \generators\
2. Sample language: dotnetcore - netcoreapp2.1
3. Sample name: EchoBot

## Describe the bug
The generated EchoBot for NetCoreApp has some conflicts in the references. In consequence, it fails when trying to deploy it to an Azure Linux Host using netcoreapp2.1.

Conflicting references:
- Microsoft.Bot.Builder.Integration.AspNet.Core 4.4.3 and Microsoft.AspNetCore.App 2.1.0.
For all the following libraries Microsoft.Bot.Builder.Integration.AspNet.Core requires a version >= 2.1.1 and Microsoft.AspNetCore.App requires version 2.1.0
    - Microsoft.Extensions.Configuration
    - Microsoft.Extensions.Configuration.Abstractions
    - Microsoft.Extensions.Configuration.Binder
    - Microsoft.Extensions.DependencyInjection.Abstractions
    - Microsoft.Extensions.Logging
    - Microsoft.Extensions.Logging.Abstractions
    - Microsoft.Extensions.Options
    - Microsoft.Extensions.Primitives

## To Reproduce
1. Install EchoBot template

```bash
# Install EchoBot template
dotnet new -i Microsoft.Bot.Framework.CSharp.EchoBot
```

2. Generate an EchoBot with netcoreapp2.1 as the targeted framework

```bash
# Generate an Echo Bot (netcoreapp2.1)
dotnet new echobot --framework netcoreapp2.1 -n MyEchoBot
```

3. Deploy the bot with git to your Azure webapp hosted in linux with netcoreapp2.1([guide for setting up the linux host](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore))

![image](https://user-images.githubusercontent.com/42191764/58105654-3e8d6500-7bbd-11e9-8961-af933fcb97f8.png)

## Expected behavior
The bot should be deployed without errors

[bug]

**Comment by sgellock** [comment]
I'm able to run the repo steps on an Ubuntu 18.04 distro (in a VM) without errors.

**Comment by EricDahlvang** [comment]
The issue here appears to be related to: https://github.com/aspnet/Universe/issues/1180 It seems we should have referenced Microsoft.Extensions.Logging v 2.1.0 instead of v 2.1.1

So far, I've found two ways to deploy an echo bot to a linux host successfully:

1) Directly reference the v 2.1.1 of Microsoft.Extensions. packages within the project
```cs
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.1.1" />
```

2) Upgrade the project, and the App Service to net core 2.2

If we want to avoid this issue future customers, we will need to either 
- reference the above packages in our template projects 
- downgrade Microsoft.Extensions.Logging in our libraries to v 2.1.0 
- bump the projects to net core app 2.2

There might be other options.?

**Comment by EricDahlvang** [comment]
@cleemullins  do you have any thoughts about this?

**Comment by EricDahlvang** [comment]
Verified this fix against the daily myget. 
https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder/4.5.0-preview-190702-3
