### ISSUE TITLE
Post process of authendication not render BOT automatially

### ISSUE THREAD

**Issue by mcakumar** [microsoft/BotBuilder-Samples#1527]
Hi Team,

I use MS graph API project to test my BOT authentication. I updated app id and password and oauth connection string.

as per my understanding we don't wan to publish my local bot to Azure .. Now I ran application and clicked Login button and Bot has opened Login page and asked credential .
 Post to success verification Auth window closed automatically . But my bot has not triggered LoginStepAsync or OnMessageActivityAsync either.

I understand this could be problem with redirect url which I provided in Azure AD app.
 redirect URL : https://dev-antares-bot.azurewebsites.net/api/messages
 this was explained in document so I added it alone.
 then why BOT was not triggered? When I tested Oauth connection it was success and return token .
 Should I add my BOt url in redirect URL? if yes it should be http://localhost:3978/api/messages or http://localhost:3978 . the project solution does not have any controller for auth.

**Comment by Savior0812** [comment]
same problem here!

**Comment by EricDahlvang** [comment]
Are you using the Emulator for testing?  There is an open issue on the Emulator repository related to this: https://github.com/microsoft/BotFramework-Emulator/issues/1544

If you check the 'Use a sign-in verification code for OAuthCards, the flow will work as expected:
![image](https://user-images.githubusercontent.com/11055362/58270303-4a546500-7d3e-11e9-95df-12f7fb1ff7ea.png)

**Comment by cleemullins** [comment]
This seems resolved. If no comment(s), we'll close this out next week.
