### ISSUE TITLE
Declarative Bot automation tool

### ISSUE THREAD

**Issue by vidya091209** [microsoft/BotBuilder-Samples#1529]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I really like this new Declarative Bot support. This is one of the feature missing in this framework compared to others.
Is there any tool to generate this josn file.  I wanted my customer to design the Bot.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by mdrichardson** [comment]
[Declarative Adaptive Dialogs](https://github.com/microsoft/BotBuilder-Samples/blob/b48f585c0c99ed33547d2a764ba368a005c6f3af/experimental/adaptive-dialog/declarative/README.md) are still in the *very* early stages. The tools that exist so far are:

* [DialogTracker](https://github.com/microsoft/botbuilder-tools/blob/V.Future/packages/DialogTracker) - PREVIEW - Library for tracking .schema, .dialog and .lg files.
* [DialogSchema](https://github.com/microsoft/botbuilder-tools/blob/V.Future/packages/DialogSchema) - PREVIEW - Merge together and check .schema and .lg files into a composite .schema file.
* [DialogLint](https://github.com/microsoft/botbuilder-tools/blob/V.Future/packages/DialogLint) - PREVIEW - Check .dialog files for errors and compile .lg files.
* [MSLG](https://github.com/microsoft/botbuilder-tools/blob/V.Future/packages/MSLG) - PREVIEW - Parse and collate lg files, expand lg templates or translate lg files.
* [VSCode Dialog Debugger](https://marketplace.visualstudio.com/items?itemName=tomlm.vscode-dialog-debugger) - This extension adds a dialog debugger for debugging Bot Framework dialogs.

Together, they can be used to help write the JSON files. Note, however, that when writing the JSON files, you only get Schema hints in VS Code, not Visual Studio.

That being said, none of these tools are particularly non-developer friendly.

**Comment by mdrichardson** [comment]
I'm going to close this issue for now as we're still pretty far away from release and there's a lot in the works. If you'd like to re-open, please be specific about what kind of tool that you're looking for and what problem you'd like it to solve.

**Comment by vidya091209** [comment]
thanks i was looking for non developer tool for bot development.
