### ISSUE TITLE
24.bot-authentication 

### ISSUE THREAD

**Issue by mplwork** [microsoft/BotBuilder-Samples#1537]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [nodejs]
3. Sample name: BotBuilder-Samples-v4/samples/javascript_nodejs/24.bot-authentication-msgraph

## Describe the bug
I used the BotBuilder-Samples-v4/samples/javascript_nodejs/24.bot-authentication-msgraph and deployed it to Azure via zip deploy. I registered an app in Azure, assigned it to the bot, and set it as ConnectionName in .env. 

If I call the bot from Teams either via Browser (IE, Edge, Firefox) or the standalone Teams app I get a login card but when clicking on the login button nothing happens.

This used to work in an earlier V4 version of the sample from around April 11, 2019. 

### Further info
As a last desperate attempt I copied the URL that is behind the login button and called it directly in a browser. I got the expected login prompt but also that 6 digit magic number. I entered it as answer into the bot after which I was logged in. I never saw that number again. 

I now do get a login window but I can't choose an account and I seem to be logged in immediately. The same happens with the iPhone app. 

In Azure I get the following exception and I still can't call the Graph API.

```
Running dialog with Message Activity.
(node:14524) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at BotFrameworkAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:505:91)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

## To Reproduce
See description.

## Expected behavior
Get a login window or a valid token.

## Additional context
This seems to work with the emulator when run locally. I can't use the emulator with Azure as I am not allowed to use ngrok.

[bug]

**Comment by tdurnford** [comment]
Closing as this appears to be related to issue https://github.com/microsoft/botbuilder-js/issues/924

**Comment by mplwork** [comment]
> 
> 
> Closing as this appears to be related to issue [microsoft/botbuilder-js#924](https://github.com/microsoft/botbuilder-js/issues/924)

Just to confirm it is related. The two fixes mentioned in 
https://github.com/microsoft/botbuilder-js/issues/924#issuecomment-494123719

solve the problem:

1. add token.botframework.com to validDomains in the bot's manifest
2. add a handler to this.onUnrecognizedActivityType:
```
const {ActivityTypes} = require("botbuilder");

this.onUnrecognizedActivityType(async (context, next) => {
    if (context.activity.type === ActivityTypes.Invoke) {
        await this.dialog.run(context, this.dialogState);
    }
    await next();
});
```

The second part should be documented here or better the code be updated. Why is handling `onTokenResponseEvent` not sufficient?

**Comment by Sujit-Gaikwad** [comment]
Is there any way to add "sign in"and "cancel " button both at time for oauth prompt

If not can we achieve above thing using another approach ???

Please Guide
