### ISSUE TITLE
No host found error after deploying

### ISSUE THREAD

**Issue by Arunprasath29** [microsoft/BotBuilder-Samples#1541]
I'm using nlp-with-dispatch sample. I have integrated luis, qna & adaptivecards with it. The bot works completely in localhost and gets deployed successfully, but when I try test in webchat in Azure it sends the welcome message but anything I send after that it throws an error "No host found". Is this ssl certificate issue?
[error.txt](https://github.com/microsoft/BotBuilder-Samples/files/3235813/error.txt)

**Comment by mdrichardson** [comment]
@Arunprasath29 	Can you verify that the values you have in `appsettings.json` match the ones in Azure Portal > App Service > Configuration?

**Comment by rakesh5689** [comment]
@mdrichardson I have the same issue but in my configuration I don't see LUIS keys at all. I created applications via LUIS.AI and then made them into a dispatch as per the https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs

**Comment by mdrichardson** [comment]
@rakesh5689 	Once deployed, you need to add the keys to Azure Portal > App Service > Configuration.

**Comment by rakesh5689** [comment]
@mdrichardson I am getting this error locally.
In my appsettings.json the LUIS (dispatch I created) looks like this
"LuisAppId": "*****-****-4701-bfdf-*******",
  "LuisAPIKey": "*****************************",
  "LuisAPIHostName": "westus", - I changed this to region only for testing and now I get an error 'Gone'

**Comment by mdrichardson** [comment]
@rakesh5689 	Can you verify that you've published "Production" and not "Staging"?

![image](https://user-images.githubusercontent.com/40401643/58656244-c1ef3a80-82d0-11e9-87e6-6d5d76388ade.png)

I'm able to repro your issue. If I only publish to staging, the API works, but I also get the "Gone" error. If I publish production, both work just fine.

You may need to re-train your app, re-publish, and restart your bot's App Service:

![image](https://user-images.githubusercontent.com/40401643/58656408-15618880-82d1-11e9-9ad7-c4f3fbedcb7b.png)

**Comment by rakesh5689** [comment]
> @rakesh5689 Can you verify that you've published "Production" and not "Staging"?
> 
> ![image](https://user-images.githubusercontent.com/40401643/58656244-c1ef3a80-82d0-11e9-87e6-6d5d76388ade.png)
> 
> I'm able to repro your issue. If I only publish to staging, the API works, but I also get the "Gone" error. If I publish production, both work just fine.
> 
> You may need to re-train your app, re-publish, and restart your bot's App Service:
> 
> ![image](https://user-images.githubusercontent.com/40401643/58656408-15618880-82d1-11e9-9ad7-c4f3fbedcb7b.png)

i have only published in production so far
Let me try publishing in staging to see if it works

**Comment by rakesh5689** [comment]
@mdrichardson So, I tried what you said...I have it published in both Prod and Staging. Restarted the bot's app service..all in vain

**Comment by mdrichardson** [comment]
@rakesh5689 	I've created a separate issue for you to better separate yours from @Arunprasath29's issue. Please continue our conversation there.
