### ISSUE TITLE
410 "Gone" Error with NLP Sample

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotBuilder-Samples#1544]
From #1541 	@rakesh5689

---

Note: this issue was created to separate two issues from one thread

---

I created applications via LUIS.AI and then made them into a dispatch as per the https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs

I am getting this error locally.
In my appsettings.json the LUIS (dispatch I created) looks like this
"LuisAppId": "*****-****-4701-bfdf-*******",
  "LuisAPIKey": "*****************************",
  "LuisAPIHostName": "westus", - I changed this to region only for testing and now I get an error 'Gone'

And LUIS is published for sure as when I hit my endpoint I get a legit response : https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/*********-7c91-***-a18b-*********?verbose=true&timezoneOffset=-360&subscription-key=*****************&q=hello

---

My recommendation:

@rakesh5689 	Can you verify that you've published "Production" and not "Staging"?

![image](https://user-images.githubusercontent.com/40401643/58656244-c1ef3a80-82d0-11e9-87e6-6d5d76388ade.png)

I'm able to repro your issue. If I only publish to staging, the API works, but I also get the "Gone" error. If I publish production, both work just fine.

You may need to re-train your app, re-publish, and restart your bot's App Service:

![image](https://user-images.githubusercontent.com/40401643/58656408-15618880-82d1-11e9-9ad7-c4f3fbedcb7b.png)

---

So, I tried what you said...I have it published in both Prod and Staging. Restarted the bot's app service..all in vain

**Comment by mdrichardson** [comment]
@rakesh5689 Can you verify that your appId's are correct? You obfuscated them, but at least from the un-obfuscated parts, the appId you used in the API appears different than the one in `appsettings.json`

**Comment by rakesh5689** [comment]
I followed the steps you mentioned that you were able to reproduce but its still not working. Thanks

**Comment by rakesh5689** [comment]
Well well...how naive. I have a couple of dispatch in LUIS and was using the previous oone. Thanks a ton @mdrichardson Saved me day of headscratch

**Comment by mdrichardson** [comment]
:) No problem. Glad you got it working. It's amazing how easy it is to make such a simple mistake like that. You're not the first.
