### ISSUE TITLE
Welcome message come after users first message in webchat 

### ISSUE THREAD

**Issue by Arunprasath29** [microsoft/BotBuilder-Samples#1547]
I've given welcome message inside onMembersAddedAsync as in the microsoft samples. The welcome message is triggered in the emulator but in directline gets triggered  only after the user sends the first message.

**Comment by tdurnford** [comment]
Per @cwhitten 

> The Bot Framework protocol sends two ConversationUpdates, one for the Bot when it enters the conversation and one for the User after they have sent their first message. This is not governed by WebChat, but built-in to the protocol events themselves itself. As a group we are discussing how to change this behavior for a better user experience, but this is what we have in place today.

https://github.com/microsoft/BotFramework-WebChat/issues/2049

If you want the welcome message to be sent before the user messages the bot, I would recommend sending a back channel event to the bot when the DirectLine Connection is fulfilled to trigger the message instead. Take a look at this Web Chat [Welcome Message](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event) sample for more details. 

Hope this helps.
