### ISSUE TITLE
Display HeroCard using luis action binding

### ISSUE THREAD

**Issue by HelloJyo** [Microsoft/BotBuilder-Samples#155]
how to create a HeroCard in the "fulfill()" of  luis action binding? any examples..?

**Comment by pcostantini** [comment]
Hi @HelloJyo ,
Take a look at the FullfillReplyHandler @ https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/blog-LUISActionBinding/samples/bot/app.js#L38
See how to configure LAB with the option @ https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/blog-LUISActionBinding/samples/bot/app.js#L28

More information here:
- [README](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/blog-LUISActionBinding/README.md) (search for `fulfillReply`)
- Commit Details: https://github.com/Microsoft/BotBuilder-Samples/pull/130

Regards,
-PabloC.

**Comment by HelloJyo** [comment]
How can I make the intent specific logic (content on the "card") coded as:


`fulfill: function (parameters, callback) {
    utilities.FilterFunction(parameters.x, parameters.y).then(function (matches){

       utilities.CreateCard(session, matches).then(function(cards){

            var reply = new builder.Message(session)
                .attachmentLayout(builder.AttachmentLayout.carousel)
                .attachments(cards);

            callback(util.format(reply));
        });

    });
}

`
How can I use session value in the fulfill method?...without session "utilities.CreateCard" won't work...

**Comment by HelloJyo** [comment]
If there are multiple intents (say 10) the app.js file needs to handle more logic which makes it complex.
What I want is return the result object (i.e, "matches" ) from

`utilities.FilterFunction(parameters.x, parameters.y).then(function (matches)`

to the FulfillReplyHandler and create the HeroCard there. An example would be helpful if possible.
  
regards,
HelloJyo

**Comment by pcostantini** [comment]
Hi @HelloJyo 

You should NOT create the card in the action's `fulfill` method. In it you should only invoke your action and pass back a result using the `callback` handler.

You should create the HeroCard from the optional `fulfillReplyHandler` when calling the `bindToBotDialog` method. See here for an example: https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/blog-LUISActionBinding/samples/bot/app.js#L28

In there you'll have access to the `session` object and the `actionModel` with the result.
You can then check the `actionModel.intentName`  to verify which LUIS intent was triggered and create the card as you wish.

Regards,
-PabloC.

**Comment by HelloJyo** [comment]
Okay, I got it now... 
Thanks and regards,
       -Jyo
