### ISSUE TITLE
Enable JS samples deployment to Azure US Government

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#1556]
## Sample information
1. Sample type: samples and templates
2. Sample language: JavaScript and TypeScript Node.js samples and templates

## Describe the bug
The Node.js samples should be able to be deployed to Fairfax without manual code changes by the user, similar to the experience for users to deploy a sample to public Azure.

This is a multi-step bug which needs a refactoring of the botbuilder-js `botbuilder` and `botframework-connector` libraries and a bumping of dependency versions in the samples and templates

DCR for BotFrameworkAdapter changes: microsoft/botframework-sdk#5417

[bug]

**Comment by sgellock** [comment]
Once 4.5.x is published, I can update the JS/TS samples to address this issue.  So T+1

**Comment by sgellock** [comment]
All JS and TS samples have been updated to use 4.5.1, which enables this scenaro
