### ISSUE TITLE
Provide samples in each language showing howto exchanging a token for a secret

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#1557]
It would be useful for users to have an example demonstrating how to show a page with WebChat loaded with a token retrieved from exchanging a secret.

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#generate-token is great, but does not have code examples.

[enhancement]

**Comment by corinagum** [comment]
To avoid overlapping effort, I'm linking these two samples:
https://github.com/microsoft/BotFramework-WebChat/issues/1534

**Comment by gabog** [comment]
Hi @EricDahlvang, this issues is quite old, can we close it?

**Comment by EricDahlvang** [comment]
Okay, closing this... looks like we do at least have a couple code examples now https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#code-examples  (dotnet and javascript)
