### ISSUE TITLE
[Question] How can I have the same data in the bot.use( session ) and the bot.dialog('/', [     function (session)

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder-Samples#156]
Hi everybody
I use middleware to get information to authentication users from hidden message that clients automatically send to Node server.  In the conversation, I need to access to session.userData.* to get user information. 
I put data into middleware part, in
```js
bot.use({
    botbuilder(session, next) { session.userData.profile = 'Data'---)
```
However, I couldnt access data in the session in the begin dialog. 
Can anyone help me for this situation. 
Thanks.

**Comment by stevengum97** [comment]
Hi @binhpht... I'm a little confused, are you trying to access `session.userData` in your middleware or in a dialog?

**Comment by brandon1780** [comment]
Session/userdata let me know take that . out.

**Comment by binhpht** [comment]
@stevengum97  I tried to access in dialog. In my case, My bot is  received message through Direct Line and Web Iframe, they have the same convervationID but Im not sure they are the same session.
