### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by kailash558** [microsoft/BotBuilder-Samples#1569]
dispatchBot.js generating following TypeError -
class DispatchBot extends ActivityHandler {
                          ^

TypeError: Class extends value undefined is not a constructor or null

How to resolve it?

**Comment by stevkan** [comment]
Just crossing t's and dotting i's: Did you perform `npm install` to install all the packages? If so, which version of Botbuilder are you using?

**Comment by kailash558** [comment]
My problem got solved by reinstalling bot builder.
