### ISSUE TITLE
Try to Implement the IStore for BlobStorage but fails on ConversationState 

### ISSUE THREAD

**Issue by ernestoguimaraes** [microsoft/BotBuilder-Samples#1574]
Hello all,

I got the sample to check how to implement the BlobStore on my bot. I got the code from this solution. 
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/42.scaleout

When I created by bot, I noticed that it has a higher 4.4.5 , generate from template with LUIS from Azure Service.

So, I noticed that the version on samples is 4.4.3, so I downgrade my solution.

I seems that worked in someway, but I got some erros on the ConversationState injection on my Dialogs. What Happened. It says that it's not possible to retrieve the StateStore because the Interface types ares difference. The conversationState expects IStorage and the one found on sample is IStore.

Well, to confirm that, I implemented the BlobStore from IStorage and the error stopped. But Now i need to implement two methods that this interface asks. DIfferent from the one in IStore found on sample.

is this a bug or Did I make something wrong?

Thank you

**Comment by ernestoguimaraes** [comment]
I found the problem. Just to clarify:

On Samples, project 42.scaleout, it uses an Implementation of IStore on BlobStore classes.

It works. but when we try to inject the ConversationState and UserState in a Dialog. it throws an exception. Because those above expects a IStorage implementation.

The template generated when we create a v4 service on Azure uses this kind of injection.

So a Switch the code

`services.AddScoped<IStore>(_ => new BlobStore(accountName, accountKey, container));`

by AzureBlobStorage, which is native and implements the expected Interface.

 ```
 var blobStorage = new  AzureBlobStorage(connStringStorage, container);
  services.AddSingleton<IStorage>(blobStorage);
```

Thank you

**Comment by johnataylor** [comment]
The storage model built into the product consists of two distinct layers. The lower layer is (fairly) raw storage with classes derived from IStorage the higher later adds some more semantics (like caching) and is derived from BotState.

The interface between the Dialogs and the storage model is through an abstraction called an Accessor. The BotState creates an Accessor.

The Dialogs don't technically have a direct dependency on BotState (i.e. UserState and ConversationState) and so anyone can create an Accessor and use the Dialogs. Sample 42 is demonstrating this and provides its own and very different ways to create the necessary Accessor object. That is the point of sample 42: showing how to create a very different state system, with different semantics and yet still use the Dialogs. IStore is _different_ than IStorage. The other samples, however, target the storage model built into botbuilder. There is documentation around sample 42 explaining the semantics. https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0

**Comment by johnataylor** [comment]
We can provide samples of how to implement the IStorage if that is helpful. However, the source code of the one in botbuilder is relative easy to follow.

Blob storage is here:

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs

And Cosmos DB here:

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs

**Comment by ernestoguimaraes** [comment]
Thank you! I will take a look on these references and information!
