### ISSUE TITLE
Core bot (via ABS) home page between JS and C#

### ISSUE THREAD

**Issue by diberry** [microsoft/BotBuilder-Samples#1577]
When creating ABS Basic bot v4 C# (this is supposed to be the core bot #13), when running bot on local host computer, the root website returns a nice home page letting me know the bot website works. When I create ABS Basic bot v4 Node.js, and run it on local host computer, there isn't a nice home page letting me know the bot website works. Can one be added? Or is it there and just not working?

**Comment by benbrown** [comment]
It is not there. One could be added!

**Comment by diberry** [comment]
Created [PR](https://github.com/microsoft/BotBuilder-Samples/pull/1582) for this.

**Comment by sgellock** [comment]
I'm moving this out to the MQ milestone

**Comment by sgellock** [comment]
We've decided not to do this work as it adds route code that will take away form the intended purpose of the samples
