### ISSUE TITLE
javascript_nodejs/11.qnamaker does not fail gracefully

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#1578]
## Sample information
1. Sample type: \samples\
2. Sample language: javascript_nodejs
3. Sample name: 11.qnamaker

## Describe the bug
Sample does not check for required QnAMaker information to connect to KB, nor does it fail gracefully if the information is missing.

## To Reproduce
1. Go to `javascript_nodejs/11.qnamaker`
2. `npm i && npm start` _// Without creating a QnAMaker instance and KB_
3. Connect to bot via Emulator
4. Send message to bot, receive `"Oops. Something went wrong!"` message
5. Check console, see error message for calls to QnAMaker:

```bash
[onTurnError]: RequestError: Error: Invalid URI "/knowledgebases//generateanswer"
```

## Expected behavior
Sample should fail gracefully and redirect user to create a QnAMaker instance and Knowledge Base instead of blowing up.

[bug]

**Comment by Zerryth** [comment]
@stevengum ping! :)

(Support Team was tasked to go through their unresolved issues and investigate why they haven't been closed yet.)

Please review PR when you have a chance :)
