### ISSUE TITLE
On intelligent SpeechToText, after this morning, it is not accepting the audio file itself. It is throwing an error like: DirectLine: Failed to post activity. No files uploaded 

### ISSUE THREAD

**Issue by Mrinnaal** [Microsoft/BotBuilder-Samples#159]
### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-SpeechToText

### Problem Description

Check to it and return back please!

**Comment by EricDahlvang** [comment]
The V3 intelligence-SpeechToText sample is fixed with this PR: https://github.com/Microsoft/BotBuilder-Samples/pull/1226 It is now using Cognitive Services Speech, instead of the deprecated Bing Speech.
