### ISSUE TITLE
Active learning sample, doesn't build successfully

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotBuilder-Samples#1625]
## Sample information
1. Sample type: experimental
2. Sample language: dotnetcore
3. Sample name: qnamaker-activelearning

## Describe the bug
Give a clear and concise description of what the bug is.

When the below line is un-commented, 
`
// IStorage dataStore = new Microsoft.Bot.Builder.Azure.AzureBlobStorage(blobStorageConfig.ConnectionString, storageContainer);
`

and when the package is installed, and namespace included
`
Microsoft.Bot.Builder.Azure
`

we get the error

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Azure' does not exist in the namespace 'Microsoft.Bot.Builder' (are you missing an assembly reference?)	qnamaker-activelearning-bot	C:\Bots\BotBuilder-Samples-master\experimental\qnamaker-activelearning\csharp_dotnetcore\Startup.cs	11	Active
`

## To Reproduce
1. open Startup.CS
2. uncomment lines as per the guidelines under "// For production bots use the Azure Blob or"
3. Install nuget package for "Microsoft.Bot.Builder.Azure"
4. Build the solution and see the error

## Expected behavior
Build clean without errors

## Additional context

[bug]

**Comment by Zerryth** [comment]
It looks like right now when you try to add package `Microsoft.Bot.Builder.Azure` the most recently published version tries to get installed (`4.4.5`)

However if you look at the `.csproj` file, you can see that the sample is targeting packages for version `4.4.3`, specifically `Microsoft.Bot.Builder`, which `Microsoft.Bot.Builder.Azure` depends on.

Installing `Microsoft.Bot.Builder.Azure 4.4.3` with Nuget Package Manager however allowed the bot to run 
![image](https://user-images.githubusercontent.com/35248895/61004908-e0a70f00-a31b-11e9-81c2-c8ae6bafd519.png)


I'll ask and see what we want to do regarding what packages we should reference in the samples, as `v4.5` should be releasing today

**Comment by Zerryth** [comment]
Also, this experimental sample still uses the `.bot` file, which the team has backed off using in favor of language-specific configs that are already built-in (e.g. appsettings.json)

**Comment by Zerryth** [comment]
Per Steven Gum, I can go ahead and bump the packages that the experimental samples are targeting, once we make the 4.5 samples update switch

For now to workaround, just specify version numbers manually when including packages

**Comment by saikumaru** [comment]
Thank you so much for the quick reply. I will do the same way. I should have checked the 
dependancy version before posting, beginners rush.

**Comment by Zerryth** [comment]
(Just a small side comment: removing this from my support queue, as Scott has assigned Rohan onto this 👍 )

**Comment by rokulka** [comment]
@trojenguri from out team is working with QnA samples at the moment. Please look into it.

**Comment by saikumaru** [comment]
hi, please can you let me know if there is a probable date by when you will have this fully migrated to look like the other V4 sample bots?

**Comment by trojenguri** [comment]
We have migrated active learning samples, this is the link https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/48.qnamaker-active-learning-bot

**Comment by trojenguri** [comment]
@Zerryth  Can we close this issue now?

**Comment by saikumaru** [comment]
Thank you, I had seen that. But I also do observe its still not consistent with other examples.

Same mentioned here

`...can check out the new active learning sample because **it hasn't been updated** to match the pattern of the other samples yet.`


https://stackoverflow.com/questions/57658154/is-the-best-practice-alwayas-to-start-a-dialog-in-bot/57664701#57664701

**Comment by trojenguri** [comment]
Main architecture is consistent with the overall sample but the Dialog path, we kept as it is or we did minimal changes. 
We would be creating one more dialog very soon, which would include Multi-turn + Active learning in consistent with latest samples.

**Comment by Zerryth** [comment]
imo yeah, we can close this issue if the Active Learning sample in master builds successfully :+1:

...I'm assuming yes it does, since someone on the team must've reviewed it recently if it just merged in

Please reopen if sample 48 is not building
