### ISSUE TITLE
Display pagination with carousel card in MS Teams

### ISSUE THREAD

**Issue by luannguyengo1** [microsoft/BotBuilder-Samples#1626]
## Sample information
1. Sample type: samples
2. Sample language: typescripts 
3. Sample name: 06.using-cards

## Describe the bug
Circle pagination does not display in carousel card.

## To Reproduce
```typescript
public buildAttachments(): Attachment[] {
    return [
      this.buildWelcomeCard(),
      this.buildSearchLibrary(),
      this.buildNextLevel(),
    ];
  }

const attachments = cardBuilder.buildAttachments();
const textHeader = `Text Header`;
await context.sendActivity({ text: textHeader, attachmentLayout: AttachmentLayoutTypes.Carousel, attachments});
```

## Expected behavior
Circle pagination candisplay in carousel card.

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/60912393-14116d00-a23a-11e9-96ce-4986ac151602.png)

**Comment by v-kydela** [comment]
Hello @luannguyengo1 

It sounds like you want an index number to automatically appear on each attachment in a carousel. Is that correct?

Some of the details about what you want are a little unclear. You're presenting this as a bug, but it would only be a bug if you've seen automatic pagination before and don't see it anymore. Where have you seen pagination successfully implemented?

If you want to implement this yourself on any channel then you need to include a number on the attachments yourself. If you want to have your channel client automatically include index numbers then you need to either use Web Chat or submit a feature request for that specific channel. What channel are you using?

**Comment by luannguyengo1** [comment]
Followed instructions from this docs: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#card-collections

I can see circle pagination 


![carousel](https://user-images.githubusercontent.com/40588179/60938151-0375fb00-a2fd-11e9-9fe1-2b84d314606e.png)

> If you want to implement this yourself on any channel then you need to include a number on the attachments yourself.

Can you give me some examples for this case?

**Comment by v-kydela** [comment]
@luannguyengo1 - Thank you for that link. In the future, you will get better help if you link to the instructions you're following and explain your desired behavior in your original post.

So you are using the Teams channel? Have you tested a carousel with the Teams mobile app?

**Comment by luannguyengo1** [comment]
> you are using the Teams channel? 
Yup. but only private channel

> Have you tested a carousel with the Teams mobile app?
Yeah. I can see pagination on Teams mobile app, but not on website/desktop app.

![paging](https://user-images.githubusercontent.com/40588179/61020883-70ef5d80-a3c9-11e9-978a-6fc83a7ed3a0.png)

**Comment by v-kydela** [comment]
@luannguyengo1 - This is working as designed/expected, so I am closing this issue. The screenshot you referenced for your expected behavior is from the mobile app and not the desktop app. If you would like to suggest this as a feature for the desktop app, please feel free to use the Teams feedback forum: https://teamsfeedback.uservoice.com
