### ISSUE TITLE
Implement refactored CoreBot and unit tests for TypeScript

### ISSUE THREAD

**Issue by gabog** [microsoft/BotBuilder-Samples#1629]
This task involves:

- Update the TypeScript corebot to match the refactored JS version in the [corebot-updates](https://github.com/microsoft/BotBuilder-Samples/tree/corebot-updates/samples/javascript_nodejs/13.core-bot) branch.
- Write unit tests in TypeScript (it should match test cases and code in the JS version).

TypeScript implementation for https://github.com/microsoft/botframework-sdk/issues/5347

**Comment by sgellock** [comment]
generator-botbuilder version 4.5.0 or above supports core bot tests in TypeScript
