### ISSUE TITLE
[LG] Need doc for how to use LG in legacy dialogs, like waterfall

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotBuilder-Samples#1630]
## Sample information
1. Sample type: doc

## Describe the bug
Need doc for how to use LG in legacy dialogs, like waterfall dialogs. Only find LG instruction for adaptive dialog, but actually, LG can be used also in legacy dialogs like waterfall.

**Comment by boydc2014** [comment]
Please check the samples here which is not using AdaptiveDialogs https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation/csharp_dotnetcore
