### ISSUE TITLE
README for new Inspection samples should be in sync with other documentation 

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#1640]
The current README for both the C# and JavaScript Inspection samples detail very basic steps regarding setting up the emulator debugging inspection.

These steps should be clarified and brought into sync with what we are saying elsewhere. For example we have a very useful description here:

https://github.com/microsoft/BotFramework-Emulator/blob/master/content/CHANNELS.md

We are also developing other documentation around this feature than should be referenced from this README.

**Comment by johnataylor** [comment]
This PR https://github.com/microsoft/BotBuilder-Samples/pull/1641 adds a link to @cwhitten README.

**Comment by Kaiqb** [comment]
The content on Inspection Middleware is here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-inspection-middleware?view=azure-bot-service-4.0&tabs=csharp
