### ISSUE TITLE
Node samples onTurnError should console log the error

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#1644]
## Sample information
1. Sample language: nodejs
2. Sample name: all

## Describe the bug
This line does not render correctly:
```js
console.error(`\n [onTurnError]: ${ error }`);
```

This would be better:
```js
console.error(error);
```

[bug]

**Comment by sgellock** [comment]
@EricDahlvang why would this be better?

**Comment by mdrichardson** [comment]
@sgellock 	I could see some benefit in that it would print the stack trace. However, I'd recommend something more like:

```js
console.error(`\n [onTurnError]: ${ error.stack ? error.stack : error }`);
```

...the ternary would prevent `[onTurnError]: undefined` in the event of

```js
throw 'message'
```

instead of

```js
throw new Error('message')
```

This would result in something like:

![image](https://user-images.githubusercontent.com/40401643/61493754-35c0d180-a969-11e9-8f89-9f9bf8058a1b.png)

**Comment by EricDahlvang** [comment]
1) @stevengum said it would be better :)

2) 
```js
console.error(`\n [onTurnError]: ${ error }`);
```
Results in a useless string in the debug console:
[onTurnError]: [object Object]

```js
console.error(error);
```
Results in an interactive object in the debug console:
GraphError {statusCode: -1, code: null, message: null, requestId: null, date: Thu Jul 18 2019 15:09:30 GMT-0700 (Pacific Dayligh…, …}

**Comment by mdrichardson** [comment]
In case anybody is curious (I was, so I did some testing and looked it up), it will print `[object Object]` if the code `throw`s a class that doesn't extend the `Error` class. [`GraphError`](https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/graphManagement/lib/models/graphError.js#L17) does not.

Any custom error classes that *do* extend the `Error` class would work just fine as-is.

**Comment by EricDahlvang** [comment]
Interesting!  Thanks @mdrichardson

**Comment by stevengum** [comment]
I modified the `EchoBot.onMessage` in the Node.js 02.echobot sample:

```js
class EchoBot extends ActivityHandler {
    constructor() {
        super();
        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.
        this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            const err = new Error('Hello world!'); // new line
            console.log(err);                      // new line
            throw err;                             // new line
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    // ...
}
```

This will result in the following:

```bash
Error: Hello world!
    at Array.EchoBot.onMessage (C:\Users\stgum\botbuilder-samples\samples\javascript_nodejs\02.echo-bot\bot.js:12:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)

 [onTurnError]: Error: Hello world!
```

The `console.log()` has the stack trace which is nice.

For "Errors" that don't extend the `Error` class it would print out the `Error.message`, it would probably output this in a `console.log(err);`:

```bash
{ message: 'Some error message', stack: 'at line 14.' }
```

**Comment by mdrichardson** [comment]
@stevengum 	The issue is more when you have:

```js
console.log(`[OnTurnError]: ${ err }`)
```

When you pass `console.log` a string instead of an `Error`, it prints `[Object object]`

```js
class IsError extends Error {
    message;
    stack = 'IsError stack'

    constructor(message){
        super(message);

        this.message = message;
    }
}

class NotError {
    message;
    stack = 'NotError stack'

    constructor(message) {
        this.message = message;
    }
}

console.log(isError); // [IsError stack] { stack: 'IsError stack', message: 'IsError Message' }
console.log(notError); // NotError { message: 'NotError Message', stack: 'NotError stack' }
console.log(`IsError TemplateString: ${ isError }`); // IsError TemplateString: Error: IsError Message
console.log(`NotError TemplateString: ${ notError }`); // NotError TemplateString: [object Object]
```

**Comment by stevengum** [comment]
I suppose I should have clarified more, I'm all for console.logging the error without trying to manually format it into a string. 

Something that Eric pointed out that we could do is add another console.error before we call `console.error(error);` to indicate where the message is being thrown from:

```js
console.error('Error caught in Adapter.onTurnError:');
console.error(error);
```

When debugging bots with a TurnError handler, I've run into the exact problem where it just says things like `[onTurnError]: Error: 401 unauthorized` which is _very_ close to being unhelpful for a developer. If I'm using 6 different services that require authorization, which service do I start with?

The first thing I usually do is change the onTurnError to just `console.error(error)`.

**Comment by mdrichardson** [comment]
...I'm a little defensive today :smile: Mb.

**Comment by sgellock** [comment]
I've taken a pass at the onTurnError in both C# and JS/TS to do 2 things:
- use more descriptive error messages
- send a trace activity if we determine we're using the emulator

This is the extent of the investment I want to make as we're starting to get into more complexity in this error handler function that I think may be appropriate.
