### ISSUE TITLE
qna prompting does not display full text with buttons

### ISSUE THREAD

**Issue by karoyal** [microsoft/BotBuilder-Samples#1645]
## Sample information
1. Sample type: botbuilder-samples\experimental\qnamaker-prompting\csharp_dotnetcore
2. Sample language: [c#]
3. Sample name: <qna-prompting>

## Describe the bug
The dialog that is displayed when there are prompts (buttons) gets cut off by them.

## To Reproduce
1. Go to 'web emulator or teams channel bot'
2. type in a value that has a response more that 2 lines of text with buttons.
3. see the text cut off by buttons. 

## Expected behavior
show full text with buttons displayed after text. 

## Screenshots
![teamserror](https://user-images.githubusercontent.com/52825327/61129835-4bbf2580-a483-11e9-86d7-e720a220527b.png)

## Additional context

[bug]

**Comment by tdurnford** [comment]
Take a look at https://github.com/microsoft/BotFramework-WebChat/issues/2043#issuecomment-497870359

**Comment by tdurnford** [comment]
@karoyal Are you still having an issue with this?

**Comment by karoyal** [comment]
Sorry for the delay, I was able to successfully edit the bot to display full text. Thank you for all the help and support.

________________________________

**Comment by jwiley84** [comment]
Glad TJ was able to help you! Closing this issue.
