### ISSUE TITLE
How can I Call an intent from LUIS from session

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder-Samples#165]
### SDK Platform
 Node SDK

### Problem Description

When user connect to the bot, user want to make some intent request, but  before my bot can help users, the bot need to check their credentials, for example, username and password. If users havent logined to the system, the bot requires users login and after-that forward to the intent requests of users. 
Now I am finding the way how to **forward intents from session instead of getting them from user prompt**.
Please share me some experiences with this problem.
Thanks.

**Comment by daveRendon** [comment]
@binhpht did you manage to make a intent call when starting your bot? I´m looking for a similar approach, my bot would start a intent call to LUIS before redirecting into a specific Dialog. 

Regards

**Comment by EricDahlvang** [comment]
The sdk and framework now provide authentication support.  Some documentation: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=javascript  and sample: https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication

After a successful login, messages can be processed by LUIS.
