### ISSUE TITLE
Add telemetry to QnAMaker sample (11)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#1654]
Please hook up telemetry to the QnAMaker sample (11). This will be used to complete the gap in telemetry documentation of the documentation (we have SDK, and LUIS but not QnA).
@munozemilio FYI.

**Comment by sgellock** [comment]
@scheyal this goes against the model we've employed with other samples.  sample 11 should be a simple, focused sample on the concept of using QnA.  if you want a telemetry sample, then there should be a new sample that adds this.  There is an "everything including the kitchen sink" QnA sample that gloms together a whole pile of QnA features.  Not a fan of this sample at all, but if we were to keep it in the samples repo (I'd rather not), then we could consider adding it there.
