### ISSUE TITLE
Video Card doesnt work in Teams Channel

### ISSUE THREAD

**Issue by vinayjayaram** [microsoft/BotBuilder-Samples#1656]
I am not able to render Video Card in Teams Channel

It is giving me an error **"Oops. Something went wrong!"**

In the logs i get **"[onTurnError]: Error: Unknow"**

Code Sample link: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/06.using-cards

**Comment by VKAlwaysWin** [comment]
Hi @vinayjayaram . It looks like Teams doesn't supporting Video Card: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#cards-not-supported-in-teams

**Comment by Emod94** [comment]
I'm just having the same problem. I wish teams would support the cards soon..
Is there already a roadmap when this feature will be available?

**Comment by v-kydela** [comment]
@Emod94 - There are a few public sites where you can see some of the things that are being worked on in Teams:

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Teams
https://microsoftteams.uservoice.com/forums/555103-public

There is no indication that there are any plans for Teams to support video cards. Sorry for the inconvenience. Closing now.
