### ISSUE TITLE
internal server error when connected to cortana channel

### ISSUE THREAD

**Issue by sumit99531** [Microsoft/BotBuilder-Samples#166]
### SDK Platform

Microsoft bot connector v3.0.2

### URL of Code Sample

https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine

### Problem Description

when i connect the bot with cortana channel, it gives internal server error, but works fine on direct line chat client
{
  "error": {
    "botId": "findMsg1",
    "botRequest": {
      "type": "message",
      "id": "8hdXvsmZpu",
      "timestamp": "2017-07-20T09:43:01.7725655Z",
      "serviceUrl": "https://CortanaBFChannelWestUS.azurewebsites.net/",
      "channelId": "cortana",
      "from": {
        "id": "271F10F5FC4F2BF00937ED565375D6E9584BB89EBBF9DC66FBE566055E54AF57"
      },
      "conversation": {
        "id": "a8d3c8ff-6ddd-483e-8c71-999a4812ea49"
      },
      "recipient": {
        "id": "findmsg1"
      },
      "locale": "en-US",
      "entities": [
        {
          "type": "Intent",
          "name": "Microsoft.Launch"
        },
        {
          "type": "DeviceInfo",
          "supportsDisplay": "true"
        }
      ],
      "channelData": {
        "skillId": "971dfc2d-374d-413a-ab34-afd12ac113ff",
        "isDebug": true
      }
    },
    "error": "Bot service failed with status code: InternalServerError"
  },
  "traceId": "5bcb64a0-cdbe-4843-a168-e7638fd77db2"
}

**Comment by EricDahlvang** [comment]
InternalServerError generally indicates an issue in the bot code.  Debugging locally is a good way to diagnose these issues: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/
