### ISSUE TITLE
javascript es6/01.browser-echo does not work in Safari

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1663]
## Sample information
1. Sample type: javascript
2. Sample language: es6
3. Sample name: 01.browser-echo

## Describe the bug
The sample doesn't run in Safari

## To Reproduce
1. Build the sample
2. Run the sample
3. Point the browser at http://localhost:8080
4. See nothing

## Expected behavior
Get the web chat window at the bottom of the browser

[bug]

**Comment by stevengum** [comment]
Fixed via #1657; thanks @compulim!
