### ISSUE TITLE
[yeoman] generator- botbuilder needs to have a supporting build and release pipeline

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1667]
We need a build pipeline and a release pipeline for generator-botbuilder.  this should be modeled in the way we do our JS modules (version information in package.json, is updated by the build process.  builds are published to botbuilder.myget until we move off of that service.  and lastly we need a release pipeline that will publish to npmjs.org

**Comment by BruceHaley** [comment]
I can do this for you. Shall we meet and go over the details? I.e. source repo and build commands.

Thanks.
--Bruce

**Comment by sgellock** [comment]
Let me know how I can help

**Comment by BruceHaley** [comment]
I will get started on a build for https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

--BH

**Comment by BruceHaley** [comment]
The build: BotBuilder-Generator-JS-daily https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=591&_a=summary
The release: Push-BotBuilder-Generator-JS-to-MyGet-daily https://fuselabs.visualstudio.com/SDK_v4/_release?definitionId=63&view=mine&_a=releases
The released package on MyGet: aitemplates - generator-botbuilder 4.6.0-preview.72039 https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder

The release definition for npmjs is coming soon.

Thanks.
-Bruce

From: Bruce Haley (Harvey Nash)
Sent: Monday, July 22, 2019 11:36 AM
To: microsoft/BotBuilder-Samples <reply@reply.github.com>; microsoft/BotBuilder-Samples <BotBuilder-Samples@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [microsoft/BotBuilder-Samples] [yeoman] generator- botbuilder needs to have a supporting build and release pipeline (#1667)

I will get started on a build for https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

--BH

**Comment by BruceHaley** [comment]
Hi Scott,

Completed:

The build: BotBuilder-Generator-JS-daily https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=591&_a=summary
The release: Push-BotBuilder-Generator-JS-to-MyGet-daily https://fuselabs.visualstudio.com/SDK_v4/_release?definitionId=63&view=mine&_a=releases
The released package on MyGet: aitemplates - generator-botbuilder 4.6.0-preview.72039 https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder
The prod release definition: [[PROD]]Push-BotBuilder-Generator-JS-to-npmjs https://fuselabs.visualstudio.com/SDK_v4/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=591&view=Tab_Tasks

Thanks.
-Bruce

From: Bruce Haley (Harvey Nash)
Sent: Monday, July 22, 2019 11:36 AM
To: microsoft/BotBuilder-Samples <reply@reply.github.com<mailto:reply@reply.github.com>>; microsoft/BotBuilder-Samples <BotBuilder-Samples@noreply.github.com<mailto:BotBuilder-Samples@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: RE: [microsoft/BotBuilder-Samples] [yeoman] generator- botbuilder needs to have a supporting build and release pipeline (#1667)

I will get started on a build for https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

--BH

**Comment by BruceHaley** [comment]
Oops, the prod release definition link below was incorrect. Now corrected.

From: Bruce Haley (Harvey Nash)
Sent: Monday, July 22, 2019 2:41 PM
To: microsoft/BotBuilder-Samples <reply@reply.github.com>; microsoft/BotBuilder-Samples <BotBuilder-Samples@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [microsoft/BotBuilder-Samples] [yeoman] generator- botbuilder needs to have a supporting build and release pipeline (#1667)

Hi Scott,

Completed:

The build: BotBuilder-Generator-JS-daily https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=591&_a=summary
The release: Push-BotBuilder-Generator-JS-to-MyGet-daily https://fuselabs.visualstudio.com/SDK_v4/_release?definitionId=63&view=mine&_a=releases
The released package on MyGet: aitemplates - generator-botbuilder 4.6.0-preview.72039 https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder
The prod release definition: [[PROD]]Push-BotBuilder-Generator-JS-to-npmjs https://fuselabs.visualstudio.com/SDK_v4/_releaseDefinition?definitionId=64&_a=environments-editor-preview
Thanks.
-Bruce

From: Bruce Haley (Harvey Nash)
Sent: Monday, July 22, 2019 11:36 AM
To: microsoft/BotBuilder-Samples <reply@reply.github.com<mailto:reply@reply.github.com>>; microsoft/BotBuilder-Samples <BotBuilder-Samples@noreply.github.com<mailto:BotBuilder-Samples@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: RE: [microsoft/BotBuilder-Samples] [yeoman] generator- botbuilder needs to have a supporting build and release pipeline (#1667)

I will get started on a build for https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

--BH

**Comment by sgellock** [comment]
Thanks @BruceHaley you're the build and release pipeline ninja
