### ISSUE TITLE
Inspection middleware sample has inconsistent OnTurnError handling

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#1668]
## Sample information
1. Sample type: [samples]
2. Sample language: [dotnetcore and nodejs]
3. Sample name: 47.inspection

## Describe the bug
1. The JavaScript OnTurnError handler doesn't clear conversation state, whereas the CoreBot's adapter does.
2. The C# adapter doesn't have an OnTurnError handler.

## To Reproduce
1. Look at the adapter/error handler for [JS](https://github.com/microsoft/BotBuilder-Samples/blob/1c7c555da2a6aa7b6901f9ec1313e89cb01eb93f/samples/javascript_nodejs/47.inspection/index.js#L45-L51) and [C#](https://github.com/microsoft/BotBuilder-Samples/blob/1c7c555da2a6aa7b6901f9ec1313e89cb01eb93f/samples/csharp_dotnetcore/47.inspection/AdapterWithInspection.cs#L11-L21)
2. Note the aforementioned issues.

## Expected behavior
Both samples should use best practices for error handling, presumably what's used in the core bot.

## Additional context
Open question: what is best practice for clobbering or persisting inspection state in the on turn error handler?

[bug]

**Comment by JonathanFingold** [comment]
@sgellock Can you take a look at this? I see that you recently touched all these error handlers.

**Comment by sgellock** [comment]
Both C# and JS samples have been updated in the 4.6-staging branch, to be merged to master as soon as 4.6 is published
