### ISSUE TITLE
Kik Carousel not working properly.

### ISSUE THREAD

**Issue by chetanmekha** [Microsoft/BotBuilder-Samples#167]
Hello Team, 
I am facing an issue with KiK communication channel. I want to show carousel with button selection but only the last option is available for selection.
I tried with setting builder.ListStyle["inline"] and builder.ListStyle["list"] but no success.

![screenshot_2017-07-24-15-42-46](https://user-images.githubusercontent.com/3276861/28519348-dbced70a-7088-11e7-9ee9-37c44fce10e5.png)

@LarsLiden @danmarshall pls help me out

**Comment by nwhitmont** [comment]
@chetanmekha Please post your questions about Bot Framework, and include your SDK language, as well as code examples, on the main BotBuilder SDK repository here: https://github.com/Microsoft/BotBuilder/issues/new
