### ISSUE TITLE
Minor directory typo & LuisAPIHostName value - 04. core-bot sample

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotBuilder-Samples#1671]
## Sample information
1. Sample type: [BotBuilder-Samples/experimental/adaptive-dialog]
2. Sample language: [C#]
3. Sample name: <04.core-bot>

## Describe the bug
In this readme file: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot

In LUIS stepup
1. there is a minor typo here: 
In the four step, "Select `botbuilder-samples/experimental/adaptive-dialog/csharp_dotnetcore/13.core-bot/CognitiveModels/CoreBot.luis.json", I think should be "Select `botbuilder-samples/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot/CognitiveModels/CoreBot.luis.json"

2. what is the right configuration value - LuisAPIHostName
Originally in the readme file, it says "You can get your 'Authoring key' by following instructions here. You can get your application id and endpoint region by following instructions here" 

Both 'Authoring key' and 'application id' can be found directly from LUIS app -> manage. 
The "endpoint region" can be found from LUIS app -> manage, too. But in the appsetting.json file, the value of "LuisAPIHostName": "" is not clear. This is the one I tried and works: <your region>.api.cognitive.microsoft.com I found from this article: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp

## Expected behavior
fix the typo and specify LuisAPIHostName value (is this one correct? <your region>.api.cognitive.microsoft.com) in appsetting.json file 

## Additional context

[bug]

**Comment by sgellock** [comment]
@zxyanliu thank you for opening this issue.  I pushed a fix into master that addresses it.
