### ISSUE TITLE
dotenv.load(); needs to be replaced with dotenv.config();

### ISSUE THREAD

**Issue by seanbetts** [microsoft/BotBuilder-Samples#1674]
Please update the documentation to state:
// initialized to access values in .env file.
var dotenv = require('dotenv');
dotenv.config();

### Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
Content: Write directly to storage - Bot Service
Content Source: articles/v4sdk/bot-builder-howto-v4-storage.md
Service: bot-service
Sub-service: sdk
GitHub Login: @DeniseMak
Microsoft Alias: v-demak

## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by mdrichardson** [comment]
Where are you seeing this? I'm not seeing any of the samples use `.load()`

**Comment by mdrichardson** [comment]
Thanks for pointing this out! I will close this issue now that a PR has been submitted for it.
