### ISSUE TITLE
Skype Video calling and recording Bot

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Microsoft/BotBuilder-Samples#168]
Do you have plans to build a sample video calling and recording bot using skype. ?

**Comment by EricDahlvang** [comment]
This could probably be done using [RealTimeMediaCalling ](https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling) as a starting point.

Some documentation can be found here: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-real-time-media-concepts?view=azure-bot-service-3.0
