### ISSUE TITLE
More TypeScript samples

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#1681]
**Describe the solution you'd like**
More of these https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs in TypeScript

[enhancement]

**Comment by sgellock** [comment]
We'll track the request with this issue.  That said, we won't make any progress on this for the remainder of the calendar year.

**Comment by EricDahlvang** [comment]
Thanks to @leolorenzoluis we have a few more Typescript samples now.

Closing this.
