### ISSUE TITLE
Prerequisites documentation should be enhanced for Experimental samples

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotBuilder-Samples#1682]
Hi team,
I now starting digging deeper into the experimental section and came across some minor issues in the docs here.
For me it would make sense to include the MyGet prerequisites into the prerequisites section here to instruct users on how to add the BotBuilder MyGet feed into Visual Studio for example, as the documentation is a bit confusing when there is no reference to this at the moment...

**Comment by sgellock** [comment]
@stephanbisser thanks for opening the issue.  I've tagged this for our 4.6 release.  I think this is a good idea.

**Comment by sgellock** [comment]
@Kaiqb I think we address this in docs?  if you disagree, then that leaves the README.md for https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental, but I'm not sure that's the right place.  maybe we link from the README.md to our docs like we do with other topics?

**Comment by EricDahlvang** [comment]
The dotnet repo also has some myget feed instructions we could link to: https://github.com/microsoft/botbuilder-dotnet/blob/master/UsingMyGet.md

**Comment by Kaiqb** [comment]
@sgellock - the samples in the experimental branch are not covered in the core docs. The readme will need to include the pre-reqs.
