### ISSUE TITLE
[Teams] Provide an Authentication sample that supports the Teams flow

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1683]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
python (Targeted at a different cycle: microsoft/botbuilder-python#330)
3. Sample name: 46.teams-auth

## Describe the bug
Rationalize the current auth samples in BF SDK to ensure they work naturally when run in Teams.  Support for C#, JS, and Python is required

**Comment by Virtual-Josh** [comment]
Per agreement with Teams team is a P1 sample. Should land in 4.6

**Comment by EricDahlvang** [comment]
Closing as a duplicate of new tracking issues:
https://github.com/microsoft/BotBuilder-Samples/issues/1840
and 
https://github.com/microsoft/BotBuilder-Samples/issues/1839

Python is R7 https://github.com/microsoft/botbuilder-python/issues/333

Also, we have Teams auth in a bot:
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth
and
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth

Teams Auth in a Messaging Extension:
PR: https://github.com/microsoft/BotBuilder-Samples/pull/1846
and
https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/MessagingExtensionAuth

js search config auth Sample coming soon, tracked in a separate issue.
and
https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder/tests/teams/messagingExtensionAuth
