### ISSUE TITLE
[Teams] Provide a sample that shows how a 1-1 bot should be written

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1684]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
python (Targeted at a different cycle: microsoft/botbuilder-python#330)
3. Sample name: 

## Describe the bug
Consider adding command menus to this sample.  Support for C#, JS, and Python is required
--

**Comment by Virtual-Josh** [comment]
@Virtual-Josh  to link back the echo bot sample

**Comment by Virtual-Josh** [comment]
Done
https://github.com/microsoft/BotBuilder-Samples/issues/1793
