### ISSUE TITLE
[Teams] Provide a sample that shows how to send and receive files

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1685]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
python (Targeted at a different cycle: microsoft/botbuilder-python#330)
3. Sample name: 

## Describe the bug
Samples needs to demonstrate how to send and receive a file when using the Teams channel.  

Support for C#, JS, and Python is required
--

**Comment by Virtual-Josh** [comment]
Per agreement with Teams this is a P3 sample, will fast follow the 4.6 release.

**Comment by Virtual-Josh** [comment]
You merged the file upload sample for Teams yeah?
