### ISSUE TITLE
[Teams] Provide a sample that shows how to do proactive messaging

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1686]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
python (Targeted at a different cycle: microsoft/botbuilder-python#330)
3. Sample name:

## Describe the bug

Sample should also show how to rate limit/throttle handling.  Support for C#, JS, and Python is required
--

**Comment by mdrichardson** [comment]
@sgellock, @johnataylor, @axelsrz 	I'd recommend adding in querying the Team Roster, then proactively messaging them. We've seen a decent number of issues come in of users wanting to do that. [Example with current solution](https://stackoverflow.com/questions/57496329/proactive-messaging-bot-in-teams-without-mentioning-the-bot-beforehand)

**Comment by Virtual-Josh** [comment]
Per agreement with Teams this is P2 sample and will fast follow the 4.6 release.

**Comment by kunalkankariya** [comment]
@mdrichardson The link to the current solution for node uses botbuilder-teams which is deprecated. Do you have a sample for 4.6 that I could refer to? Thanks!

**Comment by kunalkankariya** [comment]
@mdrichardson I know how to get this done now. Thanks :)

**Comment by adamist521** [comment]
@kunalkankariya 
Could you show me how you did it in 4.6?

**Comment by mdrichardson** [comment]
@adamist521 [Here you go](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L107)

**Comment by adamist521** [comment]
@mdrichardson 
thx! Should this be also possible for nodejs?
Can't find sample for nodejs...


It seems that following link seems to be doing different compared to c# one... (replying to coversation)

https://github.com/microsoft/BotBuilder-Samples/blob/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/javascript_nodejs/57.teams-conversation-bot/bots/teamsConversationBot.js#L117

**Comment by mdrichardson** [comment]
@adamist521 Yes, you can do that in Node as well using the code you linked. It's just shown a different way from the C# sample
