### ISSUE TITLE
[Teams] Provide a sample that shows how to write a channel bot

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1687]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
[ ] python
3. Sample name:

## Describe the bug
teams channel bot support

**Comment by cleemullins** [comment]
Teams Channel Bot Samples are coming as part of 4.6.

**Comment by Virtual-Josh** [comment]
Done.
https://github.com/microsoft/BotBuilder-Samples/issues/1793

**Comment by cindyloo** [comment]
is there a nodejs example I hope? I didn't see one on #1793

**Comment by sgellock** [comment]
@cindyloo we are tracking to have both C# and NodeJS samples for the 4.6 release.
