### ISSUE TITLE
[Teams] Ensure the Bot Fx Graph Sample supports Teams authentication

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1688]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
python (Targeted at a different cycle: microsoft/botbuilder-python#329)
3. Sample name: 

## Describe the bug
Make sure our graph auth sample we ship works with Teams

**Comment by Virtual-Josh** [comment]
@johnataylor  is this done?
