### ISSUE TITLE
[Teams] Provide a sample Teams bot that shows how to use Teams Tabs

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1689]
## Sample information
1. Sample type: samples
2. Sample language: 
[ ] dotnetcore
[ ] nodejs
[ ] typescript
3. Sample name:

## Describe the bug
Discuss with Andrew to finalize what we should show in the Tab

**Comment by clearab** [comment]
@johnataylor I believe this one can be closed as not needed.

**Comment by johnataylor** [comment]
Yes Tabs are not directly related to the bot framework SDK work
