### ISSUE TITLE
[Teams] Remove adaptivecards dependency from botbuilder-teams to reduce space usage

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#1697]
**Is your feature request related to a problem? Please describe.**
Currently the [botbuilder-teams](https://github.com/microsoft/BotBuilder-Samples/tree/teams-samples/experimental/teams/javascript_nodejs/botbuilder-teams) project in the teams-samples branch pulls in a dependency on [`adaptivecards`](https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/javascript_nodejs/botbuilder-teams/package.json#L15).

However, the `adaptivecards` dependency is only used for its [types](https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/javascript_nodejs/botbuilder-teams/src/activityProcessor/teamsFactory.ts#L28):

```ts
export type IAdaptiveCardAction = ac.IAdaptiveCard['actions'][0];
```

These types are for the interfaces [ISubmitAction, IOpenUrlAction and IShowCardAction](https://github.com/microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/schema.ts#L18-L31).

```ts
export interface IAction {
    id: string;
    title?: string;
}

export interface ISubmitAction extends IAction {
    type: "Action.Submit";
    data?: any;
}

export interface IOpenUrlAction extends IAction {
    type: "Action.OpenUrl";
    url: string;
}

export interface IShowCardAction extends IAction {
    type: "Action.ShowCard";
    card: IAdaptiveCard;
}
```

**Describe the solution you'd like**
Since the dependency is 2.46 MB and is used minimally, we should see if we can remove it by the time the botbuilder-teams library is integrated into the [botbuilder-js](https://github.com/Microsoft/botbuilder-js/) repo.

@siduppal, @johnataylor, @Virtual-Josh FYI

[enhancement]

**Comment by cleemullins** [comment]
done
