### ISSUE TITLE
[Teams] Provide a sample Teams bot that shows how to use message extensions with action command

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1700]
Sample information

Sample type: samples
Sample language:
[ ] dotnetcore
[ ] nodejs
[ ] typescript
Sample name:
MessageExtWithActionCmd

**Comment by CoHealer** [comment]
Removing support label. Please reapply if that was intended.

**Comment by sgellock** [comment]
ahh, yes.  I was probably moving too fast this morning and incorrectly added it.  Thanks Cory.

**Comment by clearab** [comment]
C3# v3 example (MS Only repo): https://github.com/OfficeDev/msteams-samples/tree/master/samples/dotnet/messaging_extensions/messaging_extension_action_with_card

**Comment by Virtual-Josh** [comment]
This work is done in C# and JS.
