### ISSUE TITLE
[Teams] Provide a sample Teams bot that shows how to use message ext w/ action-based command and bot response

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1701]
Sample information

Sample type: samples
Sample language:
[ ] dotnetcore
[ ] nodejs
[ ] typescript
Sample name:
MessageExtWithActionCmdResponse

**Comment by clearab** [comment]
C# v3 example (MS Only repo): https://github.com/OfficeDev/msteams-samples/tree/master/samples/dotnet/messaging_extensions/messaging_extension_action_bot_response

**Comment by Virtual-Josh** [comment]
This work is done.
