### ISSUE TITLE
Add JS AppInsight sample to support documentation

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#1707]
We need corresponding JS example for use of AppInsights instrumentation telemetry and corresponding documentation (see tracking issue below).

### See Also
* https://github.com/MicrosoftDocs/bot-docs/issues/1325
* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0

**Comment by scheyal** [comment]
@garypretty  - can you point us to recent samples that can be used to drive corresponding documentation?
See also: https://github.com/microsoft/botframework-sdk/issues/5706

**Comment by garypretty** [comment]
@scheyal JS sample now available (sample 21) - small PR #2147 open to update the sample to use the latest pieces

**Comment by garypretty** [comment]
@scheyal - PR #2147 has now been merged.  This is now available to support update of docs.
