### ISSUE TITLE
[Declarative Adaptive Dialogs] Handling of errors from fulfillment steps (no code)

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotBuilder-Samples#1708]
**Is your feature request related to a problem? Please describe.**
As I look at building bots using the declarative format, I realize a mechanism is needed to handle errors coming back from say httprequest fulfillment logic; or maybe some form of runtime consistency error within the context of the dialog.

**Describe the solution you'd like**
Some mechanism for taking action onError in a no-code scenario - possibly a dialog to invoke that can get error context from the preceding dialog.

[enhancement]

**Comment by EricDahlvang** [comment]
The OnError dialog event works for this: https://github.com/microsoft/botframework-sdk/issues/6080#issuecomment-711091107

closing
