### ISSUE TITLE
Rich Cards (Attachments) not working in Teams & Skype

### ISSUE THREAD

**Issue by pradeepvengala** [Microsoft/BotBuilder-Samples#171]
Rich Cards (Attachments) not showing up in Team & Skype.

I used sample 'CardsBot' and deployed to Azure Web App and updated App ID & Password. However, Cards are not showing up in Microsoft Teams & Skype. 

However, it is perfectly working in BOT Emulator. 

Please help.

**Comment by JasonSowers** [comment]
@pradeepvengala are you using node or .net?

**Comment by pradeepvengala** [comment]
Hi Jason, I’m using .NET code.

Is there any config setting that I need set to make the cards work in Skype for Business & Teams?

Please help!

Thanks,
Pradeep

**Comment by nwhitmont** [comment]
@pradeepvengala What is the URL to the "CardsBot" sample you are using?

**Comment by pradeepvengala** [comment]
URL: https://azurespendbot.azurewebsites.net

One another quick question, how to register BOT with “Skype for business”? Please provide references.

Appreciate your time and help.

Thanks,
Pradeep

**Comment by nwhitmont** [comment]
@pradeepvengala For general questions about Bot Framework, channel configuration, and the Bot Builder SDK, please open a new issue at https://github.com/microsoft/botbuilder/issues/new

**Comment by pradeepvengala** [comment]
Hello Team,

Can you please provide us an update on this issue?

Issue: Rich Cards (attachments) are not showing in Microsoft Teams, Skype. I can only see the cards in BOT Emulator.

Below are the screenshots for your reference. Please help.
[cid:image004.jpg@01D30F84.D000CF10]
Getting below message “Get the latest version of Skype to view this card” even after installing the latest (up to date) version.
[cid:image006.jpg@01D30F84.D000CF10]
Working in Emulator:
[cid:image007.jpg@01D30F84.D000CF10]

From: Pradeep Vengala (HCL America Inc)
Sent: Wednesday, August 2, 2017 7:28 PM
To: 'Microsoft/BotBuilder-Samples' <reply@reply.github.com>; Microsoft/BotBuilder-Samples <BotBuilder-Samples@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/BotBuilder-Samples] Rich Cards (Attachments) not working in Teams & Skype (#171)

URL: https://azurespendbot.azurewebsites.net

One another quick question, how to register BOT with “Skype for business”? Please provide references.

Appreciate your time and help.

Thanks,
Pradeep

**Comment by nwhitmont** [comment]
@pradeepvengala For general questions about Bot Framework, channel configuration, and the Bot Builder SDK, please open a new issue at https://github.com/microsoft/botbuilder/issues/new
