### ISSUE TITLE
QnAPrompting sample does not deserialize metadata tags correctly

### ISSUE THREAD

**Issue by kds-snyder** [microsoft/BotBuilder-Samples#1711]
## Sample information
1. Sample type: \samples\experimental\qnamaker-prompting
2. Sample language: dotnetcore
3. Sample name: QnAPrompting

## Describe the bug
When the QnA KB is queried with a question where the answer contains metadata tags, the metadata in the result returned by **QnAService.QueryQnAServiceAsync** is null. This is because in **QnAResult.cs**, **Metadata** is defined with **{ get;  }** instead of **{ get; set; }**.

## To Reproduce
1. Go to the QnA KB being used for testing
2. Add a metadata tag to one of the question-answer pairs
3. Click **Save and train**
4. Click the **Publish tab**, and then click **Publish**
5. Run the **QnAPrompting** sample, and set a breakpoint in **QnAService.QueryQnAServiceAsync** at the line containing **return result.Answers;**
6. Start the emulator and connect it to the QnAPrompting bot
7. In the emulator, enter the question where you added a metadata tag
8. At the breakpoint, examine **Metadata** in **result.Answers**. You will see that it is null for all answers, including the answer that has a metadata tag

## Expected behavior
For the answer that has a metadata tag, **Metadata** should contain the metadata tag name and value.

## Additional context
This bug can be fixed by modifying **QnAResult.cs** at the line where **Metadata** is defined, to change  **{get; }** to **{get; set; }**

[bug]

**Comment by axelsrz** [comment]
Hey @rokulka , can you look at this customer issue? Thanks.

**Comment by Zerryth** [comment]
@rokulka wanted to chime in that I was able to repro what @kds-snyder reported and adding screen shots for context
______________
### Running `qnamaker-prompting` sample as is

#### My KB - Q&A pairs with metadata
![image](https://user-images.githubusercontent.com/35248895/63301544-abcd9680-c28f-11e9-9f5f-79b730798ca8.png)

#### Breakpoint to view `qnaResult` in `QnADialog.cs`. 

* `Metadata` is `null` for all results returned from `generateAnswer` API call
![image](https://user-images.githubusercontent.com/35248895/63301273-00244680-c28f-11e9-82dd-964276515eed.png)

___

### Updating `QnAResult.cs`

* Updated to `public QnAMetadata[] Metadata { get; set; }`

#### Breakpoint again to view `qnaResult` in `QnADialog.cs` with being able to set `Metadata`

![image](https://user-images.githubusercontent.com/35248895/63301468-75901700-c28f-11e9-9bbf-6c1be9d0d584.png)

* Metadata for an answer without `Metadata` is now `[]`
* For answers with `Metadata`, results now properly show `Metadata[]`

**Comment by rokulka** [comment]
I'm looking into it.

**Comment by daveta** [comment]
Hi @kds-snyder : Thanks again for reporting.  Let us know if this doesn't address your issue.

**Comment by kds-snyder** [comment]
@axelsrz, @rokulka, @Zerryth, @trojenguri, @daveta, thanks for your quick resolution of this issue.
