### ISSUE TITLE
Update es6 70.styling-webchat sample

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotBuilder-Samples#1712]
## Description 
I think that perhaps the entire [javascript_es6](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_es6) directory should be removed?  If not, at least sample [70.styling-webchat](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_es6/70.styling-webchat) is not longer applicable since the change to Direct Line impacts how secrets/tokens are used, This sample needs to be removed.

Note sure about sample [01.browser-echo](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_es6/01.browser-echo).

**Comment by tdurnford** [comment]
@corinagum thoughts?

**Comment by mdrichardson** [comment]
`01.browser-echo` probably is one of the least popular samples, but it does demonstrate some interesting functionality: hosting the bot entirely in the user's browser.

**Comment by corinagum** [comment]
Agree with @mdrichardson :)

Not sure what you mean about sample 70... can't it just be updated? Web Chat samples already document this extensively.

**Comment by corinagum** [comment]
@axelsrz, FYI: I am removing labels since @WashingtonKayaker is part of the docs team.

**Comment by tdurnford** [comment]
The Web Chat samples request a token from Mock Bot to initiate the conversation, but [70.styling-webchat](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_es6/70.styling-webchat) just uses a Web Chat secret. Neither are wrong, but I think we should encourage our users to use a token instead of their secret on their client sites.

**Comment by sgellock** [comment]
The web chat sample, if it needs updating, should be updated.  I'm still of the opinion that the es_6 folder demonstrates concepts that have customer interest.  @corinagum does Web Chat sample need an update?

**Comment by corinagum** [comment]
@sgellock, yes. Previously @compulim and I didn't make changes to Web Chat looking for the secret because of the ongoing secret/token discussion, but since it sounds like we are officially promoting token retrieval we can emulate this sample to look like Web Chat. I'm happy to make those edits. :)

**Comment by stevengum** [comment]
@sgellock and @corinagum I've labeled this for 4.6 and with a P2 label for now.

@corinagum I updated the title as well with where I _think_ we want to be, but can you determine if we want to keep sample 70 and update it, or if we want to remove it and update 01.browser-echo?

**Comment by corinagum** [comment]
I think the plan is to update both. Updated title accordingly :)
