### ISSUE TITLE
State management samples need to show how to use Cosmos DB

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#1719]
## Sample information
1. Sample type: samples
2. Sample language: [dotnetcore, nodejs]
3. Sample name: 45.state-management

## Describe the bug
CSS would like to have a sample that shows how to use Cosmos Db and BlobStorage.  Our current state-management sample uses memoryStorage()

**Comment by mdrichardson** [comment]
I'd recommend waiting until [this is fixed](https://github.com/microsoft/botframework-sdk/issues/5467), then we can also include Partition Keys and some general guidance around them. I've also got [a draft blog post](https://microsoft-my.sharepoint.com/:w:/p/v-micric/EYhDBMJxSItGldr_j9x_K_8B68fhEkszhL9-sJ1vCDwFXQ?e=Lw6j2L) ready-ish to launch for this as well.

**Comment by cleemullins** [comment]
@garypretty The ball is in your court. We can push this to 4.7, if the referenced CosmosDB issue needs to be fixed first.

**Comment by garypretty** [comment]
@cleemullins We have the new storage provider in now. I'll update the sample to show blob and the new cosmos usage and ready to go for 4.6.
