### ISSUE TITLE
intelligence-SpeechToText bot always gives timeout 

### ISSUE THREAD

**Issue by pomarc** [Microsoft/BotBuilder-Samples#172]
### SDK Platform
node sdk

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-SpeechToText

### Problem Description
I've added my key, started the sample. each time I upload the wav the bot waits, then there is a timeout when posting the wav to Bing.
The access token is received correctly by the bot, but the post request fails with timeout.

**Comment by stevencl** [comment]
I had a similar problem with the Skype calling bot sample. There was a line of code that was commented out in the sample:

binaryContent.Headers.TryAddWithoutValidation("content-type", "audio/wav; codec=\"audio/pcm\"; samplerate=16000");

After uncommenting that, I was able to upload the audio.

I don't know why that line was commented out in the original sample. (line 45 - https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/skype-CallingBot/Services/MSCognitiveSpeechService.cs)

**Comment by EricDahlvang** [comment]
The V3 intelligence-SpeechToText sample is fixed with this PR: https://github.com/Microsoft/BotBuilder-Samples/pull/1226 It is now using Cognitive Services Speech, instead of the deprecated Bing Speech.
