### ISSUE TITLE
“No such host is known” when publishing to azure but working fine in emulator.

### ISSUE THREAD

**Issue by bnj123** [microsoft/BotBuilder-Samples#1722]
## Sample information
1. Sample type: bot with luis,qna and dispatch bot
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: NLP with dispatch bot

## Describe the bug
LUIS,QnA and Dispatch bot workning fine on emulator but gives an exception when published on azure and tested on facebook messenger.
All the luis,qna and dispatch keys are working fine on emulator and to the other older bot i have.
I have added the exception message to the error text that is why i can see it on messenger.

## Expected behavior
Expected the bot and services to work properly like on emulator.

## Screenshots
![image](https://user-images.githubusercontent.com/43533891/63517196-16e1cc00-c521-11e9-90a7-189c3a061656.png)

## Additional context
appsettings:
```json
 {
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },

  "MicrosoftAppId": "",
  "MicrosoftAppPassword": "",

  "DispatchLuisAppId": DispatchAppId,
  "DispatchLuisAPIKey": DispatchAPIKey,
  "DispatchLuisAPIHostName": "southeastasia",

  "LuisAppId": LuisAppId,
  "LuisAPIKey": LuisAPIKey,
  "LuisAPIHostName": "southeastasia",

  "QnAKnowledgebaseId": QnaMakerKBId,
  "QnAEndpointKey": QnaMAkerEndpointKey,
  "QnAEndpointHostName": QnaMakerEndpointHostName,
  "AllowedHosts": "*"
}
```

botservice
```csharp
 public class BotServices : IBotServices
{
    public BotServices(IConfiguration configuration)
    {
        DispatchService = new LuisRecognizer(new LuisApplication(
        configuration["DispatchLuisAppId"],
        configuration["DispatchLuisAPIKey"],
        $"https://{configuration["DispatchLuisAPIHostName"]}.api.cognitive.microsoft.com"),
        new LuisPredictionOptions { IncludeAllIntents = true, IncludeInstanceData = true },
        true);

        LuisService = new LuisRecognizer(new LuisApplication(
        configuration["LuisAppId"],
        configuration["LuisAPIKey"],
        $"https://{configuration["LuisAPIHostName"]}.api.cognitive.microsoft.com"),
        new LuisPredictionOptions { IncludeAllIntents = true, IncludeInstanceData = true },
        true);

        QnaService = new QnAMaker(new QnAMakerEndpoint
        {
            KnowledgeBaseId = configuration["QnAKnowledgebaseId"],
            EndpointKey = configuration["QnAEndpointKey"],
            Host = configuration["QnAEndpointHostName"]
        });
    }

    public LuisRecognizer DispatchService { get; private set; }
    public LuisRecognizer LuisService { get; private set; }
    public QnAMaker QnaService { get; private set; }
}
```

[bug]

**Comment by daveta** [comment]
Hi @bnj123 : Can you try and change your `LuisAPIHostName` to something like:
    Australia East - `australiaeast.api.cognitive.microsoft.com`
    West Europe - `westeurope.api.cognitive.microsoft.com`
    West US - `westus.api.cognitive.microsoft.com`
And see if that helps?

**Comment by mdrichardson** [comment]
@sgellock This has been a major pain-point for customers. I [opened a quick-fix PR for this](https://github.com/microsoft/botbuilder-js/pull/1083) and I agree with @cleemullins 	that there are better options; they just need to be addressed and implemented. I'm going to leave this ticket up due to [supportability], but will answer the [user's SO question](https://stackoverflow.com/questions/57600902/botframework-publish-to-azure-error-no-such-host-is-known).

@bnj123 Feel free to unsubscribe from this issue as I'll be answering you on your SO post. In the meantime, it may help to review the linked PR and attempt @daveta's suggestion while I look into this further.

**Comment by mdrichardson** [comment]
Digging into this a little further, the error does not *appear* to be related to format of `LuisAPIHostName`. Still, this is a major pain-point

**Comment by bnj123** [comment]
Thank you as instructed i will respond in stackoverflow.

**Comment by bnj123** [comment]
@daveta something weird happened. in appsettings i changed hostname to " "DispatchLuisAPIHostName": "southeastasia.api.cognitive.microsoft.com", and in botservice      $"https://{configuration["DispatchLuisAPIHostName"]}"), now it is replying but detecting everything i type as "cancel" intent.

**Comment by bnj123** [comment]
This is my SO question it is a lot detailed and has images thank you 
https://stackoverflow.com/questions/57600902/botframework-publish-to-azure-error-no-such-host-is-known

**Comment by mdrichardson** [comment]
@bnj123 	Sorry. Somehow this one fell by the wayside. You got this working, right? This can be closed?

**Comment by tsuwandy** [comment]
@bnj123, closing this as issue seems to be resolved.   Please reopen otherwise.
