### ISSUE TITLE
TypeScript / NodeJS CoreBot Sample assumes user responds to date prompt with text

### ISSUE THREAD

**Issue by DDEfromOR** [microsoft/BotBuilder-Samples#1728]
## Sample information
1. Sample type: [\samples\ or \solutions\]
\samples\typescript-nodejs\13.core-bot
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
TypeScript
3. Sample name: <Name of the sample>
13.core-bot
## Describe the bug
When going through the trip booking dialogue and reaching the point where the bot asks for a date the user response is assumed to be a string and throws an error when trying to call `toLowerCase` on any other data type, and sends no conversation update. This is inconsistent with the behavior elsewhere in the dialogue where responding with nonsensical data, like say an image, is gracefully handled without throwing an error in the bot and the previous prompt is repeated to the user. 

## To Reproduce
1. Build the 13.core-bot sample and run it using the Bot Emulator as the client.
2. Provide answers for the question of what city you are travelling to and what city you are travelling from.
3. When asked for a travel date, upload an awesome image instead of typing an answer.
4. See an error thrown by the bot and note the lack of a response to the user.
5. From the emulator, type a response and send it to the bot. 
6. Note the bot now responds as though it failed to understand your answer.

## Expected behavior
The bot should handle nonsensical responses to different prompts the same way, ideally by providing a useful tip and repeating the prompt.

## Screenshots
Emulator:
![image](https://user-images.githubusercontent.com/9256372/63619192-cad76b80-c5a2-11e9-9924-348bd390e24c.png)
Bot:
![image](https://user-images.githubusercontent.com/9256372/63619212-d9258780-c5a2-11e9-8e9f-734160f3359d.png)
Emulator after sending a typed response:
![image](https://user-images.githubusercontent.com/9256372/63619362-4d602b00-c5a3-11e9-9b71-81e1235af0f9.png)

## Additional context
I do weird things while testing my bot adapters.

[bug]

**Comment by stevengum** [comment]
It's unclear if the C# version contains the same type of bug (missing text running through the Recognizers Text library). Probably not, but we should investigate.

**Comment by sgellock** [comment]
This has implications on the yeoman generator

**Comment by stevengum** [comment]
@mdrichardson can you take a pass at hardening this code? Potential changes here might be required in the other languages.

**Comment by mdrichardson** [comment]
@stevengum Yep. Should have time to look at this early next week.
