### ISSUE TITLE
Deploy to azure button

### ISSUE THREAD

**Issue by diberry** [microsoft/BotBuilder-Samples#1729]
Can you add the deploy to azure button back? Was it problematic to maintain over time or was there some other reason it is no longer supplied?

All up samples review for R10 https://github.com/microsoft/botframework-sdk/issues/5897

**Comment by AlexanderYWH95** [comment]
i prefer all of u to chnge ur tools first, its "NOTEPAD PROGRAMMERS" and not VCS bfr start, dyd notice "this probs" when coding.... LOL
ok, now, bfr that, why not jst use ths instd?

float.h }return
not azure user, so dont care

also do know, fr BOT BUILDING, ok, no more lies..
ever heard of ths? stringing narator + batch + in +header +button
sapisvs=
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
-batch-
if " " goto " "
%speech " reply "
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
then string "tht script" with 
#include <the/bat/lib/script.bat>
int system_cstring_thescript.dll
then use "narator for speak", u sure not wanted to use "Marker" or "Matcher" like google instead?

**Comment by AlexanderYWH95** [comment]
Do notice fact, do u guys notice 1 fact?
when u guys write using "azure"
whre does all the code written by others "gone or run" to?
not display on the window...
azure is jst "knect", data storage...
that why bill gates himsele obviously state VCS "EDITOR", not "WRITTER"
https://www.pnotepad.org/     <<<real writters tools.. thnks

**Comment by AlexanderYWH95** [comment]
u cn build a walking server, but do u really want that walking server?
if others hit the bot, then no more data or leak by those who hit and take away the bot....
duo email
like Idmatcher="true"
1 email, with 2 or "duo" located at 1 plces, using GPS, detected
then 
int system
if IDMatcher="true"
{ run speak.bat
} 
\\
{ if idmatcher="false" } return;
}
\\ 

SAMPLE

**Comment by AlexanderYWH95** [comment]
https://github.com/ferhatelmas/sexmachine

do read 12yrs old projct, why nt hlp w ths instd of new proj?

**Comment by diberry** [comment]
@mdrichardson @CoHealer Can the deploy to Azure buttons come back in the table that lists the samples?

**Comment by CoHealer** [comment]
Hi Dina, Michael just pointed out to me that these buttons are in the v3 README. Were they ever in v4? I honestly don't know if this can happen or not. Perhaps you should file a more formal DCR.

**Comment by sgellock** [comment]
@diberry I've added it to the backlog for consideration.

**Comment by garypretty** [comment]
Hi @diberry. We have reviewed this issue as part of our R10 workstream. At this time we have no plans to re-instate the Deploy to Azure buttons.  This is due to a combination of factors including, the requirement for the buttons to work across all 4 SDK languages and the fact that many of our samples require pre-requisite setup and will throw exceptions on startup without those pre-reqs in place.

We will be continuing to look at ways to help smooth the process for developers, but at this stage it is out of scope. Thanks for raising the issue and having us review though.
