### ISSUE TITLE
Unable to get user Email address in 1-1 Private conversation in Microsoft Teams

### ISSUE THREAD

**Issue by satyansh-sagar** [microsoft/BotBuilder-Samples#1736]
How to get user email address in Private chat conversation in Microsoft teams. I'm using the v4 of bot framework.

If anyone can help me on this. :| 

@msft-shahins  @msftgits

**Comment by satyansh-sagar** [comment]
I am getting the user name and AAD object ID.

**Comment by satyansh-sagar** [comment]
The above link works fine fir a bot in channel where members are present. But the same thing is not working in 1-1 chat conversation.
![thumbnail_image](https://user-images.githubusercontent.com/30821164/63912735-89840780-ca4b-11e9-9527-234488b03835.png)

**Comment by mdrichardson** [comment]
@satyansh-sagar 	Interesting. I tested the Node code in a 1:1 conversation and it worked. I'll test the C# code today.

**Comment by mdrichardson** [comment]
@satyansh-sagar I see the issue. I think you're using the wrong bit of code from that answer for this. Use this:

```csharp
var credentials = new MicrosoftAppCredentials("<yourAppId>", "<yourAppPassword>");
var connector = new ConnectorClient(new Uri(turnContext.Activity.ServiceUrl), credentials);
var conversationId = turnContext.Activity.Conversation.Id;
var userInfo = await connector.Conversations.GetConversationMembersAsync(conversationId );
```

![image](https://user-images.githubusercontent.com/40401643/63952831-166f9680-ca35-11e9-8d2d-3437d5c09a93.png)

And yes, this was in a 1:1 conversation:

![image](https://user-images.githubusercontent.com/40401643/63952907-330bce80-ca35-11e9-87ff-e4f8c49c0510.png)

**Comment by satyansh-sagar** [comment]
Great! This worked for me. Thank a lot @mdrichardson :)

**Comment by mdrichardson** [comment]
@satyansh-sagar 	Tough to say. It likely has something to do with the Teams Extension. Normally, I'd say we should track it down and then submit a PR to fix. However, we're working on rolling the Teams Extension into the Bot Framework SDK, so it will likely be fixed anyway.
