### ISSUE TITLE
OAuthPrompt popup is not showing for login in MS-Teams.

### ISSUE THREAD

**Issue by Rashree138** [microsoft/BotBuilder-Samples#1739]
I have use OAuthPrompt card to login user for bot authentication. It is working in Emulator but when i test in Teams then pop-up is not showing to login.

sample code: 
==========
return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), null, cancellationToken);

Bot Framework version: 4.5.1

**Comment by mdrichardson** [comment]
@Rashree138 	Please [add `token.botframework.com` to your ValidDomains in your App Manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card#getting-started-with-oauthcard-in-teams) and let me know if you still experience this issue.

**Comment by Rashree138** [comment]
Thanks,
It is working now....
