### ISSUE TITLE
OnMessageActivityAsync() is not called after login in OAuth card

### ISSUE THREAD

**Issue by Rashree138** [microsoft/BotBuilder-Samples#1745]
Hi Team,

I am using Oauth card to login. But when I provide my credentials and logged in then OnMessageActivityAsync() method is call, that's why my further steps is not able to execute.

**Below is the sample code:**
======================

```csharp
 public class GPCBot<T> : ActivityHandler where T : Dialog
    {
public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            var activity = turnContext.Activity;
            var logData = new LogData();
            logData.Parameter = activity;
            _logHelper.Info("OnTurnAsync started....", logData);
            await base.OnTurnAsync(turnContext, cancellationToken);
          // Save any state changes that might have occured during the turn.
            await ConversationState.SaveChangesAsync(turnContext, false, cancellationToken);
            await UserState.SaveChangesAsync(turnContext, false, cancellationToken);
            _logHelper.Info("OnTurnAsync completed.");
        }
//THIS METHHOD IS NOT CALLED=>        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            Logger.LogInformation("Running dialog with Message Activity.");
            _logHelper.Info("[GPCBot] Running dialog with Message Activity.");
            // Run the Dialog with the new message Activity.
            await Dialog.RunAsync(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
        }
}
```

Is there any issue with Manifest file because earlier Login popup is not coming? 
After adding below code then login popup apears for login.

```json
"validDomains": [
	"token.botframework.com"
	]
```

Below some other values used in manifest file:

```json
"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "1.0.1",
 "permissions": [
        "identity",
        "messageTeamMembers"
    ],
```

**Comment by mdrichardson** [comment]
@Rashree138 Can you provide steps to reproduce your issue? I'm not sure that I fully understand it.

What sample are you using? If you're building a Teams bot with OAuth, you need to use/integrate the [Sample 46 - Teams Auth](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/46.teams-auth/), particularly the [TeamsActivityHandler](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/46.teams-auth/TeamsActivityHandler.cs) due to Teams handling auth a bit different than other channels.

**Comment by mdrichardson** [comment]
@Rashree138 	Are you still experiencing this issue? We need activity on it to keep it open.

**Comment by mdrichardson** [comment]
@Rashree138 	Are you still experiencing this issue? We need activity on it to keep it open.
