### ISSUE TITLE
How should i use human handoff for "handoff-library"

### ISSUE THREAD

**Issue by Kumar3010** [microsoft/BotBuilder-Samples#1750]
could you please redirect me to a sample where i can use the human handoff-library.
i was getting an error 
 Operation returned an invalid status code 'NotFound'.
this has been tested in the emulator

**Comment by hcyang** [comment]
@arturl, can you take a look of this issue? Thanks.

**Comment by mdrichardson** [comment]
@Kumar3010 	The sample [can be found here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library). Note that's in `experimental`, which isn't meant for public consumption. @arturl will need to comment on the state of that sample.

In the meantime, if you're looking for handoff samples that don't use `handoff-library`, these samples are commonly recommended:

* [C#](https://github.com/tompaana/intermediator-bot-sample)
* [Node](https://github.com/tdurnford/botframework-human-handoff)

**Comment by arturl** [comment]
Hi @Kumar3010, the library requires a channel that today you need to build yourself, for example based on your own bot adapter. In the future, we will ship such channel as part of the Bot Framework.

**Comment by Kumar3010** [comment]
Thank you @arturl  and @mdrichardson .
