### ISSUE TITLE
Broken links in the readme of sample .../javascript_es6/01.browser-echo

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotBuilder-Samples#1751]
There appears to be broken links in the 01.browser-echo sample app readme, in the very first section titled 'browser echo sample' that is pointing to WebChatAdapter: 

https://github.com/microsoft/BotBuilder-Samples/blob/master/src/webChatAdapter.js

And another broken link pointing to WebChatAdapter in the section titled 'Adapters' (The last 2 letters should be ts, not js):

https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_es6/01.browser-echo/src/WebChatAdapter.js

I believe that those links should be: 

https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_es6/01.browser-echo/src/webChatAdapter.ts

**Comment by v-kydela** [comment]
Thank you, @WashingtonKayaker 

I have submitted a pull request
