### ISSUE TITLE
[azure] Deploy node sample

### ISSUE THREAD

**Issue by mpicciolli** [Microsoft/BotBuilder-Samples#176]
Hi, 

I want to deploy Node/demo-ContosoFlowers project on Azure.

I have to create a Bot service ressource or a Web app ? Because if i create a bot service ressource, and deploy demo-ContosoFlowers code, bot doesn't work : 
> There was an error sending this message to your bot: HTTP status code NotFound

Maybe i have to add port in environnement variable ? but which ?

**Comment by JasonSowers** [comment]
You are looking for a web app, the bot service uses azure functions to build your bot.  [Here is a blog](https://blog.botframework.com/2017/04/27/Deploying-Botframework-To-Azure-On-Linux/) explaining how to do it in azure using linux.
