### ISSUE TITLE
How to add potentialAction in card relates to .NET

### ISSUE THREAD

**Issue by gomteshhatgine** [Microsoft/BotBuilder-Samples#177]
### SDK Platform
 Relates to .NET

### Problem Description
I have to add **"Add a comment** button in card and when I click on that it will shows input box after putting comment that comment should post into API but 
**Not getting property for potentialAction in cards**
as suggested here
[https://docs.microsoft.com/en-us/outlook/actionable-messages/card-reference#actions](url)

My code is 
[code1.txt](https://github.com/Microsoft/BotBuilder-Samples/files/1230787/code1.txt)

**Comment by JasonSowers** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3012

What channel are you using?  the "Invoke" action is specific to MS teams.  I think there is some confusion between the broad term "cards"  and the rich cards/adaptive cards that bot framework can use.

**Comment by gomteshhatgine** [comment]
Currently I getting response to API endpoint for invoke operations.

but actual problem is there any way send any card having comment box and button from C# code instead of JSON payload into MS teams through BOT

**Comment by gomteshhatgine** [comment]
So is there not any way to perform invoke action buttons in O365ConnectorCard

**Comment by JasonSowers** [comment]
The bot framework supports [Adaptive cards](http://adaptivecards.io/) and [Rich cards](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments).  There is no O365ConnectorCard support within bot framework that I know of.  Maybe using one of these cards would solve your problem.  Would you explain your use case a bit we could suggest a different card that meets your need.  

the subject matter expert for MS Teams would be @RichMoeMSFT.  let's see what he says about the ConnectorCard.

**Comment by gomteshhatgine** [comment]
Actually I have sent  O365ConnectorCard using Bot framework in Microsoft teams but I not able to get return event or reply from that card in MS teams to bot api endpoint.

My use case is:
  I have send  O365ConnectorCard using Bot framework C# in MS teams in that there is **Add comment ** button when user in MS teams click on that button it shows one textbox the user enter comment into that textbox and post that comment then that comment should submit to Bot API endpoint
  
   For input box and comment button I have used 
   `
                var actionCard2 = new O365ConnectorCardActionCard(
                    O365ConnectorCardActionCard.Type,
                    "Reject",
                    "card-2",
                    new List<O365ConnectorCardInputBase>
                    {
                         new O365ConnectorCardTextInput(
                            O365ConnectorCardTextInput.Type,
                            "text-123",
                            true,
                            "Enter comment here...",
                            null,
                            true,
                            null),

                    },
                    new List<O365ConnectorCardActionBase>
                    {
                        new O365ConnectorCardHttpPOST(
                            O365ConnectorCardHttpPOST.Type,
                            "Comment and Reject",
                            "card-2-btn-1",
                            @"{""text1"":""{{text-123.value}}"),

                    }
                );`

I have used this way because My use case is when user click on Reject button user should enter comment for that and submit that to Bot api endpoint
Currently I have this using O365ConnectorCard

**Comment by gomteshhatgine** [comment]
And even I tried to us Adaptive card sample as suggested here 
[https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#adaptive-card](url)

but it throws exception such as
**{"Attachment type isn’t supported"}**

while sending card in MS teams

**Comment by JasonSowers** [comment]
I apologize for the misinformation MS Teams does not support adaptive cards.

**Comment by JasonSowers** [comment]
I reached out to the MS Teams team for guidance

**Comment by JasonSowers** [comment]
The response was that ActionableMessage is not currently supported. Proper ActionableMessage support should be coming to Teams in the next month or so.  Closing this issue as it is not currently a feature.  Please continue the conversation as needed and we can always reopen.

**Comment by r4hulp** [comment]
Hi @JasonSowers 

The ActionableMessage is still not supported in Teams. can you redirect me to right forum to raise it as an issue (something like Github issues but for Teams)?
