### ISSUE TITLE
Runing nodeJs npl-with-dispatch BotBuilder sample behind corporate proxy

### ISSUE THREAD

**Issue by San-eng** [microsoft/BotBuilder-Samples#1777]
I'm trying to run the sample "14.nlp-with-dispatch" on my local machine and test it with the emulator. I have a luis and Qna azure services. I have modified some code under node_module to add proxy configuration (just to run the exemple on my local machine) : this works for my luis service but I didn't find where to add proxy configuration for qna service knowing that I have tried to use npm packages "global-tunnel" and "global-tunnel-ng" but this didn't work for me because my node version is 12.9.1. 
Has anyone experienced this? 
Is there any other way to add proxy configuration for this two services ?

**Comment by diberry** [comment]
@San-eng I don't know the answer, but I'm interested in your scenario. Can you explain why you are adding a proxy to these services? How you added it for LUIS?

**Comment by dmvtech** [comment]
hi @San-eng

Please see the issue [here](https://github.com/microsoft/botbuilder-js/issues/717). As mentioned, that is blocked due to [this](https://github.com/microsoft/botbuilder-js/issues/1072).

I'm not sure of any workarounds at the moment, but I will look into it.

**Comment by dmvtech** [comment]
@diberry I'm not sure about @San-eng's situation, but many scenearios involve situations where code is running behind a proxy, and must only use that proxy. If the application is not configured to send any/all outgoing requests through the proxy, it is blocked.

**Comment by CoHealer** [comment]
@San-eng, do you still require assistance? To keep the issue open we need activity on the thread.

**Comment by San-eng** [comment]
Sorry for the delay ,
@CoHealer  Yes I still require assistance
@dmvtech Thanks for replying
@diberry : As I said , I'm trying to run this exemple locally.
So my bot is runing on my machine and i'm using the emulator to test it.
But in my case I have luis and Qna azure services that I need to call behind a corporate proxy.
I didn't find a way to add proxy configutaion for only this two services so I modified some code in node_module to work around this as bellow:
luis :  /@azure/cognitiveservices-luis-runtime/node_modules/@azure/ms-rest-js/dist/msRest.node.js I added my proxy URL as parameter to getDefaultProxySettings()
Qna : /node-fetch/lib/index.js in fetch function I aded a https proxy agent using 'https-proxy-agent' npm package

**Comment by diberry** [comment]
@San-eng Do you have the changes checked in or in a Gist that I can look at? It would be great to get this into the SDKs at some point and into the docs sooner.

**Comment by dmvtech** [comment]
@San-eng, can you try [setting the proxy](https://jjasonclark.com/how-to-setup-node-behind-web-proxy/) in your node environment?

**Comment by dmvtech** [comment]
hi @San-eng

just checking in to see if setting the proxy in the node env helped. Please let me know if you need further assistance.

**Comment by dmvtech** [comment]
Closing this as it doesn't seem assistance is needed at this time. Please reopen if that is the case.
