### ISSUE TITLE
JavaScript samples incorrectly use the ActivityHandler's onMessage handler in place of the onDialog handler

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#1780]
## Sample information
1. Sample type: [\samples\\]
2. Sample language: [es6 or nodejs or typescript]
3. Sample name: All JS dialog samples, for instance [javascript_nodejs/05.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/05.multi-turn-prompt).

## Describe the bug
The code comments in the SDK clearly states that `onDialog` should be used to "handle Dialog activity"; however, every JS sample I've looked at splits dialog activity between the `onMessage` and `onDialog` handlers.

## To Reproduce
1. Look at the code comments for `onDialog`:
   ~~~typescript
   /**
    * onDialog fires at the end of the event emission process, and should be used to handle Dialog activity.
    * @remarks
    * ...
    * @param handler BotHandler A handler function in the form async(context, next) => { ... }
    */
    public onDialog(handler: BotHandler): this {
        return this.on('Dialog', handler);
    }
   ~~~
   https://github.com/microsoft/botbuilder-js/blob/73990aee9aad1b54ba3941d284b9aec3d0009c5f/libraries/botbuilder-core/src/activityHandler.ts#L176-L194
2. Look at a typical implementation of a JS bot that extends the ActivityHandler:
   https://github.com/microsoft/BotBuilder-Samples/blob/4308b0123e0060b7616ea82231742e5c6c59799c/samples/javascript_nodejs/05.multi-turn-prompt/bots/dialogBot.js#L24-L38
3. Error, these two patterns are nigh-incompatible.

## Expected behavior
Our official samples follow our own best practices.

## Additional context
Using `onMessage` as the "jumping off point" for beginning or continuing a dialog is problematic for dialogs that need to handle authentication (event activity) or ones that might welcome a user to the conversation (conversationUpdate activity).

A similar issue exists in the C# samples, but we have no corresponding guidance to use the `OnTurn` handler after it's inner call to `next` completes.

[bug]

**Comment by EricDahlvang** [comment]
@stevengum has a solution for this:

https://github.com/microsoft/BotBuilder-Samples/pull/1964

**Comment by stevengum** [comment]
One additional scenario where we don't use onDialog for dialogs but _should_, is for bots using the `ActivityPrompt`. ActivityPrompt was created with the idea that a user might not necessarily respond to a prompt with a "Message"-type activity. They might instead perform an event that the bot interprets as a response to a the prompt. 

> E.g. A voice-enabled bot in a car asks the driver to put on their seatbelt. When the driver puts on their seatbelt, the bot should not wait for the driver to say "my seatbelt is on". The car should send an "Event"-type activity to the bot once the seatbelt is engaged, indicating that the driver responded to the prompt.

**Comment by johnataylor** [comment]
We've updated the samples - closing this.
