### ISSUE TITLE
Which key to use after buying the azure key ?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotBuilder-Samples#179]
I have written a bot in C# and added luis to it.
the nelow being the basic luis part of the code

```
    // The LuisModel attribute specifies your LUIS app ID and your LUIS subscription key
    [LuisModel("2c2afc3e-5f39-4b6f-b8ad-c47ce1b98d8a", "9823b65a8c9045f8bce7fee87a5e1fbc")]
    [Serializable]
    public class TravelGuidDialog : LuisDialog<object>
```
So in place of model id I've entered the app id from [the luis application](https://www.luis.ai/applications) page. 
The only issue is what should I enter in place of the subscription key.
When I enter the Programmatic API Key found on https://www.luis.ai/keys, the quota gets over once 1000 endpoints are reached and the bot stops working.

So went and bought a key on Azure. Then I added Key1 from the Azure portal to the LUIS application (where it says add a new key) and then entered it in place of the subscription key in the bot code and also added it to the luis by selecting it as the endpoint while publishing the LUIS application.

When I do this the bot doesn't work at all but instead gives me an error saying access denied : error 401.
It works perfectly when i use Programmatic API Key  but I need a more permanent solution.

**Comment by ILOFI** [comment]
If you buy Luis key from Azure, you should notice that, the key can come from different place in the world, because Azure has many servers in the world.
So you should choose the right region corresponding to the key.

` //
        // 
        //     Construct the LUIS model information.
        //
        // Parameters:
        //   modelID:
        //     The LUIS model ID.
        //
        //   subscriptionKey:
        //     The LUIS subscription key.
        //
        //   apiVersion:
        //     The LUIS API version.
        //
        //   domain:
        //     Domain where LUIS model is located.
        public LuisModelAttribute(string modelID, string subscriptionKey, LuisApiVersion apiVersion = LuisApiVersion.V2, string domain = null);
        ...
        // 
        //     Domain where LUIS application is located.
        //
        // Note:
        //     Null means default which is api.projectoxford.ai for V1 API and westus.api.cognitive.microsoft.com
        //     for V2 api.
        public string Domain { get; }
...
`

As the code shows that if you do not specify `domain` parameter, it would use west us as default. Maybe you key is not a west-us key.

**Comment by nupurkamble** [comment]
@ILOFI Thank you so much. It worked. I'm closing the issue. :)
