### ISSUE TITLE
[Teams] Echo bot sample with additional functionality

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotBuilder-Samples#1794]
Create an echo bot sample that includes

- conversation updates
- message reactions
- update/delete activities
- mentions

**Comment by cleemullins** [comment]
Is this done? I thought you had written it, and sent it out for review - but I [can't find the relevant PR](https://github.com/Microsoft/botbuilder-samples/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Avirtual-josh+).

**Comment by Virtual-Josh** [comment]
You can find the draft PR for base echo bot here:

https://github.com/microsoft/botbuilder-dotnet/pull/2676

The only difference between this echo bot and the improved echo bot is the addition of the methods listed above so it's a fairly straight forward copy/paste + known additions. I'm still working on the ARM template so I'll get a PR (and slightly modified readme) for this one once the base is done.

**Comment by Virtual-Josh** [comment]
Done 

https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/teams/csharp-dotnetcore/TeamsEcho

https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/teams/csharp-dotnetcore/TeamsEnhancedEcho
