### ISSUE TITLE
Create a sample to show handoff on 2 clients using directline

### ISSUE THREAD

**Issue by vyomanaut** [microsoft/BotBuilder-Samples#1797]
i have a seen few examples on the internet showing handoff on different channels , but none of them show handoff on 2 channels in a case where both of them use directline API .

**Comment by chrimc62** [comment]
@vyomanaut thanks for the issue, we are working for formalize this and plan to have a solution with samples in our 4.7 release.

**Comment by vyomanaut** [comment]
sure thanks , looking forward to the release :).

**Comment by axelsrz** [comment]
@arturl Do you have any insight you would like to provide on this issue?
