### ISSUE TITLE
[ES][JS] Add prettier to samples

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/BotBuilder-Samples#1808]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

The JS samples have various non-idiomatic things that would be caught with `ts-lint` and `prettier`. For folks running with format on save (relatively common in JS land), this results in a ton of changes since there isn't a formatter specified for the project.

**Describe the solution you'd like**

Enable `es-lint` and `prettier` in each JS sample + include a `.prettierrc`.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

[enhancement]

**Comment by sgellock** [comment]
@christopheranderson we do have lint profiles for all the JS and TS samples.  npm run lint is a command that is available in all the package.json script command sections.  prettier is nice to have, IMHO.  not saying I wouldn't do it, it's just a lower priority in my mind.

**Comment by christopheranderson** [comment]
Yeah, Scott. I dunno what I was looking at wrt es-lint being missing. It is there in every sample. I might have seen some stuff that linting would have caught. Maybe we're not running linting in CI so we're checking stuff in without enforcing linting? I'll figure it out.

**Comment by sgellock** [comment]
I'm moving this out to the MQ milestone
