### ISSUE TITLE
Samples should show alternative approaches to cancelling dialogs

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#1820]
The samples should show alternative approaches to cancelling dialogs - with the current ComponentDialog world.

Refer to https://github.com/microsoft/botbuilder-dotnet/issues/2280

**Comment by cleemullins** [comment]
@johnataylor This bug is 7 months old. If we wait 2 more months, it might come to life!

**Comment by johnataylor** [comment]
we should wait for adaptive to understand how things change here. I'll move to R10 for now.

**Comment by johnataylor** [comment]
With the introduction of adaptive dialogs we will start to adopt the new features across the dialog samples.
As it is with the pre-adaptive samples the code in Core Bot illustrates the appropriate cancel logic. However, cancelation remains a task the bot designer needs to craft carefully. Closing this as we are not going to refresh this aspects of the samples outside of introducing some aspects of the new adaptive structures.
