### ISSUE TITLE
Update all Samples to 4.6 Dependencies

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotBuilder-Samples#1826]
Before we merge the 4.6-Staging branch, all existing samples (JS / TS / .Net Core / WebAPI) need to be updated to the 4.6 set of packages. 

- [x] Javascript
- [x] Typescript
- [x] DotNet Core
- [x] WebAPI
- [x] VSIX
- [x] .NET Templates
- [x] Yeoman generator

**Comment by sgellock** [comment]
@johnataylor I've updated all the JS, TS, Yeoman, .NET Templates, and VSIX templates.  Can you do the remaining csharp samples for dotnetcore and webapi?

**Comment by johnataylor** [comment]
we have an open issue on upgrading webapi.
The main NuGet packages include some schema files (accidentally?)
these are being added to teh project when you restore in webapi

**Comment by johnataylor** [comment]
Everything now on 4.6.1 (including webapi) 😃
