### ISSUE TITLE
Sample to handle user interruptions missing ?

### ISSUE THREAD

**Issue by vyomanaut** [microsoft/BotBuilder-Samples#1847]
I see it in the documentation , has it been removed ? if yes will it be added again ?

edit ; clicking the link in the documentation takes us to the core bot sample .

**Comment by mdrichardson** [comment]
@vyomanaut That _is_ the correct sample for handling user interruptions. Specifically, the `CancelAndHelpDialog`:

* [C#](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.core-bot/Dialogs/CancelAndHelpDialog.cs)
* [Node](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/dialogs/cancelAndHelpDialog.js)
* [TypeScript](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/typescript_nodejs/13.core-bot/src/dialogs/cancelAndHelpDialog.ts)
