### ISSUE TITLE
SpeechToText issue : One or more errors occurred.

### ISSUE THREAD

**Issue by leoullas** [Microsoft/BotBuilder-Samples#185]
Can anyone help with this? "One or more errors occurred."
PFB the stack trace. The issue is with SpeechToText, while sending request. Please note, I have used my own key for the API.

**Stack Trace:**

>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at SpeechToText.Services.Authentication.GetNewToken() in C:\Users\xxxxxx\BOT\intelligence-SpeechToText\Services\Authentication.cs:line 64
>    at SpeechToText.Services.Authentication.RefreshToken() in C:\Users\xxxxxx\BOT\intelligence-SpeechToText\Services\Authentication.cs:line 80
>    at SpeechToText.Services.Authentication.GetAccessToken() in C:\Users\xxxxxx\BOT\intelligence-SpeechToText\Services\Authentication.cs:line 45
>    at SpeechToText.Services.MicrosoftCognitiveSpeechService.<GetTextFromAudioAsync>d__0.MoveNext() in C:\Users\xxxxxx\BOT\intelligence-SpeechToText\Services\MicrosoftCognitiveSpeechService.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at SpeechToText.Controllers.MessagesController.<Post>d__1.MoveNext() in C:\Users\xxxxxx\BOT\intelligence-SpeechToText\Controllers\MessagesController.cs:line 38

**Comment by leoullas** [comment]
Is there no one to share some idea to resolve this?

**Comment by EricDahlvang** [comment]
The V3 intelligence-SpeechToText sample is fixed with this PR: https://github.com/Microsoft/BotBuilder-Samples/pull/1226 It is now using Cognitive Services Speech, instead of the deprecated Bing Speech.
