### ISSUE TITLE
C# sample for Adaptive Cards in Teams should use raw JSON files rather than AdaptiveCards package

### ISSUE THREAD

**Issue by siduppal** [microsoft/BotBuilder-Samples#1860]
## Sample information
1. Sample type: [\samples\ or \solutions\] samples
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript] dotnetcore
3. Sample name: AdaptiveCards

## Describe the bug
Given the richness of Adaptive Cards, the ideal way for developers to use them is to design the card layout in [Adaptive Card designer](https://adaptivecards.io/designer/) and then use the JSON as an attachment in activity ([example](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0#send-an-adaptive-card)). When in need of an Adaptive Card, one typically starts from one of the sample layouts and tweaks it in the AC Designer to get what they want.

However, the current C# sample leads developers to write code by hand to get the Adaptive Card layout they want. In practice, that this is a very bad way to do it and iterate on layout later. Please fix this! 

[https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/teams/csharp-dotnetcore/AdaptiveCards/Bots/AdaptiveCardsBot.cs](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/teams/csharp-dotnetcore/AdaptiveCards/Bots/AdaptiveCardsBot.cs)

The Node sample doesn't suffer from this issue though (ref), only the C# one does. We should have a similar approach between JS and C# sample for consistency.

## To Reproduce
Examine this file
[https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/teams/csharp-dotnetcore/AdaptiveCards/Bots/AdaptiveCardsBot.cs](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/teams/csharp-dotnetcore/AdaptiveCards/Bots/AdaptiveCardsBot.cs)

## Expected behavior
Give a clear and concise description of what you expected to happen.
Treat the Adaptive Card JSON as opaque and send it as an attachment to bot with the correct content-type

## Additional context

[bug]

**Comment by stevengum** [comment]
I agree with this; currently this is the best experience for creating and editing an Adaptive Card for use in Teams. The Designer for Adaptive Cards previews what the card will look like in Teams (Dark and Light Themes) by the "Select host app:" dropdown:

![adaptive card designer](https://user-images.githubusercontent.com/14935595/67453266-11653880-f5db-11e9-909d-9835baadb7d7.jpg)

___

### JS/TS samples note: 
Our linting configuration will have a fit for the use of double-quotes, so please disable the rule and reenable it in the samples if you're creating the card inline. If you're using a separate .json file there shouldn't be a problem.

**Comment by johnataylor** [comment]
@siduppal we have new samples published in both the javascript_nodejs and csharp_dotnetcore folders - I'll retitle this issue.

We should update the relevant C# samples to use raw JSON files...
- TeamsMessagingExtensionsActionPreview
- TeamsMessagingExtensionsSearchAuthConfig
- TeamsTaskModule

@EricDahlvang can you comment.

**Comment by EricDahlvang** [comment]
I think there is value in demonstrating both methods. It is good to provide options to developers.
