### ISSUE TITLE
Microsoft.Cognitive.LUIS.ActionBinding doesn't work for builtin datetimeV2 entity

### ISSUE THREAD

**Issue by edwardbakker** [Microsoft/BotBuilder-Samples#187]
The LUIS action binding example (https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/Blog-LUISActionBinding) doesn't work for the builtin datetimeV2 entity. 

It looks like a change is needed in the 'BuiltInDatetimeTypes' class but also the 'LuisActionResolver' needs some modifications in the 'AssignValue' method. 

Can we expect an update for the libray to make this work?

Thanks!
Edward

**Comment by bs-oke** [comment]
@edwardbakker 
I have the same problem. As it's not possible to use an old datetime any more (at least for new apps) action binding becomes useless for any solution which uses dates. 

Can you please update this very nice library to datetimeV2?

Thanks!
Bartek

**Comment by Annabear1103** [comment]
It seems still not solved now...

**Comment by pcostantini** [comment]
Hi @Annabear1103 , @edwardbakker, @bs-oke :

The version in the BotBuilder-Samples is kind of old. The latest version of Luis Action Binding is in its own repo now @ https://github.com/Microsoft/BotBuilder-CognitiveServices

More info @ https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/README_LuisActionBinding.md
