### ISSUE TITLE
Initial request sends a null qnAcontext instead of empty, erroneously matching context-only questions

### ISSUE THREAD

**Issue by tussosedan** [microsoft/BotBuilder-Samples#1871]
## Sample information
1. Sample type: experimental
2. Sample language: csharp_dotnetcore
3. Sample name: qnamaker-prompting

## Describe the bug
Initial request sends a null qnAcontext instead of [empty](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/multiturn-conversation#a-json-request-to-return-an-initial-answer-and-follow-up-prompts). This causes "context-only" questions to match on initial request, when they shouldn't.

## To Reproduce
Create a follow-up question set as "context-only", and see that an initial request matches it when it shouldn't.

[bug]

**Comment by johnataylor** [comment]
@trojenguri could you take a look at this customer reported issue.

**Comment by trojenguri** [comment]
@tussosedan  We have recognized the issue. We are going to deprecate 'qnamaker-prompting' sample and we would be releasing new sample which will contain Multi turn as well as active learning. In that sample, this issue will be resolved. ETA for that sample would be 4th Nov.

**Comment by tussosedan** [comment]
Thank you!
