### ISSUE TITLE
Remove TeamsActivityHandler from Teams-Auth samples

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#1875]
The first version of the TeamsActivityHandler shipped in the teams-auth samples (for both JavaScript and C#).

As this is now incorporated in the product the glass should be dropped from the respective samples.

**Comment by johnataylor** [comment]
We have decided to use this sample to verify our 4.6 bits. So this is high priority.

**Comment by EricDahlvang** [comment]
Re-opening to track migrating the node Teams Auth sample.
