### ISSUE TITLE
sample-payments app - not working on emulation mode

### ISSUE THREAD

**Issue by rondagdag** [Microsoft/BotBuilder-Samples#188]
This used to work a week ago. Everything is setup, the stripe account and linked to Microsoft Wallet.
Now, emulation mode does not work anymore,  set .env file
PAYMENTS_LIVEMODE=true
it will not process the payment properly, Microsoft Wallet displays an error and not callback the bot. It works when I set this to false. It will charge my credit card properly. (It's just too expensive to test)
Any thoughts? 

Ron

**Comment by EricDahlvang** [comment]
Emulator V4 does not currently support payments: https://github.com/Microsoft/BotFramework-Emulator/issues/1324

The V3 emulator can be downloaded from https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v3.5.37 and works with the payments sample
