### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotBuilder-Samples#1883]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
We are randomly encounter this exception in our logs. Due to this issue the response from BOT is taking time from the backend. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/10174566/67907941-ee84d800-fb36-11e9-9f40-d73d7fa7a04b.png)

## Additional context

[bug]

**Comment by dmvtech** [comment]
> We are randomly encounter this exception in our logs. Due to this issue the response from BOT is taking time from the backend.

Hi @vikramdadwal Do you have any metrics or logging in your bot to determine if it is taking a long time? If the response from your bot takes longer than 15 seconds, it will timeout (at least with the Direct Line channel). What channel is this happening for you in?

You can run the following KQL in your applications insights Logs (Analytics) to see if your bot is generally slow (anything over 10 seconds).

```
let start_time = ago(7d);
let end_time = now();
requests
| where duration > 10000
| where timestamp > start_time and timestamp < end_time
| limit 100
```

**Comment by CoHealer** [comment]
@vikramdadwal do you still require assistance or shall we consider the issue resolved?

**Comment by dmvtech** [comment]
Closing due to inaction. Please let us know if you still need assistance with this issue.
