### ISSUE TITLE
Proactive Message Example

### ISSUE THREAD

**Issue by mwbrown66** [Microsoft/BotBuilder-Samples#189]
Has anyone gotten the startNewDialog example to work?  I do not believe it works as written (it doesn't use the required adapter and when I try to use it the patched version of beginDialog is expecting opts to be passed in) and I haven't been able to get it to work yet, just playing with it.

Looks like if I specify to resume it loads the existing session for the user but then when it calls beginDialog nothing happens.

I'm using the Channel Emulator and invoking the proactive dialog via the CustomWebApi link.

**Comment by mwbrown66** [comment]
To clarify: 

I'm building an SMS-based bot on top of the MS Bot Framework. I have a need to have our bot start dialogs with customers. I can do it, but if the user was in a dialog when the proactive dialog is initiated, the old dialog is not resumed. In fact it's wiped off the dialog stack.

Looking at the BotBuilder Samples, has anyone gotten the startNewDialog to work with the botadapter? This is supposed to look up an existing session the customer might be in and allow you to resume an interrupted dialog.

It seems MS tells you the sample code needs the botadapter but then doesn't write the sample to actually use the botadapter. I do not believe it works as written (the patched version of beginDialog is expecting opts to be passed in) and I haven't been able to get it to work yet, just playing with it.
Looks like if I specify to resume it loads the existing session for the user but then when it calls beginDialog nothing happens.

I'm using the Channel Emulator and invoking the proactive dialog via the CustomWebApi link.

**Comment by EricDahlvang** [comment]
I just tried the same sample, from: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages/

![image](https://user-images.githubusercontent.com/11055362/30852011-411f2206-a25f-11e7-9122-cda9089fc0fb.png)

What are the errors you're seeing?  It seems to be working as expected for me.

This sample leaves it to the developer to store, and load, the session.message.address on a per user basis fitting to their scenario.

**Comment by U2AIT** [comment]
Yes, I can save per user's message address to session data. But only the latest user who interactive with the bot can receive the poactivate message, but I want all users can receive the message.
Have you test the Facebook bot with multiple users?
No errors I got, any idea?

Linda Liu

**Comment by EricDahlvang** [comment]
@U2AIT   The example is not complete, and is just an example.  The developer needs to store the session.message.address somewhere other than in memory, and use it to send the messages later.
