### ISSUE TITLE
[Supportability] Add a link on configuring AppInsights for a bot in OnTurnError comments

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#1909]
This information is very valuable, but I wonder if we should provide a link so they can go ahead and do it. The downside is that if the docs link gets stale, so will this.

_Originally posted by @carlosscastro in https://github.com/microsoft/BotBuilder-Samples/pull/1905_

**Comment by stevengum** [comment]
Added R10 and docs labels to prod discussions. @JonathanFingold do you think this should be added?

**Comment by JonathanFingold** [comment]
Is the proposition to link to the how to [add telemetry to your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry) from the code comments in the adapter in all samples?

If so, that seems fine, though you probably want to use an aka link so you can effectively do a bulk update if the URL changes.

**Comment by JonathanFingold** [comment]
@stevengum Assigning back to you.

**Comment by garypretty** [comment]
We can also link to the docs describing the analysis of telemetry using Kusto in Azure.  I have added the BF Docs label so that this can be handled as part of R10.

**Comment by garypretty** [comment]
Will form part of the all up samples review in R10 - https://github.com/microsoft/botframework-sdk/issues/5897

**Comment by garypretty** [comment]
Currently blocked until this PR is merged -> https://github.com/MicrosoftDocs/bot-docs-pr/pull/2262
