### ISSUE TITLE
C# Sample 21: corebot-app-insights

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotBuilder-Samples#1921]
In the **C# Sample 21: corebot-app-insights**, both the `bookingDialog` and `dialog` (MainDialog) objects are `Component Dialogs`, and hence if you set its _Telemetry_ Property that will permeate to all its child dialogs,  which means that all of the code setting up _telemetry_ (**_TelemetryClient = telemetryClient_**) in the `bookingDialog` & `MainDialog` constructors (in the `AddDialog` method calls) are not needed.

[bookingDialog.cs](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs):

I think that the line setting the [TelemetryClient](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L17) variable in the constructor should remain, but all of the **_TelemetryClient = telemetryClient_** lines in the `AddDialog` method calls (for example lines [20](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L20), [24](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L24), [28](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L28), [39](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L39)) are not needed.  With the exception of the line setting the [TelemetryClient](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/BookingDialog.cs#L17) variable, BookingDialog.cs should remain the same as the CoreBot sample.

[MainDialog.cs](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/MainDialog.cs):

I think that the line setting the [TelemetryClient](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/MainDialog.cs#L25) variable in the constructor should remain, but all of the **_TelemetryClient = telemetryClient_** lines in the `AddDialog` method calls (for example lines [29](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/MainDialog.cs#L29) and [41](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/MainDialog.cs#L41)) are not needed.  With the exception of the line setting the [TelemetryClient](https://github.com/microsoft/BotBuilder-Samples/blob/3f35b79f528833b14fd65f573c1f75173a24e05c/samples/csharp_dotnetcore/21.corebot-app-insights/Dialogs/MainDialog.cs#L25) variable, MainDialog.cs should remain the same as the CoreBot sample.

<HR>
See Dialog code in the Bot Framework SDK:

- [Dialog.TelemetryClient](https://github.com/microsoft/botbuilder-dotnet/blob/96b375ae4bc0eb97ec32e57235ce0a9e64f2f30f/libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs#L65)

- [DialogSet.TelemetryClient](https://github.com/microsoft/botbuilder-dotnet/blob/96b375ae4bc0eb97ec32e57235ce0a9e64f2f30f/libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs#L48)

- [ComponentDialog.TelemetryClient](https://github.com/microsoft/botbuilder-dotnet/blob/96b375ae4bc0eb97ec32e57235ce0a9e64f2f30f/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L41)

- [WaterfallDialog.AddStep](https://github.com/microsoft/botbuilder-dotnet/blob/96b375ae4bc0eb97ec32e57235ce0a9e64f2f30f/libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs#L79)

<HR>

An issue was logged against the docs that is impacted by this: [Issue 1388](https://github.com/MicrosoftDocs/bot-docs/issues/1388)

**Comment by scheyal** [comment]
@munozemilio FYI

**Comment by garypretty** [comment]
Docs and sample for C# now up to date.
