### ISSUE TITLE
[Bash 11-05] 50.teams-messaging-extensions-search readme should not say EchoBot

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotBuilder-Samples#1926]
[The 50.teams-messaging-extensions-search readme](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/50.teams-messaging-extensions-search/README.md) says EchoBot instead of the actual name of the sample

![image](https://user-images.githubusercontent.com/41968495/68247389-96832100-ffcf-11e9-8d6e-9cc43e4125fa.png)

[bug]

**Comment by anusharavindrar** [comment]
Same for sample 52.teams-messaging-extensions-search-auth-config
![sample](https://user-images.githubusercontent.com/48731427/68250484-dd741500-ffd5-11e9-9530-36591676e3d5.png)

**Comment by EricDahlvang** [comment]
Thank you for reporting this.

Closing since @johnataylor  fixed these yesterday: https://github.com/microsoft/BotBuilder-Samples/pull/1949
