### ISSUE TITLE
[bug bash] imprecise instruction in readme file 

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotBuilder-Samples#1927]
## Describe the bug
In the Visual Studio paragraph you say to open the manifest.json file, and the context seems to imply that it's at the same level as the appsettings.json.
Say that it's located in the TeamsAppManifest folder.

![image](https://user-images.githubusercontent.com/17152540/68247357-8408e780-ffcf-11e9-9a5e-4b07c5df6232.png)

[bug]

**Comment by johnataylor** [comment]
The C# readmes are now consistent with the JavaScript - should address this. We've hopefully made it much clearer that its the Microsoft App Id.
