### ISSUE TITLE
[bash 11 05] missing link, sample .tsv for Sample 48 readme

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotBuilder-Samples#1928]
In readme:

> Follow instructions here to import and publish the ActiveLearningSampleFAQ.tsv to your newly created QnA Maker service.

ActiveLearningSampleFAQ.tsv links to https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/48.qnamaker-active-learning-bot/CognitiveModels/ActiveLearningSampleFAQ.tsv.

There is no Cognitivemodels folder nor a ActiveLearningSampleFAQ.tsv file.

**Comment by EricDahlvang** [comment]
Thanks @dmvtech  

Fixed: https://github.com/microsoft/BotBuilder-Samples/pull/1957
