### ISSUE TITLE
[bug bash] not clear that the microsoft bot id in the teams manifest should actually be the Microsoft App Id GUID

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotBuilder-Samples#1929]
## Describe the bug
In the doc it says "Replace your botID everywhere you see the place holder string &lt;&lt;YOUR-MICROSOFT-BOT-ID&gt;&gt;".

1- botID is ambiguous, usually the botID is the bot handle. Be clear and say that it should be the App ID (GUID) instead
2-  the actual string to be replaced in the manifest is &lt;YOUR-BOT-ID&gt; instead of &lt;&lt;YOUR-MICROSOFT-BOT-ID&gt;&gt;
![image](https://user-images.githubusercontent.com/17152540/68248056-ef06ee00-ffd0-11e9-8c5b-2f712700c567.png)

[bug]

**Comment by johnataylor** [comment]
Fixed - we updated the readme's everywhere and updated (and consistently) the string we use in the manifest.json.

Please reopen if you think its still not clear enough
