### ISSUE TITLE
Visual Studio 2013 template

### ISSUE THREAD

**Issue by Shamrh** [Microsoft/BotBuilder-Samples#193]
Is there a template for VS 2013 to try out these samples in Visual studio 2013 ? 

We are still behind sadly :(!

**Comment by JasonSowers** [comment]
The template was designed to use with VS 2015 or later.  I'm not aware of anything out there for VS 2013.  The good news is the template will work with [VS Community](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15) the free version of VS
