### ISSUE TITLE
[bug bash] Make bot description of link unfurling sample in c# matches one in js

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1934]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
The JS version has a link to link unfurling documentation.
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/55.teams-link-unfurling
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/55.teams-link-unfurling

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by johnataylor** [comment]
fixed
