### ISSUE TITLE
[bug bash] Bot URL is' http://localhost:3999/api/messages' in 48.qnamaker-active-learning-bot & 49.qnamaker-all-features

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotBuilder-Samples#1935]
## Sample information
1. Sample type: \samples\ 
2. Sample language: dotnetcore 
3. Sample name: 48.qnamaker-active-learning-bot and 49.qnamaker-all-features

## Describe the bug

- In the 'Connect to the bot using Bot Framework Emulator' section, the third step specifies 'Enter a Bot URL of http://localhost:3999/api/messages'.

- When we run the bot, it shows this 'You can test your bot in the Bot Framework Emulator
by connecting to http://localhost:3978/api/messages.'

## To Reproduce
1. Run the 48.qnamaker-active-learning-bot from Visual Studio.
2. Launch Bot Framework Emulator.
3. Enter a Bot URL of http://localhost:3999/api/messages 

## Screenshots
![qna](https://user-images.githubusercontent.com/48731427/68249263-4dcd6700-ffd3-11e9-8b53-2b5631ae44ca.png)

[bug]

**Comment by EricDahlvang** [comment]
Thanks @anusharavindrar 

fixed https://github.com/microsoft/BotBuilder-Samples/pull/1957
