### ISSUE TITLE
[bash 11 05] sample 48. javascript sample folder is incorrectly named

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotBuilder-Samples#1936]
named `48.qnamaker-activelearning-bot` instead of `48.qnamaker-active-learning-bot`. this causes a broken "View" link in https://github.com/microsoft/BotBuilder-Samples/blob/master/README.md

**Comment by EricDahlvang** [comment]
Thank you for reporting this. Addressed here: https://github.com/microsoft/BotBuilder-Samples/pull/1957
