### ISSUE TITLE
[Bash 11-05] 50.teams-messaging-extensions-search readme unclear about app ID

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotBuilder-Samples#1939]
[This readme](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/50.teams-messaging-extensions-search/README.md) needs to be clear that the bot's app ID should be included twice in the manifest.json file, and also that the appsettings.json file needs to be updated.

![image](https://user-images.githubusercontent.com/41968495/68249932-9f2a2600-ffd4-11e9-8ccf-ff2dac712bb9.png)

[This readme](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/README.md) already has good information about that.

[bug]

**Comment by johnataylor** [comment]
Thanks for the feedback - we think it should be much clearer now. See the readme in both C# and JavaScript.
