### ISSUE TITLE
Deploy to Azure buttons ok?

### ISSUE THREAD

**Issue by johnd-ms** [Microsoft/BotBuilder-Samples#194]
I can't get the blue Deploy to Azure buttons to work.

Is there a trick for using these?

**Comment by Pieter-Veenstra** [comment]
Which browser are you using? I found that it didn't work in Edge, but Chrome is fine.

**Comment by FranciscoPonceGomez** [comment]
Hi @johnd-ms, 

Do you still experience problems with the Azure buttons for deployment? They work for me.

Regards,
Francisco
