### ISSUE TITLE
[bug bash] Update all "Further reading" links to open in new tab (target="_blank")

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1940]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
It'll be nice to have the links under "Further reading" open in new tab when clicked so one could stay on sample readme.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by johnataylor** [comment]
Github markdown doesn't support this. Use Cntl-Click.
