### ISSUE TITLE
[bug bash] link unfurling README (All Teams README's)

### ISSUE THREAD

**Issue by daveta** [microsoft/BotBuilder-Samples#1942]
## Link Unfurling
- README should define link unfurling
- Should show how to cause link unfurling
- Should mention only https (and not http) url's covered.
- Should mention caching behavior of Teams for unfurls

## All Teams Samples
- Should define the concept they are demonstrating
- Should have steps to invoke specific functionality
- Should have screen shots invoking on Teams client.

**Comment by mdrichardson** [comment]
I'd like to add that Node READMEs should mention editing `.env` and not `appsettings.json` (Sample 55 does not)

**Comment by johnataylor** [comment]
These should be fixed now. C# samples should refer to appsettings and JavaSCript to env.

The  intro sentence also contains the link to the link unfurling docs.
