### ISSUE TITLE
[bug bash] Need more instructions on how to test the bot (sample utterances and expected replies)

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1946]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
Readme needs more instructions on how to test the bot with utterances/expected replies specific to the bot scenario.  The utterances should demonstrate functionality of the bot.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

All up samples review for R10 https://github.com/microsoft/botframework-sdk/issues/5897

[bug]

**Comment by garypretty** [comment]
@tsuwandy do you know which issue sample does this issue refer to?  Can you confirm if this is still an issue?

**Comment by tsuwandy** [comment]
I mostly looked at the core-bot.  
This is the readme for the TypeScript version:
https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.core-bot.tests/README.md

There isn't really any instruction there how to test the bot for the core bot scenario.  What utterances to use, etc.  

The dotnet core one has some examples:
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot.tests

Would be nice if they all have one section on how to test specific to the core bot scenario (travel related scenario).

**Comment by garypretty** [comment]
Review of this sample and update of readme taking place as part of https://github.com/microsoft/botframework-sdk/issues/5897
