### ISSUE TITLE
[bug bash] Create LUIS app id/QnA kb for samples and add them to the config so samples using LUIS/QnA could be run without much manual work

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1947]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch
This sample is almost impossible to run without first setting up LUIS/QnA, installing dispatch cli and then create a dispatch app.  Readme doesn't specify steps needed either.  

Can we create sample LUIS/QnA/Dispatch apps which will be referenced from samples for the purpose of reducing the fiction needed to run the samples?  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by gandiddi** [comment]
Closing the issue because the specified sample in the bug report has been archived.
