### ISSUE TITLE
[bug bash] typo in 55.teams-link-unfurling/README.md

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotBuilder-Samples#1948]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore 
3. Sample name: 55.teams-link-unfurling

## Describe the bug
Typo in the 'Interacting with the bot' section in the README.md file.

## Screenshots

![55](https://user-images.githubusercontent.com/48731427/68252221-c6372680-ffd9-11e9-9c51-ec27dc2e4992.png)

**Comment by johnataylor** [comment]
fixed
