### ISSUE TITLE
[Bug Bash] Node sample 53 says "Something went wrong"

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotBuilder-Samples#1950]
## Sample information
1. Sample type: Sample
2. Sample language: Node
3. Sample name: 53Teams-messaging-action-extensions-preview

## Describe the bug
After you fill out the adaptive card with *anything*:

![image](https://user-images.githubusercontent.com/40401643/68253234-41014100-ffdc-11e9-8438-d07233ffb706.png)

Once you hit Submit, you get:

![image](https://user-images.githubusercontent.com/40401643/68253247-4f4f5d00-ffdc-11e9-9392-42fd20b9408f.png)

Send then works, but the error is a little confusing.

## To Reproduce
1. Follow README
2. Fill out card and hit Submit

## Expected behavior
No errors.

## Additional context
This might be a Teams issue as no errors are printed in console and in debug mode with breakpoints set for both "All Exceptions" and "Uncaught Exceptions", it never stops/breaks.

[bug]

**Comment by EricDahlvang** [comment]
This occurs when the Messaging Extension/ bot is installed only in a personal scope. Once installed in a Team, preview will then work when initiated from a personal scope also.
