### ISSUE TITLE
17.multilingual-bot requires Subscription Region to be set

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotBuilder-Samples#1966]
## Version
Master

## Describe the bug
Making calls to the Azure Cognitive Service requires the region to be specified. Otherwise an unauthorized error is returned.

## To Reproduce
Run the sample bot and choose "Español"

## Expected behavior
Translation should happen with unauthorized error.

[bug]

**Comment by jwiley84** [comment]
I don't encounter this in the C# sample, but do in the JS sample.
