### ISSUE TITLE
Wrong order of bot responses

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotBuilder-Samples#1983]
I'm using Core bot template 
After confirming the flight booking bot responses with confirmation and prompt for a new input.
The order is reversed.
Please see the screenshot
This only happen once so I can't reproduce this.

![bot answers wrong order](https://user-images.githubusercontent.com/20775323/68964073-106c9480-079e-11ea-9597-4b94fe765311.PNG)

**Comment by turbozapekanka** [comment]
Not sure if this is a sample bug or framework issue.

**Comment by EricDahlvang** [comment]
Hi @turbozapekanka 

That is strange!  Which version of WebChat is the above example using?  This must be a race condition on the client.  Please upgrade WebChat to the latest, and let us know if that resolves the issue.

**Comment by turbozapekanka** [comment]
I simply copied and pasted the example iframe code from the web chat channel configuration:
I have no idea what version of WebChat this is running.

<iframe src='https://webchat.botframework.com/embed/PogoBot?s=YOUR_SECRET_HERE'  style='min-width: 400px; width: 100%; min-height: 500px;'></iframe>

**Comment by EricDahlvang** [comment]
That embed link is the V3 WebChat (the portal is a little behind).  More information on embed links can be found here: https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/README.md#how-to-use

Please try out the Gemini embed link, which is WebChat V4:

https://webchat.botframework.com/embed/b/gemini?s=YourWebchatSecret&b=YourBotHandle

**Comment by CoHealer** [comment]
@turbozapekanka have V4 embed link? Do you still have the reversing issue?

**Comment by turbozapekanka** [comment]
Yes, but I could not reproduce this issue neither with v3 nor with v4

**Comment by EricDahlvang** [comment]
@turbozapekanka We are going to close this as not reproducible.  Please open a new issue if you run into any other problems.
