### ISSUE TITLE
[Adaptive Dialog][Recognizers] Support Dialogflow as a Recognizers 

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/BotBuilder-Samples#1990]
Will Dialogflow be supported as a Recognizer for Adaptive Dialogs?

**Comment by cwhitten** [comment]
Hello @marcasmar94 and thank you for the issue. We're actively discussing and formalizing plans to additional recognizer implementations in Adaptive Dialogs. That said, we have no upcoming plans to land this effort in the product (supporting Dialogflow specifically). I'll leave this issue open for now, and thank you for the suggestion!

**Comment by cwhitten** [comment]
Hello @marcasmar94. We'll close this issue for now. See https://github.com/microsoft/botbuilder-dotnet/issues/3063 for updates

**Comment by tomlm** [comment]
This would be great thing to add to community repo
