### ISSUE TITLE
Is the card in bot contain the funtion both ImBack and messageBack like test bot in QnA?

### ISSUE THREAD

**Issue by feifeiJun** [microsoft/BotBuilder-Samples#1995]
I want to create bot like test bot in QnA portal.
In the test in QnA portal like the below screenshot, those buttons are created by the follow-up prompts from QnA, and when click those buttons, there are two things happen 
1. the bot UI show the text in the previous button.
2. One Http request are sent, this request contains all the button information like text and qnaid. 
that seems the integrate of the function both ImBack and messageBack, it show the context in next turn, and automatically send the request with the value of button. That is what exactly i want, in the  next response, it will be the answer of the specific qnaid. 
But in your sample, when click the button, the Http request just contain the text as questions, thus the QnA will not get the answer bind with the qnaid. The answer may will not accurate.
![image](https://user-images.githubusercontent.com/15061097/69138782-43928900-0afa-11ea-8f7e-0735ea084dab.png)

**Comment by stevkan** [comment]
Generally, this is how you can get the same returned results generated from the `getAnswers()` API call as you get from QnA.

First, pass the current context into `getAnswers()` (which contains the user's message: "help", "Where did trees come from", "Why is the sky blue?", etc.) and then map the result to a variable:

```js
const stepResults = turnContext.context;
let qnaResults = await this.qnaMaker.getAnswers(stepResults);
```

After validating a response is returned, you can pass the result text into an activity:

```js
await innerDc.prompt('ConfirmPrompt', qnaResults[0].context.prompts[0].displayText);
```

Logging the above `qnaResults[0].context.prompts` shows the returned prompt values align with request payload seen in devtools:

![image](https://user-images.githubusercontent.com/18403946/69185707-0fa06f00-0acc-11ea-8e41-6e4d99dfcdb8.png)

![image](https://user-images.githubusercontent.com/18403946/69185135-ff3bc480-0aca-11ea-8d14-ab69bd824637.png)

Does this answer your question?

Also, can you post a link to the sample you mention?

**Comment by feifeiJun** [comment]
Thanks, I think that's not the answer i wanted. and i have find the solutions in this [code section](https://github.com/microsoft/BotBuilder-Samples/blob/0c2eebdc9622ee368086757f60892960aef711e3/samples/csharp_dotnetcore/49.qnamaker-all-features/Dialog/QnAMakerBaseDialog.cs#L247).

**Comment by stevkan** [comment]
If you are willing to restate your question in another way so I can better understand, I'd be happy to continue trying to help. Please let me know if you're still looking for assistance.

**Comment by CoHealer** [comment]
@feifeiJun, I'm closing the issue as you last comment implies you've answered your own question:
"and i have find the solutions in this code section.". 

Please re-open if that was not your meaning.
