### ISSUE TITLE
Issue when Applying Multi Dialog Project

### ISSUE THREAD

**Issue by mohammadamer** [Microsoft/BotBuilder-Samples#200]
### URL of Code Sample
  if (message.Text.ToLower().Contains("help") || message.Text.ToLower().Contains("support") || message.Text.ToLower().Contains("problem"))
            {
                await context.Forward(new SupportDialog(), this.ResumeAfterSupportDialog, message, CancellationToken.None);
            }

### Problem Description
Error when build
Error The type arguments for method 'IDialogStack.Forward<R, T>(IDialog<R>, ResumeAfter<R>, T, CancellationToken)'
 cannot be inferred from the usage. Try specifying the type arguments explicitly. ..\..\..\..\Dialogs\RootDialog.cs	29	Active

**Comment by sphanley** [comment]
Did you modify anything in the sample? I pulled down and built the solution in question and I can't reproduce this error.

**Comment by mohammadamer** [comment]
Just creating a new project with the same functionality and the error appeared on the line of 
await context.Forward(.....

**Comment by EricDahlvang** [comment]
Cannot reproduce this issue.
