### ISSUE TITLE
QnA maker sample is not available to select while creating a webapp bot in Azure portal

### ISSUE THREAD

**Issue by chinna98** [microsoft/BotBuilder-Samples#2003]
I'm not able to see or select option for QnA maker template in either # and Js , Please tell me how to create that template

**Comment by v-kydela** [comment]
Go ahead and publish from the publish tab in your KB. After publishing, you'll see the option to create a QnA bot:

![image](https://user-images.githubusercontent.com/41968495/69455299-00643000-0d1d-11ea-94dd-c1e062229b42.png)
