### ISSUE TITLE
getaddrinfo ENOTFOUND https error

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotBuilder-Samples#2010]
Hi,

I am getting below error please let me know how to fix this issue.
 [onTurnError] unhandled error: Error: getaddrinfo ENOTFOUND https
Thank,
Madan

 
[getaddrinfo ENOTFOUND https.docx](https://github.com/microsoft/BotBuilder-Samples/files/3901445/getaddrinfo.ENOTFOUND.https.docx)

**Comment by stevkan** [comment]
Hi @madbeher, I tried replicating your issue with some typical encountered incorrect settings or configurations, however I was unable to do so.

A few questions for you:

- Did you make any modifications to the code after installing and before running? If so, can you post what those changes were? (For instance, changing the port from `3978` to `3979`.)
- Are you running this purely locally? Or, are you using ngrok or included an AppId or AppPassword?
- Which version of Emulator are you using?
- Can you detail any settings used (AppId / AppPassword, messaging endpoint, ngrok, etc.)?

**Comment by tracyboehrer** [comment]
@madbeher Are you still experiencing a problem with this?

**Comment by stevkan** [comment]
Closing due to a lack of activity. If the problem persists, please feel free to reopen the issue.
