### ISSUE TITLE
Update and align App Insights CoreBot samples across all languages 

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#2012]
There were some pretty extensive changes in the 4.5.1 Corebot updates release that were captured in the JS version of the CoreBot-App-Insights sample app that are not included in the C# version because none of those 4.5.1 Corebot updates were applied to the C# version of the CoreBot-App-Insights sample app.  Also, the C# version is not done correctly with regards to how telemetry is implemented in dialogs, and this has been corrected in the JS sample app.

These differences make documenting both (C#|JS) versions (and Python soon) in the same article very awkward and difficult if not impossible.  What will it take to get the C# sample updated/fixed?

**Comment by garypretty** [comment]
C# sample updated in PR #2031 - Merged.
JS sample added in PR #1773 - Merged.

Updated to JS sample to use latest bits and bring parity with C# in PR #2147 - Awaiting review.

**Comment by garypretty** [comment]
JS sample merged
