### ISSUE TITLE
Wrong link in LG format document

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotBuilder-Samples#2013]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/lg-file-format.md#escape-character

'Chatdown' is linked to LU doc instead of Chatdown doc.

**Comment by vishwacsena** [comment]
Fixed via https://github.com/microsoft/BotBuilder-Samples/pull/2023
