### ISSUE TITLE
Multi-turn prompt asks if collected info is okay before summarizing the collected info

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#2018]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore, nodejs]
3. Sample name: **5.multi-turn-prompt**

## Describe the bug
1. The dialog asks the user whether the collected information is ok in the next to last step. Then summarizes the collected information in the last step. The order of these two steps should be reversed.
1. A final acknowledgement step should be added, that tells the user that their information has been saved or discarded.

## To Reproduce
1. Run the sample.
1. Error: complete the dialog and think about this from a usability perspective.

## Expected behavior
Give a clear and concise description of what you expected to happen:
- Summarize the information you wish the user to confirm before asking them to confirm it.

## Additional context
The Python sample would also be affected. However, it is currently out of sync with the C# and JavaScript samples.

[bug]

**Comment by JonathanFingold** [comment]
@tracyboehrer @mmiele - Do either of you want to weigh in on this issue?

**Comment by tracyboehrer** [comment]
@JonathanFingold I would say it seems out of order in at least C# and Python.  I didn't check JS, but I assume it is too.  As far as demonstrating saving state in a multi-turn dialog it is successful.  As a completely meaningful dialog flow... probably not.
