### ISSUE TITLE
SDK V4 - Azure Deployment - 401 Unauthorized

### ISSUE THREAD

**Issue by Magic73** [microsoft/BotBuilder-Samples#2021]
I have a problem with deploying the bot with the sdk v4.
Still on Azure I have several Bots made with SDKv3 (NetFramework) and I've never had any problems.

Now I downloaded the V4 examples, and wanted to try them on Azure. I created a new Bot, registered it with a new key pair (appid-secretkey) and entered these values ​​into appsettings.json.

I deployed, and now I'm trying the bot both via emulator and web chat.

In both cases I can't get it to work. I always get error 401.

I also analyzed network traffic, and the credentials are correct. the token request to login.microsoftonline.com is successful and I receive the jwt token correctly.

The next call to the webapp (NetCore) that hosts the bot fails (the jwt token is passed correctly in the header).

The only differences between the bots that work and what doesn't work are:

- V3: NetFramework webapp
- V4: NetCore webapp

I double-checked all the settings, and found no other differences.
I also tried deploying the V4 version, in the same webapp where I have the V3, obviously using appid and secret of the V3 bot.
Obviously always receiving the usual 401.

Can you give me some tips? what could I be wrong about

Thanks!

**Comment by anusharavindrar** [comment]
@Magic73 for more clarity, you need to enter the Microsoft App ID and password in the **appsettings.json** file of the C# bot. Also, when you test it on the emulator, you will need to enter the app credentials along with the Bot URL, else you will get the 'Unauthorized' error. How are you trying to test your bot in Web Chat? Can you share your deployment steps?

**Comment by Magic73** [comment]
Yes, I put the credentials into appsettings.json. I also put them in the emulator (I already created/tested/deployed a lot of Bot on Azure).


This are the steps that I followed:

- downloaded V4 samples
- opened Netcore sample version
- logon into Azure portal
- created Azure Bot Channel Registration
- taked AppId + Secret key from Microsoft AAD Registered App (from Azure Portal)
- updated appsettings.json with AppId + SecretId
- deployed Cards samples into an azure webapp (the defualt bot home page displayed correctly)
- configured bot channel registration settings, with the messaging endpoint (webapp url + /api/messages)
- run Test in WebChat -> 401 Unhautorized
- opened emulator, configured endpoint + appid + secret.
- opened fiddler/wireshark
- started a new conversation
- 401 Unhautorized
- from fiddler/wireshark the jwt token is correctly taken from login.microsftonline.com/botframework.com/token (if I remember well)
- then when /api/messages is called with the bearer token into the header, => 401

With the exaclty the same scenario, but uploading a V3 bot into the same azure webapp.. all it works without any issue.


I'm missing something, but I can't figure what it is… 
:(

**Comment by anusharavindrar** [comment]
@Magic73 can you elaborate more on the "deployed Cards samples into an azure webapp (the defualt bot home page displayed correctly)" step. Also, can you make use of [ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) to debug your bot locally? If you have already double checked your app ID/password and message endpoint, then I would suggest you to see if all your packages are up to date. Refer to the troubleshooting [guide](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#issue-an-http-request-to-the-microsoft-login-service) to verify if you missed any of the steps.

**Comment by Magic73** [comment]
Sure!
I opened the NetCore samples with Visual Studio, then I published the CardsBot project into an Azure webapp. Navigating to the root of the website, the default home page of the botframework is correctly displayed ( .. Your bot is ready! ... )

Using local emulator works (using appid+secret also).

**Comment by Magic73** [comment]
mmm I deleted the webapp from Azure, then I created a new webapp, and I redeployed. Now it works.

But I don't know why. O_o

@anusharavindrar Thank you for your help! :)
