### ISSUE TITLE
QnAMaker sample fails on Azure

### ISSUE THREAD

**Issue by csteelatgburg** [microsoft/BotBuilder-Samples#2024]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: QnAMaker

## Describe the bug
The QnAMaker bot runs locally and when testing with the Emulator the only issue is a trace
Unable to find a QnA Maker service with Knowledge Base ID <my KB ID displayed here>. Please add a QnA Maker service to your bot.

Once uploading to Azure and testing the bot in either Teams or Web chat it throws an exception:
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

## To Reproduce
Make a copy of the QnAMaker sample
Open the copy of the QnAMaker sample in Visual Studio
Enter the appropriate values in appsettings.json
Run the bot
Verify it works in emulator
Upload bot to Azure
Test bot
Get exception

## Expected behavior
I should get a response from the QnAMaker KB

## Additional context
I am using an app service which was configured previously and getting the code to Azure using continuous deployment via GitHub.

[bug]

**Comment by jwiley84** [comment]
Let me see if I can figure out what's going on.

**Comment by jwiley84** [comment]
I am unable to repro this, so I gotta ask the standard questions: 1) How did you initially deploy this? 2) what version of the SDK are you using?

**Comment by csteelatgburg** [comment]
This was most likely related to an issue with the app service or the underlying QnA KB. Another team member had made some changes on the KB that appear to have broken it. Once I created a new KB and changed the bot to use that KB it worked. Sorry I didn't update here.

**Comment by jwiley84** [comment]
LOL, no worries! I'm glad it was an innocent "problem". :D
