### ISSUE TITLE
Skype call sample not detecting dtmf tones

### ISSUE THREAD

**Issue by satyansh-sagar** [microsoft/BotBuilder-Samples#203]
### Problem Description
I cloned the Skype calling sample from here and made all the changes mentioned , and published the Bot.
After publishing whenever i call the bot , it is only repeating the welcome message in repeat mode.
The code is same as in sample , only i have added some keys.
Can anyone help me out here.
@msft-shahins  @msftgits 

`  // Response messages depending on user selection
        private const string WelcomeMessage = "Hello, you have successfully contacted Test Calling Bot";
        private const string MainMenuPromptMessage = "Please press 1 to continue";
        private const string NoConsultantsMessage = "Whilst we wait to connect you, please leave your name and a description of your problem. You can press the hash key when finished. We will call you as soon as possible.";
        private const string EndingMessage = "Thank you for leaving the message, goodbye";
        private const string OptionMenuNotSupportedMessage = "The option you entered is not supported. Please try again.";

        private readonly Dictionary<string, CallState> callStateMap = new Dictionary<string, CallState>();
`

**Comment by HardikShah289** [comment]
Even Skype Android App, doesn't have any dialpad to submit 1. it is just repeating first welcome message.

**Comment by sgellock** [comment]
@CoHealer not sure if we're planning to make any progress on this.  it's very old

**Comment by CoHealer** [comment]
Resolving as won't fix
