### ISSUE TITLE
Not getting response from bot

### ISSUE THREAD

**Issue by KoushikGoramane** [microsoft/BotBuilder-Samples#2050]
I created the HomeAutomation LUIS and Qnamaker , I wants to run the bot in the local and added the data to the .env file. But whenever I type message in the Bot Emulator I am getting the following error.

//Error

Dispatch unrecognized intent: HomeAutomation.

How to solve this issue?

**Comment by a-b-r-o-w-n** [comment]
@KoushikGoramane Can you provide some more information about your bot? For instance, have you trained you LUIS model prior to running the bot? Does your .env file include the correct keys for LUIS and Qnamaker?

If you can, share your .env file with us (without the secrets) so we can better help investigate. Thanks!

**Comment by dmvtech** [comment]
Hi @KoushikGoramane just checking in. Do you still need assistance on this one?

**Comment by dmvtech** [comment]
Closing this as idle. Please reopen if further assistance needed.
