### ISSUE TITLE
Add mention group / mention channel examples into #57 

### ISSUE THREAD

**Issue by mindncz** [microsoft/BotBuilder-Samples#2077]
Example #57 provides code to mention a specific user in an activity which works quite well.

While in Teams, mentioning a group or a channel is also supported in Teams app. I've tried several ways to achieve the same purpose via Bot SDK, unfortunately, they don't work. 

Could #57 also contain the examples to mention a group or a channel via Bot SDK?

**Comment by srinaath** [comment]
@Virtual-Josh  Just assigned this ticket to you. Can you take a look at it when you get a chance

**Comment by Virtual-Josh** [comment]
Sure, I'll take a look.

**Comment by Virtual-Josh** [comment]
Hi @mindncz 

Mentioning channels/group chats is done the exact same way as the sample, the only difference is what channel account/name are you piping in. You can use the code below to modify the mentions sample to reply to and mention the channel/group chat. You will need to @TheBot and @TheChannel (in that order) in the inbound message for it to work properly.

EX: (in a team) @MentionsBot @General

```
var channelMention = JObject.FromObject(turnContext.Activity.Entities[1]).ToObject<Mention>();
var mention = new Mention
     {
      Mentioned = channelMention.Mentioned,
      Text = channelMention.Text,
      };
```

If you wanted to mention a different channel you can get all the info you need from the TeamsInfo's GetChannel helper method in whatever SDK you're using.

**Comment by Virtual-Josh** [comment]
As for adding this to the sample I'm not strictly opposed to doing that, but I'm also not sure if that would cause the sample to become overly complicated. I'll bat this idea around with a couple of people and see what the consensus is.

**Comment by mindncz** [comment]
@Virtual-Josh 
1)  I used the same code as you suggested when using"@mentionsbot @general" in the inbound message.
However, turnContext.Activity.Entities only contains @mentionsbot info. The @general is not included. So turnContext.Activity.Entities[1] throws exception.

2) I tried using the below code to generate mention info of @General.
`  
            var mention = new Mention { 
             Mentioned = new ChannelAccount { Id = "19:14d9ec04***********587a6@thread.skype", Name = "General" }, 
             Text = $"<at>{XmlConvert.EncodeName("General")}</at>"
            };

            var replyActivity = MessageFactory.Text($"Hello {mention.Text}. I'm created by TurnContext");
            replyActivity.Entities = new List<Entity> { mention };

            await turnContext.SendActivityAsync(replyActivity, cancellationToken);

`

Mention doesn't take effect as the following picture:
![Mention](https://user-images.githubusercontent.com/46016028/71864259-47ed2280-30f7-11ea-936a-e518bf925bb6.png)

**Comment by Virtual-Josh** [comment]
@mindncz 

Two things. 

First, here's a screenshot of the code that works for me and the message I sent to make it work.

```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var channelMention = JObject.FromObject(turnContext.Activity.Entities[1]).ToObject<Mention>();
            var mention = new Mention
            {
                Mentioned = channelMention.Mentioned,
                Text = channelMention.Text,
            };

            // Against Teams having a Mention in the Entities but not including that
            // mention Text in the Activity Text will result in a BadRequest.
            var replyActivity = MessageFactory.Text($"Hello {mention.Text}.");
            replyActivity.Entities = new List<Entity> { mention };
            var a = JsonConvert.SerializeObject(replyActivity);
            await turnContext.SendActivityAsync(replyActivity, cancellationToken);
        }
```
![image](https://user-images.githubusercontent.com/50158775/71998974-6afdfc00-31f5-11ea-82b8-ea0201357478.png)

Try this and let me know if it doesn't work for you.

Second, I just found out that only whitelisted bots should able to @SomeChannel so while this will this will work for you now there probably will be 1 more step you'll need to take down the road to whitelist the bot so it can do that once that fix is prioritized and added.

**Comment by mindncz** [comment]
@Virtual-Josh
1) 
I used the same code again. 
![MentionCode](https://user-images.githubusercontent.com/46016028/72034788-e7dcb480-328d-11ea-96df-8d6778f0fbae.png)

However, turnContext.Activity.Entities still only contains @mentionsbot info. The @General is still not included. So turnContext.Activity.Entities[1] throws exception.

![MentionChannel](https://user-images.githubusercontent.com/46016028/72034622-77ce2e80-328d-11ea-8048-7596f8e7a109.png)

Which version of the SDK are you using and is there any special settings of the bot that I need to set?

2) How to white list a bot?

**Comment by Virtual-Josh** [comment]
I'm using the current version of the SDK. If you're only seeing 1 element in the entity object that would suggest to me that somewhere in your code you're calling `RemoveRecipientMention`. If you're using sample #57 that's the first thing that happens in the `onMessageActivity`. The easiest way to see this work is by putting this code

```
 var channelMention = JObject.FromObject(turnContext.Activity.Entities[1]).ToObject<Mention>();
            var mention = new Mention
            {
                Mentioned = channelMention.Mentioned,
                Text = channelMention.Text,
            };

            // Against Teams having a Mention in the Entities but not including that
            // mention Text in the Activity Text will result in a BadRequest.
            var replyActivity = MessageFactory.Text($"Hello {mention.Text}.");
            replyActivity.Entities = new List<Entity> { mention };
            var a = JsonConvert.SerializeObject(replyActivity);
            await turnContext.SendActivityAsync(replyActivity, cancellationToken);
```
before the `RemoveRecipientMention` call and if you are using the sample. So it would look like this in the sample

```

 protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {  
            var channelMention = JObject.FromObject(turnContext.Activity.Entities[1]).ToObject<Mention>();
            var mention = new Mention
            {
                Mentioned = channelMention.Mentioned,
                Text = channelMention.Text,
            };

            var replyActivity = MessageFactory.Text($"Hello {mention.Text}.");
            replyActivity.Entities = new List<Entity> { mention };
            var a = JsonConvert.SerializeObject(replyActivity);
            await turnContext.SendActivityAsync(replyActivity, cancellationToken);


            turnContext.Activity.RemoveRecipientMention();

            switch (turnContext.Activity.Text.Trim())
```

Try that and let me know if that works for you.

To your question #2, I'm not sure yet. It's an open question I'm following up on.

**Comment by mindncz** [comment]
@Virtual-Josh 
Thanks for the reply.

I created a web app bot "TestMentionBot1" via Azure using the default EchoBot template. And then only changed EchoBot.cs using your code as the following:
![Code](https://user-images.githubusercontent.com/46016028/72135673-f8208c80-337e-11ea-9d2b-14bf5b1e34f6.png)

The behavior is as the following:
![Behaviour](https://user-images.githubusercontent.com/46016028/72136057-d4117b00-337f-11ea-8a93-f4857b70ca45.png)

The error is caused by the same reason as I mentioned in my previous comments.

**Comment by Virtual-Josh** [comment]
Hey @mindncz 

I think I might know what's going on. I received word yesterday that the whitelisting bots is actually currently in production. For some reason my bot is whitelisted despite that bot only being created earlier this week. There's someone digging into understanding that. 

At this point I suspect you bot might not be whitelisted. I'm asking for the right email/contact point so that you can talk to the right people about the whitelisting since this isn't an SDK issue. I'll update this ticket once I get that info.

**Comment by Virtual-Josh** [comment]
Hey @mindncz 

We (as the SDK team) don't have the ability to whitelist a bot. You need to contact the Teams support team:

microsoftteamsdev@microsoft.com

and ask them about the whitelisting. I'm told they can answer your question.

**Comment by mindncz** [comment]
@Virtual-Josh  
Thanks for the reply. I will contact them.

**Comment by mindncz** [comment]
@Virtual-Josh 
I've sent them an email this Monday however no reply has been received.

**Comment by Virtual-Josh** [comment]
@mindncz 
Last week there was a lot of snow here in Seattle. A lot of people were out due to the weather. I'd recommend sending a follow up.

**Comment by Virtual-Josh** [comment]
Closing this ticket since there's a bug with Teams to remove the ability to do this.
