### ISSUE TITLE
Discuss docs where Python Azure deployment restrictions should be placed

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotBuilder-Samples#2079]
Per the issue with not being able to mix Windows and Linux services in Azure (confirmed by design):

There is a callout in the "Deploy your bot" doc.  But there is a good argument that this could/should be placed in other areas.

**Comment by JonathanFingold** [comment]
See [Deploy your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-deploy-az-cli) in the Bot Framework docs.

**Comment by Kaiqb** [comment]
done
