### ISSUE TITLE
Bot Authentication : Azure AD

### ISSUE THREAD

**Issue by sumanboltz** [Microsoft/BotBuilder-Samples#208]
Hi All,

I have a question. Can we secure the Azure Bot Service (Web Channel) with Azure AD ? The "DirectLine" seems very insecure, anyone can say view source and capture the SecretKeyID and they can use it anywhere to explore the questions and answers. So to stop this, can we have the bot to respond/work for only the Authenticated Users ? 

Please suggest. Appreciate your help.

**Comment by JasonSowers** [comment]
Take a look at [AuthBot](https://github.com/MicrosoftDX/AuthBot) and [BotAuth](https://github.com/MicrosoftDX/botauth)  These will probably get you started down the right path.  If you have further questions feel free to ask them on the [BotBuilder repo](https://github.com/Microsoft/BotBuilder/issues/new)
