### ISSUE TITLE
Is there any hook where I can process the all bots messages at one place before sending to the user?

### ISSUE THREAD

**Issue by saleemnasa** [microsoft/BotBuilder-Samples#2084]
Is there any hook where I can process the all bots messages at one place before sending to the user?

I want to know about it in Node js.

Thank You

**Comment by mdrichardson** [comment]
@saleemnasa I believe you're looking for [middleware](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-middleware?view=azure-bot-service-4.0).

The [multilingual sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/17.multilingual-bot) shows an example of it, particularly with how it uses [`onSendActivities()`](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/17.multilingual-bot/translation/translatorMiddleware.js#L39)

**Comment by saleemnasa** [comment]
Thank You @mdrichardson
