### ISSUE TITLE
image-caption bot --replying  Oops! Something went wrong. Try again later.

### ISSUE THREAD

**Issue by suresh444** [Microsoft/BotBuilder-Samples#209]
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.sendBatch() sending 0 message(s)
{ Error: connect ETIMEDOUT 40.112.254.71:443
    at Object.exports._errnoException (util.js:1014:11)
    at exports._exceptionWithHostPort (util.js:1037:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '40.112.254.71',
  port: 443 }
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)

I tried to create a image caption bot ...where in it is throwing error as above.

**Comment by EricDahlvang** [comment]
I just tried the [image-caption bot](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/intelligence-ImageCaption).  It is working as expected.  A valid MICROSOFT_VISION_API_KEY, MICROSOFT_VISION_API_ENDPOINT and internet connection are required.
