### ISSUE TITLE
Code Feature: When there is a hard error crash let the user gracefully enter back to the beginning of the main dialog loop

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotBuilder-Samples#2091]
**Is your feature request related to a problem? Please describe.**
when the user enters a bug and there is a hard error a message comes to the user that the bot is broken.  The problem with this is that if the user types anything else beyond that they will not receive any response -- albeit until they type something again or reenter into the bot as a member 
**Describe the solution you'd like**
`await bot.run(context);`
The above code snippet allows the error to occur with a message to user that something is wrong with the dialog path they went down.  However, at this point the user is placed back to the beginning of the dialog flow and they simply can start over.  Perhaps a more complex scenario would leave them in certain dialogs depending on the error. 

This is a much more graceful way to handle the error and leaves the client in the position to ask type something again and immediately get a response because they have started the dialog over again.  

The above code snippet is placed directly at the end of the on turn error in the index.js file.

I can do a pull request if thoughts and feedback agree with the sentiment.

**Describe alternatives you've considered**
Leaving it as is.

**Additional context**

[enhancement]

**Comment by christopheranderson** [comment]
Hey @xtianus79,

Thanks for opening up an issue.

First, a clarifying question: Is this a specific comment with our samples (this is our samples repo) or more of a feature request for the SDK? It seems like what you're asking for is the pattern.

Second, assuming this is more of a pattern thing, you do have a lot of control over error handling. You can wrap every `await` call and handle the errors in as graceful a fashion as you'd like. The further down the stack you catch an error, the harder it will be to keep the context, etc, but it is fully in your control. We don't show it a lot in samples, but it is fully possible.

For example, here: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/05.multi-turn-prompt/dialogs/userProfileDialog.js#L88

If that sendActivity call were to fail, you can catch it and retry it without losing any dialog state at all.

Does that clarify anything for you?

**Comment by xtianus79** [comment]
@christopheranderson yes I believe this is more of a pattern thing.  Yes, I see what you're that in a dialog that is further down the flow you may now want to bring them back to the beginning of the main dialog... That's a good point and validation and your explanation above is well noted to handle errors down into dialog task flows.  

For many use cases that don't have a dialog flow and more of a request response nature if the error occurs then what I am describing above happens and is not a good ui experience.  Meaning, the end of those dialogs brings them back to the beginning anyway so error handling in that sense would probably not be appropriate.  

I think a mixture of both would cover all cases quit well.  thanks for the feedback that answers the question.
