### ISSUE TITLE
Python Samples in Flask

### ISSUE THREAD

**Issue by vijaysaimutyala** [microsoft/BotBuilder-Samples#2099]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
All the samples were built using aiohttp. But Flask is a major web framework that Python Developers use and very easy to work with. Any particular design choice in choosing aiohttp over Flask ?

Would like to see few samples that utilize Flask.

**Comment by srinaath** [comment]
@tracyboehrer Can you take a look a this ticket.

**Comment by tracyboehrer** [comment]
@vijaysaimutyala We are standardizing on aiohttp for our samples and recommended this web framework for building a production bot.  We started with Flask, but during our load tests we encountered an unacceptable number of failures that are linked to various async/await scenarios.  

With that said, we also found Quart and Tornado acceptable, though aoihttp handled the highest requests per second.

At this particular moment, the sample "21.corebot-app-insights" is still using Flask.  Though at some point it will switch over too.

The differences are minor, and are mainly in app.py.  Also note that the ARM templates (used to deploy to Azure) in each sample match the web framework being used.  So if you use Flask, use the ARM templates from the sample mentioned above.

**Comment by vijaysaimutyala** [comment]
Thanks for the info @tracyboehrer. We built our bot on top of Flask and since we've a low traffic, I didn't experiment enough with the load tests. Good to hear that aiohttp handles that part well. We'll try to see how easy/difficult it would be to making the switch or if we could just keep using Flask.

**Comment by vijaysaimutyala** [comment]
Just wanted to ask how different is the ARM deployment via Azure CLI compared to local git deployment ? Will there be drastic difference between the two ? Will ARM template be deployed same as local git deployment ?

**Comment by tracyboehrer** [comment]
@vijaysaimutyala The ARM templates are doing a lot of the grunt work to setup the App Registration, Bot Channel Registration, and the App Service (and associated Service Plan).  The only difference between the different web frameworks used is the startup command.  Azure auto-detects a Flask app and will start it accordingly.  For other web frameworks, the startup must be specified (see appCommandLine in either of the templates from a aiohttp based sample).

I haven't personally tried a local git deploy.  My _guess_ is that how the code gets there isn't much of a differentiator.  Our deploy instructions use a zip of the source (for Python) in the "Deploy code to Azure" step.  But deploying via local git (https://docs.microsoft.com/en-us/azure/app-service/deploy-local-git) using Kudu is a variation of that.

If you discover that isn't the case, let us know and we'll dig into it.

**Comment by vijaysaimutyala** [comment]
Sure @tracyboehrer . Thanks :)
