### ISSUE TITLE
Unable to update skype settings for bot in Bot Framework Portal.

### ISSUE THREAD

**Issue by Chitma** [Microsoft/BotBuilder-Samples#210]
Hello All, 

I am building a Skype calling bot when i tried updating webhook , "unable to save" message shows up.

![image](https://user-images.githubusercontent.com/22928054/32090507-5fed2860-bb0d-11e7-807d-f5b8c8a54abb.png)

What could be the possible cause for this?

**Comment by mgbennet** [comment]
There is currently a bug in the Skype configuration validation that requires a category to be selected, even if the channel isn't being submitted. Go to the Publish tab, and select a category. Then you should be able to save as normal.

**Comment by Chitma** [comment]
Thanks a lot @mgbennet . It worked.
