### ISSUE TITLE
Update skill consumer's on error handler to cancel any active skill

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#2101]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore] [nodejs] [python]
3. Sample name: 80.skills-simple-bot-to-bot

## Describe the bug
As a best practice, the skill consumer, before clearing conversation state, should probably send an `endOfConversation` activity to any active skills. However, this sample does not do so.

## To Reproduce
1. Look at the _on turn error_ implementation in the [C#](https://github.com/microsoft/BotBuilder-Samples/blob/25c895b742cb4a4264a8f10bf0243af1b5b59ac4/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/SimpleRootBot/AdapterWithErrorHandler.cs#L19-L46) and [JavaScript](https://github.com/microsoft/BotBuilder-Samples/blob/25c895b742cb4a4264a8f10bf0243af1b5b59ac4/samples/javascript_nodejs/80.skills-simple-bot-to-bot/simple-root-bot/index.js#L34-L46) root bot adapters.
   - The Python version is in PR, but follows the same pattern.
2. Error: these clear conversation state, but do not send an `endOfConversation` activity to the skill first.
   - With a more complex skill, this could leave resources assigned that could otherwise be released.

## Expected behavior
The skill consumer, before clearing conversation state, should send an `endOfConversation` activity to any active skills.

[bug]

**Comment by JonathanFingold** [comment]
@gabog @EricDahlvang - Please let me know if you disagree.

**Comment by EricDahlvang** [comment]
I'm not sure that would be the best pattern, since the conversation has not actually ended.  If we send endOfConversation, the next message sent to the parent bot will not automatically be forwarded to the skill bot.  If we end the conversation, the skill invocation will need to be sent again to trigger the skill.  By clearing the conversation state, but not ending the skill, the next message sent will still be forwarded to the skill.

Whether or not to send endOfConversation when an unhandled exception occurs in a skill is probably very parent/skill specific.

**Comment by JonathanFingold** [comment]
Since our basic pattern is to clear conversation state, the consumer forgets that it was having a conversation with the skill, and forgets any associated information that went along with that. The user would have to trigger the consumer to start a new conversation, and then the skill would either start at the beginning, if the consumer generated a new conversation ID, or start in the middle, if the consumer generated the old ID.

If one wanted a more robust skill. It might accept some sort of _conversation error_ event, and the skill could decide whether to clear its state or not.

**Comment by gabog** [comment]
Let's address this one as part of R8, if we want the adapter to send the EndOfConversation message to the skill in the AdapterWithErrorHandler code, we will need to send pass the SkillHttpClient to the AdapterWithErrorHandler and also make sure the AdapterWithErrorHandler knows the conversationState property accessor used by the bot to track the active skill. 
Another approach would be to add a try/catch bloc to the OnMessageActivityAsync method in the RootBot and clear send the message from there.

**Comment by tracyboehrer** [comment]
Dotnet: #2109 
JS: #2115

**Comment by tracyboehrer** [comment]
Closing as all related PR's have been merged.
