### ISSUE TITLE
Unable to reach app. Please try again.

### ISSUE THREAD

**Issue by honorew** [microsoft/BotBuilder-Samples#2104]
Create app at App Studio and create Messaging Extensions, add bot for it then  create a query command.

![image](https://user-images.githubusercontent.com/43129995/71946200-157d1b80-3204-11ea-91d9-cc81d35d6e98.png)
below is my manifest.json file.
![image](https://user-images.githubusercontent.com/43129995/71946181-05fdd280-3204-11ea-9760-0eaf1e7a0de5.png)

**Comment by jwiley84** [comment]
When you created the app, did you create a new bot through app studio, or did you add an existing bot?

**Comment by honorew** [comment]
@jwiley84 yes,I add an existing bot,but it's no work,then i create a new one,it's ok,i don't know why.
thanks

**Comment by jwiley84** [comment]
I know you closed this, but just in case: I would check on the existing bot you chose in the first step: it seems that it might be down, or unreachable. Either way, I'm glad this is working for you now!!
