### ISSUE TITLE
Make app.get('/',) as nested function in app.js

### ISSUE THREAD

**Issue by daveRendon** [Microsoft/BotBuilder-Samples#211]
### SDK Platform

Node SDK
"botbuilder": "^3.11.0",
    "botbuilder-cognitiveservices": "^1.1.0",
    "botbuilder-location": "^1.1.0"

### Problem Description

added LUIS capabilities and it is working all OK, however how can you make a call from app.js to a dialog which is on bot/dialogs/myDialog.js? The objective is that if the user types an specific question they can be redirected to a second Dialog. The sample makes a call at app.js:

// Register your web app routes here
app.get('/', function (req, res, next) {
res.render('index', { title: 'Contoso Flowers' });
});

But I need to nest this function on a bot.dialog()... 

Appreciate any comment/guidance on this case.

**Comment by sgellock** [comment]
closed due to inactivity
