### ISSUE TITLE
Can a .html file be rendered in cards

### ISSUE THREAD

**Issue by Yashu1904** [Microsoft/BotBuilder-Samples#212]
Can a .html file be rendered in cards

**Comment by FranciscoPonceGomez** [comment]
No. Cards use their own schema and don't accept HTML. None of the channels in the Bot Framework actually supports HTML rendering either:

Channel | Markdown Support | HTML in Markdown Support
-- | -- | --
Bing | Yes | No
Cortana | Yes | No
Facebook | No | -
GroupMe | No | -
Kik | No | -
Slack | Partial | No
Telegram | Yes | No
Twillio (Web) | No | -
WeChat | No | -
Email | Yes | Yes
Microsoft Teams | Partial | Partial
Skype | Partial | Partial
Skype for Business | Partial | Partial
WebChat | Yes | No

Source:
https://github.com/Microsoft/BotFramework-WebChat/issues/604

Regards,
Francisco
