### ISSUE TITLE
Samples csharp_dotnetcore 19.custom-dialogs does not work using BF emulator

### ISSUE THREAD

**Issue by maximicciullo** [microsoft/BotBuilder-Samples#2143]
## Sample information
1. Sample type: sample
2. Sample language: dotnetcore
3. Sample name: 19.custom-dialogs 

## Describe the bug
After I ran the app doing 'dotnet run', when I try to use the emulator I got the following error in console log.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: /Users/maximiliano.micciullo/Projects/MeBeBot/Tests/botbuilder-samples/samples/csharp_dotnetcore/19.custom-dialogs/composerDialogs/Main.dialog error: Type specified in JSON 'Microsoft.AdaptiveDialog' was not resolved. Path '$type', line 2, position 37.

```
## To Reproduce
1. Go to '../botbuilder-samples/samples/csharp_dotnetcore/19.custom-dialogs'
2. Run the app doing 'dotnet run'
3. Launch Bot Framework Emulator
4. File -> Open Bot
5. Enter a Bot URL of http://localhost:3978/api/messages
6. See error in Terminal of VSC.

## Expected behavior
I expected to use the bot emulator, just get a response without any error.

[bug]

**Comment by jwiley84** [comment]
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/19.custom-dialogs doesn't have a /composerDialogs directory.  This is not a base sample. I can see that you're discussing the issue with @vishwacsena and @stevkan [here](https://github.com/microsoft/botbuilder-dotnet/issues/3105) so i'm going to close this as a duplicate, so all the work for this issue can be tracked in one place.

**Comment by maximicciullo** [comment]
@jwiley84, I'm just trying to follow the instruction that you've defined in your readme file and is not working ... Nothing related to the other issue!!!
