### ISSUE TITLE
Skills sample does not work with teams channel

### ISSUE THREAD

**Issue by 01** [microsoft/BotBuilder-Samples#2156]
## Sample information
1. Sample type: samples/javascript_nodejs/80.skills-simple-bot-to-bot
2. Sample language: nodejs 
3. Sample name: 80.skills-simple-bot-to-bot

## Describe the bug
Bot to Bot conversations using the MS Teams channel fails with "/api/skills/vs/converations/msteams:{converationsId}/activities/{activityId} doesnt exist

## To Reproduce
Simply run the sample using MS Teams channel instead of bot emulator

**Comment by 01** [comment]
This issue i with the conversation ids for teams channel not being url decoded after the post request.

**Comment by anusharavindrar** [comment]
@01 thank you for reporting this. I will try to repro this on the Teams channel and update the thread with my findings. In the meanwhile, can you attach a screenshot of the error you are getting?

**Comment by 01** [comment]
@anusharavindrar I dont have a screenshot of the error as I have resolved the issue. The issue should be apparent simply running sample using a Teams channel. The issue was due to the way conversation ids are formatted on teams cause the parent bot look up of the conversation id.

**Comment by anusharavindrar** [comment]
@01 Thank you for reporting this and glad that you could resolve your issue. I will have someone look into this . If you have any further issues, please feel free to open a new issue.
