### ISSUE TITLE
invalid character 'ï' looking for beginning of value in the response

### ISSUE THREAD

**Issue by mrmuralidharan** [microsoft/BotBuilder-Samples#2157]
### **Sample information**
1. Sample type: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/51.teams-messaging-extensions-action
2. Sample language: dotnetcore
3. Sample name: 51.teams-messaging-extensions-action

## **Describe the bug**
On button action in Message Extension, shows "Unable to reach app. Please try again.". On debug there is no exception. But in ngrok inspect, POST message response summary showing the "invalid character 'ï' looking for beginning of value" error message

## To Reproduce
Simply run the sample using MS Teams channel instead of bot emulator

**Comment by mrmuralidharan** [comment]
We have used the lazy loading and followed the same steps available in the README file.

**Comment by dmvtech** [comment]
Hi @mrmuralidharan Can you show me the example of the POST message (sanitized for security and anonymity)?

Also; can you give more steps on how you are able to reproduce this? I would love to see your code/markup/manifest if possible (again, sanitized). A reproduction in a GitHub repository would be ideal.

**Comment by dmvtech** [comment]
Just to be clear; I wasn't able to repro doing:

> Simply run the sample using MS Teams channel instead of bot emulator

**Comment by dmvtech** [comment]
Is it related to the data you put in the create card fields?

**Comment by mrmuralidharan** [comment]
> Hi @mrmuralidharan Can you show me the example of the POST message (sanitized for security and anonymity)?
> Also; can you give more steps on how you are able to reproduce this? I would love to see your code/markup/manifest if possible (again, sanitized). A reproduction in a GitHub repository would be ideal.

![HeaderJSON](https://user-images.githubusercontent.com/60460928/73626880-89c6a580-4670-11ea-8ee6-4ef6078e16d7.png)

**Comment by mrmuralidharan** [comment]
> Hi @mrmuralidharan Can you show me the example of the POST message (sanitized for security and anonymity)?
> Also; can you give more steps on how you are able to reproduce this? I would love to see your code/markup/manifest if possible (again, sanitized). A reproduction in a GitHub repository would be ideal.

![HeaderJSON](https://user-images.githubusercontent.com/60460928/73627063-2f7a1480-4671-11ea-8da0-63b594beb0ef.png)
Please find the POST summary message

**Comment by dmvtech** [comment]
Can i take a look at your manifest?

**Comment by dmvtech** [comment]
Hi @mrmuralidharan can we see your sanitized manifest? 

@Virtual-Josh @clearab Any thoughts here? Ever seen anything like this?

**Comment by dmvtech** [comment]
Hi @mrmuralidharan Do you still need assistance with this issue?

**Comment by mrmuralidharan** [comment]
@dmvtech You can close this, the issue is related to environment.

**Comment by mrmuralidharan** [comment]
@dmvtech You can close this, the issue was related to environment.
