### ISSUE TITLE
Is there any hook where I can process the all user messages including prompt inputs of user at one place before bot processes it?

### ISSUE THREAD

**Issue by saleemnasa** [microsoft/BotBuilder-Samples#2168]
Is there any hook where I can process the all user messages including prompt inputs of user at one place before bot processes it?

I want to know about it in Node js.

Thank You

**Comment by stevkan** [comment]
There are three places that are available to you to capture all user messages.

1. In your "index.js" file, `server.post('/api/messages', ...)` => `adapter.processActivity()` is the entry point for all incoming messages to your bot. If you are wanting to capture every incoming activity to process them, this is the first location. You will need to filter the activity to boil down the messages you are looking to affect.

```js
adapter.processActivity(req, res, async (turnContext) => {
  const { activity } = turnContext;
  if (activity && activity.type === 'message' && activity.from.role === 'user') {
    [...do stuff...]
  }
  await bot.run(turnContext);
};
```

2. In your "mainBot.js" file, you can utilize the `onTurn()` activity handler. You will need to filter on activity properties `type` and `from`.

```js
this.onTurn(async (context, next) => {
  const { activity } = context;
  if (activity && activity.type === 'message' && activity.from.role === 'user') {
    [...do stuff...]
  }

  [...]
};
```

3. In your "mainBot.js" file, you can utilize the `onMessage()` activity handler. You will only need to filter on activity `from`  as this handler already only captures messages.

```js
this.onMessage(async (context, next) => {
  const { activity } = context;
  if (activity && activity.from.role === 'user') {
    [...do stuff...]
  }
 
 [...]
};
```

Hope of help!
