### ISSUE TITLE
Fix the sample 49.qnamaker-all-features

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotBuilder-Samples#2174]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: 49.qnamaker-all-features

## Describe the bug
While using the sample and testing it locally or on any channel, for any input utterance which shows up the Active Learning Card with 'None of the Above' as one of the options, if the user selects the 'None of the above' option, the bot should respond with 'Thanks for the feedback.'. However, it is responding back with nothing, although it shows up in the emulator logs.

## To Reproduce
1. Run the sample 49.qnamaker-all-features.
2. Test it on the Emulator with utterances that trigger the Active Learning card.
3. Select the 'None of the above' option.
4. The bot responds with nothing.

## Expected behavior
The bot should respond back with 'Thanks for the response.'

## Screenshots

- While testing the sample on the Emulator:

![GHqnaActiveL_LI](https://user-images.githubusercontent.com/48731427/73884857-94716e00-481b-11ea-9dab-e2e5720549a7.jpg)

- If we change the line
 `var cardNoMatchResponse = new Activity(DefaultCardNoMatchResponse);`

to

 `var cardNoMatchResponse = (Activity)MessageFactory.Text(DefaultCardNoMatchResponse);`

in the GetQnAResponseOptionsAsync method in QnAMakerBaseDialog.cs, then it works as expected and the bot responds back with 'Thanks for the response.'

![GHqnaActiveL!](https://user-images.githubusercontent.com/48731427/73885158-2d07ee00-481c-11ea-99f2-ef081be14f5d.png)

## Additional context
Reported by a user in https://github.com/microsoft/BotBuilder-Samples/issues/2172

[bug]

**Comment by trojenguri** [comment]
Created the PR https://github.com/microsoft/BotBuilder-Samples/pull/2177
