### ISSUE TITLE
Update 15.handling-attachments README for Teams

### ISSUE THREAD

**Issue by daveta** [microsoft/BotBuilder-Samples#2175]
The `README.md` for sample `15.handling-attachments` needs an update.

- Add pointer to sample `56.teams-file-upload` as *"The Teams samples are designed to work in Teams better than the other samples"* per [this related issue](https://github.com/microsoft/BotBuilder-Samples/issues/2170).
- Needs to be done across all languages.

**Comment by sahil-lakhwani** [comment]
@daveta The differences that I see between the 2 exmaples are:

1. Sample 15 uploads file to an endpoint on on the serviceURL server (`/v3/conversations/{conversationId}/attachments`) while sample 56 uploads the SharePoint account of the Teams user.
2. Sample 15 shows how to proactively upload a file unlike sample 56 where an uploadURL is required to upload the file.

I am looking to upload a file proactively as in case of sample 15.

**Comment by garypretty** [comment]
@clearab Assigning this to you for now as related to Teams issues. Once we have a clear scope for the issues we are addressing in R10 we can load balance if needed.

**Comment by garypretty** [comment]
All up SDK tracking issue for Teams docs https://github.com/microsoft/botframework-sdk/issues/5896
