### ISSUE TITLE
Getting Service Error while sending the welcome message to the user in msteams

### ISSUE THREAD

**Issue by krisalay** [microsoft/BotBuilder-Samples#2182]
## Sample information
1. Sample type: [\samples\ ]
2. Sample language: [nodejs]
3. Sample name: 18.bot-authentication

## Describe the bug
The sample works properly in bot-emulator. But, when using the same sample in msteams, it throws error. The sample code:

```
// Copyright (c) Talview. All rights reserved.
// Licensed under the MIT License.

const { CardFactory } = require('botbuilder');

const { DialogBot } = require('./dialogBot');
const WelcomeCard = require('../dialogs/cards/welcomeCard.json');

class TeamsBot extends DialogBot {
    /**
     *
     * @param {ConversationState} conversationState
     * @param {UserState} userState
     * @param {Dialog} dialog
     */
    constructor(conversationState, userState, dialog) {
        super(conversationState, userState, dialog);

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; cnt++) {
                try {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        const welcomeCard = await CardFactory.adaptiveCard(WelcomeCard);
                        await context.sendActivity({ attachments: [welcomeCard] });
                    }
                } catch (e) {
                    console.log(e);
                }
            }

            await next();
        });
    }

    async handleTeamsSigninVerifyState(context, state) {
        await this.dialog.run(context, this.dialogState);
    }
}

module.exports.TeamsBot = TeamsBot;
```

if `membersAdded[cnt].id !== context.activity.recipient.id` then it makes a `POST` request to `https://smba.trafficmanager.net/apac/v3/conversations/.........` and in response it returns `'{"error":{"code":"ServiceError","message":"Unknown"}}'` 

## To Reproduce
1. Install the app into teams using app studio.
2. After installation, we see the error.

## Expected behavior
It should print the welcome message in the msteams bot.

[bug]

**Comment by jwiley84** [comment]
Let me try to repro.

**Comment by krisalay** [comment]
@jwiley84 I tried it by removing the `await` but still the issue persists.

**Comment by krisalay** [comment]
@jwiley84 Any update on this issue?

**Comment by CoHealer** [comment]
@jwiley84, please report back with any progress.

**Comment by anusharavindrar** [comment]
@krisalay Teams behaves somewhat differently than other channels in regards to OAuth and requires a few changes to properly implement authentication. Specifically an Invoke Activity is sent to the bot rather than the Event Activity used by other channels. This Invoke Activity must be forwarded to the dialog if the OAuthPrompt is being used. This is done by subclassing the TeamsActivityHandler and implementing handleTeamsSigninVerifyState. It is best advised to make use of the [46.teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth) sample to set up OAuth in Teams.

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if you still have issues.
