### ISSUE TITLE
adding live chat support

### ISSUE THREAD

**Issue by vp393001** [microsoft/BotBuilder-Samples#2184]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
During an ongoing conversation with bot, if customer wants to chat with a live agent then how to implement it?

**Describe the solution you'd like**
Customer should be able to chat with live agent from the same chat window.

**Comment by arturl** [comment]
Hi @vp393001, we're working on this for the next iteration of the Bot Framework. You can read about our approach [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library). They key question for you is to decide what agent hub you want to integrate with. At this moment, we offer integration with LivePerson that is available [here](https://developers.liveperson.com/third-party-bots-microsoft-bot-framework.html).
