### ISSUE TITLE
Sample 46 TeamsAuth: Logout not working if command is "logout"

### ISSUE THREAD

**Issue by rohannevrikar** [microsoft/BotBuilder-Samples#2185]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore 
3. Sample name: TeamsAuth

## Describe the bug
If a user types in command "logout" to sign out, the user does not get signed out. Instead the user is asked "Would you like to view a token". It works for commands having more words like "Please log me out" etc. 

## To Reproduce
1. Run the sample
2. Type anything to login
3. Type "logout"
4. It shows "Would you like to view your token".

## Expected behavior
If user types "logout", the bot should sign out user and show message "You have been signed out".

## Screenshots
![image](https://user-images.githubusercontent.com/26645175/74365896-f4a47900-4df4-11ea-9453-13f439a44816.png)

[bug]

**Comment by jwiley84** [comment]
Thank you for noticing this and the PR. It should be merged some time today, barring any major issues. I'll come and close this when it is.

**Comment by rohannevrikar** [comment]
Glad to contribute :)
