### ISSUE TITLE
Teams App Manifest is missing in teams-auth bot

### ISSUE THREAD

**Issue by KoushikGoramane** [microsoft/BotBuilder-Samples#2214]
Please add the manifest file for the teams-auth bot and also provide the documentation on  how to add it to the channels. It will be helpful.

**Comment by EricDahlvang** [comment]
Hi @KoushikGoramane 

Thank you for bringing this to our attention.  I've submitted a PR with these updates here: https://github.com/microsoft/BotBuilder-Samples/pull/2216
