### ISSUE TITLE
 [onTurnError] unhandled error: Error: getaddrinfo ENOTFOUND https https:443

### ISSUE THREAD

**Issue by Narayan22** [microsoft/BotBuilder-Samples#2222]

**Comment by dmvtech** [comment]
@Narayan22 

We need more info that this.

Please give the following information:

- [ ] What language are you using?
- [ ] What channel are you testing in?
- [ ] Which sample are you using?
- [ ] What steps did you take before you get this error?


If possible, the fastest way to a resolution is to post a link to your own repository where you have a reproduction of the issue.

**Comment by Narayan22** [comment]
Thanks for the reply. but I slove the error just remove https in .env file hostname.
