### ISSUE TITLE
Integrating composer Adaptive Dialogs in botframework v4 Echo bot

### ISSUE THREAD

**Issue by rajeshyalamarthi** [microsoft/BotBuilder-Samples#2225]
Hi,I am trying to integrate composer's adaptive dialog in bot framework V4 echo bot. I loaded all the components which are required. There are no build errors for me, but when i was debugging, at the point where DeclarativeTypeLoader is trying to load root dialog file, it is throwing the error:
'Type specified in JSON 'Microsoft.AdaptiveDialog' was not resolved. Path '$type', line 3, position 37.'
![Capture](https://user-images.githubusercontent.com/31951690/70438107-1ad73100-1ab3-11ea-8d4d-0265e2ffe1ef.PNG)

**Comment by stevengum** [comment]
Closing per this [comment](https://github.com/microsoft/BotBuilder-Samples/issues/2225#issuecomment-584549948)
