### ISSUE TITLE
Use ActivityHandler.onEndOfConversation() in the JS samples

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#2226]
EndOfConversation Activities now route through the ActivityHandler so we should use [`onEndOfConversation()`](https://github.com/microsoft/botbuilder-js/blob/c2eebb721d48c514b2fc6cb83fa90e408d469281/libraries/botbuilder-core/src/activityHandler.ts#L266) for the skills samples.

This is labeled as R8 as we need to be able to perform e2e tests on the skills samples in JS.

**Comment by EricDahlvang** [comment]
related to onUnrecognizedActivityType previously being used

**Comment by Kaiqb** [comment]
@stevengum - shouldn't this be in the samples repo?

**Comment by stevengum** [comment]
Closing via #2232 (merged to [`gary/net-core-3-1`](https://github.com/microsoft/BotBuilder-Samples/tree/gary/net-core-3-1))
