### ISSUE TITLE
Slack adapter sample goes into message loop

### ISSUE THREAD

**Issue by Anshul21** [microsoft/BotBuilder-Samples#2233]
## Sample information
1. Sample type: slack-adapter
2. Sample language: dotnetcore
3. Sample name: slack-adapter
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/60.slack-adapter
## Describe the bug
I am trying the slack-adapter example, when i tried the echo bot, it goes into weird loop.
## To Reproduce
1. Set-up bot according the slack-adapter example. Run hello, this will loop forever.

## Expected behavior
bot shouldn't loop
## Additional context
It works perfectly file on emulator

<img width="562" alt="Screen Shot 2020-03-10 at 8 54 40 PM" src="https://user-images.githubusercontent.com/7298709/76380956-74006c00-6311-11ea-95d5-aa8506d708c3.png">

[bug]
<img width="555" alt="Screen Shot 2020-03-10 at 8 48 54 PM" src="https://user-images.githubusercontent.com/7298709/76380788-f8062400-6310-11ea-9abe-8bbbb5363e50.png">

**Comment by jwiley84** [comment]
I am unable to repro this. Are you getting any errors when you run the bot or in  ngrok?

**Comment by Anshul21** [comment]
@jwiley84 are you doing from mac ? i am running ngox from my mac machine, also what is .netcore version you are using? i am on 2.1

**Comment by Anshul21** [comment]
also i see a diff in slack controller code mentioned in the tutorial here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=adapter

and sample code https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/60.slack-adapter/Controllers/SlackController.cs

the example has     private readonly SlackAdapter _adapter; in SlackController whereas in tutorial, it has         private readonly IBotFrameworkHttpAdapter _adapter;
@jwiley84

**Comment by Anshul21** [comment]
any update on this? @Anshul21

**Comment by Anshul21** [comment]
I see, the issue has been resolved in latest code in repository but it's not being published yet. I was able to download the repository, build a nuget pckg locally. I will mark this as resolved and would wait till they release the latest nuget pckg
