### ISSUE TITLE
Experimental Adaptive corebot C# sample SetProperty() does not save entities returned by LUIS

### ISSUE THREAD

**Issue by kellog5** [microsoft/BotBuilder-Samples#2241]
## Sample information
1. Sample type: [BotBuilder-Samples/experimental/adaptive-dialog/csharp_dotnetcore/]
2. Sample language: [dotnetcore]
3. Sample name: <04.core-bot>

## Describe the bug
When chatting with the bot and asking to book a flight AND including destinationCity, departureCity or departureDate in the original utterance, the bot DOES not store the entites and instead prompts for the user to provide the information again.

## To Reproduce
1. Start the core bot sample
2. Connect to the corebot sample with Bot Framework Emulator
3. Type the utterance "Book flight from miami"
4. The bot asks "What is your departure city?"

The same problem occurs if you provide destinationCity and/or departureDate int he original utterance.
e,g., "Book flight from miami to dallas tomorrow"

## Expected behavior
- The bot records 'miami' as the fromCity (departureCity)
- The bot ask "what is your destination city"? (since it already has your departureCity

## Additional context
I reported on StackOverflow at https://stackoverflow.com/questions/60653574/why-doesnt-botframework-experimental-adaptive-corebot-c-sharp-sample-setpropert

The code in question is found at 
https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot/Dialogs/RootDialog.cs

I thought the SetProperty() action would store the entity

Value = "@fromCity.location"
in the property

Property = "conversation.flightBooking.destinationCity"
Subsequently, the TextInput would use the prompt

Prompt = new ActivityTemplate("@{PromptForMissingInformation()}")
which reads in the RootDialog.lg file

https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot/Dialogs/RootDialog.lg

# PromptForMissingInformation
- IF: @{conversation.flightBooking.departureCity == null} 
  - @{PromptForDepartureCity()}
- ELSEIF: @{conversation.flightBooking.destinationCity == null}
  - @{PromptForDestinationCity()}
- ELSEIF: @{conversation.flightBooking.departureDate == null}
  - @{PromptForTravelDate()}
- ELSE: 
  - @{ConfirmBooking()}
This should NOT prompt for departure city if it was already provided/stored.

I also looked at the results returned from LUIS using LUIS trace in Bot Framework Emulator. LUIS appears to correctly identify the intent Book_flight AND the entity fromCity as miami

{
  "recognizerResult": {
    "alteredText": null,
    "entities": {
      "$instance": {
        "fromCity": [
          {
            "endIndex": 22,
            "startIndex": 17,
            "text": "miami",
            "type": "builtin.geographyV2.city"
          }
        ]
      },
      "fromCity": [
        {
          "location": "miami",
          "type": "city"
        }
      ]
    },
    "intents": {
      "Book_flight": {
        "score": 0.941154063
      }
    },
    "text": "book flight from miami"
  }
}

## Proposed Solution
It appears the recognized entities are stored in an array and need to be accessed via the long form in the Value expression of the SetProperty() Action.

new SetProperty()
{

     Property = "conversation.flightBooking.departureCity",
     // Value is an expresson. @entityName is short hand to refer to the value of an entity recognized.
     // @xxx is same as turn.recognized.entities.xxx
     //Value = "@fromCity.location"                                
     Value = "turn.recognized.entities.fromCity[0].location"
},
the same for destinationCity

Value = "turn.recognized.entities.toCity[0].location"
and departureDate

Value = "turn.recognized.entities.datetime[0].timex[0]"
These changes allow the entities to be stored and NOT asked for if they are provided in original message. For example,

Book flight from miami
- Where would you like to travel to? 
(miami is stored as departureCity and used later, destination city is prompted for)

I can't say this will work in all situations as I'm not sure of the data model, but it does seem to fix the specific use case for the sample.

[bug]

**Comment by CezaryMarcjan** [comment]
Thanks @kellog5 for the report. Team will address this post R8.
