### ISSUE TITLE
Twilio WhatsApp Adapter

### ISSUE THREAD

**Issue by spaniard81** [microsoft/BotBuilder-Samples#2243]
I was wondering if the Twilio WhatsApp Adapter is in the planning for the python version of the Bot? The adapter is already available for JS and C#.

What are the alternatives to connect a python Azure Bot to WhatsApp until such an adapter is available?

**Comment by stevkan** [comment]
This question should be posted in the [BotBuilder-Community-Python](https://github.com/BotBuilderCommunity/botbuilder-community-python) repo. The Samples repo provides demonstrations of current functionality and the BotBuilder-Python repo is focused on core SDK development. The community repos are focused on extending functionality, for example, the supplied adapters that already exist in some of the sister repos (dotnet and Node). Alternatively, BotKit has a Twilio adapter that _may_ work for you, depending on your needs (located [here](https://github.com/howdyai/botkit/tree/master/packages/botbuilder-adapter-twilio-sms)).

Closing this issue as unrelated to the current repo.

**Comment by arumugamm** [comment]
Could you please share the repo detail for Azure bot Twilio whatsapp adapter in C#
