### ISSUE TITLE
Add a sample for SSO with skills

### ISSUE THREAD

**Issue by swagatmishra2007** [microsoft/BotBuilder-Samples#2264]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by gabog** [comment]
this should be addressed as part of https://github.com/microsoft/BotBuilder-Samples/issues/2811, closing it.
