### ISSUE TITLE
Doesn't received message in Microsoft Teams

### ISSUE THREAD

**Issue by kennethnavarro** [microsoft/BotBuilder-Samples#2274]
## Sample information
1. Solution: 57.teams-conversation-bot
2. language: [dotnetcore]

## Describe the bug
I tried to set up the project and corresponding application like ngrok, and created a bot service using dev.botframework.com with App ID and App Password. The application is running (no error) when I send a message on the bot team channel. The problem is the reply message, the both channel doesn't display or should I say received it.

Note: I tried to use the bot emulator and everything is working fine. The application reply is displaying in the bot emulator.

## To Reproduce
1. I just followed the setup in Read.me
2. Run the ngrok
3. Configured the bot settings in dev.botframework.com to use the ngrok https site link.
4. Run the program
![image](https://user-images.githubusercontent.com/59459710/77496889-fc8d1980-6e86-11ea-9b42-8c9c9d691597.png)
After
![image](https://user-images.githubusercontent.com/59459710/77497111-7e7d4280-6e87-11ea-8ef9-012bcbcf0855.png)

## Expected behavior
I should be receiving the reply in Teams bot channel

[bug]

**Comment by kennethnavarro** [comment]
This ok already. It's an access issue in Azure. Thanks!

**Comment by neorest** [comment]
> 
> 
> This ok already. It's an access issue in Azure. Thanks!

How exactly you resolved this access issue in Azure?
