### ISSUE TITLE
Single login for all contexts

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2275]
I added sign in flow on link unfurling. So now when `OnTeamsAppBasedLinkQueryAsync` is called `turnContext.Activity.Value` contains the token saved before.
The problem is when the same user is calling bot in the same conversation window by command and `OnMessageActivityAsync` get called `turnContext.Activity.Value` is `null`.
What is the correct flow? Should I store token on my side and match user by id? What's the supposed workflow?

**Comment by congysu** [comment]
@clearab can you please take a look on this? thanks.

**Comment by clearab** [comment]
Yes, you typically cache the token on the bot side.

I'm not sure I understand your flow. Is it:
1. The user pastes a link into the compose box, then expands it to trigger link unfurling
2. The user then logs in
3. The user the @mentions the bot in the same compose box as part of the same message

Does that look correct?

**Comment by GDreyV** [comment]
Yes, you are very close:
1. The user pastes a link into compose box
2. Bot returns Sign in request for link unfurling which is displayed as thumbnail
3. User sign ins and got correct preview.
-- So we are signed in on that step and token is stored on the Teams side.
4. User sends random message
And here we do not have a token in which was just saved on unfurling flow.

**Comment by clearab** [comment]
How are you handling auth? I don't think Teams should be storing the token, it should be stored either in your bot or in the TokenService. @EricDahlvang can you assist here?

**Comment by EricDahlvang** [comment]
Hi @GDreyV 

The magic code is only useful for the initial token retrieval validation. Subsequent calls to `GetUserTokenAsync `do not require it.  Which means the following code works as expected. 

If a user had previously signed in via `OnTeamsAppBasedLinkQueryAsync`, this will successfully show the token:

```cs
        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var tokenResponse = await (turnContext.Adapter as IUserTokenProvider).GetUserTokenAsync(turnContext, _connectionName, string.Empty, cancellationToken: cancellationToken);
            if (tokenResponse != null && !string.IsNullOrEmpty(tokenResponse.Token))
            {
                var reply = MessageFactory.Text($"You are signed in.  Here is your token: {tokenResponse.Token}");
                await turnContext.SendActivityAsync(reply, cancellationToken);
            }
            else
            {
                var reply = MessageFactory.Text($"You are NOT signed in.");
                await turnContext.SendActivityAsync(reply, cancellationToken);
            }
        }
```

**Comment by GDreyV** [comment]
Ah, I got it! My bad. Thanks a lot for clarifications! I was using `magicCode` as it was always set with unfurling flow and was surprised that doesn't exist in conversation context.

**Comment by GDreyV** [comment]
@EricDahlvang, sorry one more question on the same topic. Is there any way to find out when I need to use magic code and when I should skip it? If I got it right I need it only when user logins but how can I find this? E.g. for link unfurling flow how can I find that user just signed in and I need to use magic code?
I'm asking because Dialogs have `state` value which is usually used as a magic code in auth but it's not a magic code.

**Comment by EricDahlvang** [comment]
In the link unfurling flow, the magic code is in the activity.value as 'state'.  Dialog state is different from 'magic code' state.  If you are using auth in link unfurling, then link unfurling is where the 'state' magic code will come into the bot.  If the activity.value does not have a 'state' field in the link unfurling handler, then the call is not the final step of link unfurling auth flow.

**Comment by GDreyV** [comment]
Did I got it right that the only place where I need to use magic code from the state is link unfurling auth? In Dialog flow in case if we need magic code it will be message text.

**Comment by EricDahlvang** [comment]
Teams will send an invoke, with a Name of "signin/verifyState".  If you are using the OAuthPrompt, the dialog itself will handle the incoming activity:  https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L276

Just make sure there is a handler for `handleTeamsSigninVerifyState` as demonstrated in https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/46.teams-auth/bots/teamsBot.js#L28

**Comment by GDreyV** [comment]
Ah, got it, thank you!
