### ISSUE TITLE
poll interval problem

### ISSUE THREAD

**Issue by weizhenzhao** [Microsoft/BotBuilder-Samples#228]
My colleague meet a wired problem when he using the sample code of direct line
in our back end we will query data for fusion BI report system
so there may be some latency.
But I find the direct-line will call several times, if it doesn't received the reply for my bot
So this will definitely add more latency .
So my question is how to set the poll interval in c# code?
Because currenty it seems that was config by the code
DirectLineClient client = new DirectLineClient(directLineSecret);

and I find no where to change the poll interval .
Please help with me .

I see it writes that in microsoft offical site:

"
Clients that poll using HTTP GET should choose a polling interval that matches their intended use.

Service-to-service applications often use a polling interval of 5s or 10s.

Client-facing applications often use a polling interval of 1s, and issue an additional request ~300ms after every message that the client sends (to rapidly retrieve a bot's response). This 300ms delay should be adjusted based on the bot's speed and transit time.
"

Thanks
weizhen

**Comment by sgellock** [comment]
closed due to inactivity
