### ISSUE TITLE
Segurization api

### ISSUE THREAD

**Issue by FlorenciaNodar** [microsoft/BotBuilder-Samples#2293]
Hello! Do you have an example of using the identityserver token in the bot to consume api rest service?

**Comment by mrivera-ms** [comment]
@FlorenciaNodar, thank you for opening this issue. For product behavior, how-to, general understanding questions, please use Stackoverflow. 

https://stackoverflow.com/search?q=bot+framework

Also, you can search in the [Bot Framework Samples](https://github.com/microsoft/BotFramework-Samples)
