### ISSUE TITLE
unable to restore nuget packages

### ISSUE THREAD

**Issue by kittu610** [microsoft/BotBuilder-Samples#2297]
I have downloaded the bot builder samples when i tried to build the solution i am getting this issues

 

Unable to find package Microsoft.Bot.Builder.Adapters.Webex with version (>= 4.8.0-rc2-preview)   
Unable to find package Microsoft.Bot.Builder.Adapters.slack with version (>= 4.8.0-rc2-preview)   
Unable to find package Microsoft.Bot.Builder.Adapters.twilo  with version (>= 4.8.0-rc2-preview)   
Unable to find package Microsoft.Bot.Builder.Adapters.facebook with version (>= 4.8.0-rc2-preview)   

How to resolve it,please any suggestions

**Comment by jwiley84** [comment]
I am unable to repro this. Can I get a few more details from you? 
- When did you download the samples?
- What IDE are you using?
- Which bots specifically are unable to load those packages?

**Comment by EricDahlvang** [comment]
This was fixed yesterday with https://github.com/microsoft/BotBuilder-Samples/pull/2295

Please refresh your local git with these changes from master

**Comment by kittu610** [comment]
The issues has been solved thanks
