### ISSUE TITLE
Missing dependency botbuilder-dialogs

### ISSUE THREAD

**Issue by tmpkn** [microsoft/BotBuilder-Samples#2298]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [python]
3. Sample name: 46.teams-auth

## Describe the bug
Python Teams samples miss botbuilder-dialogs dependency.

## To Reproduce
1. Go to 46.teams-auth
2. pip install -r requirements
3. python app.py
4. See error: ModuleNotFoundError: No module named 'botbuilder.dialogs'

## Expected behavior
App should run without errors

## Additional context
pip install botbuilder-dialogs fixes the issue

[bug]

**Comment by cleemullins** [comment]
@jwiley84 Please update the sample, and let us know when a Pull Request is ready. Thanks!

**Comment by jwiley84** [comment]
There are a couple that are missing this from the requirements.txt file. I'm looking into it and get a PR out!
