### ISSUE TITLE
Deployment Failed (View Error)

### ISSUE THREAD

**Issue by owidat** [Microsoft/BotBuilder-Samples#230]
I have an issue when I try to deploy "Multi Dialog" Sample Project to Azure using the following:
I used https://deploy.azure.com/#/form/deploy

1st I Created a bot with the Azure Bot Service from:
https://dev.botframework.com/bots/provision

Then I tried "deploy to azure" from:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-MultiDialogs
or from the list of:
https://github.com/microsoft/BotBuilder-Samples

I chose C# option, Also I tried Node, but the result is same:

Submitting Deployment
Deployment Started
Creating Web Hosting Plan
Creating Website
Updating Website Config 
Deployment Failed (View Error)

when I click View Error, it just a popup dialog with title "Deployment Error"
And the content "Failed Deployment"

when I go to my resource group I see that it created new "Web Hosting Plan" and "Website" every time I try this

**Comment by sgellock** [comment]
closed due to inactivity
