### ISSUE TITLE
document for operators in Pre-built functions

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotBuilder-Samples#2301]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I read the document, I don't know whether + - is supported in string/list, whether [] is case sensitive or not in https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#where

**Describe the solution you'd like**
Add explanations for operators in document

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by mrivera-ms** [comment]
@emgrol , any updates on this?

**Comment by emgrol** [comment]
@mrivera-ms I added a fix for this issue in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2268. The PR will be merged today.

**Comment by mrivera-ms** [comment]
@emgrol , thanks, Emily. The link appears to be broken. Is the PR merged?

**Comment by emgrol** [comment]
@mrivera-ms Here's the link again: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2268. The PR was just merged.

**Comment by emgrol** [comment]
This issue can be closed, the fix is now [live](https://docs.microsoft.com/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions) .
