### ISSUE TITLE
How to trigger "Menu" event handler if the choice is not mapped or not exist

### ISSUE THREAD

**Issue by deepumi** [Microsoft/BotBuilder-Samples#231]
Hi,
I have a menu with set of choices using PromptDialog.Choice, and I know I can map each menu item with multiple values.

I would like to know if user type something which is not mapped in the menu and I want to trigger the selected event handler method so that I can check with custom keywords. Is it possible?

I tried different overloads for PromptDialog.Choice but not happening..Any suggetion or workaround. Please advice.

**Comment by jkolonko** [comment]
Hi deepumi,

I wrote a custom prompt for PromptDialog.Confirm which tries to match something with LUIS before it passes control to standard prompdialog's recognizer (see https://github.com/ObjectivityLtd/Bot.Common.Dialogs/blob/master/Objectivity.Bot.BaseDialogs/Dialogs/LuisPrompt.cs) . I am not sure if a similar approach would work for you but you can write your code in a similar way - just reuse original recognizer and do some custom action when nothing matches.

Regards,
Jacek

**Comment by deepumi** [comment]
@jkolonko Thanks. 
Unfortunately I can't use PromptDialog.Confirm for the particular scenario. However, I found a workaround to use adaptive card (Hero Card) which does look like a MENU with multiple button and the post back trigger does happen for each click or user typing text.
