### ISSUE TITLE
Documentation & samples for expectReplies

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2313]
Create documentation and samples for bots connecting to skills using they "expectReplies" flag. A good example would be using a DirectLine speech parent.

**Comment by EricDahlvang** [comment]
Notes:

- We probably do not need an entire sample for this, considering there is very little code involved.

- Setting DeliveryMode to ExpectReplies will cause all replies to be buffered into the http response of the request rather than the normal bot framework sdk host to skill method of posts to the SkillController. This enables Request/Response, rather than just post/post.

- Change [80.skills-simple-bot-to-bot](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/SimpleRootBot/Bots/RootBot.cs) skill host to use ExpectReplies:

**Current code**
```cs
        private async Task SendToSkill(ITurnContext turnContext, BotFrameworkSkill targetSkill, CancellationToken cancellationToken)
        {
            await _conversationState.SaveChangesAsync(turnContext, force: true, cancellationToken: cancellationToken);

            var response = await _skillClient.PostActivityAsync(_botId, targetSkill, _skillsConfig.SkillHostEndpoint, turnContext.Activity, cancellationToken);

            if (!(response.Status >= 200 && response.Status <= 299))
            {
                throw new HttpRequestException($"Error invoking the skill id: \"{targetSkill.Id}\" at \"{targetSkill.SkillEndpoint}\" (status is {response.Status}). \r\n {response.Body}");
            }
        }
```

**Change to**
```cs
private async Task SendToSkill(ITurnContext turnContext, BotFrameworkSkill targetSkill, Activity activity = null, CancellationToken cancellationToken)
{
	await _conversationState.SaveChangesAsync(turnContext, force: true, cancellationToken: cancellationToken);

	// Clone the activity, since we are changing DeliveryMode on the outgoing activity
	var activityToSend = JsonConvert.DeserializeObject<Activity>(JsonConvert.SerializeObject(activity ?? turnContext.Activity));

	// In this way, only the Direct Line Speech channel is using ExpectReplies.
	if (turnContext.Activity.ChannelId == Channels.DirectlineSpeech)
	{
		activityToSend.DeliveryMode = DeliveryModes.ExpectReplies;
	}

	var response = await _skillClient.PostActivityAsync<ExpectedReplies>(_botId, targetSkill, _skillsConfig.SkillHostEndpoint, activity, cancellationToken);

	if (!(response.Status >= 200 && response.Status <= 299))
	{
		throw new HttpRequestException($"Error invoking the skill id: \"{targetSkill.Id}\" at \"{targetSkill.SkillEndpoint}\" (status is {response.Status}). \r\n {response.Body}");
	}
	else if (response.Body?.Activities != null && response.Body.Activities.Any())
	{
		await turnContext.SendActivitiesAsync(response.Body.Activities.ToArray(), cancellationToken);
	}
}
```

**Comment by clearab** [comment]
I'm not sure if this demonstrates how/why you would want to use expectReplies adequately. I'm ok with combining the samples (assuming @gabog agrees), but I think we'd want something easier to switch on so that developers could test this w/o DirectLine. @gabog or @johnataylor do we have a good list of the reasons why you'd use expectReplies?

**Comment by EricDahlvang** [comment]
@clearab is there any reason a skill host would or should NOT use ExpectReplies?  Maybe we should update all of the skills samples to always use it, regardless of channel.
