### ISSUE TITLE
How to get ActiveDialog externally to clear it.

### ISSUE THREAD

**Issue by Ashi123489** [microsoft/BotBuilder-Samples#2316]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
I have one Echo bot where i am using WaterFall dialog.i have one more controller there in same solution called notification controller. i want to send notification  after checking Active dialog of current user. Is there way to get Active Dialog of particular user.

**Comment by axelsrz** [comment]
Hello @Ashi123489 thanks engaging with us. In this case stackoverflow will be the correct platform to post your question. I'm going to close this thread given that we only handle issues by this channel.
