### ISSUE TITLE
Adaptive-tools

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotBuilder-Samples#2318]
- [ ] Support for visual studio
- [ ] Support for JS bots.
- [ ] Debugging - debug console integration/ ability to evaluate expressions with snapshot of memory.
- [ ] Surface predictions (if using LUIS) into .lu document
- [x] syntax highlighting, auto-suggest, auto complete functionality
    - [x] .qna documents
- [ ] ability to train, test, publish .lu documents to
    - [ ] LUIS
    - [ ] Orchestrator (embeddings)
- [ ] ability to test and refine 
    - [ ] .lu documents with
        - [ ] LUIS
        - [ ] Orchestrator
    - [ ] .qna documents with QnA Maker
- [ ] ability to get custom functions working with auto-suggest, auto-complete

**Comment by tracyboehrer** [comment]
I'm assuming this is no longer active.  Closing.
