### ISSUE TITLE
IVR Sample

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/BotBuilder-Samples#232]
Hi there, I'm wondering if it's possible to use Skype of Business Voice calling (now Teams Voice calling) to hookup incoming calls to IVR and use the bot framework to prompt the user IVR style and redirect.

If so, are there any samples on how to do this?

**Comment by HardikShah289** [comment]
I am searching for the same. I tried to use https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/skype-CallingBot for Skype For business. Message controller works as expected but no calls are picked up by bot through Skype For Business. Is there any specific setting need to do for Skype for Business channel.

**Comment by JohnGalt1717** [comment]
Anyone from MS want to comment on this? Would love to get some samples. Really want to use the same bot for web, sms, app, and voice IVR. It's the holly grail!

**Comment by kkabza** [comment]
You will be able to build a BOT in the future that can access the audio stream for speech processing or speech playback using Teams and receive calls in your bot from a ServiceLine in registered O365. I would pay attention to announcements at BUILD Conference there is no ETA for this yet. You can also search you tube for Enterprise Connect videos from Pexip. They built a bot for some video interop stuff and they have some demo videos out there. Also research this it will work kind of like this for Teams when this becomes available.

**Comment by juagraot** [comment]
> You will be able to build a BOT in the future that can access the audio stream for speech processing or speech playback using Teams and receive calls in your bot from a ServiceLine in registered O365. I would pay attention to announcements at BUILD Conference there is no ETA for this yet. You can also search you tube for Enterprise Connect videos from Pexip. They built a bot for some video interop stuff and they have some demo videos out there. Also research this it will work kind of like this for Teams when this becomes available. https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-real-time-audio-video-call-overview
Is there any solution not using Azure Cloud Service thats because is a tecnology that is going out (using Clasic portal in Azure).? And another thing is there any documentation using Teams instead of skype for business thats for the same reason (Skype for business in going out).

**Comment by kkabza** [comment]
There is nothing for Skype for Business other than UCMA. Skype on premise lives on but cloud is dead as a dev platform. Everything is cloud so NO must be in Azure also ties in with Azure AD for OAUTH. See here for hosting considerations https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots#real-time-media-bot-development-requires-cnet-and-windows-server                                                  

Options
Cloud Service
Service Fabric with Virtual Machine Scale Sets (VMSS)
Infrastructure as a Service (IaaS) Virtual Machine (VM)

**Comment by sgellock** [comment]
closed due to inactivity
