### ISSUE TITLE
Basic Bot has a hard coded date "Book a flight from Paris to Berlin on March 22, 2020"

### ISSUE THREAD

**Issue by v-josouz** [microsoft/BotBuilder-Samples#2321]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
This bug was originally written internally against the Botframework team.

## To Reproduce
1. Go to Test in Webchat of any Basic (non-echo) bot.
2. The bot will ask you what can it do for you say something like "Book a flight from Paris to Berlin on March 22, 2020".

## Expected behavior
The date shouldn't be hard coded. Instead something dynamic like today's date + 7 days

## Additional context

[bug]

**Comment by axelsrz** [comment]
Thanks for opening this issue @v-josouz, we'll assign it to someone for future fixing.

**Comment by tonyanziano** [comment]
We have prioritized this issue for the R10 milestone.
