### ISSUE TITLE
Create sample for using Skills with Dispatcher

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2323]
The purpose of this sample is to show how Dispatcher can be used to compose language models when using multiple skills. The sample needs to contain a consumer bot with some built in functionality and a language model, 2 skill each with different functionality and their own language models, and show how to use Dispatcher to combine them.

This sample should support the best-practices documentation outlined in [this issue](https://github.com/MicrosoftDocs/bot-docs-pr/issues/2092)

**Comment by gabog** [comment]
Hi @clearab, do we still need this? or should it be covered by the VA template that uses dispatcher and skills?

**Comment by gabog** [comment]
Closing it for now. We can reopen or recreate based on new developments for orchestrator and dispatcher
