### ISSUE TITLE
Teams samples: clarify bot registration requirements

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2324]
The README files for Teams samples need to be updated to clarify the requirements around creating a new bot. Currently they point [this page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration) when telling you to create your bot resource in Azure, however that page is ambiguous between creating a Bot Channels Registration or a Web App Bot. In this case they should be creating a Bot Channels Registration specifically. Also, I believe that page does not tell you how to get the app id & password for a Bot Channels Registration, just for the Web App Bot, and the steps are slightly different.

**Comment by garypretty** [comment]
All up SDK tracking issue for Teams docs https://github.com/microsoft/botframework-sdk/issues/5896
