### ISSUE TITLE
Track bot installed/deleted event.

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2331]
Hello! What is the proper way to find out that Bot was installed or removed? As I understand I should use `OnConversationUpdateActivityAsync` handler and check `turnContext.Activity.MembersAdded` or `turnContext.Activity.MembersRemoved` properties. The problem is that `member.Id` is not the same as application id, it is something like `13:{ApplicationId}`. Should I use something like `member.Id.EndsWith`? Or should I use some completely different approach for that?

**Comment by GDreyV** [comment]
Sorry, I should provide details in the beginning.
Yes, you are right, I'm talking about Teams bot. And I want to make some actions as Bot was installed or removed. As I see in [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#core-bot-framework-handlers) `OnMembersAddedAsync` is fired when either user or bot was added. So I'm trying to find out that specifically my Bot was added but not some user or different bot. My guess was that I need to check who was added and compare bot id against added or removed users.

**Comment by mdrichardson** [comment]
@GDreyV The sample I linked should already cover this with the line ` if (member.Id != turnContext.Activity.Recipient.Id)`. Teams *does* use their own ID convention, so if that's not working for you, you'll want to debug inside your bot and figure out what the `Recipient.Id` is and hardcode it in.

**Comment by GDreyV** [comment]
Ah, I got it, so instead of using application id, I should check if the recipient (in application installed/removed case it's bot id with some prefix) is within added or removed members list.
It was tricky because when I'm sending proactive message I'm using application id, but when I receive notification I can't match user which stands for the bot by the application id.
Thanks for the clarification.
