### ISSUE TITLE
Cannot read property 'isChannelConversation' of undefined

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2335]
Hello! I'm trying to use `ActionTypes.PostBack` on card returned from `OnTeamsMessagingExtensionSelectItemAsync` of my Teams bot with following code:
```csharp
var card = new ThumbnailCard
  {
    Title = project.Name,
    Buttons = new List<CardAction>
      {
        new CardAction { Type = ActionTypes.PostBack, Title = "Subscribe", Value = query },
      },
  };
var attachment = new MessagingExtensionAttachment { ContentType = ThumbnailCard.ContentType, Content = card, };
return Task.FromResult(new MessagingExtensionResponse
  {
    ComposeExtension = new MessagingExtensionResult
      {
        Type = "result",
        AttachmentLayout = "list",
        Attachments = new List<MessagingExtensionAttachment> { attachment }
      }
  });
```
but when I press the button in browser I'm getting following error and nothing happens:
```
TypeError: Cannot read property 'isChannelConversation' of undefined
    at t.getAppDefinitionFromCard (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:308254)
    at t.logTelementryForCardAction (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:276083)
    at _.debounce.trailing (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:148902)
    at e (https://statics.teams.cdn.office.net/hashedjs/2-vendor.min-68b363d0.js:64:245)
    at f (https://statics.teams.cdn.office.net/hashedjs/2-vendor.min-68b363d0.js:65:49)
    at t.e.buttonClicked (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:148400)
```
Am I sending the card wrong? Is it supported flow? MessageBack and ImBack cause slightly different errors but anyway none of them work for me.
It's duplicate of https://github.com/microsoft/botframework-sdk/issues/5811 but I'm not sure what is the better place to ask the question.

**Comment by GDreyV** [comment]
The flow I'm trying to implement is:
- user lookup the project using compose extension query command
- bot provides option to subscribe to the project or open it
- user subscribes to the project
As I understand the Card should be sent in order to enable buttons. But is it possible to use buttons without sending the card (while it's in compose message area)?

**Comment by GDreyV** [comment]
BTW it looks like `Value` of `CardAction` can be only JObject but not regular object. In case of plain object value will be set to null.

**Comment by v-kydela** [comment]
Hello @GDreyV - I would like to help but I have a few questions.

1. "I'm getting following error" doesn't tell us what you're seeing. Where are you seeing that error/stack trace (browser console, App Insights, etc.)?
1. You say you're getting the error in a browser. Does the same thing happen on the Teams desktop client and mobile clients?
1. Are you getting the error when you try to send the card or when you try to click on the card?
1. Does the card work normally when your bot tries sending the card to the conversation in response to a user message?

Also, please post a screenshot/gif so we can better understand what's happening

**Comment by GDreyV** [comment]
1. Error stack is in browser's console window when I run Teams in browser (Edge).
2. I didn't try it in desktop client. On mobile client it was impossible to reproduce as card doesn't have any buttons at all (either in compose window or when it's submitted)
3. The errors occur when I click on buttons when card is in compose area.
4. Yes, it works, also it works when card is submitted.
![image](https://user-images.githubusercontent.com/6262948/80027089-3155b600-84b1-11ea-8fca-b73b7d73bded.png)

**Comment by v-kydela** [comment]
@GDreyV - Thank you for the screenshot, that helps. Would you go ahead and try it in the desktop client and answer question 5?

**Comment by GDreyV** [comment]
in the app when I press the button it doesn't do anything. And after couple clicks button kind of hangs:
![image](https://user-images.githubusercontent.com/6262948/80036375-9b755780-84bf-11ea-83a6-a46e5b4523c4.png)

**Comment by v-kydela** [comment]
@GDreyV - What is your answer to question 5?

**Comment by GDreyV** [comment]
Oh, sorry, I missed it.
This code doesn't work, value will be null when user press the button
```csharp
new CardAction { Type = ActionTypes.MessageBack, Title = "Subscribe", Value = new { project.Id } }
```
and this code works
```csharp
new CardAction { Type = ActionTypes.MessageBack, Title = "Subscribe", Value = JObject.FromObject(new { project.Id }) }
```

**Comment by v-kydela** [comment]
@GDreyV - Since you posted in the sample repo, are you following a specific sample? Sample 50 perhaps? https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/50.teams-messaging-extensions-search

**Comment by GDreyV** [comment]
really 52.teams-messaging-extensions-search-auth-config, 50 looks pretty the same.

**Comment by stevkan** [comment]
@GDreyV, I just want to make sure I'm caught up on what you are wanting. In a 1:1 conversation between a user and your bot, you want to be able to capture any card attachment meta data sent back to the bot from a messaging extension in order to identify where the card originated from, correct? To be able to tell if the card returned came from your bot, Bing News, GitHub, or any other bot/app messaging extension the user has installed and is interacting with?

If this is so, the card returned to the bot from the messaging extension is, as you guessed, an activity type of "message". The activity attachment property contains the generated card. You can access this via `OnTurnAsync` or one of the other regular or Teams specific activity handlers in your bot.

Does this help or did I shoot wide of the mark?

**Comment by stevkan** [comment]
Hi @GDreyV, can you give example data for what you are sending in the card, namely the `project.Name` and `project.Id`? Knowing the kinds of data you are sending will be useful. Also, what is expected to happen when "Subscribe" is pressed? Is it supposed to open a link, begin some process by the bot, or something else?

**Comment by GDreyV** [comment]
Hello @stevkan `project.Name` and `project.Id` are just simple string values. Specifically `Name` is just something like "New project" and `Value` is converted to string mongo id. Subscribe button is represented by the action:
```
new CardAction { Type = ActionTypes.PostBack, Title = "Subscribe", Value = query }
```
where `query` is `{ project.Id }`. So I suppose when card is in the message composing area buttons should be either disabled (if it not supposed to be pressed) or should work correctly. Right now nothing happens except errors in console.

**Comment by stevkan** [comment]
@GDreyV, thank you for your patience. I am working on this and hope to have some response to you shortly.

**Comment by GDreyV** [comment]
@stevkan, I'm not sure if it's related issue but here the case. I sent card into the `General` channel with `Subscribe` button as in the example above. User who is not authorized in the bot is pressing that button and nothing happens. The error in the console says:
```
angular.min.js:113 2020-05-06T00:10:28.848Z AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified
(anonymous) @ angular.min.js:113
e.logMessage @ msteams-web-ng1-services.min.js:1
e.error @ msteams-web-ng1-services.min.js:1
t.getInstalledAppForTeam @ msteams-web-ng1-services.min.js:1
(anonymous) @ msteams-web-ng1-services.min.js:1
f @ angular.min.js:126
(anonymous) @ angular.min.js:126
$eval @ angular.min.js:141
$digest @ angular.min.js:138
f.$digest @ msteams-web-ng1-services.min.js:1
$apply @ angular.min.js:141
(anonymous) @ angular.min.js:269
dispatch @ jquery.min.js:1
v.handle @ jquery.min.js:1
msteams-web-common.min.js:1 Uncaught (in promise) Invalid teamId and/or appId specified
(anonymous) @ msteams-web-common.min.js:1
f @ angular.min.js:126
(anonymous) @ angular.min.js:126
$eval @ angular.min.js:141
$digest @ angular.min.js:138
f.$digest @ msteams-web-ng1-services.min.js:1
$apply @ angular.min.js:141
(anonymous) @ angular.min.js:269
dispatch @ jquery.min.js:1
v.handle @ jquery.min.js:1
```

**Comment by stevkan** [comment]
@GDreyV, to clarify, is the error occurring in 1:1, chat, or both? And, as you mentioned unauthorized bot users, is it occurring for both authorized and unauthorized users?

Also, if you wouldn't mind, can you post your bot's manifest? It might be a red herring, but I'd like to see all applicable parts.

**Comment by GDreyV** [comment]
We didn't test these issues in 1:1 conversation, so it was channel and multiusers conversation. The last error I sent was just for not authorized user.

```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.0",
  "bots": [
    {
      "botId": "",
      "scopes": [ "personal", "team" ],
      "supportsFiles": false,
      "isNotificationOnly": false,
      "commandLists": [
        {
          "scopes": [ "personal" ],
          "commands": [
            { "title": "Help", "description": "Show help info" },
            { "title": "Sign In", "description": "Sign in into account for links unfurling and notifications" },
            { "title": "Sign Out", "description": "Sign out from the account" },
            { "title": "Subscribe to {url}", "description": "Subscribe for updates" },
            { "title": "Unsubscribe from {url}", "description": "Unsubscribe from updates" }
          ]
        }
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "",
      "commands": [
        {
          "id": "searchQuery",
          "type": "query",
          "title": "Search",
          "description": "Perform a projects search",
          "initialRun": false,
          "fetchTask": false,
          "context": [ "commandBox", "compose", "message" ],
          "parameters": [ { "name": "searchQuery", "title": "Search", "description": "Project's name", "inputType": "text" } ]
        }
      ],
      "messageHandlers": [
        {
          "type": "link",
          "value": {
            "domains": [ "*.domain.com" ]
          }
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [ "*.domain.com", "*.botframework.com" ]
}
```

**Comment by tracyboehrer** [comment]
@stevkan Can you update the status of this for the customer?

**Comment by stevkan** [comment]
@GDreyV, I just noticed you are trying to send a "postBack" action type which is not supported in Teams. If you are trying to send a message back to the bot that is not intended to be displayed to the user, you will want to use the "invoke" action type, referenced [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions). A response should look something similar to [this](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#example-incoming-invoke-message).

Please try with one of the supported action types and let me know if the issue resolves itself or persists.

**Comment by GDreyV** [comment]
Sorry, it was incorrect code past, really the code is:
```
new CardAction { Type = ActionTypes.MessageBack, Title = "Subscribe", Value = JObject.FromObject(new { project.Id }) }
```

**Comment by stevkan** [comment]
Can you show me the method in your bot that you are using to handle the incoming `MessageBack`?

**Comment by GDreyV** [comment]
Sorry, it might be wrong but as I recall this one:
```csharp
protected async override Task OnTeamsMessagingExtensionCardButtonClickedAsync(
            ITurnContext<IInvokeActivity> turnContext,
            JObject cardData,
            CancellationToken cancellationToken)
        {
            if (cardData != null && cardData.ContainsKey("Id"))
            {
                await this.subscribeFlow.SubscribeToProject(cardData["Id"].Value<string>(), turnContext, cancellationToken);
            }
        }
```
but really in the cases we faced this method was not called. We were just facing numerous exceptions in the browser.

**Comment by stevkan** [comment]
Hi @GDreyV, on April 21st (when you posted the issue), you stated

>  But is it possible to use buttons without sending the card (while it's in compose message area)?

In subsequent readings, I missed the "in compose message area" of that question. Unfortunately, the answer is no. While the card is in the compose message state, the actions associated with any buttons are outside the context of the bot as the card, itself, hasn't entered the message thread, yet. This means that any action you would wish the bot to respond to cannot occur because it can't reach the bot until the card is sent by the user.

As you can see in [this doc](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions), all the card actions mention interacting with the bot in some way. It's not surprising that `openUrl` is the only action that _does_ work because the context of that action is separate from the bot and Teams.

**Comment by GDreyV** [comment]
Ah, thank a lot for the details. I got it. Thank you for your time and investigation!
