### ISSUE TITLE
Add iFrame approach to Teams Task Module sample

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2341]
The Teams Task Module samples should have both an Adaptive Card based Task Module, and a iFrame website based example. Getting the submit correct from the iFrame can be difficult.

Tracking issues for Teams Docs review - https://github.com/microsoft/botframework-sdk/issues/5896

[enhancement]

**Comment by EricDahlvang** [comment]
Dotnet PR: https://github.com/microsoft/BotBuilder-Samples/pull/2546

other languages to follow, once this is approved/merge
