### ISSUE TITLE
Bot framework adapter is throwing error

### ISSUE THREAD

**Issue by krisalay** [microsoft/BotBuilder-Samples#2343]
## Sample information
1. Sample language: [nodejs]

## Describe the bug
```
TypeError: Cannot read property 'status' of undefined
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: BotFrameworkAdapter.processActivity(): 501 ERROR
    at BotFrameworkAdapter.<anonymous> (/app/node_modules/botbuilder/lib/botFrameworkAdapter.js:690:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/botbuilder/lib/botFrameworkAdapter.js:11:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## To Reproduce
1. Open oauth prompt in waterfall model
2. Enter any interrupt command
3. Click on the older signin card

## Expected behavior
The signin card should be disabled or it should open pop up to enter username/password.

[bug]

**Comment by hcyang** [comment]
Hi, @anusharavindrar, can you update the status and reply to the customer? Need the customer-replied tag. Thanks.

**Comment by anusharavindrar** [comment]
@krisalay are you following any specific botbuilder node sample? Also, are you getting this error while testing locally on the emulator or a particular channel?

**Comment by krisalay** [comment]
@anusharavindrar I am using Teams-Auth smaple for javascript-nodejs. And, I am getting this error in the teams channel. In the emulator there are no errors.

**Comment by anusharavindrar** [comment]
@krisalay I am not able to reproduce the issue on my end. Can you attach the screenshots of what you tried on Teams as well as the Emulator? Your issue looks similar to #1740. Can you try adding token.botframework.com to your validDomains in your app manifest and see if it works?

**Comment by anusharavindrar** [comment]
Closing the issue due to no response. Please feel free to reopen if the issue persists.
