### ISSUE TITLE
[Adaptive] C# ToDo Bot unintentionally deletes all ToDos, when intending to delete only 1 todo

### ISSUE THREAD

**Issue by Zerryth** [microsoft/BotBuilder-Samples#2351]
## Sample information
Adaptive C# Sample: ToDo

## Describe the bug
When deleting a todo, it deletes the one targeted--and all the other ones saved as well

## To Reproduce
![image](https://user-images.githubusercontent.com/35248895/80856455-067d0780-8bff-11ea-8b4f-d99df7818ec7.png)

Latest from nightly
![image](https://user-images.githubusercontent.com/35248895/80856488-4e039380-8bff-11ea-9543-851fff3c2ab5.png)

[bug]

**Comment by vishwacsena** [comment]
I have a fix; will push up as part of R9 updates.
