### ISSUE TITLE
JS Adaptive Linting Errors: no-template-curly-in-string (eslint)

### ISSUE THREAD

**Issue by Zerryth** [microsoft/BotBuilder-Samples#2361]
## Versions
Samples for JS preview of Adaptive

## Describe the bug
Running the eslinter on the JS adaptive samples (currently on vishwac/r9/js branch: [JS Samples](https://github.com/microsoft/BotBuilder-Samples/tree/vishwac/r9/js/experimental/adaptive-dialog/javascript_nodejs)) yields a bunch of "`no-template-curly-in-string`" errors, which occur, because references to LG templates are written as strings with curly braces:

ex.: `'${PromptForMissingInformation()}'`

## Expected behavior
No linting errors when running the linter on the JS samples should occur.
Need to either change the rule or the samples to explicitly excuse the rule-breaking.

### Context
https://eslint.org/docs/rules/no-template-curly-in-string

[bug]

**Comment by taicchoumsft** [comment]
@mrivera-ms , assigning these to you for now, as they are showing up in DRI report now that Ashley's left.
