### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by Fugit185** [microsoft/BotBuilder-Samples#2368]
## Sample information
1. Sample type: [sample]
2. Sample language: [python]
3. Sample name: <Welcome user>

## Describe the bug
Browser gives error "500: internal server error"

## To Reproduce
1. run app by "python app.py"
2. Open link http://localhost:3978/ in browser
3. Error shown in web page

##Environment
Ubuntu 16.04
Python 3.8
Mozilla firefox 75.0
Application running in conda environment

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by cleemullins** [comment]
Some quick questions:
1. Which sample? 
2. Why are you opening the Bot link in a browser? The Bot Framework Emulator would be the right tool.

**Comment by FuzzAU** [comment]
ohh, I was having the same issue until I saw this.
The step where "python app.py" is executed gives you a link, and the next step most of us would take is to try that URL. However the instructions clearly instruct to open the Bot Framework Emulator. 

Perhaps the samples should instruct users to do open the emulator to avoid future confusion.

**Comment by v-kydela** [comment]
Thank you for the suggestion, @FuzzAU 

You can see [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/02.echo-bot#testing-the-bot-using-bot-framework-emulator) that the samples already do instruct users to open the Emulator.


> ## Testing the bot using Bot Framework Emulator
> [Microsoft Bot Framework Emulator](https://github.com/microsoft/botframework-emulator) is a desktop application that allows bot developers to test and debug their bots on localhost or running remotely through a tunnel.
> 
> - Install the Bot Framework emulator from [here](https://github.com/Microsoft/BotFramework-Emulator/releases)
> 
> ### Connect to bot using Bot Framework Emulator
> - Launch Bot Framework Emulator
> - Paste this URL in the emulator window - http://localhost:3978/api/messages

I'm closing this issue now

**Comment by FuzzAU** [comment]
Thanks @v-kydela . Sorry I didn't explain well, my suggestion was that the application itself (in app.py) that a message is printed to the terminal that tells the user to open the emulator, and gives the full link  to http://localhost:3978/api/messages. 

I'll try and find time to put in a pull request to the repo later :)
