### ISSUE TITLE
Sign In popup height

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2373]
Hello! Sorry if I'm asking the question in the wrong place. What is height of the sign in window popup for auth flow in Teams bot? I mean window which is shown up when user press Sign In button on auth prompt? I'm asking because it looks like it has different height in different scenarios and platforms. Not sure what it depends on.

**Comment by mdrichardson** [comment]
@GDreyV I don't have a great, for-sure answer for you. This should probably be asked via the [Teams UserVoice](https://microsoftteams.uservoice.com/) as it has to do with the Teams client and not Bot Framework.

That being said, on my client, the window is 786.4 x 563.2 and is set to `display: flex`. If I were to guess, the window size is based on the display size of the user's monitor/screen; that's pretty typical for responsive development.
