### ISSUE TITLE
Send message to cortana failed

### ISSUE THREAD

**Issue by weizhenzhao** [Microsoft/BotBuilder-Samples#238]
### SDK Platform

.NET

### URL of Code Sample

//This will send an adhoc message to the user
        public bool Resume(string conversationId, string channelId,string text)
        {
            Log.WriteLogToTxt("fromId is :" + this.fromId);
            Log.WriteLogToTxt("fromName is :" + this.fromName);
            Log.WriteLogToTxt("toId is :" + this.toId);
            Log.WriteLogToTxt("toName is :" + this.toName);
            Log.WriteLogToTxt("serviceUrl is :" + this.serviceUrl);
            Log.WriteLogToTxt("replyToId is :" + this.replyToId);
            Log.WriteLogToTxt("locale is :" + this.locale);

            var userAccount = new ChannelAccount(this.toId, this.toName);
            var botAccount = new ChannelAccount(this.fromId, this.fromName);
            var connector = new ConnectorClient(new Uri(this.serviceUrl));

            IMessageActivity message = Activity.CreateMessageActivity();
            if (!string.IsNullOrEmpty(conversationId) && !string.IsNullOrEmpty(channelId))
            {
                message.ChannelId = channelId;
            }
            else
            {
                conversationId = (connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount)).Id.ToString();
            }
            message.From = botAccount;
            message.Recipient = userAccount;
            message.ServiceUrl = this.serviceUrl;
            message.Conversation = new ConversationAccount(id: conversationId);
            message.TextFormat = TextFormatTypes.Markdown;
            message.Text = text;
            message.ReplyToId = this.replyToId;
            message.Locale = this.locale;
            message.Timestamp = DateTime.Now;

            Log.WriteLogToTxt("Message resume details is  :" + JsonConvert.SerializeObject(message));

            Log.WriteLogToTxt("begin to send message to user ");
            connector.Conversations.SendToConversationAsync((Activity)message);
            Log.WriteLogToTxt("send message to user successfully in Resume ");
            return true;
        }

### Problem Description

I use the above code to send the adhoc message to skypeforbusiness successfully.
But failed in cortana . could you please have a look. thank you very much

//--------------------------succefully send to cortana , activity created by context.makeMessage()                     ---------------------------
{
  "type": "message",
  "timestamp": "2018-01-27T16:28:44.2751211Z",
  "serviceUrl": "https://CortanaBFChannelWestUS.azurewebsites.net/",
  "channelId": "cortana",
  "from": {
    "id": "cirrus-assistant-botchannel"
  },
  "conversation": {
    "id": "6ee5187f-aa49-40af-8ffb-ce43dfd085ab"
  },
  "recipient": {
    "id": "272DA19DB786D79A1D7FB4B7C14C0BFCFAE5DE05AAB6DB0720AA487760317C25"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "locale": "en-US",
  "text": "",
  "attachments": [],
  "entities": [],
  "replyToId": "2K6WZVjfpl2"
}

//failed send to cortana , using the above code - --------------------------------------------------
{
  "type": "message",
  "timestamp": "2018-01-27T16:28:54.8693589+00:00",
  "serviceUrl": "https://CortanaBFChannelWestUS.azurewebsites.net/",
  "channelId": "cortana",
  "from": {
    "id": "cirrus-assistant-botchannel"
  },
  "conversation": {
    "id": "6ee5187f-aa49-40af-8ffb-ce43dfd085ab"
  },
  "recipient": {
    "id": "272DA19DB786D79A1D7FB4B7C14C0BFCFAE5DE05AAB6DB0720AA487760317C25"
  },
  "textFormat": "markdown",
  "membersAdded": [],
  "membersRemoved": [],
  "reactionsAdded": [],
  "reactionsRemoved": [],
  "locale": "en-US",
  "text": "Hi cirrus.twin, here's the data, I'm also sending the email to your mailbox. \r\n- SSO :                   302015572 \r\n- Total Roles :                    303 \r\n****************************************************\r\n",
  "attachments": [],
  "entities": [],
  "replyToId": "2K6WZVjfpl2"
}

Thanks
WeiZhen

**Comment by EricDahlvang** [comment]
Cortana does not currently allow Proactive Messaging.
