### ISSUE TITLE
Language generation, Adaptive expressions, Adaptive dialogs - docs and samples plan

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotBuilder-Samples#2382]
# Lg, adaptive dialog samples plan - R9

## Adaptive expressions
Adaptive expressions are at stable release for both C# and JS

| Current location                                        | Proposed location                                                                                                                                       |
|---------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Documentation: experimental/common-expression-language/ | Documentation: Official bot builder docs. Add a README.md under experimental/common-expression-language/ to point back to stable release docs location. |

## LG
Language generation is at stable release. Here's the planned update to the language generation samples

| Current location                                                                                   | Proposed location                                                                                                                                            |
|----------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| C# samples: experimental/language-generation/csharp_dotnetcore/                                    | C# samples: samples/csharp_dotnetcore/language-generation                                                                                                    |
| JS samples: experimental/language-generation/javascript_nodejs/                                    | JS samples: samples/javascript_nodejs/language-generation                                                                                                    |
| Documentation: experimental/language-generation/README.md & experimental/language-generation/docs/ | Documentation: Official bot builder docs. Add a README.md under experimental/language-generation/ to point back to stable release docs and samples location. |

## Adaptive dialogs
Adaptive dialogs is at stable release for C# and in preview for JS.

| Current location                                                                             | Proposed location                                                                                                                                                                         |
|----------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| C# samples: experimental/adaptive-dialogs/csharp_dotnetcore/                                 | C# samples: samples/csharp_dotnetcore/adaptive-dialog                                                                                                                                     |
| Declarative samples with C# runtime: experimental/adaptive-dialogs/csharp_dotnetcore/        | Declarative samples with C# runtime: samples/csharp_dotnetcore/adaptive-dialog                                                                                                            |
| Declarative samples with JS runtime: N/A                                                     | Declarative samples with JS runtime: experimental/adaptive-dialog/javascript_nodejs, Add a README.md to point back to experimental folder under samples/javascript_nodejs/adaptive-dialog |
| Documentation: experimental/adaptive-dialogs/README.md & experimental/adaptive-dialogs/docs/ | Documentation: Official bot builder docs. Add a README.md under experimental/language-generation/ to point back to stable release docs and samples location.                              |

**Comment by sgellock** [comment]
@vishwacsena I think this looks great.  Given that we are in a matrixed feature situation between the 4 core programming languages, we should make sure that looking at the official docs addresses this.  what do you think about adding a way for a developer to quickly be able to understand if one of these new feature areas is available in their programming language of choice?

**Comment by vishwacsena** [comment]
@sgellock agree. I will make a table that shows clearly what is available across the 4 core programming languages and work with Kamran to add this clarity to the official docs as well. 

@Kaiqb

**Comment by vishwacsena** [comment]
Addressed by the combination of the following PRs 

- Adaptive Expressions - https://github.com/microsoft/BotBuilder-Samples/pull/2400
- Language generation -  https://github.com/microsoft/BotBuilder-Samples/pull/2399
- Adaptive dialogs – C# - https://github.com/microsoft/BotBuilder-Samples/pull/2385
- Adaptive dialogs – JS - https://github.com/microsoft/BotBuilder-Samples/pull/2392
