### ISSUE TITLE
HeroCard Action does not work in MS Teams iOS version 2.0.10

### ISSUE THREAD

**Issue by vunhutien** [microsoft/BotBuilder-Samples#2398]
## Describe the bug
I'm using botframwork to build company bot chat using MS Teams channel, recently after updating iOS Teams version 2.0.10 from Appstore, the herocard action does not work anymore when user tap the button.

My code:
```
            var card = new HeroCard {
                Subtitle = $"You can use below buttons to get started:",
                Buttons = new List<CardAction> () {
                    new CardAction () {
                        Type = ActionTypes.PostBack,
                        Title = "Check in",
                        Text = "Check in",
                        Value = "Check in"
                    },
                    new CardAction () {
                        Type = ActionTypes.PostBack,
                        Title = "Check out",
                        Text = "Check out",
                        Value = "Check out"
                    }
                }
            };

            var activity = MessageFactory.Attachment (card.ToAttachment ());
            await turnContext.SendActivityAsync (activity, cancellationToken);
```

## Expected behavior
When tapping any button, a message will be posted.

## Actual behavior
Button background color was changed, but no message was posted.

## Screenshots
![IMG_1920](https://user-images.githubusercontent.com/37206017/82147892-7805b880-9883-11ea-872c-17701c0b3eb0.PNG)

## Additional context
- Try to change ActionTypes to MessageBack, OpenUrl also won't work.
- This issue is happened only on iOS Teams client, Android, desktop, browser Teams clients are still ok.
- Question also was submitted to Stackoverflow https://stackoverflow.com/questions/61847640/herocard-action-does-not-work-in-ms-teams-ios-from-version-2-0-10-updated-may-8

**Comment by v-kydela** [comment]
@vunhutien - Did you try [`ActionTypes.ImBack`](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#imback)?

**Comment by vunhutien** [comment]
> @vunhutien - Did you try [`ActionTypes.ImBack`](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#imback)?

Yes, also same result.

**Comment by v-kydela** [comment]
Thank you for reporting this, @vunhutien. This sounds like a Teams bug. You can raise the bug through the Teams app itself. This repo is for bugs and feature requests related to the Bot Builder samples. I'm closing this issue now.
