### ISSUE TITLE
Luis Sample error "500 InternalServerError {"message":  "an error has occured."}

### ISSUE THREAD

**Issue by daschdasch** [Microsoft/BotBuilder-Samples#24]
Hi,

when running the Luis sample, i get the above response after sending a message through the Emulator.
This happens in all Code where i use the LuisDialog. All other samples work. Luis seems to be the Problem...
Can you help me?

**Comment by kgrashad** [comment]
Which version are you trying (C# or Node)?

**Comment by daschdasch** [comment]
my Firewall was the problem

**Comment by willportnoy** [comment]
Thank you for the update.  I'm going to close this issue, but feel free to open a new issue for further discussion.
