### ISSUE TITLE
Skills Simple Bot to Bot NodeJS version does not work

### ISSUE THREAD

**Issue by vslum78** [microsoft/BotBuilder-Samples#2401]
## Sample information
1. Sample type: \samples\javascript_nodejs\80.skills-simple-bot-to-botuestions. 
2. Sample language: nodejs
3. Sample name: 80.skills-simple-bot-to-bot

## Describe the bug
The simple root boot seems to be sending an incorrect conversation Id to the skill bot, causing the skill bot unable respond back to the simple root bot.  This does not seem to be happening with the CSharp version of the sample.  

Connecting a CSharp root bot to a CSharp echo skill bot works
Connecting a CSharp root bot to a NodeJS echo skill bot works
Connecting a NodeJS root bot to a NodeJS echo skill bot does not work
Connecting a NodeJS root bot to a CSharp echo skill bot does not work

The echo skill bot will throw the following error when a NodeJS root bot is used 
` [onTurnError] Exception caught in sendEoCToParent: Error: /api/messages/api/skills/v3/conversations/eb2e388f-58f1-4182-b04e-ad1d35244622-aaebe6ed-b0ee-4487-92b7-798c7ea17325-fc9260e0-966b-11ea-9510-8344e3862407%7Clivechat-emulator-skillconvo/activities/00751950-966c-11ea-9f88-838c9883d7bc does not exist`

## To Reproduce
1. Deploy the NodeJS Simple Root Bot
2. Deploy the NodejS Echo Skill Bot
3. Test the Simple Root Bot from Web Chat
4. Type in 'skill' to get patched through to the Echo Skill Bot
5. Notice that no response ever comes back
6. Check the logs for the Echo Skill Bot.  One should see the above mentioned "onTurnError"

## Expected behavior
When the Simple Root bot sends an activity to the Echo Skill bot, the Skill bot should respond and offer the user a chance to end the conversation and go back to the root bot.  Please see image

![image](https://user-images.githubusercontent.com/56471570/82171874-0ec18c00-98fb-11ea-86d2-19d78fdebbf1.png)

**Comment by gabog** [comment]
Hi @vslum78, I tried running the sample locally and it works for me, are you experience the issue just when the bot is deployed to azure or it also happens locally?

**Comment by vslum78** [comment]
Hi,
I am experiencing this issue when the bot is deployed to both Azure and running locally.  If the sample is working for you, then it could be something is not right with my root bot. I'll try to reclone from Git and run another instance.
Thank You
    On Wednesday, 20 May 2020, 08:29:56 GMT+8, Gabo Gilabert <notifications@github.com> wrote:  
 
 


Hi @vslum78, I tried running the sample locally and it works for me, are you experience the issue just when the bot is deployed to azure or it also happens locally?

**Comment by gabog** [comment]
I also tested deploying the bots and they work in azure. 
Make sure that AllowedCallers is set to `"*"` or the appId of the simple-root-bot (`"*"` lets any request in without validation, a comma separated list of AppId2 allows only requests from specific bots).

Let us know how it goes.

**Comment by vslum78** [comment]
I just recloned the sample and am happy to report that the NodeJS Javascript version of the simple-bot-to-bot is now working for me.  I even recompiled and redeployed the previous cloned version of the NodeJS Javascript version of the sample and it is also working.

Although I am unable to explain what made it work, I am just happy it is and can now move on to further development.

**Comment by gabog** [comment]
Thanks for confirming @vslum78, just in case, I created a PR so AllowedCallers is set to `*` by default in the sample.
