### ISSUE TITLE
[Node] LUISActionBinding - Questions about "message" (schema): localization and choices ?

### ISSUE THREAD

**Issue by NejibK** [Microsoft/BotBuilder-Samples#241]
Hi,
I am using the LUISActionBinding feature for my bot (**Node.js**) and I have some questions about the "message" within the schema:

```
var MyIntent = {
    intentName: 'MyIntent',
    friendlyName: 'MyIntent', 
    confirmOnContextSwitch: false,
    schema: {
        MyEntity: {
            type: 'string',
            optional: false,
// the message below:
            message: 'Can you answer this question to validate the action ?'
        },
    }
```

### Q1: 
Message is by default a string. Is it possible to have/add a localization ?
The message is written in English and although my bot is able to handle the messages sent by the user in German or French, the questions asked by the bot should be provided also in the user's locale without having to use the translation API since it would generate unnecessary costs.
- I tried something like:
`message: {en: 'Question in English', de: 'Question in German'}`
but it didn't work.
- I also tried using localization files (folders _locale > en > index.json_ and _locale > de > index.json_) but although the localization works within the app.js file, it did not work in the ActionBinding.
Am I doing something wrong or it has not been implemented (yet) ?

### Q2: 
In case the functionality is not implemented, what should be modified and how to allow the localization ?

### Q3:
Is it possible to prompt choices for the user and not only a simple message ?

Thanks in advance for your help :)

**Comment by NejibK** [comment]
@pcostantini, @Stevenic can you please have a look at my questions ?
Thanks !

**Comment by NejibK** [comment]
Issue solved
#### Q1
The localization files (index.json) have to be stored in the folder _bot > locale > en >_
#### Q2
Not relevant anymore
#### Q3
Yes but it requires changing adding a new property in the schema (core > index.d.ts) (whithin export interface ISchemaParameter), then do some changes in the core > index.js file:
- `builder.Prompts.text` -> `builder.Prompts.choice`
- passing the "choices" property of the schema as choices within actionModel.parameterErrors in the tryExecute function
- changing the line `actionModel.userInput = userInput ? userInput.trim() : null;` to
```
if(typeof userInput === 'string'){
            actionModel.userInput = userInput ? userInput.trim() : null;
        }else{
            actionModel.userInput = userInput.entity;
        }
```
This has been tested only on the bot. I did not test web and console yet.

**Comment by NejibK** [comment]
Well there is still something open: localization of choices.
Example:
```
var salesData = {
    "west": {
        units: 200,
        total: "$6,000"
    },
    "central": {
        units: 100,
        total: "$3,000"
    },
    "east": {
        units: 300,
        total: "$9,000"
    }
};

bot.dialog('b', [
    function (session) {
        
        builder.Prompts.choice(session, "Which region would you like sales for?", salesData, { listStyle: 3 }); 
    },
    function (session, results) {
        if (results.response) {
            var region = salesData[results.response.entity];
            session.send(`We sold ${region.units} units for a total of ${region.total}.`); 
        } else {
            session.send("OK");
        }
    }
]);
```
Is it somehow possible to do the following:
 _locale >en > index.json_ 
`{"west": "English translation of west"}`
 _locale >de > index.json_ 
`{"west": "German translation of west"}`

When the user has to select the region, he wouldn't see `west` as a choice option but `English translation of west` or `German translation of west` depeding on his locale.
Thanks in advance !

**Comment by goncharov-do** [comment]
I also need a solution to use PromptDialog.Choice with options in LUISActionBinding (C#)

**Comment by EricDahlvang** [comment]
Localization of prompts in node Bot Builder V3 is explained here: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-localization?view=azure-bot-service-3.0#localize-prompts

The LuisActionBinding library is now in this repository: https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/CSharp/Samples/LuisActions
