### ISSUE TITLE
QnA Maker: Unandled Exception

### ISSUE THREAD

**Issue by pankaj-pal** [microsoft/BotBuilder-Samples#2417]
## Sample information
1. Sample type: QnA Maker
2. Sample language: nodejs
3. Sample name: 11.QnA Maker

## Describe the bug
QnA Maker sample throwing error

 [onTurnError] unhandled error: TypeError: Cannot read property 'map' of undefined

## To Reproduce
1.) npm install for QnA Maker.
2.) Setup the environment
3.) Ask any quetion

## Expected behavior
It should give answer from my QnA Bot

[bug]

**Comment by benbrown** [comment]
@pchoudhari can you take a look at this issue please?

**Comment by pankaj-pal** [comment]
Hello Team,

I was giving environment variables (.env file) with quotes. Removing quotes fixed it.
