### ISSUE TITLE
Is the handoff protocol and EventFactory only for the dotnet library or does javascript have these protocols too?

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotBuilder-Samples#2418]
For the sample [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library#protocol), I am wondering if the same can be done in javascript/nodejs?

**Comment by benbrown** [comment]
Yes, the event factory does exist in Javascript!

https://docs.microsoft.com/en-us/javascript/api/botbuilder/eventfactory?view=botbuilder-ts-latest#createhandoffinitiation-turncontext--any--transcript-
