### ISSUE TITLE
Teams Bot: Get message's read receipts from Microsoft teams

### ISSUE THREAD

**Issue by SathishNeel** [microsoft/BotBuilder-Samples#2423]
** we have scenario to show message/card based on user's last seen message. how to pull messages read receipts.

**Comment by benbrown** [comment]
Hey @clearab, is there a way to get the read receipts?

**Comment by clearab** [comment]
Currently there is no way for a bot to receive read receipts as events. You can see the list of events a bot will receive here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet.

If you're interested in this being added to a future release of Teams, please submit it as a feature request on uservoice: https://microsoftteams.uservoice.com/
