### ISSUE TITLE
VSIX Bug: GetManifestResourceStream does not work well with $safeprojectname$

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#2427]
Project names with multiple . or other special characters will have issues with:

```cs
var cardResourcePath = "$safeprojectname$.Cards.welcomeCard.json";
using (var stream = GetType().Assembly.GetManifestResourceStream(cardResourcePath))
```

https://github.com/microsoft/BotBuilder-Samples/blob/master/generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot-Core21/Bots/DialogAndWelcomeBot.cs#L45

[bug]

**Comment by BruceHaley** [comment]
My repro: Created a Core Bot (without test) for Core 2.1 named CoreBot4.9.1-2.1c.

**Comment by EricDahlvang** [comment]
One way to fix this is to change:
`var cardResourcePath = "$safeprojectname$.Cards.welcomeCard.json";`

to:
`var cardResourcePath = GetType().Assembly.GetManifestResourceNames().First(name => name.EndsWith("welcomeCard.json"));`
