### ISSUE TITLE
Lack of parity in scaleout BlobStore class (C# vs Python)

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#2435]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore,ptyhon]
3. Sample name: 42.scaleout

## Describe the bug
In C#, `BlobStore.SaveAsync` returns true or false, depending on whether the write with ETag succeeds. In Python, `BlobStore.save` always returns true.

## To Reproduce
1. Compare the two implementations of the save operation:
   - [C#](https://github.com/microsoft/BotBuilder-Samples/blob/0371c5a13c9c82b10dc0c61ee048a12c10c3bad6/samples/csharp_dotnetcore/42.scaleout/BlobStore.cs#L67-L100)
   - [Python](https://github.com/microsoft/BotBuilder-Samples/blob/0371c5a13c9c82b10dc0c61ee048a12c10c3bad6/samples/python/42.scaleout/store/blob_store.py#L38-L51)
1. Error: note that there appears to be logic missing from the Python implementation.

## Expected behavior
All versions of the sample implement nearly identical behavior [as much as possible].

## Additional context
Opened as part of trying to address doc issue [1717](https://github.com/MicrosoftDocs/bot-docs/issues/1717).
[bug]

**Comment by jwiley84** [comment]
I can look into this. There's something else I was looking at for this sample concerning it's dependencies.

**Comment by ramfattah** [comment]
Closing this issue.

The SDK Team is planning to retire the Bot Framework Python SDK. 
No new features, but we'll cover critical fixes until then. 

For new bots, give Power Virtual Agents or Bot Framework's C# or JavaScript SDKs a whirl. They're our go-to now.

Cheers!
