### ISSUE TITLE
Sample 49.qnamaker-all-features cognitive model doesn't match features

### ISSUE THREAD

**Issue by diberry** [microsoft/BotBuilder-Samples#2439]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore and javascript_nodejs
3. Sample name: 49.qnamaker-all-features 

## Describe the bug
The code supports follow-up conversational prompts but the prompts are not supplied in the cognitive model file. 

## Expected behavior
Expect features in code to be supported with cognitive model, where applicable. 

[bug]

**Comment by gandiddi** [comment]
This QnAMaker sample no longer work because the services they depend upon have been discontinued or are not allowing new resources and endpoints to be created.
QnAMaker sample is updated with Custom question answering samples, hence closing the issue.
