### ISSUE TITLE
Record Skype for business calls using API/SDK

### ISSUE THREAD

**Issue by ashokbn** [Microsoft/BotBuilder-Samples#244]
we are looking for recording audio of skype for business using API/SDK?  
For example, Program should join the meeting on behalf of the virtual user and record the audio and then convert audio to text format.  Is there also possiblity to capture audio of meeting at regular intervals(1 minutes) .

**Comment by sgellock** [comment]
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework
