### ISSUE TITLE
Application hosted media calling bot which proactively messages aswell.

### ISSUE THREAD

**Issue by charliewatkinson** [microsoft/BotBuilder-Samples#2465]
Trying to develop an application hosted media calling bot which when it joins an online meeting it can type a welcome message in the call chat. 

The purpose of the bot is to record calls so I shall be use the updaterecordingstatus api and I want it to type a warning in the call/meeting chat window.

Finding not many good samples on the Microsoftgraphcomms repo...

**Comment by tracyboehrer** [comment]
@charliewatkinson Can you provide more information on what you are trying to do, or where we could help?  We are a little unclear and want to make sure we get you the right help.

**Comment by charliewatkinson** [comment]
When my bot joins the call, I want it to type a message in the meeting chat window (where all participants can see).
Haven't found any information on how to do this.

**Comment by charliewatkinson** [comment]
@tracyboehrer thanks. Keep me updated.

**Comment by clearab** [comment]
You should be able to create a calling/meeting bot and add text capabilities to it. Your bot would need to be installed in the context that you wanted to send the text message to (so someone would have to manually add it to the meeting).

The documentation can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview.

If you have additional questions the Teams developer support group should be able to help, you can contact them in one of the ways listed here: https://aka.ms/teamsdevfeedback.
