### ISSUE TITLE
microsoft teams bot tab and notification

### ISSUE THREAD

**Issue by MarwaAbuEssa** [microsoft/BotBuilder-Samples#2468]
If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
HI ,
I'm using your nodejs botbuilder v4 to create a notification only bot and add it to microsoft teams app . when an event occurs at our Backend API it sends to /api/notify which will send a proactive message to bot at our app in microsoft teams app and it works ! .

my questions is :

-  When sending more than one message to the bot , only one notification is displaying at microsoft app and chat channel , is there anyway to increment notification red badge for every proactive message sent to the bot even though if needed to change message type?
 ![image](https://user-images.githubusercontent.com/7272394/83629339-33279480-a59a-11ea-88e6-528b4c2fef55.png)

- is there anyway to hide/remove/replace the activity tab from my custom app?
 ![image](https://user-images.githubusercontent.com/7272394/83629487-784bc680-a59a-11ea-8d49-c38c5a8e9e53.png)

- our api send to the the /api/notify depending on certain condition to a certain user , the bot sends the proactive message to all users installing the microsoft teams app, i need it to sent to only one user who meets certain condition.?

Regards ,
Marwa

**Comment by clearab** [comment]
Hi -

- The notification counter is controlled by the Teams client, your app will have no direct control over it.
- No, the Activity tab is where any messages your bot sends to a single user will appear. It cannot be removed.
- I'm not sure I understand the question for the third one. Every message you send from your bot will go to a single conversation based on the conversation Id you use.

**Comment by clearab** [comment]
If you have further questions specific to Teams, please feel free to reach out to the Teams development support team directly using one of the methods outlined at https://aka.ms/teamsdevfeedback.

**Comment by MarwaAbuEssa** [comment]
Hi @clearab , 

Thanks a lot for your quick reply , really appreciate .

my third question is i'm using your nodejs botbuilder sample for proactive message . it sends a proactive  notification succesfully to users . i'm hosting /api/notify using ngrok which i use to send the messages . when member added it starts a converstaion and the notification continue sending succesfully . now when i restart my ngrok (which runs my bot app), the notification is stopping !! as i found out the code using ` await adapter.continueConversation` .and i found that to continue converstaion to bot , user must send a message to bot to start a conversation . my bot is going to be a notification only bot , so my question now is how to send a proactive message to a notification only bot to a certain user (by creating a converstaion if not exists ) and not stop even if i restarted my bot app ngrok.

Regrads ,
Marwa

**Comment by clearab** [comment]
Ah, ok. You can use `createConversationAsync` to create a new one-to-one chat (assuming you have the correct Id's). I have an example of doing so here: https://github.com/clearab/teamsProactiveMessaging/blob/master/MessageSender.cs

**Comment by MarwaAbuEssa** [comment]
thanks a lot for your help , really appreciate
