### ISSUE TITLE
EchoBot-Adaptive sample: Need to pass in the resource object when creating the DialogManager

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotBuilder-Samples#2479]
The JavaScript version of the EchoBot-Adaptive sample:

The [loadRootDialog()](https://github.com/microsoft/BotBuilder-Samples/blob/d4b72fd01aa5a8606d8ed68e4334f008e02c7600/experimental/adaptive-dialog/javascript_nodejs/20.echo-bot-declarative/index.js#L72) function should pass in the `AdaptiveDialog` resource object when creating the DialogManager. The DialogManager [constructor](https://github.com/microsoft/botbuilder-js/blob/e67d6a8eca01c31b7b8f17a5023bf7451ea27287/libraries/botbuilder-dialogs/src/dialogManager.ts#L59) accepts the rootDialog as its first parameter. This would also be consistent with how the C# sample is implemented.

Here is how the `AdaptiveDialog` object is passed into the `DialogManager` in JS in the EchoBot sample currently:

```javascript
let myBot;
const loadRootDialog = () => {
    let rootDialogResource = resourceExplorer.getResource('echo.dialog');
    myBot = new DialogManager();
    ...
    myBot.rootDialog = resourceExplorer.loadType(rootDialogResource);
}
```
 
Suggested change:

```javascript
let myBot;

const loadRootDialog = () => {
    let resource = resourceExplorer.getResource('echo.dialog');
    myBot = new DialogManager(resourceExplorer.loadType(resource));
}
```

**Comment by vishwacsena** [comment]
Addressed via #2478
