### ISSUE TITLE
Acquire Using behavior

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2483]
Hi, I know it's wrong place for the general questions but I can't get answer on stackoverflow or Azure portal support.
I see that Teams Bot have `Acquire Using` field in the product description. But I can't find any place where the behavior of this field is described. If I understand it correctly Teams app can be used with both personal and business accounts. So it looks like `Acquire Using` limits usage to only business account but I don't see anything about that in the [manifest documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema). I also found that mostly all apps in the store requires `Work or school account`, e.g. [Stackoverflow app](https://appsource.microsoft.com/en-us/product/office/WA200000739) but I found couple apps which also allow `Microsoft account`, e.g. [Salesforce app](https://appsource.microsoft.com/en-us/product/office/WA104379334?tab=Overview). Does Microsoft account stands for personal?
So what does it mean and how can I change the requirements?

Stackoverflow question: https://stackoverflow.com/questions/62154460/teams-bot-acquire-using

**Comment by clearab** [comment]
Where are you seeing this property? Can you share an example?

**Comment by GDreyV** [comment]
![image](https://user-images.githubusercontent.com/6262948/83912204-6f462b00-a73b-11ea-867d-7934a6e2ffb7.png)

**Comment by GDreyV** [comment]
Just got a call from Microsoft Partner support center. If I got it right this field is set by certification team and by design all Team applications requires Business or School account. Salesforce in the first post belongs to Outlook applications which is different class of applications and it's possible to choose who can use it.
So in a nutshell it's kind of business decision to limit all Teams applications only to business or school account. Also if got it right again it's not kind of documented limitation but just an internal rule.
