### ISSUE TITLE
notification only bot is not working properly on iphone

### ISSUE THREAD

**Issue by MarwaAbuEssa** [microsoft/BotBuilder-Samples#2486]
Hi ,
I'm using your sample for nodejs botframework v4

i want the bot to be a notification only bot so i had an activity tab not a chat .
it sends a proactive messages on a certain event at our api via /api/notify end point and it is working successfully at desktop , web and android mobile .

the issue is at Iphone , if the bot is a notification only , i don't get a notification if the mobile screen is locked and no red badge at chat tab . also i can't find the bot icon at the top bar of the app too.

if I enabled the bot to send (chat not activity) , the notification displays at iphone screen lock and the bot icon is visible at the top bar of app and the red badge is working too at chat tab.

please see photo below for the difference

![without](https://user-images.githubusercontent.com/7272394/83948554-56fb0c80-a81e-11ea-8308-9701de861183.png)
![with](https://user-images.githubusercontent.com/7272394/83948555-5793a300-a81e-11ea-9f01-a9efeabe2741.png)

please this issue is so urgent for me if you can help as fast as possible

Regards,
Marwa

**Comment by mdrichardson** [comment]
@MarwaAbuEssa Since this only happens on one Teams client and the issue is UI-specific, this is a Teams issue and not a Bot Framework one. Please open a ticket on the [Teams UserVoice](https://microsoftteams.uservoice.com/forums/908686-bug-reports)
