### ISSUE TITLE
The type or namespace name 'Integration' does not exist in the namespace 'Autofac'

### ISSUE THREAD

**Issue by lvmmth** [Microsoft/BotBuilder-Samples#250]
I just modified my bot following your document. Did I miss something? I'm getting this error:

_Global.asax.cs(9,15): error CS0234: **The type or namespace name 'Integration' does not exist in the namespace 'Autofac' (are you missing an assembly reference?)** [D:\home\site\wwwroot\Microsoft.Bot.Sample.SimpleEchoBot.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\wwwroot\.\Microsoft.Bot.Sample.SimpleEchoBot.csproj" /nologo /verbosity:m /t:Build /p:AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\wwwroot\.\.\\"
An error has occurred during web site deployment._

Thank you in advance.
Joy.

**Comment by mageakos** [comment]
hey, You just need to add a NuGet package reference of  Autofac.WebApi or  Autofac.WebApi2! 
You can check the documentation here, http://autofaccn.readthedocs.io/en/latest/integration/webapi.html

**Comment by CoHealer** [comment]
Resolved, answer provided
