### ISSUE TITLE
Document + Samples for mentioning user by UPN/AAD Obj ID

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2501]
Teams is adding support for @mentioning users by UPN & AAD Object Id in both chat and Adaptive Cards, we'll need to update the conversation sample to demonstrate this functionality, and document it.

Minimally docs should be within R10.  Blocked until Teams feature is in production.

**Comment by cleemullins** [comment]
per @tacri this is still blocked. ETA in ~Sept 2020.
