### ISSUE TITLE
FTP: The remote server returned an error: (530) Not logged in.

### ISSUE THREAD

**Issue by rajeshyalamarthi** [microsoft/BotBuilder-Samples#2504]
Hi, here I am using FTP in order to fetch the files from azure app service and to display files. When I'm trying to run code locally it is working fine. But when I published the code in azure app service there it is throwing " **The remote server returned an error: (530) Not logged in."** exception.

**Comment by vishwacsena** [comment]
@rajeshyalamarthi can you please open a bug with repro steps? This seems too generic and vague to be actionable.
