### ISSUE TITLE
VS Wizard (VSIX) - Core Bot with Tests generates file with inconsistent cases cause build to fail on UBUNTU

### ISSUE THREAD

**Issue by jbinko** [microsoft/BotBuilder-Samples#2505]
With VS Wizard generate sample based on option Core Bot with Tests.
It creates physical file with wrong casing: FlightFromParisTo**n**ewYork.json
On UNIX based file systems it fails with errors in files:

    \MyBot.Tests\Dialogs\MainDialogTests.cs
    [InlineData("FlightFromParisToNewYork.json", "BookingDialog mock invoked")]

    MyBot.Tests.csproj
    <None Remove="Dialogs\TestData\FlightFromParisToNewYork.json" />
    <EmbeddedResource Include="Dialogs\TestData\FlightFromParisToNewYork.json" />

**Comment by EricDahlvang** [comment]
@jbinko thank you for raising this issue. We've fixed the source, and will update the VSIX with the next release.
