### ISSUE TITLE
[intelligence-LUIS] Import New App error "BadArgument: Version ID cannot be null or empty"

### ISSUE THREAD

**Issue by henriquebp87** [Microsoft/BotBuilder-Samples#251]
I tried to import 'LuisBot.json' file to create a new app on my LUIS account and got the error:
"BadArgument: Version ID cannot be null or empty"
![untitled](https://user-images.githubusercontent.com/6232469/37471323-401ef5f6-2848-11e8-8448-197473052c51.png)

**Comment by tiagozini** [comment]
The same with me.

**Comment by gunjankhanwilkar** [comment]
Add this property "versionId": "0.1" in LuisBot.json file.
This will solve the problem and you will be able to import the file.

**Comment by sgellock** [comment]
closed due to inactivity
