### ISSUE TITLE
Handle all standard JSON schema types and formats

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotBuilder-Samples#2510]
We need to handle all of the built-in JSON schema types without any extra machinery. In particular we need to handle string, number, integer, boolean and array of them.  Most of this should be just doing the root template.  

In addition we need to handle standard formats from here: https://json-schema.org/understanding-json-schema/reference/string.html#format
In particular we should be able to hook-up date-time, time, date, email, regex and uri/iri.  I suspect we will need to change the generator to use the format name as the type rather than just string.  With this change we can make templates that hook-up email to the LUIS email, URI to URL and the date/time ones to datetimev2.

Currently we always generate an if condition for min/max on numbers.  Make the template generation smarter to check at generation time for min/max and only generate the check if present.  We should use the same structure for also checking the pattern regex that can be specified in JSON schema for strings.

We need to update the unittest.schema to include examples of all properties and we should have tests to make sure they are all properly handled.

[enhancement]

**Comment by coldplaying42** [comment]
Does handling all of the built-in JSON schema types without any extra machinery mean that when supporting string, number, integer, boolean and array, we do not need to use extra LG function (e.g., for number type, we do not use max/min functions from LG, but use keywords of json schema types)? What is root template?
