### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/BotBuilder-Samples#2516]
### Github issues for [C#]
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/adaptive-dialog/08.todo-bot-luis-qnamaker

## Describe the bug
cd Dialogs bf luis:cross-train --in . --out ../generated --config DialogLuHierarchy.config.json
- It is unclear where the generated folder should be created as both cd and bf commands are put on the same line. Splitting the command into two, solves the issue.

**Comment by jwiley84** [comment]
I'll put in a PR to fix this. Thank you for bringing it to our attention!

**Comment by jwiley84** [comment]
I'm going to close this. The PR is in, and I don't want to leave you hanging just because I'm waiting for a reviewer. Thank you again for bringing this to our attention!
