### ISSUE TITLE
Create new conversation didn't work

### ISSUE THREAD

**Issue by weizhenzhao** [Microsoft/BotBuilder-Samples#252]
### SDK Platform

.NET
### URL of Code Sample

` public static async Task ResumeAfterCertainMinutes()
        {
            var message = JsonConvert.DeserializeObject<ConversationReference>(conversationReference).GetPostToBotMessage();
            if (!MicrosoftAppCredentials.IsTrustedServiceUrl(message.ServiceUrl))
            {
                MicrosoftAppCredentials.TrustServiceUrl(message.ServiceUrl);
            }
            var client = new ConnectorClient(new Uri(message.ServiceUrl));

            try
            {
                var conversation = await client.Conversations.CreateDirectConversationAsync(message.Recipient, message.From);
                message.Conversation.Id = conversation.Id;
            }
            catch (HttpOperationException ex)
            {
                var reply = message.CreateReply();
                reply.Text = ex.Message;
                Log.WriteLogToTxt(ex.Message);
                await client.Conversations.SendToConversationAsync(reply);
                return;
            }

            using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                var botData = scope.Resolve<IBotData>();
                await botData.LoadAsync(CancellationToken.None);

                //This is our dialog stack
                var task = scope.Resolve<IDialogTask>();

                var child = new WakeUpDialog();

                // wrap it with an additional dialog that will restart the wait for
                // messages from the user once the child dialog has finished
                var interruption = child.Void<object, IMessageActivity>();

                try
                {
                    // put the interrupting dialog on the stack
                    task.Call(interruption, null);

                    // start running the interrupting dialog
                    await task.PollAsync(CancellationToken.None);
                }
                finally
                {
                    // save out the conversation dialog state
                    await botData.FlushAsync(CancellationToken.None);
                }
            }
        }`
### Problem Description

I used this code to start a new conversation to emulator and push a message to emulator
successfully .
but when I deploy this code to the skypeforbusiness it goes wrong 
and with the error message as blow:

begin to push message to user
---------------------------------------
V5.7.7.7 Record On : 3/17/2018 2:18:17 AM 
---------------------------------------

A 504 (Server Time-Out) response was received from the network and the operation failed. See the exception details for more information.

**Comment by p0085058** [comment]
My question is doesn't the skypeforbusiness support the StartNewConversation Feature?
If someone can help me, I will be very grateful.

**Comment by sunilsoniudaipur** [comment]
I am able to create the conversation id for the first user, using start conversation method in node js and can receive the conversation id, but issue occurs when the second user connects then I called the start conversation but **it returns the same conversation id and due to that I cannot connect 2 or more users with direct line.** 

     client_manager.Conversations.Conversations_StartConversation()
        .then(function (response) {
            var responseObj = response.obj;
            onRegistrationDone(responseObj,clientWs);
            console.log("2. New Client Registered: "+responseObj.conversationId);
          
        });

**Comment by CoHealer** [comment]
Closing due to age of posting. If you still want help with this issue, please respond and I will reopen.
