### ISSUE TITLE
There's no ./Dialogs/Resources/ToDoBot.lu file

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotBuilder-Samples#2520]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: adaptive-dialog/06.todo-bot

## Describe the bug
The code comment in "BotBuilder-Samples/samples/csharp_dotnetcore/adaptive-dialog/06.todo-bot/Dialogs/RootDialog/RootDialog.cs" says this
// Intent rules for the LUIS model. Each intent here corresponds to an intent defined in ./Dialogs/Resources/ToDoBot.lu file

## Expected behavior
But there's no Resources folder. And I'm actually looking for where the Greeting intent is configured.

[bug]

**Comment by srinaath** [comment]
@vishwacsena  can you take a look at this ticket?

**Comment by vishwacsena** [comment]
Addressed via #2528
