### ISSUE TITLE
Teams Bot Auth: oAuth Card with AADV2 returns expired tokens

### ISSUE THREAD

**Issue by bravokeyl** [microsoft/BotBuilder-Samples#2530]
## Sample information
1. Sample type: **samples**
2. Sample language: **nodejs**
3. Sample name: **46.teams-auth**

## Describe the bug
I'm using sample auth with AADV2 connection and custom scope. The token is not renewed and receiving the expired token.

## To Reproduce
1. Use the 46 sample with AADV2 connection type
2. Set the scopes to be "offline_access" and custom scope like "api://appid/myscope"
3. Try the sample now the token is received 
4. After an hour we also receive the same even though the token is expired

## Expected behavior
 1. We should receive the new token after the previous token is expired.

## Additional context
https://stackoverflow.com/questions/62527519/teams-bot-auth-oauth-card-prompts-for-login-every-hour-with-aadv2

[bug]

**Comment by jwiley84** [comment]
Hi @bravokeyl 

Token handling is not something the bot does; it does not automatically refresh. The OAuth samples are meant to show simple implementation of sign-in and sign-out logic. As you've already asked this question on stackoverflow, I'm going to close this issue, and answer further queries there.

**Comment by bravokeyl** [comment]
@jwiley84 Thanks for the quick response.

I'm confused from the [comments](https://github.com/microsoft/BotBuilder-Samples/blob/93e1cca04512613af7e056caa94b1bbd1a8244b4/samples/javascript_nodejs/46.teams-auth/dialogs/mainDialog.js#L71-L79) in the code. I thought when we call the prompt it returns the new token if the previous token is expired, is my assumption wrong here?

**Comment by pujita9610** [comment]
@jwiley84 Stumbled upon on the same thing today, I'm wondering how we can retreive a new token. 
It would be great to add some notes on how to do that. Currently I can see that there is no way
to renew the token as we just get a hold on accestoken and no refresh token is received.

What are the possible ways to retreive a new token without re-prompting the user with sign-in card?

**Comment by bravokeyl** [comment]
@jwiley84 @pujita9610 Yes, it would be very helpful if there are notes/guidance on how to retrieve a new token with oAuthCard

**Comment by bravokeyl** [comment]
@jwiley84 Any further input on this would be great to retrieve the valid token. Thanks

**Comment by nayanaramakanth** [comment]
Any updates on this issue ?
