### ISSUE TITLE
Address .NET Core 3.1 change around hostingModel default value

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotBuilder-Samples#2531]
## Sample information
1. Sample type: \samples\ 
2. Sample language: dotnetcore
3. Sample name: All dotnetcore samples and generators

## Describe the bug
In .NET Core 3.1, the hosting model default switched from `"outofprocess"` to `"inprocess"` which does not work with DL ASE (which uses `"outofprocess"`). By having a mismatch for the hosting model, the two will never be able to talk to each other.

Per @DDEfromOR, this 3.1 breaking change also results in problems around deploying a DL Token server from the same App Service, so we should investigate and determine the best course of action.

[bug]

**Comment by stevengum** [comment]
Migration docs: [2.2 -> 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#in-process-hosting-model)

**Comment by stevengum** [comment]
After speaking with @Jeffders and @johnataylor, the hostingModel change to `"outofprocess"` would specifically target the Echo and Core bot samples and generators for .NET.

**Comment by stevengum** [comment]
To be explicit, there's a number of changes that need to be performed to make Echo and Core bot work out-of-the-box with minimal customer-driven changes.

### Add logic to Startup.cs/index.js/ts to connect to the NamedPipe

- In Startup.cs, add the [following](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0):
```cs
app.UseNamedPipes(System.Environment.GetEnvironmentVariable("APPSETTING_WEBSITE_SITE_NAME") + ".directline");
```
   - In index.js/ts add the following [logic](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0):

```js
adapter.useNamedPipe(async (context) => {
    await myBot.run(context);
    },
    process.env.APPSETTING_WEBSITE_SITE_NAME + '.directline'
);
```

### .NET: Update hosting process
- For the samples/generators this is just updating the .csproj
- ABS Templates need the web.config updated

### JS/TS: web.config for iisnode
- Complete https://github.com/microsoft/botframework-sdk/issues/6056 to update `az bot prepare-deploy`
- Update ABS templates web.config


### Add appropriate code comments and documentation links in the samples/generators

**Comment by stevengum** [comment]
Samples don't necessarily ship directly in sync with our milestones, this work will likely happen after 4.11 is out the door.

**Comment by gandiddi** [comment]
ASP.NET Core 3.0 or later(Migration docs: [2.2 -> 3.0](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#in-process-hosting-model)) apps hosting model default changed to the [in-process hosting model](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#in-process-hosting-model) to improve performance and simplify deployment.


To configure an app for [out-of-process hosting](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#out-of-process-hosting-model), set the value of the `<AspNetCoreHostingModel>` property to `OutOfProcess` in the project file (.csproj):

```
<PropertyGroup>
  <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
</PropertyGroup>
```
