### ISSUE TITLE
Error initializing DirectLine client TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by lingwangyan** [Microsoft/BotBuilder-Samples#254]
I just change the `var directLineSecret = 'MySecretKey';`
and install in local repository by following command: 
`npm install swagger-client
`
`npm install -g open`
`npm install --save request`
`npm install --save request-promise`
BotBuilder main repository
(https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine)

### URL of Code Sample
(https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/core-DirectLineWebSockets/DirectLineClient/app.js#L32-L45)

### Problem Description
```
Error initializing DirectLine client TypeError: Cannot read property 'add' of un
defined

```
    

`Unhandled rejection TypeError: Cannot read property 'Conversations' of undefined`

**Comment by MilkoKunev** [comment]
Probably the same issue #191

**Comment by lingwangyan** [comment]
@MilkoKunev i run the command that he provided.. but still same error

**Comment by Rigo85** [comment]
hi there, sorry for respond on closed issue, the version of swagger-client that works is "2.1.18".
