### ISSUE TITLE
A sample that integrates LUIS & QnA with the cross training solution and supports multi-turn prompts.

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/BotBuilder-Samples#2543]
Sample 08.todo-bot-luis-qnamaker didn't have support for multi-turn prompts in the .qna file. Other samples support multi-turn prompts in the .qna file.

It would it be easier to work with a sample that extends multi-turn prompt support to sample 08. todo-bot-luis-qnamaker

**Comment by vishwacsena** [comment]
Resolved.
