### ISSUE TITLE
Update documentation regarding LUIS data flowing to QnA Maker & vice versa on cross training.

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/BotBuilder-Samples#2545]
On cross training, luis data flows to QnA Maker & vice versa. It is possible that QnAMaker and LUIS applications for a user are hosted on different locations. We suggest that this be documented for the user to note.

**Comment by Virtual-Josh** [comment]
@DishaAgarwal can you provide more information about what document you're having issues with?

**Comment by DishaAgarwal** [comment]
@Virtual-Josh Hey, There is no particular document that's confusing to me. It is just a suggestion that might be included in docs related to cross training.
