### ISSUE TITLE
This sample "45. state management" redirects to V3 explanation on the bot state 

### ISSUE THREAD

**Issue by geo-msft** [microsoft/BotBuilder-Samples#2550]
## Sample information
1. Sample type: This is rather a documentation issue of that sample. 
2. Sample language: C#
3. Sample name: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/45.state-management 

## Describe the bug
This is rather a doc bug for this sample: 
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/45.state-management
The Further Reading section >> Bot storage directs the user to this V3 docs link 
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0

## To Reproduce
1. Open the link for the sample https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/45.state-management  
2. Go to Further reading section. 
3. Choose the Bot storage link and click on it. 

![image](https://user-images.githubusercontent.com/57954688/85834780-a2109b80-b79c-11ea-9347-c815b8a1df98.png)

4. This link is opened https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0 
That doc is outdated, mentioning the Global.asax and other approaches used in the V3 version. 

## Expected behavior
The Bot storage should direct the user to the actual V4 documentation page about the bot storage & state (and not to the V3 docs). 

## Screenshots

![image](https://user-images.githubusercontent.com/57954688/85835072-1ea37a00-b79d-11ea-8ce0-b41cfd944899.png)

## Additional context
If I press on this here (https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0), I am directed to the main doc page, and not to the desired doc about state and storage. 

![image](https://user-images.githubusercontent.com/57954688/85835140-35e26780-b79d-11ea-9c90-a0958c46edcd.png)

Thank you. 
[bug]

**Comment by jwiley84** [comment]
Hi @geo-msft I'll get the link corrected here, and reach out to the docs team to get their link in the docs fixed. Thanks for bringing this to our attention! Bot State is complicated enough without sending our customers all over creation to find the info!

**Comment by jwiley84** [comment]
We've corrected the sample, and notified the docs team to their issue. Thank you again!
