### ISSUE TITLE
I want to create my own UI  for Directline

### ISSUE THREAD

**Issue by NeetaA** [Microsoft/BotBuilder-Samples#256]
I want to create my own UI for Directline rather than using Botchat.js and Botchat.css
I already did custom UI in Node.js with the use of Socket.io.
Can u please help me to do it in C#.

**Comment by vinayjayaram** [comment]
@NeetaA  could you please share me your custom UI in Node.js with the use of Socket.io?

**Comment by Kartik1607** [comment]
@NeetaA You can fork [webchat](https://github.com/Microsoft/BotFramework-WebChat/) and then modify it to create custom UI for Directline.

**Comment by sgellock** [comment]
Please use Stackoverflow for how-to questions.
https://stackoverflow.com/questions/tagged/botframework
