### ISSUE TITLE
User's data is getting overlapped. User are seeing other user's data in their chat window. 

### ISSUE THREAD

**Issue by careernavigator** [microsoft/BotBuilder-Samples#2563]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore, C#, bot builder SDK]
3. Sample name: <Name of the sample>

## Describe the bug
User's data is getting overlapped. User are seeing other user's data in their chat window. We are using bot builder SDK v4, using cosmos db for state management. PFA code implmementation.

## To Reproduce
This issue comes when many concurrent users access the BOT.

## Expected behavior
User should not see other user's data.

[gitissue.txt](https://github.com/microsoft/BotBuilder-Samples/files/4871229/gitissue.txt)

[bug]

**Comment by v-kydela** [comment]
Thank you for the report, @careernavigator 

Are you using Web Chat?

**Comment by careernavigator** [comment]
Issue resolved. userID parameter was missing in renderWebChat method.
