### ISSUE TITLE
Add instructions to 52.teams-messaging-extensions-search-auth-config/README.md

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#2564]
These instructions, or something similar, should be present in Sample 52 readme.md:

1) run ngrok - point to port 3978
2) add the ngrok url to appsettings.json - SiteUrl
3) create bot framework registration - using ngrok URL
4) add MicrosoftAppId and MicrosoftAppPassword values to appsettings.json
5) add an AAD V2 OAuth Connection Setting 
scopes: email Mail.Read User.Read openid profile User.ReadBasic.All Mail.Send.Shared 
(see https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication)
6) add AAD ConnectionName to appsettings.json
7) update your manifest.json to include the app id from bot framework
8) zip up teams-manifest folder to create a manifest.zip
9) upload manifest.zip to teams (from Apps view click "Upload a custom app")
10) pick your bot from the compose command menu

[enhancement]

**Comment by johnataylor** [comment]
Seems like the sooner we get this in the better. @jwiley84 thanks for picking this up!
I think we should be able to take this straight into master @garypretty might like to comment.

**Comment by jwiley84** [comment]
I'll get a PR out on this this afternoon, unless someone say no. :D
