### ISSUE TITLE
Transform VS Code extension to Language Server Protocol

### ISSUE THREAD

**Issue by cosmicshuai** [microsoft/BotBuilder-Samples#2566]
Our VS code extension now is implemented by the builtin APIs of VS code, such as completion API, diagnostic API, Hover API.
Ref: https://code.visualstudio.com/api/language-extensions/overview#programmatic-language-features

However in Composer, the language features are implemented by Language Server Protocol. 
Ref: https://code.visualstudio.com/api/language-extensions/overview#language-server-protocol
So the issue here is we have to maintain two sets of code which have the same functionalities. 

A desired solution is we tranform the language features in our VS Code extension to language server protocol. After the transformation, it will help us reuse the code more efficiently.

**Comment by boydc2014** [comment]
Can you detail this issue with 1 Context, 2 Issue, 3 Solution
