### ISSUE TITLE
Add NodeJS sample integrating Express for scalability and maintainability

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/BotBuilder-Samples#257]
### SDK Platform
Node SDK

### URL of Code Sample
https://github.com/proyecto26/Bot-Framework/tree/master/src/nodejs

### Problem Description
In a real life project it is important to be able to scale and maintain the code, so I recommend you and I share with you a basic template that you could use to create bots for NodeJS. It would be great to include it as a template on Azure.

**Comment by sgellock** [comment]
we don't plan on adding express permutations of examples. I suggest you reach out to the maintainers of https://github.com/BotBuilderCommunity and see if there's a place this work could live.
