### ISSUE TITLE
Sudden Error in LUIS Dispatch after working normally 

### ISSUE THREAD

**Issue by HebatallaTarek** [microsoft/BotBuilder-Samples#2582]
Hello , 
i use LUIS Dispatch for LUIS apps and QnA , all QnAKnowledgebaseId , "QnAEndpointKey" ,"QnAEndpointHostName , "LuisAppId" , "LuisAPIKey" ,  "LuisAPIHostName"  are provided in appsettings .json and i used to run the project successfully through Emulator , but couple of days ago suddenly  whenever i tried to enter  LUIS intent / QnA entry  i got " Sorry, it looks like something went wrong. "

and in console i got  this  Error 
 "  No such device or address    at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)  at Microsoft.Bot.Builder.AI.Luis.LuisDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisDelegatingHandler.cs:line 31 " 

I tried to search for error but unfortunately i did not find any solution , any advice will help 
Thanks a lot in advance

**Comment by Virtual-Josh** [comment]
@compulim can you route to the correct person? I'm not sure if it's better to go to QnA or LUIS

**Comment by HebatallaTarek** [comment]
@Virtual-Josh  Thanks for your response ,  it's  related to LUIS more

**Comment by compulim** [comment]
@stevkan Please repro this and triage.

**Comment by stevkan** [comment]
@HebatallaTarek,

- Are you using a particular sample or is this something you have put together yourself?
- Can you confirm which version of the C# SDK you are using?
- Does this error occur immediately as the bot spins up or after some action?

**Comment by HebatallaTarek** [comment]
@stevkan  Hello , Thanks for response
1) the initial start was Dispatch sample but i added more features later 
2) i am using Bot Framework SDK V4 and Asp.Net Core V 2.1 on VsCode 
3 ) i am not sure if i understand the question , but the bot works fine for about 6 months and in one of testing trials through emulator this issue occurred whenever i entered query to be detected using dispatcher 
4) the issue in local running on emulator yes during development process  , i have no idea about drive :d directory i am using Linux machine

**Comment by stevkan** [comment]
> i am using Bot Framework SDK V4 and Asp.Net Core V 2.1 on VsCode

For the SDK, can you list the specific version (4.8.0, 4.9.0, 4.9.1, etc.)?
For .NET Core, can you also (try and) upgrade to v3.1? I don't think this is the issue, however the listed [prerequisite](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0&tabs=vs) is v3.1. It may make a difference.

> * Does this error occur immediately as the bot spins up or after some action?

>  i am not sure if i understand the question , but the bot works fine for about 6 months and in one of testing trials through emulator this issue occurred whenever i entered query to be detected using dispatcher

What I mean is, does this occur as the conversation first starts up between the bot and the user? Or, does it only occur as certain text is passed in or during specific parts of the dialog?

I forgot to ask, which version of Dispatch, Linux, and Emulator are you also running?

So far, I am unable to repro the issue but I will continue to test.

**Comment by HebatallaTarek** [comment]
@stevkan  Thanks for response 
- SDK is V 4.5.1 i will try to upgrade .Net Core but i am not sure if it will work 
- No it does not occur at initial start up it happen when i enter a query that will be detected using Dispatcher 
- I do not know the Dispatch versions i got it from here 
https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch

- It's Ubuntu 16.04 and Emulator V 4.9.0

**Comment by stevkan** [comment]
Ok, I will begin attempting to repro this.

> I do not know the Dispatch versions

You can type `dispatch -v` in a console which should give you the version.

**Comment by HebatallaTarek** [comment]
@stevkan  Thanks for your response , i tried command  dispatch version is :  1.6.8

**Comment by daveta** [comment]
@stevkan : Is there an updated status on this?

**Comment by stevkan** [comment]
@HebatallaTarek, thank you for your patience. I am having some difficulty in repro'ing this issue, however, I am also having a slight issue with Ubuntu. I am continuing to work on this and will keep you updated.

In the mean time, could you verify that this is still an issue for you? Also, a bit of a side question: Are you running this in a pure Linux environment, in a Docker image, VM, or something else?

**Comment by HebatallaTarek** [comment]
@stevKan sorry to hear that but  yes it's still not working ,  i am working on Ubuntu 16.04

**Comment by stevkan** [comment]
@HebatallaTarek, thank you for your continued patience. I'm still working on trying to repro and identify the cause. I hope to have an update to you soon. I will keep you posted.

**Comment by stevkan** [comment]
@HebatallaTarek, I appreciate your continued patience while I work on this. Despite several issues I've had to work around, I hope to have a response back to you today or tomorrow.

**Comment by HebatallaTarek** [comment]
> @HebatallaTarek, I appreciate your continued patience while I work on this. Despite several issues I've had to work around, I hope to have a response back to you today or tomorrow.

Sounds Great , Thanks a lot @stevkan  for your efforts to support

**Comment by stevkan** [comment]
@

> > @HebatallaTarek, I appreciate your continued patience while I work on this. Despite several issues I've had to work around, I hope to have a response back to you today or tomorrow.
> 
> Sounds Great , Thanks a lot @stevkan for your efforts to support

@HebatallaTarek, I have asked a colleague of mine, @dmvtech, to assist on this. I thought I was in a good place, but Ubuntu continues to present issues for me which is taking away from help being provided to you on the actual issue.

He will reach out with any additional questions, otherwise expect him to continue to research the issue.

**Comment by dmvtech** [comment]
I might have a repro, or am close to one. When you say you got that error in the **console**, do you mean the Visual Studio Code console? (and was it in `Problems`, `Output`, `Debug Console` or `Terminal` tab?)

I recieved this in the Terminal tab:
```
Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      Exception caught : Resource temporarily unavailable
```

I am investigating.

Also, did you receive the "Sorry, something went wrong" message only or did you also get the following message: "To run this sample make sure you have the LUIS and QnA models deployed."

**Comment by HebatallaTarek** [comment]
> I might have a repro, or am close to one. When you say you got that error in the **console**, do you mean the Visual Studio Code console? (and was it in `Problems`, `Output`, `Debug Console` or `Terminal` tab?)
> 
> I received this in the Terminal tab:
> 
> ```
> Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
>       Exception caught : Resource temporarily unavailable
> ```
> 
> I am investigating.
> 
> Also, did you receive the "Sorry, something went wrong" message only or did you also get the following message: "To run this sample make sure you have the LUIS and QnA models deployed."
@dmvtech  Thanks for you response  , it was in Terminal Tab 
No i only received sorry something went wrong in emulator

**Comment by dmvtech** [comment]
Thanks @HebatallaTarek I'm investigating and will send update asap.

**Comment by tdurnford** [comment]
@dmvtech Any updates to report?

**Comment by dmvtech** [comment]
Hi @HebatallaTarek Sorry for the delay. I just couldn't get this reproduced in Linux (didn't reach success or failure).

Are you able to run either of the following commands on your dispatch file to see what they result in?:

`dispatch eval`


`dispatch test`

Here is info on eval:
https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#evaluating-your-dispatch-model

Here is info on test:
https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#testing-your-dispatch-model
You will need to add a .tsv for test with some sample utterances.

**Comment by HebatallaTarek** [comment]
> Hi @HebatallaTarek Sorry for the delay. I just couldn't get this reproduced in Linux (didn't reach success or failure).
> 
> Are you able to run either of the following commands on your dispatch file to see what they result in?:
> 
> `dispatch eval`
> 
> `dispatch test`
> 
> Here is info on eval:
> https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#evaluating-your-dispatch-model
> 
> Here is info on test:
> https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#testing-your-dispatch-model
> You will need to add a .tsv for test with some sample utterances.

@dmvtech  Thanks a lot for return back , okay i will try these commands

**Comment by HebatallaTarek** [comment]
Thanks a lot  for your efforts it worked fine now
