### ISSUE TITLE
Change to DefaultNoAnswer not reflected in bot's response

### ISSUE THREAD

**Issue by sahithikkss** [microsoft/BotBuilder-Samples#2588]
https://github.com/microsoft/BotBuilder-Samples/blob/0148be5cd5d3fc062a1ef71625079cac481dff30/samples/javascript_nodejs/49.qnamaker-all-features/dialogs/qnamakerBaseDialog.js#L31

Note that there is no static member `DefaultNoAnswer ` in `ActivityFactory`

~~var noAnswer = ActivityFactory.DefaultNoAnswer;~~
To fix the issue, use the below line 
`        var noAnswer = ActivityFactory.fromObject(DefaultNoAnswer);`

And change the  `DefaultNoAnswer ` in the line 15.
`const DefaultNoAnswer = 'I cannot answer this question.';`

**Comment by compulim** [comment]
@pchoudhari Could you take a look at this? Looks like the sample are having some issues and may not run at all.

**Comment by pchoudhari** [comment]
@sahithikkss is tracking to fix this in the samples.

**Comment by EricDahlvang** [comment]
@pchoudhari or @sahithikkss   could you please provide a status update for this issue.

**Comment by pchoudhari** [comment]
This is an internal reported issue. Will be picked up in the next sprint.
