### ISSUE TITLE
Adaptive Card Samples are outdated

### ISSUE THREAD

**Issue by arashberlin** [Microsoft/BotBuilder-Samples#259]
**The samples on the official BotBuilder Sample Github page are outdated:** 
[https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards)

**Comment by DanDev33** [comment]
The current BotBuilder Sample code uses 5 adaptive card samples that can be found here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/07.using-adaptive-cards/Resources
Additional up to date adaptive card samples can be found at: https://adaptivecards.io/samples/
