### ISSUE TITLE
Buttons text is limited in slack coversation

### ISSUE THREAD

**Issue by kittu610** [microsoft/BotBuilder-Samples#2597]
Hi

i have using some buttons actions in my slack bot 

If buttons have some bigger button text they are not getting displayed fully. 
please find the below attached screenshot.

![image](https://user-images.githubusercontent.com/49742373/87766282-85fd9880-c836-11ea-8413-06625d9ef5c7.png)

Is there any option to display full button text (or) is there any option like tool tip (or) is there any thing we can do please suggest me

**Comment by v-kydela** [comment]
@kittu610 - This is a limitation in each individual Slack client and is out of our control. All channels have limitations for how long button titles can be, and we recommend keeping your titles shorter than 20 characters. You might try sending a numbered list before the buttons if you need more room to explain what each button does, and then the button titles could just be 1, 2, etc.

I'm closing this issue now.
