### ISSUE TITLE
onTeamsMemberAddedEvent() not working for personal scope

### ISSUE THREAD

**Issue by madhvimit123** [microsoft/BotBuilder-Samples#2599]
I was using Microsoft graph API for installing the bot for a user https://graph.microsoft.com/beta/users/{userID}/teamwork/installedApps

On installing the bot, onTeamsMemberAddedEvent() was called for the personal scope as well as for teams scope and through that, I was sending the welcome message to the users. 
Apart from graph api, I was also installing the bot directly and the function was getting invoked.

But now, this event is not getting called and I am unable to get conversationId from the personal scope of a user. It is working for teamscope only.

**Comment by compulim** [comment]
@EricDahlvang could you take a look?

**Comment by EricDahlvang** [comment]
Teams bots installed into a personal scope only receive one notice.  Uninstalling/re-installing will not generate a new one.  This does make testing personal scope welcome messages difficult, but this is a known restriction.  The only workaround I know of to test this is to create a new bot registration.

**Comment by madhvimit123** [comment]
But I have uninstalled/re-installed the app many a times in personal scope and it worked for me. It was sending the welcome message on every installation before this morning.

**Comment by hardikverma24** [comment]
@EricDahlvang  thanks for your time and thanks for replying to us. What you've said is that bots getting installed in personal scope only receive one notice but me and @madhvimit123  have been doing the same thing i.e. Uninstalling/re-installing from past couple of months for thousands of time but it stopped working today's morning only so this came to us as a wierd issue.

**Comment by hardikverma24** [comment]
@EricDahlvang  it would be really great if you can provide us some other solutions apart from this to get the user's conversation reference without user sending message to the bot. Thank you

**Comment by EricDahlvang** [comment]
Apologies if i'm mistaken and this behavior has changed. I'll ask the Teams team.

There is work planned for InstallationUpdate activity support:
https://github.com/microsoft/botframework-sdk/issues/5959 do you know if your bot is receiving this activity, or any other activity the bot is not expecting? Do you have logging/telemetry enabled?

I will get some clarification on the events, and report back.

**Comment by tacri** [comment]
Some longer time ago we were indeed sending the conversation update only on the first install of a bot in the personal scope. We changed the behavior in the meantime to send the event on each install. Unfortunately, there was a recent change which affected this scenario. The change was rolled back and should be deployed world wide by mid august.

**Comment by cleemullins** [comment]
@madhvimit123 Based on the rollout date of mid-august, I'm closing this out now. If the issue persists past that time period, please re-open this issue.

**Comment by madhvimit123** [comment]
@tacri the issue isn't reolved yet. This function is not getting triggered for personal scope on every installation.

**Comment by madhvimit123** [comment]
@EricDahlvang Is the InstallationUpdate up for use?
