### ISSUE TITLE
Container error when aiohttp module is used in the python application

### ISSUE THREAD

**Issue by v-srkov** [microsoft/BotBuilder-Samples#2602]
Hi,we are getting container error when aiohttp module is used in the python application. While deploying this sample https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/02.echo-bot getting error

Error Details Log
2020-07-16T08:46:12.160Z INFO  - Initiating warmup request to container daq3_0_d68cec48 for site daq3
2020-07-16T08:46:24.589Z ERROR - Container daq3_0_d68cec48 for site daq3 has exited, failing site start
2020-07-16T08:46:24.591Z ERROR - Container daq3_0_d68cec48 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.

We have changed the port also but still getting the same error.

2020-07-20T11:56:49.690Z INFO  - Initiating warmup request to container daq3_0_dc24b9e1 for site daq3
2020-07-20T11:56:53.242Z ERROR - Container daq3_0_dc24b9e1 for site daq3 has exited, failing site start
2020-07-20T11:56:53.250Z ERROR - Container daq3_0_dc24b9e1 didn't respond to HTTP pings on port: 3978, failing site start. See container logs for debugging.
2020-07-20T11:56:53.252Z INFO  - Stopping site daq3 because it failed during startup.

please check and let us know the resolution to address to this issue.

**Comment by jwiley84** [comment]
Hi @v-srkov, couple questions: 
Are you getting this error while deploying, or are you getting it after deployment, while attempting to interact with the bot?
How are you deploying your bot?
Have you made any changes to the requirements.txt?

**Comment by v-srkov** [comment]
Hi @jwiley84 ,Yes we are getting this error after deployment and running the app service.
I have deployed using this link https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp and our customer deployed using pipelines and they are also got the same error. We didnt modify the requirements.txt. Initially I got aiohttpmodule not found error after the deployment and ran the command pip install aiohttp and after this  container error is coming. Thanks.

**Comment by jwiley84** [comment]
Awesome. Some follow up questions: 
Are you deploying using an new, empty Resource Group? (important because you cannot combine Windows and Linux resources in the same RG, so a python bot needs to  be in in it's own RG)

Are you using the command to deploy to new RG, or are you creating the RG manually and using the command to deploy to existing RG? (important because right now there's an issue with the ARM template deployment to new RGs, so an RG needs to be created on Azure, then the command to deploy to existing RG needs to be run).

**Comment by v-srkov** [comment]
HI @jwiley84 , I have created a new resource group manually in the azure first and deployed using template-with-preexisting-rg deployement template. Thanks

**Comment by jwiley84** [comment]
Thank you for the information. I'll try to track down the  root cause.

**Comment by MariaMendietaSpur** [comment]
@jwiley84 Having the same issue. Tried deploying several bots from the python samples. Thanks for looking into it.

**Comment by marcsand** [comment]
@jwiley84 - any chance you have an update on this issue?  Thanks.

**Comment by Wajeed-msft** [comment]
@EricDahlvang - Could you please help with updates on this?

**Comment by sgellock** [comment]
@Wajeed-msft we'll put some additional eyes on it this morning and push it forward.

**Comment by mdrichardson** [comment]
@v-srkov 

Based off the errors, it looks like you're deploying as a Docker container.

1. Does the bot work locally, without a Docker container?
2. Does the bot work locally, within a Docker container?

It's a bit tricky to set a bot up with Docker (especially the Python flavor), so I want to make sure it works locally, first.

Here's an example Python Dockerfile:

```dockerfile
# python v3.7.3 is what's in the image, mcr.microsoft.com/dotnet/core/sdk:3.1
FROM python:3.7.3 as bot

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100
RUN pip install --upgrade pip

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install \
    --user \
    --no-warn-script-location \
    --index-url https://test.pypi.org/simple/ \
    --extra-index-url https://pypi.org/simple/ \
    -r requirements.txt

# The build goes significantly quicker if we don't use the alpine version
# due to additional package requirements for python
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

EXPOSE 3978

COPY ./start.sh /start.sh

# Install Python and bot
ENV PATH=/root/.local/bin:$PATH
WORKDIR /app/PythonBot
COPY ./ /app/PythonBot

RUN apt-get update &&\
 apt-get install --no-install-recommends -yqq python3 python3-setuptools

COPY --from=bot /root/.local /root/.local
COPY --from=bot /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages

# Enable SSH for deployed debugging
# This can only be accessed via Azure, so no risk of port exposure
RUN apt-get install -yqq --no-install-recommends openssh-server \
     && echo "root:Docker!" | chpasswd 
COPY sshd_config /etc/ssh/
EXPOSE 2222

CMD ["sh", "/start.sh"]
```

The start script, `start.sh`:

```bash
#!/bin/sh
(ssh-keygen -A && service ssh start) & (cd /app/PythonBot && /usr/bin/python3 -m app)
```

---

The Azure Docker Container Resources tend to provide very little logging, making it difficult to debug. Adding in SSH will allow you to SSH into the container and run the `cd /app/PythonBot && /usr/bin/python3 -m app` to see what errors get output.

Once deployed, **please SSH into the container, run the appropriate python command to start the bot and copy/paste any errors here**.

---

And here's some instructions for deploying a docker container bot:

## Deploy

### Push the Docker Image to a Registry

1. In Azure, [add a Container Registry resource](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/4e5cc492-13dd-48a7-8c0f-fce6c098730c/resourceGroups/ContainerRegistry/overview) (optional if you have your own)
   1. Ensure that you enable "Admin user"
2. Note the link to the registry in Overview > Login server (<registryName>.azurecr.io)
3. [Install Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) (if you haven't already)
4. In a CLI, log into the registry (alternatively, you can use `docker login <registryName>.azurecr.io` with the "Admin user" username and password in your Container Registry Resource > Access keys):

```cmd
az acr login --name <registryName>
```

5. Tag your docker image with your registry (if you haven't done so already):

```cmd
docker tag pythonbot <registryName>.azurecr.io/pythonbot:latest
```

6. Push your built image to the registry:

```cmd
docker push <registryName>.azurecr.io/pythonbot
```

### Create Web App

1. In Azure, [add a Web App for Containers resource](https://ms.portal.azure.com/#blade/Microsoft_Azure_Marketplace/MarketplaceOffersBlade/selectedMenuItemId/home/searchQuery/container%20app%20service)
   * Do not use a Container Instance resource; it is difficult to pull a new image while still retaining the URL/IP Address for the Bot Channels Registration
   1. Under the Basics tab:
      1. Ensure Publish: Docker Container is selected
   2. Under the Docker tab:
      1. Ensure Options > Single Container is selected
      2. Image Source is Azure Container Registry (or your own private registry)
      3. Registry, Image, and Tag match the docker image you pushed
      4. Startup Command is blank
2. Create a [Bot Channels Registration](https://ms.portal.azure.com/#create/Microsoft.BotServiceConnectivityGalleryPackage)
   1. Set the messaging endpoint to your Web App for Containers resource's URL + `/api/messages`. It should look like `https://<myAppService>.azurewebsites.net/api/messages`.
   2. You can get the AppId and password from the [App Registration](https://ms.portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) that this creates. If you need to set a new password, go to the App Registration > Certificates & secrets > New client secret.
3. Once the Web App is created, go to the Configuration pane
   1. Add the following environment variables and their appropriate values:
      1. BotAppId
      2. BotAppPassword
      5. PORT
         * Whatever you set here is what the https requests will get routed to. In this case, we want to set the value to `3978`, the Python Bot.
       * Notes:
         * Capitalization matters. Use exactly as above.
         * If you view Web App > Container Settings > Log, it won't show these environment variables anywhere but rest assured, the docker container *will* get these environment variables.
   2. Save
4. Go to Overview and restart the Web App

### Updating the Running Container

To update the running container in the Web App with a new image, just:

1. Push the new image to your repository
2. Restart the Web App (after ensuring that it is using the correct image and tag)
   1. The Web App automatically pulls the latest image on restart

---

All of that being said, I highly highly highly highly recommend against using a bot within a container without good reason. As you can see, deployment is significantly more difficult.

---

Regarding `aiohttp`, you should be able to just install `botbuilder-integration-aiohttp` listed in `requirements.txt` without also installing `aiohttp`.

**Comment by jwiley84** [comment]
Apologies. I'm tracking a couple docker issues I  believe to be related. Thank you for your patience. I should have an answer by this afternoon.

**Comment by jwiley84** [comment]
For tracking purposes: conversation concerning this ticket was taken to Teams. Will update when concluded there.

**Comment by peterinnesmsft** [comment]
@jwiley84 assuming we can close based on yesterday's conversation. Reactivate if this still needs to be addressed.
