### ISSUE TITLE
Broken links in docs for generated dialogs

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotBuilder-Samples#2605]
## Sample information
1. Sample type: experimental/generation
2. Sample language: --
3. Sample name: https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/generation/docs/templates.md

## Describe the bug
The links to the schema files for LUIS prebuilts are broken. This is the second section of the document:
https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/generation/docs/templates.md#luis-prebuilt-entities

## Expected behavior
They go to 
/experimental/generation/docs/_entityname_.schema 

Should they instead go to 
/experimental/generation/generator/templates/standard/_entityname_.schema]]

?

[bug]

**Comment by jwiley84** [comment]
Hi @mewa1024 I'll get these fixed. Thanks for letting us know!

**Comment by jwiley84** [comment]
@chrimc62 These are in the experimental folder, and I wasn't sure about hardlinking to fix the broken links, since I know stuff in experimental gets shifted around occasionally. I can PR to point them to the right place, if you're cool with it.
