### ISSUE TITLE
IncludeImage doesn't work in Microsoft Teams message action sample.

### ISSUE THREAD

**Issue by Lili-fine** [microsoft/BotBuilder-Samples#2621]
## Sample information
1. Sample type: Teams samples
2. Sample language: csharp_dotnetcore
3. Sample name: Messaging extensions - action

## Describe the bug
When choosing the 'Share Message' command in Microsoft Teams channels and choosing the 'Include image in Hero Card' toggle button,no image is included in the returned HeroCard. In sample codes, the comparison between two strings should ignore case. Please check Screenshots below for more details.

## To Reproduce
1. Deploy the sample "Messaging extensions - action" into Microsoft Teams
2. Click on "Share Message" command from any message in a Teams channel
3. Click on "Include image in Hero Card" toggle button

## Expected behavior
An image should be included in the returned HeroCard.

## Screenshots
![image](https://user-images.githubusercontent.com/11691919/88476186-1cce0180-cf69-11ea-9f01-22ba3e9d7d0d.png)
![image](https://user-images.githubusercontent.com/11691919/88476255-9e259400-cf69-11ea-9420-8bf7882c38de.png)

[bug]

**Comment by EricDahlvang** [comment]
Thank you for the PR!
