### ISSUE TITLE
Generated code should not contain copyright headers

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#2625]
The output code of the generators and the code ejected from Composer contain copyright headers. This is not correct, the generated code is produced by a tool we provide and is under the ownership of the user of the tool.

Note, for example, when you use the Add Controller feature in Visual Studio while constructing a web application the generated controller does not contain Microsoft copyright headers. Instead the developer is free to add their own copyright headers.

This also applies to the code ejected from Composer; opening the issue in samples initially because this is where the generators currently live.

**Comment by Kaiqb** [comment]
Agree with you @johnataylor . Users should be able to use the code generated from various tools and use them to build sophisticated bot. Adding @cwhitten for composer.
