### ISSUE TITLE
Add Samples for C# Azure Function

### ISSUE THREAD

**Issue by CrazyTuna** [Microsoft/BotBuilder-Samples#263]
I've started converted C# WebApp Samples to Azure Functions.

https://github.com/CrazyTuna/BotBuilder-Functions-Samples

Just wondering if it is something that could be in the Repo ?

**Comment by EricDahlvang** [comment]
Hi @CrazyTuna 

Thank you for your interest in the BotBuilder samples.  We have a very specific set of samples that demonstrate Bot Builder functionality.
