### ISSUE TITLE
.NET sample no. 15 (attachments) doesn't work on macOS

### ISSUE THREAD

**Issue by bjoernross** [microsoft/BotBuilder-Samples#2637]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: Handling attachments

## Describe the bug
.NET sample no. 15 doesn't work on macOS. Answering "1" or "3" to the welcome message, which should result in the display of an inline or uploaded attachment, respectively, results in the following error message:
```System.IO.FileNotFoundException: Could not find file '.../samples/csharp_dotnetcore/15.handling-attachments/Resources\architecture-resize.png'```
This is because the backward slash is hard-coded in `AttachmentsBot.cs` but macOS uses a forward slash.

## Screenshot
<img width="610" alt="Screenshot 2020-07-30 at 15 27 08" src="https://user-images.githubusercontent.com/6230381/88928501-3036e080-d279-11ea-84d9-78e88bcc0738.png">

**Comment by EricDahlvang** [comment]
@bjoernross  Thank you for the fix!
