### ISSUE TITLE
14.nlp-with-dispatch: luis_schema_version missing in Weather.json 

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotBuilder-Samples#2649]
## Sample information
1. Sample type: [samples]
2. Sample language: [dotnetcore & nodejs]
3. Sample name: 14.nlp-with-dispatch

## Describe the bug
The Weather.json file in the CognitiveModels folder does not contain the luis_schema_version and hence is throwing up this error "**BadArgument: Invalid luis schema version. Failed to parse application json.**" when you try to import Weather.json.

## To Reproduce
1. Go to 'www.luis.ai'
2. Click on 'New App for conversion > Import as JSON'
3. Select Weather.json file from CognitiveModels of 14.nlp-with-dispatch sample.
4. See error "BadArgument: Invalid luis schema version. Failed to parse application json."

## Expected behavior
The Weather.json file should be imported successfully without any errors.

## Fix
Add **"luis_schema_version": "3.2.0"** in the Weather.json file across both the C# and nodejs samples.

![image](https://user-images.githubusercontent.com/48731427/89451299-d1f27d80-d710-11ea-966d-06ffffbf0653.png)

## Additional context
As reported by the Cx in https://github.com/microsoft/BotBuilder-Samples/issues/2643

[bug]

**Comment by onomemillion** [comment]
It didn't work for me
