### ISSUE TITLE
Create Teams SSO sample in experimental folder

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#2651]
# Summary
Teams SSO is in partner preview, and we need to create samples and documentation to support. We need to fork the Teams auth sample into the experimental folder, and add SSO to that sample.

## De-duplication of exchange invoke requests issue
We have a need to dedupe multiple token exchange invoke requests (with same id), which may come in from multiple teams clients that the user is signed in on multiple devices. This can be done through middleware that stores the per-user requests, and ignores subsequent requests from multiple clients.

## Tracking Status
**Dotnet Sample**
- [x] PR
- [ ] Merged

**Javascript Sample**
- [ ] PR
- [ ] Merged

**Python Sample**
- [ ] PR
- [ ] Merged

**Docs **
- [ ] PR
- [ ] Merged

**Comment by clearab** [comment]
Add to existing auth sample, with SSO specific manifest.

**Comment by clearab** [comment]
Updating this item to reflect entire sample/doc creation in the experimental folder (to be migrated over the top of the existing Teams auth sample once SSO is GA).
