### ISSUE TITLE
dialog:generate - Missing template generic.lu

### ISSUE THREAD

**Issue by VinaiMeyyappan** [microsoft/BotBuilder-Samples#2657]
## Sample information
1. Sample type: BotBuilder-Samples/experimental/generation/
2. Sample language: [dotnetcore ]
3. Sample name: generator

## Describe the bug
Give a clear and concise description of what the bug is.
Get an error - Missing template generic.lu - when executing bf dialog:generate test.schema -o dialogs. 
Here is the test.schema 
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
       "Confirmation": { 
            "type": "boolean", 
            "$entities": [ "boolean" ]
        }
    },
    "required": [
        "Confirmation"
    ]
}
![image](https://user-images.githubusercontent.com/43550781/89683985-6219f980-d8ae-11ea-9d74-bd38f3731106.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by jwiley84** [comment]
Thank you for the heads up, I'll take a look and get this fixed.

**Comment by peterinnesmsft** [comment]
@jwiley84 any updates on this?

**Comment by jwiley84** [comment]
@VinaiMeyyappan My apologies for dropping the ball on this and not getting back to you faster.

Your test schema has `"type": "boolean"` which is what's kicking back this error. Per the documentation:

>The type parameter of the properties object defines the type of expected input. It should be one of string, number, or array

I agree that this error is not exactly illuminating, and I'll reach out to the cli code owners to try for a more clear one.

**Comment by VinaiMeyyappan** [comment]
Take a look at the [standard schema](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/generation/generator/packages/library/templates/standard/standard.schema) file 

` "CancelConfirmation": {
            "type": "**boolean**",
            "$entities": [
                "boolean"
            ],`

boolean is a valid type. Is the documentation out of date?
