### ISSUE TITLE
experimental/sso-with-skills Sample Does not handle the Invoke Activity from OAuth Prompt

### ISSUE THREAD

**Issue by HobbyProjects** [microsoft/BotBuilder-Samples#2658]
## Sample information
1. Sample type: experimental
2. Sample language: dotnetcore 
3. Sample name: sso-with-skills

## Describe the bug
After the "Sign In" card is displayed and the the login prompt is displayed and completed, we will get an "Invoke" activity which we should send back to `MainDialog` to complete `OAuthPromot` login process. The current sample does not handle the Invoke activity and login is never completed. To be precise, this callback needs to be added to `TeamsActivityHandler` implementation

```
protected override async Task OnTeamsSigninVerifyStateAsync(ITurnContext<IInvokeActivity> turnContext, CancellationToken cancellationToken)
        {
            // The OAuth Prompt needs to see the Invoke Activity in order to complete the login process.
            await _dialog.RunAsync(turnContext, _conversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
        }
```

## To Reproduce
1. Run the sample
2. Notice the login process never completes

## Expected behavior
Give a clear and concise description of what you expected to happen.
Login process completes.

## Additional context

[bug]

**Comment by jwiley84** [comment]
@dmvtech +Dana

**Comment by dmvtech** [comment]
I'm checking to see if I can simply reproduce.

**Comment by dmvtech** [comment]
Still working on repro. Hitting some speedbumps getting it all set up.

**Comment by pavolum** [comment]
@dmvtech any update on this?

**Comment by dmvtech** [comment]
Still working on it. Having some issues on Teams (my own issues). I hope to have an better update by the end of the day.

**Comment by dmvtech** [comment]
I can reproduce this, but I wonder if we want to consider this a bug. I know that with _samples_, we try and be as narrow as possible in the completeness of the sample/example. As we already have an example on how to do Teams auth (That _does_ handle the Invoke Activity), that whether that needs to be added to this sample (for the sake of thoroughness) or not. Not every sample should work in every scenario. They are meant to be small, concise examples that convey small aspects and approaches within SDK.

@pavolum Can you bring this up in triage and see if this is a change/addition/fix that should be implemented?

@HobbyProjects We do accept contributions from the community. Would you be interested in creating a pull request with the fix if this is an accepted approach? (if not, no worries)

**Comment by GeoffCoxMSFT** [comment]
@swagatmishra2007 - can you take a look at this?

**Comment by tdurnford** [comment]
@gabog @clearab What are your thoughts on either updating the sample, leaving the sample as is, or leaving the sample as is and adding a new sample to handle the user's scenario?

**Comment by clearab** [comment]
@tdurnford Assuming this is the only change required to make SSO work in Teams, I think adding it to this sample should be sufficient. If we want to make it a bit more explicit we could comment it out, and add a "Running in Teams" section to the readme to uncomment the code. A similar treatment may make sense for our other authentication samples (consolidate the Teams one with the "normal" auth sample).

**Comment by lzc850612** [comment]
@swagatmishra2007 do you have any update on this issue? Thanks.

**Comment by swagatmishra2007** [comment]
I agree with @clearab above, but that increases the scope a bit, including testing. So i would like to discuss this at the triage meeting

**Comment by stevengum** [comment]
@swagatmishra2007 and @clearab can the two of you sync and come up with an actionable plan for this sample?

**Comment by cwhitten** [comment]
ping @clearab

**Comment by clearab** [comment]
Are there still open questions about this? I'd like to see this get picked up and see the sample updated in-line with the comments above. @johnataylor can you help find the appropriate dev for implementation?

**Comment by gabog** [comment]
Closing this one for now, we will address it as part of SSO for teams, there's another PR for SSO with skills [here](https://github.com/microsoft/BotBuilder-Samples/pull/3673)
