### ISSUE TITLE
Teams - Task Module not working in some mobile devices

### ISSUE THREAD

**Issue by ravikant15796** [microsoft/BotBuilder-Samples#2665]
## Sample information
teams-task-module
Node JS
Bot Framework

## Describe the bug
I am trying  play some video content inside a teams bot using task module. it works fine in desktop but in some Mobile devices it showing error "Failed to load webview". 

##Error Screenshot :-
![taskModule_mobile_error](https://user-images.githubusercontent.com/10558023/89895226-10000d80-dbf9-11ea-8e7e-3e733c28faa9.png)

## Here is list of mobile devices giving  "Failed to load webview" error

1. Samsung On 7 Prime, Android Version 9
2. Pixel XL, Android Version 10
3. Samsung M21, Android Version 10

## To Reproduce
1. Implement task module with adaptive cards

here is code i have written for task module in my adaptive card

actions:[
{
        "type": "Action.Submit",
        "title": title,
        "data": {
         "url" : url,
          "msteams": {
               "type": "task/fetch",
                "title": title,
            }
         }
  } 
]

Server Code :- 

if (turnContext._activity.type === "invoke") {
          let { url } = turnContext._activity.value.data
          res.send({
            task: {
              type: 'continue',
              value: {
                "height": "large",
                "width": "large",
                "url": url
              }
            }
          })

## Expected behavior
it should work like below screenshot
![taskmodule_mobile](https://user-images.githubusercontent.com/10558023/89893779-9bc46a80-dbf6-11ea-97a1-91a6dd3f3ef0.png)

**Comment by clearab** [comment]
Hi - I'm going to move this to the Teams support repository so that they can address this directly. Please see: https://github.com/MicrosoftDocs/msteams-docs/issues/1969
