### ISSUE TITLE
Website-to-Bot ASP.NET SSO sample in Experimental

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotBuilder-Samples#2680]
Similar to Teams request, we hit customer request for this as well.

Currently, Eric crafted a sample in his repo.

"We have asked the Product Group team to provide as a Website-to-Bot ASP.NET SSO sample and they provided us with the following information:"
...One of the PG members created the following sample: https://github.com/EricDahlvang/WebChatSSO

**Comment by gabog** [comment]
Closing, we will consider adding a sample in the future based on current backlog
