### ISSUE TITLE
RView Tool

### ISSUE THREAD

**Issue by ernestoguimaraes** [Microsoft/BotBuilder-Samples#269]
Hello,
I got the RView project and found that there are some erros while executing against an assembly with classe name with more than 4 words on namespace. 

Example:
AssemblyName.Model.Forms.FormFlowClass.

Is there anyway to generate this resx. file?

**Comment by JasonSowers** [comment]
This question is probably best asked on StackOverflow so you can tag Rview and reach a broader audience that is familiar with the tool.

**Comment by fanidamj** [comment]
The [RView source](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tools/RView/Program.cs ) is open, if you’d like to debug and determine what the underlying issue is that you’re running into. The same was mentioned by Eric in email too.
