### ISSUE TITLE
Direct Line Bot takes long time

### ISSUE THREAD

**Issue by weizhenzhao** [microsoft/BotBuilder-Samples#270]
### SDK Platform
.Net

### URL of Code Sample
 [HttpPost]

        public async Task<HttpResponseMessage> Post()

        {

            //

            //var timeEnd = DateTime.Now;

            //var timeCost = 0d;

            var keyWord = await Request.Content.ReadAsStringAsync();

            //when posted word is empty, return 406 code

            if (string.IsNullOrEmpty(keyWord)) return Request.CreateResponse(HttpStatusCode.OK, "empty input");

 

            //create DirectLineClient

            //===>

            var conversationStart = DateTime.Now;

            var client = new DirectLineClient("k9R71se3nqg.cwA.GfE.4Xx7jxdr5wFAC6tkulSb9z2CK5nTt_szFevTWdUvp14");

            var conversation = await client.Conversations.StartConversationAsync();

            var conversationStartCost = (DateTime.Now - conversationStart).TotalSeconds;

            LogHelper.Instance.PacteraWrite($"===> DirectLine Conversation '{keyWord}' Time Cost: {conversationStartCost}s <===", "Bot.Controllers", "WeiXinController", "Post");

            //===>

 

            //===>

            var detectedStart = DateTime.Now;

            var language = await Translator.Instance.DetectedLanguage(keyWord);

            var detectedCost = (DateTime.Now - detectedStart).TotalSeconds;

            LogHelper.Instance.PacteraWrite($"===> Bing Language detected '{keyWord}' Time Cost: {detectedCost}s <===", "Bot.Controllers", "WeiXinController", "Post");

            //===>

            if ("Failed" == language)

            {

                var responseData = new BotInterfaceEntity();

                responseData.Result = Pactera.Common.Enums.BotResult.Exception;

                responseData.Argument = "Sorry,we can't detected your inputment's language";

                return new HttpResponseMessage { StatusCode = HttpStatusCode.OK, Content = new StringContent(JsonConvert.SerializeObject(responseData), Encoding.UTF8, "application/json") };

            }

 

            if (language != "en")

            {

                //===>

                var translateStart = DateTime.Now;

                keyWord = await Translator.Instance.TranslateTextToEn(keyWord);

                var translateCost = (DateTime.Now - detectedStart).TotalSeconds;

                LogHelper.Instance.PacteraWrite($"===> Bing Language translate '{keyWord}' Time Cost: {translateCost}s <===", "Bot.Controllers", "WeiXinController", "Post");

                //===>

            }

 

            var activity = new Activity();

            activity.From = new ChannelAccount("weixin");

            activity.Text = keyWord.Replace("\n", "").Replace("\r", "").Replace("\t", "").Trim();

            activity.Summary = language;

            activity.Type = ActivityTypes.Message;

            //call bot for advice

            //===>

            var callBot = DateTime.Now;

            var directLineResponse = await client.Conversations.PostActivityWithHttpMessagesAsync(conversation.ConversationId, activity);

            var directLineResult = JsonConvert.DeserializeObject<BotInterfaceEntity>(await directLineResponse.Response.Content.ReadAsStringAsync());

            var callBotCost = (DateTime.Now - callBot).TotalSeconds;

            LogHelper.Instance.PacteraWrite($"===> Bot Http request '{keyWord}' Time Cost: {callBotCost}s <===", "Bot.Controllers", "WeiXinController", "Post");

            //===>

            if (directLineResponse.Response.StatusCode == HttpStatusCode.OK)

            {

                //OK

                var activitySet = await client.Conversations.GetActivitiesAsync(conversation.ConversationId);

                var botActivity = activitySet.Activities.ToList().Find(p => p.From.Id == "CRMChatBot-ChannelBot");

                return new HttpResponseMessage { StatusCode = HttpStatusCode.OK, Content = new StringContent(botActivity.Text, Encoding.UTF8, "application/json") };

            }

            else

            {

                return Request.CreateResponse(directLineResponse.Response.StatusCode, directLineResult.error.message);

            }

        }

### Problem Description
I am using directline bot to connect the bot and the weixin channel .
Some time a message was sent by directline and directline received a message
The total time takes 0.2s , but sometimes it takes 2.5 seconds
but the weixin requires that a message must be returned in 5s .
So we go time out error .
My code is as above , Can you help me to make the time takes by directline stable?

Thank you very much

WeiZhen

**Comment by weizhenzhao** [comment]
@JasonSowers can you help me? my boss ask me about this issue everyday .  And I have a lot of pressure.
please .

**Comment by coderxlsn** [comment]
A long timeout can be if the application is falling sleeping or unloaded from memory. as an option to ping a bot on api once in 1 minute.

**Comment by weizhenzhao** [comment]
@coderxlsn  what do you mean that I can solve this issue by ping a bot on api once a minute in a schedule?

**Comment by EricDahlvang** [comment]
If your bot is hosted in Azure, you can enable AlwaysOn: https://docs.microsoft.com/en-us/azure/app-service/web-sites-configure#alwayson  Is your issue a cold start problem?
