### ISSUE TITLE
Receiving an attachment from facebook in C#

### ISSUE THREAD

**Issue by jonasvsaet** [Microsoft/BotBuilder-Samples#271]
### SDK Platform
.Net

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment

### Problem Description
How do you receive attachments from the facebook messenger channel? the sample code doesn't appear to work with facebook messenger but it does with other channels. 
PromptDialog.Attachment seems to give an error aswell.

**Comment by JasonSowers** [comment]
Thanks for reporting this, can you answer some follow-up questions please?  What type of file(s) are you trying to upload?  Which version of the SDK are you using (3.xx.x.x)? What channel(s) is it working in for you?  Are you just using the code from the sample or is there anything you have added?

**Comment by jonasvsaet** [comment]
I've figured out the problem. The problem is due to the Name property being empty. Thanks for your help.
