### ISSUE TITLE
Node.js sample no. 03.welcome-users: Doesn't work( get "Error: Unauthorized" )

### ISSUE THREAD

**Issue by Doppon** [microsoft/BotBuilder-Samples#2724]
## Describe the bug
When run the app, it get Unauthorized Error.

## To Reproduce
1. read the README.md and do that.

## Screenshots

![スクリーンショット_2020-09-09_1_49_47](https://user-images.githubusercontent.com/27806269/92505460-148f0480-f23f-11ea-8cd8-4edce5a86438.png)

## Additional context
There are typo in `index.js` .
https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/03.welcome-users/index.js#L22

It is **NOT**  `process.env.MicrosoftAppID`.
Correctly it is `process.env.MicrosoftAppId`.

**Comment by jwiley84** [comment]
Hi @Doppon Thank you for pointing this out! We'll get it corrected today.

**Comment by Doppon** [comment]
Thanks for fixing.
