### ISSUE TITLE
'Create New Conversion' Sharp sample doesn't work.

### ISSUE THREAD

**Issue by lin-zy1229** [Microsoft/BotBuilder-Samples#274]
### SDK Platform

.NET

### URL of Code Sample

https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-CreateNewConversation

### Problem Description

It builds and runs in Chrome successfully.
But not shows Bot message, and even can't send user message,

![image](https://user-images.githubusercontent.com/13885833/41803732-a9cb327a-76be-11e8-835c-9a831eebae23.png)

![image](https://user-images.githubusercontent.com/13885833/41803746-c9781ea8-76be-11e8-8299-6785a9ffd36a.png)

Visual Studio 2017, Bot Framework Emulator v3.5.36
As you can see, I am testing in local and nothing changed in source code.
What is the problem?

**Comment by stevkan** [comment]
Hi @lin-zy1229, please update the BotBuilder SDK to 3.15.2 and try again.

**Comment by lin-zy1229** [comment]
once upgrade, seems better, but still failing.

![image](https://user-images.githubusercontent.com/13885833/41753231-a5fbc5f8-75fe-11e8-96e6-ac82b0861f1f.png)

**Comment by lin-zy1229** [comment]
This is current setting, and nothing changed in source code as mentioned first.

![image](https://user-images.githubusercontent.com/13885833/41803696-403bfeca-76be-11e8-9dc0-17a955600e5e.png)

**Comment by dhinag** [comment]
I tried this sample code with the bot emulator and run into the same issue mentioned by @lin-zy1229 . Do you have any progress on this issue @lin-zy1229 ?

Thanks!

**Comment by lin-zy1229** [comment]
Not yet, @dhinag.

**Comment by stevkan** [comment]
@lin-zy1229 and @dhinag,

If you wish to run purely local, be sure the app is running in VS. Your Web.config settings should look like this:
![csharp no app settings](https://user-images.githubusercontent.com/18403946/41926633-be7fa742-7924-11e8-81af-06794a890a9a.JPG)

If you are using the v3 emulator, then your emulator settings should look like this:
![csharp v3 emulator no settings](https://user-images.githubusercontent.com/18403946/41926665-d8641044-7924-11e8-9196-bba45c2a5a25.JPG)

If you are using the v4 emulator, then your emulator settings should look like this:
![csharp v4 emulator no settings](https://user-images.githubusercontent.com/18403946/41927502-49d60640-7927-11e8-9d01-197e70740f47.JPG)

**Comment by dhinag** [comment]
Thanks @stevkan. I'll ensure that my settings mimic your settings and let you know.

**Comment by cristi-badila** [comment]
@stevkan I wanted to try out this sample today and I'm getting the same exception as above while trying to run the bot locally (in development) and using the V4 bot emulator.
The settings in the bot emulator:
![capture](https://user-images.githubusercontent.com/787587/42035181-01c70460-7aeb-11e8-9b92-0f395cce9b1c.PNG)
The settings in web.config
```
  <appSettings>
    <!-- update these with your BotId, Microsoft App Id and your Microsoft App Password-->
    <add key="BotId" value="" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
  </appSettings>
```
Relevant nuget packages (after suggested update):
```
  <package id="Microsoft.Bot.Builder" version="3.15.2.2" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder.Azure" version="3.15.2.2" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder.History" version="3.15.2.2" targetFramework="net46" />
  <package id="Microsoft.Bot.Connector" version="3.15.2.2" targetFramework="net46" />
```
For clarity, the received error message is:
```
Exception: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ScoringEventLoop1 (DelegateActivator), Services = [Microsoft.Bot.Builder.Base.IEventLoop], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ReactiveDialogTask (ReflectionActivator), Services = [Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Func1 (DelegateActivator), Services = [System.Func1[[Microsoft.Bot.Builder.Dialogs.IDialog1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.Bot.Builder, Version=3.12.2.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]], Lifetime = Autofac.Core.Lifetime.MatchingScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope —> Sequence contains no elements (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)
[File of type 'text/plain']
```
I should mention that I can run some of the other samples with the emulator with no issues. (eg SimpleEchoBot, MultiDialogsBot)

**Comment by cristi-badila** [comment]
Hi @stevkan, indeed I can confirm that I'm trying out the `core-CreateNewConversation` sample. I initially just cloned the repository and ran the sample as is without modifying any of the project files and encountered the mentioned exception. I then tried updating the `Microsoft.Bot.*` dependencies of the solution to 3.15.2.2 as per the advice you gave further up in this thread and unfortunately the exception persisted. Please let me know if I can help in any other way.

**Comment by JasonSowers** [comment]
I just tested this today and have been able to get it working with the latest package 3.15.3 in the v3 emulator.  Is anyone else able to do so?

**Comment by dhinag** [comment]
Hi @JasonSowers,
I just tried it again (I updated the bot builder to 3.15.2.2.), and got this error in v4 emulator:

[FileLoadException: Could not load file or assembly 'Microsoft.Bot.Builder, Version=3.12.2.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

I tried with v3 emulator and got 500 Internal Server error. It is probably the same error behind the scene.

Here is my web.config settings.

```
  <appSettings>
    <!-- update these with your BotId, Microsoft App Id and your Microsoft App Password-->
    <add key="BotId" value="" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
  </appSettings>
```

**Comment by JasonSowers** [comment]
You say you are on version 3.15.2.2 and this is showing up in your error Could not load file or assembly 'Microsoft.Bot.Builder, Version=**3.12.2.4**. Something strange is happening here. Can you try to correct this reference? You may even want to try with a fresh project. I’ll continue troubleshooting this sample for issues.

**Comment by cristi-badila** [comment]
@JasonSowers initially I had tried the sample with only the v4 emulator however I tried today the v3 one as well. Here's my experience:
- I started out by updating to v 3.15.3 of the framework but I immediately found an issue in that the `Microsoft.Bot.Builder.Azure` package doesn't have a 3.15.3 version published; only 3.15.2.2. So out of the gate I couldn't run the sample since trying to run the app with some packages on 3.15.3 and `Microsoft.Bot.Builder.Azure` on 3.15.2.2 throws an exception as the later will try to load 3.15.2.2 assemblies. 
- Next I tried running the sample with all the framework dependencies on 3.15.2.2 and the emulator on version 3.5.36. With this setup the initial conversation is started however whenever I type a message into the dialog (so as to get the conversations started) I encounter a 500 error with no more details.
![capture](https://user-images.githubusercontent.com/787587/42259199-1c50cb46-7f68-11e8-8b39-dc29867f9a9b.PNG)

I've pushed the code here: https://github.com/cristi-badila/botframework-new-conversation.

**Comment by JasonSowers** [comment]
Thanks for the details and putting your project in a repo for me. Holiday today so I will take a look tomorrow.

**Comment by JasonSowers** [comment]
I just tested with 3.15.3 and botbuilder-azure 3.13.2.2 with no issues.  I will look at your project in your repo now.

**Comment by JasonSowers** [comment]
@cristi-badila I am getting the same results with your project, yet my project is working.  I have submitted a pull request against your repo here https://github.com/cristi-badila/botframework-new-conversation/pull/1 can you please try it with those changes and let me know the results.  If it works for you I will submit a pull request against the main sample to update it as well.  This is odd because for myself and other members of my team we are having no issue running the sample 👎

**Comment by cristi-badila** [comment]
@JasonSowers thanks for your help. Indeed your PR fixed the issue. I can now successfully run the sample together with the bot framework emulator v3.5.36 (latest v3 release). For completeness I should mention however that trying to run the sample with the v4.0.15-alpha emulator (latest v4 release) the sample gets stuck when calling line 25 in the `SurveyTriggerer`:

`var conversation = await client.Conversations.CreateDirectConversationAsync(message.Recipient, message.From);`. 

No error occurs, but the call never completes and weirdly it doesn't seem to timeout either. Anyway, having the sample work with the v3 emulator should be enough I think to get me in the right direction. Thanks again 👍

**Comment by JasonSowers** [comment]
@cristi-badila thanks again for your patience and for reporting this issue.  I will keep investigating this until I can find a resolution such that the sample should just work as is for all customers in any emulator version.  I'm glad I was able to get you a version that you can use as a starting point.  Best of luck and please keep reporting any issues you find.

**Comment by dhinag** [comment]
Thanks @JasonSowers . It is working for me on v3 emulator and the same problem that @cristi-badila reported with v4 emulator.
