### ISSUE TITLE
If a skill has an error it doesn't send EndOfConversation

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotBuilder-Samples#2755]
## Version

4.10.3

## Describe the bug

If a skill triggers an exception during operation, the default `OnTurnError` handler is triggered. This results in us failing to send an `EndOfConversation` and leaving the calling bots `SkillDilaog` in somewhat of a stuck state.  My thought is we may want to special case the handling of skill errors within the [DialogManager here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L228).

## Additional context
We will address this in [sample 81](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/81.skills-skilldialog) first and consider moving to the SDK in a feature release once we have a generic solution

TODO: add placeholders for all the languages (C#, JS, Python and Docs).

Composer may need to update the runtime to do this, VA skill vsix already has this.

**Comment by stevengum** [comment]
Example code snippet from VA team

### todoskill's [DefaultAdapter.cs](https://github.com/microsoft/botframework-skills/blob/90bf544274b342ca78c3987109e37b7db5e919ce/skills/csharp/todoskill/Adapters/DefaultAdapter.cs#L90-L108)

```cs
        private async Task SendEndOfConversationToParentAsync(ITurnContext turnContext, Exception exception)
        {
            try
            {
                if (turnContext.IsSkill())
                {
                    // Send and EndOfConversation activity to the skill caller with the error to end the conversation
                    // and let the caller decide what to do.
                    var endOfConversation = Activity.CreateEndOfConversationActivity();
                    endOfConversation.Code = "SkillError";
                    endOfConversation.Text = exception.Message;
                    await turnContext.SendActivityAsync(endOfConversation);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Exception caught in SendEoCToParentAsync : {ex}");
            }
        }
```

**Comment by gabog** [comment]
This was done, closing
