### ISSUE TITLE
Port dialog samples to Adaptive Dialogs

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#2756]
Determine which of these samples should be ported to Adaptive Dialogs:

- [x] 05.multi-turn-prompt
- [x] 06.user-cards
- [x] 07.using-adaptive-cards
- [x] 08.suggested-actions
- [x] 11.qnamaker
- [x] 13.core-bot
- [ ] 13.core-bot-tests
- [ ] 14.nlp-with-dispatch
- [x] 15.handling-attachments
- [x] 16.proactive-messages
- [x] 17.multilingual-bot
- [x] 18.bot-authentication
- [ ] 19.custom-dailogs
- [ ] 21.corebot-app-insights
- [x] 23.facebook-events
- [x] 24.bot-authentication-msgraph
- [x] 25.message-reaction
- [ ] 42.scaleout
- [ ] 43.complex-dialog
- [x] 44.prompt-users-for-input
- [ ] 45.state-management
- [x] 47.inspection
- [ ] 49.qnamaker-all-features
- [ ] 80.skills-simple-bot-to-bot
- [ ] 81.skills-skilldialog

- [ ] vsix and templates core-bot

Some of these are already completed here:
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/adaptive-dialog

Teams:
- [ ] 46.teams-auth
- [ ] 50.teams-messaging-extensions-search
- [ ] 51.teams-messaging-extensions-action
- [ ] 52.teams-messaging-extensions-search-auth-config
- [ ] 53.teams-messaging-extensions-action-preview
- [ ] 54.teams-task-module
- [ ] 55.teams-link-unfurling
- [ ] 56.teams-file-upload
- [ ] 57.teams-conversation-bot
- [ ] 58.teams-start-new-thread-in-channel

Custom Adapters:
- [ ] 60.slack-adapter
- [ ] 61.facebook-adapter
- [ ] 62.webex-adapter
- [ ] 63.twilio-adapter

Not a bot:
- [ ] 40.timex-resolution

**Comment by mrivera-ms** [comment]
This is no longer needed.
