### ISSUE TITLE
Adaptive Dialog missing from the readme

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotBuilder-Samples#2759]
There needs to be a section on adaptive dialogs in the [readme](https://github.com/microsoft/BotBuilder-Samples/blob/main/README.md), and it needs to appear in the list as shown below:

![image](https://user-images.githubusercontent.com/52054121/93943783-14cfdb00-fce8-11ea-96d1-01a51ff41901.png)

**Comment by sempjc** [comment]
Hi @WashingtonKayaker today I open a PR with this change applied. You can follow up the status [here](https://github.com/microsoft/BotBuilder-Samples/pull/2999).
