### ISSUE TITLE
You have to specify TLS version during create WebSocketSharp.WebSocket in C# sample code.

### ISSUE THREAD

**Issue by micli** [Microsoft/BotBuilder-Samples#279]
My issue is about DirectLine sample code of BotBuilder SDK for .NET, which is located at:
[Samples/blob/master/core-DirectLineWebSockets/DirectLineClient](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-DirectLineWebSockets/DirectLineClient/Program.cs#L40)

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-DirectLineWebSockets/DirectLineClient/Program.cs#L40

### Problem Description
When I use above code to create a WebSocket to connect DirectLine I always get below error:
WebSocketSharp.WebSocketException: An error has occurred during a TLS handshake. ---> System.NotSupportedException: The requested security protocol is not supported.
                           at System.Net.SecurityProtocol.ThrowOnNotAllowed(SslProtocols protocols, Boolean allowNone)
                           at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
                           at WebSocketSharp.WebSocket.setClientStream()
                           --- End of inner exception stack trace ---
                           at WebSocketSharp.WebSocket.setClientStream()
                           at WebSocketSharp.WebSocket.doHandshake()
                           at WebSocketSharp.WebSocket.connect()

Actually, the root cause is  web server of DirectLine service forced TLS v1.2 but WebSocketSharp doesn't specified yet.

### How to fix
Add below line after created WebSocketSharp.WebSocket object:
`
// You have to specify TLS version to 1.2 or connection will be failed in handshake.
                WebSocketClient.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;
`

**Comment by EricDahlvang** [comment]
Would you like to submit a PR to add this code to the sample?

**Comment by micli** [comment]
OK, I will do it soon.

**Comment by CoHealer** [comment]
@EricDahlvang, to get the PR ready.

**Comment by EricDahlvang** [comment]
Closing since this was apparently already merged: https://github.com/Microsoft/BotBuilder-Samples/pull/281

https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/CSharp/core-DirectLineWebSockets/DirectLineClient/Program.cs#L44
