### ISSUE TITLE
Ensure schemas exist for all LUIS entity types

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotBuilder-Samples#2804]
We need to ensure that there are .schema for all LUIS entity types.  So far, we have only schematized ones that are formats or are objects.  We need to add schema for personname, phone number, keyphrase, percentage.   We should also change schema processing so that when $entities are in the item of an array they are promoted to the property level.  That way the elements of an array can point to one of the component schemas.

**Comment by coldplaying42** [comment]
If string LUIS entity schemas are added, the format like "$ref": "template:keyphrase.schema" can be parsed. Is it correct? I do not understand what "promoted" means in the context.
