### ISSUE TITLE
Suggested Actions buttons overwrite response in Skype

### ISSUE THREAD

**Issue by LlewellynJones** [microsoft/BotBuilder-Samples#2810]
## Sample information
1. Sample type: Suggested Actions
2. Sample language: c# dotnetcore 
3. Sample name: Suggested Actions

## Describe the bug
I'm using the suggested actions sample code but I find in Skype only, the buttons produced by the code overwrite the text in the bots response to the user.
## To Reproduce
1. Add the Actions Code to the bot. See below:
```
                        var reply4 = MessageFactory.Text, <some text>);
                        reply4.Type = ActivityTypes.Message;
                        reply4.TextFormat = TextFormatTypes.Plain;

                        reply4.SuggestedActions = new SuggestedActions()
                        {
                            Actions = new List<CardAction>()
                        {
                            new CardAction(){ Title = "Read More", Type=ActionTypes.PostBack, Value="ri next" },
                            new CardAction(){ Title = "See Book", Type=ActionTypes.PostBack, Value="ri book" }
                        }
                        };
                        await turnContext.SendActivityAsync(reply4, cancellationToken);
```

2. See the Suggested Actions buttons in Skype.

## Expected behavior
The suggested actions buttons should not overwrite the bot's response. See screenshot to see the issue.

## Screenshots
![skype image](https://user-images.githubusercontent.com/10248399/94299324-5cd74380-ff1c-11ea-9b86-103f8bf7ca1d.png)

**Comment by anusharavindrar** [comment]
@LlewellynJones, Skype has been deprecated and we no longer support it. Please refer to [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0) doc.
