### ISSUE TITLE
SSO and Skills sample referred to in docs should be core samples not experimental

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#2811]
The article:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml

refers to this sample:

https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/sso-with-skills

This sample should be in the core sample set (in the samples folder) rather than in the experimental folder if it is being referenced in this way. Experimental is a intended as a temporary home for experimental work.

And we would ultimately need this sample in all the supported languages.

The code of the sample looks pretty OK so this is just really a matter of moving it. Perhaps we need an update to the readme and a check for other minor consistency issues.

**Comment by mmiele** [comment]
@johnataylor @gabog Could you please let the documentation team know when the sample is ready so the related documentation can be updated? Thanks

**Comment by mmiele** [comment]
@johnataylor This issue is not a documentation issue per se. Would you mind to flag it as a such and then let the documentation team know when the samples are ready. At that time team will create a PR to update the related articles. Thanks
