### ISSUE TITLE
Version ID and Deprecated Geography Issue

### ISSUE THREAD

**Issue by toenie23** [Microsoft/BotBuilder-Samples#282]
### SDK Platform
.NET

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-LUIS

### Problem Description
When importing the LUISbot.JSON into LUIS.AI, you will get an issue about version ID and the bing entity "Geography" being deprecated. One way I was able to work around this was adding this line of code under luis_schema_version

"versionId": "0.2", 

and remove the "geography" text in Bing Entities...so you should have an empty bracket. 

It imported successfully, I'll keep everyone updated if this demo continues to work.

**Comment by mgn7** [comment]
This JSOn works. 

{
  "luis_schema_version": "3.1.0",
  "versionId": "0.1",
  "name": "LuisBot",
  "desc": "GitHubExampl",
  "culture": "en-us",
  "intents": [
    {
      "name": "None"
    },
    {
      "name": "SearchHotels"
    },
    {
      "name": "ShowHotelsReviews"
    },
    {
      "name": "Help"
    }
  ],
  "entities": [
    {
      "name": "Hotel"
    },
    {
      "name": "AirportCode"
    }
  ],
  "composites": [],
  "closedLists": [],
  "bing_entities": [],
  "actions": [],
  "model_features": [
    {
      "name": "Near",
      "mode": true,
      "words": "near,around,close,nearby",
      "activated": true
    },
    {
      "name": "Show",
      "mode": true,
      "words": "show,find,look,search",
      "activated": true
    }
  ],
  "regex_features": [
    {
      "name": "AirportCodeRegex",
      "pattern": "[a-z]{3}",
      "activated": true
    }
  ],
  "utterances": [
    {
      "text": "look for hotels in miami",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "search for hotels in seattle",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "show me hotels in california",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "show me the reviews of the amazing bot resort",
      "intent": "ShowHotelsReviews",
      "entities": [
        {
          "entity": "Hotel",
          "startPos": 5,
          "endPos": 8
        }
      ]
    },
    {
      "text": "can i see the reviews of extended bot hotel?",
      "intent": "ShowHotelsReviews",
      "entities": [
        {
          "entity": "Hotel",
          "startPos": 6,
          "endPos": 8
        }
      ]
    },
    
    {
      "text": "show me reviews of the amazing hotel",
      "intent": "ShowHotelsReviews",
      "entities": [
        {
          "entity": "Hotel",
          "startPos": 4,
          "endPos": 6
        }
      ]
    },
    {
      "text": "what can i do?",
      "intent": "Help",
      "entities": []
    },
    {
      "text": "help me",
      "intent": "Help",
      "entities": []
    },
    {
      "text": "what are the available options?",
      "intent": "Help",
      "entities": []
    },
    {
      "text": "i need help",
      "intent": "Help",
      "entities": []
    },
    {
      "text": "best hotels in seattle",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "hotels in los angeles",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "can you show me hotels from los angeles?",
      "intent": "SearchHotels",
      "entities": []
    },
    {
      "text": "can you show me the reviews of the amazing resort & hotel",
      "intent": "ShowHotelsReviews",
      "entities": [
        {
          "entity": "Hotel",
          "startPos": 7,
          "endPos": 11
        }
      ]
    },
    {
      "text": "what are the reviews of the hotel bot framework?",
      "intent": "ShowHotelsReviews",
      "entities": [
        {
          "entity": "Hotel",
          "startPos": 5,
          "endPos": 8
        }
      ]
    }
  
  

   
      ]
    }
  ]
}
