### ISSUE TITLE
sample 52 not work well on new teams version.

### ISSUE THREAD

**Issue by yetsmarch** [microsoft/BotBuilder-Samples#2836]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
hello, I create a message extension app as sample 52, I opened the message extension and select a herocard, the card never send out to the cannel. it seems that the dialog close soon before getting the search result.
my teams version is  1.3.00.28622, will you have a test

**Comment by Wajeed-msft** [comment]
Hi @yetsmarch - I have posted this issue on Microsoft Teams repo. Please follow it here: https://github.com/MicrosoftDocs/msteams-docs/issues/2199
