### ISSUE TITLE
pagedmembers issue 

### ISSUE THREAD

**Issue by souvik01123** [microsoft/BotBuilder-Samples#2848]
HI Team,

I am learner here . I want to create a flow where bot will interact with 3 people . 1st interaction will take bot and chat initiator . 2nd interaction will have a state where bot will open up a window with another user to get an approval .

I used your botbuilder-samples\samples\javascript_nodejs\57.teams-conversation-bot code and got below error . Please suggest what to do 
 
unhandled error: Error: /v3/conversations/e9452730-0f91-11eb-a20b-096b7b0fce21%7Clivechat/pagedmembers does not
exist

**Comment by EricDahlvang** [comment]
Hi @souvik01123 

57.teams-conversation-bot is intended to be used from the Teams channel.  Based on this url, /v3/conversations/e9452730-0f91-11eb-a20b-096b7b0fce21%7Clivechat/pagedmembers  it looks like the emulator was used to connect to the bot?  Unfortunately, the emulator does not work with the Teams samples.

Please try the bot from Teams.  Some instructions can be found in the readme.

- Edit the manifest.json contained in the teamsAppManifest folder to replace your Microsoft App Id (that was created when you registered your bot earlier) everywhere you see the place holder string <<YOUR-MICROSOFT-APP-ID>> (depending on the scenario the Microsoft App Id may occur multiple times in the manifest.json)

- Zip up the contents of the teamsAppManifest folder to create a manifest.zip

- Upload the manifest.zip to Teams (in the Apps view click "Upload a custom app")
