### ISSUE TITLE
Broken links by redirecting to QnA prompting sample

### ISSUE THREAD

**Issue by RedAvenge** [microsoft/BotBuilder-Samples#2851]
## Describe the bug
Hey there,
the links in the readme of [main/experimental/qnamaker-prompting](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/qnamaker-prompting) are broken. They link to a replaced sample but in the normal samples folder to which they are linking is no `70.qnamaker-multiturn-sample`.

## To Reproduce
1. Go to 'https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/qnamaker-prompting'
2. Click on one of the links (both are broken)
3. See error, that the page was not found.

## Expected behavior
Links should work and redirect to the proper sample and the sample itself should be available too.

**Comment by RedAvenge** [comment]
I just saw that a similar issue #2727 is still open. But I think my issue has something more to it, because the other issue does not mentioned that the sample itself is not available at all in the samples folder.

In any case, sorry for the dupe but I did not searched for an existing issues in the first place because I think this is such a "simple" error which should be fixable without the issue moving to the third page :)

**Comment by cleemullins** [comment]
@v-kydela Kyle, could you submit the PR to cleanup these links? Thanks!

**Comment by v-kydela** [comment]
Closing to address here: https://github.com/microsoft/BotBuilder-Samples/issues/2727
