### ISSUE TITLE
Dispatch refresh / create normalizing properties doesn't work

### ISSUE THREAD

**Issue by edemehmetcan** [microsoft/BotBuilder-Samples#2869]
What project is affected?
Dispatch refresh/create command

What language is this in?

Powershell

What happens?
When adding the properties in the dispatcher file:
"normalizePunctuation": true/false
"normalizeDiacritics": true/false

Commands are not working after launching the command. After checking on the LUIS portal, I don't see that the option is turn on/off. Please take a look on this.

What are the steps to reproduce this issue?

Create a dispatcher file
put option : "normalizePunctuation": true (for example)
and do a refresh

What were you expecting to happen?
Options working in LUIS app.

Can you share any logs, error output, etc.?
Any screenshots or additional context?

**Comment by v-kydela** [comment]
Closing to address here: https://github.com/microsoft/botbuilder-tools/issues/1477
