### ISSUE TITLE
Unable to see messages sent from Live Person Agent to Bot User using LivePersonProxyBot Sample

### ISSUE THREAD

**Issue by modusandrew** [microsoft/BotBuilder-Samples#2882]
## Sample information
1. Sample type: 
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot

2. Sample language: dotnetcore

3. Sample name: LivePersonProxyBot

## Describe the bug
User is not receiving chat messages back from agent when using https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot

## To Reproduce

Step 1: Setup ngrok so https://[Your Generated URL].ngrok.io points to http://localhost:3978 (port of LivePersonProxyBot). 
<img width="846" alt="Screen Shot 2020-10-30 at 11 29 16 AM" src="https://user-images.githubusercontent.com/55599469/97724330-26549180-1aa3-11eb-9d7b-1907c5bad97c.png">

Step 2: Configure all 5 webhooks with ngrok url.
<img width="907" alt="Screen Shot 2020-10-30 at 11 30 14 AM" src="https://user-images.githubusercontent.com/55599469/97724437-497f4100-1aa3-11eb-8b2e-58bfffc3e286.png">

<img width="973" alt="Screen Shot 2020-10-30 at 11 30 43 AM" src="https://user-images.githubusercontent.com/55599469/97724485-5ac84d80-1aa3-11eb-850e-e035176147b7.png">

<img width="976" alt="Screen Shot 2020-10-30 at 11 31 22 AM" src="https://user-images.githubusercontent.com/55599469/97724561-716ea480-1aa3-11eb-8ec0-f910832e1e15.png">

Step 3: Setup the Bot Emulator.
<img width="500" alt="Screen Shot 2020-10-30 at 11 31 55 AM" src="https://user-images.githubusercontent.com/55599469/97724621-85b2a180-1aa3-11eb-8096-7b0d99d1253d.png">

Step 4: Change the following appsettings in the sample project to match your bot and Live Person Account
-LivePersonAccount
-LiverPersonClientId
-LivePersonClientSecret
-MicrosoftAppId
-MicrosoftAppPassword

Step 5: Run the sample project in Visual Studio.

Step 6: Trigger handoff by typing "Agent" and then "Can you see me?".
<img width="924" alt="Screen Shot 2020-10-30 at 11 34 56 AM" src="https://user-images.githubusercontent.com/55599469/97724936-f1950a00-1aa3-11eb-8dc7-321f4bb40f75.png">

Step 7: Verify Agent can see user and "can you see me?" message in the Live Person Agent Workspace.
<img width="1021" alt="Screen Shot 2020-10-30 at 11 35 48 AM" src="https://user-images.githubusercontent.com/55599469/97725030-0ffb0580-1aa4-11eb-801d-08bad2392d60.png">

Step 8: From the Agent Workspace, type a message back to the user.
<img width="984" alt="Screen Shot 2020-10-30 at 11 36 27 AM" src="https://user-images.githubusercontent.com/55599469/97725109-27d28980-1aa4-11eb-9719-e3985c55b4fb.png">

## Expected behavior
User is expected to see the message typed by agent in the Live Person Agent Workspace.

## Actual Behavior
User does not see agent's reply.  Also, ngrok console is showing HTTP 401 Error for api/liveperson/contentevent
![Screen Shot 2020-10-30 at 3 21 02 PM](https://user-images.githubusercontent.com/55599469/97748234-878c5d00-1ac3-11eb-87c4-f6e03b330b3e.png)

## Additional Comments
I was able to debug and determine the issue is related to the Authenticate method in the LivePersonController.cs file located in the LivePersonConnector Project.

The following appears to be happening:

1. Accepts the request and HTTP Post body as parameters. (as expected)
2. Checks if all 3 required headers exist (X-Liveperson-Signature, X-Liveperson-Client-Id, X-Liveperson-Account-Id).  They do and they’re all correct. (as expected)
3. Creates our own SHA1 Signature using the HTTP Body they sent against the LP Live Person Secret stored in our configuration file. (as expected)
4. Compares the SHA1 Signature we generated to the signature they sent in the X-Liveperson-Signature header. (as expected)

However both signatures don’t match.  All configuration settings are correct in our appsetting.json file (LivePersonAccount, LivePersonClientId and LivePersonClientSecret).

The c# source code references Live Person's documentation below:
https://github.com/LivePersonInc/developers-community/blob/ae8890694cb9b3be797ca382e9ad7395382aed25/pages/documents/MessagingChannels/ConnectorAPI/webhooks/security.md#authentication

The sample below appears to be doing the same thing as the c# code.
![Screen Shot 2020-10-30 at 3 27 43 PM](https://user-images.githubusercontent.com/55599469/97748826-76901b80-1ac4-11eb-994b-47e04f2f766a.png)

At this time, we're unsure if there was a change to this project or if Live Person made any changes (or if it's something else we did wrong).  We contacted Live Person as well and are hoping to confirm.

**Comment by arturl** [comment]
@modusandrew, does the code return `Unauthorized` after comparing the signature or after comparing AccountID/ClientID?
For signature mismatch, I'm slightly suspicious of this line:
```
var hash = hmac.ComputeHash(Encoding.ASCII.GetBytes(body));
```
This probably needs to be UTF8 and not ASCII. Can you try that and tell me if it makes a difference?

If the issue is caused by AccountID/ClientID, this is most likely a legit issue -- check that these parameters are specified correctly (they come from the appsettings file)

**Comment by modusandrew** [comment]
Hi thank you for the information.  Changing Encoding from ASCII to UTF8 indeed fixes the Authorize issue.  
Authorization now works, and gets me a little farther since Webhook events like ExConversationChangeNotification are successful and show as HTTP 200 responses.

However the /api/liveperson/contentevent is giving a 500 Internal Server Error.  Debugging the source code it looks like the problem is happening in line 176 below.

**if (_conversationMap.ConversationRecords.TryGetValue(change.conversationId, out conversationRec))**

The _conversationMap.ConversationRecords.TryGetValue is not finding an item with the same change.conversationId.  The collection does have 2 items in it but they have different conversation ids.

![Screen Shot 2020-11-02 at 3 21 27 PM](https://user-images.githubusercontent.com/55599469/97915207-16e17c80-1d1f-11eb-94bf-44b4260108d7.png)

**Comment by arturl** [comment]
Thanks for confirming the ASCII vs. UTF8 issues, I'll submit a fix for that shortly (or feel free to submit a PR since you already have it). 
Are you running a multi-instance bot? The sample uses in-memory storage as an example which needs to replaces with durable storage (SQL, CosmosDB, Azure Table etc.) for a production implementation. 
Try logging creation of conversation records. Did you see if the conversation you're looking for was ever added to the conversationMap?

**Comment by mrivera-ms** [comment]
@modusandrew, do you have any updates for this issue? Thank you.

**Comment by EricDahlvang** [comment]
Hi @dileepkantapop 

Artur mentioned replacing MemoryStorage with a persistent IStorage implementation. This documentation shows how to add a CosmosDb storage:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#cosmos-db-implementation

**Comment by dileepkantapop** [comment]
Hi @EricDahlvang We found out the issue, it is because we have added scale up to our app service. So the conversation records of live person are in the bot memory. After scale down to 1 instance in app service the bot works fine. 

We have already added IStorage for the bot. The bot state is storing fine in Istorage. But the LIveperson conversationmap is not storing in Istorage. Can you help why this issue is happening?
