### ISSUE TITLE
Link Unfurl teams app erroring out when botframework link is typed in teams and OnTeamsAppBasedLinkQueryAsync method is not getting hit 

### ISSUE THREAD

**Issue by sanal5677** [microsoft/BotBuilder-Samples#2887]
I have created a teams bot  to do link unfurl by following the location - https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/55.teams-link-unfurling readme. 

I have installed the app in my teams using the custom app installation by zipping the manifest.  I am getting the error "Unable to reach the app.Please try again" after typing the botframework link (https://dev.botframework.com). I debugged the application and it wasnt hitting the OnTeamsAppBasedLinkQueryAsync. 

Note: When I added the app it was giving me option to only "Add for me". The app wasnt visible anywhere else than in the search window on top of teams.

Can you let me know if I am missing out on anything.

**Comment by EricDahlvang** [comment]
Hi @sanal5677 

I'm sorry you've run into this issue? Have you tried installing the bot in a Team, this might require changing the scopes in your manifest ? Does it work for link unfurling in a personal scope after that?

**Comment by EricDahlvang** [comment]
Closing.  Sanal and I worked through this offline.
