### ISSUE TITLE
orchestrator: Unable to find Luis application name as intent

### ISSUE THREAD

**Issue by ambuj74** [microsoft/BotBuilder-Samples#2907]
I am trying to use orchestrator as a replacement to dispatcher where I am exporting .lu files for multiple Luis applications and trying to create a snapshot(i.e.  .blu files) here i am facing two issues:
1.how to create a single snapshot(.blu file) from multiple .lu or .qna files.
2.I am unable to find Luis application name as intent name,  in place of that I am getting intent name present  inside the Luis application.
Following is the link i followed, but I am not able to get the clear idea regarding my [issues](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/orchestrator)
@tsuwandy @KoradaRajesh

**Comment by tsuwandy** [comment]
@ambuj74, the create commands needs the "--hierarchical" flag, something like the following:
bf orchestrator:create --hierarchical --in ./CognitiveModels --out ./generated --model ./model

This sample demonstrates dispatch scenario using Orchestrator.
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/orchestrator/csharp_dotnetcore/01.dispatch-bot

Let me know if you need any more info.  Thanks!

**Comment by KoradaRajesh** [comment]
Thanks @tsuwandy It's working

Do we really need to download .lu or .qna files everytime whenever we add new intents in Luis or QnA and generate new .blu

We have dispatch refresh command to refresh dispatcher and add automatically new created intents into dispatcher.
Do we have something like this in Orchestrator?

**Comment by tsuwandy** [comment]
@KoradaRajesh, thanks for the update.  Let me think what we could do on the bf orchestrator cli side to make it easier to refresh.

**Comment by mrivera-ms** [comment]
@tsuwandy I am assigning this to you. Seems like it is resolved. If it is, please feel free to close it. Thank you.

**Comment by tsuwandy** [comment]
@KoradaRajesh, i'm going to create a tracker work item on our internal repo for refresh.  Closing this one.  Thanks!
