### ISSUE TITLE
Orchestrator: How to download the .lu files from Luis or .tsv files from QNA using cli commands  

### ISSUE THREAD

**Issue by ambuj74** [microsoft/BotBuilder-Samples#2917]
I am trying to use orchestrator as a replacement to dispatcher where I am exporting .lu files for multiple Luis applications and trying to create a snapshot(i.e. .blu files), here I am downloading the .lu files from Luis manually but I want to download the .lu files using cli commands or programmatically for my requirement . Is that feature available?.

I am using the following sample:
 https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/orchestrator/csharp_dotnetcore/01.dispatch-bot
@tsuwandy

**Comment by tsuwandy** [comment]
@ambuj74 , let me take a look a the bf luis commands...

**Comment by ambuj74** [comment]
@tsuwandy I am able to download the .lu files from Luis using the following command -:
luis export version --appId <YOUR-LUIS-APP-ID> --versionId <YOUR-LUIS-APP-VERSION> | ludown refresh --stdin -o c:\test -n app1.lu
But, I am facing issue in downloading the .tsv file from QNA maker , I am using following command to download .tsv fie from QNA but the command is not working-:
qnamaker export kb --kbId <YOUR-KB-ID> --environemnt <TEST-OR-PROD> --hostname <YOUR-HOST-NAME> --endpointKey <YOUR-ENDPOINT-KEY> --subscriptionKey <YOUR-SUBSCRIPTION-KEY> | ludown refresh --stdin -o c:\test -n kb1.lu
@KoradaRajesh

**Comment by tsuwandy** [comment]
@munozemilio, could you take a look at the qna export command above?

**Comment by munozemilio** [comment]
Hello @ambuj74, by looking at your reply I see you are using deprecated and outdated commands. I would recommend you to use bf cli with bf luis command group. For the qnamaker I just checked on their api documentation and I didnt find a way to download a kb as tsv. BF cli supports downloading the kb as json and transform it to qna format. Let me know if that helps

**Comment by KoradaRajesh** [comment]
@munozemilio If you provide reference link it would be helpful

**Comment by tsuwandy** [comment]
@KoradaRajesh, here it is:  
https://github.com/microsoft/botframework-cli/tree/main/packages/qnamaker

**Comment by ambuj74** [comment]
hi @munozemilio,using the the following command 
bf qnamaker:kb:export --environment=Prod --kbId < your kbid> --qnaFormat --subscriptionKey<your subscription key>  ><name of the file>
 I am  able to download the file from qna and also able to convert it to .blu  but when i tried to export the file from another qna and then convert it to .blu, I am getting error for that particular qna .

**Comment by KoradaRajesh** [comment]
## ? how to download files from yammer
Steps to download files from yammer/n
Procedure to download files from yammer
guide me to download files from yammer
download files from yammer

```markdown
To download files from yammer follow the steps. 

1. Go to the Home. 

2. Go to the group. 

3. Click on Files. 

4. Look for the File. 

5. Open File. 

6. Click on **Download**. 

![img](https://dl.dropboxusercontent.com/s/bf63w3m03te0y3k/DwnldYamFile.png)</msg>
```
when I'm downloading the .qna file the questions in it are not formated with "**-** question" and some questions are getting with **\n** these causing issue while creating .blu file

![Uploading image.png…]()

**Comment by tsuwandy** [comment]
@ambuj74 , @KoradaRajesh, could you email me the .qna file causing issue?  tien.suwandy@microsoft.com.  Thanks!

**Comment by tsuwandy** [comment]
@KoradaRajesh, how did you get the .qna file (which caused the orchestrator:create command to fail)?  I assume it's from bf qnamaker:export command?  I see the '\n', removed them but it's still failed .qna file parsing.   Trying to figure out which part of the file failed in parsing still.

**Comment by KoradaRajesh** [comment]
In some questions we are getting with out prefix "-", try to add it then you can able to format into .blu 

we are getting like below

## ? how to delete post of yammer
how should I delete yammer post
delete post of Yammer

```markdown
Let me share you delete steps
```

Make it to 

## ? how to delete post of yammer
- how should I delete yammer post
- delete post of Yammer

```markdown
Let me share you delete steps
```

**Comment by KoradaRajesh** [comment]
Is there any bfcommand to export .tsv file from qnamaker

**Comment by tsuwandy** [comment]
@KoradaRajesh, bf CLI uses QnA Maker APIs.  I don't find anything here which allows for export to .tsv format.  https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker4.0/knowledgebase/download

I'll check with QnA Maker team...

**Comment by tsuwandy** [comment]
@KoradaRajesh , there should be a new version of the bf orchestrator plugin (https://www.npmjs.com/package/@microsoft/bf-orchestrator-cli) deployed to npmjs in a few hours.  This version allows a qna kb in .tsv format as input to bf orchestrator:create command.  kb in .tsv format can be downloaded from qnamaker.ai portal.  I tried exporting as .qna file via this command: 

bf qnamaker:kb:export --kbId 315ac233-5d1d-4744-8eb9-62555dda4764 --subscriptionKey b8f005c73e774ee2979351b00286c4dc --qnaFormat >> x.qna 

and was able to use the .qna file as input to the bf orchestrator:create command as well.  

To install latest version of bf orchestrator plugin, uninstall previous version and then run install command again.
>bf plugins:uninstall @microsoft/bf-orchestrator-cli
>bf plugins:install @microsoft/bf-orchestrator-cli@beta

**Comment by tsuwandy** [comment]
@KoradaRajesh, let me know if you have issues with the latest bf orchestrator cli plugin.  You should be able to use exported qna kb (from qnamaker.ai portal in tsv format) as input to the create command.

Feel free to reactivate if you are still seeing issues.  Thanks!

**Comment by tsuwandy** [comment]
Opened a feature request for bf luis:version:export to directly export to a .lu format.

https://github.com/microsoft/botframework-cli/issues/1078
