### ISSUE TITLE
Sample 51. The button of the messaging extension is not displayed on android mobile device

### ISSUE THREAD

**Issue by IreneG0802** [microsoft/BotBuilder-Samples#2918]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore and javascript
3. Sample name: 51.teams-messaging-extensions-action

## Describe the bug
The button of the messaging extension is not displayed on android mobile device, but it does on the web application.

## Expected behavior
The example should work on any device.

**Comment by clearab** [comment]
My apologies for the delayed response. I'm digging into this with the Teams group, but this seems like a regression in the current build of the Android Teams client.

**Comment by anbah34** [comment]
@IreneG0802 could you please help me with what app version you are facing this issue? When you mean message extension not displayed, are you referring to the '+' button in the compose box?

**Comment by IreneG0802** [comment]
Yes, I used the trunk version and using the '+' button does not show the messaging extension icon.
I attach screenshots: the first two from mobile and the last from
![MicrosoftTeams-image](https://user-images.githubusercontent.com/72894188/100202938-404a8e00-2f02-11eb-8b47-7f8889046ce3.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72894188/100202942-40e32480-2f02-11eb-8586-9c6f97e833e7.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/72894188/100203000-4f314080-2f02-11eb-8e79-7876f1ef0718.png)

**Comment by anbah34** [comment]
@IreneG0802  - Thanks. I see the messaging extensions displayed in the screenshot that you have attached. 
![image](https://user-images.githubusercontent.com/65276405/100698499-a3369c00-33be-11eb-8efb-79c95d69d085.png)

The apps in the more menu on mobile (as seen in the 2nd screenshot that you posted) are personal apps/ bots and not messaging extensions.


Were you seeing any messaging extensions missing on mobile, compared to desktop? (The same should be available across both)

**Comment by IreneG0802** [comment]
The application of this example is shown on the web, When using "..." in a channel, the icon of the messaging extension (action messaging ...) appears as it is surrounded in blue in the first image. This icon is not shown on the mobile (image 2) using "+" button in the compose box.
![image](https://user-images.githubusercontent.com/72894188/100709476-7bd7d300-33ae-11eb-85da-6adfbf3eaf0f.png)
![image](https://user-images.githubusercontent.com/72894188/100711094-133e2580-33b1-11eb-9c59-a0db9b38bf38.png)

**Comment by anbah34** [comment]
@IreneG0802 have you sideloaded this application (Action Messaging)?

**Comment by IreneG0802** [comment]
Yes, it can be seen in the first image.

**Comment by anbah34** [comment]
@IreneG0802 could you share the manifest with my team, we will look into why the app is not synced

**Comment by IreneG0802** [comment]
The manifest is the same as the example, with my Microsoft app-id.

**Comment by IreneG0802** [comment]
Something new?

**Comment by anbah34** [comment]
@IreneG0802 The issue has been fixed by the engineering team but he fix will be only available in Jan end as we don't have a release on the iOS app happening this month

**Comment by IreneG0802** [comment]
Ok, thanks!

**Comment by taicchoumsft** [comment]
@anbah34 , can you add a link to track this issue on the Teams side?

**Comment by anbah34** [comment]
Here it is - https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1373069

**Comment by Wajeed-msft** [comment]
@tacri - This is being tracker here: https://github.com/MicrosoftDocs/msteams-docs/issues/2466

@IreneG0802 - Please follow [this issue](https://github.com/MicrosoftDocs/msteams-docs/issues/2466) for updates/progress/questions.

**Comment by clearab** [comment]
[deleted link to internal tracking system]
