### ISSUE TITLE
dialog:generate plugin: not able to evaluate a reference in an LG file

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotBuilder-Samples#2953]
## Sample information
1. Sample type: \experimental\generation
2. Sample language: --
3. Sample name: --

## Describe the bug
When I generated a form dialog with **bf dialog:generate**, the bot gives me an error message:

> sandwich.en-us.lg:No such template ‘CompleteConfirmation_Name’. [propertyName] Error occurred when evaluating ‘-${template(${property}_Name)}’. [displayOperation] Condition ‘${op && property && entity.value}’: Error occurred when evaluating ‘-${operationName(op)} “${entity.text}” to ${propertyName(property)}’. [chooseEntity] Error occurred when evaluating ‘-${displayOperation(property.operation, property.property, property.entity)}’. [chooseProperties] Error occurred when evaluating ‘-Did you mean ${join(foreach(turn.dialogevent.value, choice, chooseEntity(choice)), " or ")}?’. [__temp__474b1a1e1da54179b28a2518a3201a27] Error occurred when evaluating ‘-${chooseProperties()}’.

## To Reproduce
1. Install the nightly build for the **bf** cli and the dialog:generate plugin. 
I was using **bf** version `@microsoft/botframework-cli/4.12.0-dev.20201118.1cb4bee win32-x64 node-v12.18.3`
and **bf dialog:generate** version `@microsoft/bf-generate 4.10.0-daily.20201112.185066`

2. Create the bot. I used the sandwich.schema example here: [https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas](url) so the command was:
`bf dialog:generate sandwich.schema -o sandwich-bf-1123b`

3. Build and run the bot:
`cd sandwich-bf-1123b`
`build`
`run`

4. Connect to the bot in Emulator. Start talking.

5. I hit this error at the second prompt:
![image](https://user-images.githubusercontent.com/39317542/100036766-afff3280-2db5-11eb-8f94-ca0ca31ee50c.png)

and I think this error appeared in the console at the same time:
![image](https://user-images.githubusercontent.com/39317542/100036910-f2287400-2db5-11eb-94d7-36b101e853ce.png)

Error text:
> fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
>       Exception caught : sandwich.en-us.lg:No such template 'CompleteConfirmation_Name'. [propertyName]  Error occurred when evaluating '-${template(`${property}_Name`)}'. [displayOperation] Condition '${op && property && entity.value}':  Error occurred when evaluating '-${operationName(op)} "${entity.text}" to ${propertyName(property)}'. [chooseEntity]  Error occurred when evaluating '-${displayOperation(property.operation, property.property, property.entity)}'. [chooseProperties]  Error occurred when evaluating '-Did you mean ${join(foreach(turn.dialogevent.value, choice, chooseEntity(choice)), " or ")}?'. [__temp__474b1a1e1da54179b28a2518a3201a27]  Error occurred when evaluating '-${chooseProperties()}'.
> 

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by hatpick** [comment]
FYI @coldplaying42 @chrimc62
