### ISSUE TITLE
type: string generates assets with ${property} in file names and content

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotBuilder-Samples#2957]
To repro use a simple schema like this:
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        }
    },
    "required": [
        "name"
    ]
}

If you generate when doing the stringEntity it will use genericEntity which has ${property} in it.

**Comment by hatpick** [comment]
duplicate #2956
