### ISSUE TITLE
please provide nodejs sample for token exchange(SSO) between root bot and skill bot

### ISSUE THREAD

**Issue by jonathanhotono** [microsoft/BotBuilder-Samples#2974]
please provide NodeJS/TypeScript sample for token exchange(SSO) between root bot and skill bot.
Also is this method supported in other authentication methods like Generic Oauth 2?

As per page below:
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab060f59-0fc6-d90d-6b71-a0756f1a8aa0
* Version Independent ID: f7574aeb-0002-5e07-47ed-3d135a42f4ce
* Content: [Add Single sign on to a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml)
* Content Source: [articles/v4sdk/bot-builder-authentication-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication-sso.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by tonyanziano** [comment]
Hi @jonathanhotono ,

This is currently being tracked via the following issue, and is scheduled to be completed for the upcoming release.

https://github.com/microsoft/BotBuilder-Samples/issues/2811

Currently, a [C# sample for this exists](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/sso-with-skills), so you can possibly look to that sample for the high-level concepts on what it takes to accomplish what you're trying to do.
