### ISSUE TITLE
ERROR: Failed building wheel for cryptography

### ISSUE THREAD

**Issue by CharingJC** [microsoft/BotBuilder-Samples#2977]
## Sample information
1. Sample type: [\samples\]
2. Sample language: I choose [python] coz I am a snake
3. Sample name: <EchoBot>

## Describe the bug.
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 
517 and cannot be installed directly

## To Reproduce
pip install -r requirements.txt

## Screenshots
![image](https://user-images.githubusercontent.com/74894646/101458842-5d577600-3972-11eb-887d-b025c3ff52f6.png)

**Comment by CharingJC** [comment]
![image](https://user-images.githubusercontent.com/74894646/101459757-99d7a180-3973-11eb-844e-3e239b83eddc.png)

**Comment by CharingJC** [comment]
FYI 

https://github.com/microsoft/botbuilder-python/commit/eaa65f8c1f17d43b0691f1093617df01d47f01d1

**Comment by tonyanziano** [comment]
We will check to see if our samples pin the cryptography version at 3.2 and get back to you.

**Comment by jwiley84** [comment]
None of our samples pin cryptography at any level. Your error states that botframework-connector requires cryptography at 2.8.0; can I ask why you're pinning to 3.2?

**Comment by jwiley84** [comment]
I'll look into this, see why the  bot isn't building if cryptography is supposed to be 3.2. Does the same occur if you use 2.8.0 anyway?

**Comment by CharingJC** [comment]
> I'll look into this, see why the bot isn't building if cryptography is supposed to be 3.2. Does the same occur if you use 2.8.0 anyway?

Thank you for the response❤ If l left the default requirements.txt it will be 2.8. And the first screen capture shows the Err Msg I met by using default requirements.txt (cryptography 2.8)

**Comment by CharingJC** [comment]
Dear Jessica,

Hope you are doing well.
The issue was when not pin cryptography, I got the error msg of unavailable to build.
After pin the version to 3.2 I can build but still have the un-match message.
Have a nice day mate

BR,
Juncheng
________________________________

**Comment by axelsrz** [comment]
@CharingJC I noticed you're using python 3.9, that could be causing problems at the moment of building the cryptography package version 2.8. In the [readme](https://github.com/Microsoft/botbuilder-python#prerequisites) section for the SDK we recommend Python 3.8, could you check with that?

Also, problems building cryptography are usually because of other packages in your python environment, or missing dependencies in your system, I was unable to reproduce this issue in a clean python 3.8 installation (using cryptography 2.8)

Let me know if you have further questions.

**Comment by CharingJC** [comment]
Hi Axel，

Thank you so much for pointing it out.
I will have a try with python 3.8

BR,
Juncheng

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexbprofit** [comment]
![image](https://user-images.githubusercontent.com/57172679/111658922-785d4000-8815-11eb-9654-2275c6452100.png)
![image](https://user-images.githubusercontent.com/57172679/111658976-8317d500-8815-11eb-95eb-e888ba7cda01.png)
![image](https://user-images.githubusercontent.com/57172679/111659128-a478c100-8815-11eb-8f28-19653a6206fb.png)
![image](https://user-images.githubusercontent.com/57172679/111659190-b35f7380-8815-11eb-899e-16b057015b7c.png)
![image](https://user-images.githubusercontent.com/57172679/111659295-c8d49d80-8815-11eb-95d7-ecc80a039f70.png)
I have similar problem.

**Comment by alexbprofit** [comment]
pip 19.2.3
python 3.8.5 with Conda environment
windows 10 x64
