### ISSUE TITLE
botframework-connector 4.11.0 requires msal==1.2.0, but you'll have msal<2.0.0,>=1.6.0 by azure-sdk-for-python

### ISSUE THREAD

**Issue by CharingJC** [microsoft/BotBuilder-Samples#2978]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [python]
3. Sample name: <Name of the sample>

## Describe the bug
dependency conflict

## To Reproduce
pip install 
pip install -r requirements.txt

## Expected behavior
Is there any further plan on this?

## Screenshots
![image](https://user-images.githubusercontent.com/74894646/101464773-09e92600-397a-11eb-9208-75db8ae9aae1.png)

## Additional context
https://github.com/Azure/azure-sdk-for-python/search?l=Text&q=msal
https://github.com/microsoft/botbuilder-python/blob/main/libraries/botframework-connector/requirements.txt

**Comment by jwiley84** [comment]
Please let us know what sample this occurs in so that we can pin msal to 1.2.0 in it?

**Comment by CharingJC** [comment]
> Please let us know what sample this occurs in so that we can pin msal to 1.2.0 in it?
Thank you for the response❤ this is not for a specific sample. From botbuilder-python dependency, botframework-connector 4.11.0 requires msal==1.2.0

**Comment by CharingJC** [comment]
Any update mate?

**Comment by CharingJC** [comment]
Dear Jessica,

I have replied in the dialog.

botframework-connector 4.11.0 requires msal==1.2.0, but you'll have msal<2.0.0,>=1.6.0 by azure-sdk-for-python

This is conflict between bot connector and auth process dependency

BR,
Juncheng
________________________________

**Comment by asdkant** [comment]
I'm also hitting this issue. Any recommendation on which versions to pin to to work around this?

**Comment by asdkant-ey** [comment]
I've submitted an issue to the botbuilder-python repo which mantains the library that introduced the dependency conflict: https://github.com/microsoft/botbuilder-python/issues/1450

**Comment by gabog** [comment]
Closing as it is being tracked in https://github.com/microsoft/botbuilder-python/issues/1450
