### ISSUE TITLE
Auth on my custom api

### ISSUE THREAD

**Issue by brunokunace** [microsoft/BotBuilder-Samples#2979]
Have any sample (nodejs) with login in my custom api and send after the bearer token inside each request?

like Asana App (tabs) makes login (open url in iframe) after this, can list itens in cards.

**Comment by CharingJC** [comment]
https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/18.bot-authentication/dialogs/mainDialog.js

**Comment by brunokunace** [comment]
Yes, like this, but without using oauth, my api use a jwt token auth based, on browser iam using a localstorage to save a token and use it on axios default header

**Comment by jwiley84** [comment]
Hi @brunokunace 

The bot framework team prefers that **How-To** questions be asked on StackOverflow using the [botframework tag](https://stackoverflow.com/questions/tagged/botframework).

I would start with this doc here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0
