### ISSUE TITLE
Port SSO for skills dotnet sample to JS

### ISSUE THREAD

**Issue by gabog** [microsoft/BotBuilder-Samples#2980]
## Summary

This issue should be started once https://github.com/microsoft/BotBuilder-Samples/pull/3673 is merged. 

The sample in the pull request needs to be ported to JS .

The docs references to the ported samples need to be updated too.

**Comment by gabog** [comment]
@swagatmishra2007, please review this one when is done to make sure everything looks good.

**Comment by johnataylor** [comment]
@swagatmishra2007 it would be great if you can review the PR when it's ready.

**Comment by stevengum** [comment]
@mdrichardson has agreed to port the sample; I've assigned Swagat to the issue as GitHub isn't letting me assign Michael 😞

**Comment by mdrichardson** [comment]
Per conversation w/ @gabog, there isn't a customer-friendly sample ready to port just yet.

**Comment by mdrichardson** [comment]
@gabog I can't remember where we're sitting on this. Should it be pushed off R12?

**Comment by gabog** [comment]
@JuanAr #3673 has been merged, you guys can start working on this one when you have time, Let me know if you have any questions (you can use the changes in the PR as a reference on what needs to be done).
