### ISSUE TITLE
Single messaging extension auth sample for all types of commands

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#2988]
- Start with sample 52, the combined sample will replace this one.
- Follow the structure/design/conventions in that sample.
- Remember that code from these samples is inserted directly into documentation articles. Avoid unnecessary amounts of extraction into helper methods/functions as it makes it very difficult to add into documentation
  - In order for the sample to be merged
  - It will have to be ported into all the other languages
  -documentation updated to reflect
  - readme index updated

In the sample itself
- Non SSO OAuth for:
  - Search command
  - Action command
  - Link unfurling
- Configuration page for Search command

PR with Action command sample here: https://github.com/microsoft/BotBuilder-Samples/pull/2954

## Tracking

**C#** [ ] [PR](https://github.com/microsoft/BotBuilder-Samples/pull/3007)
**JS** [ ]
**TS** [ ]
**Python** [ ]
**Java** [ ]

**Comment by Trinetra-MSFT** [comment]
@clearab , Thanks, Picking up this request.

**Comment by Trinetra-MSFT** [comment]
Hi @clearab ,
I would like to tell you that I have integrated following changes in existing sample.
1. Authentication in ME for Action command
2. Authentication in ME Link Unfurling

I've done this for following language as of now.
`C#`
`JavaScript/Node JS`
