### ISSUE TITLE
generic key not found exception every time on starting a new bot application in visual studio

### ISSUE THREAD

**Issue by mounikakalluri** [Microsoft/BotBuilder-Samples#299]
### Problem Description

![mvc issue](https://user-images.githubusercontent.com/10280224/44907102-84a34f80-ad34-11e8-86b2-9f7116711fcb.JPG)

**Comment by stevkan** [comment]
Please provide more information.

**Comment by EricDahlvang** [comment]
@mounikakalluri  Where did you obtain the vsix bot template you're using?

**Comment by mounikakalluri** [comment]
I obtained it from the Microsoft visual studio online installation page,as
it was giving error i tried out by uninstalling and reinstalling again but
the problem persisted.Is there any solution for this??I would be very
thankful if you would let me know.

Thank you
Mounika
