### ISSUE TITLE
Disable send message button while waiting for bot to response

### ISSUE THREAD

**Issue by aldvintumbelaka** [microsoft/BotBuilder-Samples#3006]
Hi,

I'm looking for solution to disable send message button while waiting for bot to response.
Because when user type multiple messages, bot will now reply it multiple times that might add confusion to user.

For example:
User: Hi
User: I have an issue with my computer
User: I cannot logged in properly
User: I'm using surface pro 6 with windows 10 OS

In this case, bot will reply it multiple times:
Bot: Hi, how can I help you? (replying to user's first message)
Bot: Do you mean "issue with laptop", "issue with surface"? (replying to user's second message)
Bot: Hi, I can help you with that. What is your device type? (replying to user's third message)
Bot: Sorry, I don't understand that. (replying to user's fourth message)

It will add lots of confusion to user because the answer that bot provided are different for every single message from the user.

Thanks

**Comment by stevkan** [comment]
@aldvintumbelaka, what channel is this for? It sounds like Web Chat, but can you clarify? Whether a button is enabled / disabled is a feature of the hosting site and not of the bot.

**Comment by aldvintumbelaka** [comment]
@stevkan it will be for microsoft teams

**Comment by stevkan** [comment]
@aldvintumbelaka, disabling a button that is specific to the Teams UI falls outside the functionality of the BotFramework. You will need to communicate with the Teams development team to determine if this is even possible, or to suggest as a feature request. Their community forum can be located at [Teams UserVoice](https://microsoftteams.uservoice.com/).
