### ISSUE TITLE
scheduling microsoft teams meeting programatically using c# mvc   

### ISSUE THREAD

**Issue by bkumar12334** [microsoft/BotBuilder-Samples#3011]
I have  a question regrading Microsoft teams.

can we programmatically schedule  teams meeting using c# code. is this possible ?

leads are appreciated.

**Comment by clearab** [comment]
You have two options:

- You can create a deeplink to the scheduling dialog that when clicked will create a stubbed-out meeting the user can then finalize: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#linking-to-the-scheduling-dialog
- You can use MS Graph APIs to create calendar items (requires Graph permissions and authentication): https://docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?view=graph-rest-1.0

**Comment by bkumar12334** [comment]
Thanks for your response. 

i have question on the second link that you provided. Is this applicable for Teams . it looks like out look.(both are Microsoft).

may be i got confused.

**Comment by clearab** [comment]
Meetings in Teams and meetings in Outlook are backed by the same calendar, so yes scheduling a meeting using the Graph APIs would create a Teams meeting. For an example of using Graph APIs from a bot, you can take a look at sample #46.
