### ISSUE TITLE
Remove DialogExtensions.cs file no more valid.

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotBuilder-Samples#3020]
**Describe the solution you'd like**
DialogExtensions.cs file is no more required in the project samples. path ....\csharp_dotnetcore\adaptive-dialog\..
will remove this file.

@EricDahlvang is that fine ? shall I create PR.

**Comment by EricDahlvang** [comment]
@rvinothrajendran you are correct, that class is no longer needed in the sample as it is now provided in the sdk.  However, I believe we are moving the adaptive-dialog folder to experimental at some point.

**Comment by rvinothrajendran** [comment]
@EricDahlvang I removed those files If you like it merge the changes 😎

**Comment by EricDahlvang** [comment]
Thanks @rvinothrajendran
