### ISSUE TITLE
Port [52.teams-messaging-extensions-search-auth-config] Sample code enhancement for Action and link unfurling authentication

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#3027]
**Is your feature request related to a problem? Please describe.**
Port these additions to javascript, python and java samples:
https://github.com/microsoft/BotBuilder-Samples/pull/3007

**Comment by Trinetra-MSFT** [comment]
Hi @EricDahlvang 
yes it was related to an issue raised over here: [https://github.com/microsoft/BotBuilder-Samples/issues/2988](https://github.com/microsoft/BotBuilder-Samples/issues/2988), This is now completed for C#, JavaScript

**Comment by tracyboehrer** [comment]
Teams samples moved out of BF Samples
