### ISSUE TITLE
Refactor sample 57

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#3031]
The messageAllMembers functionality in sample 57 needs to be refactored. As written, it is encouraging developers to call createConversation repeatedly, and is difficult to read. We need to separate out the create and continue calls, and use in-memory storage to save the conversation reference.

**Comment by clearab** [comment]
It may make more sense to pull the proactive portion out of this sample entirely, and refactor sample 58 into a proactive messaging sample all-up (sending proactive to the various constructs, using a something outside of the turnContext to send the messages to make it more clear).

**Comment by clearab** [comment]
For additional context, see the conversation here: https://gitter.im/OfficeDev/MicrosoftTeamsAppDev?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications#

**Comment by HiltonGiesenow** [comment]
@clearab thanks for creating this issue - I'm more than happy to help out on this.

**Comment by clearab** [comment]
@EricDahlvang let's talk about this one next week

**Comment by tracyboehrer** [comment]
No more Teams samples in BF Sample.
