### ISSUE TITLE
Does team-sso Show Token?

### ISSUE THREAD

**Issue by Ronnie-personal** [microsoft/BotBuilder-Samples#3034]
Hi there,
I'm able to setup bot based on team-sso sample.
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore

I didn't get any error, but it does not show token as the the other sample team-auth
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth

Can you please advise what's the expected behavior? or can you please add some code to show token?

![image](https://user-images.githubusercontent.com/76408835/105106892-d2938c00-5a84-11eb-90f2-03b4be985413.png)

**Comment by jwiley84** [comment]
Hi @Ronnie-personal !

The other samples are coded to show your token. I"ll take a look, see if the Teams-SSO sample is supposed to do the same, and show you the code for it.

**Comment by jwiley84** [comment]
'''
private async Task<DialogTurnResult> DisplayTokenPhase2Async(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            var tokenResponse = (TokenResponse)stepContext.Result;
            if (tokenResponse != null)
            {
                await stepContext.Context.SendActivityAsync(MessageFactory.Text($"Here is your token {tokenResponse.Token}"), cancellationToken);
            }

            return await stepContext.EndDialogAsync(cancellationToken: cancellationToken);
        }
'''

This is from the Teams SSO sample. does it not show your token? I'll play around with the sample, see what's going on.

**Comment by Ronnie-personal** [comment]
@jwiley84  Thank you for looking into it. Look forward to collaboration!

**Comment by Ronnie-personal** [comment]
@jwiley84 
FYI Here are the steps for my setup
https://cloudjourney.medium.com/teams-bot-single-sign-on-af21ae280e2c

**Comment by jwiley84** [comment]
Hi @Ronnie-personal 

There was a recent PR to fix a bug in this sample (https://github.com/microsoft/BotBuilder-Samples/pull/3035). Can you update your sample and try again, please?

**Comment by RonnieQuan** [comment]
@jwiley84  Sure, tested, it does not throw error, I'm able to logout, then type anything, then logout again, but token does not show.
![image](https://user-images.githubusercontent.com/25850020/105658614-d2d0c480-5e94-11eb-9681-1fe6efc752f9.png)

**Comment by RonnieQuan** [comment]
I would like to print out the token mentioned in this document https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#bot-sso-at-runtime

AAD sends the bot application token to the Teams application.

Teams sends the token to the bot as part of the value object returned by the invoke activity with the name sign-in/tokenExchange.

**Comment by RonnieQuan** [comment]
@jwiley84 Any update? Appreciate your help, thanks.

**Comment by jwiley84** [comment]
Hi @RonnieQuan I"ll get you an update shortly

**Comment by Ronnie-personal** [comment]
@jwiley84  Thank you! Any update?

**Comment by jwiley84** [comment]
@Ronnie-personal Apologies for the delay.  I am unable to repro this: 
![image](https://user-images.githubusercontent.com/17333688/108246299-220dbc00-7106-11eb-8ee8-2ef9b9054506.png)


I will read over the cloudjourney doc you linked and make sure there's not a step missing.

**Comment by jwiley84** [comment]
There doesn't seem to be anything missinng in your tutorial, so I'm going to reach out to the author of that sample, see  what's going on.

**Comment by EricDahlvang** [comment]
Hi @Ronnie-personal 

Are you still having issues with this sample?

**Comment by Ronnie-personal** [comment]
Yes, same issue,  when you say you not able to reproduce the error, did you use the code from here
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore

**Comment by EricDahlvang** [comment]
It looks like a bug was fixed in this code on on Jan 19.  Which is the same day this issue (3034) was opened.  Have you tried the code with that fix?

**Comment by EricDahlvang** [comment]
Are you able to debug locally, and step through the code?

**Comment by Ronnie-personal** [comment]
I don't know how to debug SSO, since it requires to login to the teams
The test I'm done is to deploy the code, and add the bot to teams, then logon to teams, then use the bot via teams, it does not show the show token dialog when I chat from teams

**Comment by EricDahlvang** [comment]
Hi @Ronnie-personal I'm trying the sample right now also, and running into some issues.  The Teams client does not appear to be returning the "signin/tokenExchange" invoke.

Setting 'EndOnInvalidMessage' will enable exiting the OAuthPrompt when login is not successful:

```cs
new OAuthPromptSettings
                {
                    ConnectionName = ConnectionName,
                    Text = "Please Sign In",
                    Title = "Sign In",
                    Timeout = 1000 * 60 * 1, // User has 5 minutes to login (1000 * 60 * 5)

                    EndOnInvalidMessage = true
                }));
```

I'll investigate more and get back to you.

**Comment by EricDahlvang** [comment]
Okay, thanks @tacri for assistance! m

The issue with my bot was related to missing 'token.botframework.com' in the validDomains:

```json
"validDomains": [
    "token.botframework.com",
    "ngrok.io"
  ]
```

After adding my botid to each of the required places in the manifest, and re-installing within Teams, sso works and I'm able to view the token:

![image](https://user-images.githubusercontent.com/11055362/110860219-5beb6180-8271-11eb-97a0-5e20672b2558.png)

When you installed your bot, did you use this manifest?
https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/TeamsAppManifest/manifest.json

**Comment by EricDahlvang** [comment]
Hi @Ronnie-personal 

Have you been able to work passed the issues with Teams SSO?

**Comment by Ronnie-personal** [comment]
@EricDahlvang  Thank you so much for checking in, I'm in my work environment now, I will have to test after hours or during weekend using my personal Azure subscriptions.  
Please give me a little bit time, I plan to test it out this weekend, I will keep you posted!
Please keep this ticket open, and will get back to you soon.

**Comment by Ronnie-personal** [comment]
@EricDahlvang  Yes, I use this Manifest https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/TeamsAppManifest/manifest.json, and I have the exact two domains.

Can you please confirm if you have  "/test" in the resource?

  "webApplicationInfo": {
    "id": "<<aad-app-clientid>>",
    "resource": "api://botid-<<YOUR-MICROSOFT-APP-ID>>/test"
  },

**Comment by Ronnie-personal** [comment]
This is what I got, it does not show the login card
![image](https://user-images.githubusercontent.com/76408835/111878228-b83f3700-897d-11eb-9ff8-7474a1d2da8f.png)

**Comment by Ronnie-personal** [comment]
@EricDahlvang   Could you please explain the note from https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#register-your-app-through-the-aad-portal?

    Your application's domain name must be same as the domain name that you have registered for your AAD application.
     Applications that use the azurewebsites.net domain are not supported because it is common and may be a security risk.

Two Questions:
1)
Does it mean when I deploy https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore to Azure web app, I have to create custom domain and can not leave it as azurewebsites.net?
2)
Domain name that you have registered for your AAD application, are we talking about "publisher domain"? or AAD tenant domain?

![image](https://user-images.githubusercontent.com/76408835/111883265-9307f400-8990-11eb-9f15-caf3fba27abb.png)

![image](https://user-images.githubusercontent.com/76408835/111883296-c8acdd00-8990-11eb-9a9b-bebaf7d54221.png)

**Comment by peterinnesmsft** [comment]
@EricDahlvang can you take a look at the customer questions above and provide a response? Thank you!

**Comment by EricDahlvang** [comment]
I believe the domain name is not required for sso, unless you are building "an app with a bot and a tab".  I was not aware of the restrictions on azurewebsites.net until now.  I think the publisher domain, and the aad tenant domain must be the same domain.

I think '/test' is not actually required.  The sample instructions should be updated to remove that.  Thank you for bringing this to our attention.

**Comment by Ronnie-personal** [comment]
Appreciate your help so far, what else can be done to show the token? we are using the same code, it shows token for you, but not for me.

Do you have custom domain for your bot web app?

My teams server is personal free version, is it supposed to work?

**Comment by Ronnie-personal** [comment]
Finally it works, I have documented findings in https://cloudjourney.medium.com/teams-bot-single-sign-on-af21ae280e2c

One more question regarding step 5 from https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/SSOSetup.md
Why we need to authorize clients to the application?
1fec8e78-bce4-4aaf-ab1b-5451cc387264 (Teams mobile/desktop application)
5e3ce6c0-2b1f-4285-8d4b-75ee78787346 (Teams web application)

Is this required by SSO?

Thank you!

**Comment by EricDahlvang** [comment]
Hi @Ronnie-personal 

Glad to hear it is working.  Nice writeup too :)

Yes, those client ids are required for SSO on those platforms.

Note: with the release of 4.13 sdk, this middleware can be used for Teams SSO deduplication: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsSSOTokenExchangeMiddleware.cs
