### ISSUE TITLE
Sample of human hand-off using Node.js 

### ISSUE THREAD

**Issue by geo-msft** [microsoft/BotBuilder-Samples#3041]
**Is your feature request related to a problem? Please describe.**
Some customers asked for samples on implementing human hand-off in Node.js. 
We have this C# example https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library but nothing for Node.js.

**Describe the solution you'd like**
An equivalent of the C# sample for human hand-off in Node.js, illustrating among the others how to call this method CreateHandoffInitiation and what parameters to place when making the call. 

**Additional context**
Many customers would benefit from having a sample showing how to implement the hand-off to agent.

**Comment by arturl** [comment]
We have no plans currently to port that sample to Node, but will accept community contribution if someone volunteers to do the work.
