### ISSUE TITLE
Interactive Message is not getting rendered in slack via botframework

### ISSUE THREAD

**Issue by Harshul9089** [microsoft/BotBuilder-Samples#3044]
## Describe the bug
I am using slack adapter from the sample code given [here](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/60.slack-adapter). After running the code the attachment is not getting rendered into my slack application chat.
![image](https://user-images.githubusercontent.com/60145577/105325661-dcd39880-5bf2-11eb-94b8-7eed3b0fc934.png)

## Expected behavior
Bot should render the Interactive Message

## Screenshots
Below is my the json and code I tried with.
[issue files.txt](https://github.com/microsoft/botframework-sdk/files/5847955/issue.files.txt)
![image](https://user-images.githubusercontent.com/60145577/105325989-3c31a880-5bf3-11eb-88a8-0f009039c727.png)
![image](https://user-images.githubusercontent.com/60145577/105326334-a1859980-5bf3-11eb-83ff-dd95b0a01055.png)

## Additional context
It did not show any Json deserializing error or any other exception.

**Comment by v-kydela** [comment]
Thank you for the report, @Harshul9089 

Can you go ahead and post your code as Markdown-formatted code blocks instead of screenshots?

**Comment by Harshul9089** [comment]
`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Adapters.Slack;
using Microsoft.Bot.Builder.Adapters.Slack.Model;
using Microsoft.Bot.Schema;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using SlackAPI;
using Attachment = Microsoft.Bot.Schema.Attachment;

namespace Microsoft.BotBuilderSamples.Bots
{
    /// <summary>
    /// An EchoBot class that extends from the ActivityHandler.
    /// </summary>
    public class EchoBot : ActivityHandler
    {
        /// <summary>
        /// OnMessageActivityAsync method that returns an async Task.
        /// </summary>
        /// <param name="turnContext">turnContext of ITurnContext{T}, where T is an IActivity.</param>
        /// <param name="cancellationToken">cancellationToken propagates notifications that operations should be canceled.</param>
        /// <returns>A <see cref="Task{TResult}"/> representing the result of the asynchronous operation.</returns>
        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.Text.ToString() == "test")
            {
                var interactiveMessage = MessageFactory.Attachment(
                    CreateInteractiveMessage(
                        Directory.GetCurrentDirectory() + @"\Resources\InteractiveMessage.json"));
                await turnContext.SendActivityAsync(interactiveMessage, cancellationToken);
            }

        }

        /// <summary>
        /// OnEventActivityAsync method that returns an async Task.
        /// </summary>
        /// <param name="turnContext">turnContext of ITurnContext{T}, where T is an IActivity.</param>
        /// <param name="cancellationToken">cancellationToken propagates notifications that operations should be canceled.</param>
        /// <returns>A <see cref="Task{TResult}"/> representing the result of the asynchronous operation.</returns>
     

        private static Attachment CreateInteractiveMessage(string filePath)
        {
            var interactiveMessageJson = System.IO.File.ReadAllText(filePath);
            var adaptiveCardAttachment = JsonConvert.DeserializeObject<Block[]>(interactiveMessageJson);

            var blockList = adaptiveCardAttachment.ToList();

            var attachment = new Attachment
            {
                Content = blockList,
                ContentType = "application/json",
                Name = "blocks",
            };

            return attachment;
        }
    }
}
`

Above is the code what I am trying.

**Comment by Harshul9089** [comment]
++@KoradaRajesh for issue follow up

**Comment by KoradaRajesh** [comment]
@v-kydela can you check with this solution [Slack-adapter sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/60.slack-adapter)

**Comment by v-kydela** [comment]
@Harshul9089 
@KoradaRajesh 

Sorry for the delay. I've tried the Slack adapter sample and it's able to display interactive messages without issue:

![image](https://user-images.githubusercontent.com/41968495/106212975-96e17c00-6180-11eb-959c-8a1a367768a5.png)

I can see that your C# and your JSON were taken directly from the sample. The only change you've made is to move the interactive message code from `OnEventActivityAsync` to `OnMessageActivityAsync`, presumably to get around having to register slash commands. This couldn't possibly make a difference, but still I tried it both ways and the interactive message displays successfully in both cases.

I can see that you've set a breakpoint in `OnMessageActivityAsync`. What happens when you step through that code? Does the if block get executed? Are there any exceptions?

**Comment by Harshul9089** [comment]
Hi @v-kydela , yes the if block is getting executed without any exception. But no interactive message got displayed in slack.

**Comment by v-kydela** [comment]
@Harshul9089 - It seems like the difference may be in the Slack app registration. Please create a new Slack app registration and carefully document each of the steps you take and see if you still get the same problem, then post the steps here for me to follow.

**Comment by v-kydela** [comment]
@Harshul9089 - Are you still working on this?

**Comment by Harshul9089** [comment]
@v-kydela Yes, let me get back to you after performing Slack registration steps from scratch.

**Comment by Harshul9089** [comment]
Hi @v-kydela , I appreciate your patience, Thank you for the help, now the interactive messages are getting displayed. What I understood is the last steps where we need to change Redirect Url and Request Url of **Oauth & Permissions** and **Event Subscriptions** respectively after creating ngrok tunnel were not performed which was causing the issue.

**Comment by v-kydela** [comment]
@Harshul9089 - That's very strange. You had said the if block was getting executed when you stepped through your code, which implies that the Slack messages were reaching your bot successfully. If your URL's weren't configured in the Slack app registration then your bot never should have gotten any messages. Did you actually try stepping through the code, or when you said the if block was getting executed did you just mean you weren't seeing any exceptions and so you assumed it was getting executed?

**Comment by Harshul9089** [comment]
@v-kydela- We kept Azure bot published URL instead of ngrok URL in above fields (Oauth & Permissions and Event Subscriptions) , and then in Azure bot, we kept ngrok URL in order to get all messages redirected to the solution.

**Comment by v-kydela** [comment]
@Harshul9089 - Well that doesn't answer my question, but it sounds like your issue has been resolved so I'll go ahead and close it
