### ISSUE TITLE
Consent option is not showing in mobile devices(Android and IOS)

### ISSUE THREAD

**Issue by NithinVangala** [microsoft/BotBuilder-Samples#3059]
GitHub Link : https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore

[Solution Used](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore) 
[Documentation Followed](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)

The steps given in the documentation works as expected in desktop application but fails in mobiles (Android and IOS). The below image (consent) is showing in desktop, but the same not showing in mobile, It doesn't throw any error and do not have any logs.

![image](https://user-images.githubusercontent.com/78229770/106314934-77397900-6290-11eb-9ed2-3ec6bb4c660a.png)

We have exactly followed the steps which mentioned in [README.md](https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/README.md) file and [SSOSetup.md](https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/SSOSetup.md) file

**Comment by Mikhail2k15** [comment]
1)	UX on mobile (IOS in my case) is very bad. User can see only “Accept” button. There are not message and cancel button.
 
![image](https://user-images.githubusercontent.com/11201670/106394248-aaa11280-640c-11eb-920d-ba7152e1c9e4.png)

2)	If a user hits Accept button on IOS nothing will happen. 
3)	If a bot requests permissions from a desktop and a user doesn’t answer accept/cancel user will be blocked on mobile and will not see any buttons.

**Comment by clearab** [comment]
Thank you for letting us know, we're engaging with the Team that owns the mobile client. I will update again when we have more information.

**Comment by Wajeed-msft** [comment]
@clearab , @NithinVangala - Copied this to Teams repo for tracking: https://github.com/MicrosoftDocs/msteams-docs/issues/2723

**Comment by clearab** [comment]
Thanks @Wajeed-msft! @NithinVangala I'm going to go ahead and close this issue, please follow the one above for further updates.
