### ISSUE TITLE
DotNet tests failing for Sample-Js-CoreBot-Linux-Test

### ISSUE THREAD

**Issue by harish0404** [microsoft/BotBuilder-Samples#3069]
Please see the below error details.  

##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\samples\csharp_dotnetcore\tests\Samples.CoreBot.FunctionalTests\Samples.CoreBot.FunctionalTests.csproj

## Screenshots.
![image](https://user-images.githubusercontent.com/46088560/107068915-d1619f00-67a6-11eb-9c6e-e6f3651a7544.png)

**Comment by BruceHaley** [comment]
Tests in this pipeline are now passing. See https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=1380&_a=summary
