### ISSUE TITLE
UnhandledPromiseRejectionWarning in 57.teams-conversation-bot (NodeJS)

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotBuilder-Samples#3081]
The methods onReactionsRemoved and onReactionsAdded do what they are supposed to do but also give an error in the console if you add or remove a reaction:

`(node:26860) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revokedat D:\home\site\wwwroot\node_modules\botbuilder-core\lib\turnContext.js:366:40at processTicksAndRejections (internal/process/task_queues.js:93:5)`

When I change 

```
                    const resourceResponse = context.sendActivity(newReaction);
```
into
```
                    await context.sendActivity(newReaction);
```

all is well.

**Comment by Virtual-Josh** [comment]
Hey @joshgummersall or @stevengum  can one of you take a look at this?

**Comment by Virtual-Josh** [comment]
There's a PR that will close this issue once merged.
