### ISSUE TITLE
Skill bot should create eoc as an activity, as IEndOfConversation doesn't have a Value property

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#3091]
## Sample information
1. Sample type: [samples]
2. Sample language: [dotnetcore]
3. Sample name: 80.skills-simple-bot-to-bot/EchoSkillBot (probably in sample 81, too)

## Describe the bug
With the current code, need to jump through hoops to set the `Value` property on the end of conversation activity. This is an issue because we tell developers to use the `Value` property as return value when the skill ends.

## To Reproduce
1. Edit the skill bot in the simple skill sample.
1. After creating the end of conversation activity (as written in the sample), try to assign to its value property.
1. See error (compiler warning, as there is no such property on the IEndOfConversation type).

## Expected behavior
Can assign a value to the activity.

## Additional context
https://github.com/microsoft/BotBuilder-Samples/blob/492bbc16c09998efcf935055b2378822373464f0/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/EchoSkillBot/Bots/EchoBot.cs#L17-L22

**Comment by JonathanFingold** [comment]
After talking to Srinaath and TJ, it looks like the **end dialog** action in the skill does generate an `endOfConversation` activity, and there is a way to set the generated activity value property. There doesn't seem to be a way to set the generated activity code property, however.

**Comment by Amrit10737726** [comment]
as mentioned IEndOfConversation doesn't have a Value property, we can Cast it to Activity to access the Value property and Assign the value to the Value property.
![SkillBot](https://github.com/microsoft/BotBuilder-Samples/assets/167064182/d3951db6-0fd8-4f22-a255-c53ff233a711)
![SillBotEmulator](https://github.com/microsoft/BotBuilder-Samples/assets/167064182/5f9b0671-5b42-40c5-b5c3-48f10b919ad3)
