### ISSUE TITLE
Cross-train config is outdate in samples which caused doesn't recognize the route error

### ISSUE THREAD

**Issue by Dragos04** [microsoft/BotBuilder-Samples#3097]
## Versions
@microsoft/botframework-cli/4.11.1

## Describe the bug
command : bf luis:cross-train --in . --out ../generated --config DialogLuHierarchy.config.json

my config json:
{
  ".\\RootDialog\\RootDialog.lu": {
    "rootDialog": true,
    "triggers": {
      "AddItem": ".\\AddToDoDialog\\AddToDoDialog.lu",
      "DeleteItem": ".\\DeleteToDoDialog\\DeleteToDoDialog.lu",
      "ViewItem": ".\\ViewToDoDialog\\ViewToDoDialog.lu",
      "GetUserProfile": ".\\GetUserProfileDialog\\GetUserProfileDialog.lu"
    }
  }
}

DialogLuHierarchy.config.json and RootDialog are in same folder

![Capture](https://user-images.githubusercontent.com/59847045/109126929-81974780-7756-11eb-957e-d84f48562a65.PNG)

error: Sorry, root lu file '.\RootDialog\RootDialog.lu' does not exist

**Comment by feich-ms** [comment]
Transferred from botframework-cli repo since we need to update the config in all samples to align with the latest botframework-cli.
