### ISSUE TITLE
Add samples and templates for Composer package creation and publishing

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotBuilder-Samples#3121]
**Is your feature request related to a problem? Please describe.**
Samples with clear guidelines demonstrating how to extend Bot Framework Composer with custom code in nuget and npm packages.

**Describe the solution you'd like**
**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by cleemullins** [comment]
@garypretty We need some PM assistance to define which samples we add.
