### ISSUE TITLE
02.echo-bot - cannot start

### ISSUE THREAD

**Issue by AlexanderTodorovic** [microsoft/BotBuilder-Samples#3129]
Dear All,
as described here [](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/02.echo-bot)
I've ran `git clone https://github.com/Microsoft/botbuilder-samples.git`

Unfortunately the 02.echo-bot runs into an error as two packages are missing
![image](https://user-images.githubusercontent.com/7408389/111592131-b5bcd000-880b-11eb-9700-3731f626acde.png)

[question]
I've tried e.g. to install via `Install-Package Microsoft.Bot.Builder -Version 4.12.2`
but did not succeed. How can the missing packages be resolved?

**Comment by jwiley84** [comment]
Apologies for the delay. Have you tried installing via the nuget package manager? As you can see on https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/02.echo-bot/EchoBot.csproj, 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.12.1" />
  </ItemGroup>
```

the packages are included.

**Comment by AlexanderTodorovic** [comment]
@jwiley84 Yes I did. As you can see in my first post I've used `Install-Package`. [Quickstart: Install and use a package in Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)

Anyway I run today again `git clone https://github.com/Microsoft/BotBuilder-Samples` . The version of last week has changed and it works fine now.

Thank you.
