### ISSUE TITLE
human handoff - steps to reproduce

### ISSUE THREAD

**Issue by thdotnet** [microsoft/BotBuilder-Samples#3135]
Hi,

i'm trying to implement/test human handoff. I've tried to follow the sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library but it's not clear to me how to join a person to the chat for the handoff part. Could you please provide steps on how to do it?

**Comment by daveta** [comment]
@thdotnet : FYI, experimental is preview and not production.

**Comment by thdotnet** [comment]
thanks @daveta , ready or not, I would like to run / test the sample

**Comment by arturl** [comment]
Hi @thdotnet, you need to first decide what agent hub you want to use. We have examples for Microsoft Omnichannel and LivePerson, and others have integrated with other providers (ServiceNow, RingCenhtral etc.). Can you share more detail about what you want to build?

**Comment by thdotnet** [comment]
hi @arturl , I'm interest in the hand off to human. The read.me doesn't teach how to "simulate" the human part. If I need to use ngrok or something else to send messages to the bot and it will route the conversation. Can you provide more details about how to run it?

**Comment by arturl** [comment]
@thdotnet, the decision to escalate to an agent is done by the bot based on the user input. For testing, you can add a condition (an `if` statement in the bot) that hands off the conversation if the user said "agent". From that point, the bot generates a handoff event and sends it back. Some channels "understand" it and implement the actual handoff. In other cases -- this is what you see in our samples -- the middleware intercepts and and performs the handoff by invoking the right agent hub APIs. The conversation then enters a new state ("escalated to agent") and all subsequent messages on this conversation are routed directly to the agent, so the bot doesn't get to respond to them. 
Does that help?

**Comment by thdotnet** [comment]
Partially, yes. But here's the question / confuse part. Let's say that I have a system (CRM). I will create a chat over there so agents can start to reply to end users rather than the bot. I assume, there will be some websocket endpoint to pass the messages from agent <-> end user and vice versa. Am I correct? Where is this websocket endpoint? Is there a specific payload I should use or just plain text?

That part is not clear.

**Comment by arturl** [comment]
That depends on the agent system. The ones that I'm familiar with all use HTTP. 
The logic from the middleware point of view is: for every new user message that comes in, does it belong to a conversation escalated to an agent? If yes, forward it to the agent. If not, pass it through to the bot an let it answer it. Messages from the agent also land in the bot (the bot has a special controller for that) and get pushed to the user as proactive messages. This way an agent can send multiple answers to the user. 
Another way to think about it: the user always talks to the bot; the bot either responds itself or gets the response from an agent.

**Comment by thdotnet** [comment]
Exactly, but where's the HTTP endpoint where the agent chat will POST data to the bot? That's not clear to me. There should be an ID or header I need to include into the request, otherwise, how it will know if it's a message to the bot or a message scalated to human?

**Comment by arturl** [comment]
@thdotnet, that HTTP endpoint can be added to the bot as another controller and an endpoint within an existing controller. In the LivePerson sample, the endpoint is part of the LivePersonConnector library, see here: https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonConnector/LivePersonController.cs#L24

> There should be an ID or header I need to include into the request, otherwise, how it will know if it's a message to the bot or a message scalated to human?

As you can see a few lines below, LivePerson adds HTTP headers `X-Liveperson-...` to their requests. This is used to recognize and authenticate the request.

**Comment by thdotnet** [comment]
thanks for the replies @arturl . I have a better understanding about how this works now. I understand it's "experimental", but I think it would be good some info on read.me explaining what we've discussed in here. There are a few options under experimental forlder but no information about how to run then (besides what it's on this thread).

If I could suggest something, it would be a simple chat web app where after sending a message to the bot asking for handoff, you could go the chat url and type something which will be routed and displayed in the Bot Emulator.

**Comment by arturl** [comment]
Thanks @thdotnet! I'll keep you feedback in mind for the next update of the handoff doc. Also, if you see any obvious gaps in the documentation feel free to submit a PR.
