### ISSUE TITLE
core-SendAttachment- swagger's client.clientAuthorizations  is undefined-

### ISSUE THREAD

**Issue by vivekjainAco** [Microsoft/BotBuilder-Samples#314]
### SDK Platform
Node SDK

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-SendAttachment 

### Problem Description
I am using the function 

> uploadAttachment

from the given sample node js code and updated my credentials. I used the following code snippet to send an attachment file via the Connector API. but it is giving an error: Error uploading file TypeError: Cannot read property 'add' of undefined. As per my understanding, it is giving the error on this code: 
```
 if (hasToken) {
                var authHeader = options.headers.Authorization;
                client.clientAuthorizations.add('AuthorizationBearer', new Swagger.ApiKeyAuthorization('Authorization', authHeader, 'header'));
            }
```
Can you please help me how can I fix this? I tried to search about it and found that swagger API is changed and they dont allow to add the authoriation header in thiw way. Please help to update this code.

**Comment by jwiley84** [comment]
That's saying 'clientAuthorization' has no 'add' method, because it doesn't 'clientAuthorization' doesn't exist. Where is 'clientAuthorization' being defined?

**Comment by jwiley84** [comment]
Hi @vivekjainAco! just checking to see if you're still having this issue.
