### ISSUE TITLE
C# Messaging Extension Action:  "Unable to reach app. Please try again."

### ISSUE THREAD

**Issue by TracyGH** [microsoft/BotBuilder-Samples#3140]
## Sample information
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action

## Describe the bug
After following [the instructions](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action) exactly, I receive the following message when trying any of the commands (create card/submit, fetch roster, etc.)
![image](https://user-images.githubusercontent.com/38665906/112367375-0f534d80-8c97-11eb-878c-f76e79382bed.png)

## To Reproduce
1. Follow [these instructions](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action)
2. Try to submit a Create Card or Fetch Roster and observe the error message

## Expected behavior
Successful card creation or roster fetch

## Screenshots
![image](https://user-images.githubusercontent.com/38665906/112367150-cd2a0c00-8c96-11eb-864d-4cb2e0e93ed2.png)
![image](https://user-images.githubusercontent.com/38665906/112367301-fb0f5080-8c96-11eb-864a-d5949c6aff4f.png)

**Comment by jwiley84** [comment]
Hi @TracyGH !!

This error typically happens with a appID/password mismatch. Can you confirm that they're correct, and can post what HTTP code ngrok is displaying?

**Comment by TracyGH** [comment]
Thanks so much for getting back to me, @jwiley84!  
I was able to get the FetchRoster and Share Message actions to function correctly.  However, the Create Card code is returning that 'Unable to reach app.  Please try again.' message. 

Below is what I'm seeing as far as local variable values from a breakpoint on line 55 of _Bots > TeamsMessagingExtensionsActionBot.cs._   Any thoughts?  

![image](https://user-images.githubusercontent.com/38665906/112526357-16de2980-8d5f-11eb-93eb-c703dd68f5d5.png)


![image](https://user-images.githubusercontent.com/38665906/112524787-763b3a00-8d5d-11eb-9df5-d8770769c83e.png)

**Comment by TracyGH** [comment]
Also, I think the Create Card actions are returning a 502 in ngrok, while the other actions are 200.

![image](https://user-images.githubusercontent.com/38665906/112527111-eba80a00-8d5f-11eb-84da-fd85c55eb438.png)

**Comment by TracyGH** [comment]
Hm, I tried it again this morning and now it's working fine.  I did have a firmware update last night and had to restart my machine, not sure if that made a difference.   
I'll close this out - thanks again for your help @jwiley84!
