### ISSUE TITLE
 Getting a schema validation error for liveperson thirdpartybots integration when transferring to agent

### ISSUE THREAD

**Issue by vikramhn** [microsoft/BotBuilder-Samples#3142]
## Sample information
1. Sample type: /BotBuilder-Samples/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot
2. Sample language: [dotnetcore ]
3. Sample name: LivePersonProxyBot

## Describe the bug
Trying the steps  https://developers.liveperson.com/third-party-bots-microsoft-direct-line-introduction.html
Start the conversation and when transferring to agent which succesfully happens but there is an error Unable to validate body because of invalid content and also  has schema validation error: value of element type should be equal to one of : "endOfConversation", "message" , have attached the image
https://developers.liveperson.com/third-party-bots-conversation-tester.html#microsoft-bot-framework-invalid-body 
## To Reproduce
1. Configure a directline bot - foloowed the steps here - https://developers.liveperson.com/third-party-bots-microsoft-direct-line-introduction.html
2. deploy the sample  /BotBuilder-Samples/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot to an appservice
2. test the bot from liveperson Conversational AI Third-Party Bots
3. in the chat type in agent

## Expected behavior
should not have recieved the error

## Screenshots
![image](https://user-images.githubusercontent.com/17201365/112547449-25453900-8d91-11eb-9846-2e71c4e66d3a.png)

**Comment by msomanathan** [comment]
@arturl, Could you please help with triaging this customer issue on Human Handoff scenario?

**Comment by arturl** [comment]
Hi @vikramhn,

First, apologies for the delayed response. What you're trying to accomplish here is integrate a Bot Framework bot into LivePerson using the "bot as an agent" approach, but the sample you're using follows the "bot as a proxy" approach. Mixing the two is causing the issue. Refer to [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0) document to understand the difference.

You should be able to use any Bot Framework bot with LivePerson using DirectLine protocol. However, be aware of the differences between Bot Framework and LivePerson message protocols. While the compatibility is improving over time, for now LivePerson only supports a subset of the Bot Framework protocol -- this includes text messages, handoff events and some others. In your specific case, the bot sends an event activity to LivePerson, and LivePerson is telling you that it only understands 'endOfConversation' and 'message'.

Feel free to reach out to LivePerson support as well for the latest guidance on integrating Bot Framework bots.

Let me know if this helps.

**Comment by arturl** [comment]
Closing for now. @vikramhn, feel free to reopen if you still have questions.
