### ISSUE TITLE
Use Skills between TwilioWhatsAppAdapter

### ISSUE THREAD

**Issue by manju605** [microsoft/BotBuilder-Samples#3151]
## Description
Twilio Adapter expects header params x-twilio-signature. How to send it from RootBotApp to SkillBotApp.

## To Reproduce
1. Run RootBotApp and SkillAppBot in TwilioWhatsAppAdapter
2. Post to skill from RootBot

**Comment by lauren-mills** [comment]
@garypretty - Can you comment here or transfer to the appropriate repo?

**Comment by gabog** [comment]
Hi @manju605, I am not familiar with the community adapters and samples you are referring to so you may want to post your question in the community repo.

That said, the communication between the root and the skill shouldn't requiere any channel specific headers, it is a plain HTTP call (with auth). The root bot that hosts the adapter is responsible of settings the headers for the channel before sending the activity it got from the skill back to the channel.

**Comment by tdurnford** [comment]
@manju605 The Twillio WhatsApp adapter is a community repo and not maintained by Microsoft. Can you please reopen your issue in the [BotBuilder-Community](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet) and someone from the community can help assist you with your issue there.
