### ISSUE TITLE
56.teams-file-upload : This item might not exist or is no longer available

### ISSUE THREAD

**Issue by chris-askbrian** [microsoft/BotBuilder-Samples#3190]
## Sample information
1. Sample type: samples
2. Sample language: nodejs 
3. Sample name: 56.teams-file-upload

## Describe the bug
Uploading and everything works and the file is available in the corresponding Application Folder in OneDrive, but you cant open the file in MSTeams which results in a "This item might not exist or is no longer available" message (acctually this depends on which file type is uploaded, for word files you get a "Sorry, this file has been deleted or moved." error)... (a workaround at the moment is: opening the file with the "Open in Browser" Option which is really anoying) 

## To Reproduce
1. Send something to the Bot
2. Accept the attachment
3. Wait till the download is done
4. Click on the downloaded file in Teams

## Expected behavior
Shows the content of the uploaded file instead of an error message

## Additional context
Actually I am not sure if this is a problem of ms teams itself or of this example... it worked some months ago... so maybe something changed on the ms teams part?

**Comment by Zerryth** [comment]
@chris-askbrian this is a Teams issue, and not something that we can fix on the Bot Framework Team, unfortunately.

It'd be best if you reached out to the Teams team, which you do via their desktop client app, at the bottom left

*bottom-left > Report a problem*
![image](https://user-images.githubusercontent.com/35248895/115753260-d8349280-a34f-11eb-9763-29ff7f60ffc0.png)

*report a Teams problem form*
![image](https://user-images.githubusercontent.com/35248895/115753320-ed112600-a34f-11eb-84c1-c42b6a147b5a.png)

**Comment by chris-askbrian** [comment]
Thanks... unfortunately there is no such option in my ms teams setup (Only a "Give Feedback" option, which does not look like that, eventhou I reported it there)

**Comment by laurentvizir** [comment]
@chris-askbrian I opened a new issue very similar to yours as I'm facing the exact same issue and the answer given here is not appropriate as you pointed out previously. You can find it here https://github.com/microsoft/BotBuilder-Samples/issues/3233. Hope we'll have a better answer to our request soon :)

**Comment by Zerryth** [comment]
Teams acknowledged the bug in a separate issue: https://github.com/microsoft/botbuilder-dotnet/issues/5542
The actual tracking ticket is internal only, however they created a public ticket in our SDK botbuilder-dotnet repo for visibility
