### ISSUE TITLE
Qna active learning not working if update to 4.13

### ISSUE THREAD

**Issue by davidefu** [microsoft/BotBuilder-Samples#3194]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: 49.qnamaker-all-features

## Describe the bug
If update to BotBuilder 4.13.0, active learning not work anymore

## To Reproduce
update bot builder packages to 4.13.0
trigger qna active learning
bot get exception

'turn' does not match memory scopes:[] (Parameter 'key')

**Comment by Zerryth** [comment]
I can confirm that I'm also getting the same buggy behavior as @davidefu when I try running sample 49.qnamaker-all-features after bumping package versions to v.4.13.0 😞 

![image](https://user-images.githubusercontent.com/35248895/116125340-37f5ab00-a67a-11eb-9239-8042e11e9b30.png)

In comparison, running with v.4.12.2 does not result in any errors when you trigger an active learning prompt

**Comment by davidefu** [comment]
hi @Zerryth , thanks for your reply
if I have debugged correctly the line that throws the exception is https://github.com/microsoft/botbuilder-dotnet/blob/cd897dfcc69e01ffec755027fae60c219b59074a/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L437

**Comment by tsuwandy** [comment]
@pchoudhari, who could work on fixing this issue in the the SDK repo?  https://github.com/microsoft/botbuilder-dotnet/blob/cd897dfcc69e01ffec755027fae60c219b59074a/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L437

**Comment by pchoudhari** [comment]
@sahithikkss , can you please take a look?

**Comment by sahithikkss** [comment]
@johnataylor , Apparently, this change #5441 https://github.com/microsoft/botbuilder-dotnet/pull/5441 has broken usage of "turn" scope used in QnA Maker dialog. Could you suggest the correct scope for QnA Maker Dialog to use?

**Comment by cleemullins** [comment]
After a quick sync with @mrivera-ms, she's going to follow up again with QnA Maker to get return this sample to a working state.

**Comment by Zerryth** [comment]
Wanted to chime in that people in the community are also encountering this error and posting it to StackOverflow:
https://stackoverflow.com/questions/67816160/how-to-close-the-qnamker-dialog-while-using-multiturn-qna-kb-and-luis-with-the-h

**Comment by LeeParrishMSFT** [comment]
This issue has been customer reported again in [QNA Maker Dialog with Adaptive Learning Issue](https://github.com/microsoft/botbuilder-dotnet/issues/5795) as well as the report above. Since it looks like the fix was only applied as a workaround to the Sample, and not yet to the SDK I think it would be better to re-open this issue until it can be corrected in the SDK.

**Comment by davidefu** [comment]
ok thanks to all.
so if I understand correctly. until the fix is made in the botbuilder-dotnet repo (https://github.com/microsoft/botbuilder-dotnet/pull/5758) and distribute through nuget with a future version we have to apply this workaround (https://github.com/microsoft/BotBuilder-Samples/pull/3347/commits/c8b0fca0b67b482a594e94752a1c395f8e55013d) in our bot in order to use version greater than 4.12.3

**Comment by LeeParrishMSFT** [comment]
@davidefu Yes, this is correct.

**Comment by brian-philip-dwyer** [comment]
When I put the workaround code into Startup.cs, it prevents my application from logging "BotMessageReceived" data into Application Insights. When I downgrade to 4.12.x or below, I also am not able to log "BotMessageReceived". The only way it logs is if I am running on 4.13.x or above, without the workaround. But the I get the error "'turn' does not match memory scopes:[] (Parameter 'key')". Any word on this issue?

**Comment by milind045** [comment]
I see the error "'turn' does not match memory scopes:[] (Parameter 'key')" when working with class "QnAMakerDialog" from package Microsoft.Bot.Builder.AI.QnA. I'm using latest version 4.22.2. Could somebody confirm if this package can work with newer Custom Question Answering (part of AI Language Service). I'm not using qnamaker.ai

**Comment by milind045** [comment]
> > I see the error "'turn' does not match memory scopes:[] (Parameter 'key')" when working with class "QnAMakerDialog" from package Microsoft.Bot.Builder.AI.QnA. I'm using latest version 4.22.2. Could somebody confirm if this package can work with newer Custom Question Answering (part of AI Language Service). I'm not using qnamaker.ai
> 
> I am experiencing the same issue while utilizing QnAMakerDialog and multi-turn questions.

Try adding following two lines to your Startup. Some classes are bootstrapped in a method marked Obsolete. Everything including multi-turn & active learning seems to be working for us after adding this line. Note, we use Custom Question Answering service. Ensure QnAServiceType is set to ServiceType.Languge when instantiating QnAMakerDialog class
+++
#pragma warning disable CS0618 // Type or member is obsolete
ComponentRegistration.Add(new DialogsComponentRegistration());
#pragma warning restore CS0618 // Type or member is obsolete
new DialogsBotComponent().ConfigureServices(services, config);
+++

**Comment by scimtaru** [comment]
> > > I see the error "'turn' does not match memory scopes:[] (Parameter 'key')" when working with class "QnAMakerDialog" from package Microsoft.Bot.Builder.AI.QnA. I'm using latest version 4.22.2. Could somebody confirm if this package can work with newer Custom Question Answering (part of AI Language Service). I'm not using qnamaker.ai
> > 
> > 
> > I am experiencing the same issue while utilizing QnAMakerDialog and multi-turn questions.
> 
> Try adding following two lines to your Startup. Some classes are bootstrapped in a method marked Obsolete. Everything including multi-turn & active learning seems to be working for us after adding this line. Note, we use Custom Question Answering service. Ensure QnAServiceType is set to ServiceType.Languge when instantiating QnAMakerDialog class +++ #pragma warning disable CS0618 // Type or member is obsolete ComponentRegistration.Add(new DialogsComponentRegistration()); #pragma warning restore CS0618 // Type or member is obsolete new DialogsBotComponent().ConfigureServices(services, config); +++

Thanks! I happened upon the exact same thing when comparing two projects where one was having issues and the other wasn't. Adding the above to Startup.cs fixed the multi-turn problems.
