### ISSUE TITLE
Cleanup Legacy Files across Sample(s) Repo

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotBuilder-Samples#3204]
The Samples repo has a number of out-of-date files that need to be cleaned up. 

The work item is to:
1.

- [x]  Cleanup the [Legacy CLI Tools references (such as this)](https://github.com/microsoft/BotBuilder-Samples/blob/main/INSTALLING_CLI_TOOLS.md). These files should be deleted, although replacing them with a link to the old CLI Tools repo, would be reasonable. 
- [x] 2. "Meta" files, [such as this](https://github.com/microsoft/BotBuilder-Samples/blob/main/SPEC.md) should be deleted (or cleaned up). 
- [x] 3. Examine why the ["media" folder](https://github.com/microsoft/BotBuilder-Samples/tree/main/docs/media) is there. 
- [x] 4. Examine if the ["build" folder](https://github.com/microsoft/BotBuilder-Samples/tree/main/build) can be deleted. 
- [x] 5. Understand why there are 2 "Migration v3 to v4" folders. Strongly consider deleting them in favor of a section in the main readme.md that just says "For migration, go to this older repo". Folder 1 [/Migration/MigrationV3V4](https://github.com/microsoft/BotBuilder-Samples/tree/main/Migration/MigrationV3V4). Folder 2 [/MigrationV3V4](https://github.com/microsoft/BotBuilder-Samples/tree/main/MigrationV3V4)
- [x] 6. The ("Experimental Samples List" in the readme.md)[https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/README.md] does not match reality. The links listed in that section all give 404s. The "Resources" section still points to myget. 
- [x] 7. The [readme.md in the Generators section](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators) does not include the Python or Java Generators.

**Comment by clearab** [comment]
Can we add "Remove abandoned experimental samples" to this list?
