### ISSUE TITLE
[javascript_nodejs/56.teams-file-upload] Uploaded file cannot be viewed nor downloaded

### ISSUE THREAD

**Issue by laurentvizir** [microsoft/BotBuilder-Samples#3233]
## Sample information
1. Sample type: \samples\
2. Sample language: nodejs
3. Sample name: BotBuilder-Samples/samples/javascript_nodejs/56.teams-file-upload/

## Describe the bug
After having accepted the download, when trying to view the file by clicking on it, an error page is displayed, saying "the item is not available" (see "To Reproduce" section below for screenshot). When trying to download the file by right clicking on the File Card, an error notification is displayed "The file did not upload".

## To Reproduce
1. Config your Team bot/application as mentioned in the readme
2. Launch the sample project 
3. Interact with the bot
4. Receive the Consent Card
5. Accept the Download
6. Click on the File Card once download is complete
7. See following error page (see screenshot below, in French sorry ; but changing my Team language to English did not change the language of the error page :disappointed: )
![image](https://user-images.githubusercontent.com/56591852/116987821-d2379d80-accf-11eb-9d12-459ea7080c57.png)
8. Try to download the file (from the conversation card) through the contextual menu by clicking on "Dowload file" and see the following error message:
![image](https://user-images.githubusercontent.com/56591852/116988004-1460df00-acd0-11eb-98c3-6f3914390dd0.png)

## Expected behavior
I expect the file to be viewable and downloadable

## Screenshots
Screenshots are present when needed to illustrate the previous "To reproduces" steps

## Additional context
I know this is the exact same issue reported previously here https://github.com/microsoft/BotBuilder-Samples/issues/3190 but the answer given before the issue was closed is not adapted as the solution proposed is not available. Indeed the "Report a problem" item is not present in the liste of choices proposed by the Help button (see screenshot below) 
![image](https://user-images.githubusercontent.com/56591852/116989521-280d4500-acd2-11eb-8e26-28b00d859b21.png)

**Comment by tsuwandy** [comment]
This should be addressed with fix for https://github.com/microsoft/botbuilder-dotnet/issues/5542

**Comment by laurentvizir** [comment]
While working on my Teams Bot nodejs application, I just realized that file preview access seems to be now fixed.
:tada: **Thanks for the fix!!! (and the speed you showed to implement it :muscle: )**
