### ISSUE TITLE
[500] Internal Server Error in MigrationV3V4 Sample code on session.endConversation()

### ISSUE THREAD

**Issue by Prabhu-Moorthy** [microsoft/BotBuilder-Samples#3240]
## Sample information
1. Sample type: Migration/MigrationV3V4/
2. Sample language: nodejs
3. Sample name: Skills/v3-skill-bot

## Describe the bug
When in [Skills/v3-skill-bot/app.js](https://github.com/microsoft/BotBuilder-Samples/blob/main/Migration/MigrationV3V4/Node/Skills/v3-skill-bot/app.js#L40) the `session.endConversation()` is called, the __endOfConversation__ activity is properly sent to the v4 consumer bot.
However in the v3 Skill bot I am getting an __Internal Server Error thrown.__

## To Reproduce
1. Start [Skills/v3-skill-bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/Migration/MigrationV3V4/Node/Skills/v3-skill-bot) after updating the .env file appropriately.
2. Start [Skills/v4-root-bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/Migration/MigrationV3V4/Node/Skills/v4-root-bot) after updating the .env file appropriately.
3. Connect to http://localhost:3978/api/messages from bot framework emulator
4. Follow the flow and type 'end' or 'stop'
5. [500] Internal Server Error is thrown in the [Skills/v3-skill-bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/Migration/MigrationV3V4/Node/Skills/v3-skill-bot) bot.

## Expected behavior
Should not throw [500] Internal Server Error

## Screenshots
Snippet of the  [500] Internal Server Error (in case you need to look at any additional information)
![MS Error](https://user-images.githubusercontent.com/13373307/117180001-04322800-add4-11eb-8816-74560527a732.jpg)

## Additional context
In [v4-root-bot/skillConversationIdFactory.js](https://github.com/microsoft/BotBuilder-Samples/edit/main/Migration/MigrationV3V4/Node/Skills/v4-root-bot/skillConversationIdFactory.js) if the `refs[skillConversationId]` is not cleared (the commented out line in the below snippet) I am not getting any error.
```javascript
async deleteConversationReference(skillConversationId) {
    //this.refs[skillConversationId] = undefined;
}
```

**Comment by tdurnford** [comment]
@stevkan Any update on this?

**Comment by ninggao** [comment]
@stevkan  Could you please take a look into this?

**Comment by EricDahlvang** [comment]
I believe this only occurs when connecting to the parent from the Emulator.  Have you seen this issue on any channels other than the Emulator?

**Comment by stevkan** [comment]
@Prabhu-Moorthy, also can you list which version of the SDK you are using? The sample's docs state it was created using v4.7.2. so I'm curious to know if it is happening with that version, the current version, or started with one somewhere in between.

@EricDahlvang, is there a fix or workaround that you are aware of for this occurring in Emulator? Or, is it only a known issue, at this time?

**Comment by EricDahlvang** [comment]
If i recall correctly, the issue is due to a trace activity sent from the v3 skill after endofconversation when the channel is 'emulator'. This arrives at the parent bot, and since endofconversation had already deleted the conversation.id from the skillConversationIdFactory ```this.refs[skillConversationId]``` results in an exception. The workaround shared by @Prabhu-Moorthy is one option. Another is to override the v3 bot, and modify it to not send a trace after endofconversation.

**Comment by Prabhu-Moorthy** [comment]
@EricDahlvang Thanks for the response. 
As you have mentioned, this error occurs only when connecting from Emulator.
I have tested in Directline and FB Messenger channels and I do not get this error.

Thanks for providing a workaround as well. 
Although the error occurs only in Emulator, it was good to know the reason.
