### ISSUE TITLE
BotComponent samples - C#

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#3251]
We need to create samples for developers to get started creating components for Composer bots. 

- Samples should be full bot projects, with the component in a separate .csproj from the bot. 
- README should include instructions for opening the bot from Composer.
- Base bot should be the empty bot template
- Samples should have dialogs/actions that exercise the components

We need:

- [ ] Custom action (based on existing multiply documentation)
- [ ] Custom trigger (memberAdded & memberRemoved)

**Comment by sgellock** [comment]
Shiproom - can I get confirmation that the components used in this sample are delivered as a package and not raw source changes

**Comment by clearab** [comment]
Nope, these were sample of creating a component, not a package, and were complete bot samples. I guess I'll close this one.
