### ISSUE TITLE
Bot Component Sample - JS

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#3252]
We need to create samples for developers to get started creating components for Composer bots.

- Samples should be full bot projects, with the component in a separate folder from the bot.
- README should include instructions for opening the bot from Composer.
- Base bot should be the empty bot template
- Samples should have dialogs/actions that exercise the components

We need:

- [ ] Custom action (based on existing multiply documentation)
- [ ] Custom trigger (memberAdded & memberRemoved)

**Comment by joshgummersall** [comment]
@clearab we don't yet have a great story for developing a component alongside a bot in JS short of some complex use of `yarn link`. Is this something that works well in .NET?

**Comment by clearab** [comment]
Yes - is this a solvable problem in JS?

**Comment by alexstojda** [comment]
Hi @clearab @joshgummersall, Do you have any expectation as to when this documentation & samples will be available? 

I have been trying to setup the MultiplyDialog using the node runtime, but am running into some issues as described here: https://stackoverflow.com/questions/67876232/custom-action-for-composer-2-0-bot-not-executing 

If I can get some assistance with that it would give a complete example and resolve on part of #3252

Thanks :)

**Comment by joshgummersall** [comment]
@alexstojda, my best guess is something was wrong with your NPM installation or linking. I use `yarn` with [workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) to test these scenarios locally. I [submitted a PR](https://github.com/alexstojda/adaptive-dialogs-custom-action/pull/1) to your repo that sets this up. Give that a shot and see if works!

**Comment by alexstojda** [comment]
@joshgummersall thanks for the help! It worked perfectly :)
