### ISSUE TITLE
Base Composer samples for docs - C#

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#3253]
We need to convert the old Composer samples to the new runtime, and put them here.

- Samples should be full bot projects
- README should include instructions for opening the bot from Composer.

Prioritized list of samples:

- [ ] Controlling Conversation Flow
- [ ] Responding with Text
- [ ] Responding with Cards
- [ ] Asking Questions
- [ ] Todo with LUIS

Topics that rely on the above samples:
- [Manage conversation flow](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow)
- [Send messages](https://docs.microsoft.com/en-us/composer/how-to-send-messages)
- [Send cards](https://docs.microsoft.com/en-us/composer/how-to-send-cards)
- [Ask for user input](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input)
- [Define intents with entities](https://docs.microsoft.com/en-us/composer/how-to-define-intent-entity)

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by mewa1024** [comment]
(@Quirinevwm fyi)

**Comment by clearab** [comment]
This list of samples is based current doc articles that are referencing older Composer samples that have been removed from the product. If we want to not convert these to the new runtime and put them somewhere we'll need to rewrite all of those docs.

This is NOT a list of new samples that have been prioritized, or even looked at in terms of accuracy or best practices. This is purely to support those existing documentation articles listed above.

**Comment by tracyboehrer** [comment]
Closing this since the ComposerSamples branch has these.  Of note:  These are straight conversions of all of the samples from the Composer branch (minus ActionsSample).  As such, README's may not be adequate for a sample.
