### ISSUE TITLE
Bot Composer samples for docs - JS

### ISSUE THREAD

**Issue by clearab** [microsoft/BotBuilder-Samples#3254]
We need to convert the old Composer samples to the new runtime, and put them here.

- Samples should be full bot projects
- README should include instructions for opening the bot from Composer.

Prioritized list of samples:

- [x] Controlling Conversation Flow
- [x] Responding with Text
- [x] Responding with Cards
- [x] Asking Questions
- [x] Todo with LUIS

Topics that rely on the above samples:
- [Manage conversation flow](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow)
- [Send messages](https://docs.microsoft.com/en-us/composer/how-to-send-messages)
- [Send cards](https://docs.microsoft.com/en-us/composer/how-to-send-cards)
- [Ask for user input](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input)
- [Define intents with entities](https://docs.microsoft.com/en-us/composer/how-to-define-intent-entity)

**Comment by joshgummersall** [comment]
Where are the Composer samples?

**Comment by clearab** [comment]
Here - https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/samples/assets/projects

**Comment by tracyboehrer** [comment]
@clearab I believe these are in the composer-samples tree for JS.  Can you verify and close this if so?
