### ISSUE TITLE
Why are emptybot created by composer and dotnet cli different to each other ?

### ISSUE THREAD

**Issue by parsalotfy** [microsoft/BotBuilder-Samples#3270]
## Describe alternatives you've considered

Hi,
when we create a .netcore app with visual studio, the generated files are exactly similar to files generated by dotnet cli command. Except for .sln file.
Why the same behavior does not happen when we create an empty bot with bot composer ?
When I create an empty bot with bot composer and these cli commands : 
```
dotnet new -i Microsoft.Bot.Framework.CSharp.EmptyBot
dotnet new emptybot
```
The .csproj files are different with each other

I think it would be a good idea to make them look similar to each other.
for example :

**.csproj file of the bot created by BotComposer** 
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <UserSecretsId>{redacted}</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="**/*.blu;**/*.dialog;**/*.lg;**/*.lu;**/*.onnx;**/*.qna;**/*.txt" Exclude="$(BaseOutputPath)/**;$(BaseIntermediateOutputPath)/**;wwwroot/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.8" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.13.1" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.QnA" Version="4.13.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime" Version="4.13.1" />
  </ItemGroup>
</Project>
```

**.csproj file of the bot created by dotnet cli commands**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.13.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


</Project>

```

Regards,
Parsa Lotfi

**Comment by clearab** [comment]
@tracyboehrer do you know why there are differences between the VS template and the dotnet template?

**Comment by clearab** [comment]
Wait, sorry - I might be wrong. Do you want to use Composer to create and edit your bot?

**Comment by tracyboehrer** [comment]
The only insight I can give is similar to Andrews.  These are coming from different areas of our stack, and we haven't aligned them.  The Composer csproj is specific to a Composer Bot project, which would/could have it's own requirements that differ from the pre-existing CLI template.  If I had a crystal ball, I would expect some alignment, but a Composer Bot could remain different.  Maybe more along the lines of everything moving into CLI, and that can produce a Composer compatible bot.

**Comment by parsalotfy** [comment]
> Wait, sorry - I might be wrong. Do you want to use Composer to create and edit your bot?

I want the ability of editing bots created by CLI in Composer
Bots created by composer include so many packages like QnA or LUIS which I never use.
So I create an empty bot using CLI , but I can't edit that bot through Composer.
You know I want the goods of both sides  :grin:
The simplicity of creating bot without having to code as well as having an lightweight clean bot like the one created by cli

**Comment by parsalotfy** [comment]
Is there a way to open a bot created by cli with bot composer ?

**Comment by clearab** [comment]
If you like you could drop references to those packages using either a package manager like VS, or by removing them from the CS proj and rebuilding. The current empty bot template in the daily build of Composer (which I think is what you are using) only takes 4 package dependencies though. Composer also would not detect that you need those packages and add them back for you if you decided to use a feature that required them (it will expect them to be present).

The template that the dotnet CLI scaffolds does not use the adaptive dialog stack, and would not be missing a number of elements that Composer expects to be present. The empty bot that Composer generates for you represents the minimum set of dependencies, and the project/folder/file scaffolding that Composer expects to be present. You can of course feel free to alter this, but some portions of Composer may not work as expected if you do so.

If you would like to use a CLI tool to create your Composer compatible bot, you can do so using the Yeoman template - it is available here https://www.npmjs.com/package/@microsoft/generator-bot-empty, and you can find instructions for working with Yeoman here: https://yeoman.io/learning/

**Comment by parsalotfy** [comment]
Hello again @clearab @tracyboehrer 
That yeoman couldn't help me,
I want to make an empty bot with dotnet cli
And then edit that bot with Composer.
Pleeeaaaase make that possible 🙂😁
It could be a very good feature.
Thank you ❤️
