### ISSUE TITLE
Unable to capture channel specific response times

### ISSUE THREAD

**Issue by ganeshchippada** [Microsoft/BotBuilder-Samples#328]
I have a bot instance running in Azure with MS TEAMS channel enabled. I see there is some slowness in TEAMS response when chatting with the bot. I have already enabled the Application insights to capture the response times. But unfortunately the response times which is shown in App insights is just the App service response times. Those looked great. But from the end user perspective the response time is really high. 

For ex: Response times in App insights is around 10 ms. But the user is getting the response in TEAMS in almost 10 secs. So i was wondering if there is a way to capture the response times from different channels which end user is using.

**Comment by stevkan** [comment]
Can you tell me which SDK you are using?

**Comment by CoHealer** [comment]
Closed due to inactivity
