### ISSUE TITLE
Adaptive Dialog Documentation Missing

### ISSUE THREAD

**Issue by shivajipotnuru** [microsoft/BotBuilder-Samples#3293]
I've been referring to adaptive dialog documentation for past few days, now the documentation is being not found. Kindly provide the documentation.

The link I'm referring to [Adaptive Dialog](https://docs.microsoft.com/en-us/azure/bot-service/composer/concept-dialog?view=azure-bot-service-4.0)

**Comment by jwiley84** [comment]
Hi @shivajipotnuru 

The reference documents for adaptive dialogs have been moved to https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-triggers?view=azure-bot-service-4.0
