### ISSUE TITLE
[Node] bot always replies with default message

### ISSUE THREAD

**Issue by snbuchholz** [Microsoft/BotBuilder-Samples#33]
[15:45:19] Emulator listening on http://[::]:9002 
[15:45:37] -> POST 202 [conversationUpdate] 
[15:45:50] -> POST 202 [message] hi 
[15:45:52] <- POST 200 Reply[message] Sorry, I did not understand 'hi'. Type 'help' if y... 
[15:45:59] -> POST 202 [message] help 
[15:46:00] <- POST 200 Reply[message] Sorry, I did not understand 'help'. Type 'help' if... 
[15:47:09] -> POST 202 [message] Help 
[15:47:10] <- POST 200 Reply[message] Sorry, I did not understand 'Help'. Type 'help' if...
[15:50:41] -> POST 202 [message] search hotels in Seattle 
[15:50:42] <- POST 200 Reply[message] Sorry, I did not understand 'search hotels in Seat... 

I have imported LuisBot.json into LUIS, updated .env with its URL and App ID and password and I'm trying it via the Emulator under Linux. Before importing to LUIS, I tried to "test this sample as-is, using the hosted sample application", as mentioned in the README but got 

[15:29:41] -> POST 401 [conversationUpdate] 
[15:29:41] Error: The bot's MSA appId or passsword is incorrect. 
[15:29:41] Click here to edit your bot's MSA info.

and wasn't sure what to fill in.
I notice the original URL in the sample code is https://api.projectoxford.ai/luis/v1/application?...
whereas mine is https://api.projectoxford.ai/luis/v2.0/apps/...
Could that be an issue?

**Comment by snbuchholz** [comment]
I see in the LUIS logs that the utterances were classified totally correctly (sorry, upload of CSV files is not supported here, so I'm just copy/pasting as text):

Query	UTC DateTime	     Response
hi	11/30/2016 15:45:51	"{
  ""query"": ""hi"",
  ""topScoringIntent"": {
    ""intent"": ""Help"",
    ""score"": 0.5491038
  },
  ""entities"": [
    {
      ""entity"": ""hi"",
      ""type"": ""builtin.geography.us_state"",
      ""startIndex"": 0,
      ""endIndex"": 1
    }
  ]
}"
help	11/30/2016 15:46:00	"{
  ""query"": ""help"",
  ""topScoringIntent"": {
    ""intent"": ""Help"",
    ""score"": 0.9932092
  },
  ""entities"": []
}"
help	11/30/2016 15:47:09	"{
  ""query"": ""Help"",
  ""topScoringIntent"": {
    ""intent"": ""Help"",
    ""score"": 0.9932092
  },
  ""entities"": []
}"

**Comment by snbuchholz** [comment]
For the record: this refers to this sample: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/intelligence-LUIS

**Comment by kgrashad** [comment]
@willportnoy

**Comment by willportnoy** [comment]
@stevenic is the LUIS url change significant here for this Node sample?

**Comment by snbuchholz** [comment]
Sorry, any news on this?

**Comment by willportnoy** [comment]
@pcostantini were there any issues fixed with this sample in https://github.com/Microsoft/BotBuilder-Samples/pull/51 ?

**Comment by pcostantini** [comment]
@willportnoy @snbuchholz , The only breaking change was that the LUIS needed to be updated (already in  PR #51)

**Comment by srichakradhar** [comment]
This is same as [Issue 117](https://github.com/Microsoft/BotBuilder-Samples/issues/117)
Is there any fix for this?

**Comment by sgellock** [comment]
closed due to inactivity
