### ISSUE TITLE
TaskModuleUIConstants.js does not exist

### ISSUE THREAD

**Issue by jersonjunior** [microsoft/BotBuilder-Samples#3320]
## Sample information
1. Sample type: /opt/BotBuilder-Samples/samples/javascript_nodejs/54.teams-task-module
2. Sample language: nodejs
3. Sample name: 54.teams-task-module

## Describe the bug
Error: Cannot find module '../models/TaskModuleUIConstants'

## To Reproduce
npm start

## Expected behavior
Start project

##
OS Ubuntu 18.04

##
SDK 4

##
Branch default

## Solution
cd models
cp taskmoduleuiconstants.js TaskModuleUIConstants.js

**Comment by stevkan** [comment]
@jersonjunior, can you please include the SDK version and OS you are running this on?

**Comment by jersonjunior** [comment]
![image](https://user-images.githubusercontent.com/7052700/121961277-9ddae680-cd3d-11eb-88af-2e11a1ae1adc.png)
**It is imported with upper and lower case**
![image](https://user-images.githubusercontent.com/7052700/121961407-c662e080-cd3d-11eb-896e-b8e9e4b37030.png)
**But the file is all tiny**

**Comment by stevkan** [comment]
@jersonjunior, Yes, I just saw the same. The referenced file name `TaskModuleUIConstants` in the code should be lower case to match the other referenced files being imported. I suspect that when the teamsTaskModuleBot.js file was written the name of the class was errantly copied over the referenced name of the file.

In the meantime, you can do what you have done, essentially renaming the file to match the case in the code. Or, you can adjust the code so the referenced name matches the actual name of the file, taskmoduleuiconstants.js.

Thank you for pointing out the bug. This will be corrected in a future release.

**Comment by jersonjunior** [comment]
> @jersonjunior, Yes, I just saw the same. The referenced file name `TaskModuleUIConstants` in the code should be lower case to match the other referenced files being imported. I suspect that when the teamsTaskModuleBot.js file was written the name of the class was errantly copied over the referenced name of the file.
> 
> In the meantime, you can do what you have done, essentially renaming the file to match the case in the code. Or, you can adjust the code so the referenced name matches the actual name of the file, taskmoduleuiconstants.js.
> 
> Thank you for pointing out the bug. This will be corrected in a future release.

I just copied the content to it using the command:
cp taskmoduleuiconstants.js TaskModuleUIConstants.js
