### ISSUE TITLE
Certs for App Id 75e50874-a4f9-4535-a709-18d292a700f8 was expired. 

### ISSUE THREAD

**Issue by anumoluharish** [microsoft/BotBuilder-Samples#3324]
https://fuselabs.visualstudio.com/SDK_v4/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1022&view=Tab_Variables

Certs for App Id 75e50874-a4f9-4535-a709-18d292a700f8 was expired and this causes failures of tests for Sample-Js-EchoBot-Linux-Test pipeline. Please generate new certs and update in the key vault.

**Comment by mrivera-ms** [comment]
The test is fixed.
