### ISSUE TITLE
cleanup samples folders

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#3325]
The code-first Adaptive Dialog samples folder https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/adaptive-dialog causes confusion and should be dropped. We are not suggesting hand crafting Adaptive Dialogs in code is a reasonable development approach.

The experimental folder also causes confusion and should be dropped. The content here is not official product sample and has on occasion lacked consistency and quality. Code that is intended to provoke discussion and exploration should be moved to individuals' repos. Some material maybe also be appropriate for the https://github.com/BotBuilderCommunity repo, @garypretty can perhaps comment on that.

**Comment by Yonet** [comment]
Also, can we add the info for what the sample does. For ex: following the readme for https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_es6/01.browser-echo, I have the bot running but not sure if it's working or not(See image below). An explanation of what to expect and the next steps would be helpful.
Thanks!
<img width="1434" alt="Screen Shot 2021-06-22 at 4 49 48 PM" src="https://user-images.githubusercontent.com/3523671/123013944-0a776600-d37a-11eb-9866-dcbc5e9c4808.png">
