### ISSUE TITLE
Teams sample 58

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotBuilder-Samples#3326]
Teams sample should use TeamsInfo.SendMessageToTeamsChannelAsync()

**Comment by stevengum** [comment]
https://github.com/microsoft/botbuilder-dotnet/blob/471504a95510fa053ddf3a9fd1cd48ded1f9ba45/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L192-L201
