### ISSUE TITLE
Push form prompts to a single file

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotBuilder-Samples#3336]
We need to reorganize the form wide templates so that we have one file with all of the top-level prompts in it.  To do this:
1) Consolidate all of the *-form-* into a single file and call it <prefix>-form-extensions.lg
2) Seperate out any top-level prompt with a top-level activity and its text are in a single file <prefix>-form.lg.
3) Look at all of the top-level prompts to make sure they are as simple and obvious as possible.

**Comment by coldplaying42** [comment]
Consolidate all of the -form- into a single file and call it -form-extensions.lg, do you mean that all the files with "form-" in their names should be combined into one single file? For example, form-BeginDialog.dialog.lg and form-CancelConfirmation-prompt.dialog.lg should be put into one file?

**Comment by chrimc62** [comment]
We want a single file with all of the top-level prompts in it (the ones with activity) and another single file with all of the utilities/extensions in it.
