### ISSUE TITLE
Deployment ARM templates update

### ISSUE THREAD

**Issue by MedvidekPu** [microsoft/BotBuilder-Samples#3340]
### Deployment ARM templates update

**ARM templates create resource Bot Channels registration which will has been deprecated since 9/1/2021.**
Can we please get new deployment templates which create the new Azure resource 'Azure Bot' and connect it to our app service?
A lot of manuals on microsoft websites are already suggesting the use of Azure Bot but these repositories create the former resource Bot Channels registration.

Help would be appreciated.

Thanks!

## Samples Update Tracking

- [x] [samples/typescript_nodejs](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs) 
  - PR #3412
- [x] [samples/csharp_dotnetcore](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore)
  - PR #3415
  - PR #3416
- [x] [samples/java_springboot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot)
  - PR #3421
  - PR #3422
- [x] [samples/javascript_nodejs](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs)
  - PR #3419
  - PR #3420
- [x] [samples/python](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python)
  - PR #3417
  - PR #3418
- [x] [generators](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators)
   - PR #3428 
   - PR #3429  
- [ ] [composer-samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples)
  - PR #3425
  - PR #3426
  - PR #3427
- [x] [Migration](https://github.com/microsoft/BotBuilder-Samples/tree/main/Migration)
  - PR #3423
- [ ] [experimental](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental)
  - PR #3430

**Comment by JonathanFingold** [comment]
This is causing confusion. See bot-docs [issue 2109](https://github.com/MicrosoftDocs/bot-docs/issues/2109).
- [ ] Identify the parameter change required.
- [ ] Update the ARM templates in all the samples in all the languages.
- [ ] Update the ARM templates in the templates and generators in all the languages.

**Comment by joslat** [comment]
A lot of confusion and the current templates point to the azure web app bot deployment, that is outdated and going to be 100% deprecated in 1 month and a few days..
