### ISSUE TITLE
Samples missing deployment templates

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotBuilder-Samples#3349]
## Sample information
1. Sample type: samples
2. Sample language: all
3. Sample name: several

## PR list
csharp_dotnetcore
- #3466
- #3467

javascript_nodejs
- #3468
- #3469

csharp_webapi, java_springboot, python
- #3470

## Describe the bug
Several samples are missing the **deployment templates**.

csharp_dotnetcore

- [ ] 13.core-bot
- [ ] 13.core-bot.tests
- [ ] 14.nlp-with-orchestrator
- [ ] 40.timex-resolution
- [ ] 42.scaleout
- [ ] 43.complex-dialog
- [ ] 44.prompt-users-for-input
- [ ] 45.state-management
- [ ] 50.teams-messaging-extensions-search
- [ ] 51.teams-messaging-extensions-action
- [ ] 52.teams-messaging-extensions-search-auth-config
- [ ] 53.teams-messaging-extensions-action-preview
- [ ] 54.teams-task-module
- [ ] 56.teams-file-upload
- [ ] 80.skills-simple-bot-to-bot
- [ ] 81.skills-skilldialog
- [ ] adaptive-dialog

csharp_webapi
- [ ] 13.core-bot

java_springboot
- [ ] 40.timex-resolution
- [ ] 42.scaleout

javascript_es6
- [ ] 01.browser-echo
- [ ] 70.styling-webchat

javascript_nodejs
- [ ] 01.console-echo
- [ ] 14.nlp-with-orchestrator
- [ ] 23.facebook-events
- [ ] 40.timex-resolution
- [ ] 43.complex-dialog
- [ ] 44.prompt-for-user-input
- [ ] 45.state-management
- [ ] 49.qnamaker-all-features
- [ ] language-generation
- [ ] 05.a.multi-turn-prompt-with-language-fallback
- [ ] 05.multi-turn-prompt

python
- [ ] 01.console-echo
- [ ] 40.timex-resolution

typescript_nodejs
- [ ] 01.console-echo

## Expected behavior
Add missing the **deployment templates** folder.

**Comment by mrivera-ms** [comment]
Closing as completed.
