### ISSUE TITLE
Java 18.bot-authentication sample does not prompt to show user token

### ISSUE THREAD

**Issue by LeeParrishMSFT** [microsoft/BotBuilder-Samples#3368]
## Describe the bug
The Java version of the 18.bot-authentication sample doesn't properly show the prompt after login to show the user their token in the bot framework emulator. It shows the prompt text but not the yes/no buttons as it should.

## To Reproduce
1. Run the sample and connect with the bot framework emulator
2. Login
3. After a successful login see that the prompt "Would you like to view your token?" shows the text, but doesn't show the yes/no buttons that it should display.

## Expected behavior
Yes/No buttons should be provided for the user or the prompt.

**Comment by tracyboehrer** [comment]
Closed by https://github.com/microsoft/BotBuilder-Samples/pull/3369
