### ISSUE TITLE
Audio Card not displaying Images

### ISSUE THREAD

**Issue by lijithomas2020** [microsoft/BotBuilder-Samples#3391]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/06.using-cards

## Describe the bug
The Audio Card option in Webchat does not display the image, though the Image's Url is configured in code.

## To Reproduce
Run the Cards sample project as indicated 

## Expected behavior
Expected image to be displayed in the Audio Card in Webchat

## Screenshots
![image](https://user-images.githubusercontent.com/75117644/126890345-d8a36c95-d8f0-40b9-a641-26f73590a821.png)

**Comment by taicchoumsft** [comment]
@jwiley84 , could you take a look at this sample? Thanks.

**Comment by jwiley84** [comment]
I've never noticed an image on the audio card, but I don't think I ever expected to. Lemme look at the code, see what's going on.

**Comment by dmvtech** [comment]
This is a known issue and a [bug is filed in the webchat repo](https://github.com/microsoft/BotFramework-WebChat/issues/3315).

Closing as it is not an issue with the sample itself, but with webchat.
