### ISSUE TITLE
Build error in nodejs multiply-dialog-package

### ISSUE THREAD

**Issue by austintreneff** [microsoft/BotBuilder-Samples#3398]
## Sample information
1. Sample type: Botbuilder-Samples
2. Sample language: nodejs
3. Sample name: multiply-dialog-package

## Describe the bug
When trying to build the nodejs version of the [multiply-dialog-package](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package), I get a type error in index.js:

`Property 'configureServices' in type 'MultiplyDialogBotComponent' is not assignable to the same property in base type 'BotComponent'.
  Type '(services: ServiceCollection, _configuration: Configuration) => void' is not assignable to type '(services: ServiceCollection, configuration: Configuration) => void'.
    Types of parameters 'services' and 'services' are incompatible.
      Type 'import("/Users/trenea2/dev/sandbox/botbuilder-samples/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package/node_modules/botbuilder-core/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection").ServiceCollection' is not assignable to type 'import("/Users/trenea2/dev/sandbox/botbuilder-samples/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection").ServiceCollection'.
        Types have separate declarations of a private property 'dependencies'.ts(2416)`
        
It looks like the parent class "BotComponent" is using the ServiceCollection from botbuilder-core while MultiplyDialogBotComponent is not. Causing a type incompatibility.

## To Reproduce
1. Clone [Botbuilder-Sample](https://github.com/microsoft/BotBuilder-Samples)
2. Go to './botbuilder-samples/composer-samples/javascript_nodejs/projects/custom-action/multiply-dialog-package'
2. Install dependencies
3. Try building the package

## Expected behavior
It is expected that the package would build successfully

## Additional context
MacOS - Node v14.8.0

**Comment by stevkan** [comment]
@austintreneff, thank you for the bug report. I was able to repro the issue you encountered. I am working on getting this routed to the right person for handling.
