### ISSUE TITLE
npm install gets 'found 15 moderate severity vulnerabilities'

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotBuilder-Samples#3403]
Repro: In the folder samples\javascript_nodejs\13.core-bot, give the command 'npm install'.

The message is printed:
>found 15 moderate severity vulnerabilities
>  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by joshgummersall** [comment]
The underlying vulnerability exists in `xmldom`, is patched, but is [unable to be published at the moment](https://github.com/xmldom/xmldom/issues/271). Eventually, the change will propagate automatically as the transitive `xmldom` semver references all include operators that will match `0.7.0`.
