### ISSUE TITLE
SSO in C# not Node

### ISSUE THREAD

**Issue by smtghost** [microsoft/BotBuilder-Samples#3432]
Is there a .Net core app sample for SSO that piggybacks the auth token without the user having to interact with the bot. I have not been able to pull the channel data out (no matter how I format it) coming from webchat directline. I have tried several different ways. If I try the new syntax 
action = simpleUpdateIn(
                        action,
                        ['payload', 'activity', 'channelData', 'usertoken'], function () { return '@Model.UserToken' }
                    );
I don't see it in the log and never retrieve it from the bot.

**Comment by gabog** [comment]
Hi @smtghost, see if this prototype built by @EricDahlvang helps: https://github.com/EricDahlvang/WebChatSSO
