### ISSUE TITLE
Bot with Orchestrator cant find model and path

### ISSUE THREAD

**Issue by danieldangler** [microsoft/BotBuilder-Samples#3435]
## Sample information
1. Sample type: sample
2. Sample language: dotnetcore
3. Sample name: 14.nlp-with-orchestrator

## Describe the bug
When i publish the finished Bot with orchestrator sample and test it in web, the bot throws the following exeption with the message in the App Insights:

"Failed to find or load Model with path C:\home\site\wwwroot\model Invalid or missing model file ("ModelFile" value in config): C:\home\site\wwwroot\model\model.onnx".

When i test the bot locally, everything works just fine. I have uploaded some screenshots for further informations. Maybe it is just a super simple error and i just cant get it, im pretty new to the orchestrator tool.

## To Reproduce
1. Follow the steps from the 14.nlp-with-orchestrator sample
2. In my specific case, i dont have any LUIS models, but five QnA Maker Knowledge Bases (There could be some leftovers from LUIS in the screenshots, but they arent causing the problem because on local tests everything works)
3. Publish the configured sample to a web app bot
4. Test the bot in web and try to trigger a QnA Pair

## Expected behavior
The bot should give an answer from one of the connected knowledge bases

## Screenshots
![fail](https://user-images.githubusercontent.com/39704877/131040848-b112c949-a37d-4812-ae0b-2435c52450e0.png)

![startup](https://user-images.githubusercontent.com/39704877/131040873-7db0c882-ca48-406d-bbde-793bba37ab65.png)

![appsettings](https://user-images.githubusercontent.com/39704877/131040894-1ce494ee-3660-4e6b-bfca-c5c532709273.png)

![orchestratorsettings](https://user-images.githubusercontent.com/39704877/131040905-b206d206-ba55-4f82-ae8c-cef2c832a15f.png)

![Screenshot 2021-08-27 000015](https://user-images.githubusercontent.com/39704877/131041798-aab7630e-eced-444b-9320-ed14f560c752.png)

**Comment by stevkan** [comment]
@danieldangler, thank you for your patience. When you say you don't have any LUIS models, are you still supplying the LUIS API and key? When running the botframework-cli commands listed in the samples README.md file, are you skipping the `bf luis:build` step and only running the others?

It looks like the `modelPath` and `snapshotPath` property values are not getting properly updated. I will attempt a repro, but if you could answer the above, that would help in my setting up my environment to match yours.

**Comment by danieldangler** [comment]
Hey @stevkan, yes, i skipped the complete LUIS part and only did the QnA commands. For these, i used bf `orchestrator:create` instead of bf `orchestrator:build` because i already had the knowledge bases set up.

**Comment by danieldangler** [comment]
@stevkan i found the problem. The files "model.onnx", "vocab.txt" and "orchestrator.blu" are marked as "Do not copy" in the properties in Visual Studio so if i want to manually publish the files via VS, these three wont get uploaded to the app service as well.

![1](https://user-images.githubusercontent.com/39704877/132332299-bc518739-b19a-4697-8f24-2d1e78cca692.png)

You need to set them to "copy if newer" or "always copy" to publish the files to the service in Azure.

![2](https://user-images.githubusercontent.com/39704877/132332321-54a97c3f-4b26-4fb1-8a9d-c2fcc1bb45d8.png)
