### ISSUE TITLE
Sample (python/21.corebot-app-insights) fails due to a SyntaxError

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/BotBuilder-Samples#3442]
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: python
3. Sample name: python/21.corebot-app-insights

## Describe the bug
Bot deployed to Azure did not respond and throws `SyntaxError: invalid syntax => future = tasks.async(future, loop=self)` when inspecting the Azure logs.

| Bots                                   | Status                                                                                    |
| -------------------------------------- | ----------------------------------------------------------------------------------------- |
| samples/python/21.corebot-app-insights | • Fails due to, `SyntaxError: invalid syntax => future = tasks.async(future, loop=self).` |

## Expected behavior
Being able to communicate with the bot in Azure

## Actual behavior
Throws `SyntaxError: invalid syntax => future = tasks.async(future, loop=self)` when communicating with the bot.

**Comment by gandiddi** [comment]
To reproduce the issue, we need a LUIS application. However, starting April 1, 2023, users will no longer be able to create new LUIS resources. Therefore, we are closing the issue as we are unable to create a LUIS application.
