### ISSUE TITLE
Samples (python/wip/python_quart) fail due to RuntimeError

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/BotBuilder-Samples#3444]
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: python
3. Sample name: python/wip/python_quart - 02.echo-bot and 13.core-bot

## Describe the bug
The Bots throw the error `RuntimeError: wsgi app should be either Application or async function returning Application, got <Quart 'app'>.` at startup time.

| Bots                                        | Status                                                                                                                                                             |
| ------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| samples/python/wip/python_quart/02.echo-bot | • Work in Progress folder. <br> • Fails due to, `RuntimeError: wsgi app should be either Application or async function returning Application, got <Quart 'app'> .` |
| samples/python/wip/python_quart/13.core-bot | • Work in Progress folder. <br> • Fails due to, `RuntimeError: wsgi app should be either Application or async function returning Application, got <Quart 'app'> .` |

## Expected behavior
Being able to communicate with the bot.

## Actual behavior
Fails at startup due to a `RuntimeError`.

**Comment by tracyboehrer** [comment]
Removed sample
