### ISSUE TITLE
Sample (python/wip/python_tornado/02.echo-bot) fails due to not finding the aiohttp module

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/BotBuilder-Samples#3445]
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: python
3. Sample name: python/wip/python_tornado/02.echo-bot

## Describe the bug
The Bot throw the error `ModuleNotFoundError: No module named 'aiohttp'.` at startup time.

| Bots                                          | Status                                                                                            |
| --------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| samples/python/wip/python_tornado/02.echo-bot | • Work in Progress folder. <br> • Fails due to, `ModuleNotFoundError: No module named 'aiohttp'.` |

## Expected behavior
Being able to communicate with the bot.

## Actual behavior
Fails at startup due to the missing `aiohttp` module.

**Comment by tracyboehrer** [comment]
Removed sample
