### ISSUE TITLE
Sample (python/wip/python_tornado/13.core-bot) fails due to not finding the 'APP' attribute in 'app'

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/BotBuilder-Samples#3446]
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: python
3. Sample name: python/wip/python_tornado/13.core-bot

## Describe the bug
The Bot throw the error `Find attribute 'APP' in 'app'. Reason: App failed to load.` at startup time.

| Bots                                          | Status                                                                                                       |
| --------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| samples/python/wip/python_tornado/13.core-bot | • Work in Progress folder. <br> • Fails due to, `find attribute 'APP' in 'app'. Reason: App failed to load.` |

## Expected behavior
Being able to communicate with the bot.

## Actual behavior
Fails at startup due to be unable to find the attibute `APP`.

**Comment by tracyboehrer** [comment]
Removed sample
