### ISSUE TITLE
Experimental Sample (javascript_nodejs/08.todo-bot-with-luis-qnamaker) fails due to a Syntax Error

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/BotBuilder-Samples#3448]
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: javascript_nodejs
3. Sample name: adaptive-dialog/javascript_nodejs/08.todo-bot-with-luis-qnamaker

## Describe the bug
The Bot fails due to a Syntax error in the rootDialog.js file

| Bots                                                                          | Status                                                                                                                                      |
| ----------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| experimental/adaptive-dialog/javascript_nodejs/08.todo-bot-with-luis-qnamaker | • The Bot in Azure fails with InternalServerError <br> • Fails due to, Syntax error in rootDialog.js <br> • The Bot locally works properly. |

## Expected behavior
Being able to communicate with the bot.

## Actual behavior
Fails due to a Syntax Error.

**Comment by tracyboehrer** [comment]
Sample removed
