### ISSUE TITLE
Samples (typescript_nodejs/generator-botbuilder) fail and require an additional dependency to be installed

### ISSUE THREAD

**Issue by MartinLuccanera** [microsoft/BotBuilder-Samples#3449]
## Context
For more information, see the parent issue. #3436.
This is related to #3404 

## Sample information
1. Sample type: Samples
2. Sample language: typescript_nodejs - generator-botbuilder
3. Sample name: Several

## Describe the bug
While testing these bots, we found out that they required an additional dependency to be installed. In this case "@types/node": "^10.17.27".

Here's a list of all the cases we found

| Bots                                                                                                                         | Status                                               |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| typescript_nodejs/16.proactive-messages                                                                                      | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| typescript_nodejs/50.teams-messaging-extensions-search                                                                       | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| typescript_nodejs/51.teams-messaging-extensions-action                                                                       | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| typescript_nodejs/57.teams-conversation-bot                                                                                  | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| typescript_nodejs/58.teams-start-new-thread-in-channel                                                                       | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| generator-botbuilder/generators/app/templates/core                                                                           | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |
| generator-botbuilder/generators/app/templates/echo                                                                           | • Bot generated with Yeoman and deployed successfully.</br> For TS needed to add "@types/node": "^10.17.27" |

## Expected behavior
Bots work out the box using the provided deployment templates and configuration.

## Actual behavior
Manual installation of required dev dependency was needed.

**Comment by ceciliaavila** [comment]
Closing this issue as it couldn't be reproduced. We tested the listed bots using different nodeJS versions and the `npm install` is working fine.
