### ISSUE TITLE
Samples (python/60.slack-adapter) fails due to providing the set of arguments in the SlackAdapterOptions instance

### ISSUE THREAD

**Issue by MartinLuccanera** [microsoft/BotBuilder-Samples#3451]
## Context
For more information, see the parent issue. #3436.

## Sample information
1. Sample type: Samples
2. Sample language: python
3. Sample name: 60.slack-adapter

## Describe the bug
While testing these bots, we found out that it fails due to providing the set of arguments in the SlackAdapterOptions instance.

Here's a list of all the cases we found

| Bots                                                                                                                         | Status                                               |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| python/60.slack-adapter                                                                                                      | • Fails due to, providing the set of arguments in the SlackAdapterOptions instance.</br>• By replacing the SlackAdapterOptions in favor of SlackClientOptions which is the one that the SlackClient instance uses, solved the issue. |

## Expected behavior
Bots work out the box using the provided deployment templates and configuration.

## Actual behavior
Fails due to providing the set of arguments in the SlackAdapterOptions instance.

**Comment by gandiddi** [comment]
The specified Python sample, slack-adapter, no longer exists. The appropriate repository for this functionality appears to be the [BotBuilderCommunity](https://github.com/BotBuilderCommunity). Therefore, we are closing this issue.
