### ISSUE TITLE
Samples (java_springboot/81.skills-skilldialog/dialog-skill-bot) fails during build process

### ISSUE THREAD

**Issue by MartinLuccanera** [microsoft/BotBuilder-Samples#3455]
## Context
For more information, see the parent issue. #3436.

## Sample information
1. Sample type: Samples
2. Sample language: Java
3. Sample name: 81.skills-skilldialog

## Describe the bug
While testing these bots, we found out that it Fails due to, package `com.microsoft.applicationinsights.core.dependencies.apachecommons.io` does not exist

Here's a list of all the cases we found

| Bots                                                                                                                         | Status                                               |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| java_springboot/81.skills-skilldialog/dialog-skill-bot                                                                       | • Fails during build process. </br>Fails due to, package com.microsoft.applicationinsights.core.dependencies.apachecommons.io does not exist.</br>• Adding the package dependency to the pom.xml solved the issue. |

## Expected behavior
Bots work out the box using the provided deployment templates and configuration.

## Actual behavior
Manual addition of package dependency to pom.xml was required to solved the issue.

**Comment by tracyboehrer** [comment]
Closing as Java SDK is retired as of Nov 2023
