### ISSUE TITLE
Composer-Samples (javascript_nodejs) Fails to start the bot. Unable to get a value for host from state. undefined

### ISSUE THREAD

**Issue by MartinLuccanera** [microsoft/BotBuilder-Samples#3460]
## Context
For more information, see the parent issue. #3436.

## Sample information
1. Sample type: Samples
2. Sample language: csharp_dotnetcore
3. Sample name: OrchestratorSchoolNavigator/SchoolNavigator

## Describe the bug
While testing these bots, we found out that it Fails to start the bot with error: Unable to get a value for host from state. undefined.

Here's a list of all the cases we found

| Bots                                                                                                                         | Status                                               |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| javascript_nodejs/projects/qna-sample/qnasample                                                                              | • Fails to start the bot with error: Unable to get a value for host from state. undefined. </br>•The bot doesn’t work either locally or in Azure. |

## More context

The following error is thrown in the OnTurn Trace: 
      "name": "DialogContextError",
      "message": "Unable to get a value for host from state. undefined",
      "dialogContext": {
        "activeDialog": "qnasample",
        "stack": [
          {
            "id": "qnasample",
            "state": {
              "eventCounter": 9,
              "_adaptive": {
                "actions": []
              },
              "lastEvent": "endOfActions"
            },
            "version": "553652994"
          }
        ]
      }

## Expected behavior
Bots work out the box using the provided deployment templates and configuration.

## Actual behavior
The bot doesn’t work either locally or in Azure

**Comment by ceciliaavila** [comment]
Closing issue as it couldn't be reproduced. The bot is working ok. It's an empty bot that doesn't have any intent configured.
