### ISSUE TITLE
Provide a sample demonstrating the use of CloudAdapter

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotBuilder-Samples#3476]
[Sunday 3:19 PM] Tom Laird-McConnell
I can't seem to get CloudAdapter to authenticate:I am deriving from cloudAdapterBut when I try to talk to the bot from the emulator it rejects it, because it looks like a credentialFactory is not getting initialized correctly? 

[Sunday 3:47 PM] Tom Laird-McConnell
Ugh. I figured it out.  It was defaulting to null for appid/password because IConfiguration wasn't dependency injected. That sucks, if it depends on it should barf if is not there, not default to not working silently.

**Comment by mrivera-ms** [comment]
Samples are being migrated to Cloud Adapter here: #3307. Closing as duplicate.
