### ISSUE TITLE
[Help] Use path of file instead of stream

### ISSUE THREAD

**Issue by scibol** [Microsoft/BotBuilder-Samples#35]
Hi everybody,

is there some way to use 'request', but instead of stream.pipe a file stored in my local machine? I'm asking this because I need to convert mp4 to wav before processing with your Speech API.

I am referring to this: 
```
stream.pipe(request.post(speechRequestData, (error, response, body) => {
        if (error) {
            reject(error);
        }
        else if (response.statusCode != 200) {
            reject(body);
        }
        else {
            resolve(JSON.parse(body).header.name);
        }
    }));

**Comment by scibol** [comment]
Resolved, sorry.

**Comment by mukeshzt** [comment]
HI, 

I know this close issue can you guide me how you manage this. I want to convert wma to wav
