### ISSUE TITLE
[C#](samples/csharp_dotnetcore/54.teams-task-module): Task Module not opening in the desktop client

### ISSUE THREAD

**Issue by diabhoil** [microsoft/BotBuilder-Samples#3524]
## Sample information
1. Sample type: samples/csharp_dotnetcore/54.teams-task-module
2. Sample language: dotnetcore 
3. Sample name: 54.teams-task-module

## Describe the bug
After receiving the Adaptive Card from the bot, the task module dialog is not opening. It is just showing an error message. When I pop out the app, everything is working fine. The web version is working fine too.

PS. the icons provided with the example are in the wrong size for teams apps.

## To Reproduce
1. Deploy the example
2. Add the app (after fixing the icon problems) to teams
3. Chat with the bot and try to open the task module

## Expected behavior
A task module dialog should open like this:
![image](https://user-images.githubusercontent.com/42711805/137457733-a44c6c29-090b-4426-899c-d62583b026e0.png)

## Screenshots
![image](https://user-images.githubusercontent.com/42711805/137457384-d72f465d-17a6-4435-bb6b-8093cfc5cf2d.png)

## Additional context
![image](https://user-images.githubusercontent.com/42711805/137457466-40b287a0-9d73-441c-a77a-47f4b4c41323.png)
Developer Preview and public preview enabled

Having a thread at stackoverflow too: [stackoverflow](https://stackoverflow.com/questions/69574024/teams-how-to-open-task-module-from-adaptive-card-in-desktop-app)

**Comment by anusharr** [comment]
@diabhoil, glad to hear that it is working now. Have you tried to set the bot to bidirectional and see if it works?

**Comment by diabhoil** [comment]
@anusharr, yes I've tried with the same code, and with different code. Tried a lot. I also have tried to set up the app with a bidirecitonal bot, but Teams just ignores the setting (opened an issue for this [here](https://github.com/MicrosoftDocs/msteams-docs/issues/4423)). To test that I have to build a new app (or use a new bot registration) and I had no time so far :(

**Comment by anusharr** [comment]
Thanks for the linked issue. Looks like the concerned Teams team is able to repro the bidirectional bot issue on their end and is investigating further. Once the bug fixed, can you give it a go and see if it works as expected? As of now, I am going to close this issue as the Teams Task Module sample is working. If the bot doesn't work as expected even after the fix, then I would suggest you to open a new issue and someone from the Bot framework team would be happy to assist you.
