### ISSUE TITLE
can't deploy nodejs using ARM templates

### ISSUE THREAD

**Issue by steveb85** [microsoft/BotBuilder-Samples#3561]
## Sample information
1. Sample type: Tried multiple samples 
2. Sample language: nodejs
3. Sample name: 02 echo 

## Describe the bug
deployment using ARM templates happens, with no errors, however the deployment is not working. It seems to build a .NET app service, disregarding that the sample is built on nodejs have tried with existing RG and with new RG, and also with new app service and with old. 

No errors, I checked TLS and also tried steaming endpoint. Works on emulator (with correct app id and password) 

Upon testing in WebChat, the chat loads, but the bot never responds, even a welcome message, any further input from the user appears to send, but the Channels blade reveals the error 

"There was an error sending this message to your bot: HTTP status code NotFound"

## To Reproduce
create sample bot, deploy as suggested at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp

have tried every variable. Using Sample 13. there was a linux folder within the deploymentTemplates folder, this created the correct appservice resource but still presented with the other issues.

**Comment by stevkan** [comment]
@steveb85, thank you for your patience. I will be attempting a repro today and should have a response for you by EOD.

**Comment by steveb85** [comment]
> @steveb85, thank you for your patience. I will be attempting a repro today and should have a response for you by EOD.

Thanks, I ended up doing a manual deploy, creating my own resources in azure, and deployed via an external git, and can manually push it, so no rush, I am up and running. however i’m curious to find the fault for future deployments.

**Comment by stevkan** [comment]
A quick question, can you double check that the bot's configuration includes the MicrosoftAppId and MicrosoftAppPassword and that the values are correct?

Also, regarding the "seems to build a .NET app service" bit, I believe that this is normal and expected. The JS files are there, or should be. I will double check this, however.

**Comment by steveb85** [comment]
@stevkan yes, I can confirm
I checked the id and password multiple times it would make the initial connection, but not respond.

**Comment by mrivera-ms** [comment]
Thank you for reporting this issue @steveb85. The deployment templates have been recently updated. Can you please try pulling the most recent versions and try again?

**Comment by stevkan** [comment]
Closing due to lack of response.
