### ISSUE TITLE
Samples (csharp_dotnetcore/49.qnamaker-all-features): 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.'

### ISSUE THREAD

**Issue by dougbw** [microsoft/BotBuilder-Samples#3588]
# Context:
Sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/49.qnamaker-all-features
This sample uses an obsolete class `ComponentRegistration` and I cannot find a working example with the correct implementation

# Additional Context:
The botbuilder-dotnet package was updated to change component registration: https://github.com/microsoft/botbuilder-dotnet/pull/5347

# Solution
Please provide an up to date sample of the botbuilder-dotnet BotComponent implementation

**Comment by rizified** [comment]
any update on this?

**Comment by gabog** [comment]
Hi, @dougbw and @rizified, it is OK to continue using the deprecated ComponentRegistration in this case, we will update the samples once we have a better implementation, but you should be OK
