### ISSUE TITLE
Sample Request: New Language Cognitive Service (QnA Maker replacement) 

### ISSUE THREAD

**Issue by ksuchy** [microsoft/BotBuilder-Samples#3593]
**Is your feature request related to a problem? Please describe.**
QnA Maker has recently migrated to use the new Language Cognitive Service. The Bot Framework does not appear to have a package to integrate with this service.

**Describe the solution you'd like**
It would be great to have a sample of a starter bot that fulfills questions from a project/knowledge base created within the Language Studio.

**Describe alternatives you've considered**
The provided QnA Maker samples do not work with the new service as Language Studio does not provide a KB ID (needed in appsettings.json)

**Additional context**

**Comment by dougbw** [comment]
We are in the same position - The QnA maker portal is pushing users to upgrade but from what I can see the [bot-builder-dotnet](https://github.com/microsoft/botbuilder-dotnet) SDK which we consume has not published updated packages which actually integrate with the new Language Studio.

I did manage to find a working sample by deploying a bot through the new language studio, then reverse engineering the ARM template which is used to spin up the app service which revealed a zip file which contains a modified version of the [49.qnamaker-all-features](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/49.qnamaker-all-features) sample which integrates with the new language studio.

For reference the zip file in question can be found here: https://qnamaker-data.trafficmanager.net/qnamakerdata/botservice/qnav2bot-cs.zip

**Comment by tracyboehrer** [comment]
See 12.customQABot
