### ISSUE TITLE
Impossible to loop proactive messaging for more than 200-400 messages Node.JS (S1 instance)

### ISSUE THREAD

**Issue by matthdonnet** [microsoft/BotBuilder-Samples#3600]
## Sample information
The official code:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=typescript#samples

Our code where we want to add a wait timeout:

     const members = await connector.conversations.getConversationMembers(activity.conversation.id);
     let lastRequestTs = 0;
     let index = -1;
     let currentTime = new Date().getTime();
     console.log("Started sending messages at: " + currentTime);
     members.forEach(async (teamMember) => {
     try {
     // WE NEED THE setTimeout HERE TO DELAY ALL THE REQUESTS

     const privateMessageActivity = MessageFactory.text(privateMessageText + "   \n" + markdownLink);

     var ref = TurnContext.getConversationReference(context.activity); // this one is making a request to the teams server
     ref.user = teamMember;

       await context.adapter.createConversation(ref,
         async (t1) => {
           const ref2 = TurnContext.getConversationReference(t1.activity); // this one is making a request to the teams server
           await t1.adapter.continueConversation(ref2, async (t2) => {
               index++;

             await new Promise(resolve => setTimeout(async (resolve) =>  {

               var sendAct = await t2.sendActivity(privateMessageActivity); // this one is making a request to the teams server

               let currentTs = new Date().getTime();
               console.log("SENDING MESSAGE: " +  teamMember.email + " - " + (currentTs - lastRequestTs));
               lastRequestTs = currentTs;

             }, index * 3000));
           });
       });

     } catch(exception){
     telemetry.trackException({ exception: exception });
     console.log(exception);
     }

     });

## Describe the bug

When we add something like

     const sleep = (sec) => new Promise(res => setTimeout(res, sec * 1000))
     await sleep(1); //waits for 1 second before continuing further.

The output is: "TypeError: Cannot perform 'get' on a proxy that has been revokedat members.forEach (D:\home\site\wwwroot\index.js:142:72)"

If we don't put the wait: the function crashes after 400 messages (the bot is setup in a 1500 team members channel on a S1 instance)
getConversationReference fails.

## To Reproduce
Steps to reproduce:
Use the current MSFT docs and try it in a 1500 members channel.

## Expected behavior
You get a connection timeout

**Comment by shashank0708** [comment]
Try using 

`for(const teamMember of members){}`

and put this in a function and set it's type as async.

**Comment by matthdonnet** [comment]
Thanks, and how would you timeout?

**Comment by matthdonnet** [comment]
It worked! Thanks a lot.

**Comment by stevkan** [comment]
@matthdonnet, looking at your code, the 'get' error is likely coming from attempting to use `setTimeout()` to delay sending an activity. This is a known issue that others have discovered before. I came up with this solution (the code below) to get around the 'get' error when wanting to use either `setInterval()` or `setTimeout()`. For clarity, I'm using this inside a waterfall step in a component dialog.

Try updating your code to utilize the `asyncInterval()` function implementation and see if it works in your use case. 

```js
const TEXT_PROMPT = 'textPrompt';
const SET_TIMEOUT_WITH_PROMISE_DIALOG = 'setTimeoutWithPromiseDialog';

class SetTimeoutWithPromiseDialog extends ComponentDialog {
  constructor(id) {
    super(id);

    this.addDialog(new TextPrompt(TEXT_PROMPT))
      .addDialog(new WaterfallDialog(SET_TIMEOUT_WITH_PROMISE_DIALOG, [
        this.askQuestionStep.bind(this),
        this.setTimeoutStep.bind(this),
      ]));

    this.initialDialogId = SET_TIMEOUT_WITH_PROMISE_DIALOG;
  }

  async askQuestionStep(stepContext) {
    const message = MessageFactory.text('Type something...and then count the seconds...');
    return await stepContext.prompt(TEXT_PROMPT, message);
    // return await stepContext.next();
  }

  async setTimeoutStep(stepContext) {
    await asyncTimeout(async () => await stepContext.context.sendActivity("Woot! A brilliant 4 seconds just passed. And, you'll never get them back!"), 4000);

    // I'm using 'beginDialog()' to replay the dialog
    return await stepContext.beginDialog(SET_TIMEOUT_WITH_PROMISE_DIALOG);
    // return await stepContext.endDialog();
  }
}

module.exports.SetTimeoutWithPromiseDialog = SetTimeoutWithPromiseDialog;
module.exports.SET_TIMEOUT_WITH_PROMISE_DIALOG = SET_TIMEOUT_WITH_PROMISE_DIALOG;

const asyncInterval = async (callback, ms, triesLeft = 5) => new Promise((resolve, reject) => {
  const interval = setInterval(async () => {
    if (await callback()) {
      resolve();
      clearInterval(interval);
    } else if (triesLeft <= 1) {
      reject();
      clearInterval(interval);
    }
    triesLeft--;
  }, ms);
});

const asyncTimeout = async (callback, ms) => new Promise((resolve, reject) => {
  const timeout = setTimeout(async () => {
    if (await callback()) {
      resolve();
      clearTimeout(timeout);
    } else {
      reject();
      clearTimeout(timeout);
    }
  }, ms);
});
```

**Demo:**
![setTimeoutWithPromise](https://user-images.githubusercontent.com/18403946/142667739-677b849b-443d-44cd-8cfa-f6491316e540.gif)

**Comment by matthdonnet** [comment]
Thanks a lot Steven!
