### ISSUE TITLE
Bot not able to send uploaded attachments to the user in Sample 15

### ISSUE THREAD

**Issue by birla** [microsoft/BotBuilder-Samples#3612]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 15.handling-attachments

## Describe the bug
The bot is not able to demo the uploaded attachment option.

## To Reproduce
1. Configure the bot
2. Run and open the bot in Teams
3. Type "hi"
4. Select option 3

## Expected behavior
The bot should share an uploaded attachment with the user.

## Screenshots
![image](https://user-images.githubusercontent.com/283677/143239087-e45275bc-fc3f-4f05-8524-7e6dd9dfdaf2.png)

**Comment by birla** [comment]
The rest API call results in a 404 Not Found error.

**Comment by stevkan** [comment]
@birla, thank you for your patience. I was able to repro the issue and am looking at the sample to try and identify where the problem lies.

Out of curiosity, when you first ran the bot from the sample, did you get an error related to the 'path' module not being installed, like below? I had to manually install that module before I could repro your issue. Just verifying if this is specific to me or if others encounter it.

> [onTurnError] unhandled error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by birla** [comment]
@stevkan, great! No, I don't remember seeing any missing modules on first use.

**Comment by EricDahlvang** [comment]
Please refer to sample https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/56.teams-file-upload for uploading files to Teams bots.

**Comment by stevkan** [comment]
@birla, thank you for your patience. I hope to have a response for you soon regarding the sample. Eric's comment brings up a clarifying question I have. To be clear, are you referring to a bot that has uploaded an image that then should display and be downloadable (like in sample 15, specifically) or are you referring to an image or attachment you have sent to the bot and then should display and be downloadable (sample 56)? I assumed the first, but your response would be helpful.
