### ISSUE TITLE
No Example for Ask Activity in AskingQuestionsSample 

### ISSUE THREAD

**Issue by MCKRUZ** [microsoft/BotBuilder-Samples#3616]
**Is your feature request related to a problem? Please describe.**
In the AskingQuestionsSample application you have examples of every other action besides the Ask Activity action

**Describe the solution you'd like**
I would like a clear example of this action like the ones you have for the other actions under the Ask A Question heading

**Additional context**
In addition it would also be nice to update the documentation to include this feature, because there is nothing about it in the docs at all.

**Comment by benbrown** [comment]
@MCKRUZ The Ask activity was part of the dialog generation tools and should not be directly used by end users.

**Comment by gabog** [comment]
@MCKRUZ, closing this one, feel free to re-open if you have more questions
