### ISSUE TITLE
Reload dialog stack to resume conversation after long-running activity

### ISSUE THREAD

**Issue by lshade** [microsoft/BotBuilder-Samples#3677]
How can I load the dialog stack like this comment suggests?

https://github.com/microsoft/BotBuilder-Samples/blob/0dab95601c6a97324f5e3011eedf665233ae1d4a/experimental/immediate-accept-adapter/csharp_dotnetcore/Bots/EchoBot.cs#L117

I'm working on Middleware that reprompts a user after they have been silent for 15 seconds. I trigger this background task and then ask the last prompt again if it's been 15 seconds since the last message. 

My issue is that if the user responds to the reprompt, their response is taken to the beginning of the conversation stack instead of as the answer to the prompt inside the dialog.

For example,

bot: Welcome, how may I help you?
user: book appointment
bot: What type of appointment?
_15 seconds passes_
bot on background thread: Sorry, I didn't hear you. What type of appointment?
user: Automobile
_bot treats "Automobile" like it was the answer to "Welcome, how may I help you?" instead of the current prompt_

**Comment by ceciliaavila** [comment]
Hi @lshade, we have been trying to generate a sample to reproduce this issue, it would be very helpful if you could share your code so we can better analyze the problem with the dialog stack.
Thanks!
