### ISSUE TITLE
Java Samples on Unit Testing

### ISSUE THREAD

**Issue by ClaudioConsolmagno** [microsoft/BotBuilder-Samples#3690]
**Is your feature request related to a problem? Please describe.**
I'm having a hard time writing unit tests for the code using botframework in Java. Sure I can manually test the logic, but writing unit tests isn't trivial with the way TurnContext, ActivityHandler, Dialogs, etc have numerous different attributes. It could be that there are replacement mock classes for testing but none that I could find. Also, there is valid usage for certain static methods that, for being static, are naturally hard to mock such as `TeamsInfo.getMember()` which makes external api call.

**Describe the solution you'd like**
I'd like to see in the Java repositories, samples of how we should go about unit testing. Even the "echo-bot" sample doesn't have any tests which is disappointing.

**Comment by tracyboehrer** [comment]
Closing as Java SDK is retired as of Nov 2023
