### ISSUE TITLE
Errors are ignored by the bot (python)

### ISSUE THREAD

**Issue by master0v** [microsoft/BotBuilder-Samples#3699]
I am just starting to modify the echobot provided by Microsoft

```
class EchoBot(ActivityHandler):
  
  async def on_message_activity(self, turn_context: TurnContext):    
    return await turn_context.send_activity(MessageFactory.text(f"Echo: {message_text}"))
```
for some reason any errors in my code are ignored, as in the bot hides any error messages and simply fails to return from await `ADAPTER.process_activity(...`

for example if I modify the code above to

```
class EchoBot(ActivityHandler):
  
  async def on_message_activity(self, turn_context: TurnContext):  
    throw("ERROR!")
    return await turn_context.send_activity(MessageFactory.text(f"Echo: {message_text}"))
```
it shows no sign of failure in the console. Does it write errors somewhere else? This makes it impossible to debug any issues whatsoever.

**Comment by master0v** [comment]
you can close this issue.  It happens because your stupid sample includes `file=sys.stderr`

**Comment by BruceHaley** [comment]
In my repro, following [this documentation](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot#testing-the-bot-using-bot-framework-emulator), the error did get written to the console as designed.
