### ISSUE TITLE
Rename release branches to releases/Major.Minor and apply branch protection rules

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotBuilder-Samples#3700]
Parent Issue: [botframework-sdk/issues/6468](https://github.com/microsoft/botframework-sdk/issues/6468)
## Summary

We don't have branch protection rules enabled on our release branches and we name them as RXY (R14, R15, etc.).  There are two problems with this approach:
1. Defining a branch protection rule for R* is to broad and will impact any branch that starts with "r".
2. RXY doesn't mean much to people outside the team

The changes involve: 
1. Renaming all the release branches to `releases/Major.Minor`
2. Adding a branch protection rule with the pattern `releases/*` and enforce the same restrictions we have on main on release branches.

The renamed branches will look like this:
![image](https://user-images.githubusercontent.com/12264946/145418415-e75e4f1c-94dc-45cc-838b-97f201d9e340.png)

The branch protection rules for release branches will look like this:
![image](https://user-images.githubusercontent.com/12264946/145418281-4f8a1dda-7bf0-47ae-8757-8010ab3f749c.png)

**Comment by BruceHaley** [comment]
Completed for all branches.
