### ISSUE TITLE
Incomplete telemetry setup

### ISSUE THREAD

**Issue by ivopisarovic** [microsoft/BotBuilder-Samples#3706]
## Sample information
1. Sample type: samples
2. Sample language: python
3. Sample name: 21.corebot-app-insights

## Describe the bug
The example (https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/21.corebot-app-insights/app.py) is completely missing the initialization of the TelemetryMiddleware. Hence, logging is not set up completely and messages are not sent to App Insigts.

```
INSTRUMENTATION_KEY = CONFIG.APPINSIGHTS_INSTRUMENTATION_KEY
TELEMETRY_CLIENT = ApplicationInsightsTelemetryClient(
    INSTRUMENTATION_KEY, telemetry_processor=AiohttpTelemetryProcessor(), client_queue_size=1
) if INSTRUMENTATION_KEY else None
TELEMETRY_LOGGER_MIDDLEWARE = TelemetryLoggerMiddleware(TELEMETRY_CLIENT, True) # this is the key missing part to log sent and received messages!
ADAPTER.use(TELEMETRY_LOGGER_MIDDLEWARE) # this is the key missing part to log sent and received messages!
```

## To Reproduce
1. Set up `AppInsightsInstrumentationKey` env var.
2. Start the bot and communicate.
3. Info about sent and received messages does not appear in Application Insights. Only the waterfall dialog steps are logged.

## Expected behavior
Sending logs about sent and received messages to Application Insights.

**Comment by anishprasad01** [comment]
Hi @ivopisarovic,

As per my understanding, that's how the samples are written, due to the need to get user consent to log more deeply than that. That said, I see from the linked issue that there may be some discrepancies relating to how to enable such logging in the docs. I will investigate that and see what the next steps might be.

**Comment by anishprasad01** [comment]
@ivopisarovic

Thanks for your report. Once the linked PR goes through, this issue will be considered resolved and closed. After that, we will look into updating the docs.
