### ISSUE TITLE
Move custom adapter samples to community

### ISSUE THREAD

**Issue by gabog** [microsoft/BotBuilder-Samples#3713]
## Summary

The custom adapters have been deprecated in https://github.com/microsoft/botbuilder-dotnet/pull/6137 and moved to https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries.

As part this issue, we should move the samples for the custom adapters to the community repo and remove the reference from the samples readme: https://github.com/microsoft/botbuilder-samples#custom-adapter-samples

**Comment by mrivera-ms** [comment]
PR created: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/472

**Comment by JonathanFingold** [comment]
@gabog , @mrivera-ms , Can we please also update https://github.com/Microsoft/botframework-sdk#channels-and-adapters. Also, this broke a couple articles.

**Comment by gabog** [comment]
Yes, we should update the docs, will ping you offline so we can scope the work.
