### ISSUE TITLE
v4 C# samples should explicitly call the state accessor's SetAsync method

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#373]
### SDK Platform
C# (ASP.NET Core)

### URL of Code Sample
csharp_dotnetcore/2.EchoBot-With-Counter/

However, many (if not most) of the samples that work with state seem to skip the SetAsync step.

### Problem Description
Update sample 2 to use an `int` for the state property, instead of the CounterState class.
Run the sample.
Note that in the Emulator the counter always stays at 1.

By not calling SetAsync, we're relying on not losing the original reference to our state object. This can get broken in many ways, but using a value type as the state object is the easiest.

**Comment by JonathanFingold** [comment]
@johnataylor , @cleemullins , Can one of you surface this. It seems like a key concept for devs to understand.

**Comment by daveta** [comment]
@JonathanFingold : Yep, it's not setting.

**Comment by daveta** [comment]
Thanks Jonathan!
