### ISSUE TITLE
Update dotnet samples to target Net 6

### ISSUE THREAD

**Issue by gabog** [microsoft/BotBuilder-Samples#3740]
## Summary

**Note:** we should begin working on this issue once https://github.com/microsoft/botbuilder-dotnet/issues/5977 is complete and we can reference builds that target net 6 from my get. 

As part of this issue we will update the dotnet samples to target Net 6. We will not adopt Net 6 specific features like implicit namespaces or class names so customers can re-target 3.1 if needed. 

We should also update the Readmes to require net 6.

We should do manual testing on EchoBot, CoreBot and some teams bots to make sure everything works as expected.

**Comment by markgibbons25** [comment]
Would be nice to have https://github.com/BotBuilderCommunity/botbuilder-community-dotnet updated too (they are still referencing .NET Core 2).

**Comment by tracyboehrer** [comment]
Merged
