### ISSUE TITLE
bot-teams-authentication miss dependency ！！！

### ISSUE THREAD

**Issue by zsoftbuilder** [microsoft/BotBuilder-Samples#3745]
bot-teams-authentication miss dependency ？
Missing artifact com.microsoft.graph:microsoft-graph:jar:2.8.9  ，why？

**Comment by LeeParrishMSFT** [comment]
Looks like an incorrect version was updated on that dependency from 2.6.0 to 2.8.9 a few months ago and there is no 2.8.9 version in maven. We can make an update to the pom.xml to reflect this, but until that is pushed into the repo you can also make the same change by updating the pom.xml file to reference the 2.9.0 version for com.microsoft.graph.
