### ISSUE TITLE
Library cannot function without isomorphic fetch

### ISSUE THREAD

**Issue by breakpoint7** [microsoft/BotBuilder-Samples#3758]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 24.bot-authentication-msgraph/

## Describe the bug
Running this sample produces a fetch error.  When the call to create SimpleGraphClient tries to run, it kicks back the following error:
[onTurnError] unhandled error: DialogContextError: Library cannot function without fetch. So, please provide polyfill for it.

I've had the same problem trying to user SimpleGraphClient in nodejs in other places, so I decided to go back to this very simple sample.  
If you trace into the client calls, it is kicking back a PolyFillNotAvailable

## To Reproduce
Follow the sample steps as advertised -- login and get authenticated, then try to issue the command 'me'.  That fires a call into the client auth library that fails.

## Expected behavior
I expect this call to complete successfully

**Comment by anishprasad01** [comment]
Hi @breakpoint7,

I'm currently investigating this. Could you please try something for me?

1.  In your bot, run `npm install isomorphic-fetch` to install the package. In your `package.json` file, you should then see this package in the dependencies.
2. At the top of `index.js`, add the line `require("isomorphic-fetch")`
3. Run the bot
 
Let me know if the issue persists after this, and what error messages (if any) appear.

**Comment by breakpoint7** [comment]
Thanks, that works.
