### ISSUE TITLE
Python echo bot sample should use the cloud adapter

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#3763]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [python]
3. Sample name: <02.echo-bot>

## Describe the bug
Sample uses old adapter, instead of the "best practice" cloud adapter.

re: https://github.com/microsoft/BotBuilder-Samples/blob/a09dd4672bf315f26d50e09373ec5e717ef74d21/samples/python/02.echo-bot/app.py#L24-L27

## To Reproduce
1. Go to the Python 02 echo bot sample.
1. Open **app.py** and find where the adapter is created.
1. See error.

## Expected behavior
All samples (that don't use custom channel adapters (other than Java)) should use the cloud adapter, _especially_ introductory ones.

## Additional context
The docs rely on the code in the samples, so if the samples are not showing best practice, the docs will also tell a confusing story.

- Also seen in Python sample 13.core-bot.

**Comment by gabog** [comment]
Hi @JonathanFingold, we will not be updating Python samples going forward, closing this issue
