### ISSUE TITLE
bf:luis build failing for Region WestEurope, Access Denied

### ISSUE THREAD

**Issue by ShivaniJain-msft** [microsoft/BotBuilder-Samples#3765]
## Describe the bug
I have an Azure Bot which is using LUIS. I am trying to deploy both via CICD pipeline. Region of LUIS resources is West Europe.
In Build-LUIS.ps, while trying to build luConfigFile, I am getting error -

**Luis build failed: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
##[error]Script failed with exit code: 1**

![image](https://user-images.githubusercontent.com/100755187/171955511-7ec6f36d-8b42-4d09-99c7-b64821f0b49d.png)

## To Reproduce
1. Create CICD Pipeline for Bot deployment
2. Create LUIS Authoring and Prediction Resources in West Europe region.
3. Run the pipeline to start the deployment.
4. Publish Luis fails with the mentioned error.

## Expected behavior
LUIS should be published successfully

## Screenshots
![image](https://user-images.githubusercontent.com/100755187/171956008-82dec5e7-aa2c-46cb-ae7b-f6d8aa4ffb4a.png)

## Additional context
It is an incremental pipeline used for deployment in Dev, QA and Performance env, its working in Dev, QA which are in West US region.

**Comment by BruceHaley** [comment]
Hi Shivani,
I assume you are following the [documentation here](https://docs.microsoft.com/en-us/composer/how-to-cicd) to create your pipeline.
Using that documentation, the following steps ought to work for you:
1. Create the bot in Composer specifying West Europe for the LUIS location.
2. Test the bot in Composer in Web Chat.
3. In Composer, publish the bot to Azure.
4. In Azure, test the bot in Test in Web Chat.
5. In Azure, get the settings for LUIS, etc. from the settings/appsettings.json file.
6. In your CICD pipeline, set the variables using the values from step 5.
7. Run the pipeline to publish the bot.
8. In Azure, test the bot in Test in Web Chat.

I understand you are using the Core Bot with Language template to create the bot. I followed the above steps using that template, and it worked for me.

Also, please ensure you are using the latest .yaml files in your pipeline. Those files are [here](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSample/build/yaml).

If you are still having problems, let me know and we can review your process together.

--Bruce
