### ISSUE TITLE
[Feature Request] Interactive Fiction

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/BotBuilder-Samples#3767]
I would like to request a Bot Builder sample which showcases uses of dialog systems, perhaps spoken-language varieties, as [conversational user interfaces](https://en.wikipedia.org/wiki/Conversational_user_interface) for [interactive fiction](https://en.wikipedia.org/wiki/Interactive_fiction) games.

Classic examples of interactive fiction games include [Colossal Cave Adventure](https://en.wikipedia.org/wiki/Colossal_Cave_Adventure) and [Zork](https://en.wikipedia.org/wiki/Zork). Perhaps dialog-system-based interactive-fiction games would be enjoyable to develop and would delight end-users who could, thanks to the Bot Framework, play across a number of communication channels using one of a number of devices.

Thank you for considering these topics for a new Bot Builder sample.

**Comment by stevkan** [comment]
@AdamSobieski - thank you for the suggestion.

However, the purpose of the provided samples is to demonstrate how a developer can utilize the various libraries of the BotFramework SDK. For example, adding component dialogs, sending an activity or event, connecting QnA/LUIS (and how to pass/receive data from those services), or sending a task module in Teams.

The samples are not meant to demonstrate the different kinds of bots that can be built from the SDK. The actual construction of the bots is left to the developer to design, build, and publish.
