### ISSUE TITLE
What is the correct method to create a CloudAdapter instance?

### ISSUE THREAD

**Issue by gleysonlf** [microsoft/BotBuilder-Samples#3797]
All Typescript samples follow the following pattern to instantiate a CloudAdapter where the mandatory parameter of type "Configuration" is passed a null value:

1. Create a "credentialsFactory with ConfigurationServiceClientCredentialFactory;
2. Creates a botFrameworkAuthentication with createBotFrameworkAuthenticationFromConfiguration passing as parameter "null" and the "credentialsFactory";
3. Create an "adapter" with CloudAdapter passing as a parameter the "botFrameworkAuthentication";

**What is the correct method to create a CloudAdapter instance?**

## Sample information
**1. Sample type: ** samples
**2. Sample language:**  typescript
**3. Sample name:** 
- 00.empty-bot
- 02.echo-bot
- 03.welcome-users
- 05.multi-turn-prompt
- 06.using-cards
- 16.proactive-messages
- 50.teams-messaging-extensions-search
- 51.teams-messaging-extensions-action
- 57.teams-conversation-bot
- 58.teams-start-new-thread-in-channel

## To Reproduce
1. Clone and install de solution according to instructions in the README
2. Configure tsconfig.json with compiler options strict, noImplicitOverride, emitDecoratorMetadata and experimentalDecorators as true
3. Build and run application

## Expected behavior
Normal build and started application

## Screenshots
![image](https://user-images.githubusercontent.com/33023194/180468571-fd2a6b27-1cc8-4072-ad9b-7d4818ed2b57.png)
![image](https://user-images.githubusercontent.com/33023194/180468166-0f3de97b-22fc-4b83-a131-e5cb5fbb7f91.png)
![image](https://user-images.githubusercontent.com/33023194/180468313-fecd9753-1bc2-4a0a-b08f-f12db7a1394d.png)

**Comment by anishprasad01** [comment]
Hi @gleysonlf,

This is probably related to #3792. You can take a look at that one for inspiration for the moment, and I will see about having the TypeScript samples updated as well.

**Comment by gleysonlf** [comment]
Hi @anishprasad01, thanks for your reply.

I've seen this commit with tweaks, but the parameter applied to the ConfigurationBotFrameworkAuthentication class constructor required BotOpenIdMetadata, OAuthApiEndpoint, ValidateAuthority, or even a ToChannelFromBotLoginUrl.

Once the ProcessEnv has been sent, I receive:

`Type 'ProcessEnv' has no properties in common with type '{ BotOpenIdMetadata?: string | undefined; ChannelService?: string | undefined; OAuthApiEndpoint?: string | undefined; ValidateAuthority?: string | boolean | undefined; ToChannelFromBotLoginUrl?: string | undefined; ... 5 more ...; CallerId?: string | undefined; }'.`

I tried to directly send an object like ConfigurationBotFrameworkAuthenticationOptions but no success. The app runs but does not connect. 

**index.ts**
```
const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication(
  {
    MicrosoftAppId: string;
    MicrosoftAppPassword: string;
    MicrosoftAppType: string;
    MicrosoftAppTenantId: string;
  } as ConfigurationBotFrameworkAuthenticationOptions
);
```

Bot Emulator:
```
POST 400 directline/conversations/<conversationId>/activities
```

**Sending an empty object, I have the same result.**

**Comment by anishprasad01** [comment]
Thanks, we'll investigate further.

**Comment by munozemilio** [comment]
Hello @gleysonlf the PR that addresses this issue has been merged. Could you please try the samples again?

**Comment by gleysonlf** [comment]
Hi @munozemilio, worked perfectly! Thanks!

**Comment by gleysonlf** [comment]
```
import {
    CloudAdapter,
    ConfigurationBotFrameworkAuthentication,
    ConfigurationBotFrameworkAuthenticationOptions
} from 'botbuilder';

const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication(process.env as ConfigurationBotFrameworkAuthenticationOptions);
const adapter = new CloudAdapter(botFrameworkAuthentication);
```
