### ISSUE TITLE
Internal Service Error through Emulator

### ISSUE THREAD

**Issue by anjika456** [microsoft/BotBuilder-Samples#3798]
## Sample information
1. Sample type: BotBuilder-Samples - samples
2. Sample language: python
3. Sample name: 02.echo-bot

## Describe the bug
When I attempt to run the code in the emulator I receive an error

## To Reproduce
1. I installed the latest bot simulator using the link provided in the README, and downloaded this "[BotFramework-Emulator-4.14.1-windows-setup.exe](https://github.com/microsoft/BotFramework-Emulator/releases/download/v4.14.1/BotFramework-Emulator-4.14.1-windows-setup.exe)"
2. Then I launched the emulator
3. Pressed file -> open bot
4. entered the url given "http://localhost:3978/api/messages"
5. typed in "hello bot"
6. received a "500: Internal Service Errors"

## Expected behavior
I expected the bot to say "hello bot" back to me as I picked the echo version

## Screenshots

![error4](https://user-images.githubusercontent.com/49654265/180783695-b9b1c28e-97b1-43ff-a9d8-8d00f2a905df.JPG)

## Additional context
This is my first time reporting an issue so please let me know if I needed to add any other details! Thanks!

**Comment by ramfattah** [comment]
Hi @anjika456,

I'm not able to reproduce this issue using python sample [02.echo-bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot).

![image](https://user-images.githubusercontent.com/38049078/180836890-13090926-c3a2-40b5-983b-161c583222c0.png)

#

I was able to run the bot by following instructions here
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot#readme

What steps did you take to run the bot?

**Comment by anjika456** [comment]
I used the exact steps on that page under Testing the Bot using bot framework emulator...could I have downloaded the wrong emulator, I downloaded the windows setup
![emulator](https://user-images.githubusercontent.com/49654265/180837679-fa5877bf-255b-496c-8fe8-31213090412a.JPG)

**Comment by ramfattah** [comment]
Hi @anjika456,

I'm using Emulator v 4.14.1 as well. Not sure why it's not working for you.

Could you please configure Ngrok in Emulator settings using the below link instructions and try again?
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)

**Comment by anjika456** [comment]
![ngrok](https://user-images.githubusercontent.com/49654265/181077038-d2851e32-5498-4a42-aab4-dd3cc6f318f4.JPG)

So I configured ngrok but still no "Hello and Welcome" message...

**Comment by ramfattah** [comment]
@anjika456, what command did you execute to run the bot on localhost?

**Comment by anjika456** [comment]
I just opened the bot emulator application and then pressed file, open bot and entered "http://localhost:3978/api/messages". I waited a bit for a message to pop up and nothing did so I typed in hello

**Comment by ramfattah** [comment]
I'm referring to the [02.echo-bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot) it self, not Emulator.

How did you run the bot? ex: `python app.py` ?
After you send the message `hello`, is there any exception message in the same terminal window you ran than bot?

**Comment by ramfattah** [comment]
@anjika456,

For example; here are the steps I took to run the **echo bo:**
1. Cloned [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) into my local machine
2. Navigated to echo bot's root directory at 
     * `botbuilder-samples/samples/python/02.echo-bot/`
3. Created virtual environment by executing: `python -m venv env`
4. Activated virtual environment by running: ` env\Scripts\Activate.ps1` in Powershell
5. Installed dependency packages by running: `pip install -r requirements.txt`
6. Ran the bot by executing this command in powershell: `python app.py`

After running comman in step 6, in powershell it displays `Running on http://localhost:3978`
![image](https://user-images.githubusercontent.com/38049078/181133710-216d5209-46f5-4d87-8558-d76260c7a5ed.png)

**Comment by ramfattah** [comment]
@anjika456,

For example; here are the steps I took to run the **echo bo:**
1. Cloned [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) onto my local machine
2. Navigated to echo bot's root directory at 
     * `botbuilder-samples/samples/python/02.echo-bot/`
3. Created virtual environment by executing: `python -m venv env`
4. Activated virtual environment by running: ` env\Scripts\Activate.ps1` in Powershell
5. Installed dependency packages by running: `pip install -r requirements.txt`
6. Ran the bot by executing this command in powershell: `python app.py`

After running comman in step 6, in powershell it displays `Running on http://localhost:3978`
![image](https://user-images.githubusercontent.com/38049078/181133710-216d5209-46f5-4d87-8558-d76260c7a5ed.png)

**Comment by anjika456** [comment]
I think the steps I was taking incorrectly was running it on my local machine, it is working now I had to download these after I was receiving an error and now it is working in the emulator. Thank you for the help!
[botframework-connector](https://pypi.org/project/botframework-connector/)

[botbuilder-core](https://pypi.org/project/botbuilder-core/)

[botbuilder-schema](https://pypi.org/project/botbuilder-schema/)
