### ISSUE TITLE
Creating resources with ARM template for Python echobot fails

### ISSUE THREAD

**Issue by dbeyda** [microsoft/BotBuilder-Samples#3803]
## Sample information
1. Sample type: \samples\python
2. Sample language: python
3. Sample name: 02.echo-bot / possibly all python samples

## Describe the bug
Following the [deployment docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=multitenant%2Cnewgroup%2Ccsharp#create-resources-with-an-arm-template), when creating resources with ARM template (MultiTenant // new resource group // python // sample echobot) fails, with message:

>```unrecognized template parameter 'appType'. Allowed parameters: appId, appSecret, botId, botSku, groupLocation, groupName, newAppServicePlanLocation, newAppServicePlanName, newAppServicePlanSku, newWebAppName```

The command that triggers the error is:
```
az deployment sub create --template-file "<path>" --location <bot-region> --parameters appType="MultiTenant" appId="<app-id>" appSecret="<password>" botId="<bot-id>" botSku=<tier> newAppServicePlanName="<plan-name>" newWebAppName="<service-name>" groupName="<group-name>" groupLocation="<group-region>" newAppServicePlanLocation="<plan-region>" --name "<deployment-name>"
```

## To Reproduce
1. Copy python/samples/02.echobot to a work directory.
2. `pip install -r requirements.txt`
3. Follow the [Deploy Your Bot to Azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=userassigned%2Cnewgroup%2Ccsharp) docs.
4. In the create resources with ARM template section, run the command relative to new resources // multitenancy (the others might be broken as well, I don't know).
5. Watch error in console.

## Expected behavior
Resources should be created without displaying any error.

## Additional context
Indeed, all Python samples use a 2015 schema, which does not have `appType`, causing the command to fail. I copied over the whole `template-with-new-rg.json` file from Node samples, which uses schema from 2019-04-01, and the command succeded.

**Comment by tracyboehrer** [comment]
This is indeed an incomplete handling of those ARM templates changes across the 4 SDK's.  In the coming days, we will be updating all ARM templates to a new set of templates, and all 4 repos, and the associated doc should match.  Sorry for the confusion.  I'll leave this issue open for tracking until that work is done.
