### ISSUE TITLE
Bot Registration for web channel for Production environment 

### ISSUE THREAD

**Issue by NaveenKumarNN** [microsoft/BotBuilder-Samples#3804]
Hello Team
I have created the Bot using Microsoft Bot framework in C# and I have hosted the Bot in the cloud environment (Pivotal cloud Foundry) not in Azure. I have registered the bot in the link (https://dev.botframework.com/bots/new)  to enable webchat using direct line and I have received the   appid and app password for that. I Understand that registration is free without azure subscription to enable the webchat. I have red the forum link(https://techcommunity.microsoft.com/t5/teams-developer/register-bot-without-azure-process/m-p/1490808) which clearly tells that subscription is not required for bot registration if the bot is hosted in the non-azure environment. Now my Bot is working without any issues. But my question is shall i proceed with same process for production environment. is there any limitation on this? Kindly Advise on this

**Comment by dmvtech** [comment]
Hi @NaveenKumarNN 

If you create a Bot Registration with within a subscription (for example Pay-As-You-Go), you would have the option to switch to a different payment tier, up and over the free. Creating the registration via the portal, you won't have the ability to change. 

![image](https://user-images.githubusercontent.com/43397658/182970461-58821f77-aa80-456d-a328-b7e74dc4e8ca.png)

Other than that, there are other options and settings that you can get to (setting up OAuth config settings, etc.)

**Comment by NaveenKumarNN** [comment]
Thanks for your response.
I m still not clear. I don't have azure subscription ,I want to go with free bot registration()  for the production environment. Actually i am using direct line\webchat  channel for my bot . I am trying to understand whether the application in prod environment will be stable or not ,since we couldn't face any issues in the development environment.

**Comment by NaveenKumarNN** [comment]
> Thanks for your response. I m still not clear. I don't have azure subscription ,I want to go with free bot registration() for the production environment. Actually i am using direct line\webchat channel for my bot . I am trying to understand whether the application in prod environment will be stable or not ,since we couldn't face any issues in the development environment.
