### ISSUE TITLE
WaterFall Dialog Flow works in Emulator but not in WebChat or Teams

### ISSUE THREAD

**Issue by Incedendo** [microsoft/BotBuilder-Samples#3805]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [python]
3. Sample name: 43: complex-dialog

## Describe the bug
I built my bot based on the samples [BotBuilder-Samples/samples/python at main · microsoft/BotBuilder-Samples (github.com)](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python). For waterfall-driven dialog (sample 43 complex-dialog), in Emulator, the bot's waterfall dialog works fine and all dialog flows from start to finish. However, after deploying to Azure Portal and tested in Web chat, the flow of conversation is messed up and bot is not able to follow scripted dialog. Specifically, in a 3-step waterfall dialog, after entering response for question, bot is supposed to move on to step 2 and prompt next question, but it sometimes reprompts the same question, or exit the current dialog to the main dialog, then later the show again the missing step of the previous inner dialog. Behaviors are erratic.

## To Reproduce
1. Publish the sample 43 to Portal Azure with preset environments
2. Open the bot to "Test in Web Chat"

## Expected behavior
Expect bot to follow steps of waterfall dialog from start to finish like it did in Emulator
Step 1: name
Step 2: age
if age >= 25: prompt for 2 companies choices then end dialog
Step 3: Summary and end dialog

## Screenshots
Bot keeps asking for "name" after user already enters name
![image](https://user-images.githubusercontent.com/17934623/182687295-af940a42-9a5e-4d33-925c-b7ef6bccc674.png)

Bot is supposed to register the 2nd company name and end the dialog but it ends the dialog prematurely and saved no companies.
![image](https://user-images.githubusercontent.com/17934623/182687415-a6df0b19-8888-408d-abc7-fb2782de814c.png)

**Comment by ramfattah** [comment]
Hey @Incedendo,

Looks like I'm not able to reproduce this error using fresh python sample [43.complex-dialog](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/43.complex-dialog).

Note: I used ngrok to tunnel localhost to Azure bot Messaging endpoint.

![image](https://user-images.githubusercontent.com/38049078/182708903-2e8b52db-8b5c-4aed-a762-af4e9328e6d4.png)


#

* Have you attempted to use ngrok to look for error traces in the console?
* Are you experiencing this behavior only after deploying the bot to Azure?

**Comment by ramfattah** [comment]
Spoke with @Incedendo offline. 
Looks like this issue is happening only after deployed sample [43.complex-dialog](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/43.complex-dialog) to Azure.

Investigating further...

**Comment by ramfattah** [comment]
@Incedendo I'm attempting to deploy and publish to Azure using a new app service, from scratch. 
I will let you know of any updates. 

Thanks.

**Comment by ramfattah** [comment]
Hi @Incedendo,

Publishing C# and JS works as expected using the latest az cli (2.39.0). 
I cannot seem to publish python bot using the latest or given versions of az cli in the docs.

Using same exact publishing steps [mentioned here](https://github.com/MicrosoftDocs/bot-docs/issues/2228) that worked for C# and JS does not seem to work for python bots. 
>Note:  The resources were created using az cli 2.39.0 with latest ARM templates and parameter files.python app service URL 

after zip deploy:
![image](https://user-images.githubusercontent.com/38049078/185474191-9cab678b-f68b-49c9-af7e-f424a18da72a.png)
![image](https://user-images.githubusercontent.com/38049078/185474265-83e0ec7a-522a-421c-b686-3f9b9c23ce2d.png)

Thank you for your patience @Incedendo, we are looking into this and will let you know of any updates.

**Comment by ramfattah** [comment]
Hi @Incedendo 

I was not able to reproduce this anymore after the latest publishing docs update. 

Could you please try to publish the bot from docs here: 
https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot

**Comment by ramfattah** [comment]
Doc for this issue has been updated
https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot
