### ISSUE TITLE
18.bot-authentication error

### ISSUE THREAD

**Issue by xinyi1989** [microsoft/BotBuilder-Samples#3813]
## Sample information
1. Sample type: [samples]
2. Sample language: [nodejs]
3. Sample name: 18.bot-authentication

## Describe the bug
1. It takes a long time to get the login status after the SSO login is successful

2. After successful login, you can't get the login success status immediately. You need to ask a question to prompt that you haven't logged in. Ask another question to get the login success status directly.

## Expected behavior
After successful login, obtain the status of successful login immediately and prompt the login success information

## Screenshots
<img width="823" alt="image" src="https://user-images.githubusercontent.com/22472112/187112834-57a1faf2-035a-4e0f-9db0-b01231338a58.png">

## Additional context
[transcripts.zip](https://github.com/microsoft/BotBuilder-Samples/files/9441203/transcripts.zip)

**Comment by dmvtech** [comment]
Thank you @xinyi1989 

I am investigating.
