### ISSUE TITLE
Java sample bot deploy meet subscription not match

### ISSUE THREAD

**Issue by woasishen** [microsoft/BotBuilder-Samples#3818]
## [Sample information](https://github.com/microsoft/BotBuilder-Samples/tree/b68d7b0856c90dc57b602654be221a94e316696b/samples/java_springboot/02.echo-bot)
1. Sample type: [samples]
2. Sample language: [spring bot]
3. Sample name: <02.echo-bot>

## Describe the bug
After I excute
`mvn azure-webapp:deploy -Dgroupname="resource-group-name" -Dbotname="name-of-web-app"`

![image](https://user-images.githubusercontent.com/22291967/187825899-3c6afaf6-9507-41e6-9249-0b7813db7522.png)

Notice: az account set --subscription "<subscription>" can't fix it.
I think the subscriptionId should add to the pom.xml and use 
`mvn azure-webapp:deploy -Dgroupname="resource-group-name" -Dbotname="name-of-web-app" -Dsubscription="subscriptionId-of-web-app"`

## To Reproduce
1. create appservice
2. follow doc to excute `mvn azure-webapp:deploy -Dgroupname="<resource-group-name>" -Dbotname="<name-of-web-app>"`

**Comment by tracyboehrer** [comment]
Closing as Java is retired as of Nov 2023
