### ISSUE TITLE
C# Sample 04.Simple-Prompt-Bot is missing a readme

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder-Samples#382]
No readme file.

https://github.com/Microsoft/BotBuilder-Samples/tree/v4/csharp_dotnetcore/04.Simple-Prompt-Bot

**Comment by stevengum** [comment]
Fixed: https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/04.simple-prompt/readme.md
