### ISSUE TITLE
46.teams-auth - Authentication Issue when deploying Teams Auth Bot sample

### ISSUE THREAD

**Issue by marianocalero** [microsoft/BotBuilder-Samples#3823]
[onTurnError] unhandled error: DialogContextError: Error retrieving token: 6043025e3309fc4aa45db05b8aba1d81.

Trying to deploy javascript_nodejs - 46.teams-auth bot, but I'm getting the above error when testing in Web Chat and Teams Chat. 

Using Ngrok and running bot in Visual Studio. 

![image](https://user-images.githubusercontent.com/68557521/189424389-e5c27941-4de3-4771-ae1e-949dbc443761.png)

https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/46.teams-auth - this was the article I followed.

![image](https://user-images.githubusercontent.com/68557521/189424487-0de39363-e15a-4fce-a900-fb3a844a02ec.png)

![image](https://user-images.githubusercontent.com/68557521/189424529-1d89cb9c-5eca-432d-b5b7-fafc2225e691.png)

**Comment by anishprasad01** [comment]
Hi @marianocalero,

The Teams Auth sample makes use of AAD Authentication to authorize users. While the steps in the readme show you how to deploy the bot and configure the manifest, they do not specify how to set-up auth. You must also [set up user auth](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots) for your bot in Azure after deploying it.

Follow the steps in the above article to set up auth before using it. Begin immediately after the section on creating an app registration (as you have deployed a bot, you already have one and can edit the existing registration) and end at updating the Teams manifest. You should not need to make code changes if using the Teams auth sample.

Once Auth is configured, please test the bot in the Teams app to verify functionality.

**Comment by marianocalero** [comment]
Hi @anishprasad01 ! Thank you for that, I've gone through most of the steps in the linked documentation up until https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#add-the-code-to-request-and-receive-a-bot-token

I'm not sure how to add the code for the token - I am only using the 46.teams-auth sample. Is there anything I need to modify in the sample code? This is the first time I'm doing this, any help/clarification you can provide would help a lot - thank you!

**Comment by anishprasad01** [comment]
You should not need to make any modifications to the sample project other than updating `.env` with the required values. The sample code should already be ready for use. As long as your Azure config is correct, the Teams App Manifest is correct and installed, the bot with up-to-date `.env` is running and accessible, everything should work.

Note that the settings must match up everywhere. Inconsistencies such as a missed character in the AppId in the manifest would be enough to cause a problem.

**Comment by marianocalero** [comment]
Hi @anishprasad01 - thank you! I went through and realized I did not add the connectionName in the .env. Once I added that, it began to work in Azure Web Chat, however I'm not getting anything in Teams:

![image](https://user-images.githubusercontent.com/68557521/191083131-7f40e4ed-f853-4dbf-972b-c153f8dc7146.png)


![image](https://user-images.githubusercontent.com/68557521/191083206-4953ec39-7c96-483a-8d30-ba3708608d2a.png)


Is there something I might be missing? 

![image](https://user-images.githubusercontent.com/68557521/191083307-55b5448e-9ca2-4c65-b6fc-5731fe903919.png)

**Comment by anishprasad01** [comment]
It could be a number of things.

- Something may be wrong with your App Manifest.
- Your App Registration scopes might be wrong.

Have you tried [debugging with Ngrok](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) to run locally but test in Teams? You run the bot locally, start up Ngrok, and set the Ngrok URL as the messaging endpoint in Azure, in the form `https://[ngrok-url]/api/messages`. You should then be able to see any errors.

**Comment by marianocalero** [comment]
Hey @anishprasad01 - I have only been using ngrok, but forgot to check the response there. It looks like I'm getting a 501 Not Implemented when sending a message via Teams: 

HTTP/1.1 501 Not Implemented
Server: restify
Date: Mon, 19 Sep 2022 21:25:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0

**Comment by marianocalero** [comment]
I'm also getting this shortly after: 

HTTP/1.1 405 Method Not Allowed
Server: restify
Allow: POST
Content-Type: application/json
Content-Length: 62
Date: Mon, 19 Sep 2022 21:30:05 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"code":"MethodNotAllowed","message":"OPTIONS is not allowed"}

**Comment by anishprasad01** [comment]
Appears to have been a permissions issue with the requested scopes preventing sign-in. Choosing a smaller scope solved the issue.
