### ISSUE TITLE
 Can we send proactive message with "Important" tag for Teams?

### ISSUE THREAD

**Issue by Raviiraju** [microsoft/BotBuilder-Samples#3831]
Can we send proactive message with "Important" tag for Teams?

![image](https://user-images.githubusercontent.com/114903590/193518746-72d5d40e-af90-4d70-aafc-13be8afdfc23.png)

**Comment by ramfattah** [comment]
Hi @Raviiraju, we are investigating.

**Comment by ramfattah** [comment]
Discussing internally with the Microsoft "Teams" team. We will report back once we have updates. 
Thanks for your patience @Raviiraju
