### ISSUE TITLE
QnA Maker (Java): It seems the page to get  QnAKnowledgebaseId, QnAEndpointKey and QnAEndpointHostName is not updated for the new QnA Maker Azure Service

### ISSUE THREAD

**Issue by mrodfuentes** [microsoft/BotBuilder-Samples#3832]
## Sample information
1. Sample type: sample
2. Sample language: java
3. Sample name: QnA Maker

## Describe the bug
The section regarding the way to get the values of QnAKnowledgebaseId, QnAEndpointKey and QnAEndpointHostName (application.properties) are not in accordance to the language studio page from Azure. It seems that it is not updated to the new way to implement a QnA Maker.
This is the section:

https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/11.qnamaker#create-a-qnamaker-application-to-enable-qna-knowledge-bases

## To Reproduce
1. Go to 'https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/11.qnamaker#create-a-qnamaker-application-to-enable-qna-knowledge-bases'
2. Click on 'this section'
3. You can see that explanation is not according to the new page of language studio

## Expected behavior
new procedure to get the values of the application.properties (QnAKnowledgebaseId, QnAEndpointKey and QnAEndpointHostName )

## Screenshots
You can see that the following picture refers to "settings" sheet...
![image](https://user-images.githubusercontent.com/5442722/193579711-97bc9ae0-924d-480b-9fca-67472d9a690c.png)
but in the current page the option the "settings" sheet has not the information described before:
![image](https://user-images.githubusercontent.com/5442722/193581064-255fcb86-03ae-4836-b518-877b2ce3c983.png)

**Comment by anishprasad01** [comment]
Hi @mrodfuentes,

Thanks for the report. We'll take this issue under consideration as a feature request. We do not have an ETA at this time for when this update might be available.
