### ISSUE TITLE
Samples (csharp_dotnetcore/49.qnamaker-all-features): 'ComponentRegistration' is obsolete: 'Use BotComponent for new components

### ISSUE THREAD

**Issue by sukeerthimulakala** [microsoft/BotBuilder-Samples#3834]
Hi Team,

As per new code `ComponentRegistration.Add(new DialogsComponentRegistration());` has replaced with  new `DialogsBotComponent().ConfigureServices(services, Configuration);`.  When I replaced am getting an error on clicking on Promtp of Bot response. exception message **'turn' does not match memory scopes:[] (Parameter 'key')**.
Could you please help me to resolve this issue. If I use `ComponentRegistration.Add(new DialogsComponentRegistration()` perfectly working fine but as its suggested not to use ComponentRegistration and use BotComponent for new components.

**Comment by tracyboehrer** [comment]
Hi @sukeerthimulakala You are fine to use the old way for now.  There are no immediate plans for use to drop it, and no harm in doing so now.  I'll look into this though.

**Comment by sukeerthimulakala** [comment]
@tracyboehrer thank you so much

**Comment by sparkcontext** [comment]
Hi Team

i got similar issue using sample of Samples (csharp_dotnetcore/48.customQABot-all-features): 
when i click multiturn options using BF emulator,
It throws exception of value:"'turn' does not match memory scopes:[] (Parameter 'key')"
when i click the second time, it work fine again.

Please advice if further information is required/move to a new issue. thank you so much

**Comment by johnataylor** [comment]
We have archived sample 49 so this doesn't directly apply. But, as you say, you would see a similar issue with 48.

@tracyboehrer has confirmed that we are not changing anything here and the "old way" will continue to work. The memory scopes can probably be added to the new way but this doesn't really change anything very significant.

Closing this issue. If you there is a problem, please reopen and we can see if we can work out how avoid this altogether.
