### ISSUE TITLE
Composer C# AskingQuestionsSample: sign-in card flow appears to have a variable mismatch

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotBuilder-Samples#3835]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: AskingQuestionsSample (Composer)

## Describe the bug
The OAuth logic action saves the token to `turn.token`. However, the next action (HTTP request) tries to get the token from `user.token.token`.

## To Reproduce
1. Open the C# AskingQuestionsSample bot in Composer.
1. Open the **oauthinput** dialog's **Dialog started** trigger.
1. Review the **OAuth login** and **Send an HTTP request** actions.
1. Error: Not that they are not referencing the same variable.
    - Error: The first action is also referencing the user scope variable, which never gets set.

## Expected behavior
The sample shouldn't contain buggy code.

## Additional context
See also, https://github.com/MicrosoftDocs/composer-docs/issues/203

**Comment by anishprasad01** [comment]
@JonathanFingold,

Opened a [PR](https://github.com/microsoft/BotBuilder-Samples/pull/3836) which fixes the mismatch.
