### ISSUE TITLE
POST 400 directline/conversations/<conversationId>/activities on wsl

### ISSUE THREAD

**Issue by roeibh** [microsoft/BotBuilder-Samples#3841]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [typescript]
3. Sample name: echo-bot

## Describe the bug
executed the instructions in https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/02.echo-bot.
running windows 11 and Ubuntu in wsl
output of `npm start`:
```
> echobot@1.0.0 start
> tsc --build && node ./lib/index.js

(node:19892) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

restify listening to http://[::]:3978

Get Bot Framework Emulator: https://aka.ms/botframework-emulator

To talk to your bot, open the emulator select "Open Bot"
```
* Launched Bot Framework Emulator
* Went to File -> Open Bot
* Entered the Bot URL: http://localhost:3978/api/messages

Got the following output:
```
Connectivity Status: Connected
Suggested Actions Container: Is empty

Type your message

[22:41:02]Connecting to bot on http://localhost:3978/api/messages
[22:41:02]Emulator listening on http://[::]:57433
[22:41:02]ngrok configured but not running
[22:41:02]-> conversationUpdate
[22:41:02]POST400
directline/conversations/<conversationId>/activities
```

tried the following API call in my REST client:
```
curl --request POST \
  --url http://localhost:3978/api/messages \
  --header 'Content-Type: application/json' \
  --data '{
  "type": "conversationUpdate",
  "membersAdded": [
    {
      "id": "b9032ff0-5f11-11ed-a78c-9dfe41534b23",
      "name": "Bot"
    },
    {
      "id": "eb981899-b4c6-4086-96ad-9139931697ff",
      "name": "User"
    }
  ],
  "membersRemoved": [],
  "channelId": "emulator",
  "conversation": {
    "id": "b903a520-5f11-11ed-9175-b106cd91b2cf|livechat"
  },
  "id": "b909e6b0-5f11-11ed-9175-b106cd91b2cf",
  "localTimestamp": "2022-11-07T22:02:04-05:00",
  "recipient": {
    "id": "b9032ff0-5f11-11ed-a78c-9dfe41534b23",
    "name": "Bot",
    "role": "bot"
  },
  "timestamp": "2022-11-08T03:02:04.187Z",
  "from": {
    "id": "eb981899-b4c6-4086-96ad-9139931697ff",
    "name": "User",
    "role": "user"
  },
  "locale": "",
  "serviceUrl": "http://localhost:57433"
}'
```
and after 40 seconds or so I got
```
"request to http://localhost:57433/v3/conversations/b903a520-5f11-11ed-9175-b106cd91b2cf%7Clivechat/activities/b909e6b0-5f11-11ed-9175-b106cd91b2cf failed, reason: connect ECONNREFUSED 127.0.0.1:57433"
```
So it seems like the server eventually receives it and tries to communicate with the emulator

## To Reproduce
1. Go to https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/02.echo-bot
2. follow the instructions (using wsl)
3. try to test using bot emulator

## Expected behavior
it should work as it works when I create the bot in windows

## Screenshots
![image](https://user-images.githubusercontent.com/8393044/200471487-f16cd7b4-d773-4e0b-b28c-ebcbae776317.png)

**Comment by anishprasad01** [comment]
Hi @roeibh,

This is actually the behavior we would expect to see in this instance. 

Remember that WSL is in essence a stripped-down virtual machine, which means that it has its own network address space. This means that `localhost` for WSL and `localhost` for Windows are not that same thing. When you try to connect to the bot from Emulator running on Windows or from a REST client, it will fail since the bot isn't actually running on Windows, and therefore isn't actually running on the `localhost` these applications can see.

In order to communicate with a bot running in WSL from Windows, you'll need to use some kind of tunneling tool (such as [Ngrok](https://ngrok.com/)) to allow requests to reach WSL from Windows, Azure, or any other external source.
