### ISSUE TITLE
can i publish a bot app without azure serivce

### ISSUE THREAD

**Issue by 86driver** [microsoft/BotBuilder-Samples#3842]
i want build bot app without azure service
1. i create a bot by Developer Portal
2. set the endpoint in Developer Portal
3. i fount the bot has registered in azure 

can i use the bot in teams app, or i must create a bot in azure bot

in the [doc](https://learn.microsoft.com/zh-cn/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned) i found must use azure bot service

**Comment by dmvtech** [comment]
The bot code doesn't need to run in Azure. If you want to use Teams, you can use the Bot registration created in Azure (even if the code runs elsewhere) to configure Teams channel. 

If you don't want to use the Azure bot registration or channels, you can use an [adapter from the bot builder community](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries), or you can build your own.
