### ISSUE TITLE
C# Teams-auth / about AAD SSO

### ISSUE THREAD

**Issue by dhddldid** [microsoft/BotBuilder-Samples#3849]
## Sample information
1. [46.Teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth)

## Describe the bug
1. If clicked accept in the Teams desktop app, the accept page does not open
2. If the accept page open in Teams web, it automatically accepted it without any procedure

## To Reproduce

Describe the bug about 1.
1. Go to 'Teames desktop'
2. Click on 'Teams-auth app'

Describe the bug about 2.
1. Go to 'Teames web'
2. Click on 'Teams-auth app'
3. (but at the very first time i try to get a authorization i needed to click the authorization button)

**Comment by anishprasad01** [comment]
Hi @dhddldid,

Could you please provide:
- More information regarding each scenario.
- More details regarding your deployment and testing environment.

**Comment by dhddldid** [comment]
# The detailed scenario is as follows
1. I followed the 46.teams-auth code  
2. I [followed the document]((https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso)) to register azure bot and to configure sso.
3. And in the web version of Teams, it worked as follows.
   ![teams-web_01](https://user-images.githubusercontent.com/24456683/203453519-da8f2b1c-f46b-4e46-8289-0e5dbf83e4b5.png)
   ![teams-web_02](https://user-images.githubusercontent.com/24456683/203453516-9c74b380-66da-428b-8653-fb844d89073a.png)
The problem described in "Describe the bug about2" occurs here.  
At first, there was a button to agree, but now it automatically agrees.

4. In addition, the following phenomenon occurs in Teasm's desktop app
   (To return to the scenario for consent, we modified the permission of Microsoft Graph.)
![teams-desktop_01](https://user-images.githubusercontent.com/24456683/203454952-de11dfc9-d695-44e6-ba18-dba749fcfb96.png)
   Press the displayed "Continue" button
   The following window did not appear
   This is about "Describe the bug about 1."
   ![teams-desktop_02](https://user-images.githubusercontent.com/24456683/203454948-52c9bec2-d453-4e56-ac25-8f8557684041.png)

**Comment by anishprasad01** [comment]
Thank you. I will attempt to reproduce this issue.

**Comment by anishprasad01** [comment]
@dhddldid

At the moment, I am unable to reproduce Bug #1. With the `User.Read` scope, I am able to see the consent window when the bot is running in Teams.

As for Bub #2, I believe that this may actually be intended behavior, and not a bug. After you log in once, you remain logged in until the token expires unless you explicitly log out.

**Comment by dhddldid** [comment]
@anishprasad01 Thank you for thinking about the bug and answering.

I will share my opinion on the answer.

In Bug 1, can you try to press permission after turning on the Teams desktop app without opening the web page?
If you follow the above scenario and the page opens the same way, I'll closed bug1.


In Bug 2, if you want to reopen pages that allow permissions, you can:

When you modify the permissions in AAD as shown in the figure, you will have to accept the permissions again in Teams, as you saw in the phrase "You are editing permission(s) to your application, users will have to have them already done if they appear on the Accept Permissions page as if they were logged in for the first time. At this time, please check if the authority is accepted automatically.
![bug2](https://user-images.githubusercontent.com/24456683/204516574-64136ebb-10e0-4c77-a0ec-c6d79c2a312f.png)


I don't think it has anything to do with login and token.

Could you give it another try?

**Comment by anishprasad01** [comment]
> can you try to press permission after turning on the Teams desktop app without opening the web page?

Do you mean without using the Teams Web App? I have attempted only in the desktop app, as per your report.

> permissions in AAD as shown in the figure, you will have to accept the permissions again in Teams

Correct, but your sign-in will be retained, so you will not be asked to log in again once you accept the permissions.

**Comment by dhddldid** [comment]
@anishprasad01 
 
1. You're right, I'm referring to running only on the desktop app.

2. Thanks for trying.



Thanks for checking the issues. We will see you often in the future as we develop the Teams app. 

Am I asking for closed? This is my first time doing a git issue.

**Comment by anishprasad01** [comment]
Thanks for clarifying. Feel free to open an issue in the appropriate repository as needed, and good luck with your project.
