### ISSUE TITLE
The OAuth prompt doesn't go away after the permission is given to the bot.

### ISSUE THREAD

**Issue by thashu0424** [microsoft/BotBuilder-Samples#3858]
## Sample information
1. Sample type: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/18.bot-authentication
2. Sample language: dotnetcore 
3. Sample name: 18.bot-authentication

## Describe the bug
The OAuth prompt doesn't go away after the permission is given to the bot.

## To Reproduce
1. Give the permissions when the prompt comes for the first time 
2. Then after login go to another tab and comeback
3. The prompt will be showed again

## Expected behavior
The prompt should be showed only once

## Screenshots
<img width="627" alt="Screenshot 2022-12-23 175120" src="https://user-images.githubusercontent.com/52147960/209341762-cf1d01f7-0040-4d86-b341-9899898da710.png">

## Additional context
The OAuth prompt doesn't go away after the permission is given to the bot. This prompt keeps showing even after the user has given the permissions. 
And when clicked on continue this error comes up .
![fec2a186-3f59-43c2-bcd4-ba2aa1b4a95f](https://user-images.githubusercontent.com/52147960/209341982-28a42d10-fbed-45fd-82a8-f9fa576c2c68.png)

**Comment by thashu0424** [comment]
Any updated on this? @johnataylor @dmvtech

**Comment by dmvtech** [comment]
Hi @thashu0424 Apologies for the delay. Still investigating at this point.

**Comment by dmvtech** [comment]
Closing in lieu of: https://github.com/microsoft/botbuilder-dotnet/issues/6574
