### ISSUE TITLE
SSO login doesnt work in iOS and macOS 

### ISSUE THREAD

**Issue by thashu0424** [microsoft/BotBuilder-Samples#3859]
Any reason why SSO login doesn't work in iOS and macOS ? When clicked on allow a blank black screen appears and goes away and the authentication doesn't happen.

**Comment by anishprasad01** [comment]
Hi @thashu0424,

SSO authentication in bots should work on these platforms through our various supported channels. Couple you please provide more information about what you have so far?

Helpful details:
- Which sample are you using?
- Which programming language?
- Which channel are you using? (Web Chat, Teams, Direct Line, etc.)
- Have you followed documentation and configured SSO in the Azure Portal?
    - Which documents did you follow?
- Did you update the configurations in your bot and the channel?
- Do you have the appropriate permissions in your tenant?

**Comment by thashu0424** [comment]
Sample type: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/18.bot-authentication
Sample language: dotnetcore
Channel - Teams
Did you update the configurations in your bot and the channel? - Yes as per the document
Do you have the appropriate permissions in your tenant? Yes

**Comment by anishprasad01** [comment]
Teams works a little differently, and Sample 18 does not work in the Teams channel. To see a sample of bot SSO in Teams, please refer to the [Teams Bot Auth Sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/csharp) from the samples repo provided by the Teams group.

**Comment by anishprasad01** [comment]
Teams SSO sample uses the Microsoft Graph API to authenticate the user. The standard bot authentication sample does not.
