### ISSUE TITLE
Example no 16. - Typescript version

### ISSUE THREAD

**Issue by misaizdaleka** [microsoft/BotBuilder-Samples#3863]
## Sample information
1. Sample type: typescript_nodejs/16.proactive-messages
2. Sample language: TypeScript
3. Sample name: Proactive messages

## Describe the bug
Project won't build

## To Reproduce
1. Run npm install
2. See error

Screenshot: 

![image](https://user-images.githubusercontent.com/2690948/213668630-b5034b34-10f6-47bd-8808-caeaf7dbf2ea.png)

**Comment by ramfattah** [comment]
Thanks @misaizdaleka, investigating further.

**Comment by misaizdaleka** [comment]
I was able to get it running by removing @types/restify as a dependency.

**Comment by ramfattah** [comment]
Thanks for sharing. Verified removing @types/restify in package.json solved this issue from my end as well.

Closing this for now. @misaizdaleka. please re-open if needed.
