### ISSUE TITLE
Suggested actions are not working in teams when I'm using bot composer to create my bot

### ISSUE THREAD

**Issue by Shobraj** [microsoft/BotBuilder-Samples#3868]
Suggested Actions feature is working fine in teams application when I use bot framework SDK. But when I use Send a response in Bot Composer and add the Suggested Actions it doesn't work.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/36963737/222340621-27b3b67e-3261-4225-8d25-de51107c1798.png">

**Comment by dmvtech** [comment]
Suggested actions are not supported by the Teams channel. Please see more information here:
https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#card-action-support-by-channel

**Comment by Shobraj** [comment]
Suggested action are supported in teams if you are using bot framework SDK. But when we use composer its not working. The link is redirecting me to a page where it is mentioned that suggested actions are not supported teams application which is not true.

I have tried this solution and deployed the bot and tried in teams application I'm able to get the suggested actions.
[https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/08.suggested-actions](url)

**Comment by dmvtech** [comment]
Hi @Shobraj 

I just tested the SDK sample and Suggested Actions **do not** show for me:
![image](https://user-images.githubusercontent.com/43397658/222796698-52256ba0-f750-4352-a5fa-fe6bb82fe7e4.png)


- What version of Teams are you using? 
- What OS?

**Comment by Shobraj** [comment]
@dmvtech sorry for sending you wrong sample link.

please find a sample solution which is part of **Microsoft-Teams-Samples**
https://github.com/officedev/microsoft-teams-samples/tree/main/samples/bot-suggested-actions/csharp

I have run this solution and it works fine in teams please find the screenshot for your reference.

**My Microsoft Teams Version 1.6.00.1381 (32-bit). It was last updated on 2/7/2023.
I'm using dotnet 6.0 and using window OS**

<img width="702" alt="image" src="https://user-images.githubusercontent.com/36963737/223035284-e4d560de-1201-4b0e-8f29-b738d7ab1717.png">

**Comment by dmvtech** [comment]
Thanks @Shobraj 

Investigating.

**Comment by ShobharajaNagarro** [comment]
@dmvtech Any update?

**Comment by dmvtech** [comment]
HI @ShobharajaNagarro 

Apologies for the delay. Please see the issue here:
https://github.com/microsoft/botbuilder-dotnet/issues/6086

Looks like work is being done to fix this, just nothing yet. Closing this so we can continue to track there.
