### ISSUE TITLE
Suggested actions are not supported by the Teams channel. Please see more information here:

### ISSUE THREAD

**Issue by Shobraj** [microsoft/BotBuilder-Samples#3870]
Suggested actions are not supported by the Teams channel. Please see more information here:
https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#card-action-support-by-channel

_Originally posted by @dmvtech in https://github.com/microsoft/BotBuilder-Samples/issues/3868#issuecomment-1452258840_

**Comment by dmvtech** [comment]
Closing as duplicate of linked issue.
