### ISSUE TITLE
How to enable microphone option for bot in teams

### ISSUE THREAD

**Issue by ShobharajaNagarro** [microsoft/BotBuilder-Samples#3873]
In teams you can send voice messages to user. The microphone option is not available if i want to send voice message to a bot.

Microphone button is enabled in personal chat
![WhatsApp Image 2023-03-24 at 14 37 58](https://user-images.githubusercontent.com/127189165/227474947-1a98db45-6741-418b-8298-fa302b678d62.jpg)

Microphone option is not available for bot
![WhatsApp Image 2023-03-24 at 14 37 56](https://user-images.githubusercontent.com/127189165/227558172-9268cba6-b25f-40a3-ba6b-9cfb762d2fdf.jpg)

**Comment by tracyboehrer** [comment]
We recommend contacting Teams via https://github.com/OfficeDev/Microsoft-Teams-Samples or their developer program: https://developer.microsoft.com/en-us/microsoft-teams
