### ISSUE TITLE
Echo bot sample returns error when using LINE channel

### ISSUE THREAD

**Issue by risakur** [microsoft/BotBuilder-Samples#3879]
## Sample information
1. Sample type: Java SDK Echo Bot Sample 

https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/02.echo-bot

2. Sample language: Java
3. Channel : LINE Channel (other than LINE channel, Web Chat and Teams channels are enabled and the issue only occurs when using LINE channel

## Describe the bug
When using Java SDK Echo Bot Sample, the bot sends payload like below 

"conversation":{**_"properties":{},_**"isGroup":false,"id":"xxxxxxxxxxxxxxxxxxxxxxxx"}

And having this "properties" is causing LINE channel to return 400 error. 
(Same payload is sent to Web Chat as well but only LINE channel returned errors and responses from Web Chat channel were fine)

## To Reproduce
1. Go to https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/02.echo-bot and enable LINE Channel.
※Make sure  "properties":{} is included

## Expected behavior
Return echoed response, not an error even when I am using LINE Channel.

**Comment by risakur** [comment]
Hello @dmvtech ,

Just for your information, the issue does not get reproduced now since Bot Service rolled out a fix but what I want to focus is that unnecessary "properties" is included in JSON, and it was causing 400 error.

**Comment by dmvtech** [comment]
Hi @risakur 

Most likely it is needed in other channel(s) other than Line.
