### ISSUE TITLE
Anti-Virus notification

### ISSUE THREAD

**Issue by forX01** [microsoft/BotBuilder-Samples#3900]
I try to download the zip of BotBuilder-Samples (main branch).
My antivirus (bitdefender) say that there is a suspect ressource with a code Amsi.Edge.22.CFF02E58
I'm gonna check with them but its the first time a code in your git that cause this.

**Comment by sw-joelmut** [comment]
HI @forX01,
 
Following the provided information, we couldn't reproduce this issue.
We tried using Bitdefender (free plan) as well as Malwarebytes (free trial), running multiple scans over the _.zip_ file and the extracted content, but none of them detected anything suspicious.
![imagen](https://github.com/microsoft/BotBuilder-Samples/assets/62260472/db5db349-db3e-4789-99a0-767e35b2c0e9)
 
Let us know if there is any extra information that could be important to reproduce this issue.
