### ISSUE TITLE
How can we integrate the user-assigned managed identity bot in Teams?

### ISSUE THREAD

**Issue by nithin-viswanathan** [microsoft/BotBuilder-Samples#3904]
🚨 The issue tracker is not for questions 🚨

I am trying to hook my user-assigned bot into teams. But User authentication is not happening. It is showing "Login was not successful; please try again."

I am using the below URL for reference. [Code](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore/BotConversationSsoQuickstart)

**Comment by abhi-shek-09** [comment]
There is a chance that you might have to update your app service on Azure
Check out: https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=multitenant%2Caadv2%2Cjava#to-update-your-app-service

**Comment by nithin-viswanathan** [comment]
> There is a chance that you might have to update your app service on Azure Check out: https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=multitenant%2Caadv2%2Cjava#to-update-your-app-service

Already done. Can we have Teams and Managed Identity in different Tenant?
