### ISSUE TITLE
In the new version of Teams, the "platform" field is no longer available

### ISSUE THREAD

**Issue by jeffzhangAI** [microsoft/BotBuilder-Samples#3912]
## Describe the bug
When using the new Teams to send messages to the bot, the "platform" field cannot be retrieved.

## To Reproduce
for (Entity entity : turnContext.getActivity().getEntities()) {
            if (entity.getType().equals("clientInfo")) {
                teamsCommand.setPlatform(entity.getProperties().get("platform").asText());
                break;
            }
        }

## Expected behavior
In the older version, it was possible to retrieve the "platform" field successfully. However, in the new version, the absence of this field will throw a NullPointerException.

## Screenshots
new Teams properties: {"type":"clientInfo","country":"CN","timezone":"Asia/Shanghai","locale":"zh-CN"}
old Teams properties: {"type":"clientInfo","country":"US","timezone":"Asia/Shanghai","locale":"en-US","platform":"Windows"}

**Comment by stevkan** [comment]
@jeffzhangAI - The BotFramework team is not responsible for development of the Teams app. As such, we are unable to help you in this. I would suggest you post this issue in the Microsoft Q&A docs [site](https://learn.microsoft.com/en-us/answers/questions/ask/). There is plenty of traffic there so you should be able to get a response. Be sure to add the 'Microsoft Teams" and Microsoft Teams Development" tags so the appropriate people see it.
