### ISSUE TITLE
I want to maintain same code base for both botframework in web chat & teams chat.

### ISSUE THREAD

**Issue by samthrusha123** [microsoft/BotBuilder-Samples#3915]
I want to maintain same code base for both bot framework in web chat & teams chat. Teams I need SSO authentication as well. I created sample app but it is not triggering on member added async method in teams bot. OnMembersAddedAsync.

**Comment by ramfattah** [comment]
Hi @samthrusha123, 

Could you please explain what you mean by:
> maintain same code base for both bot framework in web chat & teams chat.

Are you referring to having same programming language?


Could you please provide detailed information of your issue along with code if possible?

**Comment by samthrusha123** [comment]
We can use same code base for both. Thanks for the reply
