### ISSUE TITLE
MS Teams Bot Login Issue: Successful Authentication but 'Unable to reach app' Error

### ISSUE THREAD

**Issue by kajasherif** [microsoft/BotBuilder-Samples#3919]
**Details:**
I'm working on a Microsoft Teams Bot and encountering an issue. Even though the login is successful, I keep seeing the error message "Unable to reach app. Please try again."

When I use Node.js with the Microsoft Bot Framework to display the OAuthPrompt, the Authentication Sign In is correctly displayed. The login process does succeed and returns the correct token. However, an error message is displayed on the Login card itself, stating "Unable to reach app. Please try again."

**Configuration Steps Taken:**

1. I set up the App Registration.
2. In the Azure AD's Manage section, I configured the following:
- Authentication
- Certificates & secrets
- API permissions
3. I also configured the Azure bot, particularly the OAuth Connection Settings. Testing the connection was successful and returned a token.
4. I then created an app in the Microsoft Teams App using the Developer Portal. I added the basic configuration, app features (bot), single sign-in, and domain section.

**Issue:**
After publishing and testing, the sign-in bot appears as expected. However, when I click on it, I encounter the "Unable to reach app" error. This issue is exclusive to the Teams app. When testing with the bot emulator and Azure bot (test in web chat), everything works correctly. Additionally, when I tried the Teams app in a browser and inspected the network tab, it threw a 502 bad gateway error.

![image](https://github.com/microsoft/BotBuilder-Samples/assets/101790522/fe55db84-816c-4fc4-878f-363f0e0edc69)
![image](https://github.com/microsoft/BotBuilder-Samples/assets/101790522/bf580325-3314-43b1-a057-1892d28b7e5d)

Has anyone encountered a similar issue or can provide insights into resolving this? Any guidance would be greatly appreciated.

**Comment by ramfattah** [comment]
Hi @kajasherif, thanks for reporting this issue.

Since the Authentication works and the issue is exclusive to Teams channel, could you please open an issue in `OfficeDev/Microsoft-Teams-Samples` repository for a more targeted resolution? 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples

Please make sure to additionally share your Teams app manifest with them as well.
