### ISSUE TITLE
Unable to call bot service when we've enabled NGNIX & Fortigate for appservice in azure portal.

### ISSUE THREAD

**Issue by samthrusha123** [microsoft/BotBuilder-Samples#3930]
All the bot services I created in azure portal  are working fine until we add **ngnix & fortigate** to appservices. After that it's not even responding.

Getting the below error when tries in web chat

`{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  }
}`

can you please specify what the issue is?

**Comment by stevkan** [comment]
@samthrusha123 - I am unfamiliar with Fortigate outside of the quick search I just performed on Bing. As it appears to provide a firewall solution, my initial guess is the firewall has not been configured correctly to allow communication with the bot from an external source. I would suggest looking closer at the docs for any possible errors in setup.

That being said, if the bot was working until you added the two tools to the app service, then this would seem to be an issue for the App Services team. If you believe the Fortigate firewall has been configured correctly and Web Chat still cannot connect to the bot, then I would further suggest you open a ticket in the app service for Azure support.
