### ISSUE TITLE
bot is not responding.

### ISSUE THREAD

**Issue by ajeetchoudhary** [microsoft/BotBuilder-Samples#3934]
I have deployed a bot on azure using this example.
https://github.com/Microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/24.bot-authentication-msgraph 

and to deploy the bot service, AD app, App service and their relevent configuration, I followed this https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp

but after deploying my bot is not responding. i am sending Hi but not getting response . here is screen shot of channels page
![image](https://github.com/microsoft/BotBuilder-Samples/assets/5568257/80964eae-f6ba-4131-806f-4d5eff4395f2)

![image](https://github.com/microsoft/BotBuilder-Samples/assets/5568257/13d5c50f-4963-4693-a683-6b51aced17b4)

**Comment by dmvtech** [comment]
@ajeetchoudhary 

- The bot works successfully when ran locally?
- Does it work locally when using the appid, apppassword and (oauth) connectionName?
- What language is the bot written in?
- What version of the SDK?
