### ISSUE TITLE
Sideloading Disabled in Teams Toolkit

### ISSUE THREAD

**Issue by BoostN** [microsoft/BotBuilder-Samples#3936]
We have a teams tenant for our company that I was just my account for (I'm the company owner, admin) and I was facing this issue.. the suggestions then said get a E5 Developer Sandbox.. went through that and I still have this issue. The feature to "upload apps" within teams is there, and the custom teams policy is ok as well (enabled to allow uploads). Any ideas here? Using the latest version of Teams Toolkit and VSCODE on Windows 11. 

![sideloadfailed](https://github.com/microsoft/BotBuilder-Samples/assets/6150217/3a618429-9d70-456a-9b3f-12bf1d72801b)

**Comment by dmvtech** [comment]
Please open this issue in the Teams repository:
https://github.com/OfficeDev/Microsoft-Teams-Samples
