### ISSUE TITLE
How to get conversation paged members's email?

### ISSUE THREAD

**Issue by KaratLee** [microsoft/BotBuilder-Samples#3946]
According to the documentation, Get conversation paged members: will not return email

But the actual call found that email will be returned. Will there be a day when this interface does not return email?

https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversation-paged-members

<img width="1632" alt="image" src="https://github.com/microsoft/BotBuilder-Samples/assets/37133480/40b862c4-cb59-44f2-a9a4-9735927506c8">

This is the result I get via Post main request：
<img width="1021" alt="image" src="https://github.com/microsoft/BotBuilder-Samples/assets/37133480/b61fd1a4-9fef-43ff-a6bf-efdfc3f50716">

I also saw that other users are also using email in this interface:
https://techcommunity.microsoft.com/t5/teams-developer/teams-notification-bot-teamsinfo-getpagedmembers-is-sometimes/m-p/3044679

**Comment by tracyboehrer** [comment]
@KaratLee Azure Bot Service doesn't contain that information.  However, reach out to the Teams group on their Samples repo or Teams AI SDK repo for specifics on Teams capabilities.
