### ISSUE TITLE
Update dotnet samples to target .Net 8

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/BotBuilder-Samples#3948]
## Summary

> Note: We should begin working on this issue once https://github.com/microsoft/botbuilder-dotnet/issues/6741 is complete and we can reference builds that target NET8. 

As part of this issue, we will update the dotnet samples to target NET 8.

We should also update the Readmes to require NET 8.

We will divide the PRs following these categories:

- [x] Essential bots
- [x] Advanced bots
- [x] Authentication bots
- [x] Skills bots
- [x] QA bots

**Comment by sw-joelmut** [comment]
Closed as completed
