### ISSUE TITLE
Potential Vulnerability in one of the dependencies 

### ISSUE THREAD

**Issue by ovishesh** [Microsoft/BotBuilder-Samples#395]
Working with the nodejs Console Echobot sample. I committed `package-locked.json` file into one of my own repos and then GitHub notified me of a potential vulnerability. Adding the screenshots here, as a heads-up and in case anything needs to be updated.

Package - https://github.com/Microsoft/BotBuilder-Samples/blob/v4/javascript_nodejs/01.console-echobot/package-lock.json#L279

![image](https://user-images.githubusercontent.com/3990367/45601433-d51eea80-ba60-11e8-8f53-622daacbdec4.png)

![image](https://user-images.githubusercontent.com/3990367/45601438-e2d47000-ba60-11e8-968f-a8cd1736400c.png)

**Comment by sgellock** [comment]
the above PR addresses the issue.
