### ISSUE TITLE
Error message showed in sign in oauth card

### ISSUE THREAD

**Issue by Aiswarya1794** [microsoft/BotBuilder-Samples#3976]
Hi team,

We are using

return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), null, cancellationToken); method to use sign in feature for user authentication.

In Waterfall dialog, we start the oauth prompt, in next step validating the token response and send the success message and call the next async method to go to the next dialog to fetch the details. But by the time it fetches the data, error message shows up in the sign in card.

How we can resolve the error message which we get in adaptive card because of the bot delay in fetching the data.

![image](https://github.com/microsoft/BotBuilder-Samples/assets/109646037/ac1a9eed-9d18-47fb-a41c-8fc49eafed93)

**Comment by Amrit10737726** [comment]
could you provide more details. Still Are you getting the same issue? in which sample you are getting the issue.
Created SignInCard Under resources in AdaptiveCardBot to check the issue. Could you please provide more details?
![SignInAdpter](https://github.com/microsoft/BotBuilder-Samples/assets/167064182/e41199bb-d1f0-46b0-94fc-4d0389b1b533)
![SignInJson](https://github.com/microsoft/BotBuilder-Samples/assets/167064182/641318ef-0094-4c80-8bf1-610d2545cbb4)

**Comment by Amrit10737726** [comment]
@Aiswarya1794 Could you provide more details? Are you still experiencing the same issue? If so, which sample is causing the problem?
