### ISSUE TITLE
[ignite] V4 Basic Bot sample 13 fails to run

### ISSUE THREAD

**Issue by Joseph-Szymanski** [Microsoft/BotBuilder-Samples#399]
Using the V4 SDK, \javascript_nodejs\13.basic-bot, I get an error trying to run my locally created bot (using basic bot sample 13 from the SDK):

Launch configuration created based on 'package.json'.
C:\Program Files\nodejs\node.exe --inspect-brk=20551 index.js 
Debugger listening on ws://127.0.0.1:20551/4b77bfa9-8b97-4cc7-96f3-7ddbe55f8218
Debugger attached.
module.js:549
    throw err;
    ^

Error: Cannot find module 'ms-rest-js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\foo\bugbash-20180917\BotBuilder-Samples-4\javascript_nodejs\13.basic-bot\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\connectorClient.js:10:16)

**Comment by Joseph-Szymanski** [comment]
I found it worked after running the following commands:
npm install ms-rest-js
npm install request
npm install jsonwebtoken
npm install rsa-pem-from-mod-exp
npm install base64url
npm install async-file
npm install filenamify
npm install fs-extra
npm install read-text-file
npm install azure-cognitiveservices-luis-runtime
npm install html-entities
npm install request-promise-native
npm install @microsoft/recognizers-text-number
npm install @microsoft/recognizers-text-choice
npm install @microsoft/recognizers-text-date-time

**Comment by stevengum** [comment]
Note: Original attempts were with Node.js 8.10.0.

Closing as Joe and I were both unable to repro this on my machine and his original machine: we both had Node.js 8.12.0 and NPM 6.4.1 installed.

The dependencies below are subdependencies of our packages and are (should) be installed whenever `npm i` or  `npm install` is called:

```bash
npm install ms-rest-js
npm install request
npm install jsonwebtoken
npm install rsa-pem-from-mod-exp
npm install base64url
npm install async-file
npm install filenamify
npm install fs-extra
npm install read-text-file
npm install azure-cognitiveservices-luis-runtime
npm install html-entities
npm install request-promise-native
npm install @microsoft/recognizers-text-number
npm install @microsoft/recognizers-text-choice
npm install @microsoft/recognizers-text-date-time
```
