### ISSUE TITLE
https://www.facebook.com/profile.php?id=100078106500760

### ISSUE THREAD

**Issue by marissareyes80** [microsoft/BotBuilder-Samples#4012]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by stevkan** [comment]
@marissareyes80 - There is no information provided in this issue. Can you provide details and answers to the above questions about the problem you are experiencing?
