### ISSUE TITLE
OAuthPrompt popup is not showing for login in MS-Teams. 

### ISSUE THREAD

**Issue by sc3446** [microsoft/BotBuilder-Samples#4013]
For Bot authentication, OAuthPrompt card user for user login. It is working in Emulator online Test in Web chat but tested in Teams then pop-up is not showing to "login" button. It is working before 10 Sep 2024.

Chatbot is build using Azure bot framework(node.js). node modules botbuilder-dialogs(^4.18.0) – OauthPrompt with service provider(Azure Active Directory v2, Azure Active Directory) used for login purpose. OAuthPrompt “Sign In” button not displaying on Teams channel. 
FYI, OAuthPrompt “Sign In” button displaying on Webchat channel.

Tried sample codes still same issue with sample code as well. 
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/nodejs

Sample code:
return await stepContext.beginDialog(OAUTH_PROMPT);

Screenshot: Teams
![image](https://github.com/user-attachments/assets/a1634398-d989-4651-a5d9-3c56ad7e2d5b)

Tried this still not working:
https://github.com/microsoft/BotBuilder-Samples/issues/1739

**Comment by sc3446** [comment]
Same issue reported once again: https://github.com/OfficeDev/microsoft-teams-library-js/issues/2510

**Comment by tracyboehrer** [comment]
This is a Teams issue.  I believe a fix is in progress.

**Comment by tracyboehrer** [comment]
The fix was rolled out and should be resolved.  Reopen if not.
