### ISSUE TITLE
[.NET] Problems with speech to text sample

### ISSUE THREAD

**Issue by noxsicarius** [Microsoft/BotBuilder-Samples#42]
This may not be specific to this sample as I see an interesting error on all projects I run.

First, the immediate window is getting this a good number of times: 
`iisexpress.exe Warning: 0 : Service url localhost:62141 is not trusted and JwtToken cannot be sent to it.`

I feel like this may be causing my issue where I can push an attachment to the emulator, but if it is a wav file I break to the catch exception on the try catch. Anything not a wav file gives me the correct output, but the wav seems to throw an exception when it tries to hit the bing service. I was hoping someone may have some information on this issue.

**Comment by willportnoy** [comment]
@msft-shahins can you comment?

**Comment by nwhitmont** [comment]
relates to: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-SpeechToText

**Comment by sgellock** [comment]
closed due to inactivity
