### ISSUE TITLE
Context.Call doesn't call Dialog's StartAsync

### ISSUE THREAD

**Issue by michaelsrichter** [Microsoft/BotBuilder-Samples#43]
I have the following code in my rootDialog (see below). I am detecting if a user has a profile set up in UserData, if not, I want them to go to the BotUserProfile dialog. There is a series of DialogPrompts in that Dialog, so I need to use Context.Call (not Context.Forward).

The problem is that when I call Context.Call from MessageReceivedAsync, it **does not** appear to call StartAsync in the child dialog. In fact, it's not clear to me how any methods get called in the child dialog and all the examples of Context.Call that I can find are for FormFlow, not custom dialogs.  Context.Call appears to just immediately return the ResumeAfter callback.

BUT, If I move that Context.Call code into the RootDialog's StartAsync, then Context.Call **does** call the child dialog's StartAsync.  This wont work for me as StartAsync is called once per conversation, and I need this check to be performed on every message sent. 

Thanks for any help.

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(this.MessageReceivedAsync);
        }

        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {

            BotUserProfile botUserProfile;

            if (!context.UserData.TryGetValue("botUserProfile", out botUserProfile))
            {
                if (botUserProfile == null)
                {
                    try
                    {
                        //this doesn't seem to be calling _botUserProfileDialog's StartAsync
                        context.Call(_botUserProfileDialog, ResumeAfterDialog);
                    }
                    catch (Exception e)
                    {

                        await context.PostUpAsync(e.ToString());
                    }
                }
                else
                {
                    {
                        if (botUserProfile.ActiveUntil < DateTime.UtcNow)
                        {
                            context.UserData.RemoveValue("botUserProfile");
                            context.Call(_botUserProfileDialog, ResumeAfterDialog);
                        }
                    }
                }
                ...
            }

**Comment by michaelsrichter** [comment]
I am going to close this. The problem was further down in my MessageReceivedAsync method; it was throwing an unhandled exception which was messing with the execution of the dialogs. It works now.

**Comment by willportnoy** [comment]
I'm happy to hear you found the issue.  By the way, you might find a more active forum at https://github.com/Microsoft/BotBuilder/issues.
