### ISSUE TITLE
Spelling error: paternAny should be patternAny

### ISSUE THREAD

**Issue by diberry** [Microsoft/BotBuilder-Samples#436]
### SDK Platform
v4 branch

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/blob/v4/javascript_ts/13.basic-bot/src/bot.ts

probably in others

### Problem Description
One line spells pattern correctly and the other is missing the second "t".

// Supported LUIS Entities, defined in ./dialogs/greeting/resources/greeting.lu
const USER_NAME_ENTITIES = ['userName', 'userName_paternAny'];
const USER_LOCATION_ENTITIES = ['userLocation', 'userLocation_patternAny'];

Do you want a pull request?

**Comment by vishwacsena** [comment]
Also needs a fix in the .lu file - https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_typescript/13.basic-bot/resources/greeting.lu
