### ISSUE TITLE
[Code Example] intelligence-ImageCaption: {"code":"ResourceNotFound","message":"/ does not exist"}

### ISSUE THREAD

**Issue by ShuaiW** [Microsoft/BotBuilder-Samples#44]
So I tried the example, [ImageCaption](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/intelligence-ImageCaption), and deployed to Azure (by clicking the blue button).

 However after the deployment I got the following error when I visit the url:

`{"code":"ResourceNotFound","message":"/ does not exist"}`

Any help would be appreciated.

**Comment by pcostantini** [comment]
The bot runs on the `/api/messages` endpoint. E.g.: `https://[YOURAZUREBOTAPP].azurewebsites.net/api/messages`

You need to [edit the bot registration](https://dev.botframework.com/bots) and update the message endpoint.
(Remember to set the Microsoft App Id and Microsoft App Password when deploying the bot)

Once the bot is configured and deployed, you can try the webchat from the [Bot registration page](https://dev.botframework.com/bots).

> NOTE: The sample code does not contain or host any webpages, it just a REST API with a single endpoint

**Comment by nwhitmont** [comment]
relates to: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/intelligence-ImageCaption

**Comment by nikhilabhiman** [comment]
Even, I get the same issue.  How do I access the Bot I have built over the browser and give URL to someone to test. Everytime , I need to login in azure and see it in Web chat

I get the below error when accessed through the browser

https://{mydomain}.azurewebsites.net/ . 
{"code":"ResourceNotFound","message":"/ does not exist"}

https://{mydomain}.azurewebsites.net/webchat?s={direct_line_secret_key} 
{"code":"ResourceNotFound","message":"/webchat does not exist"}

**Comment by nwhitmont** [comment]
@nikhilabhiman - You can test your deployed bot using 1) the Bot Framework Emulator, or 2) a WebChat hosted on your server.

For more information on Emulator, check out:
https://github.com/Microsoft/BotFramework-Emulator
