### ISSUE TITLE
[Feature Request] Unit and integration testing examples for Node samples

### ISSUE THREAD

**Issue by anweiss** [Microsoft/BotBuilder-Samples#46]
Would love to see some unit and integration testing examples for the Node samples

**Comment by wilhen01** [comment]
Bump! 💯 

Currently googling around for examples of how to Unit Test the v4 BotBuilder SDK in NodeJS and there is basically nothing out there, a few blog posts about v3 but nothing current.

**Comment by benbrown** [comment]
V4 has a lot more testing infrastructure, and a lot more coming soon.  We are not planning on going back to v3 to add anything new like this.
