### ISSUE TITLE
C# Basic sample is missing .lu files under Dialogs\greetings\resources

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotBuilder-Samples#464]
### SDK Platform
in .NET  Dialog greeting is missing resource folder with all .lu files
https://github.com/Microsoft/BotBuilder-Samples/tree/v4/samples/csharp_dotnetcore/13.basic-bot
**missing**

in JS
**Found**
https://github.com/Microsoft/BotBuilder-Samples/tree/v4/samples/javascript_nodejs/13.basic-bot/dialogs/greeting

Also,
CognativeModels  includes a basic-bot.luis
DeploymentScript\MsbotClone  includes the same file(?)  called 34.luis? 

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/v4/samples/csharp_dotnetcore/13.basic-bot

**Comment by vishwacsena** [comment]
Fixed.
