### ISSUE TITLE
Always see "[File of type 'audio/wav'] Oops! Something went wrong. Try again later."

### ISSUE THREAD

**Issue by smich73** [Microsoft/BotBuilder-Samples#48]
I have tried a number of wav files when using this sample, including the weather wav file provided and each time it fails with: "[File of type 'audio/wav'] Oops! Something went wrong. Try again later."

This is the C# sample running in the emulator .
In Skype I cannot get a response at all

**Comment by ejadib** [comment]
@smich73 try removing [this block of code](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/intelligence-SpeechToText/Controllers/MessagesController.cs#L156-L159) and let me know if it works for you.

**Comment by smich73** [comment]
The fix is in the GetImageStream() method:

Replace existing code with:

using (var httpClient = new HttpClient())
            {
                // The Skype attachment URLs are secured by JwtToken,
                // you should set the JwtToken of your bot as the authorization header for the GET request your bot initiates to fetch the image.
                // https://github.com/Microsoft/BotBuilder/issues/662
                var uri = new Uri(imageAttachment.ContentUrl);
                if (uri.Host.EndsWith("skype.com") && uri.Scheme == "https")
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await GetTokenAsync(connector));
                }

                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/octet-stream"));
                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(imageAttachment.ContentType));
               return
