### ISSUE TITLE
[.NET] Are these samples outdated?

### ISSUE THREAD

**Issue by arashberlin** [Microsoft/BotBuilder-Samples#49]
Hi there.

sorry for my English. I try the undersatnd the Microsoft Bot Builder and the Dialogs methods.

In the samples the Microsoft Bot Builder 3.2.1.0 is used.

In the namespace Microsoft.Bot.Builder.Dialogs there is a class called **PromptStyler**

The void method "Apply"  uses **IList**<T> option.

In the new assembly 3.5.0.0  there is **IReadOnlyList**<T> options.

When I updated the solution I can't build the Bot.   Why is there a change from _IList_ to _IReadOnlyList_?

And how can I fix the issue?

-->Sample I used: SearchPowerBots  > Project "Search.Dialogs"

Many thanks
Arash

**Comment by ejadib** [comment]
They are, but they are being updated. PR #50 takes care of updating the C# samples. That being said, the issue you are having is pretty straightforward to fix; just update the references to be IReadOnlyList. At some point BotBuilder introduced that breaking change.

**Comment by arashberlin** [comment]
Thanks. I give it a try tomorrow.

Regards 
Arash




On Thu, Jan 12, 2017 at 9:14 PM +0100, "Ezequiel Jadib" <notifications@github.com> wrote:












They are, but they are being updated. PR #50 takes care of updating the C# samples. That being said, the issue you are having is pretty straightforward to fix; just update the references to be IReadOnlyList. At some point BotBuilder introduced that breaking change.

**Comment by oflahero** [comment]
I had to do some messing around also with the 'SettingsScorable' IScorable implementation in the ContosoFlowers sample to get it to work with the latest IScorable also. Guess I should be looking more closely at the pull requests!

**Comment by ejadib** [comment]
The PR with the updated C# samples was already merged!

**Comment by oflahero** [comment]
Nice one, thanks E, I must have last pulled just before the merge.

**Comment by piffarettig** [comment]
DirectLine Sample has outdated code as well. It could be great if you fix it :)

**Comment by ejadib** [comment]
The DirectLine sample was also updated to use DirectLine V3. What part is outdated?
