### ISSUE TITLE
npm i -g <botbuilder-tools packages> errors out on Linux

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder-Samples#519]
### SDK Platform
Node.js v4 Samples

### URL of Code Sample
All current README.md telling users to install botbuilder-tools packages via `npm i -g`

### Problem Description
Linux users need to use `sudo npm i -g`, `npm i -g` will error out unless the user is already logged in as the super user (which is nomally unlikely).

### Fix
We should include a separate set of instructions (which is most likely two lines) in the READMEs indicating what users need to do to install the CLI tools for their respective platform.

Encountered on Ubuntu 16.04

**Comment by vishwacsena** [comment]
@stevengum  - great bug. Can you help draft up the concise set of instructions we can share out? We likely need to fix botbuilder-tools repo as well.

**Comment by stevengum** [comment]
Closing this as #587 was merged in. We are reevaluating our READMEs and _documentation_ to come up with a clear set of concise instructions and the info in #587/Installing_CLI_tools.md should most likely go in there.
