### ISSUE TITLE
[Question] Support for audio/aac and video/mp4 file formats used in Facebook Messenger

### ISSUE THREAD

**Issue by weiligao** [Microsoft/BotBuilder-Samples#52]
Is it there a way to add support for audio/aac and video/mp4 file formats used in Facebook Messenger, as currently the Bing Speech API is only able to handle audio/wav files? For example, is there a way to convert audio/aac or video/mp4 files into audio/wav files online?

**Comment by pcostantini** [comment]
Hi @weiligao,
Currently, the Bing Speech API only supports WAV/PCM. You'll need to convert from AAC or MP4 into PCM.

For C# I think one of the best options is to use NAudio (https://www.nuget.org/packages/NAudio/ | https://github.com/naudio/NAudio).
For Node, I'm not aware of any out-of-the-box AAC/MP3 to PCM encoders, but there are Node wrappers for ffmpeg (e.g.: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) that could be used for the same purpose.

Also, there are a few online converters that expose some kind of API and could be helpful, search for "mp3 to wav API".
Regards,
-PabloC.
