### ISSUE TITLE
Uploaded attachment option in sample throws content length error

### ISSUE THREAD

**Issue by nyxsys** [Microsoft/BotBuilder-Samples#540]
## Sample information
1. Sample type: \samples\
2. Sample language: nodejs 
3. Sample name: 15.handling-attachments

## Describe the bug
"Uploaded Attachment" causes an error `[onTurnError]: Error: The request content length exceeded limit of 262144 bytes.` This occurs in at least webchat, facebook and slack. Additionally, these channels appear to not allow uploading a new attachment in place of the old one.

## To Reproduce

1. Set up sample
2. Begin conversation with bot in webchat
3. select option 3 'Uploaded Attachment'

## Expected behavior
Give a clear and concise description of what you expected to happen.
Card saved within bot 'architecture-resize' should appear, it is a reasonable size as well (less than 1mb) 

## Screenshots

<img width="252" alt="error" src="https://user-images.githubusercontent.com/6576516/45984068-3a03b300-c014-11e8-93ca-3d0d95a85deb.PNG">

## Additional context
So it seems that this picture is considered too large for the channel, but it really seems like this one is smaller than what would be expected in production environments.

[bug]

**Comment by JasonSowers** [comment]
This also happens in c# going to resize the image.
