### ISSUE TITLE
SendAttachment samples should illustrate upload and base64 data URIs

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotBuilder-Samples#55]
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-SendAttachment
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-SendAttachment

These samples do a good job on the attachment side, but don't illustrate upload.

They should show:
1. Uploading via the attachment API (https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_UploadAttachment)
2. Including an attachment inline as a base64 data URI (example here, search for "base64": https://docs.botframework.com/en-us/core-concepts/attachments/)

**Comment by ejadib** [comment]
Thanks @dandriscoll. We applying these enhancements and they will be ready to be reviewed later today.

**Comment by ejadib** [comment]
@dandriscoll this is already merged. Feel free to close the issue if the updates are ok for you.

**Comment by dandriscoll** [comment]
These are great! Thanks @ejadib and @pcostantini
