### ISSUE TITLE
NLP with Dispatch throws exception after following readme instructions

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#557]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 14.nlp-with-dispatch

## Describe the bug
Follow README instructions up through **Securing keys in your .bot file** and [**Visual Studio**](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch#visual-studio). The bot throws an exception during setup.

## To Reproduce
1. Follow the instructions in the readme. (Use your own subscription key instead of the hard coded one for QnA Maker. Update your **appsettings.json** file instead of the **.env** file for recording your secret key.)
1. Open the project in Visual Studio and hit F5.
1. A web page is displayed, with an exception (see screenshot).

## Expected behavior
The bot should run.

## Screenshots
![capture](https://user-images.githubusercontent.com/35047199/46100101-7868b180-c17d-11e8-875d-a859657fefba.PNG)

[bug]

**Comment by JonathanFingold** [comment]
Fix line 186
```csharp
var app = new LuisApplication(luis.AppId, luis.AuthoringKey, luis.GetEndpoint());
```

Next error, line 216:
```text
System.InvalidOperationException
  HResult=0x80131509
  Message=The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file.
  Source=NLP_With_Dispatch_Bot
  StackTrace:
   at NLP_With_Dispatch_Bot.Startup.InitBotServices(BotConfiguration config) in C:\Users\v-jofing\source\repos\scratch\14.nlp-with-dispatch\Startup.cs:line 219
   at NLP_With_Dispatch_Bot.Startup.<>c__DisplayClass6_0.<ConfigureServices>b__0(BotFrameworkOptions options) in C:\Users\v-jofing\source\repos\scratch\14.nlp-with-dispatch\Startup.cs:line 80
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

**Comment by JasonSowers** [comment]
@JonathanFingold would you like to submit a PR with these changes or would you like me to?

**Comment by JonathanFingold** [comment]
Since there are more errors that I haven't tracked down yet, please go for it.

**Comment by daveta** [comment]
See https://github.com/Microsoft/BotBuilder-Samples/pull/576 which should address the issues.

**Comment by JonathanFingold** [comment]
Following the non-clone instructions still is throwing various exceptions:

Line 7 in **BotConfiguration.bot** still needs to change to:
```json
        "name": "development",
```

Also, **Startup.cs** line 189 throws. Changing it to
```csharp
luisServices.Add(luis.Name.Split(" ")[1], recognizer);
```
Gets rid of the first exception thrown by that line (for "Home Automation"), but it still throws (for "Weather"). I'm not even sure why this line is in here. Should this really be:
```csharp
luisServices.Add(luis.Name.Replace(' ', '_'), recognizer);
```

Changing that get to the next exception at line 216:
```csharp
throw new InvalidOperationException("The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file.");
```
Is this a bug in the `dispatch` or `msbot` tool, where the .bot file isn't updated correctly? Since I've been following along with the readme instructions up to this point, I've set a bot secret, so I don't know how to manually fix my .bot file.

**Comment by JonathanFingold** [comment]
I'm still not out of **Startup.cs**

Tweaking the code around 216 to the following gets me past one more hurdle:
```csharp
if (string.IsNullOrWhiteSpace(dispatch.SubscriptionKey))
{
    if (string.IsNullOrWhiteSpace(dispatch.AuthoringKey))
    {
        throw new InvalidOperationException("The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file.");
    }
    else
    {
        dispatch.SubscriptionKey = dispatch.AuthoringKey;
    }
}
```

Then I run into the dreaded  `dispatch.Name.Split("_")[1]` call, which throws. Replacing with:
```csharp
luisServices.Add(dispatch.Name.Replace(' ', '_'), dispatchARecognizer);
```

This maybe gets me out of Startup? Now I get a 404.
```text
NLP-With-Dispatch-Bot>       Request starting HTTP/1.1 GET http://localhost:3978/  
NLP-With-Dispatch-Bot> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
NLP-With-Dispatch-Bot>       Request starting HTTP/1.1 DEBUG http://localhost:3978/  0
NLP-With-Dispatch-Bot> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
NLP-With-Dispatch-Bot>       Request finished in 141.1612ms 200 
NLP-With-Dispatch-Bot> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
NLP-With-Dispatch-Bot>       Request finished in 151.758ms 404 
```

**Comment by JonathanFingold** [comment]
Yes, so:
1. Creating a folder named **wwwroot**, and creating a **default.html** file within it solves the 404 issue.

**Comment by JonathanFingold** [comment]
Well, now I'm getting `System.ArgumentException: Invalid configuration.  Please check your '.bot' file for a Luis service named 'Home Automation'.` So, I guess the dreaded Name.Split("_")[1] should be simple just Name...

**Comment by JonathanFingold** [comment]
Doing that at least gets me to the welcome message, but no further. Throwing in the towel for now.
```text
NLP-With-Dispatch-Bot>       Exception caught : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
NLP-With-Dispatch-Bot>          at System.ThrowHelper.ThrowKeyNotFoundException()
NLP-With-Dispatch-Bot>          at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
NLP-With-Dispatch-Bot>          at NLP_With_Dispatch_Bot.NlpDispatchBot.<OnTurnAsync>d__7.MoveNext() in C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\csharp_dotnetcore\14.nlp-with-dispatch\NlpDispatch\NlpDispatchBot.cs:line 92
NLP-With-Dispatch-Bot>       --- End of stack trace from previous location where exception was thrown ---
NLP-With-Dispatch-Bot>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
NLP-With-Dispatch-Bot>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
NLP-With-Dispatch-Bot>          at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
NLP-With-Dispatch-Bot>       --- End of stack trace from previous location where exception was thrown ---
NLP-With-Dispatch-Bot>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
NLP-With-Dispatch-Bot>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
NLP-With-Dispatch-Bot>          at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167
NLP-With-Dispatch-Bot> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
NLP-With-Dispatch-Bot>       Request finished in 179.8303ms 200 
```

**Comment by daveta** [comment]
@JonathanFingold : Thanks for finding the missing default.htm file - not sure how I missed that!  I checked in a fix for that.

For the other stuff, the sample assumes you have run msbot.  The implications are:
- You should use the .bot configuration file that gets generated for you.
- When you deploy using msbot, you provide a name (hopefully a short name - i don't know the max limit on chars before you get into trouble).
- Msbot will then generate the .bot configuration file, and it decorates the names of the LUIS and Dispatch entries - prefixes each name with YOUR MSBOT NAME_yourluismodel.
- The code in there is handling this case..

Let me know if this helps.

**Comment by JonathanFingold** [comment]
@daveta I followed the readme instruction faithfully. This is the structure of the resulting .bot file. There's an `authoringKey`, but no `subscriptionKey` in the Dispatch section.
```json
{
    "name": "NLP-With-Dispatch-Bot",
    "description": "",
    "services": [
        {
            "type": "endpoint",
            "name": "<some-name-other-than-development>",
            "id": "http://localhost:3978/api/messages",
            "appId": "",
            "appPassword": "",
            "endpoint": "http://localhost:3978/api/messages"
        },
        {
            "type": "luis",
            "name": "Home Automation",
            "appId": "ef40dce4-611d-40d8-9bee-374d6b3c31f0",
            "version": "0.1",
            "authoringKey": "<encrypted-stuff>",
            "subscriptionKey": "<encrypted-stuff>",
            "region": "westus",
            "id": "162"
        },
        {
            "type": "luis",
            "name": "Weather",
            "appId": "29e24ac7-30fb-4fd4-9e6e-e1ee1a96afe1",
            "version": "0.1",
            "authoringKey": "<encrypted-stuff>",
            "subscriptionKey": "<encrypted-stuff>",
            "region": "westus",
            "id": "14"
        },
        {
            "type": "qna",
            "name": "sample-qna",
            "kbId": "1ee7c8e6-0d18-4bf5-a8a0-6d4d5eed8caf",
            "subscriptionKey": "<encrypted-stuff>",
            "endpointKey": "<encrypted-stuff>",
            "hostname": "https://jf-qnamaker.azurewebsites.net/qnamaker",
            "id": "49"
        },
        {
            "type": "dispatch",
            "name": "NLP-With-Dispatch-BotDispatch",
            "appId": "f5e0ee97-d054-4a17-935b-69f394fea517",
            "authoringKey": "<encrypted-stuff>",
            "version": "Dispatch",
            "region": "westus",
            "serviceIds": [
                "162",
                "14",
                "49"
            ],
            "id": "236"
        }
    ],
    "padlock": "<encrypted-stuff>",
    "version": "2.0"
}
```

**Comment by ryantwarner** [comment]
@JonathanFingold currently working through this, can confirm adding subscriptionKey to dispatch, and the missing default.htm, makes things work.

**Comment by JonathanFingold** [comment]
@JasonSowers Did you mean to close this issue? I think your PR only addressed some of the issues raised here.
