### ISSUE TITLE
TypeScript missing from Prerequisites list in Botbuilder SDK for Javascript QuickStart page

### ISSUE THREAD

**Issue by mriverap** [Microsoft/BotBuilder-Samples#560]
## Sample information
1. Sample type: QuickStart instructions
2. Sample language: typescript

## Describe the bug
The bot created by following steps in the page fails to start if Typescript is not installed in the machine. The page should include Typescript as pre-requisite when running the installer for Typescript.

## To Reproduce
1. Go to [https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
2. Follow all installation steps. When choosing the language for the bot, choose TypeScript.
3. Attempt to start the bot.
4. See error.

**Comment by sgellock** [comment]
fixed with https://github.com/Microsoft/BotBuilder-Samples/pull/569.
Will be in 4.0.9 update of generator-botbuilder
