### ISSUE TITLE
Broken link in sample 11, QnA Maker

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#562]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 11.qnamaker

## Describe the bug
The second link in the [Prerequisites](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker#prerequisites) section generates a 404.

## To Reproduce
1. Go to [Prerequisites](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker#prerequisites).
1. Click on the [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/migrate-knowledge-base) link in the second bullet.
1. See error.

## Expected behavior
The link should go to a page with instructions on how to import a QnA Maker file.

[bug]

**Comment by JasonSowers** [comment]
addressed in #573
