### ISSUE TITLE
v4 Emulator fails to connect using Node.js proactive bot file.

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#563]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 16.proactive-messages

## Describe the bug
The **.bot** file refuses to open in the v4 Emulator.

## To Reproduce
1. Open the BotBuilder-Samples/samples/javascript_nodejs/16.proactive-messages/ folder in VS Code.
  - In the terminal, enter `npm i` and `npm start` to get the bot running.
1. Open the v4 Emulator.
  - Try to open the Node.js proactive-messages.bot.
  - **Nothing happens**.
  - Try to open the Node.js echobot-with-counter.bot [sample 2], which uses the same port.
  - The Emulator connects to the bot.

## Expected behavior
Opening the proactive-messages.bot file in the Emulator should connect to the bot.

## Additional context
I tried copy-pasting the contents of the echobot-with-counter.bot file to the proactive-messages.bot file, then updating the "name" property, and still got the same behavior. I am completely baffled.

[bug]

**Comment by benbrown** [comment]
@JonathanFingold What version of the emulator are you using?
Are you on a Mac, PC or linux?

**Comment by JonathanFingold** [comment]
@benbrown I'm on Windows 10 Enterprise x64, using "Bot Framework Emulator (V4 PREVIEW) version 4.0.196-nightly.

**Comment by JonathanFingold** [comment]
@benbrown PS. Creating an echo bot from the Yeoman template produces the same behavior. I've tried both js and ts templates.

**Comment by benbrown** [comment]
@JonathanFingold thanks for the info. I am not able to reproduce so far, but I'm still investigating.

**Comment by JonathanFingold** [comment]
Here's some additional system info:
node v8.12.0
npm 6.4.1
python 3.7.0
yeoman 2.0.5
botbuilder 4.0.6

**Comment by benbrown** [comment]
@JonathanFingold can you give it a shot with a slightly newer build of the emulator? I can't reproduce with 577-nightly for example.

**Comment by JonathanFingold** [comment]
@benbrown Well, that appears to have been mostly it. I uninstalled the emulator and installed the preview, and now it's working, at least with the changes I had already made to the .bot file.

I'll revert those to see if it still works

Bot Framework Emulator (V4 PREVIEW)
version: 4.0.0-preview.40326

**Comment by JonathanFingold** [comment]
@benbrown Okay, it seems to work, even after reverting the .bot file. Closing.
