### ISSUE TITLE
[Yeoman] TypeScript Basic template prompt bug

### ISSUE THREAD

**Issue by afnan-ahmad** [Microsoft/BotBuilder-Samples#585]
## Describe the bug
I am using the **Basic** bot template in TypeScript via Yeoman generator, when I get into the **Greeting** intent by saying hello, the bot asks for the user's name (In Prompt), and when replying with a name, it goes into the **None** intent on the next **onTurn** resulting in a _"I didn't understand what you just said."_ response.

## Expected behavior
The bot should have continued the dialog after getting a reply for the Prompt instead of checking for a new intent.

## Causes
```JavaScript
      if (!dc.context.responded) {
        // examine results from active dialog
        switch (dialogResult.status) {
          case DialogTurnStatus.empty:
            switch (topIntent) {
              case GREETING_INTENT:
                await dc.beginDialog(GREETING_DIALOG);
                break;
              case NONE_INTENT:
              default:
                // help or no intent identified, either way, let's provide some help
                // to the user
                await dc.context.sendActivity(`I didn't understand what you just said to me.`);
                break;
            }
          default:
            // Unrecognized status from child dialog. Cancel all dialogs.
            await dc.cancelAllDialogs();
            break;
        }
      }
```

Break is missing in the first switch statement **(dialogResult.status)** on the **DialogTurnStatus.empty** case causing the child dialog(s) to be canceled always (Because default case is triggered). **[See Line 146](https://github.com/Microsoft/BotBuilder-Samples/blob/master/generators/generator-botbuilder/generators/app/templates/basic/bot.ts#L146)**

[bug]

**Comment by vishwacsena** [comment]
Bug also exists in the TS basic bot sample. JS and C# basic bot samples are ok.

**Comment by afnan-ahmad** [comment]
Right, the code seems identical for both. Should I submit a PR?

**Comment by sgellock** [comment]
@afnan-ahmad that code lives in multiple places. so I'll push up a PR today.  Thanks for reporting the issue.

**Comment by sgellock** [comment]
Fix addressed in pull https://github.com/Microsoft/BotBuilder-Samples/pull/603
