### ISSUE TITLE
V3 links are broken

### ISSUE THREAD

**Issue by mikeblancas** [Microsoft/BotBuilder-Samples#590]
## Sample information
1. Sample type: V3 Samples
2. Sample language: any
3. Sample name: any

## Describe the bug
Getting a 404 error when accessing V3 samples repository

## To Reproduce
1. Go to 'https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples'
2. See error

## Expected behavior
Was able to access this Friday morning GMT+8.

## Additional context
Must be related to the recent update of the repository to v4

[bug]

**Comment by stevengum** [comment]
Thanks for reporting this, the branch is now back up and available. Can you confirm your access to it?

I'm going to close this issue tomorrow as I am able to access the branch via the link in the current `master` README.md.
