### ISSUE TITLE
[24.bot-authentication-msgraph] TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by mzoi** [Microsoft/BotBuilder-Samples#596]
## Sample information
[24.bot-authentication-msgraph
](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph)

## Describe the bug
After displaying Login card, an error occurred : "**TypeError: Converting circular structure to JSON**" and I can not login, even when I typed the magic number.
The error is displayed server side, so I deciced to display in the bot for debuging purpose.

## To Reproduce
Deploy the bot in Azure and use Web chat or Direct Line channel.

## Screenshot
![image](https://user-images.githubusercontent.com/43778222/46345756-0218f300-c646-11e8-8780-ce378a1e5bf4.png)
![image](https://user-images.githubusercontent.com/43778222/46345898-8d928400-c646-11e8-97b5-746428458437.png)

**Comment by JasonSowers** [comment]
Looking into this

**Comment by JasonSowers** [comment]
#621 addresses this and has been merged, please pull from the repo.  Thanks for reporting this.

**Comment by mzoi** [comment]
It works. Thanks for the fix.
