### ISSUE TITLE
C# Dispatch startup code expects a subscription key for Dispatch, throws exception

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#607]
## Sample information
1. Sample type: **samples**
2. Sample language: **dotnetcore**
3. Sample name: **14.nlp-with-dispatch**

## Describe the bug
Following the readme instructions causes an exception at startup;
C# Dispatch startup code expects a subscription key for Dispacth, throws exception.

## To Reproduce
1. Go to the [README](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md) for the sample.
1. Follow the steps in the readme:
   1. [Install BotBuilder tools](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#install-botbuilder-tools).
   1. [Manually configure required services](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#manually-configure-required-services).
   1. Manually change the endpoint name in the .bot file to "development". (re: issue #606)
   1. Run the bot in [Visual Studio](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md#visual-studio).
1. The app throws an exception in Startup.cs, line 216:
```text
System.InvalidOperationException
  HResult=0x80131509
  Message=The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file.
  Source=NLP_With_Dispatch_Bot
  StackTrace:
   at NLP_With_Dispatch_Bot.Startup.InitBotServices(BotConfiguration config) in C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\csharp_dotnetcore\14.nlp-with-dispatch\Startup.cs:line 219
   at NLP_With_Dispatch_Bot.Startup.ConfigureServices(IServiceCollection services) in C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\csharp_dotnetcore\14.nlp-with-dispatch\Startup.cs:line 77
```

## Expected behavior
Following the instructions should not cause an exception.

## Additional context
Here are the offending lines. The instructions to construct the .bot file or the code in Startup should be updated so no exception is thrown.

**BotConfiguration.bot** (lines 42-55):
```json
        {
            "type": "dispatch",
            "name": "NLP-With-Dispatch-BotDispatch",
            "appId": "5b0651a9-2f9f-4b90-826d-93005de692e4",
            "authoringKey": "<my-authoring-key>",
            "version": "Dispatch",
            "region": "westus",
            "serviceIds": [
                "178",
                "46",
                "54"
            ],
            "id": "138"
        },
```

**Startup.cs** (lines 193-217):
```csharp
case ServiceTypes.Dispatch:
	...
	if (string.IsNullOrWhiteSpace(dispatch.SubscriptionKey))
	{
		throw new InvalidOperationException("The Subscription Key ('subscriptionKey') is required to run this sample. Please update your '.bot' file.");
	}
	...
```

[bug]

**Comment by stevengum** [comment]
Closing via #613
