### ISSUE TITLE
Can't run DirectLine sample

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder-Samples#62]
Hello,

I have a bot registered on bot framework. I have it's bot-id, it's Microsoft app id, and its  Microsoft secret password. I have also configured DirectLine as a channel on it.

I have downloaded the [core-DirectLine](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine) sample, and I did the following changes before running the sample:

- To the Web Api Project (Bot's logic), I modified the web.config values:

```
 <add key="BotId" value="MY_BOT_ID_HERE" />
 <add key="MicrosoftAppId" value="MY_APP_ID_HERE" />
 <add key="MicrosoftAppPassword" value="MY_PASS_HERE" />
```

- To the Console Application (DirectLine client), I modified the app.config values:
```

<add key="DirectLineSecret" value="DIRECT_LINE_SECRET_HERE"/>
<add key="BotId" value="MY_BOT_ID_HERE" />

```
One thing to mention is that when I configured DirectLine, it gives me two secret keys but I think is the same using one or another.

I have the Bot app deployed on Azure, and I run the console app locally.

**What happens:**

Whenever I send a message from Skype (bot user), the client doesn't receive anything. Similarly, when I write something on the DirectLineClientApp, the bot user doesn't receive anything via the bot.

This is what I get when I send something via direct line client app:

<img width="941" alt="screen shot 2017-01-25 at 14 25 16" src="https://cloud.githubusercontent.com/assets/16963208/22301626/70fcb5de-e30a-11e6-8d97-4a4e3a82364c.png">

But nothing on Skype bot. And the same vice versa.

Any help?

Thanks.

**Comment by piffarettig** [comment]
@dandriscoll @willportnoy 

Maybe you know the answer to this one. Thanks!

**Comment by ejadib** [comment]
@piffarettig Let's leave Azure out of the picture for now and try the simplest path first. 

What happen if you run both the client and the bot locally and use ngrok to tunnel your bot (updating the Bot URL in the Bot Framework portal to match the one provided by ngrok)? I'm running that scenario right now and it's working for me

**Comment by piffarettig** [comment]
The same. First I was running it on ngrok as it easier to debug but I tried uploading it to Azure because maybe something related to the connection was happening.

I think that maybe I got wrong the idea of the demo, it works, but I first thought that the DirectLine Client App was  a client to send messages to the user behind the bot, not the bot itself. How could adapt this to make it send messages to the user (via the Console App)?

Thanks

**Comment by ejadib** [comment]
From the image above, it seems the bot received your message. You can try sending "show me a hero card".  The console app is just showing how you can create a simple client using DirectLine... users write in the console and get the response from the Bot in the console.

**Comment by piffarettig** [comment]
I want to send a message to some user behind Skype Channel. 

And what you say is correct. I got wrong the idea of the demo. I thought the idea of this was to achieve an interaction like:

Human -> Bot -> Human

Not like: 

[ https://github.com/Microsoft/BotBuilder/issues/2011](Like this use case)

How can redirect the message to the user?

**Comment by piffarettig** [comment]
I know this is different from the original post, but maybe you could give me a hand. 

So I am in this scenario:

Some users use a bot via Skype. These users asks questions to the bot. Whenever the bot is not able to answer any of those questions, a conversation between the user and a customer representative/expert starts.

Just for testing if this works, what I did was:

1. Created a simple bot and have it running over ngrok.
2. Created a simple Console App and have it running locally. This apps connects to the previous bot via DirectLine. 
3. Whenever a user sends a message via Skype, I want to broadcast it to the ConsoleApp, via DirectLine.

Is this possible?

What I did for testing was getting the ConversationID of the ConsoleApp interaction with the bot, and tried this code snippet:

var userAccount = new ChannelAccount("ID_OF_THE_CONVERSATION_BETWEEN_CSI_AND_BOT");
var botAccount = context.Activity.Recipient;
var connector = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount); //botAccount now is the sender, userAccount (CS) is now the recipent.
IMessageActivity messageToSend = Activity.CreateMessageActivity();
messageToSend.From = botAccount;
messageToSend.Recipient = userAccount;
messageToSend.Conversation = new ConversationAccount(id: conversationId.Id);
messageToSend.Text = message.Text;
messageToSend.Locale = "en-Us";
await connector.Conversations.SendToConversationAsync((Activity)message);
But the DirectLine Console Application is not receiving the message. Is it possible that the ConversationId (ID_OF_THE_CONVERSATION_BETWEEN_CSI_AND_BOT) changes?

Thanks

**Comment by nwhitmont** [comment]
Hi @piffarettig - If you still have questions, please post a new issue on [BotBuilder](https://github.com/Microsoft/BotBuilder) repo.
