### ISSUE TITLE
V3 .visx

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/BotBuilder-Samples#622]
This is only aplicable to the V3 version of the visx template.

In the doc located at https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0 there is a broken link to the v3 visx in the prerequisites section.  The link directs the user to the marketplace where the visx no longer exists.

In the doc located at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-overview-getstarted?view=azure-bot-service-3.0 The link directs you to a direct download of the visx.

As per the discussion we had during standup, we would like to keep a download link for the visx template active, but keep it removed from the marketplace.  Can we make the first link I mentioned lead the user to the direct download?

**Comment by Kaiqb** [comment]
@JasonSowers - The only content we have in V3 is about using ABS to create bots. Other quickstarts have been removed.
