### ISSUE TITLE
[typescript][12.nlp with luis] Sample can't be run

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/BotBuilder-Samples#627]
## Sample information
1. Sample type: \samples\
2. Sample language: typescript
3. Sample name: 12.nlp-with-luis

## Describe the bug
The sample can't be run correctly due to the following error message
`src/index.ts:45:26 - error TS2339: Property 'getEndpoint' does not exist on type 'ILuisService'.`

## To Reproduce
1. Follow the deployment, configuration and installation instructions from the [README.md](https://github.com/southworkscom/BotBuilder-Samples/blob/master/samples/javascript_typescript/12.nlp-with-luis/README.md)
2. Run `npm start`
3. The following error message appears: `src/index.ts:45:26 - error TS2339: Property 'getEndpoint' does not exist on type 'ILuisService'.`

## Expected behavior
After the configuration the sample should run correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/23645105/46559053-7f05d000-c8c5-11e8-9988-608de572e27c.png)

## Additional context
The `getEndpoint` function is found in the next context in [line 45 of src/index.ts](https://github.com/southworkscom/BotBuilder-Samples/blob/1e8cbbfc70d3ca9fb2ea38a75df79ec57311fc06/samples/javascript_typescript/12.nlp-with-luis/src/index.ts#L45)

```typescript
const luisApplication: LuisApplication = {
    applicationId: luisConfig.appId,
    endpoint: luisConfig.getEndpoint(),
    endpointKey: luisConfig.subscriptionKey
}
```

The only trace for the function `.getEndpoint()` is found in the `LuisService `class in the `botframework-config` library for the BotBuilder-js project but none is found in the TypeScript implementation. A good starting point would be adding the signature to the `ILuisService `interface.

[bug]

**Comment by benbrown** [comment]
I just submitted a pull request that should fix this.

The issue is that we were casting the LuisService to the abstract interface `ILuisService` instead of the implemented class `LuisService` that actually contains the getEndpoint() function.

We may also want to add `getEndpoint()` to the `ILuisService` definition if it is a required component. I will open a separate ticket for that on the SDK repo.
