### ISSUE TITLE
[netcore][11.qnamaker] Missing files and Readme has wrong instruction

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/BotBuilder-Samples#628]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: 11.qnamaker

## Describe the bug
-  The `qna` resource is missing in `bot.recipe`.
-  The `qna` service is missing in `BotConfiguration.bot`.
-  Step 2 from [**Prerequisites**](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/README.md#prerequisites) in `readme.md` points to import the wrong archive.
-  File `smartLightFAQ.tsv` is missing from directory `\11.qnamaker\CognitiveModels\`.
-  File `34.qna` is missing from directory `\11.qnamaker\deploymentScripts\msbotClone`.

## To Reproduce

1. Follow the [**Prerequisites**](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/README.md#prerequisites) steps from `readme.md` up to step 2.
2. Import `sample.qna` to QnA portal
3. The following message will appear: `The file format is not supported for sample.qna. Incorrect file format. Import operation expects a .tsv file with question, answer, source and metadata fields.`

## Expected behavior
The steps in **Prerequisites** should say to import a `.tsv` file. Said file should be present in the directory `\11.qnamaker\CognitiveModels\`.

After importing the correct file, the Knowledge Base should be updated with the content of the file.

Additionally, following the steps in the `readme.md` the `BotConfiguration.bot` should have the corresponding properties to update with the QnA information.

## Screenshots
This is the error that appears when trying to import the `.qna `to QnA portal.
![image](https://user-images.githubusercontent.com/23645105/46561200-13bffc00-c8cd-11e8-9cbd-d2f5ad0e954f.png)
On the left, the content of the `bot.recipe` from sample `11.qna` (netcore), on the right, the content of the `bot.recipe` taken from the same sample but for JavaScript.
![image](https://user-images.githubusercontent.com/23645105/46561317-7a451a00-c8cd-11e8-9004-ab0389fabfca.png)

[bug]

**Comment by JasonSowers** [comment]
@dfavretto was this fixed in one of your PRs?

**Comment by dfavretto** [comment]
Hi @JasonSowers, we didn't fixed this issue.

However, if you can confirm us that the missing `smartLightFAQ.tsv` file is the same that is used in the [TypeScript 11.qnamaker](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_typescript/11.qnamaker/cognitiveModels/smartLightFAQ.tsv) sample, and the missing `34.qna` file is the same that is used in the [NetCore 20.qna-with-appinsights](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/20.qna-with-appinsights/DeploymentScripts/MsBotClone/34.qna) sample, we can create a PR with the needed changes.
