### ISSUE TITLE
Node.js issue with MessageRoutingBot

### ISSUE THREAD

**Issue by Joombalaya** [Microsoft/BotBuilder-Samples#629]
In the Greetings extension of ComponentDialog in the greeting.js file
when intializeStateStep() is called the WaterfallStepContext is not being defined. as a result the bot fails when it tries to call options. 

```
async initializeStateStep(dc, step) {
        let greetingState = await this.greetingStateAccessor.get(dc.context);
        if (greetingState === undefined) {
            if (step.options && step.options.greetingState) {
                await this.greetingStateAccessor.set(dc.context, step.options.greetingState);
            } else {
                await this.greetingStateAccessor.set(dc.context, new GreetingState());
            }
            await this.userState.saveChanges(dc.context);
        }
        return await step.next();
    }
```

I went ahead and did a console.log of dc (step returned undefined) and got the following:

```
WaterfallStepContext {
  dialogs:
   DialogSet {
     dialogState: null,
     dialogs:
      { profileDialog: [Object],
        namePrompt: [Object],
        cityPrompt: [Object] } },
  context:
   TurnContext {
     _respondedRef: { responded: false },
     _turnState: Map { Symbol(state) => [Object] },
     _onSendActivities: [],
     _onUpdateActivity: [],
     _onDeleteActivity: [],
     _adapter:
      BotFrameworkAdapter {
        middleware: [Object],
        settings: [Object],
        credentials: [Object],
        credentialsProvider: [Object],
        isEmulatingOAuthCards: false,
        turnError: [AsyncFunction] },
     _activity:
      { type: 'message',
        text: 'hello',
        from: [Object],
        locale: 'en-US',
        textFormat: 'plain',
        timestamp: '2018-10-05T20:51:33.185Z',
        channelData: [Object],
        channelId: 'emulator',
        conversation: [Object],
        id: '712db310-c8e0-11e8-9b51-f3b28890b680',
        localTimestamp: '2018-10-05T15:51:33-05:00',
        recipient: [Object],
        serviceUrl: 'http://localhost:52543' } },
  stack: [ { id: 'profileDialog', state: [Object] } ],
  _info:
   { index: 0,
     options: {},
     reason: 'beginCalled',
     result: undefined,
     values: {},
     onNext: [Function: onNext] } }
```

The greetingStateAccessor.get() is also not returning a value back. It's a moot point however because when step.next() is called the program will fail. I checked that the waterfall was being created before it's called. I'm just not sure why it doesn't get a step context

**Comment by Joombalaya** [comment]
So I found out that this issue is fixed if you take out all the dc calls and replace them with step (or vise versa) so the following snippet worked :

```
async initializeStateStep(step) {

        let greetingState = await this.greetingStateAccessor.get(step.context);
        if (greetingState === undefined) {
            if (step.options && step.options.greetingState) {
                await this.greetingStateAccessor.set(step.context, step.options.greetingState);
            } else {
                await this.greetingStateAccessor.set(step.context, new GreetingState());
            }
            await this.userState.saveChanges(step.context);
        }
        return await step.next();
    }
```

Repo probably needs to be corrected

**Comment by Joombalaya** [comment]
Turns out there is a bunch wrong with the greeting.js file because anytime `return await <param>.end() ` gets called it says that it's not a function. And simply returning the value is causing some amusing errors. A sample Dialog:

 

>    "Bot": "Welcome to the message routing bot! Try saying 'hello' to start talking, and use 'help' or 'cancel' at anytime to try interruption and cancellation.",
> 
> "Me": "hello",
> 
> "Bot": "What is your name?",
> 
> "Me": "cancel",
> 
> "Bot": "Ok.  I've cancelled our last activity.",
> 
> "Me": "hello",
> 
> "Bot": "Hello Hello, what city do you live in?",
> 
> "Me": "help",
> 
> "Bot": "Let me try to provide some help.",
> "Bot": "I understand greetings, being asked for help, or being asked to cancel what I am doing.",
> "Bot": "Hello Hello, what city do you live in?",
> 
>  "Me": "cancel",
> 
> "Bot": "Ok.  I've cancelled our last activity.",
> 
> "Me": "hello",
> 
> "Bot": "Hi Hello, from Hello, nice to meet you!",
> 
> 
>

**Comment by Joombalaya** [comment]
I was doing more digging on why the bot error. It seems that when the interrupt function is called in bot.js that it is not removing the waterfalldialog from the stack and so the dialog just continues on even though it's told us that the activity is cancelled.

**Comment by stevengum** [comment]
@stevkan, can you take a run at this and make sure the sample is updated and working? Thanks!
