### ISSUE TITLE
display attachment content

### ISSUE THREAD

**Issue by Sid245439** [Microsoft/BotBuilder-Samples#63]
can I display attachment content if so instead of attachment.contenttype what should I use???
By attachment I mean a audio file

**Comment by willportnoy** [comment]
Attachment.Content or Attachment.ContentURL: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/Attachment.cs#L46

I'd file your issues on https://github.com/Microsoft/BotBuilder/issues for more exposure.
