### ISSUE TITLE
[netcore] BotConfiguration.bot is missing LUIS and QnA service section

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/BotBuilder-Samples#635]
**Is your feature request related to a problem? Please describe.**
The `BotConfiguration.bot` file in samples that use LUIS or QnA services, i.g. [Sample # 11](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/BotConfiguration.bot) and [Sample # 13](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.basic-bot/BotConfiguration.bot), lacks their respective service section.

Following the [Readme.md](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.basic-bot/README.md) causes confussion as it asks to update the field, but both the fields and service sections are missing. 

**Describe the solution you'd like**
The `BotConfiguration.bot` should already have the respective service section for the user to complete. The following is an example for the [Sample 13](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.basic-bot):
```
{
	"type": "luis",
	"id": "235",
	"name": "basic-bot-LUIS",
	"version": "0.1",
	"appId": "",
	"authoringKey": "",
	"subscriptionKey": "",
	"region": ""
}
```

**Describe alternatives you've considered**
An alternative is to guide the user in `Readme.md` to add the service section manually to `BotConfiguration.bot`.

[enhancement]

**Comment by benbrown** [comment]
We'll address this in #653
