### ISSUE TITLE
51. Cafe Bot OnTurnPropert.cs error

### ISSUE THREAD

**Issue by talon2king** [Microsoft/BotBuilder-Samples#636]
## The bug
With the code written as is, line 55 was throwing an error saying that FirstOrDefault is not a method of JToken (Newtonsoft.Json.Linq.JEnumerable<Newtonsoft.Json.Linq.JToken>' does not contain a definition for 'FirstOrDefault'). 

## To Reproduce
1. Execute project
2. Use bot emulator
3. Enter an utterance that has a LUIS entity in it
4. place a line break at line 55 to catch error

## Expected behavior
It gives this error:
Newtonsoft.Json.Linq.JEnumerable<Newtonsoft.Json.Linq.JToken>' does not contain a definition for 'FirstOrDefault'

## Additional context
I was able to fix it with the following code:

value = (from val in (JArray)value
                              select val).FirstOrDefault();

[bug]

**Comment by JasonSowers** [comment]
@talon2king would you like to submit a pull request with this fix?

**Comment by talon2king** [comment]
@JasonSowers Sure thing!

**Comment by JasonSowers** [comment]
Closing this issue as we will continue the conversation in the pull request thread as we review it, thanks!
