### ISSUE TITLE
[Question] deploy a C# to azure

### ISSUE THREAD

**Issue by Sid245439** [Microsoft/BotBuilder-Samples#64]
Guys which document should I refer in order to deply a C# code to azure. Please give the link

**Comment by willportnoy** [comment]
Can you give more context?  This is one example document: https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-dotnet-get-started

You might consider filiing your issue on https://github.com/Microsoft/BotBuilder where it will get more attention.

**Comment by nwhitmont** [comment]
- https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-deploy
- https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview
