### ISSUE TITLE
51.cafe-bot throws on startup

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/BotBuilder-Samples#643]
running `npm start` in 51.cafe-bot fails to startup and throws the following error:

![image](https://user-images.githubusercontent.com/2652885/46634870-46edcf80-cb07-11e8-8a3f-c0ed005fa301.png)

**Comment by sgellock** [comment]
#686 also reports the same issue

**Comment by sgellock** [comment]
I built a clean Win10 image this morning, installed .net core SDK 2.1.403 and node v8.12.0.
 
$>  npm i -g luisgen.                        # installs runs successfully (no errors reported), but luisgen is not available.
 
If I look at where npm installs things, I get the following:
 
C:\Users\scottgellock>dir C:\Users\scottgellock\AppData\Roaming\npm\node_modules\luisgen
Volume in drive C has no label.
Volume Serial Number is E0F2-A9F3
 
Directory of C:\Users\scottgellock\AppData\Roaming\npm\node_modules\luisgen
 
10/12/2018  10:57 AM    <DIR>          .
10/12/2018  10:57 AM    <DIR>          ..
10/26/1985  01:15 AM               566 dotnetpreinstall.js
10/12/2018  10:57 AM             1,494 package.json
09/23/2018  04:44 PM             3,200 readme.md
               3 File(s)          5,260 bytes
               2 Dir(s)  251,343,638,528 bytes free
 
We probably need to push out a fix once we understand what the core issue is.

**Comment by sgellock** [comment]
I am able to verify on a clean Win10 with .net core 2.1.403 that nom install of luisgen works
