### ISSUE TITLE
Project 21 (Luis with AI) BotServices resolution error

### ISSUE THREAD

**Issue by markleavesley** [Microsoft/BotBuilder-Samples#645]
I'm trying to get this sample project for LUIS to work. The bot starts but when I try and use it I get this error:

`Unable to resolve service for type 'Microsoft.BotBuilderSamples.BotServices' while attempting to activate 'Microsoft.BotBuilderSamples.LuisBot'.`

I've changed no code other than setting up LUIS and AI (which was a chore in itself). I've spent hours trying to figure this out out (I'm new to .NET Core) to no avail.

Any direction appreciated.

**Comment by daveta** [comment]
@markleavesley : Can you take a look at:
https://github.com/Microsoft/BotBuilder-Samples/pull/659
This should address the issues you ran into.  Hopefully will be merged in soon.
Thanks
