### ISSUE TITLE
[Feature Request] Non ASP .NET sample?

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/BotBuilder-Samples#65]
Can we have a sample that doesn't use ASP .NET to interact with the bot API etc.? Just something super simple so that we have a distilled example of the bot API calls without the ASP .NET stuff around it.

**Comment by willportnoy** [comment]
There is some unit test code that doesn't require asp.net.  Are you primarily hoping to see the essential aspects of the bot logic?

**Comment by isaacabraham** [comment]
Exactly. Writing a bot, hosting it in a simple console, receiving a message, responding to a message etc.. Can you use the .NET SDK in that way? How would you handle auth? etc.

**Comment by willportnoy** [comment]
@isaacabraham we're doing some work to separate out dependencies on particular versions of asp.net, but in the end, you still need to expose a web endpoint for your bot service.

FormTest (C#) and the ConsoleConnector (node) show how you might interact with your bot through the console.  But often people who want a completely custom client use something like DirectLine.

**Comment by isaacabraham** [comment]
There are several web frameworks on .net, of which ASP .NET. Where things could be improved would be using a bare bones example. Even using OwinHost would be a start, but ideally moving away from the magic attributes etc. would be best so people can write their own bot wrappers.

**Comment by sgellock** [comment]
closed due to inactivity
