### ISSUE TITLE
LUIS custom dimension entity

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder-Samples#66]
I realise this is not exactly related to bot builder but i dont know where else to put LUIS related questions.

What i want to do is define a hierarchical entity with the following template "the car has x doors and y seats"

Now the inbuilt dimension entity is pretty unreliable when it comes to recognizing "x doors" and "y seats" so i want to create my own entities called 'doors' and 'seats' which i can do by highlighting the sample utterance and labeling however LUIS doesn't seem to be able to generalize x and y, so if my sample utterance is 5 doors and 7 seats then it wont recognize 3 doors and 5 seats correctly.

How can i get LUIS to recognize a number followed by a keyword as a single entity where number is variable?

**Comment by chrimc62** [comment]
Create a composite entity between a pre-built number and your description.

**Comment by nwhitmont** [comment]
If you have additional questions, please open a new issue on [BotBuilder](https://github.com/Microsoft/BotBuilder/issues) repo. thx
