### ISSUE TITLE
[nodejs][20.qna-with-appinsights] Missing QnA recipe file

### ISSUE THREAD

**Issue by enzocanoo** [Microsoft/BotBuilder-Samples#662]
## Sample information
1. Sample type: **samples**
2. Sample language: **nodejs**
3. Sample name: **20.qna-with-appinsights**

## Describe the bug
The [`./deploymentScripts/msbotClone`](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/20.qna-with-appinsights/deploymentScripts/msbotClone) folder does not contain the `34.qna` file declared in [`bot.recipe`](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/20.qna-with-appinsights/deploymentScripts/msbotClone/bot.recipe#L12).

## To Reproduce
1. Go to sample folder:
  `cd .\samples\javascript_nodejs\20.qna-with-appinsights`
2. Run the `msbot` script to clone the services required for the bot:
  `msbot clone services -f deploymentScripts/msbotClone -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id>`
3. The script fails doe to a problem with QnA resource.

## Expected behavior
The clone should finish without errors.

## Screenshots
![image](https://user-images.githubusercontent.com/12394167/46735421-97cb0880-cc6c-11e8-8da3-ec3d20cb0cb8.png)

[bug]

**Comment by JasonSowers** [comment]
@enzocanoo was this fixed in one of your PRs?

**Comment by enzocanoo** [comment]
Hi @JasonSowers, this issue wasn't addressed.

If you confirm us that the missing file is the same that is used in the [TypeScript 11.qnamaker](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_typescript/11.qnamaker/deploymentScripts/msbotClone/34.qna) sample, we can create a pull-request with the changes.
