### ISSUE TITLE
V3 Samples documentation issues

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#668]
## The following links need some edits to account for v3 samples changes
1.https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0 references the v3 VSIX template, but doesn't provide a link to download the template.
2. http://aka.ms/bf-bc-vstemplate used to link to the v3 VSIX, but now appears to not point to anything.  We should update this to point to the v4 VSIX

[bug]

**Comment by Kaiqb** [comment]
Fixed both issues. The docs now have a single starting point using ABS for V3. The topic referenced above now redirects users to V4 quickstart.
