### ISSUE TITLE
core-MultiDialogs no Buttons in Emulator

### ISSUE THREAD

**Issue by ap-teammobile** [Microsoft/BotBuilder-Samples#68]
In the preview picture for the emulator of the readme, there are buttons to click (hotels and flights).

When I run the example in the emulator, it is just text. Can't figure out why.
Isn't this Code just sending text?

`            builder.Prompts.choice(
                session,
                'Are you looking for a flight or a hotel?',
                [Flights.Label, Hotels.Label],
                {
                    maxRetries: 3,
                    retryPrompt: 'Not a valid option'
                });`

<img width="1513" alt="bildschirmfoto 2017-02-10 um 14 53 39" src="https://cloud.githubusercontent.com/assets/2803061/22829044/c622c592-efa0-11e6-80ed-1a0a8d077b36.png">

**Comment by pcostantini** [comment]
Hi @ap-teammobile ,
The screenshot must be outdated. If you wish to display buttons instead of a list of items, you'll need to set the `listStyle` of the `promptOptions` to `ListStyle.button`.
E.g.:

````JavaScript
builder.Prompts.choice(
    session,
    'Are you looking for a flight or a hotel?',
    [Flights.Label, Hotels.Label],
    {
        maxRetries: 3,
        retryPrompt: 'Not a valid option',
        listStyle: builder.ListStyle.button
    });
````

**Comment by willportnoy** [comment]
It looks like the question was answered - I'm going to close this issue.
