### ISSUE TITLE
Node.js dice roller bot [50] instructions incomplete and incorrect bonus: buggy default filename in code

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#682]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 50.diceroller-skill

## Describe the bug
1. Steps in the [To try this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/50.diceroller-skill#to-try-this-sample) section still say to use the packages from the nightly builds.
2. The instruction `npm i & npm start` should use a double ampersand, `npm i && npm start`.
3. npm throws an error on starting the bot.

## To Reproduce
1. Follow the steps in the [To try this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/50.diceroller-skill#to-try-this-sample) section, but using the correct package repository and using the correct npm command to start the bot.
4. See error:
```text
Error reading bot file. Please ensure you have valid botFilePath and botFileSecret set for your environment.
{ Error: ENOENT: no such file or directory, stat 'C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\javascript_nodejs\50.diceroller-skill\cortana-skill.bot'
    at Object.fs.statSync (fs.js:948:11)
    at Object.readSync (C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\javascript_nodejs\50.diceroller-skill\node_modules\read-text-file\dist\read-text-file.js:76:19)
    at Function.loadSync (C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\javascript_nodejs\50.diceroller-skill\node_modules\botframework-config\lib\botConfiguration.js:82:30)
    at Object.<anonymous> (C:\Users\v-jofing\source\repos\BotBuilder-Samples\samples\javascript_nodejs\50.diceroller-skill\index.js:34:34)
…
```

## Expected behavior
1. The instructions should be accurate and the non-placeholder filenames should be correct.
1. The instructions should also include steps for updating the placeholder values in the **.env** and code files.
1. There should be a default **.env** file in the project.

## Additional context
The error on line 34 is caused by a value from [line 28](https://github.com/Microsoft/BotBuilder-Samples/blob/89739c630222d978c32fcf505c20bf74bb8a9abc/samples/javascript_nodejs/50.diceroller-skill/index.js#L28)
- The default name here for the bot file is `cortana-skill.bot`; however, the bot file in the project is **diceroller-skill.bot**.
- Creating an **.env** file with the following line lets me start the bot locally without errors.
```text
botFilePath = "diceroller-skill.bot"
```

[bug]

**Comment by JonathanFingold** [comment]
PS. The **New Game** option always goes to the roll dice sequence, no matter which "game" you chose it from.

**Comment by sgellock** [comment]
README.md refers to the myget feed, and needs to pull from nom

**Comment by benbrown** [comment]
This sample has been deprecated.
