### ISSUE TITLE
Luisgen install failed -- broken link

### ISSUE THREAD

**Issue by wiazur** [Microsoft/BotBuilder-Samples#686]
## Sample information
1. Sample type: sample
2. Sample language: dotnetcore
3. Sample name: BotBuilder-Samples

## Describe the bug
When trying to install with `dotnet tool install -g LUISGen` from CLI, it returns an error message.

![luisgen error](https://user-images.githubusercontent.com/38537084/46839714-1d85ab80-cd74-11e8-8984-932d894b1415.PNG)

But then I try to view the Newtonsoft.Json link as mentioned in the console error, it's a 404. So maybe the LUISgen installer needs reconfiguring to direct to the correct link.

A fix is just to go to the [Luisgen](https://www.nuget.org/packages/LUISGen/) package and install it directly.

`dotnet tool install --global LUISGen --version 2.0.0`

[bug]

**Comment by sgellock** [comment]
dup of #643
