### ISSUE TITLE
[Question] Problem with the code...

### ISSUE THREAD

**Issue by Sid245439** [Microsoft/BotBuilder-Samples#69]
Hi ,
I ran this code few days ago it was running fine . But now I dowloaded this code from git and deployed it to azure by changing appid and app password , when I run it now i am getting "Did you upload an audio file? I’m more of an audible person. Try sending me a wav file". 

Please help.

![speech_scrennshot](https://cloud.githubusercontent.com/assets/25339664/22883400/1ebcfcbe-f216-11e6-8456-2f11b2206f2a.PNG)

**Comment by deksden** [comment]
I m not an expert with Speech API & Azure, but:

General tips: Did you try to place some console.log lines into code? No errors? No exceptions? Try to analyze generated logs.

Maybe some APIs require to have registered valid webhook / callback URLs? Maybe, they have localhost registered, but not Azure.

**Comment by nwhitmont** [comment]
@Sid245439 Apologies for the late response. Are you still having issues with the code sample? Are you using .NET or Node SDK? Which sample has the error?

**Comment by sgellock** [comment]
closed due to inactivity
