### ISSUE TITLE
Sample of Translation Text in C#/SDKv4.0

### ISSUE THREAD

**Issue by stofte** [Microsoft/BotBuilder-Samples#698]
There's currently no working code examples of using the Translation Text api i Azure in an C#/Bot Framework 4.0 context. The "multilingual" sample is much too complicated.

**Comment by stofte** [comment]
I'm unsure what the MultiLingualBot should be doing. I assumed it would translate, but it seems to just store my preference?

**Comment by carlosscastro** [comment]
It translates in the middleware, based on your preference chosen. I recommend you to start by reading the readme.md file. Let me know if you have questions!
