### ISSUE TITLE
ConversationUpdate Activity.MembersAdded should check for null 

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/BotBuilder-Samples#705]
## Sample information
Many samples show a welcome message when they receive a conversationUpdate. All these samples potentially have this bug.

## Describe the bug
The code assumes the conversationUpdate is for a new member joining the conversation. If this is the case the membersAdded property will not be null otherwise it might. If it is null the bot will hit a null exception.

## To Reproduce
Send a conversationUpdate Activity to the bit with membersAdded as null. For example a membersRemoved. (In the near future you should be able to use the emulator to do this.)

## Expected behavior
Check for the null.

**Comment by JasonSowers** [comment]
Addressed in #718
