### ISSUE TITLE
Oauth card does not work in Teams/web channel 24.bot-authentication-msgraph

### ISSUE THREAD

**Issue by vasavenk** [Microsoft/BotBuilder-Samples#707]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[Hi, 

I am trying to run 24.bot-authentication-msgraph sample and configure authentication in Teams or Web Chat. I got it working locally using Emulator, however, when I deploy it to Teams the Oauth card button does not work and in web chat it prompts "[File of type 'application/vnd.microsoft.card.oauth']". Is there a specific auth sample for Teams channel? ]

**Comment by JasonSowers** [comment]
In order for teams to open the link you have 2 options.  

The first is a hacky workaround discussed [here](https://github.com/Microsoft/BotBuilder/issues/4768) 

The second is the "right way" to do it.  You must include the token URL as a valid domain in your [manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package) file.  Here is the [schema](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema) for the manifest file. You will have to zip the manifest file with 2 images for the icons.  below is an example of a manifest file I actually use:

```javascript
{
    "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
    "manifestVersion": "1.0",
    "version": "1.0.0",
    "id": "{YOUR BOT APP ID}",
    "packageName": "bot.builder",
    "developer": {
        "name": "jason",
        "websiteUrl": "https://example.com/",
        "privacyUrl": "https://example.com/privacy",
        "termsOfUseUrl": "https://example.com/app-tos"
    },
    "name": {
        "short": "{YOUR BOT NAME}"
    },
    "description": {
        "short": "A Bot",
        "full": "This app displays information."
    },
	 "icons": {
	    "outline": "{SOME IMAGE}.png",
		"color": "{SOME IMAGE}.png"
	 },
    "accentColor": "#0099ff",
    "bots": [
        {
            "botId": "{YOUR BOT APP ID}",
            "isNotificationOnly": false,
            "needsChannelSelector": "true",
            "scopes": [
                "personal",
                "team"
            ]
        }
    ],
  "validDomains": [
     "token.botframework.com"
  ]
}
```

**Comment by JasonSowers** [comment]
@vasavenk did that work for you?

**Comment by arturopolanco** [comment]
Hi @JasonSowers .  I had the same issue and the second option worked for me.  Thanks :)
