### ISSUE TITLE
[netcore][21.luis with appinsights] LuisApplication wrong argument when initializing

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/BotBuilder-Samples#711]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: `21.luis-with-appinsights`

## Describe the bug
In [Line 178](https://github.com/Microsoft/BotBuilder-Samples/blob/995219f8ff8fa4eaf4359c2af8db5fc290a3295c/samples/csharp_dotnetcore/21.luis-with-appinsights/Startup.cs#L178) of `Startup.cs`, a new `LuisApplication` is being initialized. However, the `region` is being used as argument instead of `endpoint`.
This gives as result an exception message saying `{region} is not a valid LUIS endpoint`.

## To Reproduce
1. Go to `samples/csharp_dotnetcore/21.luis-with-appinsights`
2. Configure `BotConfiguration.bot` with the required fields
3. Open the project `LuisBotAppInsights.csproj`
4. Select and run `LuisBotAppInsights` project
5. After trying to interact with the bot, an exception will be thrown saying that the specified region is not a valid LUIS endpoint.

## Expected behavior
The bot should work with the endpoint configured in `BotConfiguration.bot`.

## Screenshots
![image](https://user-images.githubusercontent.com/39467613/46691178-a49f1c00-cbda-11e8-984e-21c534da65de.png)

[bug]

**Comment by t1agob** [comment]
This must be a mismatch in nuget package versions. Im my case, Region property actually returns the full endpoint - which doesn't make much sense to me.

**nuget package version**
Microsoft.Bot.Builder.AI.Luis (v4.0.8)

This is what I see:

![luisregionerror](https://user-images.githubusercontent.com/2689939/47372834-83faba00-d6e2-11e8-93dc-1ecc09123fdc.png)

**Comment by dfavretto** [comment]
This was solved in #673, so I'm closing it.
