### ISSUE TITLE
[Question] Bing spell check mode

### ISSUE THREAD

**Issue by Noc2** [Microsoft/BotBuilder-Samples#72]
The spell checker didn’t work for me until I added the mode:
```
var values = new Dictionary<string, string>
{
{ "text", text },
{ "mode", "spell" }
};
```
Is "spell" the correct mode for Chatbots?

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
