### ISSUE TITLE
Cafe Contoso bot is missing .bot file

### ISSUE THREAD

**Issue by robartz** [Microsoft/BotBuilder-Samples#724]
## Sample information

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/51.cafe-bot2. 
Sample language: dotnetcore3. 
Sample name: cafe bot

## Describe the bug
Can't build due to missing .bot file. Tried to copy a bot file from another project still missing lines.

**Comment by v-kydela** [comment]
The bot file was deleted in this commit: https://github.com/Microsoft/BotBuilder-Samples/commit/06dfb1b074563ef390b837535593f5e45e76eac1#diff-4d152ecef42bc2d4d5726453bbcc4e89

I understand that's because you're supposed to generate the file yourself using the Azure CLI

**Comment by robartz** [comment]
msbot clone services fails during Creating and importing LUIS application. 

The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure App Site Plan                     eastus2             S1                  CafeBot
 Azure AppInsights Service               East US             F0                  CafeBot
 Azure Blob Storage Service              eastus2             Standard_LRS        CafeBot
 Azure Bot Service Registration          Global                                  CafeBot
 Azure LUIS Cognitive Service            eastus2             S0                  CafeBot
 Azure LUIS Cognitive Service            eastus2             S0                  CafeBot
 Azure LUIS Cognitive Service            eastus2             S0                  CafeBot
 Azure QnA Maker Service                 westus              S0                  CafeBot
 Azure Search Service                    eastus2             Standard            CafeBot
 Azure WebApp Service (Bot)              eastus2                                 CafeBot
 Azure WebApp Service (QnA)              eastus2                                 CafeBot
Would you like to perform this operation? [y/n]y
Checking az botservice version
Fetching subscription account
Creating resources in subscription: Internt forbruk på Microsoft Azure 31a7429d-17c4-4831-9ab1-6f817b82e456
Creating Azure group [CafeBot]
Creating Azure Bot Service [CafeBot]
[az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code D2S5UHJM7 to authenticate.

[az bot] obtained msa app id and password. Provisioning bot now.
 (Please be patient, this may take several minutes)
Fetching bot extended information [CafeBot]
Fetching co-created resources [CafeBot]
Fetching bot website appsettings [CafeBot]
Creating LUIS Cognitive Service [CafeBot-LUIS]
Fetching LUIS Keys [CafeBot-LUIS]
Creating site plan [CafeBot]
Creating Azure Search Service [cafebot-search]
Fetching Azure Search Service keys [cafebot-search]
Creating QnA Maker host web service [CafeBot-qnahost]
Configuring QnA Maker host web service settings [CafeBot-qnahost]
Configuring QnA Maker host web service CORS [CafeBot-qnahost]
Creating QnA Maker Cognitive Service [CafeBot-QnAMaker]
Fetching QnA Maker Cognitive Service [CafeBot-QnAMaker]
Creating and importing LUIS application [CafeBot_cafeBotBookTableTurnNModel]
Command failed: luis import application --region westus --appName "CafeBot_cafeBotBookTableTurnNModel" --in DeploymentScripts\msbotClone\95.luis --authoringKey fa33e9f574844b22a412f1c10f07d758 --msbot'luis' is not recognized as operable program or batch file.,

**Comment by joseques** [comment]
Hi @robartz 
Looks like you don't have the `luis` tool installed globally.
If you haven't installed the `luis-apis` package before, you may not have the package installed. The documentation is a bit outdated up to the [Install CLI tools](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/51.cafe-bot#install-cli-tools) the installation command for the CLI tools should be 
```
> npm i -g msbot chatdown ludown luis-apis qnamaker 
```
Since the package for `luis` is called `luis-apis` now.

**Comment by JasonSowers** [comment]
Added bot file in #920
