### ISSUE TITLE
Add Bot PowerBI template to AppSource.

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotBuilder-Samples#726]
**Describe the solution you'd like**
Add our Bot PowerBI template to AppSource.
https://appsource.microsoft.com/en-US/marketplace/apps?product=pbi-solutiontemplates

Currently shipped in our App Insights samples.

For further context, click on https://github.com/daveta/analytics/blob/master/app_insights_for_bots.md and scroll to the bottom to see the reports.

**Comment by vishwacsena** [comment]
Its unclear if appsource is the right place to publish this. We need to get some help from the right team to understand what's possible. Pushing this out to 4.3. 

@yochay; @Kaiqb - would be great if you can help drive. 

@sgellock - FYI

**Comment by Kaiqb** [comment]
@daveta @yochay - what is the status of this one? This is marked for 4.3.

**Comment by yochay** [comment]
@Kaiqb moving this to 4.4 as we have not integrated the AI code from samples into the core SDK.

**Comment by yochay** [comment]
with 4.4 AI is an integral part of the SDK. We are adding the dashboards to the ARM template for creating a new bot. We'll add documentation as needed. Not sure we will push the ARM template to App Source.

**Comment by daveta** [comment]
Re-opening issue, adding Eyal, Ryan and Emelio.

@scheyal : FYI: Ryan has been maintaining a [analytics section in the solutions github, including PowerBI](https://github.com/Microsoft/AI/blob/master/docs/analytics/README.md) which our samples should reference as well.

If we push to AppSource, we might want to keep Ryan in the loop as they periodically update the reports.

**Comment by daveta** [comment]
Actually, closing - Ryan can add if it makes sense, given new focus on dashboards from SDK side.
