### ISSUE TITLE
[nodejs][24.bot-authentication-msgraph] No reply address is registered for the application

### ISSUE THREAD

**Issue by jonathanhotono** [Microsoft/BotBuilder-Samples#756]
It seems that the sample on nodejs authentication to msgraph is not working quite right.

I'm getting message: AADSTS50011: No reply address is registered for the application when registering aad v2

Am I missing a step here? I'm using AADV2 authentication based and followed the tutorial here:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=javascript

I've made sure to enable `Use a sign-in verification code for OAuthCards` option in the emulator.
![image](https://user-images.githubusercontent.com/6864547/47344121-7863bf00-d6f3-11e8-979a-e461b0fe3819.png)

Update: tried on teams and it does the same thing too:
![image](https://user-images.githubusercontent.com/6864547/47346221-5c165100-d6f8-11e8-9f16-5bea80d4f9c6.png)

**Comment by jonathanhotono** [comment]
Update: I tried to use AADV1 and it works fine. Not sure why it doesn't work with AAD V2

**Comment by JasonSowers** [comment]
Did you set your reply URL in your AAD application to `https://token.botframework.com/.auth/web/redirect` like below :

![image](https://user-images.githubusercontent.com/6301037/47534430-327e3680-d86c-11e8-8987-8d6f00ce4926.png)
