### ISSUE TITLE
[nodejs][03.welcome users] won't start - wrong path to bot file

### ISSUE THREAD

**Issue by mehd-io** [Microsoft/BotBuilder-Samples#757]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 03.welcome users

## Describe the bug
Could not start with npm start : 
Error reading bot file. Please ensure you have valid botFilePath and botFileSecret set for your environment.

The path in the .env point to **welcome-user.bot** instead of **welcome-users.bot**

[bug]

**Comment by yochay** [comment]
requires rebase

**Comment by sgellock** [comment]
fixed with PR #916
