### ISSUE TITLE
[netcore][52. enterprise bot] there's no sample code for adding cosmos to .bot file

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/BotBuilder-Samples#760]
If I follow the instructions (which also don't tell me to create a bot file, but that's another issue, and I think yall have seen it in other Issues)

I run the Enterprise Bot (after running msclone and adding my botsecret) and get the following exception
![image](https://user-images.githubusercontent.com/28786161/47385095-a3044680-d6f8-11e8-9f1d-093438e1044a.png)

There are no instructions (at least that I can find) anywhere within docs or GitHub. How do I do this?

Thanks,
Anna

**Comment by amthomas46** [comment]
I was able to get this via trial and error, but then the next service, AppInsights, and then I'm assuming every service after that. I really think there should be some guidance on how to configure this

**Comment by lauren-mills** [comment]
Hi Anna, your .bot file is created as the output of running msbot clone in the directory where the command was run. Were you able to create that .bot file during the clone process?

**Comment by amthomas46** [comment]
Hi Lauren, thanks for your message.

So what appears to be happening, I've tested this twice on a DSVM from scratch, is that the msbot commands / none of the botbuilder-tools commands are able to run unless I run from the directory C:\Users\dsvmuser\AppData\Roaming\npm. So I can run the command, but only from that directory as follows:  

```
C:\Users\dsvmuser\AppData\Roaming\npm>msbot clone services --name "CSAgent" --luisAuthoringKey "mykeyhere" --folder "C:\Users\dsvmuser\Desktop\CSAgent\DeploymentScripts\msbotClone" --location "westus" --verbose
```

Some digging resulted in me finding the CSAgent.bot file in two locations:  
1. within bin/debug of my CSAgent folder
2. within the npm folder (I understand this one)  

So I can move the file to the root of the project directory, but now my issue, unfortunately, is that I'm unable to open the bot in the Emulator (V4 Preview) when it runs. I select "Open Bot" in the V4 Emulator, navigate to the .bot file in my project directory, and then supply my botSecret. I hit submit and it just takes me back to the Welcome page, without opening to bot.  


However, I'm able to access it just fine if I connect to localhost (so not using the bot file) with the V3 emulator.

**Comment by lauren-mills** [comment]
When you installed the CLI tools did you add "-g"? It seems like maybe they aren't installed globally if you can only run them from a specific folder

**Comment by lauren-mills** [comment]
Also, not being able to open the file in the emulator suggests that maybe the file is malformed. Can you try running "msbot secret clear --secret YOUR_BOT_SECRET" and then try again?

**Comment by amthomas46** [comment]
Yes, used -g to install all the tools, here's an example 
![image](https://user-images.githubusercontent.com/28786161/47532687-e92ae880-d865-11e8-877f-3dc9d289fde5.png)

Let me check your second point!

**Comment by lauren-mills** [comment]
For the first one, I'm not sure what could cause that except some issue with your path variable and if possible I would suggest reinstalling nodejs, because it should be able to reset everything. 

For the second, I would try pulling down the latest template from the other issue first. And then if you continue getting the error, check that your appId and password in the .bot file "development" and "production" services matches the appId and password that the bot has configured in the Azure portal.

**Comment by lauren-mills** [comment]
Moving issue to [AI](https://github.com/Microsoft/AI/issues) repo.
