### ISSUE TITLE
Extremely small typo in code for inline attachment in HandlingAttachmentsBot

### ISSUE THREAD

**Issue by JonBing** [Microsoft/BotBuilder-Samples#768]
## Describe the bug
Missing @ before Name string in method GetInlineAttachment.
Causes the '\a' in "Resources\architecture-resize.png" to turn into an alert.

## To Reproduce
1. Run the sample project HandlingAttachmentsBot.
2. Use debugger or Bot Framework Emulator when communicating with bot.
3. Select '1. Inline Attachment' and see the \a turn into \u0007 by inspecting either the debugger value for Name, or the name property for the image in the emulator Inspector.

## Expected behavior
Expect string Name to be "Resources\architecture-resize.png", and not "Resources\u0007rchitecture-resize.png".

## Screenshots
From the source in AttachmentsBot.cs:
![image](https://user-images.githubusercontent.com/12552584/47435184-56764500-d7a4-11e8-9cad-7aa4ea468f24.png)

From the Inspector view in the Bot Framework Emulator:
![image](https://user-images.githubusercontent.com/12552584/47435239-7a398b00-d7a4-11e8-8d84-28746be54939.png)

## Additional context
This is, of course, an extremely small problem, but hopefully it's also extremely easy to fix :)

[bug]

**Comment by v-kydela** [comment]
Would you like to submit a pull request for this?

**Comment by JonBing** [comment]
Sure, I'll just have to find out how to do it first :)
Never done it before.
I'll look into it.
