### ISSUE TITLE
Samples documentation does not reflect new arguments for MSBot Clone Services

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/BotBuilder-Samples#772]
**Is your feature request related to a problem? Please describe.**
MSBot Clone Services autoprovision for ApplicationId was failing (see https://github.com/Microsoft/botbuilder-tools/issues/596). The issue was fixed with a hotfix by adding new parameters to the command line (see https://github.com/Microsoft/botbuilder-tools/pull/639).

The [current readmes](https://github.com/Microsoft/BotBuilder-Samples/tree/5be0364be8614b42469a630e8c7343c96364253e/samples/csharp_dotnetcore/04.simple-prompt#deploy-this-bot-to-azure) do not reflect these changes, they have the following command line to deploy to Azure:
```bash
msbot clone services -f deploymentScripts/msbotClone -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id>
```

**Describe the solution you'd like**
Steps about how to obtain the `AppId` and `AppSecret` from [Application Registration Portal](https://apps.dev.microsoft.com/) should be added to the readme, along with the addition of `--appId` and `--appSecret` to the command line:
```bash
msbot clone services -f deploymentScripts/msbotClone -n <BOT-NAME> -l <Azure-location> --subscriptionId <Azure-subscription-id> --appId "<App-Id>" --appSecret "<App-Secret>"
```
[enhancement]

**Comment by yochay** [comment]
Please submit a pull request.
