### ISSUE TITLE
[Question] Always get a 400 Bad Request response.

### ISSUE THREAD

**Issue by crob1** [Microsoft/BotBuilder-Samples#78]
Hi,

I can't get this code works with the Bot Framework Emulator. I always have a 400 BAD REQUEST response on Conversation.SendAsync(activity, () => new RootLuisDialog()).

I've triple checked my modelId and SuscriptionKey, but no change.

Thanks.

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
