### ISSUE TITLE
Samples that uses generated .bot files points to wrong files

### ISSUE THREAD

**Issue by joseques** [Microsoft/BotBuilder-Samples#788]
## Sample information
Sample name: Any sample that uses a `.bot` file that requires to be generated by `msbot` after #660 

## Describe the bug
The samples, when running them, instructs to open a `.bot` file which filename is hardcoded.

As an example, in NodeJS - 11.qnamaker
In `index.js` [line 79](https://github.com/Microsoft/BotBuilder-Samples/blob/ebcc17cedc5ac252d390e71d1c996307317b2365/samples/javascript_nodejs/11.qnamaker/index.js#L79) the sample instructs to open an inexistent file and potentially wrong if a different name is used when using `msbot clone services`
```javascript
server.listen(process.env.port || process.env.PORT || 3978, function() {
    console.log(`\n${ server.name } listening to ${ server.url }.`);
    console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator.`);
    console.log(`\nTo talk to your bot, open qnamaker.bot file in the emulator.`);
});
```

## To Reproduce 
Steps to reproduce the behavior (with demonstration purpose):
1. Follow instructions for [NodeJS - 11.qnamaker](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker)
1. Run the sample
1. See the message
```
restify listening to http://[::]:3978.
Get Bot Framework Emulator: https://aka.ms/botframework-emulator.
To talk to your bot, open qnamaker.bot file in the emulator.
```

## Proposed Solution
Change the instruction to open the bot to an ideal generic phrase, like
```
To talk yo your bot, open your .bot file in the Emulator
```

An alternative to this would be using the bot filename from the `.env`/`appsettings.json` to instruct the user to open the `.bot` file.

[bug]

**Comment by jwiley84** [comment]
Hi Joe! 

There shouldn't be any .bot file in the samples that require services at all. The team is in the process up updating the READMEs to reflect this fact, as well as putting in instructions on how to create a .bot file. The instructions that show when you run the sample shouldn't even actually show unless you have a correctly named bot file, but I will raise the issue with the appropriate team members.
