### ISSUE TITLE
[Question] Adding a bot as a Team member - (bots in channels) NOT working

### ISSUE THREAD

**Issue by nycodes9** [Microsoft/BotBuilder-Samples#79]
I was successfully able to add(sideload) a 1:1 bot and interact but instruction outlined here recently - [Bots in channels](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd#adding-a-bot-as-a-team-member---bots-in-channels) is not working (the bot doesn't show up for add member in teams)

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
