### ISSUE TITLE
v3 branch results in 404 error

### ISSUE THREAD

**Issue by plzm** [Microsoft/BotBuilder-Samples#810]
Switching to branch v3-sdk-samples just results in a 404 page. Please provide that branch for people still working on bot SDK v3. Thanks.

**Comment by nyxsys** [comment]
Can you post the page where you found the broken url? https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples (reached via the branches dropdown on the main page) still works for me.

**Comment by plzm** [comment]
I'm going to close this issue. I see what happened: between SDK v3 and master (v4), folders containing samples were renamed, e.g. CSharp -> csharp-dotnetcore. So going to https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp and switching to master results in a 404 but this makes sense since the samples switched to .net core.
