### ISSUE TITLE
Typescript Generator and Samples Lack Typing

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#812]
TypeScript samples and the Yeoman generator lack typing. The generator uses require syntax, which implicitly types all imports as any: 
```
const { ActivityTypes } = require('botbuilder');
```
The right Types are not imported, so we end up with untyped code like: 
```
 async onTurn(turnContext) {
```
or
```
  constructor(conversationState) {
```

Any TypeScript developer will be immediately blocked - they'll have to backfill the types (if they can figure out how properties should be typed). Further, most TS developers use strict compiler options and ts lint rules, which would make samples/generators uncompilable. 

I would recommend developing TS samples with strict typing/linting, so that any TS developer can seamlessly get started with samples and templates.

**Comment by sgellock** [comment]
fixed with PR #861
