### ISSUE TITLE
12.nlp-with-luis - BotConfiguration.bot file missing from repo

### ISSUE THREAD

**Issue by mekinney** [Microsoft/BotBuilder-Samples#813]
BotBuilder-Samples/samples/csharp_dotnetcore/12.nlp-with-luis/

## Describe the bug
The BotConfiguration.bot file linked multiple times in the readme is missing.

## To Reproduce
Navigate to:
https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/12.nlp-with-luis/README.md

Click on the BotConfiguration.bot link.

## Expected behavior
The referenced file should be there.

**Comment by joseques** [comment]
Hi @mekinney 
I think that after #653 was issued, the PR #685 got merged removing the `.bot` files to force the generation using `msbot` or with the CLI Tools (instead of modifying it by hand).
Not all of the samples READMEs reflect this change yet.

**Comment by jwiley84** [comment]
Hi @mekinney! 
Joseques is correct, the .bot files were all removed from the sample bots that had connections to services (LUIS, QnAMaker, App Insights, etc). The team is currently in the process of updating the README.md to reflect this fact, as well as outline how to manually create your own .bot file.
