### ISSUE TITLE
TypeScript Yeoman Generator watch script does not watch

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#819]
## Describe the bug
The yeoman generator for TypeScript has a watch script that does not watch: 
```
        "start": "tsc && node ./lib/index.js",
        "watch": "tsc && node ./lib/index.js"
```

## To Reproduce
1. Try running ```npm run watch```

## Expected behavior
1. The bot code should automatically recompile and re-run on changes.

**Comment by cleemullins** [comment]
Thanks Ryan!
