### ISSUE TITLE
01.a.browser-echo doesn't run

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#829]
## Sample information
1. Sample type: samples
2. Sample language: es6
3. Sample name: 01.a.browser-echo

## Describe the bug
This sample doesn't seem to run

## To Reproduce
1. Run ```npm i```
2. Run ```npm start```

## Expected behavior
I expected the sample to be hosted on localhost:8080

## Screenshots
![image](https://user-images.githubusercontent.com/3891951/47875034-9fe11880-ddd2-11e8-974b-b78f0fd3fcab.png)

## Additional context
Sample instructions call for ```npm i && npm start```. Incidentally the '&&' operator doesn't work from cmd line/powershell

[bug]

**Comment by joseques** [comment]
Hi @ryanvolum 
I tried running the sample and it's working fine with NodeJS `v10.10.0`
What version of NodeJS do you have installed on your machine?
This could be a long shot but if you haven't modified the `webChatAdapter.js` script, you are probably trying to run the sample with an incompatible version of NodeJS with the spread operator; It is not completely supported before NodeJS `v5.0.0` (But you can workaround-it using the --harmony flag to enable [ES6 staged features](https://nodejs.org/es/docs/es6/)).

**Comment by ryanvolum** [comment]
Hey @joseques you hit the nail on the head :) I'll go ahead and close this. Thanks!
