### ISSUE TITLE
[Bug] root README.md does not have the latest samples

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder-Samples#841]
## Sample information
1. Sample language: dotnetcore
2. Sample numbers: 40, 42

## Describe the bug
The root README.md does not have the latest samples added to the repo.

[bug]

**Comment by dfavretto** [comment]
@stevengum the sample [30.asp-mvc-bot](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/30.asp-mvc-bot) is missing too, it would be great to add it.

**Comment by johnataylor** [comment]
thanks @vishwacsena just pointed this out to me. expect a PR soon.
