### ISSUE TITLE
The node sample does not match the documentation. 

### ISSUE THREAD

**Issue by vkurpad** [Microsoft/BotBuilder-Samples#847]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by nyxsys** [comment]
Could you please specify which sample has this issue and detail how the readme does not match the sample in the template?

**Comment by nyxsys** [comment]
Please update this issue with details of the problem or it will have to be closed.
