### ISSUE TITLE
Deployment documentation is incomplete

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#875]
The documentation is scattered and only covers a happy path in .NET. There is no explicit deployment documentation that addresses how to deploy a JavaScript or TypeScript bot. Developers need a single document that covers end-to-end deployment in each language. This deployment document should also address the architecture of the deployed solution. As of now the msbot cli tool spins up several resources with little mention of what they do/how they are connected. Developers (especially those new to Azure) will have a hard time justifying the value of these resources without understanding how they work together. To make matters worse, scattered documentation (e.g. README in yeoman generator) is misleading.

[bug]

**Comment by Kaiqb** [comment]
Blocked. Dependent on AZ CLI fixes.

**Comment by sgellock** [comment]
now published live.
