### ISSUE TITLE
[Docs] Deployment docs never mention the .bot file/deployment folder

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#881]
## Describe the bug
These are part of every sample and are still undocumented. If developers need to use a new tool, it needs to be a seamless, well-documented experience. 

## Additional context

[bug]

**Comment by CathyQian** [comment]
I'm investigating this now.

**Comment by Kaiqb** [comment]
@dandev33 - can you take a look at this one?

**Comment by Kaiqb** [comment]
Blocked on az cli fix.

**Comment by sgellock** [comment]
Track to a PR that fixes this by Wed, the 21st

**Comment by Kaiqb** [comment]
Blocked. This issue has a dependency on [issue# 814](https://github.com/Microsoft/botbuilder-tools/issues/814), because MSBot Clone does not seem to work.

**Comment by Kaiqb** [comment]
This was addressed released in December.
