### ISSUE TITLE
[Docs] How-To/Develop needs an article on using state to prompt users

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#882]
## Describe the bug
Using state to prompt users is core to understanding BBV4, how prompting/conversation modeling abstractions work, and explains how the Dialogs API is structured and how it works. Without understanding this core concept, developers are confused about how conversation modeling works.

## Additional context
Here is the link to the docs
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp

[bug]

**Comment by JonathanFingold** [comment]
This was covered in the overly complex version of the primitive prompts topic. It will get covered as part of rewriting the topic (re: issue #884 ).
