### ISSUE TITLE
[Docs] How-To/Develop/"Create you own prompts" sample doesn't run

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#883]
## Describe the bug
Docs/How-To/Develop/"Create you own prompts" sample code doesn't run, doesn't link to sample that does, sample is different.  Sample code should be easy to run and be the same as what is presented in doc.

## Additional context
Here are the links in the docs:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/04.simple-prompt/bot.js

[bug]

**Comment by Kaiqb** [comment]
[Create your own prompt to gather user input](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp) updated to include simpler code that works and a sample has been added to the doc's sample repo also.
