### ISSUE TITLE
[Docs] How-To/Develop/"Create you own prompts" sample code is overly complex

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#884]
## Describe the bug
Sample should simply cover asking for name/age using Conversation State. 

## Additional context
Link to the docs:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp

Sample should simply cover asking for name/age using Conversation State.

                 // Determine which fields are not yet set.
                 const empty_fields = [];
                 Object.keys(fields).forEach(function(key) {
                    if (!userProfile[key]) {
                        empty_fields.push({
                           key: key,
                           prompt: fields[key]
                        });
                     }
                 }); 

[bug]

**Comment by JonathanFingold** [comment]
Need to include the following in the updated topic (lifted from #882 ):

> Using state to prompt users is core to understanding BBV4, how prompting/conversation modeling abstractions work, and explains how the Dialogs API is structured and how it works. Without understanding this core concept, developers are confused about how conversation modeling works.

**Comment by sgellock** [comment]
@JonathanFingold @Kaiqb are we closing this because it's a dup?

**Comment by JonathanFingold** [comment]
I closed #882 as a dup of this one.

**Comment by Kaiqb** [comment]
[Create your own prompt to gather user input](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp) updated to include simpler code and a sample has been added to the doc's sample repo.
