### ISSUE TITLE
[Docs] /How-To/Develop/"Use dialog library to gather user input" badly named, incomplete code

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#885]
## Describe the bug
Docs/How-To/Develop/"Use dialog library to gather user input" is badly named, has incomplete code samples, poorly organized

## Additional context
Link to the doc
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript#prompt-the-user

This document has a number of issues that blocks understanding/adoption of Prompts and Dialogs, including:
•	The doc is about prompting using Prompts, but is titled “Use dialog library to gather user input”.
•	The doc introduces/links to Dialogs docs, which is required to understand this doc/Prompts.
o	If knowledge of Dialogs is required, why isn’t that doc organized first?
•	The “Prompt the user” sample code starts with a scenario asking for name/place of work.
o	https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript#prompt-the-user
o	There are no details on how to run that sample or what it should do.
•	The “Specify prompt options” switches to a different scenario (party size of reservation) rather than building on prior sample code (ask your age to show number prompt).
o	https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript#specify-prompt-options
o	There are no details on how to run that sample or what it should do.
o	The concepts of prompt and retry are not explained.
•	The article links to samples for more examples of Prompts, but rather than linking to a specific example, just links to the root, leaving the user to hunt for what they are looking for.
[bug]

**Comment by Kaiqb** [comment]
Changed the order of the topics and renamed prompt topic to make it clear.
