### ISSUE TITLE
EchoBot sample is far too complicated as the introductory sample

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#888]
## Describe the bug
EchoBot sample is far too complicated as the introductory sample.  The EchoBot sample introduces state management and error-handling, making it difficult to separate signal from noise. 

## Additional context
This change will need to be reflected in the following areas:
- VSIX for C#
- yeoman for NodeJS & TypeScript
- Sample:  all languages

[bug]

**Comment by cleemullins** [comment]
Note that #943 introduces an "Empty Bot" which is just Hello World with none of the bells and whistles (no state, no logging, hardcoded .bot file name, etc). This may be a suitable replacement for the "Getting Started" bot.
