### ISSUE TITLE
[Docs] No parallel is made between state in web apps  (e.g. session state) and state in bots

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#894]
## Describe the bug
The documentation for bot state leads developers to believe that state management in bots may somehow be signficantly different from state management they're used to working with in other web application paradigms when, in fact, it's really not that dissimilar at all. User/Conversation state are presented as someplace to store data for the app. User/Conversation state should only be usd to a) tie the user back to the user in App Data and b) manage the conversation, everything else should be in App Data.

## Additional context
Link to docs:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp

In general, the documentation around state management tends to be very focused on discussing the specifics of its APIs rather than the higher level concepts. State management in a bot is not really all that different than state management in traditional, modern day web applications. People are used to maintaining state for users based on individual identifiers (e.g. session state, etc). Therefore, the core state management documentation would benefit by starting off with a small discussion around state management in web applications and then moving from there into how the state management abstractions the bot framework provides help solve this problem for bots more specifically.

[bug]

**Comment by johnataylor** [comment]
The following article has a discussion of how the Activity exchange relates to storage.

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0

This article touches on the semantics and how it can _sometimes_ be brought into a similar pattern to the classic web application. It then goes deeper and illustrates how _sometimes_ the HTTP eTag behavior often used on web applications can be leveraged by a custom storage solution to provide scale out in a manner you might expect from a web application.

However, there are significant differences between the bot Activity protocol and a regular web application, most significantly the bot Activity exchange is not request/reply. In fact it is two (generally) correlated HTTP connections running in opposite directions. Also of note is the scope of the activity id, the uniqueness of which is dependent on the channel being used, for example, direct line provides unique ids, other channels not necessarily. A web application would often have more control of the scope of critical ids like this.

How about we review the docs in the above link and the accompanying sample and then determine if we are still missing material?

**Comment by Kaiqb** [comment]
In the [Managing state](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0) we now mention the how web apps and bot are similar when it comes to state.
