### ISSUE TITLE
[Docs] State management documentation should be separated from Dialogs

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#898]
## Describe the bug
State management documentation should be separated from Dialogs

## Additional context
Currently the state management documentation is under a section called Concepts / Dialog State. The first two paragraphs, which are single sentences each, mention dialogs, but the reset of the documentation is actually about the core state management feature.

As a developer who is trying to learn the basic details about how to manage state in my bot I am going to start going through the documentation looking for something about state management. Currently all the documentation for state management is under a section called Concepts / Dialog State which, personally, I would expect to contain details about managing state when using the Dialogs API specifically.

I would highly recommend the following:
 * Rename the current article to just "Managing State"
 * Move this article up so it's the second topic under "Concepts" (right under "How bots work")
 * Move any Dialogs specific details over to the "Dialogs Library" article under a header tentatively called just "Managing State in Dialogs". I would also go into far more detail about managing state in dialogs specifically because it is abstracted and much more constrained than the core state management APIs.
 * Consider adding a link under a "Additional Resources" section at the end of "Managing State" that links to the Dialog state section and vice versa.

[bug]

**Comment by Kaiqb** [comment]
Based on the suggestions, we've added a [Managing state](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0) topic, and Updated [Dialogs library](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0) topic to include dialog specific state content.
