### ISSUE TITLE
[Question] Add an Image to a button

### ISSUE THREAD

**Issue by iseltula** [Microsoft/BotBuilder-Samples#90]
Hi, I am trying to use CardAction to add a button with an image in it. I was reading through the documentation and I did what it says there, but it is still not working.

`builder.CardAction.openUrl(session,"", "Go to Link").image("http://www.clker.com/cliparts/Y/w/d/M/s/y/call-icon-hi.png")`

Am I doing anything wrong?
Also. Is there any way to use icons in the text like glyph icons or font awesome icons?

**Comment by mgbennet** [comment]
So, currently images on CardActions are supported by a very limited pool of channels. I think only Facebook Quick Replies supports it right now. You can of course add images as a CardImage to a card, but that's not the same functionality.

I don't believe you can change the font to use glyph icons, but you can add Unicode symbols in the usual ways, which might work for you.

**Comment by nwhitmont** [comment]
If you still have questions, please open a new issue on BotBuilder repo here: https://github.com/Microsoft/BotBuilder
