### ISSUE TITLE
Yeoman generated echobot "watch" script does not watch

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#901]
## Describe the bug
NPM script in generated projects has a watch command.  that command doesn't actually watch for files changes in the typescript generated projects.

## Additional context
There is a PR issued & merged that fixed the echo template.  The PR did not fix the same bug in the  basic template:
https://github.com/Microsoft/BotBuilder-Samples/pull/820

[bug]

**Comment by cleemullins** [comment]
This is related to, and perhaps fixed by, PR #820. The solution(s) is probably the same.

**Comment by sgellock** [comment]
This only fixed some of the places that needed fixing.  It’s not a complete fix for all samples.

**Comment by sgellock** [comment]
PR #949 fixes the remaining TS samples that have a broken watch script
