### ISSUE TITLE
Many samples lack .bot files 

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#903]
## Describe the bug
Many samples lack .bot files 

## Additional context
README docs for samples refer to .bot files that aren't in the actual sample

We need to address the Emulator's ability to talk to bots without the need for a bot file.  If we do that work, then we can make a call as to when in the samples flow we introduce .BOT files.

When we land this, there will be doc impact

[bug]

**Comment by DanDev33** [comment]
I think this can be mitigated by explaining the Emulator option "create a new bot configuration." This includes showing how you find UserName/Password when the bot was generated in Azure. I have had to manually walk folks in India through this process. Once they "got it" they were unstuck and could debug their bots.

**Comment by sgellock** [comment]
relates to:  #912 and #913

**Comment by toddpenland** [comment]
I was struggling with the exact same issue. I didn't realize even realize you could use the emulator to create a bot configuration, so thanks for mentioning it DanDev33. It would helpful to understand when you don't need a .bot file, but where you do it would be great if there was either a .bot in the sample project or some discussion (or link) of how to create one in the readme.

**Comment by sgellock** [comment]
@toddpenland thanks for the feedback.  our plan is to add documentation that addresses the purpose and use of .bot files.  some of that will come in how we address #881 plus we also plan to write some specifics about the file and it's use

**Comment by Kaiqb** [comment]
A topic that covers bot file is now in the concepts section of the docs. You can find it here: https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0. 

Note that there is a separate issue around adding .bot file to samples.

**Comment by JasonSowers** [comment]
Added bot files in #920
