### ISSUE TITLE
Add "Click to run emulator" to samples (protocol handler)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotBuilder-Samples#911]
If we add a button to the HTML in the samples, the "click" can launch the emulator. This does require the emulator to be installed. 

For example, the HTML below, will launch the emulator with the bot file:

```
<div class="content-title">Your bot is ready! 
    <a href="bfemulator://bot.open?path=C%3a%5ctemp%5cPublishTesting%5cechobot-with-counter.bot">Click Me</a>
</div>

```
The Path (seems) to need to be URL encoded, but this could be easily set with Javascript.

**Comment by sgellock** [comment]
Colonel-major, I'm closing this as we've been carrying it for a while and I'm not sure we'll get to it any time soon
