### ISSUE TITLE
13.basic-bot for node does not have a .bot file

### ISSUE THREAD

**Issue by wiazur** [Microsoft/BotBuilder-Samples#919]
## Sample information
1. Sample type: sample
2. Sample language: JavaScript/Node.js
3. Sample name: 13.basic-bot

## Describe the bug
The instructions in the Readme say to open the `basic-bot.bot` file in the Emulator, but there is no .bot file.

**Instructions:**
![missing bot file](https://user-images.githubusercontent.com/38537084/48442085-ff7be400-e741-11e8-9278-db721a2576e2.PNG)

**Folder structure:**
![folder structure](https://user-images.githubusercontent.com/38537084/48442163-3fdb6200-e742-11e8-8013-2e63b196d16a.PNG)

**Comment by cleemullins** [comment]
@sgellock It looks like you missed this sample in PR #916. 

The [Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/13.basic-bot) is indeed still missing the .bot file.

**Comment by DavideDelVecchio** [comment]
Seems that all bots in samples  for node with index > 10 are missing the .bot file

**Comment by sgellock** [comment]
@JasonSowers once #920 is merged, can you resolve this Issue?  thanks
