### ISSUE TITLE
[Question] Contoso Flowers sample does not show a welcome message on skype

### ISSUE THREAD

**Issue by TessFerrandez** [Microsoft/BotBuilder-Samples#92]
It shows up just fine in the emulator but the bot is quiet in skype and facebook until the user says something

**Comment by nwhitmont** [comment]
@TessFerrandez Are you using .NET or Node SDK sample code?

**Comment by TessFerrandez** [comment]
The .net sample

Hämta Outlook för iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by EricDahlvang** [comment]
The sample is responding to [ConversationUpdate](https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/CSharp/demo-ContosoFlowers/ContosoFlowers/Controllers/MessagesController.cs#L59) This ActivityType is not sent by Skype.  ContactRelationUpdate should be used to send a welcome message on the Skype channel.
