### ISSUE TITLE
Broken links caused by non-standard casing of file names

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder-Samples#924]
Our samples have files with inconsistent casing. Such as:

1. README.md
2. readme.md
3. DEPLOY.md

This is causing issues with the Markdown on case-sensitive file systems (Mac, Linux), resulting in PR's such as #921.

We need to standardize the .md files as all lower case.

**Comment by sgellock** [comment]
@cleemullins the model is to use CAPITAL.md for markdown files.  I'd like to follow what the viscose team is doing, which is this model.
