### ISSUE TITLE
51.cafe-bot does not have a .bot file

### ISSUE THREAD

**Issue by damadei** [Microsoft/BotBuilder-Samples#931]
## Sample information
1. Sample type: [\samples\ or \solutions\]
51.cafe-bot

2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
dotnet core

3. Sample name: 51.cafe-bot

## Describe the bug
Sample does not have a .bot file

[bug]

**Comment by JasonSowers** [comment]
Added bot file in #920
