### ISSUE TITLE
[boframework v4][kudu] Access to the path 'D:\home\site\artifacts\manifest' is denied.

### ISSUE THREAD

**Issue by sumithsudesan** [Microsoft/BotBuilder-Samples#936]
## Sample information
1. Sample type: sample
2. Sample language: dotnetcore
3. Sample name: UmisBotServiceApp

## Describe the bug
build operation failed with error "Access to the path 'D:\home\site\artifacts\manifest' is denied."

## Steps to reproduce
1. created web chat bot
2. modified the .bot file (online visual studio editor)
3. execute 'd:\home\site\wwwroot\build.cmd' in kudu console

## Expected behavior
The build should be successful

## Screenshots
![issue](https://user-images.githubusercontent.com/20800082/48538072-73042980-e8d9-11e8-9aeb-9f178c3a1984.PNG)

[bug]

**Comment by jwiley84** [comment]
Hi @sumithsudesan! What in the .bot file are you modifying?

**Comment by sumithsudesan** [comment]
> Hi @sumithsudesan! What in the .bot file are you modifying?
bot file in 'site\wwwroot' folder.
added luis and qna configurations

**Comment by vishwacsena** [comment]
@jwiley84 - @sgellock has additional context here. when able can you connect with him so we can figure out a plan to get the customer unblocked?
