### ISSUE TITLE
JS card sample makes no mention of carousels 

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#939]
**Is your feature request related to a problem? Please describe.**
Carousels are one of the most useful forms of media in bot development, but make no appearance in the [JS card sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/06.using-cards/bot.js).

**Describe the solution you'd like**
Sample(s) should highlight the ability to create carousels using the ```MessageFactory```, as with:
```
const carousel = MessageFactory.carousel(attachments);
await context.sendActivity(carousel);
```

**Describe alternatives you've considered**
Carousels are [documented in the Azure Bot Service docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp#send-a-carousel-of-cards), but finding it (or even knowing that they exist) requires extensive digging. 

[enhancement]

**Comment by JasonSowers** [comment]
added carousel to node sample in #946
