### ISSUE TITLE
[01.a.browser-echo] Does Not Receive conversationUpdate Activity. 

### ISSUE THREAD

**Issue by Joll59** [Microsoft/BotBuilder-Samples#945]
## Sample information
1. Sample type: Sample
2. Sample language: JS
3. Sample name: 01.a.browser-echo

## Describe the bug
Can not greet incoming users using the current in-browser set-up. 

## Speculation 
there is no `conversationUpdate` activity sent, which is expected based on the samples for greeting the user. 

## To Reproduce
1. Clone Sample repo
2. Create Logic for Greeting user.
3. Nothing (Which is the error).

## Expected behavior
Ability to greet a user on bot start. 

Maybe related: #944 
[bug]

**Comment by stevengum** [comment]
Yomi, I read up on #944 (Now Microsoft/BotFramework-WebChat#1371) and they're different issues as this sample has the bot and WebChatdirectly connected. Ryan's issue occurs when the bot is sending messages through the Connector to a WebChat instance. I've filed PR #1098 which should address this specific issue (#945).
