### ISSUE TITLE
[nodejs][12.nlp-with-luis] Authorization error

### ISSUE THREAD

**Issue by rsweetland** [Microsoft/BotBuilder-Samples#947]
## Describe the bug
Following [readme](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/12.nlp-with-luis) instructions (including double-verifying all credentials) still results in authorization errors. 

Possibly related, the below line in the readme conflicts with the page it links to, which shows both authoringKey and subscriptionKey. I tried all combinations without result.
> The Version is listed on the page. Note: Enter the either "authoringKey" OR "subscriptionKey", not both. [See an example .bot service configuration for using LUIS here.](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=js#configure-your-bot-to-use-your-luis-app)

Resulting config: 

```javascript
{
    "type": "luis",
    "name": "BOT_CENTRAL", // matches LUIS_CONFIGURATION in index.js
    "appId": "[redacted]", 
    "version": "0.1", //matches version number on luis.ai
    "authoringKey": "[redacted]",
    "subscriptionKey": "[redacted]",
    "region": "westus",  // matches region in luis.ai
    "id": "83"
}
```

## To Reproduce
1. Follow instructions in [readme](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/12.nlp-with-luis) (including prerequisites)
2. `npm start`
3. Connect emulator, bot starts
4. Type "Add Event"  in emulator
5. Observe the following error in console: 
```
[onTurnError]: Error: Response 401: The key used is invalid, malformed, empty, or doesn't match the region.
BotFrameworkAdapter.processActivity(): 500 ERROR - TypeError: this.addUserAgentInfo is not a function
(node:73552) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: TypeError: this.addUserAgentInfo is not a function
```

And this error in the emulator: 
```
"\"TypeError: this.addUserAgentInfo is not a function\""
```

## Additional context
`nlp-with-luis` version from package.json is `1.0.0`
I'm running Node v8.9.1

[bug]

**Comment by sgellock** [comment]
There are two issues called out in this Issue.:  one of the issues pertains to LUIS creds, the other issue is why the onTurnError handler is firing with a TypeError.

I submitted PR #948 to add some additional clarity to the sample's README, specifically pertaining to LUIS setup.  That said, I am able to create a LUIS app, import the language file (.json), train and publish the model, and use the key and region data found on the Luis.ai `Keys and Endpoint` page to update the .bot file.  Once I do the above steps, and address the second issue, see below, I am able to run the sample successfully.

For the second issue, the TypeError, there is a temporary workaround that will fix the TypeError.  Perform the following commands from a shell console:
```bash
$ cd 12.nlp-with-luis
$ npm install
$ npm uninstall ms-rest-js ms-rest-azure-js
$ npm i ms-rest-js@1.0.455 ms-rest-azure-js@1.0.176
```

The TypeError is a result of a breaking change introduced by a dependent component we us in the SDK.  We''ve logged an issue against that team to fix there breaking change.  That can be tracked here:
https://github.com/Azure/ms-rest-js/issues/276.

The PR https://github.com/Microsoft/botbuilder-js/pull/644 will address the issue in the SDK, until the above Issue is resolved. 

We will publish new SDK bits that will lock to a previous (unbroken) version of that dependency.  ETA for that is tracking to Monday of this coming week. 

@rsweetland, I'm adding the support team to the issue.  They can help you further if my above data doesn't fully get you up and running

**Comment by rsweetland** [comment]
Solved! Thanks for answering and pushing a fix so quickly. 

The additional steps added to the readme (train + publish on luis.ai) were my missing steps. It would be nice if Luis's error message suggested that. For example: 

```
Error: Response 401: The key used is invalid, malformed, empty, doesn't match the region or your model has not yet been published.
```

I also tested with an invalid key and confirmed the type error is not happening.

**Comment by sgellock** [comment]
Thanks for the feedback on the improved error message.  We're not able to provide a better error message as there isn't an api we can use to detect the scenario.
