### ISSUE TITLE
Deployed bot created via File -> New project -> VSIX template fails to run in Azure

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#955]
## Tool
Name: VSIX
Version: 4.0.6
OS: Windows

## Describe the bug
Deployed bot created via File -> New project -> VSIX template fails to run when published to AppService due to missing "production" endpoint configuration in .bot file

## Additional context
Both the Echo and the Basic bot VSIX templates include a .bot file along with startup code that attempts to load this file and confirm proper configuration for the target host environment, however the documentation for deploying bots makes no mention of this file and what to do with it resulting in a non-functional app once deployed.

[bug]

**Comment by sgellock** [comment]
We plan to have this addressed, with an updated VSIX template published no later than 12/15

**Comment by cleemullins** [comment]
This has been (mostly) resolved, with more improvements coming. The latest VSIX has been published to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4). 

This will get better (significantly) once the [configuration validation code](https://github.com/Microsoft/botbuilder-dotnet/pull/1214) is merged in and integrated. That code will validate, as part of the Visual Studio publish process, that the .bot file is properly setup. 

In the immediate term, the "production" endpoint is now part of the .bot file, and needs to be filled out by the developer.

**Comment by cleemullins** [comment]
We've turned the crank of the VSIX files in 4.2, and will do so again in 4.3. Pushing this to 4.3, as the root problems are not yet resolved.

**Comment by jengstro2** [comment]
Is this the same not-so-nice experience what I had after renaming the sample project file from BasicBot -> WhatEveryIWant (csproj). After renaming the sample project -> publish -> nothing happens / freezes over. Local debug environment works. Is there some nice dependencies on those Azure deployment files -> towards the BasicBot.DLL name?

**Comment by gabog** [comment]
Closing, we are moving the infrasctructure deployments to ARM templates.
