### ISSUE TITLE
Instantiating DialogSet in bot constructor should be considered an anti-pattern

### ISSUE THREAD

**Issue by drub0y** [microsoft/BotBuilder-Samples#972]
## Sample information
1. Sample type: /samples **AND** VSIX templates
2. Sample language: dotnetcore/webapi
3. Sample name: BasicBot (and many others)

## Describe the bug
The Dialogs API is designed in such a way that you build out the structure of a conversation using a container called a `DialogSet` and then add _N_ `Dialog` subtypes to it. In C# this currently involves instantiating new instances of all the `Dialog` types "up front" as a singleton and manually supplying any dependencies to those `Dialog` instances via constructor. At the same time, the ASP.NET integration APIs around `IBot` are configured by default to instantiate the type and inject it with any of its dependencies using DI on *each turn* (e.g. as a transient). 

Right now the C# samples and VSIX templates seem to have followed the same pattern as JS/TS where the `DialogsSet` and the _N_ `Dialogs` are built out in the constructor of the `IBot` subtype. The difference tho is that, in the JS/TS samples/templates, the bot itself is also treated as a singleton and, thus, the work to build the `DialogSet` is also only run once and then maintained as a singleton. 

The biggest problem here is the amount of memory that is going to be allocated on every single turn and, thus, have to be garbage collected (GC'd). This will create memory pressure resulting in GC pauses and ultimately degrade the performance of a bot application that follows this anti-pattern. 

Think of it like this: imagine if in ASP.NET every single controller class was instantiated and all depdnencies resolved for every single HTTP request rather than just the controller that is known to map to the incoming request's route.

## To Reproduce
N/A

## Expected behavior
Recommend guiding people towards a pattern where they create the DialogSet once as a lazy singleton. This can be accomplished several ways, but here are a couple suggestions:

    1) Inline in Startup::ConfigureServices
        1a) Directly "inline" with a call to `services.AddSingleton(sp => new DialogSet().Add(...).Add(...))` 
         1b) Semi-inline, factored into a helper method for cleaner encapsulation of `DialogSet` creation as `services.AddSingleton(MyDialogInitializationMethod)`
         In both of these cases the callback can resolve any necessary dependencies from the `IServiceProvider` manually.
     2) As custom `DialogSet` subclasses where the logic is completely encapsulated inside the constructor of that subclass. Also, this subclass can clearly call for any dependencies which the dialogs might need via its constructor and then these can be resolved automatically by DI rather than manually resolving them from the `IServiceProvider` as in option 1a/b.

## Additional context
I have been prototyping some work for a DCR that I intend to submit soon that solves these problems and more by introducing both rich configuration APIs as well as factory semantics around `Dialog` instances which will enable just-in-time, transient instantiation of dialogs allowing for DI backed factory implementations while simultaneously maintaining backwards compatibility with existing `DialogSet` API for the early adopters. [You can check that out here if interested](https://github.com/Microsoft/botbuilder-dotnet/tree/drmarsh/dcr/better-dialogs-integration).

[bug]

**Comment by benbrown** [comment]
Acknowledged! Thanks for the feedback, and we'll work on a solution to this.
