### ISSUE TITLE
Sample: 01.a.browser-echo fails to run

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotBuilder-Samples#979]
## Sample information
**javascript_es6/01.a.browser-echo**

## Describe the bug
The bot fails to run when you follow the instructions in the readme file. 

## To Reproduce
1. Run the bot using **npm i && npm start**.
2. You'll get **ERROR in ./src/webChatAdapter.js** message.

## Screenshots
See attached screenshot for error information.
![browser](https://user-images.githubusercontent.com/29185255/49047750-4a0f4e80-f18d-11e8-822a-71348bcc4775.png)

[bug]

**Comment by sgellock** [comment]
Sample doesn't build.  bumping to 4.2, P0
