### ISSUE TITLE
Watch script in generators and samples errors on first run 

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotBuilder-Samples#980]
## Sample information
1. Sample type: TypeScript Samples/generators
2. Sample language: TypeScript
3. Sample name: TypeScript Samples/generators

## Describe the bug
The watch script in the TS samples/generators has a race condition - it tries to run compiled code before it's fully compiled. This means that on first run (before anything has ever been compiled), it throws a cryptic error. It then runs successfully once the code _has_ compiled, but the error is likely confusing to new devs. 

## To Reproduce
1. Run yeoman generator for echobot 
2. Run ```npm run watch```
3. Observe the error:

![image](https://user-images.githubusercontent.com/3891951/49047944-e9344600-f18d-11e8-912f-d662c4bcb379.png)

## Expected behavior
The bot should compile and run code. It should not throw errors on first compile. It should recompile whenever changes are made. 

## Additional context
Having contributed the concurrently code, I've got a fix in mind. I'll issue a PR to fix all samples/generators shortly. 

[bug]

**Comment by ryanvolum** [comment]
It turns out that we can resolve this race condition by pointing nodemon at our typescript files and running the existing ```npm run start``` script whenever they've changed: 

![image](https://user-images.githubusercontent.com/3891951/49048199-c48c9e00-f18e-11e8-94f7-850f2e829092.png)

This removes the dependency on ```concurrently``` and instead relies on ```nodemon```, which the JS samples/generators are already using.

**Comment by sgellock** [comment]
fixed by PR #1000
