### ISSUE TITLE
generator-botbuilder v4.0.11 or 4.1.0 ?

### ISSUE THREAD

**Issue by alundiak** [Microsoft/BotBuilder-Samples#984]
when?
cc/ @daveta ; @JasonSowers ; @dfavretto

**Comment by benbrown** [comment]
The generators are going to be refreshed in the next few weeks.

**Comment by alundiak** [comment]
I see package.json contains 4.2.0 but here 
https://www.npmjs.com/package/generator-botbuilder?activeTab=readme
no new version.
