### ISSUE TITLE
[.net-core][22.conversation-history] Calling GetTranscriptActivitiesAsync results in infinite loop

### ISSUE THREAD

**Issue by progutskyi** [Microsoft/BotBuilder-Samples#990]
## Describe the bug
Calling **GetTranscriptActivitiesAsync** without supplying **continuationToken** to the methods results in endless loop.

## Steps to reproduce
1. Run the sample
2. Chat with bot for a while to have paged result. Enter about 20-30 messages
3. type !history in the window

## Expected result
Algorithm collects activities and sends transcript

## Actual result
Infinite loop

## The cause of the bug

The call to transcript store is

```csharp
var pagedTranscript = await _transcriptStore.GetTranscriptActivitiesAsync(activity.ChannelId, activity.Conversation.Id);
```

But should be:
```csharp
var pagedTranscript = await _transcriptStore.GetTranscriptActivitiesAsync(activity.ChannelId, activity.Conversation.Id, continuationToken);
```

Whithout passing the continuation token in it never resets to null

**Comment by progutskyi** [comment]
Disregard that, I checked sample, and it works.

I've experienced this issue on my own code, and for now I can't tell why in my case there is an infinite loop.

**Comment by ckkashyap** [comment]
Thanks @progutskyi  for reporting this and suggesting the fix.
