### ISSUE TITLE
Customizing the webchat

### ISSUE THREAD

**Issue by hemachowdary** [Microsoft/BotBuilder-Samples#994]
🚨 The issue tracker is not for questions 🚨
Hi team, 
I am currently using sdk4 nodejs  for developing a chatbot. I am referring to sample [here ](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_es6/70.styling-webchat)for styling the webchat. I noticed that styling is also different in v3 and v4.  In the sample it is referring to the preview mode of botchat.js file `<script type="text/javascript" src="https://cdn.botframework.com/botframework-webchat/preview/botchat.js"></script>` Is it okay to refer to that file. I need to clarify the below points:
1. I am getting some black space as soon as I load the bot . Can we eliminate that space? attaching the screenshot for reference.
![landingpage](https://user-images.githubusercontent.com/2978192/49273950-a8de0c00-f49c-11e8-82f9-31cfc5d66cd6.png)
2. How can I  add a header for my bot.
3. I am able to add initals to bot and user avatars using `botAvatarInitials: 'BOT',
        userAvatarInitials: 'ME'`. how can I add an image instead of having initials.
4. Also whenever you add some new functionality for styling please add comments 
5. Does bot supports only the stylings mentioned [here ](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleSetOptions.js)as of now?

**Comment by jwiley84** [comment]
This particular repo is for submitting **bug fixes** and **feature requests** to the various samples. You'll get better traction on this in the BotFramework-WebChat repo [HERE](https://github.com/Microsoft/BotFramework-WebChat), as that is the source of the styling for the core (webchat and directline) channels. Closing this.
