### ISSUE TITLE
Deployed but no translation occurring 17.multilingual-conversations

### ISSUE THREAD

**Issue by VanessaOrtiz30** [Microsoft/BotBuilder-Samples#997]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 17.multilingual-conversations

## Describe the bug
So I'm having an issue where my bot runs after 'npm start' I write anything and then it asks me "Choose Your Language:" with the "es" or "en" options. I choose the 'es' for Spanish and then it responds in English "Your current language code is: es" after that it repeatedly asks me "Choose Your Language:". So my question is what might I perhaps be doing wrong? Also, shouldn't the statement "Your current language code is: es" be in Spanish after choosing? Am I perhaps adding the translation keys in the incorrect location (I put it in the .env file)? PLEASE HELP.

## To Reproduce
1. Follow instructions to run the sample and open the emulator.
2. Send es to change user language to Spanish.

## Expected behavior
The statement "Your current language code is: es" should be in Spanish after choosing "es"

## Screenshots
![testingmultilingual bot 2](https://user-images.githubusercontent.com/32853613/49307367-f9f0fe80-f4a2-11e8-847d-6214a6477960.PNG)

[bug]

**Comment by sgellock** [comment]
Support, can you help Vanessa?  thanks

**Comment by jwiley84** [comment]
Hi @VanessaOrtiz30! 

Have you set your translator key in the .env file? This sample should probably have a try/catch for trying to run it without a translator key, but it does not. If you don't have that set, it will simply return the proper phrase (Your current...), but untranslated.

**Comment by jwiley84** [comment]
Hi Vanessa! I'm going to go ahead and close this issue. If you're still having issues with the sample not translating after you've added your translator key, please feel free to comment on this issue again.
